<a href="https://colab.research.google.com/github/hernandezb3/llm-text-classification/blob/main/kylie_replication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATASET Persuade Corpus 2.0

https://www.kaggle.com/datasets/nbroad/persaude-corpus-2
* The PERSUADE 2.0 corpus builds on the PERSUADE 1.0 corpus by providing holistic essay scores to each persuasive essay in the PERSUADE 1.0 corpus as well as proficiency scores for each argumentative and discourse element found in the initial corpus. This version also contains all essays (as compared to 1.0 which linked the training set for the Kaggle competition)

* In total, the PERSUADE 2.0 corpus comprises over 25,000 argumentative essays produced by 6th-12th grade students in the United States for 15 prompts on two writing tasks: independent and source-based writing. The PERSUADE 2.0 corpus provides detailed individual and demographic information for each writer as well as the initial annotations for argumentative and discourse element found PERSUADE 1.0.

Packages
* We are going to use a genAI model as a classifier via prompting then evaluate it against gold human labels
* Aumodelforcausallm

In [ ]:
import os
import re
import pandas as pd
import numpy as np
import torch
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

Kaggle
* PERSUADE 2.0 is a public dataset, and kagglehub can download public datasets anonymously no credentials required.
* kagglehub.dataset_download(...) pulls the dataset from Kaggle and caches it locally, returning the path to that cached copy
*  We are loading one specific file the persuade_2.0_human_scores_demo_id_github.csv into a dataframe

In [ ]:
#load data
import kagglehub

# Download dataset
path = kagglehub.dataset_download("nbroad/persaude-corpus-2")
print("Dataset path:", path)
print("Files:", os.listdir(path))

scores_path = os.path.join(path, "persuade_2.0_human_scores_demo_id_github.csv")
scores = pd.read_csv(scores_path)

print(f"Shape  : {scores.shape}")
print(f"Columns: {scores.columns.tolist()}")
scores.head()

Using Colab cache for faster access to the 'persaude-corpus-2' dataset.
Dataset path: /kaggle/input/persaude-corpus-2
Files: ['persuade_corpus_1.0.csv', 'persuade_2.0_human_scores_demo_id_github.csv', 'sources.csv']
Shape  : (25996, 14)
Columns: ['essay_id_comp', 'full_text', 'holistic_essay_score', 'word_count', 'prompt_name', 'task', 'assignment', 'source_text', 'gender', 'grade_level', 'ell_status', 'race_ethnicity', 'economically_disadvantaged', 'student_disability_status']

,essay_id_comp,full_text,holistic_essay_score,word_count,prompt_name,task,assignment,source_text,gender,grade_level,ell_status,race_ethnicity,economically_disadvantaged,student_disability_status
0,423A1CA112E2,Phones\n\nModern humans today are always on th...,3,378,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN
1,BC75783F96E3,This essay will explain if drivers should or s...,4,432,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN
2,74C8BC7417DE,Driving while the use of cellular devices\n\nT...,2,179,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,F,NaN,NaN,White,NaN,NaN
3,A8445CABFECE,Phones & Driving\n\nDrivers should not be able...,3,221,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN
4,6B4F7A0165B9,Cell Phone Operation While Driving\n\nThe abil...,4,334,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,White,NaN,NaN

In [ ]:
os.listdir(path)

['persuade_corpus_1.0.csv',
 'persuade_2.0_human_scores_demo_id_github.csv',
 'sources.csv']

## Assign Prompt IDS

In [ ]:
#how many prompt topics
prompt_summary = (
    scores.groupby("prompt_name")["holistic_essay_score"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)
prompt_summary["prompt_id"] = ["Prompt " + str(i + 1) for i in range(len(prompt_summary))]

prompt_id_map = prompt_summary.set_index("prompt_name")["prompt_id"].to_dict()
scores["prompt_id"] = scores["prompt_name"].map(prompt_id_map)

print(prompt_summary[["prompt_id", "prompt_name", "holistic_essay_score"]]
      .rename(columns={"holistic_essay_score": "mean_score"})
      .round(2)
      .to_string(index=False))

prompt_id                           prompt_name  mean_score
 Prompt 1                       Summer projects        4.49
 Prompt 2                     Distance learning        4.35
 Prompt 3  Mandatory extracurricular activities        3.85
 Prompt 4                    Phones and driving        3.85
 Prompt 5             Seeking multiple opinions        3.84
 Prompt 6                       Driverless cars        3.15
 Prompt 7                       Car-free cities        3.10
 Prompt 8                 Cell phones at school        3.04
 Prompt 9      Does the electoral college work?        3.00
Prompt 10                      The Face on Mars        2.95
Prompt 11                     Community service        2.93
Prompt 12 Grades for extracurricular activities        2.91
Prompt 13                       Exploring Venus        2.88
Prompt 14           Facial action coding system        2.88
Prompt 15         "A Cowboy Who Rode the Waves"        2.42

## Binary Classification

In [ ]:
# Scores 1 to 3 = Fail (0), Scores 4 to 6 = Pass (1)
PASS_THRESHOLD = 4

def to_binary(score):
    return 1 if score >= PASS_THRESHOLD else 0

In [ ]:
# total sample is 25,000 too many essay
# lets take 340 from each prompt type
sample = (
    pd.concat([
        grp.sample(n=min(340, len(grp)), random_state=42)
        for _, grp in scores.groupby("prompt_name", sort=False)
    ])
    .reset_index(drop=True)
)
sample["binary_score"] = sample["holistic_essay_score"].apply(to_binary)


print(f"Total essays  : {len(sample):,}")
print(f"Unique prompts: {sample['prompt_name'].nunique()}")
print()
print(sample["binary_score"].value_counts().rename({0: "Fail", 1: "Pass"}))

Total essays  : 5,100
Unique prompts: 15

binary_score
Fail    2950
Pass    2150
Name: count, dtype: int64

In [ ]:
#Train/Val/Test

Data Split
*  data split
   * Train is the data the model learns from. Its parameters (weights) are fit to this set. This is for finetuning
   * Validation is a held-out set that the model don't train on, it is used during development to tune things such as learning rate, number of epochs, which model, prompt wording, decision thresholds. It is for adjustment
   * Test is a held-out set, it is only touched once, at the very end, to get an honest estimate of how the model does on data it has never influenced in any way.
* Finetuning overfitting? the thing that causes overfitting is too many epochs on too little data


Sample Size
* Training set if for finetuning... 3000 essays
* not sure sample size here, is 3000 too much for finetuning...

In [ ]:
X = sample.drop(columns=["holistic_essay_score", "binary_score"])
y = sample["binary_score"].copy()          # binary 0/1 instead of 1 to 6, th 1 to 6 was not working at all

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print(f"Train : {len(X_train):,}  ({len(X_train)/len(sample)*100:.1f}%)")
print(f"Val   : {len(X_val):,}   ({len(X_val)/len(sample)*100:.1f}%)")
print(f"Test  : {len(X_test):,}   ({len(X_test)/len(sample)*100:.1f}%)")
print("\nClass distribution (stratification check):")
for name, y_split in [("Train", y_train), ("Val", y_val), ("Test", y_test)]:
    counts = y_split.value_counts().rename({0: "Fail", 1: "Pass"})
    print(f"  {name}: {counts.to_dict()}")

Train : 3,570  (70.0%)
Val   : 765   (15.0%)
Test  : 765   (15.0%)

Class distribution (stratification check):
  Train: {'Fail': 2065, 'Pass': 1505}
  Val: {'Fail': 443, 'Pass': 322}
  Test: {'Fail': 442, 'Pass': 323}

## MODEL INPUT

**Building the Model Prompt**
* generate_prompt: this is to build the prompt and give it to the llm, this include the
    * Instructions
    * Student essay text
    *  essay label of pass/fail

* generate_test_pumpt: here is similar as above but the prompt stops before providing the label, nolabel provided here

train_df
* Here train df gets the generated prmpt with inlcude the full examples with the labels. Now this is the training data that we will feed to a finetuner LoRA as training needs the answer

test_df
* Here test df gets teh generate test prompt as labels are not given. The model nees to predict the essay pass/failing and such predictions will be evaluated against teh y_true (human evaluated gold standard)

In [ ]:
#Prompt generation

def grading_instruction_prompt(row):
    return (
        f"You are an expert essay grader. Read the essay and respond with exactly one word.\n"
        f"Your response must be either the word Fail or Pass. No other words.\n\n"
        f"Rules:\n"
        f"- Fail: the essay is weak, underdeveloped, or below standard\n"
        f"- Pass: the essay is proficient, strong, or excellent\n\n"
        f"Prompt: {row['prompt_name']}\n"
        f"Task: {row['task']}\n"
        f"Essay: {row['full_text']}\n\n"
        f"Respond with one word only (Fail or Pass): "
    )


def make_prompt_completion(row, tokenizer):
    user_content = grading_instruction_prompt(row)   # same wording
    prompt = tokenizer.apply_chat_template(
        [{"role": "user", "content": user_content}],
        tokenize=False, add_generation_prompt=True,
    )
    completion = "Pass" if row["binary_score"] == 1 else "Fail"
    return {"prompt": prompt, "completion": completion}

#Train
train_df = X_train.copy()
train_df["binary_score"] = y_train.values # why does this not get grading_instruction_prompt?

# eval prompt
val_df = X_val.copy()
val_df["binary_score"] = y_val.values
X_val_prompts = pd.DataFrame(val_df.apply(grading_instruction_prompt, axis=1), columns=["text"])

test_df = X_test.copy()
test_df["binary_score"] = y_test.values
y_true = test_df["binary_score"].values
X_test_prompts = pd.DataFrame(test_df.apply(grading_instruction_prompt, axis=1), columns=["text"])

In [ ]:
train_df.sample()

,essay_id_comp,full_text,word_count,prompt_name,task,assignment,source_text,gender,grade_level,ell_status,race_ethnicity,economically_disadvantaged,student_disability_status,prompt_id,binary_score
4990,FC492DC3D1D3,Generic_Name\n\nMr. Generic_Name\n\nEnglish Ho...,302,Seeking multiple opinions,Independent,"When people ask for advice, they sometimes tal...",NaN,M,8.0,No,White,Economically disadvantaged,Identified as having disability,Prompt 5,0

In [ ]:
test_df.sample()

,essay_id_comp,full_text,word_count,prompt_name,task,assignment,source_text,gender,grade_level,ell_status,race_ethnicity,economically_disadvantaged,student_disability_status,prompt_id,binary_score
3712,FF1A49833BFF,Driverless cars may be the future but it would...,345,Driverless cars,Text dependent,"In the article “Driverless Cars are Coming,” t...","""Driverless Cars are Coming""",F,10.0,No,Hispanic/Latino,Economically disadvantaged,Not identified as having disability,Prompt 6,1

In [ ]:
X_val_prompts

                                                   text
1812  You are an expert essay grader. Read the essay...
1955  You are an expert essay grader. Read the essay...
3427  You are an expert essay grader. Read the essay...
3615  You are an expert essay grader. Read the essay...
1184  You are an expert essay grader. Read the essay...
...                                                 ...
484   You are an expert essay grader. Read the essay...
3717  You are an expert essay grader. Read the essay...
1740  You are an expert essay grader. Read the essay...
4092  You are an expert essay grader. Read the essay...
1125  You are an expert essay grader. Read the essay...

[765 rows x 1 columns]

val_df
* X_val_prompt validation data that does not have the labels
* val_df have the labels it got it from  generate prompt

In [ ]:
print(f"Train      : {len(train_df)}")
print(f"Val prompts: {len(X_val_prompts)}")
print(f"Test prompts: {len(X_test_prompts)}")

Train      : 3570
Val prompts: 765
Test prompts: 765

In [ ]:
#balanced for training
fail_df = train_df[train_df["binary_score"] == 0]
pass_df = train_df[train_df["binary_score"] == 1]

train_balanced = pd.concat([
    fail_df.sample(n=len(pass_df), random_state=42),
    pass_df,
]).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Balanced: {train_balanced['binary_score'].value_counts().to_dict()}")

Balanced: {1: 1505, 0: 1505}

In [ ]:
def predict_decoder_only(test, model, tokenizer, verbose=False):
    """Zero-shot or finetuned inference for decoder-only instruct model. So this can
    served tinyllama, gemma, mistral, phi-3.5, qwen2 and llama-3.1 unchanged.

    Why? universal because apply_chat_template emits each model's own markers
    (<|assistant|>, [INST], ChatML, ...)
    The slice exists because decoder-only output = prompt + answer in one stream.

    Returns (y_pred, y_generated): 1=Pass, 0=Fail, -1=unparseable.
    Many -1s = the format/extraction is wrong, not the model."""
    y_pred      = []
    y_generated = []

    model.eval()   # disable training-only behavior (dropout)

    # pad token dedicated pad if the model has one,
    # else EOS (first element if EOS is a list, e.g. Gemma's [1, 107])
    pad_id = tokenizer.pad_token_id
    if pad_id is None:
        eos = tokenizer.eos_token_id
        pad_id = eos[0] if isinstance(eos, list) else eos

    for i in tqdm(range(len(test))):

        # wrap the prompt in this model's chat format
        messages = [{"role": "user", "content": test.iloc[i]["text"]}]
        prompt = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True,
        )

        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=4096,   # OOM guard, not a constraint...prompts run ~700-900 tokens,
                               # (Real ceiling per model:
                               # look into model.config.max_position_embeddings.)
            padding=False,     # one essay at a time, nothing to pad against right now
        ).to(model.device)

        # decoder-only models return input + answer together
        # remember the input length so we can cut the prompt back off
        input_len = inputs["input_ids"].shape[1]

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=10,     # we only need one word ("Pass"/"Fail")
                do_sample=False,       # greedy = deterministic = reproducible
                pad_token_id=pad_id,
                use_cache=False,       # kept off since the Phi remote-code cache bug errors
                                       # harmless for native classes at 10 new tokens
            )

        # keep only what the model added, after the prompt
        new_tokens = outputs[0][input_len:]
        generated = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()
        y_generated.append(generated)

        # parse: contains "pass" -> 1, "fail" -> 0, neither -> -1 (unparseable)
        if   "pass" in generated: y_pred.append(1)
        elif "fail" in generated: y_pred.append(0)
        else:                     y_pred.append(-1)

        if verbose:
            print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {y_pred[-1]}")

    return y_pred, y_generated

# THE MODELS INFO

### **Tokenizer info**

AutoTokenizer loads the tokenizer that matches a model
1. Text ↔ token IDs: As we know models dont see words. They see ID numbers from fixed vocabulary

AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
* The tokenizer is the model's dictionary (Language)
* downloads (or reads) the tokenizer files from that Hub repo related to that specific model (the vocabulary and merge rules)
* tokenizer_config.json (settings, special tokens, and the chat template if the model has one).


The tokenizer and model are inseparable partners
* The model's embedding table has exactly one row per vocabulary entry. Encode with the wrong tokenizer and ID 8241 points at a different word than the model thinks (complete chaos)

### **Padding info**
What is padding? T-T

I guess it is about filling extra space like placeholders tokens because we need that every sequence in a batch ends up with the same length
 * This is for processing GPU process barches as rectangular grids of numbers can not handle rows with different lengths in a single batch, like matrices calculations

GPU needs every sequence of token lenght to be the same lenght. But lets say essays are of different lenghts.
 * Essay A: "I think cars ar bad."
    * 6 tokens

 * Essay B: "Online school is great."
    * 5 tokens

To Batch, the model will need to pad to length 6
(so we need to padding, this is what i understands)
- Essay A: [i] [think] [cars] [are] [bad] [.]

- Essay B: [online] [school] [is] [great] [.] [PAD]

So now that these are all the same length, they can be stacked into one tensor the GPU can process in parallel. Also, i need to remember that pad has no meeaning when we mask it looks something lik
- Essay 1 input: [I] [like] [cars] [.] [PAD] [PAD]

- Essay 1 input: 1 1 1 1 0 0

(The masking allow the model to ignore the padded positions when computing attention and loss)

### **Model Architecture**
There are three classic families of transformer architecture
1. Encoder only (BERT, RoBERT, DeBERTa)
   * It ingests/reads the whole input at once and builds a representation of it, but it doesn't generate text. Like embeddings, in another project I feed essays to a BERT model and it returned the essays embedding (this was a BERTembedding model)
   * bidirectional attention layers, every tokens can see each other, left and right
2. Decoder only (GPT, Llama, Mistral, TinyLlama, Qwen, Phi)
   * Read input and continues the text, so output = prompt + answer
   * causal left attention, each token see only the token before it, that why instructions, prompt and answer are like glued together, what we are calling the answer/label token is the later position in the left to right sequence
3. Encoder/decoder seq2seq (T5, BART)
   * Encoder/decoder is for transformation tasks such as translations, summarization, input and output are different objects.
   * bidirectional attention layers. Fully reads read input, the a casual layer decoder generates the output.

BUT wait there is more...
* These architecture are different from the model specified training such as...
   * Based Model???: a base model is trained on predicting the text token across a huge pile of text (usually internet). Good at continuation
   * Instruct models???: Takes the based models and these get an extra round of training of millions of dialogue, instructions-->good response
      * like dialogue pair, here each model...wait for it...develop their own MARKER token....so what is a Marker tokennnnnnnnnnnnnn (see more below of course)
      * So, instruct models specify on a dialogue behavior. They starts as base model given additional training to follow instructions and respond as a helpful assistant, rather than just continue text
        * when they see a instruction in the EXPECTED FORMAT it recognizes the instruction and produce a response

Why do we have to know all of the above??
* because of errors..............

### **Code explanation**


**Model Tasks**
* .from_pretrained() method, we use it to load the model weighits
* AutoModelFor...class name to get the import. Now, which model weight??????
    * AutoModelForCausalLM.from_pretrained()
         * decoder only model = output prompt + continuation
   * AutoModelForSequenceClassification()
     * encoder only, the outputs is the label

  * AutoModelForSeq2SeqLM()
    * encoder/decoder, translation, summary and so on
      * outputs the generated text only

**Pad and eos**
  * **tokenizer.eos_token_id **refers to the End Of Sequence token. Its job is to signal "the text is finished." The model emits it to say "I'm done"
    * Do no confuse this with marker tokens, marker token refers to th structural tokens that labels who is talking. This is about Who is talking
      * <|user|>, <|assistant|>, [INST], <start_of_turn>user, <start_of_turn>model
      * OES is different type of tokens whose jobs is to signal "the text is finished, like saying im done

  * **tokenizer.pad_token_id** refers to the padding token. Its job is to fill empty space so multiple sequences of different lengths can be stacked into one rectangular tensor for batching. We are not batching but this is very important

So,
* tokenizer.pad_token = tokenizer.eos_token
   * set the pad and token to be the same value
   * some models doesnt come with a pad token, but they have to come with eos
    * in this case it doesnt matter which we passed to the generate()
    * generate() pad_token_id argument wants a single integer
EOS marks the end of real content, PAD is fake content added to line things up.

**Model Computation**

* Model computation are done using floating-point numbers
The precision of these number impact how accurately the model performs in different task such as training and inferences.
* Floating Point Representation: Mantissa, Exponent, and Sign. A floating-point number is made up of three parts:     
    * The mantissa
      * Mantissa: fraction significant digits more bits allocated here more accurate the number
    * The exponent
      * Exponent the scale or range of the number, how far left or right it should be
    * The sign bit
      * the number sign, a whole bit just dedicated to know if the number is positive or negative, idk why this is important

**dtype nightmares**
* So torch dtype is the numeric precision of the models weights. This is just one line of code but i do argue is the most or one of the most important part to understands.
  * **FP32 (32-bit floating point):** This is the standard data type for many machine learning applications. It provides high precision, with 23 bits for the mantissa and 8 as exponent. However, the high precision comes at the cost of large memory usage and slower computations.
    * PLEASE know we can do float 32 because this is a very very small model
    
  * **FP16 (16-bit Floating Point)**: This is a compromise between speed and accuracy. It reduces memory usage and speeds up computations but sacrifices some precision.
    * For bigger models I use this OR wait for it....yess quantization...

  * **Bfloat16 (Brain Floating Point)**: This is a more recent development designed for deep learning tasks. It has 8 exponent bits but 7 mantissa bits. It keeps the exponent size from FP32 but reduces the mantissa size. Bfloat16 maintains the dynamic range of FP32, making it  useful for training large models, though it still comes with the trade-off of needing specialized hardware and being more expensive than lower-precision types like FP16.
    * ERROR: cannot use bf15 with T4 or even L4 GPU, to use bf16 the newer gpu are needed like A100... (dont want to talk about gpu....)

### **Tinyllama model 1.1B**

In [ ]:
# This is model loading
# LOCAL: TinyLlama 1.1B, CPU, PLEASE know that there is NO quantization happening here right now
base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0" #not working all pssed all faild
#based_model = "google/flan-t5-base" #250m maybe less biased

#convert text into numbers, tokenIDs that the model understands
#every model have their own matching tokenizer
tokenizer = AutoTokenizer.from_pretrained(base_model) #this is our tokenizer

#this is about padding [PAD]
#each model has a dedicated PAD only and  <EOS> end of sequence token!! (separate)
tokenizer.pad_token = tokenizer.eos_token

#where the padding goes
# to the left for inferences
tokenizer.padding_side = "left"

#auto.. to call a causal language model a model that predicts th next token
#from_pretrained, downloads the pretrained weights for th model
model = AutoModelForCausalLM.from_pretrained(   # remember this is from huggingface to call the model
    base_model,                      # the name of the model
    torch_dtype=torch.float32,       # float32 for CPU stability, T-T every important
                                     # we are controlling hte precision of the loaded weights
                                     # float 16 halves memory usage compared to float32
                                     # GPU T4 does not support bfloat16
    device_map="auto",               # auto tells hf to decide on the avaliable resources: in our case: change "cpu" to "auto" so T4 GPU is used
)

#model and tokenizer aggreement, they need to speack the same language
model.config.pad_token_id = tokenizer.eos_token_id #

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
# helpful info if you want to complicate your life more
print(model)
# what element i would lookhere the attention layers
# the max features here is 2048, this is important to know see below

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 2048)
    (layers): ModuleList(
      (0-21): 22 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=256, bias=False)
          (v_proj): Linear(in_features=2048, out_features=256, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=2048, out_features=5632, bias=False)
          (up_proj): Linear(in_features=2048, out_features=5632, bias=False)
          (down_proj): Linear(in_features=5632, out_features=2048, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((2048,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=2048, out_features=32000, bias=False)
)

In [ ]:
print(model.config)
#here i will check dtype if quant worked it showed here

LlamaConfig {
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "dtype": "float32",
  "eos_token_id": 2,
  "head_dim": 64,
  "hidden_act": "silu",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 5632,
  "max_position_embeddings": 2048,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 22,
  "num_key_value_heads": 4,
  "pad_token_id": 2,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_parameters": {
    "rope_theta": 10000.0,
    "rope_type": "default"
  },
  "tie_word_embeddings": false,
  "transformers_version": "5.13.1",
  "use_cache": true,
  "vocab_size": 32000
}

In [ ]:
print(model.get_memory_footprint() / 1e9, "GB")
#model size

4.400193792 GB

In [ ]:
print("Model loaded on:", next(model.parameters()).device)
print("Vocab size     :", len(tokenizer))
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

# Sanity check: confirm pass/fail tokens exist in vocabular
pass_id = tokenizer.encode("Pass", add_special_tokens=False)
fail_id = tokenizer.encode("Fail", add_special_tokens=False)
print(f"\nToken check:")
print(f"  'Pass'  token id(s): {pass_id}")
print(f"  'Fail'  token id(s): {fail_id}")

Model loaded on: cpu
Vocab size     : 32000
Memory (MB)    : 4400.2

Token check:
  'Pass'  token id(s): [6978]
  'Fail'  token id(s): [29098]

## Chat Format
* No idea how to call this section

### **Models Marker Tokens**
* Models need their specified FORMAT, if you want to talk to them of course. So, if they want you to call them Sir thats how you need to address them. This is all related to MARKER tokens. Lets put more seasoning...

**LLM text-Completer**
at the lowest level, every causal LM (Phi-2, Mistral, Llama, GPT) does exactly something like given some text, predict the next token
   * If we as the user feed a model this

```
The capital of DR is
```
* It continues "Santo Domingo" not because it is answering but because "Santo Domingo" is the statistically most likely continuation

SPECIAL MARKERS TOKENS

**LLM:Instruct Models** like Mistral-7B Instruct, Llama-3-Instruct and every chat assistant starts as a base model, then it get extra round of training on thousands of formatted dialogues (repetition is good for learning, read that again)

```
user message-->assistant response, user message-->assistant response
```
BUT the models see a flat stream of tokens , it/they? doesnt know where the user turn ends and its own begins. So, we need **"Special Marker Tokens"** inserted around each turn during that training. Different models have different markers.

    * Mistral's markers tokens
       - <s>[INST] Classify this essay as Pass or Fail. Essay: ... [/INST]
       - During instruct-training, the model saw millions of examples where the text after [/INST] was a helpful assistant response. So it learned the association: "when I see [/INST], what follows is my answer"

    * llama 3 Instruct
      - <|begin_of_text|><|start_header_id|>user<|end_header_id|>Grade this essay. Essay: ...<|eot_id|><|start_header_id|>assistant<|end_header_id|>Pass<|eot_id|>


    * ChatML (use by Qwen)
     - <|im_start|>user
       Grade this essay. Essay: ...<|im_end|>
       <|im_start|>assistant
       Pass<|im_end|>

So
1. Feed an instruct model its expected format, and it behaves like an assistant.
2. But know that special marker tokens are arbitraty and every model has different one.
   * Use the wrong format on the wrong model and things degrade quietly: the model half-recognizes the structure, output quality drops, and nothing errors out to tell whyyyyyyyyyyyyyyyy.

So,

Do we need to memorize every format (T-T, crying face), the answer is no (:D). Hugging Face stores each model's format inside its tokenizer as a template that we can use for most models (a Jinja string in tokenizer_config.json). We have to write the conversation in a universal shape:
```
messages = [{"role": "user", "content": "Grade this essay. Essay: ..."}]

prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

# add_generation_prompt=True appends the assistant-turn opener,
# so the model's next tokens ARE the assistant's reply
```

Messages is in the standard format, then, **apply_chat_template** renders it into that model's markers
  * The add_generation_prompt=True flag appends the "your turn now" model marker
  * if a model does not have have a chat template it will only have \nAnswer:

So, (my last So)
 "role": "user" labels who is speaking in that turn of the conversation, while "content" is the message itself.

 A conversation is a list of these dicts


```
messages = [
    {"role": "system",    "content": "You are a strict essay grader."},   # setup/instructions
    {"role": "user",      "content": "Grade this essay: ..."},            # the human
    {"role": "assistant", "content": "Pass"},                             # the model
    {"role": "user",      "content": "Are you sure? It's quite short."},  # human again
]
```

The main three roles:
* User is the human's turns (requests, questions)
* Assistant is the model's turns (its previous answers), the model needs to identify its own answer
* System is optional first message with standing instructions/persona; not part of the back-and-forth, more like stage directions

**BUT WAIT there is more!!**

**OUTPUT FORMAT**
...T_T...

## **Extracting the output**

Different models have different ways to hand back their output, so we need to know the model type to know where to reach for the answer. T-T ...let's put
some more seasoning on all of this.

Remember model types?? yes me either...

This comes straight from the architecture,
i.e. **where the answer starts**:

* **Decoder only Models** (Llama, GPT, Mistral, TinyLlama):
   * One single stream token after tokenm the model just continues the text.
   * So the answer starts **at the end of the prompt**, glued on.
   * `output[0]` = the **entire prompt + the answer**.
      * So we must **slice off the input** first: `output[0][input_len:]`,
      * if no, we decode the whole essay back and the "pass"/"fail" check matches a word inside the essay, not the model's actual answer...yes easy peasy...

* **Encoder/decoder** Models (T5, BART, FLAN-T5):
   * Remember here, two components the encoder reads the input, a separate decoder writes.
   * So the answer starts fresh, the input never appears in the output.
   * `output[0]` = **only the newly generated text** decode it directly, no need for slicing.


**Why I care about this**
* Because it bit me T-T
* I was getting `-1`s in `y_pred` and a classification report that made no sense
   * That `-1` is my "unparseable" bucket fires when the decoded text contains neither "pass" nor "fail". And a pile of `-1`s is almost always the extraction going wrong for exactly the reason above: if I forget to slice off the prompt on a decoder-only model, I'm scanning the whole essay text instead of the shortanswer,
   * So the parse is unreliable and the metrics go haywire.
   * Problems with prompt echo, model just echoing back the prompt, or parroting the text rules
     * Instead the generated output extracting is checkking the first match, but the first  match is the model repeating the prompt not answering it

So we need to match the extraction to the architecture. `-1`s aren't "the model
is bad", it is can be that I'm reading the output from the wrong place.

(That is.... help! send a search party with a helicopter and half the state troopers; I am so lost, and we havent even start with quantization T-T)

#### **Testing llama function**

**Explain the code**

* **max_lenghth = 2048** or lower,  this is the ceiling
  * This is the model context windown, related to the max number of tokens the model can pay attention to in one sequence
     * TinyLlama was pretrained, it learned positional embeddings, the model needs to know where each token sits in the sequence (position 1, position 2, ... position 2048)
     * It has no learned representation for position 2048 and beyond
  * This include the total input+output= these cannot passed 2048 tokens
    * This is importnat this 2048 has to cover instructions+essay + everything. So need to estimate like how long are the essay, the instructions, and the expected llm output
      * It has to be within the model max_lenghth
  * This is also do get data truncated, increasing this number beyond the model max makes the model instable
  * check the output and maybe lets check how many essay exceed teh 2000 tokens

In [ ]:
def count_tokens(text):
    return len(tokenizer.encode(text, add_special_tokens=False))

X_test_prompts["prompt_tokens"] = X_test_prompts["text"].apply(count_tokens)

print(X_test_prompts["prompt_tokens"].describe())
print("\nlongest prompt :", X_test_prompts["prompt_tokens"].max(), "tokens")
print("over 2048      :", (X_test_prompts["prompt_tokens"] > 2048).sum())

count     765.000000
mean      617.181699
std       221.770764
min       281.000000
25%       450.000000
50%       585.000000
75%       742.000000
max      1570.000000
Name: prompt_tokens, dtype: float64

longest prompt : 1570 tokens
over 2048      : 0

Keep in mind that to this we need to add the model response
  * In our case we put nes tokens to 10 so we still are within the max_token

In [ ]:
# Length of just the essay
test_df["essay_tokens"] = test_df["full_text"].apply(count_tokens)
print(test_df["essay_tokens"].describe())

count     765.000000
mean      509.815686
std       222.078629
min       173.000000
25%       343.000000
50%       478.000000
75%       634.000000
max      1462.000000
Name: essay_tokens, dtype: float64

In [ ]:
#deciding where to slide the prompt and teh llm answer, easy...
print(repr(X_test_prompts.iloc[0]["text"]))

"You are an expert essay grader. Read the essay and respond with exactly one word.\nYour response must be either the word Fail or Pass. No other words.\n\nRules:\n- Fail: the essay is weak, underdeveloped, or below standard\n- Pass: the essay is proficient, strong, or excellent\n\nPrompt: Cell phones at school\nTask: Independent\nEssay: I think policy 1 is better because some students need their phones for important things. They should let everyone do that because not all students will call someone while they are at school because it is not appropriate. I think that my principal should give us a try just for one day to see how it would turn out but if we do good then we could do it as a privilege but if we are really bad then we could go back to the rule where we cant bring them. The only time that they wont be able to use them during class because we need to pay attention in class to do good on the TAKS test. I think that it would get the children to behave more so that they could use their phones on their free times. If it doesn't I don't know what will because I know that I would always do good with or without it. Sometimes that is what it takes to make them act better to reward them with things that will make them want to behave in class and in the hallways.\n\nI think that the only reason they act bad at times is because they are bored and have nothing else to do. If I were a principal I would try it to see how things change if it makes great changes I would keep it that way, but if it is worse then i would change the rule back and they wont be able to bring them at all. I would hope and pray that it would work out well and not get worser than what it is. I like to see people happy because it makes me feel happy inside and out too. So, please, please, please give us a shot at it!!! But if you don't I understand that it is your decision because you don't want to take any chances just incase it gets worse but it would be very nice of you if you did.\n\nRespond with one word only (Fail or Pass): "

One essay at a time
* The loop processes one index per iteration
  *  for i in tqdm(range(len(test)))
  *  test.iloc[i], the [i] picks out exactly one row
  *  Padding False

In [ ]:
# Quick zero-shot check on 50 VAL essays (test stays sealed for final numbers)
val_sample   = X_val_prompts.iloc[:50].reset_index(drop=True)
y_val_sample = y_val.values[:50]

y_pred, y_generated = predict_decoder_only(val_sample,
                                           model,
                                           tokenizer, verbose=True)

  0%|          | 0/50 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 1/50 [00:55<45:11, 55.34s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  1/50]  raw='pass'  →  1

  4%|▍         | 2/50 [04:05<1:47:39, 134.58s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  2/50]  raw='pass: venus is a fascinating planet'  →  1

  6%|▌         | 3/50 [08:35<2:34:03, 196.66s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  3/50]  raw='pass: driverless cars can be safe as well'  →  1

  8%|▊         | 4/50 [09:01<1:39:03, 129.21s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  4/50]  raw='pass'  →  1

 10%|█         | 5/50 [09:28<1:09:19, 92.44s/it] [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  5/50]  raw='pass'  →  1

 12%|█▏        | 6/50 [10:26<59:05, 80.57s/it]  [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  6/50]  raw='pass'  →  1

 14%|█▍        | 7/50 [13:23<1:20:23, 112.16s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  7/50]  raw='pass: the essay is proficient,'  →  1

 16%|█▌        | 8/50 [17:28<1:48:06, 154.45s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  8/50]  raw='pass: phones and driving'  →  1

 18%|█▊        | 9/50 [17:53<1:17:51, 113.93s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  9/50]  raw='pass'  →  1

 20%|██        | 10/50 [18:57<1:05:39, 98.49s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 10/50]  raw='pass'  →  1

 22%|██▏       | 11/50 [19:21<49:18, 75.85s/it]  [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 11/50]  raw='pass'  →  1

 24%|██▍       | 12/50 [20:04<41:41, 65.82s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 12/50]  raw='pass'  →  1

 26%|██▌       | 13/50 [20:44<35:38, 57.81s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 13/50]  raw='pass'  →  1

 28%|██▊       | 14/50 [21:13<29:26, 49.06s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 14/50]  raw='pass'  →  1

 30%|███       | 15/50 [21:43<25:18, 43.38s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 15/50]  raw='pass'  →  1

 32%|███▏      | 16/50 [22:14<22:32, 39.78s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 16/50]  raw='pass'  →  1

 34%|███▍      | 17/50 [23:14<25:10, 45.76s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 17/50]  raw='pass'  →  1

 36%|███▌      | 18/50 [23:52<23:08, 43.40s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 18/50]  raw='pass'  →  1

 38%|███▊      | 19/50 [24:25<20:54, 40.46s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 19/50]  raw='pass'  →  1

 40%|████      | 20/50 [26:32<33:08, 66.28s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 20/50]  raw='pass: fail'  →  1

 42%|████▏     | 21/50 [27:26<30:17, 62.68s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 21/50]  raw='pass'  →  1

 44%|████▍     | 22/50 [27:54<24:24, 52.29s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 22/50]  raw='pass'  →  1

 46%|████▌     | 23/50 [28:36<22:10, 49.28s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 23/50]  raw='pass'  →  1

 48%|████▊     | 24/50 [29:05<18:41, 43.12s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 24/50]  raw='pass'  →  1

 50%|█████     | 25/50 [30:04<19:54, 47.79s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 25/50]  raw='pass'  →  1

 52%|█████▏    | 26/50 [31:01<20:12, 50.52s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 26/50]  raw='pass'  →  1

 54%|█████▍    | 27/50 [31:25<16:21, 42.69s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 27/50]  raw='pass'  →  1

 56%|█████▌    | 28/50 [31:51<13:49, 37.72s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 28/50]  raw='pass'  →  1

 58%|█████▊    | 29/50 [32:22<12:29, 35.71s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 29/50]  raw='pass'  →  1

 60%|██████    | 30/50 [33:08<12:56, 38.81s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 30/50]  raw='pass'  →  1

 62%|██████▏   | 31/50 [34:04<13:51, 43.75s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 31/50]  raw='pass'  →  1

 64%|██████▍   | 32/50 [34:27<11:19, 37.75s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 32/50]  raw='pass'  →  1

 66%|██████▌   | 33/50 [35:17<11:40, 41.21s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 33/50]  raw='pass'  →  1

 68%|██████▊   | 34/50 [36:54<15:26, 57.93s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 34/50]  raw='pass'  →  1

 70%|███████   | 35/50 [37:21<12:11, 48.79s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 35/50]  raw='pass'  →  1

 72%|███████▏  | 36/50 [37:49<09:57, 42.65s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 36/50]  raw='pass'  →  1

 74%|███████▍  | 37/50 [38:32<09:12, 42.50s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 37/50]  raw='pass'  →  1

 76%|███████▌  | 38/50 [39:09<08:13, 41.12s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 38/50]  raw='fail'  →  0

 78%|███████▊  | 39/50 [39:48<07:25, 40.48s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 39/50]  raw='pass'  →  1

 80%|████████  | 40/50 [40:23<06:27, 38.76s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 40/50]  raw='pass'  →  1

 82%|████████▏ | 41/50 [47:31<23:19, 155.55s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 41/50]  raw='pass: join us on the high stormy'  →  1

 84%|████████▍ | 42/50 [48:00<15:40, 117.59s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 42/50]  raw='pass'  →  1

 86%|████████▌ | 43/50 [48:23<10:23, 89.10s/it] [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 43/50]  raw='pass'  →  1

 88%|████████▊ | 44/50 [49:27<08:09, 81.56s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 44/50]  raw='pass'  →  1

 90%|█████████ | 45/50 [49:53<05:24, 64.95s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 45/50]  raw='pass'  →  1

 92%|█████████▏| 46/50 [52:33<06:14, 93.56s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 46/50]  raw='pass: cell phones at school'  →  1

 94%|█████████▍| 47/50 [53:15<03:53, 77.99s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 47/50]  raw='pass'  →  1

 96%|█████████▌| 48/50 [53:41<02:04, 62.39s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 48/50]  raw='pass'  →  1

 98%|█████████▊| 49/50 [54:19<00:55, 55.08s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 49/50]  raw='fail'  →  0

100%|██████████| 50/50 [54:47<00:00, 65.75s/it]

[ 50/50]  raw='pass'  →  1

In [ ]:
# ── Evaluate against VAL labels ──
assert len(y_pred) == len(y_val_sample)

# drop unparseable (-1) predictions
valid = [i for i, p in enumerate(y_pred) if p != -1]
yt = y_val_sample[valid]
yp = [y_pred[i] for i in valid]

print(f"Parsed: {len(valid)}/{len(y_pred)}")
print(f"Accuracy: {accuracy_score(yt, yp):.4f}")
print(classification_report(yt, yp, target_names=["Fail", "Pass"], zero_division=0))
print(confusion_matrix(yt, yp))
print(f"Predicted-Pass fraction: {(pd.Series(yp)==1).mean():.3f}  (true rate: {(pd.Series(yt)==1).mean():.3f})")

Parsed: 50/50
Accuracy: 0.3400
              precision    recall  f1-score   support

        Fail       0.50      0.03      0.06        33
        Pass       0.33      0.94      0.49        17

    accuracy                           0.34        50
   macro avg       0.42      0.49      0.27        50
weighted avg       0.44      0.34      0.21        50

[[ 1 32]
 [ 1 16]]
Predicted-Pass fraction: 0.960  (true rate: 0.340)

Results
* This model 1.1B model can't do this task....

In [ ]:
# predict on first 10 test essays only
test_sample = X_test_prompts.iloc[:50].reset_index(drop=True)
y_true_sample = y_true[:50]          #  this is what was missing

y_pred, y_generated = predict_decoder_only(test_sample, model, tokenizer)

  0%|          | 0/50 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 1/50 [00:34<28:33, 34.98s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 2/50 [01:15<30:33, 38.19s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▌         | 3/50 [01:48<28:12, 36.01s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 4/50 [03:58<55:48, 72.79s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 5/50 [04:19<40:41, 54.26s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 6/50 [04:55<35:12, 48.01s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 7/50 [05:47<35:30, 49.54s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 8/50 [06:28<32:40, 46.69s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 9/50 [08:40<50:01, 73.20s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 10/50 [09:02<38:19, 57.48s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 11/50 [09:41<33:38, 51.76s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 12/50 [10:44<34:55, 55.16s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 13/50 [13:03<49:48, 80.77s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 14/50 [13:48<41:53, 69.82s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 15/50 [14:25<34:59, 59.99s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 16/50 [15:14<32:04, 56.59s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▍      | 17/50 [15:54<28:24, 51.65s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 18/50 [16:52<28:37, 53.68s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 19/50 [17:20<23:45, 45.99s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 20/50 [21:59<57:56, 115.89s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 21/50 [22:27<43:14, 89.47s/it] [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 22/50 [22:56<33:14, 71.22s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 23/50 [23:22<26:02, 57.89s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 24/50 [29:12<1:03:01, 145.43s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|█████     | 25/50 [30:02<48:38, 116.75s/it]  [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 26/50 [30:37<36:53, 92.21s/it] [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 27/50 [31:06<28:07, 73.37s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 28/50 [33:42<35:55, 97.96s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 29/50 [34:22<28:15, 80.72s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|██████    | 30/50 [35:01<22:40, 68.05s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 31/50 [35:42<19:00, 60.03s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▍   | 32/50 [36:15<15:34, 51.94s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▌   | 33/50 [42:10<40:28, 142.86s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 68%|██████▊   | 34/50 [42:43<29:18, 109.88s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 70%|███████   | 35/50 [43:16<21:42, 86.84s/it] [transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 72%|███████▏  | 36/50 [43:56<16:57, 72.65s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 74%|███████▍  | 37/50 [44:38<13:48, 63.71s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 76%|███████▌  | 38/50 [45:20<11:23, 56.98s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 78%|███████▊  | 39/50 [46:12<10:11, 55.58s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 80%|████████  | 40/50 [47:14<09:35, 57.52s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 82%|████████▏ | 41/50 [54:43<26:13, 174.89s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 84%|████████▍ | 42/50 [55:30<18:13, 136.66s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 86%|████████▌ | 43/50 [55:55<12:02, 103.16s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 88%|████████▊ | 44/50 [59:25<13:31, 135.28s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 90%|█████████ | 45/50 [59:48<08:27, 101.48s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 92%|█████████▏| 46/50 [1:00:28<05:32, 83.15s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 94%|█████████▍| 47/50 [1:01:07<03:29, 69.82s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 96%|█████████▌| 48/50 [1:01:51<02:03, 61.88s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 98%|█████████▊| 49/50 [1:02:25<00:53, 53.60s/it][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
100%|██████████| 50/50 [1:03:16<00:00, 75.93s/it]

In [ ]:
results_df = pd.DataFrame({
    "y_true"    : y_true_sample,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true_sample[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    labels = [0, 1]
    target_names = ["Fail", "Pass"]
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print("\nClassification Report:")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=labels, target_names=target_names, zero_division=0
    ))
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=labels)
    for label, row in zip(target_names, cm):
        print(f"True {label:<5}: {row}")
else:
    print("No valid predictions to evaluate.")

    y_true  y_pred                                          generated y_true_label y_pred_label
0        0       1                                               pass         Fail         Pass
1        0       1                                               pass         Fail         Pass
2        0       1                                               pass         Fail         Pass
3        1       1                                         pass: fail         Pass         Pass
4        0       1                                               pass         Fail         Pass
5        0       1                                               pass         Fail         Pass
6        1       1                                               pass         Pass         Pass
7        1       0                                               fail         Pass         Fail
8        1       1                                         pass: fail         Pass         Pass
9        0       1                                               pass         Fail         Pass
10       0       1                                               pass         Fail         Pass
11       1       1                                               pass         Pass         Pass
12       1       1                           pass: distracted driving         Pass         Pass
13       1       1                                               pass         Pass         Pass
14       1       1                                               pass         Pass         Pass
15       1       1                                               pass         Pass         Pass
16       1       1                                               pass         Pass         Pass
17       1       1                                               pass         Pass         Pass
18       0       1                                               pass         Fail         Pass
19       0       1                              pass: car-free cities         Fail         Pass
20       0       1                                               pass         Fail         Pass
21       0       1                                               pass         Fail         Pass
22       0       1                                               pass         Fail         Pass
23       1       1          pass: driverless cars are impractical and         Pass         Pass
24       1       1                                               pass         Pass         Pass
25       1       0                                               fail         Pass         Fail
26       0       1                                               pass         Fail         Pass
27       1       1                        pass: cell phones at school         Pass         Pass
28       1       1                                               pass         Pass         Pass
29       0       1                                               pass         Fail         Pass
30       1       1                                               pass         Pass         Pass
31       0       1                                               pass         Fail         Pass
32       1       1                     pass: the essay is proficient,         Pass         Pass
33       0       1                                               pass         Fail         Pass
34       0       1                                               pass         Fail         Pass
35       1       1                                               pass         Pass         Pass
36       1       1                                               pass         Pass         Pass
37       0       1                                               pass         Fail         Pass
38       1       1                                               pass         Pass         Pass
39       1       1                                               pass         Pass         Pass
40       1       1  pass: online schooling is beneficial for students         Pass         Pass
41       0       1                                               pass         Fail         Pass
42       0       1                                               pass         Fail         Pass
43       1       1    pass: cellular devices should not be used while         Pass         Pass
44       0       1                                               pass         Fail         Pass
45       0       1                                               pass         Fail         Pass
46       0       1                                               pass         Fail         Pass
47       1       1                                               pass         Pass         Pass
48       0       1                                               pass         Fail         Pass
49       1       1                                               pass         Pass         Pass

Parsed      : 50/50
Unparseable : 0

Accuracy : 0.4800

Classification Report:
              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00        24
        Pass       0.50      0.92      0.65        26

    accuracy                           0.48        50
   macro avg       0.25      0.46      0.32        50
weighted avg       0.26      0.48      0.34        50

Confusion Matrix (rows=true, cols=pred):
           Fail  Pass
True Fail : [ 0 24]
True Pass : [ 2 24]

### Finetuning

In [ ]:
# TinyLlama loading A100 GPUedition
base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token     # TinyLlama: no dedicated pad alias eos (correct here)
tokenizer.padding_side = "right"              # training mode (left for inference later)

model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype=torch.bfloat16,   # A100 GPU, fp32 was the CPU setting
    device_map="auto",
)
model.config.pad_token_id = tokenizer.eos_token_id
model.config.use_cache = False

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training
!pip install trl
from trl import SFTTrainer, SFTConfig
import torch

Collecting trl
  Downloading trl-1.9.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cpu)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)
Downloading trl-1.9.2-py3-none-any.whl (889 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 889.0/889.0 kB 11.9 MB/s eta 0:00:0000:0100:01
Downloading datasets-5.0.1-py3-none-any.whl (559 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 24.9 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 9.1 MB/s eta 0:00:00:00:0100:01m
Installing collected packages: pyarrow, datasets, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.1 pyarrow-25.0.0 trl-1.9.2

RuntimeError: Failed to import trl.trainer.sft_trainer because of the following error (look up to see its traceback):
pyarrow.lib.IpcReadOptions size changed, may indicate binary incompatibility. Expected 112 from C header, got 104 from PyObject

In [ ]:
lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05, bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
)

In [ ]:
from datasets import Dataset

In [ ]:
train_hf = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in train_balanced.iterrows()])
val_hf   = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in val_df.iterrows()])
print(repr(train_hf[0]["prompt"][-70:]))   # want TinyLlama/Zephyr style: ...</s>\n<|assistant|>\n

'T_NAME\n\nRespond with one word only (Fail or Pass): </s>\n<|assistant|>\n'

In [ ]:
!pip install -U torchao

Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (0.10.0)
Collecting torchao
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 105.3 MB/s eta 0:00:00
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.17.0

In [ ]:
#A100 GPU
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()          # trainable parameters

sft_config = SFTConfig(
    output_dir="./tinyllama-lora-balanced",
    num_train_epochs=1,
    per_device_train_batch_size=16,          # 1.1B on 80GB go big or go home
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=1,           # effective batch = 16
    warmup_steps=50,
    learning_rate=2e-4,                      # standard LoRA rate; small models tolerate it
    max_grad_norm=0.3,
    fp16=False, bf16=True,                   # A100: bf16, only bf16=True with a100 GPU!
    logging_steps=10,
    eval_strategy="steps", eval_steps=50,
    save_strategy="steps", save_steps=50,
    load_best_model_at_end=True, metric_for_best_model="eval_loss",
    report_to="none",
    max_length=2000,                         # TinyLlama's real ceiling is 2048, remember!
    completion_only_loss=True,
    optim="adamw_torch",                     # no memory pressure today we rich
)

trainer = SFTTrainer(
    model=model, args=sft_config,
    train_dataset=train_hf,
    eval_dataset=val_hf.select(range(250)),
    processing_class=tokenizer,
)
trainer.train()

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

trainable params: 12,615,680 || all params: 1,112,664,064 || trainable%: 1.1338

Adding EOS to train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (2212 > 2048). Running this sequence through the model will result in indexing errors

Building labels for train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.

TrainOutput(global_step=188, training_loss=0.21723561718108805, metrics={'train_runtime': 360.0249, 'train_samples_per_second': 8.352, 'train_steps_per_second': 0.522, 'total_flos': 2.225965990146048e+16, 'train_loss': 0.21723561718108805, 'epoch': 1.0})

In [ ]:
# Save locally
ADAPTER_PATH = "./tinyllama-lora-balanced-adapter"

trainer.model.save_pretrained(ADAPTER_PATH)
tokenizer.save_pretrained(ADAPTER_PATH)
print(f"Saved locally: {ADAPTER_PATH}")
print(f"Files: {os.listdir(ADAPTER_PATH)}")

Saved locally: ./tinyllama-lora-balanced-adapter
Files: ['adapter_model.safetensors', 'tokenizer_config.json', 'chat_template.jinja', 'adapter_config.json', 'README.md', 'tokenizer.json']

In [ ]:
# Backup to Drive dont forget
import shutil, os
from google.colab import drive

drive.mount("/content/drive", force_remount=True)

LOCAL_ADAPTER_PATH = "./tinyllama-lora-balanced-adapter"
DRIVE_ADAPTER_PATH = "/content/drive/MyDrive/tinyllama-lora-balanced-adapter"

assert os.path.exists(LOCAL_ADAPTER_PATH), "No local adapter — did the save cell run?"

if os.path.exists(DRIVE_ADAPTER_PATH):
    shutil.rmtree(DRIVE_ADAPTER_PATH)
    print("Removed old version from Drive")

shutil.copytree(LOCAL_ADAPTER_PATH, DRIVE_ADAPTER_PATH)
print(f"   Backed up to Drive: {DRIVE_ADAPTER_PATH}")
print(f"   Files: {os.listdir(DRIVE_ADAPTER_PATH)}")

In [ ]:
tokenizer.padding_side = "left"          # flip back from training's "right"
model_ft = trainer.model                 # best checkpoint (load_best_model_at_end)
model_ft.eval()
model_ft.config.use_cache = False

smoke = X_val_prompts.iloc[:1].reset_index(drop=True)
_, g = predict_decoder_only(smoke, model_ft, tokenizer)
print(repr(g[0]))    # want a clean 'pass' or 'fail'

  0%|          | 0/1 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
100%|██████████| 1/1 [00:00<00:00,  6.79it/s]

[  1/1]  raw='pass'  → → 1
'pass'

In [ ]:
y_pred, y_generated = predict_decoder_only(
    X_test_prompts.reset_index(drop=True), model_ft, tokenizer
)

# save straight to Drive before anything else
pd.DataFrame({"y_true": y_true, "y_pred": y_pred, "generated": y_generated}) \
  .to_csv("/content/drive/MyDrive/tinyllama_finetuned_test_results.csv", index=False)

  0%|          | 0/765 [00:00<?, ?it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  0%|          | 1/765 [00:00<01:41,  7.54it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  0%|          | 2/765 [00:00<01:40,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  1/765]  raw='fail'  → → 0
[  2/765]  raw='fail'  → → 0

  0%|          | 3/765 [00:00<01:38,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|          | 4/765 [00:00<01:40,  7.61it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  3/765]  raw='fail'  → → 0
[  4/765]  raw='pass'  → → 1

  1%|          | 5/765 [00:00<01:39,  7.61it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|          | 6/765 [00:00<01:38,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  5/765]  raw='fail'  → → 0
[  6/765]  raw='fail'  → → 0

  1%|          | 7/765 [00:00<01:38,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|          | 8/765 [00:01<01:37,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  7/765]  raw='pass'  → → 1
[  8/765]  raw='fail'  → → 0

  1%|          | 9/765 [00:01<01:38,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|▏         | 10/765 [00:01<01:37,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[  9/765]  raw='pass'  → → 1
[ 10/765]  raw='fail'  → → 0

  1%|▏         | 11/765 [00:01<01:36,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 12/765 [00:01<01:37,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 11/765]  raw='fail'  → → 0
[ 12/765]  raw='pass'  → → 1

  2%|▏         | 13/765 [00:01<01:37,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 14/765 [00:01<01:36,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 13/765]  raw='pass'  → → 1
[ 14/765]  raw='pass'  → → 1

  2%|▏         | 15/765 [00:01<01:37,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 16/765 [00:02<01:36,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 15/765]  raw='pass'  → → 1
[ 16/765]  raw='pass'  → → 1

  2%|▏         | 17/765 [00:02<01:36,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 18/765 [00:02<01:36,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 17/765]  raw='fail'  → → 0
[ 18/765]  raw='pass'  → → 1

  2%|▏         | 19/765 [00:02<01:36,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 20/765 [00:02<01:36,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 19/765]  raw='fail'  → → 0
[ 20/765]  raw='pass'  → → 1

  3%|▎         | 21/765 [00:02<01:36,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 22/765 [00:02<01:35,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 21/765]  raw='fail'  → → 0
[ 22/765]  raw='fail'  → → 0

  3%|▎         | 23/765 [00:02<01:36,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 24/765 [00:03<01:37,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 23/765]  raw='fail'  → → 0
[ 24/765]  raw='pass'  → → 1

  3%|▎         | 25/765 [00:03<01:37,  7.57it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 26/765 [00:03<01:37,  7.60it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 25/765]  raw='pass'  → → 1
[ 26/765]  raw='fail'  → → 0

  4%|▎         | 27/765 [00:03<01:36,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▎         | 28/765 [00:03<01:36,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 27/765]  raw='fail'  → → 0
[ 28/765]  raw='fail'  → → 0

  4%|▍         | 29/765 [00:03<01:36,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 30/765 [00:03<01:36,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 29/765]  raw='pass'  → → 1
[ 30/765]  raw='fail'  → → 0

  4%|▍         | 31/765 [00:04<01:36,  7.59it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 32/765 [00:04<01:35,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 31/765]  raw='pass'  → → 1
[ 32/765]  raw='fail'  → → 0

  4%|▍         | 33/765 [00:04<01:36,  7.58it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 34/765 [00:04<01:35,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 33/765]  raw='pass'  → → 1
[ 34/765]  raw='fail'  → → 0

  5%|▍         | 35/765 [00:04<01:35,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▍         | 36/765 [00:04<01:34,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 35/765]  raw='fail'  → → 0
[ 36/765]  raw='fail'  → → 0

  5%|▍         | 37/765 [00:04<01:33,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▍         | 38/765 [00:04<01:33,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 37/765]  raw='pass'  → → 1
[ 38/765]  raw='fail'  → → 0

  5%|▌         | 39/765 [00:05<01:33,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▌         | 40/765 [00:05<01:33,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 39/765]  raw='pass'  → → 1
[ 40/765]  raw='pass'  → → 1

  5%|▌         | 41/765 [00:05<01:34,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▌         | 42/765 [00:05<01:34,  7.67it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 41/765]  raw='pass'  → → 1
[ 42/765]  raw='fail'  → → 0

  6%|▌         | 43/765 [00:05<01:34,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▌         | 44/765 [00:05<01:33,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 43/765]  raw='fail'  → → 0
[ 44/765]  raw='pass'  → → 1

  6%|▌         | 45/765 [00:05<01:33,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▌         | 46/765 [00:05<01:33,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 45/765]  raw='fail'  → → 0
[ 46/765]  raw='fail'  → → 0

  6%|▌         | 47/765 [00:06<01:33,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▋         | 48/765 [00:06<01:33,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 47/765]  raw='pass'  → → 1
[ 48/765]  raw='fail'  → → 0

  6%|▋         | 49/765 [00:06<01:32,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 50/765 [00:06<01:32,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 49/765]  raw='fail'  → → 0
[ 50/765]  raw='pass'  → → 1

  7%|▋         | 51/765 [00:06<01:32,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 52/765 [00:06<01:32,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 51/765]  raw='pass'  → → 1
[ 52/765]  raw='fail'  → → 0

  7%|▋         | 53/765 [00:06<01:32,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 54/765 [00:07<01:33,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 53/765]  raw='pass'  → → 1
[ 54/765]  raw='pass'  → → 1

  7%|▋         | 55/765 [00:07<01:33,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 56/765 [00:07<01:32,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 55/765]  raw='fail'  → → 0
[ 56/765]  raw='fail'  → → 0

  7%|▋         | 57/765 [00:07<01:32,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 58/765 [00:07<01:31,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 57/765]  raw='fail'  → → 0
[ 58/765]  raw='fail'  → → 0

  8%|▊         | 59/765 [00:07<01:32,  7.67it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 60/765 [00:07<01:31,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 59/765]  raw='pass'  → → 1
[ 60/765]  raw='fail'  → → 0

  8%|▊         | 61/765 [00:07<01:32,  7.61it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 62/765 [00:08<01:32,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 61/765]  raw='pass'  → → 1
[ 62/765]  raw='fail'  → → 0

  8%|▊         | 63/765 [00:08<01:32,  7.56it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 64/765 [00:08<01:32,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 63/765]  raw='pass'  → → 1
[ 64/765]  raw='fail'  → → 0

  8%|▊         | 65/765 [00:08<01:31,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▊         | 66/765 [00:08<01:31,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 65/765]  raw='fail'  → → 0
[ 66/765]  raw='pass'  → → 1

  9%|▉         | 67/765 [00:08<01:32,  7.57it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▉         | 68/765 [00:08<01:34,  7.38it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 67/765]  raw='pass'  → → 1
[ 68/765]  raw='fail'  → → 0

  9%|▉         | 69/765 [00:09<01:38,  7.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▉         | 70/765 [00:09<01:41,  6.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 69/765]  raw='fail'  → → 0
[ 70/765]  raw='fail'  → → 0

  9%|▉         | 71/765 [00:09<01:46,  6.49it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▉         | 72/765 [00:09<01:50,  6.29it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 71/765]  raw='fail'  → → 0
[ 72/765]  raw='fail'  → → 0

 10%|▉         | 73/765 [00:09<01:50,  6.28it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|▉         | 74/765 [00:09<01:43,  6.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 73/765]  raw='fail'  → → 0
[ 74/765]  raw='fail'  → → 0

 10%|▉         | 75/765 [00:09<01:39,  6.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|▉         | 76/765 [00:10<01:35,  7.22it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 75/765]  raw='fail'  → → 0
[ 76/765]  raw='fail'  → → 0

 10%|█         | 77/765 [00:10<01:33,  7.36it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 78/765 [00:10<01:30,  7.56it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 77/765]  raw='fail'  → → 0
[ 78/765]  raw='pass'  → → 1

 10%|█         | 79/765 [00:10<01:29,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 80/765 [00:10<01:29,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 79/765]  raw='fail'  → → 0
[ 80/765]  raw='pass'  → → 1

 11%|█         | 81/765 [00:10<01:29,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 82/765 [00:10<01:28,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 81/765]  raw='pass'  → → 1
[ 82/765]  raw='fail'  → → 0

 11%|█         | 83/765 [00:10<01:28,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 84/765 [00:11<01:30,  7.49it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 83/765]  raw='pass'  → → 1
[ 84/765]  raw='pass'  → → 1

 11%|█         | 85/765 [00:11<01:32,  7.35it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 86/765 [00:11<01:35,  7.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 85/765]  raw='fail'  → → 0
[ 86/765]  raw='fail'  → → 0

 11%|█▏        | 87/765 [00:11<01:35,  7.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 88/765 [00:11<01:35,  7.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 87/765]  raw='fail'  → → 0
[ 88/765]  raw='pass'  → → 1

 12%|█▏        | 89/765 [00:11<01:37,  6.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 90/765 [00:11<01:37,  6.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 89/765]  raw='pass'  → → 1
[ 90/765]  raw='fail'  → → 0

 12%|█▏        | 91/765 [00:12<01:37,  6.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 92/765 [00:12<01:39,  6.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 91/765]  raw='pass'  → → 1
[ 92/765]  raw='pass'  → → 1

 12%|█▏        | 93/765 [00:12<01:39,  6.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 94/765 [00:12<01:37,  6.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 93/765]  raw='pass'  → → 1
[ 94/765]  raw='fail'  → → 0

 12%|█▏        | 95/765 [00:12<01:38,  6.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 96/765 [00:12<01:35,  7.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 95/765]  raw='fail'  → → 0
[ 96/765]  raw='fail'  → → 0

 13%|█▎        | 97/765 [00:12<01:33,  7.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 98/765 [00:13<01:31,  7.29it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 97/765]  raw='fail'  → → 0
[ 98/765]  raw='fail'  → → 0

 13%|█▎        | 99/765 [00:13<01:31,  7.30it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 100/765 [00:13<01:29,  7.42it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[ 99/765]  raw='pass'  → → 1
[100/765]  raw='fail'  → → 0

 13%|█▎        | 101/765 [00:13<01:28,  7.50it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 102/765 [00:13<01:27,  7.60it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[101/765]  raw='fail'  → → 0
[102/765]  raw='fail'  → → 0

 13%|█▎        | 103/765 [00:13<01:26,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▎        | 104/765 [00:13<01:26,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[103/765]  raw='fail'  → → 0
[104/765]  raw='fail'  → → 0

 14%|█▎        | 105/765 [00:14<01:26,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 106/765 [00:14<01:26,  7.63it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[105/765]  raw='fail'  → → 0
[106/765]  raw='pass'  → → 1

 14%|█▍        | 107/765 [00:14<01:26,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 108/765 [00:14<01:25,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[107/765]  raw='pass'  → → 1
[108/765]  raw='fail'  → → 0

 14%|█▍        | 109/765 [00:14<01:25,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 110/765 [00:14<01:25,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[109/765]  raw='pass'  → → 1
[110/765]  raw='fail'  → → 0

 15%|█▍        | 111/765 [00:14<01:25,  7.67it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▍        | 112/765 [00:14<01:25,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[111/765]  raw='fail'  → → 0
[112/765]  raw='fail'  → → 0

 15%|█▍        | 113/765 [00:15<01:26,  7.58it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▍        | 114/765 [00:15<01:25,  7.63it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[113/765]  raw='pass'  → → 1
[114/765]  raw='fail'  → → 0

 15%|█▌        | 115/765 [00:15<01:25,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▌        | 116/765 [00:15<01:24,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[115/765]  raw='fail'  → → 0
[116/765]  raw='fail'  → → 0

 15%|█▌        | 117/765 [00:15<01:24,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▌        | 118/765 [00:15<01:23,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[117/765]  raw='pass'  → → 1
[118/765]  raw='pass'  → → 1

 16%|█▌        | 119/765 [00:15<01:23,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 120/765 [00:15<01:23,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[119/765]  raw='fail'  → → 0
[120/765]  raw='pass'  → → 1

 16%|█▌        | 121/765 [00:16<01:24,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 122/765 [00:16<01:23,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[121/765]  raw='pass'  → → 1
[122/765]  raw='fail'  → → 0

 16%|█▌        | 123/765 [00:16<01:25,  7.51it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 124/765 [00:16<01:25,  7.49it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[123/765]  raw='pass'  → → 1
[124/765]  raw='pass'  → → 1

 16%|█▋        | 125/765 [00:16<01:24,  7.60it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▋        | 126/765 [00:16<01:22,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[125/765]  raw='fail'  → → 0
[126/765]  raw='fail'  → → 0

 17%|█▋        | 127/765 [00:16<01:21,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 128/765 [00:17<01:21,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[127/765]  raw='fail'  → → 0
[128/765]  raw='fail'  → → 0

 17%|█▋        | 129/765 [00:17<01:20,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 130/765 [00:17<01:20,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[129/765]  raw='fail'  → → 0
[130/765]  raw='pass'  → → 1

 17%|█▋        | 131/765 [00:17<01:20,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 132/765 [00:17<01:19,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[131/765]  raw='fail'  → → 0
[132/765]  raw='fail'  → → 0

 17%|█▋        | 133/765 [00:17<01:19,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 134/765 [00:17<01:19,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[133/765]  raw='fail'  → → 0
[134/765]  raw='fail'  → → 0

 18%|█▊        | 135/765 [00:17<01:19,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 136/765 [00:18<01:19,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[135/765]  raw='fail'  → → 0
[136/765]  raw='pass'  → → 1

 18%|█▊        | 137/765 [00:18<01:20,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 138/765 [00:18<01:20,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[137/765]  raw='pass'  → → 1
[138/765]  raw='pass'  → → 1

 18%|█▊        | 139/765 [00:18<01:20,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 140/765 [00:18<01:20,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[139/765]  raw='pass'  → → 1
[140/765]  raw='fail'  → → 0

 18%|█▊        | 141/765 [00:18<01:20,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▊        | 142/765 [00:18<01:19,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[141/765]  raw='fail'  → → 0
[142/765]  raw='fail'  → → 0

 19%|█▊        | 143/765 [00:18<01:19,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 144/765 [00:19<01:19,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[143/765]  raw='fail'  → → 0
[144/765]  raw='pass'  → → 1

 19%|█▉        | 145/765 [00:19<01:18,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 146/765 [00:19<01:18,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[145/765]  raw='pass'  → → 1
[146/765]  raw='fail'  → → 0

 19%|█▉        | 147/765 [00:19<01:18,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 148/765 [00:19<01:19,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[147/765]  raw='pass'  → → 1
[148/765]  raw='pass'  → → 1

 19%|█▉        | 149/765 [00:19<01:21,  7.53it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|█▉        | 150/765 [00:19<01:19,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[149/765]  raw='pass'  → → 1
[150/765]  raw='fail'  → → 0

 20%|█▉        | 151/765 [00:19<01:19,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|█▉        | 152/765 [00:20<01:18,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[151/765]  raw='pass'  → → 1
[152/765]  raw='pass'  → → 1

 20%|██        | 153/765 [00:20<01:17,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 154/765 [00:20<01:17,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[153/765]  raw='fail'  → → 0
[154/765]  raw='fail'  → → 0

 20%|██        | 155/765 [00:20<01:17,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 156/765 [00:20<01:17,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[155/765]  raw='pass'  → → 1
[156/765]  raw='pass'  → → 1

 21%|██        | 157/765 [00:20<01:17,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 158/765 [00:20<01:17,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[157/765]  raw='pass'  → → 1
[158/765]  raw='pass'  → → 1

 21%|██        | 159/765 [00:20<01:17,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 160/765 [00:21<01:17,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[159/765]  raw='pass'  → → 1
[160/765]  raw='pass'  → → 1

 21%|██        | 161/765 [00:21<01:16,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 162/765 [00:21<01:16,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[161/765]  raw='fail'  → → 0
[162/765]  raw='fail'  → → 0

 21%|██▏       | 163/765 [00:21<01:15,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██▏       | 164/765 [00:21<01:15,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[163/765]  raw='fail'  → → 0
[164/765]  raw='pass'  → → 1

 22%|██▏       | 165/765 [00:21<01:15,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 166/765 [00:21<01:15,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[165/765]  raw='fail'  → → 0
[166/765]  raw='fail'  → → 0

 22%|██▏       | 167/765 [00:21<01:14,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 168/765 [00:22<01:15,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[167/765]  raw='fail'  → → 0
[168/765]  raw='fail'  → → 0

 22%|██▏       | 169/765 [00:22<01:16,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 170/765 [00:22<01:15,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[169/765]  raw='pass'  → → 1
[170/765]  raw='pass'  → → 1

 22%|██▏       | 171/765 [00:22<01:16,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 172/765 [00:22<01:17,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[171/765]  raw='pass'  → → 1
[172/765]  raw='pass'  → → 1

 23%|██▎       | 173/765 [00:22<01:17,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 23%|██▎       | 174/765 [00:22<01:17,  7.58it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[173/765]  raw='pass'  → → 1
[174/765]  raw='pass'  → → 1

 23%|██▎       | 175/765 [00:23<01:17,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 23%|██▎       | 176/765 [00:23<01:17,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[175/765]  raw='fail'  → → 0
[176/765]  raw='fail'  → → 0

 23%|██▎       | 177/765 [00:23<01:16,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 23%|██▎       | 178/765 [00:23<01:16,  7.67it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[177/765]  raw='fail'  → → 0
[178/765]  raw='pass'  → → 1

 23%|██▎       | 179/765 [00:23<01:17,  7.59it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▎       | 180/765 [00:23<01:17,  7.59it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[179/765]  raw='pass'  → → 1
[180/765]  raw='fail'  → → 0

 24%|██▎       | 181/765 [00:23<01:16,  7.61it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 182/765 [00:23<01:16,  7.63it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[181/765]  raw='fail'  → → 0
[182/765]  raw='fail'  → → 0

 24%|██▍       | 183/765 [00:24<01:17,  7.55it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 184/765 [00:24<01:17,  7.49it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[183/765]  raw='fail'  → → 0
[184/765]  raw='fail'  → → 0

 24%|██▍       | 185/765 [00:24<01:18,  7.40it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 186/765 [00:24<01:18,  7.35it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[185/765]  raw='pass'  → → 1
[186/765]  raw='pass'  → → 1

 24%|██▍       | 187/765 [00:24<01:17,  7.43it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▍       | 188/765 [00:24<01:16,  7.51it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[187/765]  raw='fail'  → → 0
[188/765]  raw='fail'  → → 0

 25%|██▍       | 189/765 [00:24<01:16,  7.52it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▍       | 190/765 [00:25<01:16,  7.54it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[189/765]  raw='pass'  → → 1
[190/765]  raw='pass'  → → 1

 25%|██▍       | 191/765 [00:25<01:15,  7.61it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 192/765 [00:25<01:15,  7.59it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[191/765]  raw='pass'  → → 1
[192/765]  raw='pass'  → → 1

 25%|██▌       | 193/765 [00:25<01:15,  7.62it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 194/765 [00:25<01:14,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[193/765]  raw='fail'  → → 0
[194/765]  raw='fail'  → → 0

 25%|██▌       | 195/765 [00:25<01:14,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 196/765 [00:25<01:13,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[195/765]  raw='pass'  → → 1
[196/765]  raw='fail'  → → 0

 26%|██▌       | 197/765 [00:25<01:13,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 198/765 [00:26<01:13,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[197/765]  raw='pass'  → → 1
[198/765]  raw='pass'  → → 1

 26%|██▌       | 199/765 [00:26<01:13,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 200/765 [00:26<01:13,  7.68it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[199/765]  raw='pass'  → → 1
[200/765]  raw='fail'  → → 0

 26%|██▋       | 201/765 [00:26<01:13,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▋       | 202/765 [00:26<01:12,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[201/765]  raw='fail'  → → 0
[202/765]  raw='pass'  → → 1

 27%|██▋       | 203/765 [00:26<01:12,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 204/765 [00:26<01:12,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[203/765]  raw='fail'  → → 0
[204/765]  raw='fail'  → → 0

 27%|██▋       | 205/765 [00:26<01:11,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 206/765 [00:27<01:11,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[205/765]  raw='fail'  → → 0
[206/765]  raw='pass'  → → 1

 27%|██▋       | 207/765 [00:27<01:11,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 208/765 [00:27<01:10,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[207/765]  raw='pass'  → → 1
[208/765]  raw='fail'  → → 0

 27%|██▋       | 209/765 [00:27<01:10,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 210/765 [00:27<01:10,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[209/765]  raw='fail'  → → 0
[210/765]  raw='fail'  → → 0

 28%|██▊       | 211/765 [00:27<01:09,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 212/765 [00:27<01:09,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[211/765]  raw='fail'  → → 0
[212/765]  raw='fail'  → → 0

 28%|██▊       | 213/765 [00:27<01:09,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 214/765 [00:28<01:09,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[213/765]  raw='pass'  → → 1
[214/765]  raw='fail'  → → 0

 28%|██▊       | 215/765 [00:28<01:10,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 216/765 [00:28<01:10,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[215/765]  raw='pass'  → → 1
[216/765]  raw='fail'  → → 0

 28%|██▊       | 217/765 [00:28<01:10,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 218/765 [00:28<01:10,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[217/765]  raw='fail'  → → 0
[218/765]  raw='pass'  → → 1

 29%|██▊       | 219/765 [00:28<01:10,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▉       | 220/765 [00:28<01:09,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[219/765]  raw='pass'  → → 1
[220/765]  raw='fail'  → → 0

 29%|██▉       | 221/765 [00:29<01:09,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▉       | 222/765 [00:29<01:09,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[221/765]  raw='fail'  → → 0
[222/765]  raw='fail'  → → 0

 29%|██▉       | 223/765 [00:29<01:10,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▉       | 224/765 [00:29<01:10,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[223/765]  raw='pass'  → → 1
[224/765]  raw='pass'  → → 1

 29%|██▉       | 225/765 [00:29<01:09,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|██▉       | 226/765 [00:29<01:09,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[225/765]  raw='fail'  → → 0
[226/765]  raw='pass'  → → 1

 30%|██▉       | 227/765 [00:29<01:09,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|██▉       | 228/765 [00:29<01:08,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[227/765]  raw='fail'  → → 0
[228/765]  raw='fail'  → → 0

 30%|██▉       | 229/765 [00:30<01:08,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 230/765 [00:30<01:07,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[229/765]  raw='fail'  → → 0
[230/765]  raw='fail'  → → 0

 30%|███       | 231/765 [00:30<01:07,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 232/765 [00:30<01:07,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[231/765]  raw='fail'  → → 0
[232/765]  raw='pass'  → → 1

 30%|███       | 233/765 [00:30<01:07,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███       | 234/765 [00:30<01:06,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[233/765]  raw='fail'  → → 0
[234/765]  raw='fail'  → → 0

 31%|███       | 235/765 [00:30<01:07,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███       | 236/765 [00:30<01:06,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[235/765]  raw='pass'  → → 1
[236/765]  raw='fail'  → → 0

 31%|███       | 237/765 [00:31<01:07,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███       | 238/765 [00:31<01:06,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[237/765]  raw='fail'  → → 0
[238/765]  raw='fail'  → → 0

 31%|███       | 239/765 [00:31<01:07,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███▏      | 240/765 [00:31<01:06,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[239/765]  raw='pass'  → → 1
[240/765]  raw='pass'  → → 1

 32%|███▏      | 241/765 [00:31<01:07,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 242/765 [00:31<01:06,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[241/765]  raw='pass'  → → 1
[242/765]  raw='fail'  → → 0

 32%|███▏      | 243/765 [00:31<01:06,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 244/765 [00:31<01:06,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[243/765]  raw='fail'  → → 0
[244/765]  raw='fail'  → → 0

 32%|███▏      | 245/765 [00:32<01:06,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 246/765 [00:32<01:07,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[245/765]  raw='fail'  → → 0
[246/765]  raw='pass'  → → 1

 32%|███▏      | 247/765 [00:32<01:07,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 248/765 [00:32<01:06,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[247/765]  raw='pass'  → → 1
[248/765]  raw='fail'  → → 0

 33%|███▎      | 249/765 [00:32<01:06,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 250/765 [00:32<01:06,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[249/765]  raw='fail'  → → 0
[250/765]  raw='fail'  → → 0

 33%|███▎      | 251/765 [00:32<01:05,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 252/765 [00:32<01:05,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[251/765]  raw='fail'  → → 0
[252/765]  raw='pass'  → → 1

 33%|███▎      | 253/765 [00:33<01:05,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 254/765 [00:33<01:05,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[253/765]  raw='fail'  → → 0
[254/765]  raw='fail'  → → 0

 33%|███▎      | 255/765 [00:33<01:05,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 256/765 [00:33<01:05,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[255/765]  raw='pass'  → → 1
[256/765]  raw='pass'  → → 1

 34%|███▎      | 257/765 [00:33<01:05,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▎      | 258/765 [00:33<01:04,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[257/765]  raw='fail'  → → 0
[258/765]  raw='fail'  → → 0

 34%|███▍      | 259/765 [00:33<01:04,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▍      | 260/765 [00:34<01:04,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[259/765]  raw='fail'  → → 0
[260/765]  raw='pass'  → → 1

 34%|███▍      | 261/765 [00:34<01:04,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▍      | 262/765 [00:34<01:04,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[261/765]  raw='fail'  → → 0
[262/765]  raw='pass'  → → 1

 34%|███▍      | 263/765 [00:34<01:04,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▍      | 264/765 [00:34<01:04,  7.71it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[263/765]  raw='pass'  → → 1
[264/765]  raw='fail'  → → 0

 35%|███▍      | 265/765 [00:34<01:05,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▍      | 266/765 [00:34<01:05,  7.67it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[265/765]  raw='pass'  → → 1
[266/765]  raw='pass'  → → 1

 35%|███▍      | 267/765 [00:34<01:05,  7.58it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▌      | 268/765 [00:35<01:05,  7.59it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[267/765]  raw='pass'  → → 1
[268/765]  raw='pass'  → → 1

 35%|███▌      | 269/765 [00:35<01:05,  7.58it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▌      | 270/765 [00:35<01:05,  7.55it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[269/765]  raw='pass'  → → 1
[270/765]  raw='fail'  → → 0

 35%|███▌      | 271/765 [00:35<01:05,  7.56it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 272/765 [00:35<01:05,  7.53it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[271/765]  raw='fail'  → → 0
[272/765]  raw='pass'  → → 1

 36%|███▌      | 273/765 [00:35<01:05,  7.50it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 274/765 [00:35<01:05,  7.52it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[273/765]  raw='fail'  → → 0
[274/765]  raw='pass'  → → 1

 36%|███▌      | 275/765 [00:35<01:05,  7.47it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 276/765 [00:36<01:05,  7.50it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[275/765]  raw='pass'  → → 1
[276/765]  raw='fail'  → → 0

 36%|███▌      | 277/765 [00:36<01:04,  7.52it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▋      | 278/765 [00:36<01:04,  7.51it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[277/765]  raw='fail'  → → 0
[278/765]  raw='fail'  → → 0

 36%|███▋      | 279/765 [00:36<01:05,  7.46it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 280/765 [00:36<01:04,  7.52it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[279/765]  raw='pass'  → → 1
[280/765]  raw='fail'  → → 0

 37%|███▋      | 281/765 [00:36<01:05,  7.43it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 282/765 [00:36<01:04,  7.52it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[281/765]  raw='pass'  → → 1
[282/765]  raw='fail'  → → 0

 37%|███▋      | 283/765 [00:37<01:03,  7.54it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 284/765 [00:37<01:03,  7.54it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[283/765]  raw='pass'  → → 1
[284/765]  raw='fail'  → → 0

 37%|███▋      | 285/765 [00:37<01:05,  7.33it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 286/765 [00:37<01:04,  7.43it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[285/765]  raw='fail'  → → 0
[286/765]  raw='pass'  → → 1

 38%|███▊      | 287/765 [00:37<01:03,  7.49it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 288/765 [00:37<01:02,  7.59it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[287/765]  raw='fail'  → → 0
[288/765]  raw='pass'  → → 1

 38%|███▊      | 289/765 [00:37<01:02,  7.64it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 290/765 [00:37<01:01,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[289/765]  raw='fail'  → → 0
[290/765]  raw='fail'  → → 0

 38%|███▊      | 291/765 [00:38<01:01,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 292/765 [00:38<01:01,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[291/765]  raw='fail'  → → 0
[292/765]  raw='fail'  → → 0

 38%|███▊      | 293/765 [00:38<01:00,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 294/765 [00:38<01:00,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[293/765]  raw='pass'  → → 1
[294/765]  raw='pass'  → → 1

 39%|███▊      | 295/765 [00:38<01:00,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▊      | 296/765 [00:38<00:59,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[295/765]  raw='fail'  → → 0
[296/765]  raw='pass'  → → 1

 39%|███▉      | 297/765 [00:38<00:59,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▉      | 298/765 [00:38<00:59,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[297/765]  raw='pass'  → → 1
[298/765]  raw='pass'  → → 1

 39%|███▉      | 299/765 [00:39<00:59,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▉      | 300/765 [00:39<00:59,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[299/765]  raw='pass'  → → 1
[300/765]  raw='fail'  → → 0

 39%|███▉      | 301/765 [00:39<00:58,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▉      | 302/765 [00:39<00:59,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[301/765]  raw='fail'  → → 0
[302/765]  raw='pass'  → → 1

 40%|███▉      | 303/765 [00:39<00:59,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|███▉      | 304/765 [00:39<00:58,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[303/765]  raw='pass'  → → 1
[304/765]  raw='fail'  → → 0

 40%|███▉      | 305/765 [00:39<00:58,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 306/765 [00:40<00:58,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[305/765]  raw='fail'  → → 0
[306/765]  raw='fail'  → → 0

 40%|████      | 307/765 [00:40<00:58,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 308/765 [00:40<00:57,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[307/765]  raw='fail'  → → 0
[308/765]  raw='fail'  → → 0

 40%|████      | 309/765 [00:40<00:57,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████      | 310/765 [00:40<00:57,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[309/765]  raw='pass'  → → 1
[310/765]  raw='fail'  → → 0

 41%|████      | 311/765 [00:40<00:57,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████      | 312/765 [00:40<00:57,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[311/765]  raw='fail'  → → 0
[312/765]  raw='fail'  → → 0

 41%|████      | 313/765 [00:40<00:56,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████      | 314/765 [00:41<00:57,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[313/765]  raw='fail'  → → 0
[314/765]  raw='pass'  → → 1

 41%|████      | 315/765 [00:41<00:57,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████▏     | 316/765 [00:41<00:56,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[315/765]  raw='fail'  → → 0
[316/765]  raw='fail'  → → 0

 41%|████▏     | 317/765 [00:41<00:56,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 318/765 [00:41<00:55,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[317/765]  raw='fail'  → → 0
[318/765]  raw='fail'  → → 0

 42%|████▏     | 319/765 [00:41<00:56,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 320/765 [00:41<00:56,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[319/765]  raw='fail'  → → 0
[320/765]  raw='fail'  → → 0

 42%|████▏     | 321/765 [00:41<00:55,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 322/765 [00:42<00:55,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[321/765]  raw='fail'  → → 0
[322/765]  raw='fail'  → → 0

 42%|████▏     | 323/765 [00:42<00:56,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 324/765 [00:42<00:55,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[323/765]  raw='pass'  → → 1
[324/765]  raw='fail'  → → 0

 42%|████▏     | 325/765 [00:42<00:55,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 326/765 [00:42<00:55,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[325/765]  raw='fail'  → → 0
[326/765]  raw='pass'  → → 1

 43%|████▎     | 327/765 [00:42<00:55,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 328/765 [00:42<00:55,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[327/765]  raw='fail'  → → 0
[328/765]  raw='pass'  → → 1

 43%|████▎     | 329/765 [00:42<00:55,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 330/765 [00:43<00:55,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[329/765]  raw='fail'  → → 0
[330/765]  raw='pass'  → → 1

 43%|████▎     | 331/765 [00:43<00:54,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 332/765 [00:43<00:54,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[331/765]  raw='fail'  → → 0
[332/765]  raw='fail'  → → 0

 44%|████▎     | 333/765 [00:43<00:54,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▎     | 334/765 [00:43<00:53,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[333/765]  raw='fail'  → → 0
[334/765]  raw='pass'  → → 1

 44%|████▍     | 335/765 [00:43<00:53,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 336/765 [00:43<00:53,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[335/765]  raw='fail'  → → 0
[336/765]  raw='fail'  → → 0

 44%|████▍     | 337/765 [00:43<00:53,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 338/765 [00:44<00:53,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[337/765]  raw='pass'  → → 1
[338/765]  raw='fail'  → → 0

 44%|████▍     | 339/765 [00:44<00:53,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 340/765 [00:44<00:53,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[339/765]  raw='pass'  → → 1
[340/765]  raw='pass'  → → 1

 45%|████▍     | 341/765 [00:44<00:53,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▍     | 342/765 [00:44<00:53,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[341/765]  raw='pass'  → → 1
[342/765]  raw='pass'  → → 1

 45%|████▍     | 343/765 [00:44<00:53,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▍     | 344/765 [00:44<00:54,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[343/765]  raw='pass'  → → 1
[344/765]  raw='fail'  → → 0

 45%|████▌     | 345/765 [00:44<00:53,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▌     | 346/765 [00:45<00:54,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[345/765]  raw='pass'  → → 1
[346/765]  raw='pass'  → → 1

 45%|████▌     | 347/765 [00:45<00:53,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▌     | 348/765 [00:45<00:53,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[347/765]  raw='fail'  → → 0
[348/765]  raw='fail'  → → 0

 46%|████▌     | 349/765 [00:45<00:52,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 350/765 [00:45<00:52,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[349/765]  raw='fail'  → → 0
[350/765]  raw='fail'  → → 0

 46%|████▌     | 351/765 [00:45<00:51,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 352/765 [00:45<00:51,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[351/765]  raw='fail'  → → 0
[352/765]  raw='pass'  → → 1

 46%|████▌     | 353/765 [00:45<00:50,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▋     | 354/765 [00:46<00:50,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[353/765]  raw='fail'  → → 0
[354/765]  raw='fail'  → → 0

 46%|████▋     | 355/765 [00:46<00:50,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 356/765 [00:46<00:50,  8.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[355/765]  raw='pass'  → → 1
[356/765]  raw='pass'  → → 1

 47%|████▋     | 357/765 [00:46<00:50,  8.12it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 358/765 [00:46<00:50,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[357/765]  raw='fail'  → → 0
[358/765]  raw='pass'  → → 1

 47%|████▋     | 359/765 [00:46<00:49,  8.12it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 360/765 [00:46<00:49,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[359/765]  raw='pass'  → → 1
[360/765]  raw='fail'  → → 0

 47%|████▋     | 361/765 [00:46<00:49,  8.17it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 362/765 [00:47<00:49,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[361/765]  raw='fail'  → → 0
[362/765]  raw='pass'  → → 1

 47%|████▋     | 363/765 [00:47<00:49,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 364/765 [00:47<00:49,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[363/765]  raw='fail'  → → 0
[364/765]  raw='pass'  → → 1

 48%|████▊     | 365/765 [00:47<00:49,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 366/765 [00:47<00:49,  8.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[365/765]  raw='fail'  → → 0
[366/765]  raw='fail'  → → 0

 48%|████▊     | 367/765 [00:47<00:50,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 368/765 [00:47<00:51,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[367/765]  raw='pass'  → → 1
[368/765]  raw='fail'  → → 0

 48%|████▊     | 369/765 [00:47<00:51,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 370/765 [00:48<00:50,  7.77it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[369/765]  raw='pass'  → → 1
[370/765]  raw='pass'  → → 1

 48%|████▊     | 371/765 [00:48<00:50,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▊     | 372/765 [00:48<00:50,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[371/765]  raw='pass'  → → 1
[372/765]  raw='fail'  → → 0

 49%|████▉     | 373/765 [00:48<00:51,  7.67it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 374/765 [00:48<00:50,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[373/765]  raw='pass'  → → 1
[374/765]  raw='pass'  → → 1

 49%|████▉     | 375/765 [00:48<00:51,  7.63it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 376/765 [00:48<00:50,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[375/765]  raw='pass'  → → 1
[376/765]  raw='fail'  → → 0

 49%|████▉     | 377/765 [00:48<00:50,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 378/765 [00:49<00:50,  7.65it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[377/765]  raw='fail'  → → 0
[378/765]  raw='pass'  → → 1

 50%|████▉     | 379/765 [00:49<00:49,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|████▉     | 380/765 [00:49<00:49,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[379/765]  raw='fail'  → → 0
[380/765]  raw='fail'  → → 0

 50%|████▉     | 381/765 [00:49<00:49,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|████▉     | 382/765 [00:49<00:49,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[381/765]  raw='pass'  → → 1
[382/765]  raw='fail'  → → 0

 50%|█████     | 383/765 [00:49<00:48,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|█████     | 384/765 [00:49<00:48,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[383/765]  raw='fail'  → → 0
[384/765]  raw='fail'  → → 0

 50%|█████     | 385/765 [00:50<00:48,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|█████     | 386/765 [00:50<00:48,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[385/765]  raw='fail'  → → 0
[386/765]  raw='pass'  → → 1

 51%|█████     | 387/765 [00:50<00:48,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 388/765 [00:50<00:47,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[387/765]  raw='fail'  → → 0
[388/765]  raw='pass'  → → 1

 51%|█████     | 389/765 [00:50<00:47,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 390/765 [00:50<00:48,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[389/765]  raw='pass'  → → 1
[390/765]  raw='pass'  → → 1

 51%|█████     | 391/765 [00:50<00:47,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 392/765 [00:50<00:47,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[391/765]  raw='fail'  → → 0
[392/765]  raw='fail'  → → 0

 51%|█████▏    | 393/765 [00:51<00:47,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 394/765 [00:51<00:47,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[393/765]  raw='pass'  → → 1
[394/765]  raw='pass'  → → 1

 52%|█████▏    | 395/765 [00:51<00:47,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 396/765 [00:51<00:46,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[395/765]  raw='pass'  → → 1
[396/765]  raw='fail'  → → 0

 52%|█████▏    | 397/765 [00:51<00:46,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 398/765 [00:51<00:45,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[397/765]  raw='fail'  → → 0
[398/765]  raw='fail'  → → 0

 52%|█████▏    | 399/765 [00:51<00:45,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 400/765 [00:51<00:45,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[399/765]  raw='fail'  → → 0
[400/765]  raw='pass'  → → 1

 52%|█████▏    | 401/765 [00:52<00:45,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 402/765 [00:52<00:44,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[401/765]  raw='fail'  → → 0
[402/765]  raw='pass'  → → 1

 53%|█████▎    | 403/765 [00:52<00:45,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 404/765 [00:52<00:45,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[403/765]  raw='fail'  → → 0
[404/765]  raw='fail'  → → 0

 53%|█████▎    | 405/765 [00:52<00:45,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 406/765 [00:52<00:44,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[405/765]  raw='fail'  → → 0
[406/765]  raw='pass'  → → 1

 53%|█████▎    | 407/765 [00:52<00:44,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 408/765 [00:52<00:44,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[407/765]  raw='pass'  → → 1
[408/765]  raw='fail'  → → 0

 53%|█████▎    | 409/765 [00:53<00:44,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▎    | 410/765 [00:53<00:44,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[409/765]  raw='fail'  → → 0
[410/765]  raw='fail'  → → 0

 54%|█████▎    | 411/765 [00:53<00:44,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 412/765 [00:53<00:45,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[411/765]  raw='fail'  → → 0
[412/765]  raw='pass'  → → 1

 54%|█████▍    | 413/765 [00:53<00:45,  7.73it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 414/765 [00:53<00:44,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[413/765]  raw='pass'  → → 1
[414/765]  raw='pass'  → → 1

 54%|█████▍    | 415/765 [00:53<00:44,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 54%|█████▍    | 416/765 [00:53<00:43,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[415/765]  raw='fail'  → → 0
[416/765]  raw='fail'  → → 0

 55%|█████▍    | 417/765 [00:54<00:43,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 55%|█████▍    | 418/765 [00:54<00:43,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[417/765]  raw='fail'  → → 0
[418/765]  raw='fail'  → → 0

 55%|█████▍    | 419/765 [00:54<00:43,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 55%|█████▍    | 420/765 [00:54<00:43,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[419/765]  raw='fail'  → → 0
[420/765]  raw='pass'  → → 1

 55%|█████▌    | 421/765 [00:54<00:43,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 55%|█████▌    | 422/765 [00:54<00:43,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[421/765]  raw='fail'  → → 0
[422/765]  raw='pass'  → → 1

 55%|█████▌    | 423/765 [00:54<00:43,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 55%|█████▌    | 424/765 [00:54<00:42,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[423/765]  raw='pass'  → → 1
[424/765]  raw='fail'  → → 0

 56%|█████▌    | 425/765 [00:55<00:42,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 426/765 [00:55<00:42,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[425/765]  raw='fail'  → → 0
[426/765]  raw='pass'  → → 1

 56%|█████▌    | 427/765 [00:55<00:42,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 428/765 [00:55<00:42,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[427/765]  raw='pass'  → → 1
[428/765]  raw='fail'  → → 0

 56%|█████▌    | 429/765 [00:55<00:42,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▌    | 430/765 [00:55<00:42,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[429/765]  raw='fail'  → → 0
[430/765]  raw='pass'  → → 1

 56%|█████▋    | 431/765 [00:55<00:42,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 56%|█████▋    | 432/765 [00:55<00:41,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[431/765]  raw='pass'  → → 1
[432/765]  raw='fail'  → → 0

 57%|█████▋    | 433/765 [00:56<00:42,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 57%|█████▋    | 434/765 [00:56<00:41,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[433/765]  raw='pass'  → → 1
[434/765]  raw='fail'  → → 0

 57%|█████▋    | 435/765 [00:56<00:41,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 57%|█████▋    | 436/765 [00:56<00:41,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[435/765]  raw='fail'  → → 0
[436/765]  raw='fail'  → → 0

 57%|█████▋    | 437/765 [00:56<00:40,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 57%|█████▋    | 438/765 [00:56<00:40,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[437/765]  raw='fail'  → → 0
[438/765]  raw='fail'  → → 0

 57%|█████▋    | 439/765 [00:56<00:40,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 440/765 [00:56<00:40,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[439/765]  raw='pass'  → → 1
[440/765]  raw='fail'  → → 0

 58%|█████▊    | 441/765 [00:57<00:40,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 442/765 [00:57<00:40,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[441/765]  raw='pass'  → → 1
[442/765]  raw='fail'  → → 0

 58%|█████▊    | 443/765 [00:57<00:40,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 444/765 [00:57<00:40,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[443/765]  raw='fail'  → → 0
[444/765]  raw='fail'  → → 0

 58%|█████▊    | 445/765 [00:57<00:40,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 58%|█████▊    | 446/765 [00:57<00:40,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[445/765]  raw='fail'  → → 0
[446/765]  raw='fail'  → → 0

 58%|█████▊    | 447/765 [00:57<00:40,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▊    | 448/765 [00:57<00:39,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[447/765]  raw='pass'  → → 1
[448/765]  raw='fail'  → → 0

 59%|█████▊    | 449/765 [00:58<00:39,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▉    | 450/765 [00:58<00:39,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[449/765]  raw='fail'  → → 0
[450/765]  raw='pass'  → → 1

 59%|█████▉    | 451/765 [00:58<00:39,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▉    | 452/765 [00:58<00:38,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[451/765]  raw='fail'  → → 0
[452/765]  raw='fail'  → → 0

 59%|█████▉    | 453/765 [00:58<00:38,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 59%|█████▉    | 454/765 [00:58<00:38,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[453/765]  raw='fail'  → → 0
[454/765]  raw='fail'  → → 0

 59%|█████▉    | 455/765 [00:58<00:38,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|█████▉    | 456/765 [00:58<00:38,  8.12it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[455/765]  raw='pass'  → → 1
[456/765]  raw='fail'  → → 0

 60%|█████▉    | 457/765 [00:59<00:38,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|█████▉    | 458/765 [00:59<00:37,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[457/765]  raw='fail'  → → 0
[458/765]  raw='fail'  → → 0

 60%|██████    | 459/765 [00:59<00:37,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|██████    | 460/765 [00:59<00:37,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[459/765]  raw='fail'  → → 0
[460/765]  raw='fail'  → → 0

 60%|██████    | 461/765 [00:59<00:38,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 60%|██████    | 462/765 [00:59<00:39,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[461/765]  raw='pass'  → → 1
[462/765]  raw='pass'  → → 1

 61%|██████    | 463/765 [00:59<00:38,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 61%|██████    | 464/765 [00:59<00:38,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[463/765]  raw='fail'  → → 0
[464/765]  raw='fail'  → → 0

 61%|██████    | 465/765 [01:00<00:38,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 61%|██████    | 466/765 [01:00<00:38,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[465/765]  raw='fail'  → → 0
[466/765]  raw='fail'  → → 0

 61%|██████    | 467/765 [01:00<00:37,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 61%|██████    | 468/765 [01:00<00:38,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[467/765]  raw='pass'  → → 1
[468/765]  raw='pass'  → → 1

 61%|██████▏   | 469/765 [01:00<00:38,  7.76it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 61%|██████▏   | 470/765 [01:00<00:38,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[469/765]  raw='fail'  → → 0
[470/765]  raw='pass'  → → 1

 62%|██████▏   | 471/765 [01:00<00:37,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 472/765 [01:00<00:37,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[471/765]  raw='fail'  → → 0
[472/765]  raw='fail'  → → 0

 62%|██████▏   | 473/765 [01:01<00:37,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 474/765 [01:01<00:37,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[473/765]  raw='fail'  → → 0
[474/765]  raw='fail'  → → 0

 62%|██████▏   | 475/765 [01:01<00:37,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 476/765 [01:01<00:36,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[475/765]  raw='pass'  → → 1
[476/765]  raw='fail'  → → 0

 62%|██████▏   | 477/765 [01:01<00:36,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 62%|██████▏   | 478/765 [01:01<00:36,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[477/765]  raw='fail'  → → 0
[478/765]  raw='fail'  → → 0

 63%|██████▎   | 479/765 [01:01<00:35,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 63%|██████▎   | 480/765 [01:01<00:35,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[479/765]  raw='fail'  → → 0
[480/765]  raw='pass'  → → 1

 63%|██████▎   | 481/765 [01:02<00:35,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 63%|██████▎   | 482/765 [01:02<00:35,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[481/765]  raw='fail'  → → 0
[482/765]  raw='fail'  → → 0

 63%|██████▎   | 483/765 [01:02<00:35,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 63%|██████▎   | 484/765 [01:02<00:35,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[483/765]  raw='fail'  → → 0
[484/765]  raw='fail'  → → 0

 63%|██████▎   | 485/765 [01:02<00:34,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▎   | 486/765 [01:02<00:35,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[485/765]  raw='pass'  → → 1
[486/765]  raw='pass'  → → 1

 64%|██████▎   | 487/765 [01:02<00:35,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▍   | 488/765 [01:02<00:35,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[487/765]  raw='fail'  → → 0
[488/765]  raw='pass'  → → 1

 64%|██████▍   | 489/765 [01:03<00:34,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▍   | 490/765 [01:03<00:34,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[489/765]  raw='fail'  → → 0
[490/765]  raw='pass'  → → 1

 64%|██████▍   | 491/765 [01:03<00:34,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 64%|██████▍   | 492/765 [01:03<00:34,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[491/765]  raw='pass'  → → 1
[492/765]  raw='pass'  → → 1

 64%|██████▍   | 493/765 [01:03<00:33,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▍   | 494/765 [01:03<00:33,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[493/765]  raw='fail'  → → 0
[494/765]  raw='pass'  → → 1

 65%|██████▍   | 495/765 [01:03<00:33,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▍   | 496/765 [01:03<00:32,  8.15it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[495/765]  raw='fail'  → → 0
[496/765]  raw='fail'  → → 0

 65%|██████▍   | 497/765 [01:04<00:33,  8.12it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▌   | 498/765 [01:04<00:32,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[497/765]  raw='pass'  → → 1
[498/765]  raw='fail'  → → 0

 65%|██████▌   | 499/765 [01:04<00:32,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 65%|██████▌   | 500/765 [01:04<00:32,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[499/765]  raw='pass'  → → 1
[500/765]  raw='fail'  → → 0

 65%|██████▌   | 501/765 [01:04<00:32,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▌   | 502/765 [01:04<00:32,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[501/765]  raw='fail'  → → 0
[502/765]  raw='fail'  → → 0

 66%|██████▌   | 503/765 [01:04<00:32,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▌   | 504/765 [01:04<00:32,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[503/765]  raw='pass'  → → 1
[504/765]  raw='fail'  → → 0

 66%|██████▌   | 505/765 [01:05<00:32,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▌   | 506/765 [01:05<00:32,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[505/765]  raw='fail'  → → 0
[506/765]  raw='fail'  → → 0

 66%|██████▋   | 507/765 [01:05<00:32,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 66%|██████▋   | 508/765 [01:05<00:32,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[507/765]  raw='fail'  → → 0
[508/765]  raw='pass'  → → 1

 67%|██████▋   | 509/765 [01:05<00:32,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 67%|██████▋   | 510/765 [01:05<00:31,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[509/765]  raw='pass'  → → 1
[510/765]  raw='fail'  → → 0

 67%|██████▋   | 511/765 [01:05<00:31,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 67%|██████▋   | 512/765 [01:05<00:31,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[511/765]  raw='pass'  → → 1
[512/765]  raw='pass'  → → 1

 67%|██████▋   | 513/765 [01:06<00:31,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 67%|██████▋   | 514/765 [01:06<00:31,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[513/765]  raw='fail'  → → 0
[514/765]  raw='fail'  → → 0

 67%|██████▋   | 515/765 [01:06<00:31,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 67%|██████▋   | 516/765 [01:06<00:31,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[515/765]  raw='fail'  → → 0
[516/765]  raw='pass'  → → 1

 68%|██████▊   | 517/765 [01:06<00:30,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 68%|██████▊   | 518/765 [01:06<00:30,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[517/765]  raw='fail'  → → 0
[518/765]  raw='pass'  → → 1

 68%|██████▊   | 519/765 [01:06<00:30,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 68%|██████▊   | 520/765 [01:06<00:30,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[519/765]  raw='fail'  → → 0
[520/765]  raw='pass'  → → 1

 68%|██████▊   | 521/765 [01:07<00:30,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 68%|██████▊   | 522/765 [01:07<00:30,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[521/765]  raw='fail'  → → 0
[522/765]  raw='fail'  → → 0

 68%|██████▊   | 523/765 [01:07<00:30,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 68%|██████▊   | 524/765 [01:07<00:29,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[523/765]  raw='fail'  → → 0
[524/765]  raw='fail'  → → 0

 69%|██████▊   | 525/765 [01:07<00:29,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 69%|██████▉   | 526/765 [01:07<00:29,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[525/765]  raw='pass'  → → 1
[526/765]  raw='fail'  → → 0

 69%|██████▉   | 527/765 [01:07<00:29,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 69%|██████▉   | 528/765 [01:07<00:29,  8.11it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[527/765]  raw='fail'  → → 0
[528/765]  raw='pass'  → → 1

 69%|██████▉   | 529/765 [01:08<00:29,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 69%|██████▉   | 530/765 [01:08<00:28,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[529/765]  raw='fail'  → → 0
[530/765]  raw='fail'  → → 0

 69%|██████▉   | 531/765 [01:08<00:28,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 70%|██████▉   | 532/765 [01:08<00:28,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[531/765]  raw='fail'  → → 0
[532/765]  raw='fail'  → → 0

 70%|██████▉   | 533/765 [01:08<00:29,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 70%|██████▉   | 534/765 [01:08<00:28,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[533/765]  raw='pass'  → → 1
[534/765]  raw='pass'  → → 1

 70%|██████▉   | 535/765 [01:08<00:28,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 70%|███████   | 536/765 [01:08<00:28,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[535/765]  raw='pass'  → → 1
[536/765]  raw='fail'  → → 0

 70%|███████   | 537/765 [01:09<00:28,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 70%|███████   | 538/765 [01:09<00:28,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[537/765]  raw='fail'  → → 0
[538/765]  raw='fail'  → → 0

 70%|███████   | 539/765 [01:09<00:28,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 71%|███████   | 540/765 [01:09<00:27,  8.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[539/765]  raw='fail'  → → 0
[540/765]  raw='pass'  → → 1

 71%|███████   | 541/765 [01:09<00:27,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 71%|███████   | 542/765 [01:09<00:27,  8.11it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[541/765]  raw='pass'  → → 1
[542/765]  raw='fail'  → → 0

 71%|███████   | 543/765 [01:09<00:27,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 71%|███████   | 544/765 [01:09<00:27,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[543/765]  raw='pass'  → → 1
[544/765]  raw='fail'  → → 0

 71%|███████   | 545/765 [01:10<00:27,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 71%|███████▏  | 546/765 [01:10<00:27,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[545/765]  raw='fail'  → → 0
[546/765]  raw='fail'  → → 0

 72%|███████▏  | 547/765 [01:10<00:26,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 72%|███████▏  | 548/765 [01:10<00:26,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[547/765]  raw='fail'  → → 0
[548/765]  raw='pass'  → → 1

 72%|███████▏  | 549/765 [01:10<00:26,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 72%|███████▏  | 550/765 [01:10<00:26,  8.11it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[549/765]  raw='pass'  → → 1
[550/765]  raw='fail'  → → 0

 72%|███████▏  | 551/765 [01:10<00:26,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 72%|███████▏  | 552/765 [01:10<00:26,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[551/765]  raw='fail'  → → 0
[552/765]  raw='fail'  → → 0

 72%|███████▏  | 553/765 [01:11<00:26,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 72%|███████▏  | 554/765 [01:11<00:26,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[553/765]  raw='pass'  → → 1
[554/765]  raw='pass'  → → 1

 73%|███████▎  | 555/765 [01:11<00:26,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 73%|███████▎  | 556/765 [01:11<00:26,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[555/765]  raw='fail'  → → 0
[556/765]  raw='fail'  → → 0

 73%|███████▎  | 557/765 [01:11<00:26,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 73%|███████▎  | 558/765 [01:11<00:26,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[557/765]  raw='pass'  → → 1
[558/765]  raw='fail'  → → 0

 73%|███████▎  | 559/765 [01:11<00:26,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 73%|███████▎  | 560/765 [01:11<00:25,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[559/765]  raw='fail'  → → 0
[560/765]  raw='fail'  → → 0

 73%|███████▎  | 561/765 [01:12<00:25,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 73%|███████▎  | 562/765 [01:12<00:25,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[561/765]  raw='pass'  → → 1
[562/765]  raw='fail'  → → 0

 74%|███████▎  | 563/765 [01:12<00:25,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 74%|███████▎  | 564/765 [01:12<00:25,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[563/765]  raw='fail'  → → 0
[564/765]  raw='fail'  → → 0

 74%|███████▍  | 565/765 [01:12<00:25,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 74%|███████▍  | 566/765 [01:12<00:24,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[565/765]  raw='pass'  → → 1
[566/765]  raw='pass'  → → 1

 74%|███████▍  | 567/765 [01:12<00:24,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 74%|███████▍  | 568/765 [01:12<00:24,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[567/765]  raw='pass'  → → 1
[568/765]  raw='fail'  → → 0

 74%|███████▍  | 569/765 [01:13<00:25,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 75%|███████▍  | 570/765 [01:13<00:24,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[569/765]  raw='fail'  → → 0
[570/765]  raw='pass'  → → 1

 75%|███████▍  | 571/765 [01:13<00:24,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 75%|███████▍  | 572/765 [01:13<00:24,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[571/765]  raw='fail'  → → 0
[572/765]  raw='pass'  → → 1

 75%|███████▍  | 573/765 [01:13<00:23,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 75%|███████▌  | 574/765 [01:13<00:24,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[573/765]  raw='pass'  → → 1
[574/765]  raw='pass'  → → 1

 75%|███████▌  | 575/765 [01:13<00:24,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 75%|███████▌  | 576/765 [01:14<00:24,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[575/765]  raw='pass'  → → 1
[576/765]  raw='pass'  → → 1

 75%|███████▌  | 577/765 [01:14<00:24,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 76%|███████▌  | 578/765 [01:14<00:23,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[577/765]  raw='fail'  → → 0
[578/765]  raw='fail'  → → 0

 76%|███████▌  | 579/765 [01:14<00:23,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 76%|███████▌  | 580/765 [01:14<00:23,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[579/765]  raw='fail'  → → 0
[580/765]  raw='pass'  → → 1

 76%|███████▌  | 581/765 [01:14<00:23,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 76%|███████▌  | 582/765 [01:14<00:22,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[581/765]  raw='fail'  → → 0
[582/765]  raw='fail'  → → 0

 76%|███████▌  | 583/765 [01:14<00:22,  8.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 76%|███████▋  | 584/765 [01:15<00:22,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[583/765]  raw='fail'  → → 0
[584/765]  raw='pass'  → → 1

 76%|███████▋  | 585/765 [01:15<00:22,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 77%|███████▋  | 586/765 [01:15<00:22,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[585/765]  raw='pass'  → → 1
[586/765]  raw='pass'  → → 1

 77%|███████▋  | 587/765 [01:15<00:22,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 77%|███████▋  | 588/765 [01:15<00:22,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[587/765]  raw='fail'  → → 0
[588/765]  raw='fail'  → → 0

 77%|███████▋  | 589/765 [01:15<00:22,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 77%|███████▋  | 590/765 [01:15<00:22,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[589/765]  raw='fail'  → → 0
[590/765]  raw='fail'  → → 0

 77%|███████▋  | 591/765 [01:15<00:22,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 77%|███████▋  | 592/765 [01:16<00:21,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[591/765]  raw='fail'  → → 0
[592/765]  raw='fail'  → → 0

 78%|███████▊  | 593/765 [01:16<00:21,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 78%|███████▊  | 594/765 [01:16<00:21,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[593/765]  raw='fail'  → → 0
[594/765]  raw='fail'  → → 0

 78%|███████▊  | 595/765 [01:16<00:21,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 78%|███████▊  | 596/765 [01:16<00:21,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[595/765]  raw='pass'  → → 1
[596/765]  raw='fail'  → → 0

 78%|███████▊  | 597/765 [01:16<00:21,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 78%|███████▊  | 598/765 [01:16<00:21,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[597/765]  raw='pass'  → → 1
[598/765]  raw='pass'  → → 1

 78%|███████▊  | 599/765 [01:16<00:21,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 78%|███████▊  | 600/765 [01:17<00:20,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[599/765]  raw='pass'  → → 1
[600/765]  raw='fail'  → → 0

 79%|███████▊  | 601/765 [01:17<00:20,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 79%|███████▊  | 602/765 [01:17<00:20,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[601/765]  raw='fail'  → → 0
[602/765]  raw='pass'  → → 1

 79%|███████▉  | 603/765 [01:17<00:20,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 79%|███████▉  | 604/765 [01:17<00:20,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[603/765]  raw='pass'  → → 1
[604/765]  raw='pass'  → → 1

 79%|███████▉  | 605/765 [01:17<00:20,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 79%|███████▉  | 606/765 [01:17<00:19,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[605/765]  raw='pass'  → → 1
[606/765]  raw='fail'  → → 0

 79%|███████▉  | 607/765 [01:17<00:19,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 79%|███████▉  | 608/765 [01:18<00:19,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[607/765]  raw='fail'  → → 0
[608/765]  raw='pass'  → → 1

 80%|███████▉  | 609/765 [01:18<00:19,  8.04it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 80%|███████▉  | 610/765 [01:18<00:19,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[609/765]  raw='pass'  → → 1
[610/765]  raw='pass'  → → 1

 80%|███████▉  | 611/765 [01:18<00:18,  8.11it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 80%|████████  | 612/765 [01:18<00:18,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[611/765]  raw='pass'  → → 1
[612/765]  raw='fail'  → → 0

 80%|████████  | 613/765 [01:18<00:18,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 80%|████████  | 614/765 [01:18<00:18,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[613/765]  raw='pass'  → → 1
[614/765]  raw='pass'  → → 1

 80%|████████  | 615/765 [01:18<00:18,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 81%|████████  | 616/765 [01:19<00:18,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[615/765]  raw='fail'  → → 0
[616/765]  raw='fail'  → → 0

 81%|████████  | 617/765 [01:19<00:18,  8.13it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 81%|████████  | 618/765 [01:19<00:18,  8.16it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[617/765]  raw='fail'  → → 0
[618/765]  raw='pass'  → → 1

 81%|████████  | 619/765 [01:19<00:17,  8.15it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 81%|████████  | 620/765 [01:19<00:18,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[619/765]  raw='fail'  → → 0
[620/765]  raw='pass'  → → 1

 81%|████████  | 621/765 [01:19<00:18,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 81%|████████▏ | 622/765 [01:19<00:18,  7.55it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[621/765]  raw='pass'  → → 1
[622/765]  raw='fail'  → → 0

 81%|████████▏ | 623/765 [01:19<00:18,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 82%|████████▏ | 624/765 [01:20<00:18,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[623/765]  raw='pass'  → → 1
[624/765]  raw='pass'  → → 1

 82%|████████▏ | 625/765 [01:20<00:17,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 82%|████████▏ | 626/765 [01:20<00:17,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[625/765]  raw='fail'  → → 0
[626/765]  raw='fail'  → → 0

 82%|████████▏ | 627/765 [01:20<00:17,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 82%|████████▏ | 628/765 [01:20<00:17,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[627/765]  raw='pass'  → → 1
[628/765]  raw='pass'  → → 1

 82%|████████▏ | 629/765 [01:20<00:16,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 82%|████████▏ | 630/765 [01:20<00:16,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[629/765]  raw='pass'  → → 1
[630/765]  raw='pass'  → → 1

 82%|████████▏ | 631/765 [01:20<00:16,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 83%|████████▎ | 632/765 [01:21<00:16,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[631/765]  raw='pass'  → → 1
[632/765]  raw='fail'  → → 0

 83%|████████▎ | 633/765 [01:21<00:16,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 83%|████████▎ | 634/765 [01:21<00:16,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[633/765]  raw='pass'  → → 1
[634/765]  raw='pass'  → → 1

 83%|████████▎ | 635/765 [01:21<00:16,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 83%|████████▎ | 636/765 [01:21<00:16,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[635/765]  raw='pass'  → → 1
[636/765]  raw='pass'  → → 1

 83%|████████▎ | 637/765 [01:21<00:16,  7.80it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 83%|████████▎ | 638/765 [01:21<00:16,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[637/765]  raw='pass'  → → 1
[638/765]  raw='fail'  → → 0

 84%|████████▎ | 639/765 [01:21<00:16,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 84%|████████▎ | 640/765 [01:22<00:15,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[639/765]  raw='fail'  → → 0
[640/765]  raw='fail'  → → 0

 84%|████████▍ | 641/765 [01:22<00:15,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 84%|████████▍ | 642/765 [01:22<00:15,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[641/765]  raw='fail'  → → 0
[642/765]  raw='pass'  → → 1

 84%|████████▍ | 643/765 [01:22<00:15,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 84%|████████▍ | 644/765 [01:22<00:15,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[643/765]  raw='fail'  → → 0
[644/765]  raw='fail'  → → 0

 84%|████████▍ | 645/765 [01:22<00:14,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 84%|████████▍ | 646/765 [01:22<00:14,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[645/765]  raw='fail'  → → 0
[646/765]  raw='pass'  → → 1

 85%|████████▍ | 647/765 [01:22<00:14,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 85%|████████▍ | 648/765 [01:23<00:14,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[647/765]  raw='pass'  → → 1
[648/765]  raw='pass'  → → 1

 85%|████████▍ | 649/765 [01:23<00:14,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 85%|████████▍ | 650/765 [01:23<00:14,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[649/765]  raw='fail'  → → 0
[650/765]  raw='pass'  → → 1

 85%|████████▌ | 651/765 [01:23<00:14,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 85%|████████▌ | 652/765 [01:23<00:14,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[651/765]  raw='fail'  → → 0
[652/765]  raw='fail'  → → 0

 85%|████████▌ | 653/765 [01:23<00:14,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 85%|████████▌ | 654/765 [01:23<00:13,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[653/765]  raw='pass'  → → 1
[654/765]  raw='fail'  → → 0

 86%|████████▌ | 655/765 [01:23<00:13,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 86%|████████▌ | 656/765 [01:24<00:13,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[655/765]  raw='fail'  → → 0
[656/765]  raw='fail'  → → 0

 86%|████████▌ | 657/765 [01:24<00:13,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 86%|████████▌ | 658/765 [01:24<00:13,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[657/765]  raw='fail'  → → 0
[658/765]  raw='fail'  → → 0

 86%|████████▌ | 659/765 [01:24<00:13,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 86%|████████▋ | 660/765 [01:24<00:13,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[659/765]  raw='fail'  → → 0
[660/765]  raw='fail'  → → 0

 86%|████████▋ | 661/765 [01:24<00:13,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 87%|████████▋ | 662/765 [01:24<00:13,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[661/765]  raw='pass'  → → 1
[662/765]  raw='pass'  → → 1

 87%|████████▋ | 663/765 [01:24<00:12,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 87%|████████▋ | 664/765 [01:25<00:12,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[663/765]  raw='fail'  → → 0
[664/765]  raw='pass'  → → 1

 87%|████████▋ | 665/765 [01:25<00:12,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 87%|████████▋ | 666/765 [01:25<00:12,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[665/765]  raw='fail'  → → 0
[666/765]  raw='pass'  → → 1

 87%|████████▋ | 667/765 [01:25<00:12,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 87%|████████▋ | 668/765 [01:25<00:12,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[667/765]  raw='fail'  → → 0
[668/765]  raw='pass'  → → 1

 87%|████████▋ | 669/765 [01:25<00:11,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 88%|████████▊ | 670/765 [01:25<00:12,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[669/765]  raw='pass'  → → 1
[670/765]  raw='pass'  → → 1

 88%|████████▊ | 671/765 [01:25<00:12,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 88%|████████▊ | 672/765 [01:26<00:11,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[671/765]  raw='pass'  → → 1
[672/765]  raw='pass'  → → 1

 88%|████████▊ | 673/765 [01:26<00:11,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 88%|████████▊ | 674/765 [01:26<00:11,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[673/765]  raw='fail'  → → 0
[674/765]  raw='pass'  → → 1

 88%|████████▊ | 675/765 [01:26<00:11,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 88%|████████▊ | 676/765 [01:26<00:11,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[675/765]  raw='fail'  → → 0
[676/765]  raw='fail'  → → 0

 88%|████████▊ | 677/765 [01:26<00:10,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 89%|████████▊ | 678/765 [01:26<00:10,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[677/765]  raw='fail'  → → 0
[678/765]  raw='fail'  → → 0

 89%|████████▉ | 679/765 [01:26<00:10,  8.04it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 89%|████████▉ | 680/765 [01:27<00:10,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[679/765]  raw='pass'  → → 1
[680/765]  raw='pass'  → → 1

 89%|████████▉ | 681/765 [01:27<00:10,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 89%|████████▉ | 682/765 [01:27<00:10,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[681/765]  raw='pass'  → → 1
[682/765]  raw='pass'  → → 1

 89%|████████▉ | 683/765 [01:27<00:10,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 89%|████████▉ | 684/765 [01:27<00:10,  8.07it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[683/765]  raw='pass'  → → 1
[684/765]  raw='fail'  → → 0

 90%|████████▉ | 685/765 [01:27<00:09,  8.10it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 90%|████████▉ | 686/765 [01:27<00:09,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[685/765]  raw='pass'  → → 1
[686/765]  raw='fail'  → → 0

 90%|████████▉ | 687/765 [01:27<00:09,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 90%|████████▉ | 688/765 [01:28<00:09,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[687/765]  raw='pass'  → → 1
[688/765]  raw='fail'  → → 0

 90%|█████████ | 689/765 [01:28<00:09,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 90%|█████████ | 690/765 [01:28<00:09,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[689/765]  raw='pass'  → → 1
[690/765]  raw='fail'  → → 0

 90%|█████████ | 691/765 [01:28<00:09,  7.81it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 90%|█████████ | 692/765 [01:28<00:09,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[691/765]  raw='fail'  → → 0
[692/765]  raw='fail'  → → 0

 91%|█████████ | 693/765 [01:28<00:09,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 91%|█████████ | 694/765 [01:28<00:09,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[693/765]  raw='pass'  → → 1
[694/765]  raw='fail'  → → 0

 91%|█████████ | 695/765 [01:28<00:08,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 91%|█████████ | 696/765 [01:29<00:08,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[695/765]  raw='fail'  → → 0
[696/765]  raw='fail'  → → 0

 91%|█████████ | 697/765 [01:29<00:08,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 91%|█████████ | 698/765 [01:29<00:08,  7.78it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[697/765]  raw='pass'  → → 1
[698/765]  raw='fail'  → → 0

 91%|█████████▏| 699/765 [01:29<00:08,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 92%|█████████▏| 700/765 [01:29<00:08,  7.84it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[699/765]  raw='fail'  → → 0
[700/765]  raw='fail'  → → 0

 92%|█████████▏| 701/765 [01:29<00:08,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 92%|█████████▏| 702/765 [01:29<00:07,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[701/765]  raw='fail'  → → 0
[702/765]  raw='fail'  → → 0

 92%|█████████▏| 703/765 [01:29<00:07,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 92%|█████████▏| 704/765 [01:30<00:07,  8.06it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[703/765]  raw='pass'  → → 1
[704/765]  raw='pass'  → → 1

 92%|█████████▏| 705/765 [01:30<00:07,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 92%|█████████▏| 706/765 [01:30<00:07,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[705/765]  raw='fail'  → → 0
[706/765]  raw='fail'  → → 0

 92%|█████████▏| 707/765 [01:30<00:07,  7.85it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 93%|█████████▎| 708/765 [01:30<00:07,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[707/765]  raw='pass'  → → 1
[708/765]  raw='fail'  → → 0

 93%|█████████▎| 709/765 [01:30<00:07,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 93%|█████████▎| 710/765 [01:30<00:06,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[709/765]  raw='fail'  → → 0
[710/765]  raw='pass'  → → 1

 93%|█████████▎| 711/765 [01:31<00:06,  8.01it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 93%|█████████▎| 712/765 [01:31<00:06,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[711/765]  raw='fail'  → → 0
[712/765]  raw='pass'  → → 1

 93%|█████████▎| 713/765 [01:31<00:06,  8.03it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 93%|█████████▎| 714/765 [01:31<00:06,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[713/765]  raw='pass'  → → 1
[714/765]  raw='fail'  → → 0

 93%|█████████▎| 715/765 [01:31<00:06,  8.08it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 94%|█████████▎| 716/765 [01:31<00:06,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[715/765]  raw='fail'  → → 0
[716/765]  raw='fail'  → → 0

 94%|█████████▎| 717/765 [01:31<00:05,  8.20it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 94%|█████████▍| 718/765 [01:31<00:05,  8.19it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[717/765]  raw='pass'  → → 1
[718/765]  raw='fail'  → → 0

 94%|█████████▍| 719/765 [01:31<00:05,  8.14it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 94%|█████████▍| 720/765 [01:32<00:05,  8.09it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[719/765]  raw='fail'  → → 0
[720/765]  raw='fail'  → → 0

 94%|█████████▍| 721/765 [01:32<00:05,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 94%|█████████▍| 722/765 [01:32<00:05,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[721/765]  raw='pass'  → → 1
[722/765]  raw='pass'  → → 1

 95%|█████████▍| 723/765 [01:32<00:05,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 95%|█████████▍| 724/765 [01:32<00:05,  7.93it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[723/765]  raw='fail'  → → 0
[724/765]  raw='fail'  → → 0

 95%|█████████▍| 725/765 [01:32<00:05,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 95%|█████████▍| 726/765 [01:32<00:04,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[725/765]  raw='fail'  → → 0
[726/765]  raw='pass'  → → 1

 95%|█████████▌| 727/765 [01:33<00:04,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 95%|█████████▌| 728/765 [01:33<00:04,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[727/765]  raw='fail'  → → 0
[728/765]  raw='fail'  → → 0

 95%|█████████▌| 729/765 [01:33<00:04,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 95%|█████████▌| 730/765 [01:33<00:04,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[729/765]  raw='pass'  → → 1
[730/765]  raw='fail'  → → 0

 96%|█████████▌| 731/765 [01:33<00:04,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 96%|█████████▌| 732/765 [01:33<00:04,  7.82it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[731/765]  raw='fail'  → → 0
[732/765]  raw='pass'  → → 1

 96%|█████████▌| 733/765 [01:33<00:04,  7.83it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 96%|█████████▌| 734/765 [01:33<00:03,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[733/765]  raw='fail'  → → 0
[734/765]  raw='fail'  → → 0

 96%|█████████▌| 735/765 [01:34<00:03,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 96%|█████████▌| 736/765 [01:34<00:03,  7.99it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[735/765]  raw='fail'  → → 0
[736/765]  raw='fail'  → → 0

 96%|█████████▋| 737/765 [01:34<00:03,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 96%|█████████▋| 738/765 [01:34<00:03,  8.05it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[737/765]  raw='fail'  → → 0
[738/765]  raw='pass'  → → 1

 97%|█████████▋| 739/765 [01:34<00:03,  7.98it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 97%|█████████▋| 740/765 [01:34<00:03,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[739/765]  raw='fail'  → → 0
[740/765]  raw='fail'  → → 0

 97%|█████████▋| 741/765 [01:34<00:03,  8.00it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 97%|█████████▋| 742/765 [01:34<00:02,  7.92it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[741/765]  raw='fail'  → → 0
[742/765]  raw='pass'  → → 1

 97%|█████████▋| 743/765 [01:35<00:02,  7.95it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 97%|█████████▋| 744/765 [01:35<00:02,  7.94it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[743/765]  raw='fail'  → → 0
[744/765]  raw='pass'  → → 1

 97%|█████████▋| 745/765 [01:35<00:02,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 98%|█████████▊| 746/765 [01:35<00:02,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[745/765]  raw='fail'  → → 0
[746/765]  raw='pass'  → → 1

 98%|█████████▊| 747/765 [01:35<00:02,  7.90it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 98%|█████████▊| 748/765 [01:35<00:02,  7.89it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[747/765]  raw='fail'  → → 0
[748/765]  raw='fail'  → → 0

 98%|█████████▊| 749/765 [01:35<00:02,  7.66it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 98%|█████████▊| 750/765 [01:35<00:01,  7.70it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[749/765]  raw='fail'  → → 0
[750/765]  raw='fail'  → → 0

 98%|█████████▊| 751/765 [01:36<00:01,  7.69it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 98%|█████████▊| 752/765 [01:36<00:01,  7.72it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[751/765]  raw='fail'  → → 0
[752/765]  raw='pass'  → → 1

 98%|█████████▊| 753/765 [01:36<00:01,  7.75it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 99%|█████████▊| 754/765 [01:36<00:01,  7.74it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[753/765]  raw='fail'  → → 0
[754/765]  raw='fail'  → → 0

 99%|█████████▊| 755/765 [01:36<00:01,  7.79it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 99%|█████████▉| 756/765 [01:36<00:01,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[755/765]  raw='pass'  → → 1
[756/765]  raw='pass'  → → 1

 99%|█████████▉| 757/765 [01:36<00:01,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 99%|█████████▉| 758/765 [01:36<00:00,  7.91it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[757/765]  raw='pass'  → → 1
[758/765]  raw='pass'  → → 1

 99%|█████████▉| 759/765 [01:37<00:00,  7.86it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 99%|█████████▉| 760/765 [01:37<00:00,  7.87it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[759/765]  raw='pass'  → → 1
[760/765]  raw='pass'  → → 1

 99%|█████████▉| 761/765 [01:37<00:00,  7.88it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
100%|█████████▉| 762/765 [01:37<00:00,  7.96it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[761/765]  raw='pass'  → → 1
[762/765]  raw='fail'  → → 0

100%|█████████▉| 763/765 [01:37<00:00,  7.97it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
100%|█████████▉| 764/765 [01:37<00:00,  8.02it/s][transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[763/765]  raw='pass'  → → 1
[764/765]  raw='pass'  → → 1

100%|██████████| 765/765 [01:37<00:00,  7.82it/s]

[765/765]  raw='fail'  → → 0

In [ ]:
valid = [i for i, p in enumerate(y_pred) if p != -1]
yt = y_true[valid]; yp = [y_pred[i] for i in valid]

print(f"Parsed: {len(valid)}/{len(y_pred)}")
print(f"Accuracy: {accuracy_score(yt, yp):.4f}")
print(classification_report(yt, yp, target_names=["Fail", "Pass"]))
print(confusion_matrix(yt, yp))
print("Predicted-Pass fraction:", (pd.Series(yp)==1).mean(), " (true rate 0.42)")

Parsed: 765/765
Accuracy: 0.8863
              precision    recall  f1-score   support

        Fail       0.90      0.90      0.90       442
        Pass       0.87      0.86      0.87       323

    accuracy                           0.89       765
   macro avg       0.88      0.88      0.88       765
weighted avg       0.89      0.89      0.89       765

[[399  43]
 [ 44 279]]
Predicted-Pass fraction: 0.42091503267973857  (true rate 0.42)

### Google model 250M

In [ ]:
from transformers import T5ForConditionalGeneration, T5Tokenizer

In [ ]:
#model loading
# no quantization
model_name = "google/flan-t5-base" #250m smaller

tokenizer  = T5Tokenizer.from_pretrained(model_name)
model      = T5ForConditionalGeneration.from_pretrained(
                 model_name,
                 #torch_dtype=torch.float16, #we could do 32 but lets do 16
                 torch_dtype=torch.float32,
                 device_map="auto"
             )

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

In [ ]:

#model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Vocab size     :", len(tokenizer))
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

# Sanity-check: confirm Pass/Fail tokens exist in vocabulary
pass_id = tokenizer.encode("Pass", add_special_tokens=False)
fail_id = tokenizer.encode("Fail", add_special_tokens=False)
print(f"\nToken check:")
print(f"  'Pass' → token id(s): {pass_id}")
print(f"  'Fail' → token id(s): {fail_id}")

Model loaded on: cpu
Vocab size     : 32100
Memory (MB)    : 990.3

Token check:
  'Pass' → token id(s): [3424]
  'Fail' → token id(s): [1699, 173]

In [ ]:
print(model)
# what element i would lookhere the attention layers
# the max features here is 2048, this is important to know see below

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
)

In [ ]:
print(model.config)
#here i will check dtype if quant worked it showed here
# check the model type   "is_decoder": false,
# "is_encoder_decoder": true,
#"model_type": "t5",
# "n_positions": 512, this is the max length for this model

T5Config {
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "classifier_dropout": 0.0,
  "d_ff": 2048,
  "d_kv": 64,
  "d_model": 768,
  "decoder_start_token_id": 0,
  "dense_act_fn": "gelu_new",
  "dropout_rate": 0.1,
  "dtype": "float32",
  "eos_token_id": 1,
  "feed_forward_proj": "gated-gelu",
  "initializer_factor": 1.0,
  "is_decoder": false,
  "is_encoder_decoder": true,
  "is_gated_act": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "n_positions": 512,
  "num_decoder_layers": 12,
  "num_heads": 12,
  "num_layers": 12,
  "output_past": true,
  "pad_token_id": 0,
  "relative_attention_max_distance": 128,
  "relative_attention_num_buckets": 32,
  "scale_decoder_outputs": false,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
    "translation_en_to_de": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to German: "
    },
    "translation_en_to_fr": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to French: "
    },
    "translation_en_to_ro": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to Romanian: "
    }
  },
  "tie_word_embeddings": true,
  "transformers_version": "5.13.1",
  "use_cache": true,
  "vocab_size": 32128
}

In [ ]:
print(model.get_memory_footprint() / 1e9, "GB")
#model size increases from float16 to 32

0.990311424 GB

Free genertion approach to get output

* This is no a good model to classify essay it is too small the max lengh is too narrow

In [ ]:
def predict_t5(test, model, tokenizer):
    y_pred      = []
    y_generated = []

    model.eval() # disable training only behavior

   #it is a loop that goes through
    for i in tqdm(range(len(test))): #this is for the process bar
        prompt = test.iloc[i]["text"]

        # truncate to 512 tokens  T5's hard limit

        #the prompt needs to be converted into tokensID (numeric)
        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512, #if essays are longer than 512 tokens but the rest bye bye, many will go bye bye
            padding=False #one essay at a time, no multiple essays so no ned to pad multiple different essays
        ).to(model.device) #find the model, device it is in the cpu or gpu
                           #we are moving the tokenized prompt to th model


        #no gradient tracking we are not training
        with torch.no_grad():
            # T5 uses .generate() directly, NOT pipeline("text-generation")
            # different models have different way to extract their generated output
            # this tells the model to generate the tokens
             #the models tht needs pipeline ("text-generate") is for decoder only models
             #such s GPT adn llama wher input output shar th same workflow
             #T5 is a encoder/decoder model it understand the input stage and the output stage diffrently
            outputs = model.generate(
                **inputs,
                max_new_tokens=5, #up to 5 tokens
            )

        #this generate the token id for the first batch only 0
        # tokenizer.decode() token id back to human readable text
        #skip_special get mor clean tokens
        # strip() remove leading whitspace and everything lower
        generated = tokenizer.decode(outputs[0], skip_special_tokens=True).strip().lower()


        #for the y generated if the generated token has the world pass predict 1
        # fail as 0,  otherwise mark it as -1
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {y_pred[-1]}")

    return y_pred, y_generated

In [ ]:
#  run on val set first
val_sample   = X_val_prompts.iloc[:50].reset_index(drop=True)
y_val_sample = y_val.values[:50]

y_pred, y_generated = predict_t5(val_sample, model, tokenizer)

  2%|▏         | 1/50 [00:01<00:57,  1.18s/it]

[  1/50]  raw='pass'  →  1

  4%|▍         | 2/50 [00:02<00:49,  1.03s/it]

[  2/50]  raw='pass'  →  1

  6%|▌         | 3/50 [00:03<00:46,  1.02it/s]

[  3/50]  raw='pass'  →  1

  8%|▊         | 4/50 [00:03<00:39,  1.18it/s]

[  4/50]  raw='pass'  →  1

 10%|█         | 5/50 [00:04<00:34,  1.29it/s]

[  5/50]  raw='pass'  →  1

 12%|█▏        | 6/50 [00:05<00:35,  1.22it/s]

[  6/50]  raw='pass'  →  1

 14%|█▍        | 7/50 [00:06<00:36,  1.19it/s]

[  7/50]  raw='fail'  →  0

 16%|█▌        | 8/50 [00:07<00:36,  1.16it/s]

[  8/50]  raw='pass'  →  1

 18%|█▊        | 9/50 [00:07<00:31,  1.29it/s]

[  9/50]  raw='pass'  →  1

 20%|██        | 10/50 [00:08<00:32,  1.22it/s]

[ 10/50]  raw='pass'  →  1

 22%|██▏       | 11/50 [00:09<00:30,  1.28it/s]

[ 11/50]  raw='pass'  →  1

 24%|██▍       | 12/50 [00:10<00:32,  1.16it/s]

[ 12/50]  raw='fail'  →  0

 26%|██▌       | 13/50 [00:11<00:34,  1.08it/s]

[ 13/50]  raw='fail'  →  0

 28%|██▊       | 14/50 [00:12<00:30,  1.17it/s]

[ 14/50]  raw='pass'  →  1

 30%|███       | 15/50 [00:12<00:26,  1.34it/s]

[ 15/50]  raw='pass'  →  1

 32%|███▏      | 16/50 [00:13<00:23,  1.45it/s]

[ 16/50]  raw='pass'  →  1

 34%|███▍      | 17/50 [00:13<00:22,  1.47it/s]

[ 17/50]  raw='pass'  →  1

 36%|███▌      | 18/50 [00:14<00:21,  1.48it/s]

[ 18/50]  raw='pass'  →  1

 38%|███▊      | 19/50 [00:14<00:20,  1.54it/s]

[ 19/50]  raw='pass'  →  1

 40%|████      | 20/50 [00:15<00:19,  1.52it/s]

[ 20/50]  raw='pass'  →  1

 42%|████▏     | 21/50 [00:16<00:19,  1.51it/s]

[ 21/50]  raw='pass'  →  1

 44%|████▍     | 22/50 [00:16<00:16,  1.66it/s]

[ 22/50]  raw='fail'  →  0

 46%|████▌     | 23/50 [00:17<00:16,  1.61it/s]

[ 23/50]  raw='pass'  →  1

 48%|████▊     | 24/50 [00:17<00:15,  1.71it/s]

[ 24/50]  raw='pass'  →  1

 50%|█████     | 25/50 [00:18<00:15,  1.64it/s]

[ 25/50]  raw='pass'  →  1

 52%|█████▏    | 26/50 [00:19<00:15,  1.59it/s]

[ 26/50]  raw='pass'  →  1

 54%|█████▍    | 27/50 [00:19<00:13,  1.71it/s]

[ 27/50]  raw='fail'  →  0

 56%|█████▌    | 28/50 [00:20<00:12,  1.81it/s]

[ 28/50]  raw='pass'  →  1

 58%|█████▊    | 29/50 [00:21<00:13,  1.60it/s]

[ 29/50]  raw='pass'  →  1

 60%|██████    | 30/50 [00:22<00:14,  1.37it/s]

[ 30/50]  raw='pass'  →  1

 62%|██████▏   | 31/50 [00:23<00:16,  1.18it/s]

[ 31/50]  raw='pass'  →  1

 64%|██████▍   | 32/50 [00:23<00:14,  1.23it/s]

[ 32/50]  raw='pass'  →  1

 66%|██████▌   | 33/50 [00:25<00:15,  1.10it/s]

[ 33/50]  raw='pass'  →  1

 68%|██████▊   | 34/50 [00:25<00:14,  1.14it/s]

[ 34/50]  raw='pass'  →  1

 70%|███████   | 35/50 [00:26<00:11,  1.28it/s]

[ 35/50]  raw='fail'  →  0

 72%|███████▏  | 36/50 [00:26<00:09,  1.40it/s]

[ 36/50]  raw='fail'  →  0

 74%|███████▍  | 37/50 [00:27<00:09,  1.40it/s]

[ 37/50]  raw='fail'  →  0

 76%|███████▌  | 38/50 [00:28<00:09,  1.32it/s]

[ 38/50]  raw='pass'  →  1

 78%|███████▊  | 39/50 [00:29<00:10,  1.07it/s]

[ 39/50]  raw='fail'  →  0

 80%|████████  | 40/50 [00:30<00:09,  1.02it/s]

[ 40/50]  raw='pass'  →  1

 82%|████████▏ | 41/50 [00:32<00:09,  1.03s/it]

[ 41/50]  raw='pass'  →  1

 84%|████████▍ | 42/50 [00:32<00:07,  1.03it/s]

[ 42/50]  raw='pass'  →  1

 86%|████████▌ | 43/50 [00:33<00:06,  1.14it/s]

[ 43/50]  raw='pass'  →  1

 88%|████████▊ | 44/50 [00:34<00:05,  1.05it/s]

[ 44/50]  raw='pass'  →  1

 90%|█████████ | 45/50 [00:35<00:04,  1.09it/s]

[ 45/50]  raw='fail'  →  0

 92%|█████████▏| 46/50 [00:36<00:03,  1.01it/s]

[ 46/50]  raw='fail'  →  0

 94%|█████████▍| 47/50 [00:37<00:03,  1.04s/it]

[ 47/50]  raw='pass'  →  1

 96%|█████████▌| 48/50 [00:38<00:01,  1.09it/s]

[ 48/50]  raw='pass'  →  1

 98%|█████████▊| 49/50 [00:39<00:00,  1.12it/s]

[ 49/50]  raw='fail'  →  0

100%|██████████| 50/50 [00:39<00:00,  1.26it/s]

[ 50/50]  raw='pass'  →  1

In [ ]:
results_df = pd.DataFrame({
    "y_true"    : y_val_sample,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask     = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid   = y_val_sample[valid_mask]
y_pred_valid   = [y_pred[i] for i in valid_mask]

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0,1], target_names=["Fail","Pass"], zero_division=0
    ))

    y_true  y_pred generated y_true_label y_pred_label
0        1       1      pass         Pass         Pass
1        1       1      pass         Pass         Pass
2        0       1      pass         Fail         Pass
3        0       1      pass         Fail         Pass
4        0       1      pass         Fail         Pass
5        1       1      pass         Pass         Pass
6        0       0      fail         Fail         Fail
7        1       1      pass         Pass         Pass
8        0       1      pass         Fail         Pass
9        1       1      pass         Pass         Pass
10       0       1      pass         Fail         Pass
11       1       0      fail         Pass         Fail
12       0       0      fail         Fail         Fail
13       0       1      pass         Fail         Pass
14       0       1      pass         Fail         Pass
15       0       1      pass         Fail         Pass
16       1       1      pass         Pass         Pass
17       0       1      pass         Fail         Pass
18       0       1      pass         Fail         Pass
19       1       1      pass         Pass         Pass
20       0       1      pass         Fail         Pass
21       0       0      fail         Fail         Fail
22       0       1      pass         Fail         Pass
23       0       1      pass         Fail         Pass
24       1       1      pass         Pass         Pass
25       1       1      pass         Pass         Pass
26       0       0      fail         Fail         Fail
27       0       1      pass         Fail         Pass
28       0       1      pass         Fail         Pass
29       1       1      pass         Pass         Pass
30       1       1      pass         Pass         Pass
31       0       1      pass         Fail         Pass
32       1       1      pass         Pass         Pass
33       1       1      pass         Pass         Pass
34       0       0      fail         Fail         Fail
35       0       0      fail         Fail         Fail
36       0       0      fail         Fail         Fail
37       1       1      pass         Pass         Pass
38       0       0      fail         Fail         Fail
39       0       1      pass         Fail         Pass
40       0       1      pass         Fail         Pass
41       0       1      pass         Fail         Pass
42       0       1      pass         Fail         Pass
43       1       1      pass         Pass         Pass
44       0       0      fail         Fail         Fail
45       1       0      fail         Pass         Fail
46       0       1      pass         Fail         Pass
47       0       1      pass         Fail         Pass
48       0       0      fail         Fail         Fail
49       0       1      pass         Fail         Pass

Accuracy : 0.5000
              precision    recall  f1-score   support

        Fail       0.83      0.30      0.44        33
        Pass       0.39      0.88      0.55        17

    accuracy                           0.50        50
   macro avg       0.61      0.59      0.49        50
weighted avg       0.68      0.50      0.48        50

In [ ]:
# run on full test set
y_pred, y_generated = predict_t5(X_test_prompts, model, tokenizer)

#test
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

  0%|          | 2/765 [00:00<01:20,  9.50it/s]

[  1/765]  raw='pass'  →  1
[  2/765]  raw='pass'  →  1
[  3/765]  raw='pass'  →  1

  1%|          | 6/765 [00:00<01:13, 10.29it/s]

[  4/765]  raw='pass'  →  1
[  5/765]  raw='pass'  →  1
[  6/765]  raw='pass'  →  1

  1%|          | 8/765 [00:00<01:16,  9.92it/s]

[  7/765]  raw='pass'  →  1
[  8/765]  raw='pass'  →  1

  1%|          | 9/765 [00:01<01:41,  7.46it/s]

[  9/765]  raw='pass'  →  1

  1%|▏         | 10/765 [00:01<01:54,  6.61it/s]

[ 10/765]  raw='pass'  →  1

  1%|▏         | 11/765 [00:01<02:12,  5.68it/s]

[ 11/765]  raw='pass'  →  1

  2%|▏         | 12/765 [00:01<02:38,  4.74it/s]

[ 12/765]  raw='pass'  →  1

  2%|▏         | 13/765 [00:02<02:52,  4.36it/s]

[ 13/765]  raw='pass'  →  1

  2%|▏         | 14/765 [00:02<03:00,  4.17it/s]

[ 14/765]  raw='pass'  →  1

  2%|▏         | 15/765 [00:02<03:10,  3.93it/s]

[ 15/765]  raw='pass'  →  1

  2%|▏         | 16/765 [00:02<03:20,  3.73it/s]

[ 16/765]  raw='pass'  →  1

  2%|▏         | 17/765 [00:03<03:21,  3.71it/s]

[ 17/765]  raw='pass'  →  1

  2%|▏         | 19/765 [00:03<03:12,  3.87it/s]

[ 18/765]  raw='pass'  →  1
[ 19/765]  raw='pass'  →  1

  3%|▎         | 21/765 [00:04<03:04,  4.04it/s]

[ 20/765]  raw='pass.'  →  1
[ 21/765]  raw='pass'  →  1

  3%|▎         | 22/765 [00:04<02:51,  4.33it/s]

[ 22/765]  raw='pass'  →  1

  3%|▎         | 24/765 [00:04<02:32,  4.87it/s]

[ 23/765]  raw='pass'  →  1
[ 24/765]  raw='pass'  →  1

  3%|▎         | 26/765 [00:05<02:27,  5.02it/s]

[ 25/765]  raw='fail'  →  0
[ 26/765]  raw='pass'  →  1

  4%|▎         | 28/765 [00:05<02:11,  5.62it/s]

[ 27/765]  raw='pass'  →  1
[ 28/765]  raw='pass'  →  1

  4%|▍         | 30/765 [00:05<01:55,  6.35it/s]

[ 29/765]  raw='pass'  →  1
[ 30/765]  raw='pass'  →  1

  4%|▍         | 32/765 [00:06<02:07,  5.77it/s]

[ 31/765]  raw='fail'  →  0
[ 32/765]  raw='pass'  →  1

  4%|▍         | 34/765 [00:06<02:15,  5.41it/s]

[ 33/765]  raw='fail'  →  0
[ 34/765]  raw='pass'  →  1

  5%|▍         | 36/765 [00:07<02:23,  5.08it/s]

[ 35/765]  raw='fail'  →  0
[ 36/765]  raw='pass'  →  1

  5%|▍         | 37/765 [00:07<02:23,  5.08it/s]

[ 37/765]  raw='fail'  →  0

  5%|▌         | 39/765 [00:07<02:13,  5.44it/s]

[ 38/765]  raw='pass'  →  1
[ 39/765]  raw='pass'  →  1

  5%|▌         | 40/765 [00:07<02:00,  6.03it/s]

[ 40/765]  raw='pass'  →  1

  5%|▌         | 41/765 [00:08<02:28,  4.86it/s]

[ 41/765]  raw='fail'  →  0

  5%|▌         | 42/765 [00:08<02:54,  4.15it/s]

[ 42/765]  raw='pass'  →  1

  6%|▌         | 43/765 [00:08<02:52,  4.19it/s]

[ 43/765]  raw='pass'  →  1

  6%|▌         | 45/765 [00:09<03:01,  3.97it/s]

[ 44/765]  raw='fail'  →  0
[ 45/765]  raw='pass'  →  1

  6%|▌         | 46/765 [00:09<02:55,  4.10it/s]

[ 46/765]  raw='fail'  →  0

  6%|▋         | 48/765 [00:09<02:32,  4.70it/s]

[ 47/765]  raw='pass'  →  1
[ 48/765]  raw='pass'  →  1

  6%|▋         | 49/765 [00:10<02:43,  4.39it/s]

[ 49/765]  raw='fail'  →  0

  7%|▋         | 51/765 [00:10<02:25,  4.92it/s]

[ 50/765]  raw='fail, they will'  →  0
[ 51/765]  raw='pass'  →  1

  7%|▋         | 54/765 [00:10<01:43,  6.85it/s]

[ 52/765]  raw='fail'  →  0
[ 53/765]  raw='pass'  →  1
[ 54/765]  raw='fail'  →  0

  7%|▋         | 56/765 [00:10<01:24,  8.42it/s]

[ 55/765]  raw='pass'  →  1
[ 56/765]  raw='pass'  →  1
[ 57/765]  raw='pass'  →  1

  8%|▊         | 60/765 [00:11<01:04, 10.95it/s]

[ 58/765]  raw='pass'  →  1
[ 59/765]  raw='pass'  →  1
[ 60/765]  raw='pass'  →  1

  8%|▊         | 62/765 [00:11<01:01, 11.41it/s]

[ 61/765]  raw='pass'  →  1
[ 62/765]  raw='pass'  →  1
[ 63/765]  raw='pass'  →  1

  9%|▊         | 66/765 [00:11<00:54, 12.75it/s]

[ 64/765]  raw='pass'  →  1
[ 65/765]  raw='pass'  →  1
[ 66/765]  raw='pass'  →  1

  9%|▉         | 68/765 [00:11<00:55, 12.66it/s]

[ 67/765]  raw='pass'  →  1
[ 68/765]  raw='fail'  →  0
[ 69/765]  raw='pass'  →  1

  9%|▉         | 72/765 [00:12<00:55, 12.54it/s]

[ 70/765]  raw='pass'  →  1
[ 71/765]  raw='pass'  →  1
[ 72/765]  raw='fail'  →  0

 10%|▉         | 74/765 [00:12<00:52, 13.04it/s]

[ 73/765]  raw='pass'  →  1
[ 74/765]  raw='pass'  →  1
[ 75/765]  raw='pass'  →  1

 10%|█         | 78/765 [00:12<00:52, 12.98it/s]

[ 76/765]  raw='pass'  →  1
[ 77/765]  raw='pass'  →  1
[ 78/765]  raw='fail'  →  0

 10%|█         | 80/765 [00:12<00:53, 12.72it/s]

[ 79/765]  raw='fail'  →  0
[ 80/765]  raw='pass'  →  1
[ 81/765]  raw='pass'  →  1

 11%|█         | 84/765 [00:13<00:55, 12.25it/s]

[ 82/765]  raw='pass'  →  1
[ 83/765]  raw='fail'  →  0
[ 84/765]  raw='fail'  →  0

 11%|█         | 86/765 [00:13<00:53, 12.70it/s]

[ 85/765]  raw='pass'  →  1
[ 86/765]  raw='pass'  →  1
[ 87/765]  raw='pass'  →  1

 12%|█▏        | 90/765 [00:13<00:50, 13.28it/s]

[ 88/765]  raw='pass'  →  1
[ 89/765]  raw='pass'  →  1
[ 90/765]  raw='pass'  →  1

 12%|█▏        | 92/765 [00:13<00:55, 12.07it/s]

[ 91/765]  raw='pass'  →  1
[ 92/765]  raw='pass'  →  1

 12%|█▏        | 94/765 [00:13<00:57, 11.60it/s]

[ 93/765]  raw='pass'  →  1
[ 94/765]  raw='pass'  →  1

 13%|█▎        | 96/765 [00:14<01:01, 10.94it/s]

[ 95/765]  raw='fail'  →  0
[ 96/765]  raw='pass'  →  1
[ 97/765]  raw='fail'  →  0

 13%|█▎        | 100/765 [00:14<01:02, 10.72it/s]

[ 98/765]  raw='pass'  →  1
[ 99/765]  raw='pass'  →  1
[100/765]  raw='pass'  →  1

 13%|█▎        | 102/765 [00:14<00:59, 11.06it/s]

[101/765]  raw='pass'  →  1
[102/765]  raw='pass'  →  1
[103/765]  raw='pass'  →  1

 14%|█▍        | 106/765 [00:14<00:58, 11.26it/s]

[104/765]  raw='pass'  →  1
[105/765]  raw='pass'  →  1
[106/765]  raw='pass'  →  1

 14%|█▍        | 108/765 [00:15<01:01, 10.66it/s]

[107/765]  raw='pass'  →  1
[108/765]  raw='pass'  →  1
[109/765]  raw='pass'  →  1

 14%|█▍        | 110/765 [00:15<01:02, 10.54it/s]

[110/765]  raw='pass'  →  1
[111/765]  raw='pass'  →  1

 15%|█▍        | 114/765 [00:15<01:02, 10.38it/s]

[112/765]  raw='pass'  →  1
[113/765]  raw='pass'  →  1
[114/765]  raw='pass'  →  1

 15%|█▌        | 116/765 [00:15<00:57, 11.29it/s]

[115/765]  raw='pass'  →  1
[116/765]  raw='pass'  →  1
[117/765]  raw='pass'  →  1

 16%|█▌        | 120/765 [00:16<00:53, 12.08it/s]

[118/765]  raw='pass'  →  1
[119/765]  raw='pass'  →  1
[120/765]  raw='fail'  →  0

 16%|█▌        | 122/765 [00:16<00:51, 12.59it/s]

[121/765]  raw='pass'  →  1
[122/765]  raw='pass'  →  1
[123/765]  raw='prompt'  →  -1

 16%|█▋        | 126/765 [00:16<00:50, 12.61it/s]

[124/765]  raw='pass'  →  1
[125/765]  raw='pass'  →  1
[126/765]  raw='pass'  →  1
[127/765]  raw='pass'  →  1

 17%|█▋        | 130/765 [00:16<00:47, 13.46it/s]

[128/765]  raw='pass'  →  1
[129/765]  raw='pass'  →  1
[130/765]  raw='pass'  →  1

 17%|█▋        | 132/765 [00:17<00:48, 13.17it/s]

[131/765]  raw='pass'  →  1
[132/765]  raw='fail'  →  0
[133/765]  raw='pass'  →  1

 18%|█▊        | 134/765 [00:17<00:46, 13.49it/s]

[134/765]  raw='pass'  →  1
[135/765]  raw='pass'  →  1

 18%|█▊        | 138/765 [00:17<00:54, 11.55it/s]

[136/765]  raw='pass, the essay is'  →  1
[137/765]  raw='fail'  →  0
[138/765]  raw='fail'  →  0

 18%|█▊        | 140/765 [00:17<00:52, 11.93it/s]

[139/765]  raw='fail'  →  0
[140/765]  raw='pass'  →  1
[141/765]  raw='pass'  →  1

 19%|█▉        | 144/765 [00:18<00:49, 12.52it/s]

[142/765]  raw='pass'  →  1
[143/765]  raw='fail'  →  0
[144/765]  raw='pass'  →  1

 19%|█▉        | 146/765 [00:18<00:47, 12.98it/s]

[145/765]  raw='pass'  →  1
[146/765]  raw='pass'  →  1
[147/765]  raw='pass'  →  1

 20%|█▉        | 150/765 [00:18<00:46, 13.31it/s]

[148/765]  raw='pass'  →  1
[149/765]  raw='pass'  →  1
[150/765]  raw='pass'  →  1

 20%|█▉        | 152/765 [00:18<00:47, 12.95it/s]

[151/765]  raw='pass'  →  1
[152/765]  raw='fail'  →  0
[153/765]  raw='pass'  →  1

 20%|██        | 156/765 [00:19<00:44, 13.66it/s]

[154/765]  raw='pass'  →  1
[155/765]  raw='pass'  →  1
[156/765]  raw='pass'  →  1

 21%|██        | 158/765 [00:19<00:46, 13.10it/s]

[157/765]  raw='pass'  →  1
[158/765]  raw='fail'  →  0
[159/765]  raw='pass'  →  1

 21%|██        | 162/765 [00:19<00:48, 12.46it/s]

[160/765]  raw='fail'  →  0
[161/765]  raw='pass'  →  1
[162/765]  raw='fail'  →  0

 21%|██▏       | 164/765 [00:19<00:48, 12.30it/s]

[163/765]  raw='pass'  →  1
[164/765]  raw='pass'  →  1
[165/765]  raw='fail'  →  0

 22%|██▏       | 168/765 [00:20<00:46, 12.91it/s]

[166/765]  raw='pass'  →  1
[167/765]  raw='pass'  →  1
[168/765]  raw='pass'  →  1
[169/765]  raw='pass'  →  1

 22%|██▏       | 172/765 [00:20<00:43, 13.70it/s]

[170/765]  raw='pass'  →  1
[171/765]  raw='pass'  →  1
[172/765]  raw='pass'  →  1

 23%|██▎       | 174/765 [00:20<00:45, 13.05it/s]

[173/765]  raw='pass'  →  1
[174/765]  raw='fail'  →  0
[175/765]  raw='pass'  →  1

 23%|██▎       | 178/765 [00:20<00:43, 13.56it/s]

[176/765]  raw='pass'  →  1
[177/765]  raw='pass'  →  1
[178/765]  raw='pass'  →  1

 24%|██▎       | 180/765 [00:20<00:43, 13.33it/s]

[179/765]  raw='pass'  →  1
[180/765]  raw='fail'  →  0
[181/765]  raw='fail'  →  0

 24%|██▍       | 184/765 [00:21<00:45, 12.86it/s]

[182/765]  raw='fail'  →  0
[183/765]  raw='pass'  →  1
[184/765]  raw='fail'  →  0

 24%|██▍       | 186/765 [00:21<00:44, 13.15it/s]

[185/765]  raw='pass'  →  1
[186/765]  raw='pass'  →  1
[187/765]  raw='pass'  →  1

 25%|██▍       | 190/765 [00:21<00:42, 13.54it/s]

[188/765]  raw='pass'  →  1
[189/765]  raw='pass'  →  1
[190/765]  raw='pass'  →  1

 25%|██▌       | 192/765 [00:21<00:42, 13.49it/s]

[191/765]  raw='pass'  →  1
[192/765]  raw='pass'  →  1
[193/765]  raw='pass'  →  1

 26%|██▌       | 196/765 [00:22<00:42, 13.51it/s]

[194/765]  raw='pass'  →  1
[195/765]  raw='pass'  →  1
[196/765]  raw='fail'  →  0

 26%|██▌       | 198/765 [00:22<00:41, 13.79it/s]

[197/765]  raw='pass'  →  1
[198/765]  raw='pass'  →  1
[199/765]  raw='pass'  →  1

 26%|██▋       | 202/765 [00:22<00:42, 13.35it/s]

[200/765]  raw='fail'  →  0
[201/765]  raw='pass'  →  1
[202/765]  raw='fail'  →  0

 27%|██▋       | 204/765 [00:22<00:41, 13.42it/s]

[203/765]  raw='pass'  →  1
[204/765]  raw='pass'  →  1
[205/765]  raw='pass'  →  1

 27%|██▋       | 208/765 [00:22<00:40, 13.86it/s]

[206/765]  raw='pass'  →  1
[207/765]  raw='pass'  →  1
[208/765]  raw='pass'  →  1

 28%|██▊       | 212/765 [00:23<00:38, 14.52it/s]

[209/765]  raw='pass'  →  1
[210/765]  raw='pass'  →  1
[211/765]  raw='pass'  →  1
[212/765]  raw='pass'  →  1

 28%|██▊       | 216/765 [00:23<00:37, 14.75it/s]

[213/765]  raw='pass'  →  1
[214/765]  raw='pass'  →  1
[215/765]  raw='pass'  →  1
[216/765]  raw='pass'  →  1

 28%|██▊       | 218/765 [00:23<00:39, 14.02it/s]

[217/765]  raw='fail'  →  0
[218/765]  raw='pass'  →  1
[219/765]  raw='pass'  →  1

 29%|██▉       | 222/765 [00:23<00:41, 13.11it/s]

[220/765]  raw='fail'  →  0
[221/765]  raw='pass'  →  1
[222/765]  raw='fail'  →  0

 29%|██▉       | 224/765 [00:24<00:42, 12.82it/s]

[223/765]  raw='fail'  →  0
[224/765]  raw='pass'  →  1
[225/765]  raw='pass'  →  1

 30%|██▉       | 228/765 [00:24<00:39, 13.69it/s]

[226/765]  raw='pass'  →  1
[227/765]  raw='pass'  →  1
[228/765]  raw='pass'  →  1

 30%|███       | 230/765 [00:24<00:38, 13.87it/s]

[229/765]  raw='pass'  →  1
[230/765]  raw='pass'  →  1
[231/765]  raw='pass'  →  1

 31%|███       | 234/765 [00:24<00:38, 13.74it/s]

[232/765]  raw='pass'  →  1
[233/765]  raw='pass'  →  1
[234/765]  raw='pass'  →  1

 31%|███       | 238/765 [00:25<00:36, 14.29it/s]

[235/765]  raw='pass'  →  1
[236/765]  raw='pass'  →  1
[237/765]  raw='pass'  →  1
[238/765]  raw='pass'  →  1

 31%|███▏      | 240/765 [00:25<00:38, 13.64it/s]

[239/765]  raw='pass'  →  1
[240/765]  raw='fail'  →  0
[241/765]  raw='pass'  →  1

 32%|███▏      | 244/765 [00:25<00:36, 14.26it/s]

[242/765]  raw='pass'  →  1
[243/765]  raw='pass'  →  1
[244/765]  raw='pass'  →  1
[245/765]  raw='pass'  →  1

 32%|███▏      | 246/765 [00:25<00:36, 14.10it/s]

[246/765]  raw='pass'  →  1
[247/765]  raw='pass'  →  1

 33%|███▎      | 250/765 [00:26<00:44, 11.62it/s]

[248/765]  raw='pass'  →  1
[249/765]  raw='pass'  →  1
[250/765]  raw='pass'  →  1

 33%|███▎      | 252/765 [00:26<00:47, 10.90it/s]

[251/765]  raw='pass'  →  1
[252/765]  raw='fail'  →  0

 33%|███▎      | 254/765 [00:26<00:48, 10.53it/s]

[253/765]  raw='pass'  →  1
[254/765]  raw='fail'  →  0
[255/765]  raw='pass'  →  1

 34%|███▎      | 258/765 [00:26<00:46, 10.94it/s]

[256/765]  raw='pass'  →  1
[257/765]  raw='pass'  →  1
[258/765]  raw='pass'  →  1

 34%|███▍      | 260/765 [00:27<00:47, 10.57it/s]

[259/765]  raw='fail'  →  0
[260/765]  raw='pass'  →  1
[261/765]  raw='pass'  →  1

 34%|███▍      | 262/765 [00:27<00:46, 10.83it/s]

[262/765]  raw='pass'  →  1
[263/765]  raw='pass'  →  1

 35%|███▍      | 266/765 [00:27<00:49, 10.15it/s]

[264/765]  raw='fail'  →  0
[265/765]  raw='pass'  →  1
[266/765]  raw='pass'  →  1

 35%|███▌      | 268/765 [00:27<00:50,  9.82it/s]

[267/765]  raw='pass'  →  1
[268/765]  raw='pass'  →  1

 35%|███▌      | 271/765 [00:28<00:44, 11.07it/s]

[269/765]  raw='pass'  →  1
[270/765]  raw='pass'  →  1
[271/765]  raw='pass'  →  1

 36%|███▌      | 273/765 [00:28<00:41, 11.90it/s]

[272/765]  raw='pass'  →  1
[273/765]  raw='pass'  →  1
[274/765]  raw='pass'  →  1

 36%|███▌      | 277/765 [00:28<00:38, 12.53it/s]

[275/765]  raw='pass'  →  1
[276/765]  raw='pass'  →  1
[277/765]  raw='fail'  →  0

 36%|███▋      | 279/765 [00:28<00:38, 12.68it/s]

[278/765]  raw='pass'  →  1
[279/765]  raw='pass'  →  1
[280/765]  raw='fail'  →  0

 37%|███▋      | 283/765 [00:29<00:39, 12.30it/s]

[281/765]  raw='pass'  →  1
[282/765]  raw='fail'  →  0
[283/765]  raw='pass'  →  1

 37%|███▋      | 285/765 [00:29<00:37, 12.84it/s]

[284/765]  raw='pass'  →  1
[285/765]  raw='pass'  →  1
[286/765]  raw='fail'  →  0

 38%|███▊      | 289/765 [00:29<00:35, 13.36it/s]

[287/765]  raw='pass'  →  1
[288/765]  raw='pass'  →  1
[289/765]  raw='pass'  →  1

 38%|███▊      | 291/765 [00:29<00:36, 13.01it/s]

[290/765]  raw='fail'  →  0
[291/765]  raw='pass'  →  1
[292/765]  raw='pass'  →  1

 39%|███▊      | 295/765 [00:29<00:35, 13.21it/s]

[293/765]  raw='pass'  →  1
[294/765]  raw='pass'  →  1
[295/765]  raw='fail'  →  0

 39%|███▉      | 297/765 [00:30<00:38, 12.21it/s]

[296/765]  raw='pass'  →  1
[297/765]  raw='fail'  →  0
[298/765]  raw='pass'  →  1

 39%|███▉      | 301/765 [00:30<00:34, 13.30it/s]

[299/765]  raw='pass'  →  1
[300/765]  raw='pass'  →  1
[301/765]  raw='pass'  →  1

 40%|███▉      | 303/765 [00:30<00:34, 13.56it/s]

[302/765]  raw='pass'  →  1
[303/765]  raw='pass'  →  1
[304/765]  raw='pass'  →  1

 40%|████      | 307/765 [00:30<00:32, 14.19it/s]

[305/765]  raw='pass'  →  1
[306/765]  raw='pass'  →  1
[307/765]  raw='pass'  →  1
[308/765]  raw='pass'  →  1

 41%|████      | 311/765 [00:31<00:33, 13.63it/s]

[309/765]  raw='fail'  →  0
[310/765]  raw='pass'  →  1
[311/765]  raw='pass'  →  1

 41%|████      | 313/765 [00:31<00:33, 13.42it/s]

[312/765]  raw='pass'  →  1
[313/765]  raw='fail'  →  0
[314/765]  raw='pass'  →  1

 41%|████▏     | 317/765 [00:31<00:32, 13.96it/s]

[315/765]  raw='pass'  →  1
[316/765]  raw='pass'  →  1
[317/765]  raw='pass'  →  1

 42%|████▏     | 319/765 [00:31<00:33, 13.46it/s]

[318/765]  raw='fail'  →  0
[319/765]  raw='pass'  →  1
[320/765]  raw='fail'  →  0

 42%|████▏     | 323/765 [00:32<00:33, 13.06it/s]

[321/765]  raw='pass'  →  1
[322/765]  raw='pass'  →  1
[323/765]  raw='fail'  →  0

 42%|████▏     | 325/765 [00:32<00:33, 13.12it/s]

[324/765]  raw='pass'  →  1
[325/765]  raw='pass'  →  1
[326/765]  raw='pass'  →  1

 43%|████▎     | 329/765 [00:32<00:31, 14.03it/s]

[327/765]  raw='pass'  →  1
[328/765]  raw='pass'  →  1
[329/765]  raw='pass'  →  1

 43%|████▎     | 331/765 [00:32<00:32, 13.47it/s]

[330/765]  raw='pass'  →  1
[331/765]  raw='fail'  →  0
[332/765]  raw='pass'  →  1

 44%|████▍     | 335/765 [00:32<00:30, 13.95it/s]

[333/765]  raw='pass'  →  1
[334/765]  raw='pass'  →  1
[335/765]  raw='pass'  →  1
[336/765]  raw='pass'  →  1

 44%|████▍     | 339/765 [00:33<00:30, 13.95it/s]

[337/765]  raw='pass'  →  1
[338/765]  raw='pass'  →  1
[339/765]  raw='pass'  →  1

 45%|████▍     | 341/765 [00:33<00:30, 14.01it/s]

[340/765]  raw='pass'  →  1
[341/765]  raw='pass'  →  1
[342/765]  raw='pass'  →  1

 45%|████▌     | 345/765 [00:33<00:29, 14.23it/s]

[343/765]  raw='pass'  →  1
[344/765]  raw='pass'  →  1
[345/765]  raw='pass'  →  1

 45%|████▌     | 347/765 [00:33<00:29, 14.15it/s]

[346/765]  raw='pass'  →  1
[347/765]  raw='pass'  →  1
[348/765]  raw='pass'  →  1

 46%|████▌     | 351/765 [00:34<00:28, 14.57it/s]

[349/765]  raw='pass'  →  1
[350/765]  raw='pass'  →  1
[351/765]  raw='pass'  →  1

 46%|████▌     | 353/765 [00:34<00:30, 13.52it/s]

[352/765]  raw='fail'  →  0
[353/765]  raw='pass'  →  1
[354/765]  raw='pass'  →  1

 47%|████▋     | 357/765 [00:34<00:28, 14.26it/s]

[355/765]  raw='pass'  →  1
[356/765]  raw='pass'  →  1
[357/765]  raw='pass'  →  1

 47%|████▋     | 359/765 [00:34<00:28, 14.30it/s]

[358/765]  raw='pass'  →  1
[359/765]  raw='pass'  →  1
[360/765]  raw='fail'  →  0

 47%|████▋     | 363/765 [00:34<00:30, 13.22it/s]

[361/765]  raw='fail'  →  0
[362/765]  raw='fail'  →  0
[363/765]  raw='pass'  →  1

 48%|████▊     | 365/765 [00:35<00:29, 13.53it/s]

[364/765]  raw='pass'  →  1
[365/765]  raw='pass'  →  1
[366/765]  raw='fail'  →  0

 48%|████▊     | 369/765 [00:35<00:29, 13.23it/s]

[367/765]  raw='fail'  →  0
[368/765]  raw='pass'  →  1
[369/765]  raw='pass'  →  1

 49%|████▉     | 373/765 [00:35<00:28, 13.94it/s]

[370/765]  raw='pass'  →  1
[371/765]  raw='pass'  →  1
[372/765]  raw='pass'  →  1
[373/765]  raw='pass'  →  1

 49%|████▉     | 375/765 [00:35<00:29, 13.39it/s]

[374/765]  raw='fail'  →  0
[375/765]  raw='pass'  →  1
[376/765]  raw='pass'  →  1

 50%|████▉     | 379/765 [00:36<00:30, 12.83it/s]

[377/765]  raw='pass'  →  1
[378/765]  raw='fail'  →  0
[379/765]  raw='fail'  →  0

 50%|████▉     | 381/765 [00:36<00:29, 13.06it/s]

[380/765]  raw='pass'  →  1
[381/765]  raw='pass'  →  1
[382/765]  raw='pass'  →  1

 50%|█████     | 385/765 [00:36<00:27, 14.07it/s]

[383/765]  raw='pass'  →  1
[384/765]  raw='pass'  →  1
[385/765]  raw='pass'  →  1

 51%|█████     | 387/765 [00:36<00:26, 14.09it/s]

[386/765]  raw='pass'  →  1
[387/765]  raw='pass'  →  1
[388/765]  raw='pass'  →  1

 51%|█████     | 391/765 [00:36<00:26, 14.14it/s]

[389/765]  raw='pass'  →  1
[390/765]  raw='pass'  →  1
[391/765]  raw='pass'  →  1
[392/765]  raw='pass'  →  1

 52%|█████▏    | 395/765 [00:37<00:26, 13.98it/s]

[393/765]  raw='pass'  →  1
[394/765]  raw='pass'  →  1
[395/765]  raw='pass'  →  1

 52%|█████▏    | 397/765 [00:37<00:26, 13.94it/s]

[396/765]  raw='pass'  →  1
[397/765]  raw='pass'  →  1
[398/765]  raw='pass'  →  1

 52%|█████▏    | 401/765 [00:37<00:28, 13.00it/s]

[399/765]  raw='fail'  →  0
[400/765]  raw='fail'  →  0
[401/765]  raw='pass'  →  1

 53%|█████▎    | 403/765 [00:37<00:27, 13.23it/s]

[402/765]  raw='pass'  →  1
[403/765]  raw='pass'  →  1
[404/765]  raw='fail'  →  0

 53%|█████▎    | 407/765 [00:38<00:30, 11.56it/s]

[405/765]  raw='pass'  →  1
[406/765]  raw='pass'  →  1
[407/765]  raw='pass'  →  1

 53%|█████▎    | 409/765 [00:38<00:31, 11.16it/s]

[408/765]  raw='pass'  →  1
[409/765]  raw='pass'  →  1
[410/765]  raw='pass'  →  1

 54%|█████▍    | 413/765 [00:38<00:30, 11.40it/s]

[411/765]  raw='pass'  →  1
[412/765]  raw='pass'  →  1
[413/765]  raw='pass'  →  1

 54%|█████▍    | 415/765 [00:39<00:32, 10.92it/s]

[414/765]  raw='pass'  →  1
[415/765]  raw='fail'  →  0
[416/765]  raw='pass'  →  1

 55%|█████▍    | 419/765 [00:39<00:31, 10.94it/s]

[417/765]  raw='fail'  →  0
[418/765]  raw='pass'  →  1
[419/765]  raw='pass'  →  1

 55%|█████▌    | 421/765 [00:39<00:32, 10.62it/s]

[420/765]  raw='pass'  →  1
[421/765]  raw='pass'  →  1

 55%|█████▌    | 423/765 [00:39<00:33, 10.31it/s]

[422/765]  raw='pass'  →  1
[423/765]  raw='pass'  →  1
[424/765]  raw='pass'  →  1

 56%|█████▌    | 426/765 [00:40<00:35,  9.55it/s]

[425/765]  raw='fail'  →  0
[426/765]  raw='pass'  →  1
[427/765]  raw='pass'  →  1

 56%|█████▌    | 430/765 [00:40<00:31, 10.67it/s]

[428/765]  raw='fail'  →  0
[429/765]  raw='pass'  →  1
[430/765]  raw='pass'  →  1

 56%|█████▋    | 432/765 [00:40<00:30, 10.89it/s]

[431/765]  raw='fail'  →  0
[432/765]  raw='pass'  →  1
[433/765]  raw='fail'  →  0

 57%|█████▋    | 436/765 [00:40<00:26, 12.20it/s]

[434/765]  raw='pass'  →  1
[435/765]  raw='pass'  →  1
[436/765]  raw='pass'  →  1

 57%|█████▋    | 438/765 [00:41<00:25, 12.99it/s]

[437/765]  raw='pass'  →  1
[438/765]  raw='pass'  →  1
[439/765]  raw='pass'  →  1

 58%|█████▊    | 442/765 [00:41<00:23, 13.65it/s]

[440/765]  raw='pass'  →  1
[441/765]  raw='pass'  →  1
[442/765]  raw='pass'  →  1

 58%|█████▊    | 444/765 [00:41<00:22, 14.17it/s]

[443/765]  raw='pass'  →  1
[444/765]  raw='pass'  →  1
[445/765]  raw='pass'  →  1

 59%|█████▊    | 448/765 [00:41<00:22, 13.92it/s]

[446/765]  raw='pass'  →  1
[447/765]  raw='pass'  →  1
[448/765]  raw='pass'  →  1

 59%|█████▉    | 450/765 [00:41<00:23, 13.28it/s]

[449/765]  raw='pass'  →  1
[450/765]  raw='fail'  →  0
[451/765]  raw='pass'  →  1

 59%|█████▉    | 454/765 [00:42<00:22, 13.99it/s]

[452/765]  raw='pass'  →  1
[453/765]  raw='pass'  →  1
[454/765]  raw='pass'  →  1

 60%|█████▉    | 456/765 [00:42<00:24, 12.42it/s]

[455/765]  raw='fail'  →  0
[456/765]  raw='pass'  →  1
[457/765]  raw='fail'  →  0

 60%|██████    | 460/765 [00:42<00:23, 12.90it/s]

[458/765]  raw='pass'  →  1
[459/765]  raw='pass'  →  1
[460/765]  raw='pass'  →  1

 60%|██████    | 462/765 [00:42<00:23, 12.70it/s]

[461/765]  raw='fail'  →  0
[462/765]  raw='pass'  →  1
[463/765]  raw='pass'  →  1

 61%|██████    | 466/765 [00:43<00:22, 13.10it/s]

[464/765]  raw='pass'  →  1
[465/765]  raw='fail'  →  0
[466/765]  raw='pass'  →  1

 61%|██████    | 468/765 [00:43<00:23, 12.89it/s]

[467/765]  raw='fail'  →  0
[468/765]  raw='pass'  →  1
[469/765]  raw='pass'  →  1

 62%|██████▏   | 472/765 [00:43<00:21, 13.44it/s]

[470/765]  raw='pass'  →  1
[471/765]  raw='pass'  →  1
[472/765]  raw='pass'  →  1

 62%|██████▏   | 474/765 [00:43<00:22, 13.15it/s]

[473/765]  raw='fail'  →  0
[474/765]  raw='pass'  →  1
[475/765]  raw='fail'  →  0

 62%|██████▏   | 478/765 [00:44<00:21, 13.58it/s]

[476/765]  raw='pass'  →  1
[477/765]  raw='pass'  →  1
[478/765]  raw='pass'  →  1

 63%|██████▎   | 480/765 [00:44<00:20, 13.64it/s]

[479/765]  raw='pass'  →  1
[480/765]  raw='pass'  →  1
[481/765]  raw='pass'  →  1

 63%|██████▎   | 484/765 [00:44<00:20, 13.57it/s]

[482/765]  raw='pass'  →  1
[483/765]  raw='pass'  →  1
[484/765]  raw='fail'  →  0

 64%|██████▎   | 486/765 [00:44<00:20, 13.45it/s]

[485/765]  raw='pass'  →  1
[486/765]  raw='pass'  →  1
[487/765]  raw='pass'  →  1

 64%|██████▍   | 490/765 [00:44<00:19, 13.95it/s]

[488/765]  raw='pass'  →  1
[489/765]  raw='pass'  →  1
[490/765]  raw='pass'  →  1

 64%|██████▍   | 492/765 [00:45<00:19, 14.07it/s]

[491/765]  raw='pass'  →  1
[492/765]  raw='pass'  →  1
[493/765]  raw='fail'  →  0

 65%|██████▍   | 496/765 [00:45<00:19, 13.98it/s]

[494/765]  raw='pass'  →  1
[495/765]  raw='pass'  →  1
[496/765]  raw='pass'  →  1

 65%|██████▌   | 498/765 [00:45<00:19, 13.49it/s]

[497/765]  raw='fail'  →  0
[498/765]  raw='pass'  →  1
[499/765]  raw='pass'  →  1

 66%|██████▌   | 502/765 [00:45<00:19, 13.73it/s]

[500/765]  raw='pass'  →  1
[501/765]  raw='pass'  →  1
[502/765]  raw='pass'  →  1

 66%|██████▌   | 506/765 [00:46<00:18, 14.37it/s]

[503/765]  raw='pass'  →  1
[504/765]  raw='pass'  →  1
[505/765]  raw='pass'  →  1
[506/765]  raw='pass'  →  1

 66%|██████▋   | 508/765 [00:46<00:18, 14.24it/s]

[507/765]  raw='pass'  →  1
[508/765]  raw='pass'  →  1
[509/765]  raw='pass'  →  1

 67%|██████▋   | 512/765 [00:46<00:17, 14.22it/s]

[510/765]  raw='pass'  →  1
[511/765]  raw='pass'  →  1
[512/765]  raw='pass'  →  1

 67%|██████▋   | 514/765 [00:46<00:17, 14.12it/s]

[513/765]  raw='pass'  →  1
[514/765]  raw='pass'  →  1
[515/765]  raw='fail'  →  0

 68%|██████▊   | 518/765 [00:46<00:18, 13.22it/s]

[516/765]  raw='fail'  →  0
[517/765]  raw='pass'  →  1
[518/765]  raw='pass'  →  1

 68%|██████▊   | 520/765 [00:47<00:18, 13.49it/s]

[519/765]  raw='pass'  →  1
[520/765]  raw='pass'  →  1
[521/765]  raw='pass'  →  1

 68%|██████▊   | 524/765 [00:47<00:17, 13.39it/s]

[522/765]  raw='pass'  →  1
[523/765]  raw='fail'  →  0
[524/765]  raw='pass'  →  1

 69%|██████▉   | 526/765 [00:47<00:17, 13.67it/s]

[525/765]  raw='pass'  →  1
[526/765]  raw='pass'  →  1
[527/765]  raw='fail'  →  0

 69%|██████▉   | 530/765 [00:47<00:17, 13.70it/s]

[528/765]  raw='pass'  →  1
[529/765]  raw='pass'  →  1
[530/765]  raw='pass'  →  1
[531/765]  raw='pass'  →  1

 70%|██████▉   | 534/765 [00:48<00:16, 14.03it/s]

[532/765]  raw='pass'  →  1
[533/765]  raw='pass'  →  1
[534/765]  raw='pass'  →  1

 70%|███████   | 536/765 [00:48<00:16, 13.96it/s]

[535/765]  raw='pass'  →  1
[536/765]  raw='pass'  →  1
[537/765]  raw='pass'  →  1

 71%|███████   | 540/765 [00:48<00:15, 14.24it/s]

[538/765]  raw='pass'  →  1
[539/765]  raw='pass'  →  1
[540/765]  raw='pass'  →  1

 71%|███████   | 542/765 [00:48<00:16, 13.52it/s]

[541/765]  raw='fail'  →  0
[542/765]  raw='pass'  →  1
[543/765]  raw='pass'  →  1

 71%|███████▏  | 546/765 [00:49<00:16, 13.67it/s]

[544/765]  raw='pass'  →  1
[545/765]  raw='pass'  →  1
[546/765]  raw='pass'  →  1

 72%|███████▏  | 548/765 [00:49<00:16, 13.30it/s]

[547/765]  raw='fail'  →  0
[548/765]  raw='pass'  →  1
[549/765]  raw='pass'  →  1

 72%|███████▏  | 552/765 [00:49<00:15, 14.08it/s]

[550/765]  raw='pass'  →  1
[551/765]  raw='pass'  →  1
[552/765]  raw='pass'  →  1

 72%|███████▏  | 554/765 [00:49<00:16, 12.97it/s]

[553/765]  raw='fail'  →  0
[554/765]  raw='fail'  →  0
[555/765]  raw='pass'  →  1

 73%|███████▎  | 558/765 [00:49<00:16, 12.79it/s]

[556/765]  raw='fail'  →  0
[557/765]  raw='pass'  →  1
[558/765]  raw='pass'  →  1

 73%|███████▎  | 560/765 [00:50<00:15, 13.17it/s]

[559/765]  raw='pass'  →  1
[560/765]  raw='pass'  →  1
[561/765]  raw='pass'  →  1

 74%|███████▎  | 564/765 [00:50<00:17, 11.72it/s]

[562/765]  raw='pass'  →  1
[563/765]  raw='pass'  →  1
[564/765]  raw='pass'  →  1

 74%|███████▍  | 566/765 [00:50<00:18, 10.48it/s]

[565/765]  raw='fail'  →  0
[566/765]  raw='fail'  →  0

 74%|███████▍  | 568/765 [00:50<00:20,  9.72it/s]

[567/765]  raw='fail'  →  0
[568/765]  raw='pass'  →  1

 75%|███████▍  | 570/765 [00:51<00:19,  9.79it/s]

[569/765]  raw='fail'  →  0
[570/765]  raw='pass'  →  1
[571/765]  raw='pass'  →  1

 75%|███████▍  | 572/765 [00:51<00:18, 10.20it/s]

[572/765]  raw='pass'  →  1
[573/765]  raw='pass'  →  1

 75%|███████▌  | 574/765 [00:51<00:20,  9.35it/s]

[574/765]  raw='pass you should always ask'  →  1
[575/765]  raw='pass'  →  1

 75%|███████▌  | 577/765 [00:51<00:19,  9.52it/s]

[576/765]  raw='pass'  →  1
[577/765]  raw='pass'  →  1

 76%|███████▌  | 579/765 [00:52<00:22,  8.39it/s]

[578/765]  raw='fail'  →  0
[579/765]  raw='fail'  →  0

 76%|███████▌  | 581/765 [00:52<00:21,  8.62it/s]

[580/765]  raw='pass'  →  1
[581/765]  raw='pass'  →  1
[582/765]  raw='pass'  →  1

 76%|███████▋  | 585/765 [00:52<00:16, 10.82it/s]

[583/765]  raw='fail'  →  0
[584/765]  raw='pass'  →  1
[585/765]  raw='pass'  →  1

 77%|███████▋  | 587/765 [00:52<00:15, 11.61it/s]

[586/765]  raw='pass'  →  1
[587/765]  raw='pass'  →  1
[588/765]  raw='pass'  →  1

 77%|███████▋  | 591/765 [00:53<00:13, 12.92it/s]

[589/765]  raw='pass'  →  1
[590/765]  raw='pass'  →  1
[591/765]  raw='pass'  →  1

 78%|███████▊  | 593/765 [00:53<00:12, 13.45it/s]

[592/765]  raw='pass'  →  1
[593/765]  raw='pass'  →  1
[594/765]  raw='pass'  →  1

 78%|███████▊  | 597/765 [00:53<00:12, 13.69it/s]

[595/765]  raw='pass'  →  1
[596/765]  raw='pass'  →  1
[597/765]  raw='pass'  →  1

 78%|███████▊  | 599/765 [00:53<00:12, 13.78it/s]

[598/765]  raw='pass'  →  1
[599/765]  raw='pass'  →  1
[600/765]  raw='fail'  →  0

 79%|███████▉  | 603/765 [00:54<00:12, 13.19it/s]

[601/765]  raw='pass'  →  1
[602/765]  raw='pass'  →  1
[603/765]  raw='pass'  →  1

 79%|███████▉  | 605/765 [00:54<00:11, 13.41it/s]

[604/765]  raw='pass'  →  1
[605/765]  raw='pass'  →  1
[606/765]  raw='pass'  →  1

 80%|███████▉  | 609/765 [00:54<00:11, 13.85it/s]

[607/765]  raw='pass'  →  1
[608/765]  raw='pass'  →  1
[609/765]  raw='pass'  →  1

 80%|███████▉  | 611/765 [00:54<00:11, 13.85it/s]

[610/765]  raw='pass'  →  1
[611/765]  raw='pass'  →  1
[612/765]  raw='fail'  →  0

 80%|████████  | 615/765 [00:54<00:11, 13.54it/s]

[613/765]  raw='pass'  →  1
[614/765]  raw='pass'  →  1
[615/765]  raw='pass'  →  1

 81%|████████  | 617/765 [00:55<00:10, 13.47it/s]

[616/765]  raw='pass'  →  1
[617/765]  raw='pass'  →  1
[618/765]  raw='pass'  →  1

 81%|████████  | 621/765 [00:55<00:10, 13.91it/s]

[619/765]  raw='pass'  →  1
[620/765]  raw='pass'  →  1
[621/765]  raw='pass'  →  1

 81%|████████▏ | 623/765 [00:55<00:10, 13.98it/s]

[622/765]  raw='pass'  →  1
[623/765]  raw='pass'  →  1
[624/765]  raw='pass'  →  1

 82%|████████▏ | 627/765 [00:55<00:09, 14.37it/s]

[625/765]  raw='pass'  →  1
[626/765]  raw='pass'  →  1
[627/765]  raw='pass'  →  1

 82%|████████▏ | 629/765 [00:55<00:09, 14.27it/s]

[628/765]  raw='pass'  →  1
[629/765]  raw='pass'  →  1
[630/765]  raw='fail'  →  0

 83%|████████▎ | 633/765 [00:56<00:10, 12.56it/s]

[631/765]  raw='fail'  →  0
[632/765]  raw='fail'  →  0
[633/765]  raw='pass'  →  1

 83%|████████▎ | 635/765 [00:56<00:10, 12.98it/s]

[634/765]  raw='pass'  →  1
[635/765]  raw='pass'  →  1
[636/765]  raw='pass'  →  1

 84%|████████▎ | 639/765 [00:56<00:09, 13.01it/s]

[637/765]  raw='pass'  →  1
[638/765]  raw='pass'  →  1
[639/765]  raw='fail'  →  0

 84%|████████▍ | 641/765 [00:56<00:09, 12.89it/s]

[640/765]  raw='pass'  →  1
[641/765]  raw='fail'  →  0
[642/765]  raw='pass'  →  1

 84%|████████▍ | 645/765 [00:57<00:08, 13.64it/s]

[643/765]  raw='pass'  →  1
[644/765]  raw='pass'  →  1
[645/765]  raw='pass'  →  1

 85%|████████▍ | 647/765 [00:57<00:08, 13.76it/s]

[646/765]  raw='pass'  →  1
[647/765]  raw='pass'  →  1
[648/765]  raw='pass'  →  1

 85%|████████▌ | 651/765 [00:57<00:08, 13.07it/s]

[649/765]  raw='pass'  →  1
[650/765]  raw='fail'  →  0
[651/765]  raw='fail'  →  0

 85%|████████▌ | 653/765 [00:57<00:08, 13.28it/s]

[652/765]  raw='pass'  →  1
[653/765]  raw='pass'  →  1
[654/765]  raw='pass'  →  1

 86%|████████▌ | 657/765 [00:58<00:08, 13.33it/s]

[655/765]  raw='pass'  →  1
[656/765]  raw='pass'  →  1
[657/765]  raw='fail'  →  0

 86%|████████▌ | 659/765 [00:58<00:07, 13.39it/s]

[658/765]  raw='pass'  →  1
[659/765]  raw='pass'  →  1
[660/765]  raw='pass'  →  1

 87%|████████▋ | 663/765 [00:58<00:07, 12.86it/s]

[661/765]  raw='pass'  →  1
[662/765]  raw='fail'  →  0
[663/765]  raw='fail'  →  0

 87%|████████▋ | 665/765 [00:58<00:07, 12.76it/s]

[664/765]  raw='pass'  →  1
[665/765]  raw='fail'  →  0
[666/765]  raw='pass'  →  1

 87%|████████▋ | 669/765 [00:58<00:07, 12.79it/s]

[667/765]  raw='pass'  →  1
[668/765]  raw='pass'  →  1
[669/765]  raw='fail'  →  0

 88%|████████▊ | 671/765 [00:59<00:07, 13.10it/s]

[670/765]  raw='pass'  →  1
[671/765]  raw='pass'  →  1
[672/765]  raw='pass'  →  1

 88%|████████▊ | 675/765 [00:59<00:06, 13.17it/s]

[673/765]  raw='pass'  →  1
[674/765]  raw='pass'  →  1
[675/765]  raw='pass'  →  1

 88%|████████▊ | 677/765 [00:59<00:06, 13.40it/s]

[676/765]  raw='pass'  →  1
[677/765]  raw='pass'  →  1
[678/765]  raw='pass'  →  1

 89%|████████▉ | 681/765 [00:59<00:06, 13.84it/s]

[679/765]  raw='pass'  →  1
[680/765]  raw='pass'  →  1
[681/765]  raw='pass'  →  1

 89%|████████▉ | 683/765 [00:59<00:05, 13.89it/s]

[682/765]  raw='pass'  →  1
[683/765]  raw='pass'  →  1
[684/765]  raw='fail'  →  0

 90%|████████▉ | 687/765 [01:00<00:05, 13.20it/s]

[685/765]  raw='pass'  →  1
[686/765]  raw='pass'  →  1
[687/765]  raw='pass'  →  1

 90%|█████████ | 691/765 [01:00<00:05, 13.87it/s]

[688/765]  raw='pass'  →  1
[689/765]  raw='pass'  →  1
[690/765]  raw='pass'  →  1
[691/765]  raw='pass'  →  1

 91%|█████████ | 695/765 [01:00<00:04, 14.24it/s]

[692/765]  raw='pass'  →  1
[693/765]  raw='pass'  →  1
[694/765]  raw='pass'  →  1
[695/765]  raw='pass'  →  1

 91%|█████████▏| 699/765 [01:01<00:04, 14.71it/s]

[696/765]  raw='pass'  →  1
[697/765]  raw='pass'  →  1
[698/765]  raw='pass'  →  1
[699/765]  raw='pass'  →  1

 92%|█████████▏| 701/765 [01:01<00:04, 13.91it/s]

[700/765]  raw='pass'  →  1
[701/765]  raw='pass'  →  1
[702/765]  raw='fail'  →  0

 92%|█████████▏| 705/765 [01:01<00:04, 13.14it/s]

[703/765]  raw='pass'  →  1
[704/765]  raw='pass'  →  1
[705/765]  raw='fail'  →  0

 92%|█████████▏| 707/765 [01:01<00:04, 13.47it/s]

[706/765]  raw='pass'  →  1
[707/765]  raw='pass'  →  1
[708/765]  raw='pass'  →  1

 93%|█████████▎| 711/765 [01:02<00:04, 13.32it/s]

[709/765]  raw='pass'  →  1
[710/765]  raw='pass'  →  1
[711/765]  raw='fail'  →  0

 93%|█████████▎| 713/765 [01:02<00:03, 13.56it/s]

[712/765]  raw='pass'  →  1
[713/765]  raw='pass'  →  1
[714/765]  raw='fail'  →  0

 94%|█████████▎| 717/765 [01:02<00:03, 12.52it/s]

[715/765]  raw='pass'  →  1
[716/765]  raw='pass'  →  1
[717/765]  raw='pass'  →  1

 94%|█████████▍| 719/765 [01:02<00:03, 11.97it/s]

[718/765]  raw='pass'  →  1
[719/765]  raw='pass'  →  1

 94%|█████████▍| 721/765 [01:02<00:04, 10.92it/s]

[720/765]  raw='fail'  →  0
[721/765]  raw='pass'  →  1
[722/765]  raw='pass'  →  1

 95%|█████████▍| 723/765 [01:03<00:03, 10.64it/s]

[723/765]  raw='fail'  →  0
[724/765]  raw='pass'  →  1

 95%|█████████▌| 727/765 [01:03<00:03, 10.50it/s]

[725/765]  raw='fail'  →  0
[726/765]  raw='pass'  →  1
[727/765]  raw='pass'  →  1

 95%|█████████▌| 729/765 [01:03<00:03, 10.84it/s]

[728/765]  raw='pass'  →  1
[729/765]  raw='pass'  →  1
[730/765]  raw='fail'  →  0

 96%|█████████▌| 733/765 [01:04<00:03, 10.51it/s]

[731/765]  raw='pass'  →  1
[732/765]  raw='pass'  →  1
[733/765]  raw='pass'  →  1

 96%|█████████▌| 735/765 [01:04<00:02, 10.62it/s]

[734/765]  raw='pass'  →  1
[735/765]  raw='pass'  →  1
[736/765]  raw='pass'  →  1

 96%|█████████▋| 737/765 [01:04<00:02,  9.89it/s]

[737/765]  raw='pass'  →  1
[738/765]  raw='fail'  →  0

 97%|█████████▋| 741/765 [01:04<00:02, 10.04it/s]

[739/765]  raw='fail'  →  0
[740/765]  raw='fail'  →  0
[741/765]  raw='pass'  →  1

 97%|█████████▋| 743/765 [01:05<00:02, 10.88it/s]

[742/765]  raw='pass'  →  1
[743/765]  raw='pass'  →  1
[744/765]  raw='pass'  →  1

 98%|█████████▊| 747/765 [01:05<00:01, 12.41it/s]

[745/765]  raw='pass'  →  1
[746/765]  raw='pass'  →  1
[747/765]  raw='pass'  →  1

 98%|█████████▊| 749/765 [01:05<00:01, 12.69it/s]

[748/765]  raw='pass'  →  1
[749/765]  raw='pass'  →  1
[750/765]  raw='pass'  →  1

 98%|█████████▊| 753/765 [01:05<00:00, 13.56it/s]

[751/765]  raw='pass'  →  1
[752/765]  raw='pass'  →  1
[753/765]  raw='pass'  →  1

 99%|█████████▊| 755/765 [01:05<00:00, 12.94it/s]

[754/765]  raw='fail'  →  0
[755/765]  raw='pass'  →  1
[756/765]  raw='fail'  →  0

 99%|█████████▉| 759/765 [01:06<00:00, 13.00it/s]

[757/765]  raw='earth'  →  -1
[758/765]  raw='pass'  →  1
[759/765]  raw='pass'  →  1

 99%|█████████▉| 761/765 [01:06<00:00, 11.01it/s]

[760/765]  raw='fail grades, i'  →  0
[761/765]  raw='fail'  →  0
[762/765]  raw='pass'  →  1

100%|██████████| 765/765 [01:06<00:00, 11.45it/s]

[763/765]  raw='pass'  →  1
[764/765]  raw='pass'  →  1
[765/765]  raw='pass'  →  1
     y_true  y_pred                   generated y_true_label y_pred_label
0         0       1                        pass         Fail         Pass
1         0       1                        pass         Fail         Pass
2         0       1                        pass         Fail         Pass
3         1       1                        pass         Pass         Pass
4         0       1                        pass         Fail         Pass
5         0       1                        pass         Fail         Pass
6         1       1                        pass         Pass         Pass
7         1       1                        pass         Pass         Pass
8         1       1                        pass         Pass         Pass
9         0       1                        pass         Fail         Pass
10        0       1                        pass         Fail         Pass
11        1       1                        pass         Pass         Pass
12        1       1                        pass         Pass         Pass
13        1       1                        pass         Pass         Pass
14        1       1                        pass         Pass         Pass
15        1       1                        pass         Pass         Pass
16        1       1                        pass         Pass         Pass
17        1       1                        pass         Pass         Pass
18        0       1                        pass         Fail         Pass
19        0       1                       pass.         Fail         Pass
20        0       1                        pass         Fail         Pass
21        0       1                        pass         Fail         Pass
22        0       1                        pass         Fail         Pass
23        1       1                        pass         Pass         Pass
24        1       0                        fail         Pass         Fail
25        1       1                        pass         Pass         Pass
26        0       1                        pass         Fail         Pass
27        1       1                        pass         Pass         Pass
28        1       1                        pass         Pass         Pass
29        0       1                        pass         Fail         Pass
30        1       0                        fail         Pass         Fail
31        0       1                        pass         Fail         Pass
32        1       0                        fail         Pass         Fail
33        0       1                        pass         Fail         Pass
34        0       0                        fail         Fail         Fail
35        1       1                        pass         Pass         Pass
36        1       0                        fail         Pass         Fail
37        0       1                        pass         Fail         Pass
38        1       1                        pass         Pass         Pass
39        1       1                        pass         Pass         Pass
40        1       0                        fail         Pass         Fail
41        0       1                        pass         Fail         Pass
42        0       1                        pass         Fail         Pass
43        1       0                        fail         Pass         Fail
44        0       1                        pass         Fail         Pass
45        0       0                        fail         Fail         Fail
46        0       1                        pass         Fail         Pass
47        1       1                        pass         Pass         Pass
48        0       0                        fail         Fail         Fail
49        1       0             fail, they will         Pass         Fail
50        0       1                        pass         Fail         Pass
51        0       0                        fail         Fail         Fail
52        1       1                        pass         Pass         Pass
53        1       0                        fail         Pass         Fail
54        0       1                        pass         Fail         Pass
55        0       1                        pass         Fail         Pass
56        0       1                        pass         Fail         Pass
57        0       1                        pass         Fail         Pass
58        0       1                        pass         Fail         Pass
59        0       1                        pass         Fail         Pass
60        1       1                        pass         Pass         Pass
61        0       1                        pass         Fail         Pass
62        1       1                        pass         Pass         Pass
63        0       1                        pass         Fail         Pass
64        0       1                        pass         Fail         Pass
65        1       1                        pass         Pass         Pass
66        1       1                        pass         Pass         Pass
67        0       0                        fail         Fail         Fail
68        1       1                        pass         Pass         Pass
69        0       1                        pass         Fail         Pass
70        0       1                        pass         Fail         Pass
71        0       0                        fail         Fail         Fail
72        0       1                        pass         Fail         Pass
73        0       1                        pass         Fail         Pass
74        0       1                        pass         Fail         Pass
75        1       1                        pass         Pass         Pass
76        0       1                        pass         Fail         Pass
77        1       0                        fail         Pass         Fail
78        0       0                        fail         Fail         Fail
79        1       1                        pass         Pass         Pass
80        1       1                        pass         Pass         Pass
81        1       1                        pass         Pass         Pass
82        1       0                        fail         Pass         Fail
83        1       0                        fail         Pass         Fail
84        0       1                        pass         Fail         Pass
85        0       1                        pass         Fail         Pass
86        0       1                        pass         Fail         Pass
87        0       1                        pass         Fail         Pass
88        1       1                        pass         Pass         Pass
89        0       1                        pass         Fail         Pass
90        1       1                        pass         Pass         Pass
91        1       1                        pass         Pass         Pass
92        1       1                        pass         Pass         Pass
93        0       1                        pass         Fail         Pass
94        0       0                        fail         Fail         Fail
95        0       1                        pass         Fail         Pass
96        0       0                        fail         Fail         Fail
97        0       1                        pass         Fail         Pass
98        0       1                        pass         Fail         Pass
99        0       1                        pass         Fail         Pass
100       0       1                        pass         Fail         Pass
101       0       1                        pass         Fail         Pass
102       0       1                        pass         Fail         Pass
103       0       1                        pass         Fail         Pass
104       0       1                        pass         Fail         Pass
105       1       1                        pass         Pass         Pass
106       1       1                        pass         Pass         Pass
107       0       1                        pass         Fail         Pass
108       1       1                        pass         Pass         Pass
109       0       1                        pass         Fail         Pass
110       0       1                        pass         Fail         Pass
111       0       1                        pass         Fail         Pass
112       1       1                        pass         Pass         Pass
113       0       1                        pass         Fail         Pass
114       0       1                        pass         Fail         Pass
115       0       1                        pass         Fail         Pass
116       1       1                        pass         Pass         Pass
117       1       1                        pass         Pass         Pass
118       0       1                        pass         Fail         Pass
119       1       0                        fail         Pass         Fail
120       1       1                        pass         Pass         Pass
121       1       1                        pass         Pass         Pass
122       1      -1                      prompt         Pass          ???
123       1       1                        pass         Pass         Pass
124       0       1                        pass         Fail         Pass
125       0       1                        pass         Fail         Pass
126       0       1                        pass         Fail         Pass
127       0       1                        pass         Fail         Pass
128       0       1                        pass         Fail         Pass
129       1       1                        pass         Pass         Pass
130       0       1                        pass         Fail         Pass
131       0       0                        fail         Fail         Fail
132       0       1                        pass         Fail         Pass
133       0       1                        pass         Fail         Pass
134       0       1                        pass         Fail         Pass
135       0       1          pass, the essay is         Fail         Pass
136       1       0                        fail         Pass         Fail
137       1       0                        fail         Pass         Fail
138       1       0                        fail         Pass         Fail
139       0       1                        pass         Fail         Pass
140       0       1                        pass         Fail         Pass
141       0       1                        pass         Fail         Pass
142       1       0                        fail         Pass         Fail
143       1       1                        pass         Pass         Pass
144       0       1                        pass         Fail         Pass
145       1       1                        pass         Pass         Pass
146       1       1                        pass         Pass         Pass
147       1       1                        pass         Pass         Pass
148       1       1                        pass         Pass         Pass
149       0       1                        pass         Fail         Pass
150       1       1                        pass         Pass         Pass
151       0       0                        fail         Fail         Fail
152       1       1                        pass         Pass         Pass
153       0       1                        pass         Fail         Pass
154       0       1                        pass         Fail         Pass
155       1       1                        pass         Pass         Pass
156       0       1                        pass         Fail         Pass
157       1       0                        fail         Pass         Fail
158       1       1                        pass         Pass         Pass
159       1       0                        fail         Pass         Fail
160       0       1                        pass         Fail         Pass
161       0       0                        fail         Fail         Fail
162       0       1                        pass         Fail         Pass
163       1       1                        pass         Pass         Pass
164       0       0                        fail         Fail         Fail
165       0       1                        pass         Fail         Pass
166       0       1                        pass         Fail         Pass
167       0       1                        pass         Fail         Pass
168       1       1                        pass         Pass         Pass
169       1       1                        pass         Pass         Pass
170       1       1                        pass         Pass         Pass
171       1       1                        pass         Pass         Pass
172       1       1                        pass         Pass         Pass
173       1       0                        fail         Pass         Fail
174       0       1                        pass         Fail         Pass
175       0       1                        pass         Fail         Pass
176       0       1                        pass         Fail         Pass
177       0       1                        pass         Fail         Pass
178       1       1                        pass         Pass         Pass
179       0       0                        fail         Fail         Fail
180       0       0                        fail         Fail         Fail
181       0       0                        fail         Fail         Fail
182       0       1                        pass         Fail         Pass
183       0       0                        fail         Fail         Fail
184       1       1                        pass         Pass         Pass
185       1       1                        pass         Pass         Pass
186       0       1                        pass         Fail         Pass
187       0       1                        pass         Fail         Pass
188       1       1                        pass         Pass         Pass
189       1       1                        pass         Pass         Pass
190       0       1                        pass         Fail         Pass
191       1       1                        pass         Pass         Pass
192       0       1                        pass         Fail         Pass
193       0       1                        pass         Fail         Pass
194       1       1                        pass         Pass         Pass
195       0       0                        fail         Fail         Fail
196       1       1                        pass         Pass         Pass
197       0       1                        pass         Fail         Pass
198       1       1                        pass         Pass         Pass
199       0       0                        fail         Fail         Fail
200       0       1                        pass         Fail         Pass
201       1       0                        fail         Pass         Fail
202       0       1                        pass         Fail         Pass
203       1       1                        pass         Pass         Pass
204       0       1                        pass         Fail         Pass
205       0       1                        pass         Fail         Pass
206       1       1                        pass         Pass         Pass
207       0       1                        pass         Fail         Pass
208       0       1                        pass         Fail         Pass
209       0       1                        pass         Fail         Pass
210       0       1                        pass         Fail         Pass
211       0       1                        pass         Fail         Pass
212       1       1                        pass         Pass         Pass
213       0       1                        pass         Fail         Pass
214       0       1                        pass         Fail         Pass
215       0       1                        pass         Fail         Pass
216       0       0                        fail         Fail         Fail
217       1       1                        pass         Pass         Pass
218       1       1                        pass         Pass         Pass
219       0       0                        fail         Fail         Fail
220       0       1                        pass         Fail         Pass
221       0       0                        fail         Fail         Fail
222       1       0                        fail         Pass         Fail
223       1       1                        pass         Pass         Pass
224       0       1                        pass         Fail         Pass
225       1       1                        pass         Pass         Pass
226       0       1                        pass         Fail         Pass
227       0       1                        pass         Fail         Pass
228       0       1                        pass         Fail         Pass
229       0       1                        pass         Fail         Pass
230       1       1                        pass         Pass         Pass
231       1       1                        pass         Pass         Pass
232       0       1                        pass         Fail         Pass
233       0       1                        pass         Fail         Pass
234       1       1                        pass         Pass         Pass
235       0       1                        pass         Fail         Pass
236       0       1                        pass         Fail         Pass
237       0       1                        pass         Fail         Pass
238       1       1                        pass         Pass         Pass
239       0       0                        fail         Fail         Fail
240       0       1                        pass         Fail         Pass
241       0       1                        pass         Fail         Pass
242       0       1                        pass         Fail         Pass
243       0       1                        pass         Fail         Pass
244       0       1                        pass         Fail         Pass
245       1       1                        pass         Pass         Pass
246       1       1                        pass         Pass         Pass
247       0       1                        pass         Fail         Pass
248       1       1                        pass         Pass         Pass
249       0       1                        pass         Fail         Pass
250       0       1                        pass         Fail         Pass
251       1       0                        fail         Pass         Fail
252       1       1                        pass         Pass         Pass
253       0       0                        fail         Fail         Fail
254       1       1                        pass         Pass         Pass
255       0       1                        pass         Fail         Pass
256       1       1                        pass         Pass         Pass
257       0       1                        pass         Fail         Pass
258       0       0                        fail         Fail         Fail
259       1       1                        pass         Pass         Pass
260       0       1                        pass         Fail         Pass
261       1       1                        pass         Pass         Pass
262       1       1                        pass         Pass         Pass
263       0       0                        fail         Fail         Fail
264       1       1                        pass         Pass         Pass
265       1       1                        pass         Pass         Pass
266       1       1                        pass         Pass         Pass
267       1       1                        pass         Pass         Pass

### Gemma 2 2B

* Differences between gated and not gated model sweet beans...
* I need to activate my HF key

## Gated vs. Non-Gated Models...

Not every model on huggingface is free to just download and go. Some are
**gated**, error of (a 401) and
lose 15 minutes wondering what is wrong. (I did. T-T)

### What's the difference?

* **Non-gated (open) models**: anyone can download them, no login, no token,
  no permission. Just call `from_pretrained(...)` and it works.
    - Examples we used: `TinyLlama/TinyLlama-1.1B-Chat-v1.0`, `google/flan-t5-large`
    - Also ungated: Qwen, SmolLM, most community models

* **Gated models**: the owner (usually a big company) requires you to
  **agree to a license first** before the model can be downloaded. The weights are still
  free, but access is controlled.
    - Examples: `google/gemma-2-2b-it` (Google), `meta-llama/*` (Meta)
    - Why gated? License terms, acceptable-use policies, "know who's using it"

### The gotcha: TWO things are required, not one
(dont be me)

1. **Accept the license in the browser (one-time).**
   Go to the model page and while logged in, and click to accept the terms. Access is usually instant.
     * This grants YOUR ACCOUNT access to this model.

2. **Authenticate the notebook with your unique HF token.**
   The token proves *who you are* and proves *you're allowed in*.
     * You need BOTH. Token without license accepted = still 401.
     * License accepted without token = notebook doesn't know who you are = 401.

In [ ]:
#interactive logging for the workshop
from huggingface_hub import login
login()   # paste your token

In [ ]:
from google.colab import userdata
os.environ["HF_TOKEN"] = userdata.get("B-Llama-3.1-8B-Access")

In [ ]:
# Now this is a gated Model, #no Quant but it is really slow using CPU, moving to to L4GPU to get thigs faster
model_name = "google/gemma-2-2b-it"

# Gemma is decoder only
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token   # Gemma, like Llama, has no dedicated PAD
tokenizer.padding_side = "left"             # left-pad for inference, but we not batching really we dong one essay at a time so padding is not needed either but lets keep it

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float32,   # float32 = CPU safe; switch to float16 if on a T4 GPU
    #HF_TOKEN=HF_TOKEN,
    device_map="auto",           # let HF place it on GPU if available
)

model.config.pad_token_id = tokenizer.eos_token_id # we can star using more fancy coding
# this model is not working

config.json:   0%|          | 0.00/838 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/47.0k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.5MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/288 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

In [ ]:
#HF_TOKEN = "B-Llama-3.1-8B-Access" this way is not working

In [ ]:
print(model)
# what element i would lookhere the attention layers
# the max features here is 8192, this is important to know see below
# "max_position_embeddings": 8192

Gemma2ForCausalLM(
  (model): Gemma2Model(
    (embed_tokens): Gemma2TextScaledWordEmbedding(256000, 2304, padding_idx=0)
    (layers): ModuleList(
      (0-25): 26 x Gemma2DecoderLayer(
        (self_attn): Gemma2Attention(
          (q_proj): Linear(in_features=2304, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2304, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2304, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2304, bias=False)
        )
        (mlp): Gemma2MLP(
          (gate_proj): Linear(in_features=2304, out_features=9216, bias=False)
          (up_proj): Linear(in_features=2304, out_features=9216, bias=False)
          (down_proj): Linear(in_features=9216, out_features=2304, bias=False)
          (act_fn): GELUTanh()
        )
        (input_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
        (post_attention_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
        (pre_feedforward_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
        (post_feedforward_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
      )
    )
    (norm): Gemma2RMSNorm((2304,), eps=1e-06)
    (rotary_emb): Gemma2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=2304, out_features=256000, bias=False)
)

eos
* "eos_token_id": [1, 107]
   * token i the classic en of everything token
   * 107 end of turn, the end of turn token here in GEMM is registered as EOS

pad
  * "pad_token_id": 1. Gemma has a real, dedicated pad token, a single integer.
  * tokenizer.pad_token_id returns a clean 1, exactly the single value generate wants.
    * So for gemma since it has its PAD
      * ad_token_id=tokenizer.pad_token_id
         * hands to generate it 1: correct, clean.

We will not use here
* pad_token_id=tokenizer.eos_token_id
   * We are not combining pad with eos why? Gemma is fancy it has both pad token and eos tokens
     * risks handing generate the list [1, 107]

In [ ]:
print(model.config)
#here i will check dtype if quant worked it showed here
# some elements to look
# attention layers
#"dtype": "float32"
# PAD token as "pad_token_id": 1
# EOS token as
# "eos_token_id": [
#    1,
#    107
#  ]

Gemma2Config {
  "architectures": [
    "Gemma2ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "attn_logit_softcapping": 50.0,
  "bos_token_id": 2,
  "cache_implementation": "hybrid",
  "dtype": "float32",
  "eos_token_id": [
    1,
    107
  ],
  "final_logit_softcapping": 30.0,
  "head_dim": 256,
  "hidden_act": "gelu_pytorch_tanh",
  "hidden_activation": "gelu_pytorch_tanh",
  "hidden_size": 2304,
  "initializer_range": 0.02,
  "intermediate_size": 9216,
  "layer_types": [
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "full_attention"
  ],
  "max_position_embeddings": 8192,
  "model_type": "gemma2",
  "num_attention_heads": 8,
  "num_hidden_layers": 26,
  "num_key_value_heads": 4,
  "pad_token_id": 1,
  "query_pre_attn_scalar": 256,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 10000.0,
    "rope_type": "default"
  },
  "sliding_window": 4096,
  "tie_word_embeddings": true,
  "transformers_version": "5.13.1",
  "use_bidirectional_attention": null,
  "use_cache": true,
  "vocab_size": 256000
}

In [ ]:
print(model.get_memory_footprint() / 1e9, "GB")
#model size increases from float16 to 32

10.45736858 GB

In [ ]:
#model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Vocab size     :", len(tokenizer))
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

# Sanity-check: confirm Pass/Fail tokens exist in vocabulary
pass_id = tokenizer.encode("Pass", add_special_tokens=False)
fail_id = tokenizer.encode("Fail", add_special_tokens=False)
print(f"\nToken check:")
print(f"  'Pass' → token id(s): {pass_id}")
print(f"  'Fail' → token id(s): {fail_id}")

Model loaded on: cuda:0
Vocab size     : 256000
Memory (MB)    : 10457.4

Token check:
  'Pass' → token id(s): [5825]
  'Fail' → token id(s): [15293]

In [ ]:

#model.config.pad_token_id = tokenizer.eos_token_id

Gemma has 2 eos tokens
* "eos_token_id": [1, 107]
   * remember this from model info
So
 * tokenizer.eos_token_id may return a list, not a single integer
 * .generate wants a single int for pad_token_id, and handing it a list can throw an error
    * this part here pad_token_id=tokenizer.eos_token_id
    * How do i know this.....errors here, errors there, erros everywhere

In [ ]:
def predict_gemma(test, model, tokenizer):
    y_pred      = []
    y_generated = []

    model.eval()  # disable training only behavior (we not training here)

    # loop through every prompt in the test set
    for i in tqdm(range(len(test))):  # tqdm gives the progress bar, really helpful

        messages = [{"role": "user", "content": test.iloc[i]["text"]}]
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        # convert the prompt string into token IDs (numeric)
        # we are giving all of this to our model in a language it can understand (tokenize)
        inputs = tokenizer(
            prompt,             #this is the prompt
            return_tensors="pt",  #tensor
            truncation=True,      # cut, not sure how this affect the evaluation
            max_length=8192,   # Llama handles longer context than T5's 512, anything more 2048 bye bye
            padding=False      # one essay at a time, nothing to pad against, less problems
        ).to(model.device)     # move the tokenized prompt to wherever the model lives (cpu/gpu)

        # remember how long the INPUT was, in tokens
        # decoder-only models return input + answer glued together,
        # so we need this to cut the input back off afterwards

        input_len = inputs["input_ids"].shape[1]

        # no gradient tracking, we are not training
        with torch.no_grad():
            # Llama GPT are decoder only no not forget this so --->>>input and output share one stream,
            # so .generate() APPENDS the answer onto the prompt tokens
            outputs = model.generate(
                **inputs,
                max_new_tokens=10,         # only need a word or two ("Pass"/"Fail")
                do_sample=False,           # greedy = deterministic, reproducible in a workshop
                pad_token_id=tokenizer.pad_token_id,  # read above why
            )
        # Where the answerrrrr
        # The key step here: keep only the tokens AFTER the prompt.
        # outputs[0] = [ ...prompt tokens... , ...new answer tokens... ]
        # so lets slice from input_len onward to get ONLY what the model added.

        new_tokens = outputs[0][input_len:]

        # turn those new token IDs back into text
        # skip_special_tokens drops <|assistant|>, </s>, etc.
        generated = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()

        y_generated.append(generated)

        # map the text answer to a label, So
        # contains "pass" -> 1, contains "fail" -> 0, neither -> -1 (unparseable problems)
        if "pass" in generated: y_pred.append(1)
        elif "fail" in generated: y_pred.append(0)
        else: y_pred.append(-1)

        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  → → {y_pred[-1]}")

    return y_pred, y_generated

In [ ]:
i = 0
messages = [{"role": "user", "content": val_sample.iloc[i]["text"]}]
p = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
#we can see the model maker, i mean if you want to see it
print(repr(p[-120:]))   # tail should show ...<start_of_turn>model\n
ins = tokenizer(p, return_tensors="pt").to(model.device)
out = model.generate(**ins, max_new_tokens=10, do_sample=False, pad_token_id=tokenizer.pad_token_id)
print("SLICED:", repr(tokenizer.decode(out[0][ins['input_ids'].shape[1]:], skip_special_tokens=True)))

' is a worthy pursuit despite the dangers.\n\nRespond with one word only (Fail or Pass):<end_of_turn>\n<start_of_turn>model\n'
SLICED: 'Pass \n'

In [ ]:
def predict_t5(test, model, tokenizer):
    y_pred      = []
    y_generated = []

    model.eval()
    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]

        # truncate to 512 tokens — T5's hard limit
        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=False
        ).to(model.device)

        with torch.no_grad():
            # T5 uses .generate() directly, NOT pipeline("text-generation")
            outputs = model.generate(
                **inputs,
                max_new_tokens=5,
            )

        generated = tokenizer.decode(outputs[0], skip_special_tokens=True).strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {y_pred[-1]}")

    return y_pred, y_generated

In [ ]:
## Val first

In [ ]:
# remember this model is at high capacity of float32
# 30m to run 100 using CPU
# 3m to run 100 using L4GPU
# run on val set first
val_sample   = X_val_prompts.iloc[:100].reset_index(drop=True)
y_val_sample = y_val.values[:100]

y_pred, y_generated = predict_gemma(val_sample, model, tokenizer)

results_df = pd.DataFrame({
    "y_true"    : y_val_sample,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask     = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid   = y_val_sample[valid_mask]
y_pred_valid   = [y_pred[i] for i in valid_mask]

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0,1], target_names=["Fail","Pass"], zero_division=0
    ))

  1%|          | 1/100 [00:01<01:58,  1.20s/it]

[  1/100]  raw='pass'  → → 1

  2%|▏         | 2/100 [00:02<01:35,  1.03it/s]

[  2/100]  raw='fail'  → → 0

  3%|▎         | 3/100 [00:03<01:42,  1.05s/it]

[  3/100]  raw='fail'  → → 0

  4%|▍         | 4/100 [00:03<01:27,  1.10it/s]

[  4/100]  raw='fail'  → → 0

  5%|▌         | 5/100 [00:04<01:19,  1.19it/s]

[  5/100]  raw='fail'  → → 0

  6%|▌         | 6/100 [00:05<01:35,  1.01s/it]

[  6/100]  raw='fail'  → → 0

  7%|▋         | 7/100 [00:06<01:28,  1.06it/s]

[  7/100]  raw='fail'  → → 0

  8%|▊         | 8/100 [00:08<01:46,  1.15s/it]

[  8/100]  raw='fail'  → → 0

  9%|▉         | 9/100 [00:08<01:30,  1.01it/s]

[  9/100]  raw='fail'  → → 0

 10%|█         | 10/100 [00:10<01:33,  1.04s/it]

[ 10/100]  raw='pass'  → → 1

 11%|█         | 11/100 [00:10<01:22,  1.08it/s]

[ 11/100]  raw='fail'  → → 0

 12%|█▏        | 12/100 [00:11<01:23,  1.06it/s]

[ 12/100]  raw='fail'  → → 0

 13%|█▎        | 13/100 [00:12<01:22,  1.05it/s]

[ 13/100]  raw='fail'  → → 0

 14%|█▍        | 14/100 [00:13<01:16,  1.13it/s]

[ 14/100]  raw='fail'  → → 0

 15%|█▌        | 15/100 [00:14<01:11,  1.18it/s]

[ 15/100]  raw='fail'  → → 0

 16%|█▌        | 16/100 [00:15<01:10,  1.19it/s]

[ 16/100]  raw='fail'  → → 0

 17%|█▋        | 17/100 [00:16<01:23,  1.01s/it]

[ 17/100]  raw='fail'  → → 0

 18%|█▊        | 18/100 [00:17<01:18,  1.04it/s]

[ 18/100]  raw='fail'  → → 0

 19%|█▉        | 19/100 [00:18<01:15,  1.08it/s]

[ 19/100]  raw='fail'  → → 0

 20%|██        | 20/100 [00:19<01:25,  1.07s/it]

[ 20/100]  raw='fail'  → → 0

 21%|██        | 21/100 [00:20<01:27,  1.11s/it]

[ 21/100]  raw='fail'  → → 0

 22%|██▏       | 22/100 [00:21<01:16,  1.02it/s]

[ 22/100]  raw='fail'  → → 0

 23%|██▎       | 23/100 [00:22<01:16,  1.01it/s]

[ 23/100]  raw='fail'  → → 0

 24%|██▍       | 24/100 [00:23<01:10,  1.08it/s]

[ 24/100]  raw='fail'  → → 0

 25%|██▌       | 25/100 [00:24<01:20,  1.07s/it]

[ 25/100]  raw='fail'  → → 0

 26%|██▌       | 26/100 [00:25<01:20,  1.09s/it]

[ 26/100]  raw='fail'  → → 0

 27%|██▋       | 27/100 [00:26<01:10,  1.03it/s]

[ 27/100]  raw='fail'  → → 0

 28%|██▊       | 28/100 [00:27<01:03,  1.14it/s]

[ 28/100]  raw='fail'  → → 0

 29%|██▉       | 29/100 [00:27<01:01,  1.15it/s]

[ 29/100]  raw='fail'  → → 0

 30%|███       | 30/100 [00:28<01:03,  1.10it/s]

[ 30/100]  raw='pass'  → → 1

 31%|███       | 31/100 [00:30<01:09,  1.01s/it]

[ 31/100]  raw='fail'  → → 0

 32%|███▏      | 32/100 [00:30<01:01,  1.10it/s]

[ 32/100]  raw='fail'  → → 0

 33%|███▎      | 33/100 [00:32<01:06,  1.00it/s]

[ 33/100]  raw='fail'  → → 0

 34%|███▍      | 34/100 [00:34<01:31,  1.39s/it]

[ 34/100]  raw='fail'  → → 0

 35%|███▌      | 35/100 [00:35<01:17,  1.20s/it]

[ 35/100]  raw='fail'  → → 0

 36%|███▌      | 36/100 [00:35<01:08,  1.06s/it]

[ 36/100]  raw='fail'  → → 0

 37%|███▋      | 37/100 [00:36<01:06,  1.06s/it]

[ 37/100]  raw='fail'  → → 0

 38%|███▊      | 38/100 [00:37<01:02,  1.01s/it]

[ 38/100]  raw='fail'  → → 0

 39%|███▉      | 39/100 [00:38<00:59,  1.02it/s]

[ 39/100]  raw='fail'  → → 0

 40%|████      | 40/100 [00:39<00:56,  1.06it/s]

[ 40/100]  raw='fail'  → → 0

 41%|████      | 41/100 [00:41<01:12,  1.23s/it]

[ 41/100]  raw='fail'  → → 0

 42%|████▏     | 42/100 [00:42<01:03,  1.10s/it]

[ 42/100]  raw='fail'  → → 0

 43%|████▎     | 43/100 [00:42<00:55,  1.03it/s]

[ 43/100]  raw='fail'  → → 0

 44%|████▍     | 44/100 [00:44<01:01,  1.09s/it]

[ 44/100]  raw='pass'  → → 1

 45%|████▌     | 45/100 [00:45<00:53,  1.03it/s]

[ 45/100]  raw='fail'  → → 0

 46%|████▌     | 46/100 [00:46<00:53,  1.01it/s]

[ 46/100]  raw='fail'  → → 0

 47%|████▋     | 47/100 [00:47<00:53,  1.01s/it]

[ 47/100]  raw='fail'  → → 0

 48%|████▊     | 48/100 [00:47<00:48,  1.06it/s]

[ 48/100]  raw='pass'  → → 1

 49%|████▉     | 49/100 [00:48<00:47,  1.08it/s]

[ 49/100]  raw='fail'  → → 0

 50%|█████     | 50/100 [00:49<00:44,  1.13it/s]

[ 50/100]  raw='pass'  → → 1

 51%|█████     | 51/100 [00:50<00:43,  1.13it/s]

[ 51/100]  raw='pass'  → → 1

 52%|█████▏    | 52/100 [00:51<00:44,  1.07it/s]

[ 52/100]  raw='pass'  → → 1

 53%|█████▎    | 53/100 [00:52<00:43,  1.08it/s]

[ 53/100]  raw='pass'  → → 1

 54%|█████▍    | 54/100 [00:53<00:50,  1.09s/it]

[ 54/100]  raw='fail'  → → 0

 55%|█████▌    | 55/100 [00:54<00:48,  1.08s/it]

[ 55/100]  raw='fail'  → → 0

 56%|█████▌    | 56/100 [00:57<01:03,  1.45s/it]

[ 56/100]  raw='pass'  → → 1

 57%|█████▋    | 57/100 [00:58<00:59,  1.38s/it]

[ 57/100]  raw='pass'  → → 1

 58%|█████▊    | 58/100 [01:00<01:00,  1.43s/it]

[ 58/100]  raw='fail'  → → 0

 59%|█████▉    | 59/100 [01:01<00:56,  1.39s/it]

[ 59/100]  raw='fail'  → → 0

 60%|██████    | 60/100 [01:02<00:48,  1.21s/it]

[ 60/100]  raw='fail'  → → 0

 61%|██████    | 61/100 [01:03<00:50,  1.30s/it]

[ 61/100]  raw='fail'  → → 0

 62%|██████▏   | 62/100 [01:04<00:46,  1.23s/it]

[ 62/100]  raw='fail'  → → 0

 63%|██████▎   | 63/100 [01:05<00:42,  1.14s/it]

[ 63/100]  raw='fail'  → → 0

 64%|██████▍   | 64/100 [01:06<00:38,  1.06s/it]

[ 64/100]  raw='fail'  → → 0

 65%|██████▌   | 65/100 [01:07<00:37,  1.06s/it]

[ 65/100]  raw='fail'  → → 0

 66%|██████▌   | 66/100 [01:08<00:33,  1.01it/s]

[ 66/100]  raw='fail'  → → 0

 67%|██████▋   | 67/100 [01:09<00:37,  1.13s/it]

[ 67/100]  raw='fail'  → → 0

 68%|██████▊   | 68/100 [01:10<00:33,  1.03s/it]

[ 68/100]  raw='fail'  → → 0

 69%|██████▉   | 69/100 [01:12<00:35,  1.15s/it]

[ 69/100]  raw='fail'  → → 0

 70%|███████   | 70/100 [01:13<00:32,  1.08s/it]

[ 70/100]  raw='fail'  → → 0

 71%|███████   | 71/100 [01:14<00:32,  1.14s/it]

[ 71/100]  raw='fail'  → → 0

 72%|███████▏  | 72/100 [01:15<00:29,  1.04s/it]

[ 72/100]  raw='pass'  → → 1

 73%|███████▎  | 73/100 [01:16<00:31,  1.18s/it]

[ 73/100]  raw='fail'  → → 0

 74%|███████▍  | 74/100 [01:17<00:28,  1.10s/it]

[ 74/100]  raw='fail'  → → 0

 75%|███████▌  | 75/100 [01:19<00:33,  1.36s/it]

[ 75/100]  raw='fail'  → → 0

 76%|███████▌  | 76/100 [01:20<00:33,  1.40s/it]

[ 76/100]  raw='fail'  → → 0

 77%|███████▋  | 77/100 [01:22<00:29,  1.30s/it]

[ 77/100]  raw='fail'  → → 0

 78%|███████▊  | 78/100 [01:22<00:24,  1.12s/it]

[ 78/100]  raw='fail'  → → 0

 79%|███████▉  | 79/100 [01:23<00:22,  1.05s/it]

[ 79/100]  raw='fail'  → → 0

 80%|████████  | 80/100 [01:24<00:21,  1.06s/it]

[ 80/100]  raw='fail'  → → 0

 81%|████████  | 81/100 [01:26<00:22,  1.17s/it]

[ 81/100]  raw='fail'  → → 0

 82%|████████▏ | 82/100 [01:26<00:18,  1.02s/it]

[ 82/100]  raw='pass'  → → 1

 83%|████████▎ | 83/100 [01:28<00:23,  1.37s/it]

[ 83/100]  raw='fail'  → → 0

 84%|████████▍ | 84/100 [01:30<00:22,  1.42s/it]

[ 84/100]  raw='fail'  → → 0

 85%|████████▌ | 85/100 [01:31<00:19,  1.30s/it]

[ 85/100]  raw='pass'  → → 1

 86%|████████▌ | 86/100 [01:32<00:17,  1.23s/it]

[ 86/100]  raw='fail'  → → 0

 87%|████████▋ | 87/100 [01:33<00:15,  1.18s/it]

[ 87/100]  raw='fail'  → → 0

 88%|████████▊ | 88/100 [01:34<00:14,  1.21s/it]

[ 88/100]  raw='pass'  → → 1

 89%|████████▉ | 89/100 [01:36<00:13,  1.21s/it]

[ 89/100]  raw='fail'  → → 0

 90%|█████████ | 90/100 [01:37<00:11,  1.11s/it]

[ 90/100]  raw='fail'  → → 0

 91%|█████████ | 91/100 [01:37<00:09,  1.05s/it]

[ 91/100]  raw='fail'  → → 0

 92%|█████████▏| 92/100 [01:39<00:08,  1.11s/it]

[ 92/100]  raw='fail'  → → 0

 93%|█████████▎| 93/100 [01:40<00:08,  1.20s/it]

[ 93/100]  raw='fail'  → → 0

 94%|█████████▍| 94/100 [01:41<00:06,  1.16s/it]

[ 94/100]  raw='fail'  → → 0

 95%|█████████▌| 95/100 [01:42<00:05,  1.19s/it]

[ 95/100]  raw='fail'  → → 0

 96%|█████████▌| 96/100 [01:43<00:04,  1.07s/it]

[ 96/100]  raw='pass'  → → 1

 97%|█████████▋| 97/100 [01:44<00:02,  1.01it/s]

[ 97/100]  raw='fail'  → → 0

 98%|█████████▊| 98/100 [01:45<00:01,  1.04it/s]

[ 98/100]  raw='fail'  → → 0

 99%|█████████▉| 99/100 [01:46<00:01,  1.05s/it]

[ 99/100]  raw='fail'  → → 0

100%|██████████| 100/100 [01:47<00:00,  1.08s/it]

[100/100]  raw='fail'  → → 0
    y_true  y_pred generated y_true_label y_pred_label
0        1       1      pass         Pass         Pass
1        1       0      fail         Pass         Fail
2        0       0      fail         Fail         Fail
3        0       0      fail         Fail         Fail
4        0       0      fail         Fail         Fail
5        1       0      fail         Pass         Fail
6        0       0      fail         Fail         Fail
7        1       0      fail         Pass         Fail
8        0       0      fail         Fail         Fail
9        1       1      pass         Pass         Pass
10       0       0      fail         Fail         Fail
11       1       0      fail         Pass         Fail
12       0       0      fail         Fail         Fail
13       0       0      fail         Fail         Fail
14       0       0      fail         Fail         Fail
15       0       0      fail         Fail         Fail
16       1       0      fail         Pass         Fail
17       0       0      fail         Fail         Fail
18       0       0      fail         Fail         Fail
19       1       0      fail         Pass         Fail
20       0       0      fail         Fail         Fail
21       0       0      fail         Fail         Fail
22       0       0      fail         Fail         Fail
23       0       0      fail         Fail         Fail
24       1       0      fail         Pass         Fail
25       1       0      fail         Pass         Fail
26       0       0      fail         Fail         Fail
27       0       0      fail         Fail         Fail
28       0       0      fail         Fail         Fail
29       1       1      pass         Pass         Pass
30       1       0      fail         Pass         Fail
31       0       0      fail         Fail         Fail
32       1       0      fail         Pass         Fail
33       1       0      fail         Pass         Fail
34       0       0      fail         Fail         Fail
35       0       0      fail         Fail         Fail
36       0       0      fail         Fail         Fail
37       1       0      fail         Pass         Fail
38       0       0      fail         Fail         Fail
39       0       0      fail         Fail         Fail
40       0       0      fail         Fail         Fail
41       0       0      fail         Fail         Fail
42       0       0      fail         Fail         Fail
43       1       1      pass         Pass         Pass
44       0       0      fail         Fail         Fail
45       1       0      fail         Pass         Fail
46       0       0      fail         Fail         Fail
47       0       1      pass         Fail         Pass
48       0       0      fail         Fail         Fail
49       0       1      pass         Fail         Pass
50       0       1      pass         Fail         Pass
51       0       1      pass         Fail         Pass
52       0       1      pass         Fail         Pass
53       1       0      fail         Pass         Fail
54       1       0      fail         Pass         Fail
55       0       1      pass         Fail         Pass
56       1       1      pass         Pass         Pass
57       1       0      fail         Pass         Fail
58       1       0      fail         Pass         Fail
59       0       0      fail         Fail         Fail
60       1       0      fail         Pass         Fail
61       1       0      fail         Pass         Fail
62       0       0      fail         Fail         Fail
63       0       0      fail         Fail         Fail
64       1       0      fail         Pass         Fail
65       0       0      fail         Fail         Fail
66       1       0      fail         Pass         Fail
67       0       0      fail         Fail         Fail
68       1       0      fail         Pass         Fail
69       0       0      fail         Fail         Fail
70       1       0      fail         Pass         Fail
71       0       1      pass         Fail         Pass
72       1       0      fail         Pass         Fail
73       0       0      fail         Fail         Fail
74       1       0      fail         Pass         Fail
75       1       0      fail         Pass         Fail
76       0       0      fail         Fail         Fail
77       0       0      fail         Fail         Fail
78       0       0      fail         Fail         Fail
79       0       0      fail         Fail         Fail
80       1       0      fail         Pass         Fail
81       0       1      pass         Fail         Pass
82       1       0      fail         Pass         Fail
83       1       0      fail         Pass         Fail
84       1       1      pass         Pass         Pass
85       0       0      fail         Fail         Fail
86       1       0      fail         Pass         Fail
87       0       1      pass         Fail         Pass
88       0       0      fail         Fail         Fail
89       0       0      fail         Fail         Fail
90       1       0      fail         Pass         Fail
91       1       0      fail         Pass         Fail
92       1       0      fail         Pass         Fail
93       1       0      fail         Pass         Fail
94       1       0      fail         Pass         Fail
95       0       1      pass         Fail         Pass
96       0       0      fail         Fail         Fail
97       0       0      fail         Fail         Fail
98       1       0      fail         Pass         Fail
99       0       0      fail         Fail         Fail

Accuracy : 0.5400
              precision    recall  f1-score   support

        Fail       0.57      0.83      0.68        58
        Pass       0.38      0.14      0.21        42

    accuracy                           0.54       100
   macro avg       0.47      0.49      0.44       100
weighted avg       0.49      0.54      0.48       100

In [ ]:
#testing

In [ ]:
# run on full test set
# will take too long
y_pred, y_generated = predict_gemma(X_test_prompts, model, tokenizer)

#test
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

#QUANTIZATION

* What is quant?? well it is a technique that compress the model, it reduces llm by converting/changing their weights activations. Quantified Weight activation from maybe high precision formats like FP32 or FP16 to lower representation like INT8 (8bit quant) or INT4 (4bit quant)

* Models are usually represented in bfloat 16bits at least in huggingface (bfloat 16 is huge is one of the latest, so a100 GPU and up)

The precision of model from Hugging Face may vary depending on how the model was stored (e.g., FP32 weights or bP16 weights), but i do think most models are bf16
  * To run BF16 A100 GPU are required, remember bf16 is one of the latest precision
    * https://huggingface.co/docs/optimum/en/concept_guides/quantization
    *  https://huggingface.co/docs/hub/en/gguf#quantization-types

### Mistral 7B **4bit**

Why quant Mistral?
* Mistral-7B in float16 is ~14 GB
   * too big for a T4's 16 GB alongside activations. 4-bit quantization (load_in_4bit) compresses the weights to 4 GB, so it fits. This is the only way to run a 7B on a T4 we cannot run this model using cpu
   * nf4 + double quant + fp16 compute are the standard QLoRA-style settings
      * nf4 is the 4-bit number format optimized for neural-net weights
      * double-quant squeezes a bit more,
      * compute power stays in fp16 so the math is still reasonably precise

In [ ]:
!pip install -U bitsandbytes>=0.46.1 accelerate transformers

In [ ]:
from google.colab import userdata
from huggingface_hub import login

HF_TOKEN = userdata.get('B-Llama-3.1-8B-Access')   # stored securely in Colab secrets
login(token=HF_TOKEN)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.
WARNING:huggingface_hub._login:Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [ ]:
import bitsandbytes as bnb
print("bitsandbytes version:", bnb.__version__)

bitsandbytes version: 0.49.2

In [ ]:
# 8m GPU 4T
# 1m GPU L4
# Load Mistral 7B with 4-bit quantization (required for T4 16GB)
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "mistralai/Mistral-7B-Instruct-v0.2"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16, # see we are float16
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    #HF_TOKEN= HF_TOKEN,
)
model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

Model loaded on: cuda:0
Memory (MB)    : 4014.5

In [ ]:
print(model)
# what element i would lookhere the attention layers
# the max features here is 8192, this is important to know see below
# "max_position_embeddings": 8192

MistralForCausalLM(
  (model): MistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): MistralRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): MistralRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): MistralRMSNorm((4096,), eps=1e-05)
    (rotary_emb): MistralRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)

eos
* "eos_token_id": 2

pad
  * "pad_token_id": 2
For Mistral the eos and pad point to the same token. So here
 * tokenizer.pad_token = tokenizer.eos_token
 * pad_token_id=tokenizer.pad_token_id both resolve to the same value and work without conflict.

We dont have to worry about max token here
*  "max_position_embeddings": 32768,

In [ ]:
print(model.config)
#here i will check dtype if quant worked it showed here
# some elements to look
# attention layers
#"dtype":
# PAD token as "pad_token_id":
# EOS token as "eos_token_id"

MistralConfig {
  "architectures": [
    "MistralForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "dtype": "bfloat16",
  "eos_token_id": 2,
  "head_dim": 128,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 32768,
  "model_type": "mistral",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "pad_token_id": 2,
  "quantization_config": {
    "_load_in_4bit": true,
    "_load_in_8bit": false,
    "bnb_4bit_compute_dtype": "float16",
    "bnb_4bit_quant_storage": "uint8",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false,
    "quant_method": "bitsandbytes"
  },
  "rms_norm_eps": 1e-05,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": false,
  "transformers_version": "5.13.1",
  "use_cache": true,
  "vocab_size": 32000
}

In [ ]:
print(model.get_memory_footprint() / 1e9, "GB")
#model size increases from float16 to 32

4.01448192 GB

In [ ]:
#model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Vocab size     :", len(tokenizer))
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

# Sanity-check: confirm Pass/Fail tokens exist in vocabulary
pass_id = tokenizer.encode("Pass", add_special_tokens=False)
fail_id = tokenizer.encode("Fail", add_special_tokens=False)
print(f"\nToken check:")
print(f"  'Pass' : token id(s): {pass_id}")
print(f"  'Fail' : token id(s): {fail_id}")

Model loaded on: cuda:0
Vocab size     : 32000
Memory (MB)    : 4014.5

Token check:
  'Pass' : token id(s): [8201]
  'Fail' : token id(s): [28278]

In [ ]:
def predict_mistral(test, model, tokenizer):
    y_pred      = []
    y_generated = []

    model.eval()  # disable training only behavior (we not training here)

    # loop through every prompt in the test set
    for i in tqdm(range(len(test))):  # tqdm gives the progress bar, really helpful

        messages = [{"role": "user", "content": test.iloc[i]["text"]}]
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        # convert the prompt string into token IDs (numeric)
        # we are giving all of this to our model in a language it can understand (tokenize)
        inputs = tokenizer(
            prompt,             #this is the prompt
            return_tensors="pt",  #tensor
            truncation=True,      # cut, not sure how this affect the evaluation
            max_length=10000,   # Llama handles longer context than T5's 512, anything more 2048 bye bye
            padding=False      # one essay at a time, nothing to pad against, less problems
        ).to(model.device)     # move the tokenized prompt to wherever the model lives (cpu/gpu)

        # remember how long the INPUT was, in tokens
        # decoder-only models return input + answer glued together,
        # so we need this to cut the input back off afterwards

        input_len = inputs["input_ids"].shape[1]

        # no gradient tracking, we are not training
        with torch.no_grad():
            # Llama GPT are decoder only no not forget this so --->>>input and output share one stream,
            # so .generate() APPENDS the answer onto the prompt tokens
            outputs = model.generate(
                **inputs,
                max_new_tokens=10,         # only need a word or two ("Pass"/"Fail")
                do_sample=False,           # greedy = deterministic, reproducible in a workshop
                pad_token_id=tokenizer.eos_token_id,
            )
        # Where the answerrrrr
        # The key step here: keep only the tokens AFTER the prompt.
        # outputs[0] = [ ...prompt tokens... , ...new answer tokens... ]
        # so lets slice from input_len onward to get ONLY what the model added.

        new_tokens = outputs[0][input_len:]

        # turn those new token IDs back into text
        # skip_special_tokens drops <|assistant|>, </s>, etc.
        generated = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()

        y_generated.append(generated)

        # map the text answer to a label, So
        # contains "pass" -> 1, contains "fail" -> 0, neither -> -1 (unparseable problems)
        if "pass" in generated: y_pred.append(1)
        elif "fail" in generated: y_pred.append(0)
        else: y_pred.append(-1)

        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  → → {y_pred[-1]}")

    return y_pred, y_generated

In [ ]:
#sample of 100
val_sample   = X_val_prompts.iloc[:100].reset_index(drop=True)
y_val_sample = y_val.values[:100]

y_pred, y_generated = predict_mistral(val_sample, model, tokenizer)

results_df = pd.DataFrame({
    "y_true"    : y_val_sample,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask     = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid   = y_val_sample[valid_mask]
y_pred_valid   = [y_pred[i] for i in valid_mask]

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0,1], target_names=["Fail","Pass"], zero_division=0
    ))

  0%|          | 0/100 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
  1%|          | 1/100 [00:02<03:52,  2.34s/it]

[  1/100]  raw='pass. the essay presents a clear argument for the'  → → 1

  2%|▏         | 2/100 [00:04<03:22,  2.07s/it]

[  2/100]  raw='pass. the essay presents a clear argument for why'  → → 1

  3%|▎         | 3/100 [00:06<03:24,  2.11s/it]

[  3/100]  raw='fail. the essay lacks a clear argument and'  → → 0

  4%|▍         | 4/100 [00:07<03:02,  1.90s/it]

[  4/100]  raw='pass.

the essay presents a clear position'  → → 1

  5%|▌         | 5/100 [00:09<02:49,  1.79s/it]

[  5/100]  raw='pass. the essay demonstrates a clear understanding of'  → → 1

  6%|▌         | 6/100 [00:11<03:00,  1.92s/it]

[  6/100]  raw='fail. the essay lacks clear argumentation and'  → → 0

  7%|▋         | 7/100 [00:13<02:51,  1.84s/it]

[  7/100]  raw='fail. the essay expresses a negative attitude towards'  → → 0

  8%|▊         | 8/100 [00:15<03:08,  2.05s/it]

[  8/100]  raw='pass. the essay presents a clear argument against the'  → → 1

  9%|▉         | 9/100 [00:17<02:52,  1.89s/it]

[  9/100]  raw='pass. the essay demonstrates a clear understanding of'  → → 1

 10%|█         | 10/100 [00:19<02:57,  1.97s/it]

[ 10/100]  raw='pass. the essay presents a clear argument with well'  → → 1

 11%|█         | 11/100 [00:21<02:44,  1.85s/it]

[ 11/100]  raw='pass. the essay presents a clear position on the'  → → 1

 12%|█▏        | 12/100 [00:22<02:24,  1.64s/it]

[ 12/100]  raw='fail.'  → → 0

 13%|█▎        | 13/100 [00:24<02:26,  1.69s/it]

[ 13/100]  raw='fail. the essay contains several grammatical errors'  → → 0

 14%|█▍        | 14/100 [00:25<02:23,  1.67s/it]

[ 14/100]  raw='pass. the essay presents clear ideas and effectively explains'  → → 1

 15%|█▌        | 15/100 [00:27<02:21,  1.67s/it]

[ 15/100]  raw='pass. the essay follows a clear structure, has'  → → 1

 16%|█▌        | 16/100 [00:29<02:20,  1.67s/it]

[ 16/100]  raw='pass. the essay presents a clear position and uses'  → → 1

 17%|█▋        | 17/100 [00:31<02:32,  1.84s/it]

[ 17/100]  raw='pass. the essay presents clear reasons for the author'  → → 1

 18%|█▊        | 18/100 [00:33<02:29,  1.83s/it]

[ 18/100]  raw='pass. the essay presents a clear and well-'  → → 1

 19%|█▉        | 19/100 [00:34<02:24,  1.78s/it]

[ 19/100]  raw='pass. the essay presents a clear opinion on the'  → → 1

 20%|██        | 20/100 [00:37<02:35,  1.94s/it]

[ 20/100]  raw='pass. the essay presents a clear and well-'  → → 1

 21%|██        | 21/100 [00:39<02:38,  2.01s/it]

[ 21/100]  raw='fail. the essay is disorganized, contains'  → → 0

 22%|██▏       | 22/100 [00:40<02:28,  1.90s/it]

[ 22/100]  raw='fail. the essay contains several grammatical errors'  → → 0

 23%|██▎       | 23/100 [00:42<02:29,  1.94s/it]

[ 23/100]  raw='pass. the essay expresses a clear opinion on'  → → 1

 24%|██▍       | 24/100 [00:44<02:20,  1.85s/it]

[ 24/100]  raw='pass. the essay presents a clear and coherent'  → → 1

 25%|██▌       | 25/100 [00:46<02:28,  1.98s/it]

[ 25/100]  raw='pass. the essay presents clear ideas and arguments,'  → → 1

 26%|██▌       | 26/100 [00:49<02:30,  2.04s/it]

[ 26/100]  raw='pass. the essay effectively argues against cell phone'  → → 1

 27%|██▋       | 27/100 [00:50<02:19,  1.92s/it]

[ 27/100]  raw='fail. the essay lacks clear organization, proper'  → → 0

 28%|██▊       | 28/100 [00:52<02:12,  1.84s/it]

[ 28/100]  raw='fail. the essay lacks clear and concise'  → → 0

 29%|██▉       | 29/100 [00:54<02:07,  1.80s/it]

[ 29/100]  raw='pass. the essay presents a clear and well-'  → → 1

 30%|███       | 30/100 [00:56<02:11,  1.88s/it]

[ 30/100]  raw='pass. the essay effectively argues for the importance'  → → 1

 31%|███       | 31/100 [00:58<02:16,  1.98s/it]

[ 31/100]  raw='pass. the essay presents a clear argument for the'  → → 1

 32%|███▏      | 32/100 [00:59<02:06,  1.86s/it]

[ 32/100]  raw='pass. the essay presents a clear position and provides'  → → 1

 33%|███▎      | 33/100 [01:02<02:09,  1.93s/it]

[ 33/100]  raw='pass. the essay provides a clear and well-'  → → 1

 34%|███▍      | 34/100 [01:05<02:31,  2.30s/it]

[ 34/100]  raw='pass. the essay is well-written, clear'  → → 1

 35%|███▌      | 35/100 [01:06<02:16,  2.10s/it]

[ 35/100]  raw='fail. the essay lacks clear organization and co'  → → 0

 36%|███▌      | 36/100 [01:08<02:06,  1.97s/it]

[ 36/100]  raw='fail. the essay lacks clear organization, contains'  → → 0

 37%|███▋      | 37/100 [01:10<02:02,  1.94s/it]

[ 37/100]  raw='fail. the essay lacks clear organization, contains'  → → 0

 38%|███▊      | 38/100 [01:12<01:58,  1.91s/it]

[ 38/100]  raw='pass. the essay presents a clear and well-'  → → 1

 39%|███▉      | 39/100 [01:14<01:55,  1.89s/it]

[ 39/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 40%|████      | 40/100 [01:15<01:50,  1.85s/it]

[ 40/100]  raw='pass. the essay presents clear reasons for allowing cell'  → → 1

 41%|████      | 41/100 [01:18<02:05,  2.12s/it]

[ 41/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 42%|████▏     | 42/100 [01:20<01:55,  1.99s/it]

[ 42/100]  raw='fail. the essay lacks clear organization, proper'  → → 0

 43%|████▎     | 43/100 [01:21<01:46,  1.87s/it]

[ 43/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 44%|████▍     | 44/100 [01:24<01:52,  2.01s/it]

[ 44/100]  raw='pass. the essay presents clear and well-develop'  → → 1

 45%|████▌     | 45/100 [01:25<01:43,  1.88s/it]

[ 45/100]  raw='pass. the essay presents clear arguments and uses logical'  → → 1

 46%|████▌     | 46/100 [01:27<01:41,  1.87s/it]

[ 46/100]  raw='pass. the essay presents clear reasons against allowing cell'  → → 1

 47%|████▋     | 47/100 [01:29<01:39,  1.87s/it]

[ 47/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 48%|████▊     | 48/100 [01:31<01:33,  1.79s/it]

[ 48/100]  raw='pass. the essay demonstrates an understanding of the'  → → 1

 49%|████▉     | 49/100 [01:33<01:35,  1.87s/it]

[ 49/100]  raw='pass. the essay presents clear reasons and arguments,'  → → 1

 50%|█████     | 50/100 [01:34<01:32,  1.86s/it]

[ 50/100]  raw='pass. the essay provides clear examples and effectively arg'  → → 1

 51%|█████     | 51/100 [01:36<01:29,  1.83s/it]

[ 51/100]  raw='pass. the essay presents clear benefits of distance learning'  → → 1

 52%|█████▏    | 52/100 [01:38<01:28,  1.85s/it]

[ 52/100]  raw='pass. the essay presents clear reasons for limiting car'  → → 1

 53%|█████▎    | 53/100 [01:40<01:24,  1.81s/it]

[ 53/100]  raw='pass. the essay presents a clear position and provides'  → → 1

 54%|█████▍    | 54/100 [01:42<01:29,  1.94s/it]

[ 54/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 55%|█████▌    | 55/100 [01:44<01:26,  1.92s/it]

[ 55/100]  raw='pass. the essay presents clear and logical arguments with'  → → 1

 56%|█████▌    | 56/100 [01:48<01:48,  2.45s/it]

[ 56/100]  raw='pass. the essay presents a clear and well-'  → → 1

 57%|█████▋    | 57/100 [01:50<01:41,  2.37s/it]

[ 57/100]  raw='pass. the essay presents clear arguments with logical reasoning'  → → 1

 58%|█████▊    | 58/100 [01:52<01:41,  2.42s/it]

[ 58/100]  raw='pass. the essay presents a clear and well-'  → → 1

 59%|█████▉    | 59/100 [01:54<01:35,  2.34s/it]

[ 59/100]  raw='fail. the essay provides several reasons why the fac'  → → 0

 60%|██████    | 60/100 [01:56<01:24,  2.12s/it]

[ 60/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 61%|██████    | 61/100 [01:58<01:24,  2.18s/it]

[ 61/100]  raw='pass. the essay provides a clear and detailed analysis'  → → 1

 62%|██████▏   | 62/100 [02:00<01:21,  2.15s/it]

[ 62/100]  raw='pass. the essay presents clear arguments for limiting car'  → → 1

 63%|██████▎   | 63/100 [02:02<01:14,  2.02s/it]

[ 63/100]  raw='pass. the essay presents a clear and logical argument'  → → 1

 64%|██████▍   | 64/100 [02:04<01:09,  1.93s/it]

[ 64/100]  raw='fail. the essay lacks a clear and co'  → → 0

 65%|██████▌   | 65/100 [02:06<01:07,  1.92s/it]

[ 65/100]  raw='pass. the essay presents clear reasons for the benefits'  → → 1

 66%|██████▌   | 66/100 [02:08<01:02,  1.85s/it]

[ 66/100]  raw='fail. the essay contains several grammatical errors'  → → 0

 67%|██████▋   | 67/100 [02:10<01:05,  2.00s/it]

[ 67/100]  raw='pass. the essay presents clear and well-reason'  → → 1

 68%|██████▊   | 68/100 [02:12<01:00,  1.90s/it]

[ 68/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 69%|██████▉   | 69/100 [02:14<01:03,  2.05s/it]

[ 69/100]  raw='pass. the essay presents clear and well-reason'  → → 1

 70%|███████   | 70/100 [02:16<00:58,  1.95s/it]

[ 70/100]  raw='pass. the essay is written in an engaging and'  → → 1

 71%|███████   | 71/100 [02:18<00:57,  1.98s/it]

[ 71/100]  raw='pass. the essay presents a clear argument for the'  → → 1

 72%|███████▏  | 72/100 [02:19<00:52,  1.87s/it]

[ 72/100]  raw='pass. the essay presents a clear position on the'  → → 1

 73%|███████▎  | 73/100 [02:22<00:53,  1.98s/it]

[ 73/100]  raw='pass. the essay presents a clear and well-'  → → 1

 74%|███████▍  | 74/100 [02:23<00:50,  1.93s/it]

[ 74/100]  raw='pass. the essay is well-written, engaging'  → → 1

 75%|███████▌  | 75/100 [02:26<00:53,  2.14s/it]

[ 75/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 76%|███████▌  | 76/100 [02:28<00:51,  2.15s/it]

[ 76/100]  raw='pass. the essay presents clear ideas and arguments about'  → → 1

 77%|███████▋  | 77/100 [02:30<00:48,  2.11s/it]

[ 77/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 78%|███████▊  | 78/100 [02:32<00:42,  1.95s/it]

[ 78/100]  raw='fail. the essay raises valid concerns but the arguments'  → → 0

 79%|███████▉  | 79/100 [02:33<00:39,  1.86s/it]

[ 79/100]  raw='pass. the essay presents a clear position and provides'  → → 1

 80%|████████  | 80/100 [02:35<00:36,  1.85s/it]

[ 80/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

 81%|████████  | 81/100 [02:38<00:37,  1.99s/it]

[ 81/100]  raw='pass. the essay presents a clear and well-'  → → 1

 82%|████████▏ | 82/100 [02:39<00:33,  1.87s/it]

[ 82/100]  raw='pass. the essay expresses a clear opinion and'  → → 1

 83%|████████▎ | 83/100 [02:42<00:36,  2.15s/it]

[ 83/100]  raw='pass. the essay presents clear and well-reason'  → → 1

 84%|████████▍ | 84/100 [02:44<00:35,  2.24s/it]

[ 84/100]  raw='pass. the essay presents clear and well-reason'  → → 1

 85%|████████▌ | 85/100 [02:46<00:32,  2.14s/it]

[ 85/100]  raw='pass. the essay provides a clear and well-'  → → 1

 86%|████████▌ | 86/100 [02:48<00:28,  2.05s/it]

[ 86/100]  raw='pass. the essay demonstrates a clear understanding of'  → → 1

 87%|████████▋ | 87/100 [02:50<00:26,  2.06s/it]

[ 87/100]  raw='pass. the essay presents a clear argument and provides'  → → 1

 88%|████████▊ | 88/100 [02:52<00:24,  2.08s/it]

[ 88/100]  raw='pass. the essay presents clear reasons for limiting the'  → → 1

 89%|████████▉ | 89/100 [02:54<00:22,  2.07s/it]

[ 89/100]  raw='pass. the essay provides a clear and cohes'  → → 1

 90%|█████████ | 90/100 [02:56<00:19,  1.97s/it]

[ 90/100]  raw='pass. the essay provides multiple reasons for joining the'  → → 1

 91%|█████████ | 91/100 [02:58<00:17,  1.92s/it]

[ 91/100]  raw='fail. the essay lacks a clear and well'  → → 0

 92%|█████████▏| 92/100 [03:00<00:15,  1.97s/it]

[ 92/100]  raw='fail. the essay lacks a clear and focused'  → → 0

 93%|█████████▎| 93/100 [03:02<00:14,  2.08s/it]

[ 93/100]  raw='pass. the essay presents clear arguments and provides evidence'  → → 1

 94%|█████████▍| 94/100 [03:04<00:12,  2.06s/it]

[ 94/100]  raw='pass. the essay presents a clear and well-'  → → 1

 95%|█████████▌| 95/100 [03:06<00:10,  2.05s/it]

[ 95/100]  raw='pass. the essay presents clear ideas and effectively arg'  → → 1

 96%|█████████▌| 96/100 [03:08<00:07,  1.91s/it]

[ 96/100]  raw='pass. the essay presents a clear argument and provides'  → → 1

 97%|█████████▋| 97/100 [03:10<00:05,  1.83s/it]

[ 97/100]  raw='fail. the essay lacks clear organization, proper'  → → 0

 98%|█████████▊| 98/100 [03:11<00:03,  1.79s/it]

[ 98/100]  raw='pass. the essay presents a clear position on the'  → → 1

 99%|█████████▉| 99/100 [03:13<00:01,  1.88s/it]

[ 99/100]  raw='fail. the essay contains numerous grammatical errors'  → → 0

100%|██████████| 100/100 [03:15<00:00,  1.96s/it]

[100/100]  raw='fail. the essay contains several grammatical errors'  → → 0
    y_true  y_pred                                                        generated y_true_label y_pred_label
0        1       1                pass. the essay presents a clear argument for the         Pass         Pass
1        1       1                pass. the essay presents a clear argument for why         Pass         Pass
2        0       0                       fail. the essay lacks a clear argument and         Fail         Fail
3        0       1                     pass.\n\nthe essay presents a clear position         Fail         Pass
4        0       1            pass. the essay demonstrates a clear understanding of         Fail         Pass
5        1       0                    fail. the essay lacks clear argumentation and         Pass         Fail
6        0       0            fail. the essay expresses a negative attitude towards         Fail         Fail
7        1       1            pass. the essay presents a clear argument against the         Pass         Pass
8        0       1            pass. the essay demonstrates a clear understanding of         Fail         Pass
9        1       1              pass. the essay presents a clear argument with well         Pass         Pass
10       0       1                 pass. the essay presents a clear position on the         Fail         Pass
11       1       0                                                            fail.         Pass         Fail
12       0       0              fail. the essay contains several grammatical errors         Fail         Fail
13       0       1    pass. the essay presents clear ideas and effectively explains         Fail         Pass
14       0       1                   pass. the essay follows a clear structure, has         Fail         Pass
15       0       1               pass. the essay presents a clear position and uses         Fail         Pass
16       1       1            pass. the essay presents clear reasons for the author         Pass         Pass
17       0       1                       pass. the essay presents a clear and well-         Fail         Pass
18       0       1                  pass. the essay presents a clear opinion on the         Fail         Pass
19       1       1                       pass. the essay presents a clear and well-         Pass         Pass
20       0       0                        fail. the essay is disorganized, contains         Fail         Fail
21       0       0              fail. the essay contains several grammatical errors         Fail         Fail
22       0       1                     pass. the essay expresses a clear opinion on         Fail         Pass
23       0       1                    pass. the essay presents a clear and coherent         Fail         Pass
24       1       1              pass. the essay presents clear ideas and arguments,         Pass         Pass
25       1       1            pass. the essay effectively argues against cell phone         Pass         Pass
26       0       0                 fail. the essay lacks clear organization, proper         Fail         Fail
27       0       0                          fail. the essay lacks clear and concise         Fail         Fail
28       0       1                       pass. the essay presents a clear and well-         Fail         Pass
29       1       1            pass. the essay effectively argues for the importance         Pass         Pass
30       1       1                pass. the essay presents a clear argument for the         Pass         Pass
31       0       1           pass. the essay presents a clear position and provides         Fail         Pass
32       1       1                       pass. the essay provides a clear and well-         Pass         Pass
33       1       1                           pass. the essay is well-written, clear         Pass         Pass
34       0       0                  fail. the essay lacks clear organization and co         Fail         Fail
35       0       0               fail. the essay lacks clear organization, contains         Fail         Fail
36       0       0               fail. the essay lacks clear organization, contains         Fail         Fail
37       1       1                       pass. the essay presents a clear and well-         Pass         Pass
38       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
39       0       1         pass. the essay presents clear reasons for allowing cell         Fail         Pass
40       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
41       0       0                 fail. the essay lacks clear organization, proper         Fail         Fail
42       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
43       1       1                  pass. the essay presents clear and well-develop         Pass         Pass
44       0       1        pass. the essay presents clear arguments and uses logical         Fail         Pass
45       1       1     pass. the essay presents clear reasons against allowing cell         Pass         Pass
46       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
47       0       1             pass. the essay demonstrates an understanding of the         Fail         Pass
48       0       1            pass. the essay presents clear reasons and arguments,         Fail         Pass
49       0       1      pass. the essay provides clear examples and effectively arg         Fail         Pass
50       0       1     pass. the essay presents clear benefits of distance learning         Fail         Pass
51       0       1          pass. the essay presents clear reasons for limiting car         Fail         Pass
52       0       1           pass. the essay presents a clear position and provides         Fail         Pass
53       1       0             fail. the essay contains numerous grammatical errors         Pass         Fail
54       1       1        pass. the essay presents clear and logical arguments with         Pass         Pass
55       0       1                       pass. the essay presents a clear and well-         Fail         Pass
56       1       1  pass. the essay presents clear arguments with logical reasoning         Pass         Pass
57       1       1                       pass. the essay presents a clear and well-         Pass         Pass
58       1       0             fail. the essay provides several reasons why the fac         Pass         Fail
59       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
60       1       1           pass. the essay provides a clear and detailed analysis         Pass         Pass
61       1       1        pass. the essay presents clear arguments for limiting car         Pass         Pass
62       0       1            pass. the essay presents a clear and logical argument         Fail         Pass
63       0       0                             fail. the essay lacks a clear and co         Fail         Fail
64       1       1          pass. the essay presents clear reasons for the benefits         Pass         Pass
65       0       0              fail. the essay contains several grammatical errors         Fail         Fail
66       1       1                   pass. the essay presents clear and well-reason         Pass         Pass
67       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
68       1       1                   pass. the essay presents clear and well-reason         Pass         Pass
69       0       1                    pass. the essay is written in an engaging and         Fail         Pass
70       1       1                pass. the essay presents a clear argument for the         Pass         Pass
71       0       1                 pass. the essay presents a clear position on the         Fail         Pass
72       1       1                       pass. the essay presents a clear and well-         Pass         Pass
73       0       1                        pass. the essay is well-written, engaging         Fail         Pass
74       1       0             fail. the essay contains numerous grammatical errors         Pass         Fail
75       1       1         pass. the essay presents clear ideas and arguments about         Pass         Pass
76       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
77       0       0          fail. the essay raises valid concerns but the arguments         Fail         Fail
78       0       1           pass. the essay presents a clear position and provides         Fail         Pass
79       0       0             fail. the essay contains numerous grammatical errors         Fail         Fail
80       1       1                       pass. the essay presents a clear and well-         Pass         Pass
81       0       1                    pass. the essay expresses a clear opinion and         Fail         Pass
82       1       1                   pass. the essay presents clear and well-reason         Pass         Pass
83       1       1                   pass. the essay presents clear and well-reason         Pass         Pass
84       1       1                       pass. the essay provides a clear and well-         Pass         Pass
85       0       1            pass. the essay demonstrates a clear understanding of         Fail         Pass
86       1       1           pass. the essay presents a clear argument and provides         Pass         Pass
87       0       1          pass. the essay presents clear reasons for limiting the         Fail         Pass
88       0       1                       pass. the essay provides a clear and cohes         Fail         Pass
89       0       1        pass. the essay provides multiple reasons for joining the         Fail         Pass
90       1       0                           fail. the essay lacks a clear and well         Pass         Fail
91       1       0                        fail. the essay lacks a clear and focused         Pass         Fail
92       1       1   pass. the essay presents clear arguments and provides evidence         Pass         Pass
93       1       1                       pass. the essay presents a clear and well-         Pass         Pass
94       1       1         pass. the essay presents clear ideas and effectively arg         Pass         Pass
95       0       1           pass. the essay presents a clear argument and provides         Fail         Pass
96       0       0                 fail. the essay lacks clear organization, proper         Fail         Fail
97       0       1                 pass. the essay presents a clear position on the         Fail         Pass
98       1       0             fail. the essay contains numerous grammatical errors         Pass         Fail
99       0       0              fail. the essay contains several grammatical errors         Fail         Fail

Accuracy : 0.5800
              precision    recall  f1-score   support

        Fail       0.75      0.41      0.53        58
        Pass       0.50      0.81      0.62        42

    accuracy                           0.58       100
   macro avg       0.62      0.61      0.58       100
weighted avg       0.65      0.58      0.57       100

In [ ]:
# The whole essays test
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred                    generated y_true_label y_pred_label
0         0       1      pass. the essay express         Fail         Pass
1         0       1        pass. the essay meets         Fail         Pass
2         0       1     pass. the essay presents         Fail         Pass
3         1       1     pass. the essay provides         Pass         Pass
4         0       1     pass. the essay presents         Fail         Pass
5         0       1     pass. the essay provides         Fail         Pass
6         1       1     pass. the essay presents         Pass         Pass
7         1       1     pass. the essay provides         Pass         Pass
8         1       1     pass. the essay presents         Pass         Pass
9         0       1        pass. the essay meets         Fail         Pass
10        0       1     pass. the essay presents         Fail         Pass
11        1       1        pass. the essay meets         Pass         Pass
12        1       1     pass. the essay presents         Pass         Pass
13        1       1     pass. the essay presents         Pass         Pass
14        1       1     pass. the essay presents         Pass         Pass
15        1       1     pass. the essay presents         Pass         Pass
16        1       1     pass. the essay presents         Pass         Pass
17        1       1     pass. the essay provides         Pass         Pass
18        0       1     pass. the essay presents         Fail         Pass
19        0       1     pass. the essay provides         Fail         Pass
20        0       0     fail. the essay contains         Fail         Fail
21        0       1     pass. the essay presents         Fail         Pass
22        0       1     pass. the essay provides         Fail         Pass
23        1       1     pass. the essay presents         Pass         Pass
24        1       1     pass. the essay presents         Pass         Pass
25        1       1     pass. the essay presents         Pass         Pass
26        0       1      pass. the essay express         Fail         Pass
27        1       1     pass. the essay presents         Pass         Pass
28        1       1     pass. the essay presents         Pass         Pass
29        0       1     pass. the essay provides         Fail         Pass
30        1       1     pass. the essay presents         Pass         Pass
31        0       1     pass. the essay provides         Fail         Pass
32        1       1     pass. the essay presents         Pass         Pass
33        0       1     pass. the essay presents         Fail         Pass
34        0       0     fail. the essay contains         Fail         Fail
35        1       1        pass. the essay meets         Pass         Pass
36        1       1     pass. the essay presents         Pass         Pass
37        0       1     pass. the essay presents         Fail         Pass
38        1       1     pass. the essay presents         Pass         Pass
39        1       1     pass. the essay provides         Pass         Pass
40        1       1     pass. the essay presents         Pass         Pass
41        0       0     fail. the essay contains         Fail         Fail
42        0       1     pass. the essay demonstr         Fail         Pass
43        1       1     pass. the essay presents         Pass         Pass
44        0       0     fail. the essay contains         Fail         Fail
45        0       0         fail. the essay lack         Fail         Fail
46        0       1     pass. the essay presents         Fail         Pass
47        1       1     pass. the essay presents         Pass         Pass
48        0       1     pass. the essay presents         Fail         Pass
49        1       1        pass. the essay meets         Pass         Pass
50        0       1     pass. the essay presents         Fail         Pass
51        0       1     pass. the essay presents         Fail         Pass
52        1       1           pass. the essay is         Pass         Pass
53        1       1     pass. the essay presents         Pass         Pass
54        0       1     pass. the essay provides         Fail         Pass
55        0       0     fail. the essay contains         Fail         Fail
56        0       1     pass. the essay provides         Fail         Pass
57        0       1     pass. the essay presents         Fail         Pass
58        0       1     pass. the essay presents         Fail         Pass
59        0       1     pass. the essay provides         Fail         Pass
60        1       1     pass. the essay presents         Pass         Pass
61        0       1     pass. the essay presents         Fail         Pass
62        1       0     fail. the essay contains         Pass         Fail
63        0       0     fail. the essay contains         Fail         Fail
64        0       0     fail. the essay contains         Fail         Fail
65        1       1     pass. the essay presents         Pass         Pass
66        1       1     pass. the essay presents         Pass         Pass
67        0       1     pass. the essay presents         Fail         Pass
68        1       1     pass. the essay presents         Pass         Pass
69        0       1     pass. the essay provides         Fail         Pass
70        0       1     pass. the essay provides         Fail         Pass
71        0       0     fail. the essay contains         Fail         Fail
72        0       0         fail. the essay does         Fail         Fail
73        0       1     pass. the essay presents         Fail         Pass
74        0       0     fail. the essay contains         Fail         Fail
75        1       1      pass. the essay express         Pass         Pass
76        0       1        pass. the essay meets         Fail         Pass
77        1       0     fail. the essay contains         Pass         Fail
78        0       0     fail. the essay contains         Fail         Fail
79        1       1        pass. the essay meets         Pass         Pass
80        1       1     pass. the essay presents         Pass         Pass
81        1       1     pass. the essay presents         Pass         Pass
82        1       1     pass. the essay presents         Pass         Pass
83        1       1     pass. the essay presents         Pass         Pass
84        0       1     pass. the essay provides         Fail         Pass
85        0       1     pass. the essay provides         Fail         Pass
86        0       1     pass. the essay presents         Fail         Pass
87        0       1     pass. the essay provides         Fail         Pass
88        1       1     pass. the essay presents         Pass         Pass
89        0       1     pass. the essay provides         Fail         Pass
90        1       1     pass. the essay presents         Pass         Pass
91        1       1     pass. the essay provides         Pass         Pass
92        1       1     pass. the essay presents         Pass         Pass
93        0       1     pass. the essay provides         Fail         Pass
94        0       0     fail. the essay contains         Fail         Fail
95        0       0     fail. the essay contains         Fail         Fail
96        0       0         fail. the essay does         Fail         Fail
97        0       1      pass. the essay express         Fail         Pass
98        0       1     pass. the essay presents         Fail         Pass
99        0       0     fail. the essay contains         Fail         Fail
100       0       1     pass. the essay presents         Fail         Pass
101       0       1     pass. the essay presents         Fail         Pass
102       0       1      pass. the essay express         Fail         Pass
103       0       1     pass. the essay presents         Fail         Pass
104       0       1     pass. the essay presents         Fail         Pass
105       1       1     pass. the essay presents         Pass         Pass
106       1       1        pass. the essay meets         Pass         Pass
107       0       1      pass. the essay express         Fail         Pass
108       1       1      pass. the essay clearly         Pass         Pass
109       0       1     pass. the essay presents         Fail         Pass
110       0       1     pass. the essay provides         Fail         Pass
111       0       1     pass. the essay presents         Fail         Pass
112       1       1     pass. the essay presents         Pass         Pass
113       0       1     pass. the essay provides         Fail         Pass
114       0       1     pass. the essay provides         Fail         Pass
115       0       1     pass. the essay presents         Fail         Pass
116       1       1     pass. the essay presents         Pass         Pass
117       1       1     pass. the essay presents         Pass         Pass
118       0       1     pass. the essay presents         Fail         Pass
119       1       1     pass. the essay presents         Pass         Pass
120       1       1  pass. the essay effectively         Pass         Pass
121       1       1     pass. the essay provides         Pass         Pass
122       1       1        pass. the essay meets         Pass         Pass
123       1       1     pass. the essay presents         Pass         Pass
124       0       1      pass. the essay express         Fail         Pass
125       0       1     pass. the essay presents         Fail         Pass
126       0       1     pass. the essay provides         Fail         Pass
127       0       1     pass. the essay presents         Fail         Pass
128       0       1     pass. the essay demonstr         Fail         Pass
129       1       1     pass. the essay presents         Pass         Pass
130       0       1        pass. the essay meets         Fail         Pass
131       0       1     pass. the essay presents         Fail         Pass
132       0       0     fail. the essay contains         Fail         Fail
133       0       0     fail. the essay contains         Fail         Fail
134       0       1     pass. the essay provides         Fail         Pass
135       0       1     pass. the essay presents         Fail         Pass
136       1       1     pass. the essay presents         Pass         Pass
137       1       0         fail. the essay does         Pass         Fail
138       1       1     pass. the essay presents         Pass         Pass
139       0       1      pass. the essay express         Fail         Pass
140       0       1     pass. the essay presents         Fail         Pass
141       0       0     fail. the essay contains         Fail         Fail
142       1       0         fail. the essay lack         Pass         Fail
143       1       1     pass. the essay provides         Pass         Pass
144       0       1     pass. the essay provides         Fail         Pass
145       1       1     pass. the essay presents         Pass         Pass
146       1       1     pass. the essay presents         Pass         Pass
147       1       1     pass. the essay presents         Pass         Pass
148       1       1     pass. the essay presents         Pass         Pass
149       0       1     pass. the essay presents         Fail         Pass
150       1       1        pass. the essay meets         Pass         Pass
151       0       1     pass. the essay presents         Fail         Pass
152       1       0     fail. the essay contains         Pass         Fail
153       0       0     fail. the essay contains         Fail         Fail
154       0       1     pass. the essay presents         Fail         Pass
155       1       1     pass. the essay presents         Pass         Pass
156       0       0     fail. the essay contains         Fail         Fail
157       1       1     pass. the essay presents         Pass         Pass
158       1       1     pass. the essay provides         Pass         Pass
159       1       0     fail. the essay contains         Pass         Fail
160       0       1     pass. the essay presents         Fail         Pass
161       0       1     pass. the essay presents         Fail         Pass
162       0       1  pass. the essay effectively         Fail         Pass
163       1       1     pass. the essay presents         Pass         Pass
164       0       0     fail. the essay contains         Fail         Fail
165       0       0     fail. the essay contains         Fail         Fail
166       0       1      pass. the essay express         Fail         Pass
167       0       1     pass. the essay provides         Fail         Pass
168       1       0     fail. the essay contains         Pass         Fail
169       1       1     pass. the essay presents         Pass         Pass
170       1       1     pass. the essay presents         Pass         Pass
171       1       1        pass. the essay meets         Pass         Pass
172       1       1        pass. the essay meets         Pass         Pass
173       1       1     pass. the essay presents         Pass         Pass
174       0       1     pass. the essay presents         Fail         Pass
175       0       1     pass. the essay presents         Fail         Pass
176       0       1        pass. the essay meets         Fail         Pass
177       0       1     pass. the essay presents         Fail         Pass
178       1       1     pass. the essay provides         Pass         Pass
179       0       0     fail. the essay contains         Fail         Fail
180       0       1     pass. the essay presents         Fail         Pass
181       0       0     fail. the essay contains         Fail         Fail
182       0       1     pass. the essay presents         Fail         Pass
183       0       1     pass. the essay presents         Fail         Pass
184       1       1     pass. the essay presents         Pass         Pass
185       1       1        pass. the essay meets         Pass         Pass
186       0       1     pass. the essay presents         Fail         Pass
187       0       1     pass. the essay presents         Fail         Pass
188       1       1     pass. the essay presents         Pass         Pass
189       1       1     pass. the essay presents         Pass         Pass
190       0       1     pass. the essay presents         Fail         Pass
191       1       1     pass. the essay presents         Pass         Pass
192       0       1     pass. the essay provides         Fail         Pass
193       0       1     pass. the essay presents         Fail         Pass
194       1       1     pass. the essay presents         Pass         Pass
195       0       0     fail. the essay contains         Fail         Fail
196       1       1     pass. the essay presents         Pass         Pass
197       0       1     pass. the essay presents         Fail         Pass
198       1       1  pass. the essay effectively         Pass         Pass
199       0       1     pass. the essay presents         Fail         Pass
200       0       1     pass. the essay presents         Fail         Pass
201       1       1     pass. the essay presents         Pass         Pass
202       0       0     fail. the essay contains         Fail         Fail
203       1       1     pass. the essay presents         Pass         Pass
204       0       1      pass. the essay express         Fail         Pass
205       0       1     pass. the essay provides         Fail         Pass
206       1       1     pass. the essay provides         Pass         Pass
207       0       1     pass. the essay presents         Fail         Pass
208       0       0     fail. the essay contains         Fail         Fail
209       0       1      pass. the essay express         Fail         Pass
210       0       1     pass. the essay presents         Fail         Pass
211       0       1     pass. the essay presents         Fail         Pass
212       1       1     pass. the essay provides         Pass         Pass
213       0       0     fail. the essay contains         Fail         Fail
214       0       1     pass. the essay presents         Fail         Pass
215       0       1     pass. the essay provides         Fail         Pass
216       0       0     fail. the essay contains         Fail         Fail
217       1       1     pass. the essay presents         Pass         Pass
218       1       1     pass. the essay presents         Pass         Pass
219       0       1     pass. the essay presents         Fail         Pass
220       0       1     pass. the essay presents         Fail         Pass
221       0       0     fail. the essay contains         Fail         Fail
222       1       1     pass. the essay presents         Pass         Pass
223       1       1     pass. the essay demonstr         Pass         Pass
224       0       1     pass. the essay provides         Fail         Pass
225       1       1     pass. the essay provides         Pass         Pass
226       0       1     pass. the essay presents         Fail         Pass
227       0       0     fail. the essay contains         Fail         Fail
228       0       0     fail. the essay contains         Fail         Fail
229       0       1     pass. the essay demonstr         Fail         Pass
230       1       1     pass. the essay presents         Pass         Pass
231       1       1     pass. the essay presents         Pass         Pass
232       0       0     fail. the essay contains         Fail         Fail
233       0       1     pass. the essay presents         Fail         Pass
234       1       1     pass. the essay presents         Pass         Pass
235       0       1     pass. the essay provides         Fail         Pass
236       0       1      pass. the essay express         Fail         Pass
237       0       1        pass. the essay meets         Fail         Pass
238       1       1     pass. the essay presents         Pass         Pass
239       0       0     fail. the essay contains         Fail         Fail
240       0       1     pass. the essay provides         Fail         Pass
241       0       1     pass. the essay presents         Fail         Pass
242       0       1     pass. the essay provides         Fail         Pass
243       0       1     pass. the essay presents         Fail         Pass
244       0       1        pass. the essay meets         Fail         Pass
245       1       1     pass. the essay presents         Pass         Pass
246       1       1        pass. the essay meets         Pass         Pass
247       0       0     fail. the essay contains         Fail         Fail
248       1       1      pass. the essay express         Pass         Pass
249       0       1     pass. the essay presents         Fail         Pass
250       0       1     pass. the essay presents         Fail         Pass
251       1       0     fail. the essay contains         Pass         Fail
252       1       0         fail. the essay does         Pass         Fail
253       0       0     fail. the essay contains         Fail         Fail
254       1       1     pass. the essay presents         Pass         Pass
255       0       1     pass. the essay provides         Fail         Pass
256       1       1     pass. the essay presents         Pass         Pass
257       0       0     fail. the essay contains         Fail         Fail
258       0       1     pass. the essay presents         Fail         Pass
259       1       1     pass. the essay presents         Pass         Pass
260       0       1     pass. the essay provides         Fail         Pass
261       1       1     pass. the essay presents         Pass         Pass
262       1       1     pass. the essay provides         Pass         Pass
263       0       1     pass. the essay presents         Fail         Pass
264       1       1     pass. the essay demonstr         Pass         Pass

#### **LoRA Finetuning**

* Yes, we've arrived at the eye of the storm, welcome to fine-tuning!  Now the fun begins. Let's add more spice to the mix!

In [ ]:
!pip install -U peft trl bitsandbytes accelerate transformers

Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.14.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.11.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.8.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.23.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.13.0->peft) (1.5.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
import torch

Model
* HF model card here

In [ ]:
model_name = "microsoft/phi-2"

# Load in 4bit, cuz we poor and dont have A100 GPU today
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"   # right padding for training (left for inference, dont forget!!)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model.config.pad_token_id = tokenizer.eos_token_id

print("Base model loaded on:", next(model.parameters()).device)
print("Memory (MB)         :", round(model.get_memory_footprint() / 1e6, 1))

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Base model loaded on: cuda:0
Memory (MB)         : 1784.5

In [ ]:
print(model)
# what element i would lookhere the attention layers
# the max features here is 8192, this is important to know see below
# "max_position_embeddings": 8192

PhiForCausalLM(
  (model): PhiModel(
    (embed_tokens): Embedding(51200, 2560)
    (layers): ModuleList(
      (0-31): 32 x PhiDecoderLayer(
        (self_attn): PhiAttention(
          (q_proj): Linear4bit(in_features=2560, out_features=2560, bias=True)
          (k_proj): Linear4bit(in_features=2560, out_features=2560, bias=True)
          (v_proj): Linear4bit(in_features=2560, out_features=2560, bias=True)
          (dense): Linear4bit(in_features=2560, out_features=2560, bias=True)
        )
        (mlp): PhiMLP(
          (activation_fn): NewGELUActivation()
          (fc1): Linear4bit(in_features=2560, out_features=10240, bias=True)
          (fc2): Linear4bit(in_features=10240, out_features=2560, bias=True)
        )
        (input_layernorm): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
        (resid_dropout): Dropout(p=0.1, inplace=False)
      )
    )
    (rotary_emb): PhiRotaryEmbedding()
    (embed_dropout): Dropout(p=0.0, inplace=False)
    (final_layernorm): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=2560, out_features=51200, bias=True)
)

eos
*   eos_token_id": 50256

pad
*   pad_token_id": 50256

In [ ]:
print(model.config)
#here i will check dtype if quant worked it showed here
# some elements to look
# attention layers
#"dtype": "float32"
# PAD token as "pad_token_id": 1
# EOS token as
# "eos_token_id": [
#    1,
#    107
#  ]

PhiConfig {
  "architectures": [
    "PhiForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 50256,
  "dtype": "float16",
  "embd_pdrop": 0.0,
  "eos_token_id": 50256,
  "hidden_act": "gelu_new",
  "hidden_size": 2560,
  "initializer_range": 0.02,
  "intermediate_size": 10240,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "phi",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 50256,
  "partial_rotary_factor": 0.4,
  "qk_layernorm": false,
  "quantization_config": {
    "_load_in_4bit": true,
    "_load_in_8bit": false,
    "bnb_4bit_compute_dtype": "float16",
    "bnb_4bit_quant_storage": "uint8",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false,
    "quant_method": "bitsandbytes"
  },
  "resid_pdrop": 0.1,
  "rope_parameters": {
    "partial_rotary_factor": 0.4,
    "rope_theta": 10000.0,
    "rope_type": "default"
  },
  "tie_word_embeddings": false,
  "transformers_version": "5.14.1",
  "use_cache": true,
  "vocab_size": 51200
}

In [ ]:
print(model.get_memory_footprint() / 1e9, "GB")
#model size increases from float16 to 32

1.784494208 GB

In [ ]:
#model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Vocab size     :", len(tokenizer))
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

# Sanity-check: confirm Pass/Fail tokens exist in vocabulary
pass_id = tokenizer.encode("Pass", add_special_tokens=False)
fail_id = tokenizer.encode("Fail", add_special_tokens=False)
print(f"\nToken check:")
print(f"  'Pass' → token id(s): {pass_id}")
print(f"  'Fail' → token id(s): {fail_id}")

Model loaded on: cuda:0
Vocab size     : 256000
Memory (MB)    : 10457.4

Token check:
  'Pass' → token id(s): [5825]
  'Fail' → token id(s): [15293]

##Microsoft Phi-3

Phi 2 ~4B
* It is a base model not a instruct model, so what we have used previously (on our previous episodes) of tokenizer.apply_chat_template()
  * remember this to get us  the chat template that belongs to a model that is for instruct model...Phi is a base model
  * Phi does not have a chat template
  * IM not sure if Phi is useful for our tasks
So,
maybe lets not do
 * model_name = "microsoft/phi-2"
 * we can use phi  instruct version

In [ ]:
!pip install -U transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.12.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.11.0+cu128)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

Please note that we are not quantizing the model.

Model info
*

In [ ]:
#model_name = "microsoft/phi-2"

model_name = "microsoft/Phi-3.5-mini-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    #trust_remote_code=True,
)

[transformers] This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

eos
*   "eos_token_id": 32000

pad
*   pad_token_id": 32000

Max token 131072
* wow that's like 130K context. Our ~700-token prompts are microscopic against it, we dont need to worry about ever truncates

In [ ]:
print(model)

Phi3ForCausalLM(
  (model): Phi3Model(
    (embed_tokens): Embedding(32064, 3072, padding_idx=32000)
    (layers): ModuleList(
      (0-31): 32 x Phi3DecoderLayer(
        (self_attn): Phi3Attention(
          (o_proj): Linear(in_features=3072, out_features=3072, bias=False)
          (qkv_proj): Linear(in_features=3072, out_features=9216, bias=False)
        )
        (mlp): Phi3MLP(
          (gate_up_proj): Linear(in_features=3072, out_features=16384, bias=False)
          (down_proj): Linear(in_features=8192, out_features=3072, bias=False)
          (activation_fn): SiLUActivation()
        )
        (input_layernorm): Phi3RMSNorm((3072,), eps=1e-05)
        (post_attention_layernorm): Phi3RMSNorm((3072,), eps=1e-05)
        (resid_attn_dropout): Dropout(p=0.0, inplace=False)
        (resid_mlp_dropout): Dropout(p=0.0, inplace=False)
      )
    )
    (norm): Phi3RMSNorm((3072,), eps=1e-05)
    (rotary_emb): Phi3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=3072, out_features=32064, bias=False)
)

In [ ]:
print(model.config)
#here i will check dtype if quant worked it showed here
# some elements to look
# attention layers
#"dtype": "float32"
# PAD token as "pad_token_id":
# EOS token as "eos_token_id":

Phi3Config {
  "architectures": [
    "Phi3ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_phi3.Phi3Config",
    "AutoModelForCausalLM": "modeling_phi3.Phi3ForCausalLM"
  },
  "bos_token_id": 1,
  "dtype": "float16",
  "embd_pdrop": 0.0,
  "eos_token_id": 32000,
  "hidden_act": "silu",
  "hidden_size": 3072,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "model_type": "phi3",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "original_max_position_embeddings": 4096,
  "pad_token_id": 32000,
  "resid_pdrop": 0.0,
  "rms_norm_eps": 1e-05,
  "rope_parameters": {
    "long_factor": [
      1.0800000429153442,
      1.1100000143051147,
      1.1399999856948853,
      1.340000033378601,
      1.5899999141693115,
      1.600000023841858,
      1.6200000047683716,
      2.620000123977661,
      3.2300000190734863,
      3.2300000190734863,
      4.789999961853027,
      7.400000095367432,
      7.700000286102295,
      9.09000015258789,
      12.199999809265137,
      17.670000076293945,
      24.46000099182129,
      28.57000160217285,
      30.420001983642578,
      30.840002059936523,
      32.590003967285156,
      32.93000411987305,
      42.320003509521484,
      44.96000289916992,
      50.340003967285156,
      50.45000457763672,
      57.55000305175781,
      57.93000411987305,
      58.21000289916992,
      60.1400032043457,
      62.61000442504883,
      62.62000274658203,
      62.71000289916992,
      63.1400032043457,
      63.1400032043457,
      63.77000427246094,
      63.93000411987305,
      63.96000289916992,
      63.970001220703125,
      64.02999877929688,
      64.06999969482422,
      64.08000183105469,
      64.12000274658203,
      64.41000366210938,
      64.4800033569336,
      64.51000213623047,
      64.52999877929688,
      64.83999633789062
    ],
    "original_max_position_embeddings": 4096,
    "rope_theta": 10000.0,
    "rope_type": "longrope",
    "short_factor": [
      1.0,
      1.0199999809265137,
      1.0299999713897705,
      1.0299999713897705,
      1.0499999523162842,
      1.0499999523162842,
      1.0499999523162842,
      1.0499999523162842,
      1.0499999523162842,
      1.0699999332427979,
      1.0999999046325684,
      1.1099998950958252,
      1.1599998474121094,
      1.1599998474121094,
      1.1699998378753662,
      1.2899998426437378,
      1.339999794960022,
      1.679999828338623,
      1.7899998426437378,
      1.8199998140335083,
      1.8499997854232788,
      1.8799997568130493,
      1.9099997282028198,
      1.9399996995925903,
      1.9899996519088745,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0799996852874756,
      2.0899996757507324,
      2.189999580383301,
      2.2199995517730713,
      2.5899994373321533,
      2.729999542236328,
      2.749999523162842,
      2.8399994373321533
    ],
    "type": "longrope"
  },
  "rope_theta": 10000.0,
  "sliding_window": 262144,
  "tie_word_embeddings": false,
  "transformers_version": "5.14.1",
  "use_cache": true,
  "vocab_size": 32064
}

In [ ]:
print(model.get_memory_footprint() / 1e9, "GB")
#model size increases from float16 to 32

7.642159104 GB

In [ ]:
#model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Vocab size     :", len(tokenizer))
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

# Sanity-check: confirm Pass/Fail tokens exist in vocabulary
pass_id = tokenizer.encode("Pass", add_special_tokens=False)
fail_id = tokenizer.encode("Fail", add_special_tokens=False)
print(f"\nToken check:")
print(f"  'Pass' → token id(s): {pass_id}")
print(f"  'Fail' → token id(s): {fail_id}")

Model loaded on: cuda:0
Vocab size     : 32011
Memory (MB)    : 7642.2

Token check:
  'Pass' → token id(s): [6978]
  'Fail' → token id(s): [29098]

In [ ]:
def predict_phi3(test, model, tokenizer):
    y_pred      = []
    y_generated = []

    model.eval()  # disable training only behavior (we not training here)

    # loop through every prompt in the test set
    for i in tqdm(range(len(test))):  # tqdm gives the progress bar, really helpful

        messages = [{"role": "user", "content": test.iloc[i]["text"]}]
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        # convert the prompt string into token IDs (numeric)
        # we are giving all of this to our model in a language it can understand (tokenize)
        inputs = tokenizer(
            prompt,             #this is the prompt
            return_tensors="pt",  #tensor
            truncation=True,      # cut, not sure how this affect the evaluation
            max_length=10000,   # Llama handles longer context than T5's 512,
            padding=False      # one essay at a time, nothing to pad against, less problems
        ).to(model.device)     # move the tokenized prompt to wherever the model lives (cpu/gpu)

        # remember how long the INPUT was, in tokens
        # decoder-only models return input + answer glued together,
        # so we need this to cut the input back off afterwards

        input_len = inputs["input_ids"].shape[1]

        # no gradient tracking, we are not training
        with torch.no_grad():
            # Llama GPT are decoder only no not forget this so --->>>input and output share one stream,
            # so .generate() APPENDS the answer onto the prompt tokens
            outputs = model.generate(
                **inputs,
                max_new_tokens=10,         # only need a word or two ("Pass"/"Fail")
                do_sample=False,           # greedy = deterministic, reproducible in a workshop
                pad_token_id=tokenizer.eos_token_id,
                use_cache=False,
            )
        # Where the answerrrrr
        # The key step here: keep only the tokens AFTER the prompt.
        # outputs[0] = [ ...prompt tokens... , ...new answer tokens... ]
        # so lets slice from input_len onward to get ONLY what the model added.

        new_tokens = outputs[0][input_len:]

        # turn those new token IDs back into text
        # skip_special_tokens drops <|assistant|>, </s>, etc.
        generated = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()

        y_generated.append(generated)

        # map the text answer to a label, So
        # contains "pass" -> 1, contains "fail" -> 0, neither -> -1 (unparseable problems)
        if "pass" in generated: y_pred.append(1)
        elif "fail" in generated: y_pred.append(0)
        else: y_pred.append(-1)

        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  → → {y_pred[-1]}")

    return y_pred, y_generated

In [ ]:
# remember this model is at high capacity of float32
# 30m to run 100 using CPU
# 3m to run 100 using L4GPU
# run on val set first
val_sample   = X_val_prompts.iloc[:100].reset_index(drop=True)
y_val_sample = y_val.values[:100]

y_pred, y_generated = predict_phi3(val_sample, model, tokenizer)

results_df = pd.DataFrame({
    "y_true"    : y_val_sample,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask     = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid   = y_val_sample[valid_mask]
y_pred_valid   = [y_pred[i] for i in valid_mask]

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0,1], target_names=["Fail","Pass"], zero_division=0
    ))

NameError: name 'X_val_prompts' is not defined

In [ ]:
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

#### LoRA finetuning

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install -U peft trl bitsandbytes accelerate transformers
!pip install -U transformers accelerate

Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Collecting bitsandbytes
  Downloading bitsandbytes-0.50.0-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.14.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.11.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.8.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.23.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.13.0->peft) (1.5.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Downloading bitsandbytes-0.50.0-py3-none-manylinux_2_24_x86_64.whl (40.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 49.8 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
  Attempting uninstall: bitsandbytes
    Found existing installation: bitsandbytes 0.49.2
    Uninstalling bitsandbytes-0.49.2:
      Successfully uninstalled bitsandbytes-0.49.2
Successfully installed bitsandbytes-0.50.0

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.14.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.23.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.11.0+cu128)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate) (1.5.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 447, in run
^C

Careful with the target modules
* target_modules=["q_proj", "k_proj", "v_proj", "dense", "fc1", "fc2"] these are the one for phi 2
* different models will have different targets

In [ ]:
#find the model target
import torch.nn as nn
linear_names = {name.split(".")[-1] for name, module in model.named_modules()
                if isinstance(module, nn.Linear)}
print(linear_names)

{'base_layer', 'lm_head', 'default'}

LoRA parameters
* r=   common values are 8, 16, 32,64
  * maybe 8
  * LoRa freezes a small matric and learns a small correct to it, writing as the product of two small matrices

* lora_alpha = 32
  * this is a scaling factor the correction gets multiplided by alpha/r before it is addded to the frozen weights
  * in our example 32/16 = 2
  * this is about how strong the contribution is relateive to the base model

* lora_dropout= 0.05
  * this is a regularization. During training, 5% of the adapters get shut down, this is to minimize overfitting and memorizing the data

* bias ="none"
  * dont train on bias terms. Linear weight sometime has biases

* task_type=TaskType.CAUSAL_LM
  * this is about telling PEFT what model it is so the adapter knows if it is a decoder only model, tells the adapter the type of model

* target_modules= [...]
  * where the adapters go, needs to checks this by model
    * check the attention layers
      * models decides what to pay attention too this is related to
        like q k v project, o_project
        * gate_up_proj adn down_proj
        * these are many times architecture specific

(There are other parameters see: [link text](https://4d9506f4.isolation.zscaler.com/profile/99dc41b0-1dad-4477-abaf-98852b346d52/zia-session/?controls_id=5ce955a4-1151-4a37-87ed-461c122b389e&region=was&tenant=9b5cea868a14&user=f5f5d245a2f0743f905306cd843b572624a923ce78e9fcb89f3e8f33ee0116f0&original_url=https%3A%2F%2Fhuggingface.co%2Fdocs%2Fpeft%2Fen%2Fpackage_reference%2Flora&key=sh-1&hmac=fc1517c6fb75016d771473ef1189709d2ca3b547e7e1ab4e403ebbca03f98aa2)

In [ ]:
# Part 1 model and QLoRA parameters
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training, PeftModel
from trl import SFTTrainer, SFTConfig
from datasets import Dataset
import torch
import gc

MODEL_NAME   = "microsoft/Phi-3.5-mini-instruct"
ADAPTER_PATH = "./phi3-lora-balanced-adapter"

# 4-bit quantization: float16 required for T4 (no bfloat16 support)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

lora_config = LoraConfig(
    r=16,                       # higher more correction, more trainable mor memory and more overfitting risk
                                # lower more constrained
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["qkv_proj", "o_proj", "gate_up_proj", "down_proj"],
)

In [ ]:
X = sample.drop(columns=["holistic_essay_score", "binary_score"])
y = sample["binary_score"].copy()          # binary 0/1 instead of 1 to 6, th 1 to 6 was not working at all

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print(f"Train : {len(X_train):,}  ({len(X_train)/len(sample)*100:.1f}%)")
print(f"Val   : {len(X_val):,}   ({len(X_val)/len(sample)*100:.1f}%)")
print(f"Test  : {len(X_test):,}   ({len(X_test)/len(sample)*100:.1f}%)")
print("\nClass distribution (stratification check):")
for name, y_split in [("Train", y_train), ("Val", y_val), ("Test", y_test)]:
    counts = y_split.value_counts().rename({0: "Fail", 1: "Pass"})
    print(f"  {name}: {counts.to_dict()}")

In [ ]:
#Part 2
#better version to keep things consistent
def generate_test_prompt(row):
    return (
        f"You are an expert essay grader. Read the essay and respond with exactly one word.\n"
        f"Your response must be either the word Fail or Pass. No other words.\n\n"
        f"Rules:\n"
        f"- Fail: the essay is weak, underdeveloped, or below standard\n"
        f"- Pass: the essay is proficient, strong, or excellent\n\n"
        f"Prompt: {row['prompt_name']}\n"
        f"Task: {row['task']}\n"
        f"Essay: {row['full_text']}\n\n"
        f"Respond with one word only (Fail or Pass): "
    )


def make_prompt_completion(row, tokenizer):
    user_content = generate_test_prompt(row)   # same wording
    prompt = tokenizer.apply_chat_template(
        [{"role": "user", "content": user_content}],
        tokenize=False, add_generation_prompt=True,
    )
    completion = "Pass" if row["binary_score"] == 1 else "Fail"
    return {"prompt": prompt, "completion": completion}

#Train
train_df = X_train.copy()
train_df["binary_score"] = y_train.values

# eval prompt
val_df = X_val.copy()
val_df["binary_score"] = y_val.values
X_val_prompts = pd.DataFrame(val_df.apply(generate_test_prompt, axis=1), columns=["text"])

test_df = X_test.copy()
test_df["binary_score"] = y_test.values
y_true = test_df["binary_score"].values
X_test_prompts = pd.DataFrame(test_df.apply(generate_test_prompt, axis=1), columns=["text"])

In [ ]:
#print(train_df["text"].iloc[0])

In [ ]:
# Part 3
fail_df = train_df[train_df["binary_score"] == 0]
pass_df = train_df[train_df["binary_score"] == 1]
min_class = len(pass_df)

train_balanced = pd.concat([
    fail_df.sample(n=min_class, random_state=42),
    pass_df,
]).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Balanced distribution: {train_balanced['binary_score'].value_counts().to_dict()}")

Balanced distribution: {1: 1505, 0: 1505}

In [ ]:
# Part 4: Build HuggingFace datasets
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"    # right for training (flip back to "left" for inference)

train_hf = Dataset.from_list(
    [make_prompt_completion(r, tokenizer) for _, r in train_balanced.iterrows()]
)
val_hf = Dataset.from_list(
    [make_prompt_completion(r, tokenizer) for _, r in val_df.iterrows()]
)

print(f"Train : {len(train_hf)}")
print(f"Val   : {len(val_hf)}")
print("Columns:", train_hf.column_names)                      # should be ['prompt', 'completion']
print("Sample prompt ending:", repr(train_hf[0]["prompt"][-70:]))   # should end at <|assistant|>\n
print("Sample completion  :", repr(train_hf[0]["completion"]))      # should be 'Pass' or 'Fail'

Train : 3010
Val   : 765
Columns: ['prompt', 'completion']
Sample prompt ending: 'AME\n\nRespond with one word only (Fail or Pass): <|end|>\n<|assistant|>\n'
Sample completion  : 'Pass'

In [ ]:
train_hf = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in train_balanced.iterrows()])
val_hf   = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in val_df.iterrows()])
print(train_hf[0])   # {'prompt': '<|user|>...<|assistant|>\n', 'completion': 'Pass'}

{'prompt': "<|user|>\nYou are an expert essay grader. Read the essay and respond with exactly one word.\nYour response must be either the word Fail or Pass. No other words.\n\nRules:\n- Fail: the essay is weak, underdeveloped, or below standard\n- Pass: the essay is proficient, strong, or excellent\n\nPrompt: Cell phones at school\nTask: Independent\nEssay: Dear Principal,\n\nThe majority of students in middle and high schools are glued to their cell phones everywhere they go. Even though they are used to text friends frequently, they are also important to scheduling. I think the policy best suited for our school would be the first policy. Cell phones are often necessary to determine whether or not a student can get home after school, to schedule after school activities, and to make plans with other students. To take away all of their right to use a cell phone during school hours would limit them to not being able to do this while eating lunch or having a free period.\n\nIf a student is unsure if their parents can pick them up from school or not when they aren't taking the bus, it is necessary to contact either their mom or dad to see if they can get home quickly after school ends. Sometimes, when a student isn't able to call a parent, they end up waiting for an hour or more outside the school until he/she is picked up from school. Students need to be able to use cell phones for situations like these, especially when they much homework to complete for school because then they have less time to do their required work.\n\nAnother reason why students should be allowed to use their cell phones during lunch and free times is because many are involved with some sort of after school activity. Whether it's a sport, musical instrument, or anything else, events within that activity are often scheduled last minute or without the student knowing days ahead of time. When this happens, they may not have transportation to the location if it is not held at the same school. In this scenario, students should be able to contact a parent or friend who can drive them to wherever they need to be.\n\nThe last reason why I think you should choose Policy 1 is because students need to take a break from working constantly and make plans with friends. Students have so much homework to do when they come home from school, and sometimes it can become overwhelming. Students need to be able to spend time with friends after school and not be always thinking of all the work that needs to get done by the next day. Taking a short break is helpful and make them feel less stressed about their schoolwork. So, students should also be able to use their cell phones to call or text friends to schedule activities together. They can even study for an upcoming test or quiz together, so they can get a higher grade.\n\nOverall, Policy 1 is a better policy because it still allows students to sometimes contact others with their cell phones. Today, cell phones are used by the majority of Americans multiple times. To take away their cell phones wouldn't be right. In some situations, students need them to call or text others to help them for whatever. Policy 1 works best because they have the chance to contact parents or friends when they need to, but they won't get distracted during class when they are turned off. This policy allows them to take care of anything they may need to, yet still be able to focus in class.\n\nSincerely,\n\nSTUDENT_NAME\n\nRespond with one word only (Fail or Pass): <|end|>\n<|assistant|>\n", 'completion': 'Pass'}

Huge Error
* fp16=True
* bf16=False
  * LoRA adapters loaded in bfloat16 (lora_A.default.weight such as torch.bfloat16, and "any bf16 trainable: True"), but fp16=True uses an fp16 gradient scaler that can't handle bf16 gradients. On a T4 (no bf16 support)
  * Cast the adapters to fp32

In [ ]:
# Part 5
gc.collect()
torch.cuda.empty_cache()

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.float16,
)
model.config.pad_token_id = tokenizer.eos_token_id
model.config.use_cache = False                      #  checkpointing
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)
model = get_peft_model(model, lora_config)

#casting
for name, param in model.named_parameters():
    if param.requires_grad:
        param.data = param.data.float()   # so bf16 adapters to fp32 (standard QLoRA

# verify
print("any bf16 trainable:", any(p.dtype == torch.bfloat16 for p in model.parameters() if p.requires_grad))
model.print_trainable_parameters()                  # show small nonzero trainable

[transformers] Phi3ForCausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

[transformers] Phi3ForCausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.

any bf16 trainable: False
trainable params: 25,165,824 || all params: 3,846,245,376 || trainable%: 0.6543

In [ ]:
#lens = [len(tokenizer.encode(t)) for t in train_hf["text"]]
#print("max:", max(lens), " | over 1024:", sum(l > 1024 for l in lens))
lens = [len(tokenizer.encode(ex["prompt"] + ex["completion"])) for ex in train_hf]
print("max:", max(lens), " | over 1024:", sum(l > 1024 for l in lens))

max: 4930  | over 1024: 247

In [ ]:
!pip install trl

Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.14.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)

In [ ]:
for n, p in model.named_parameters():
    if p.requires_grad:   # the trainable LoRA/adapter params
        print(n, p.dtype)
        break
print("any bf16 trainable:", any(p.dtype==torch.bfloat16 for p in model.parameters() if p.requires_grad))

base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight torch.float32
any bf16 trainable: False

In [ ]:
import torch

In [ ]:
# Part 6 SFT config and  train

sft_config = SFTConfig(
    output_dir="./phi3-lora-balanced",
    num_train_epochs=1,                  # 1 epoch enough for binary labels, keeps runtime sane w/o fp16
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,       # effective batch = 8
    warmup_steps=50,
    learning_rate=2e-4,
    fp16=False,                          # Ooff no GradScaler = no bf16 unscale crash error fix
    bf16=False,                          # T4 has no bf16 anyway
    logging_steps=25,
    eval_strategy="steps",
    eval_steps=200,                      # eval passes are slow in full precision; less often
    save_strategy="steps",
    save_steps=200,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    report_to="none",
    max_length=1024,                     # prompts ~700 tokens + label; nothing truncates
    completion_only_loss=True,           # loss only on the Pass/Fail completion
    optim="paged_adamw_8bit",
)

# cast LoRA adapters to fp32 right before training, stops the error
for name, param in model.named_parameters():
    if param.requires_grad:
        param.data = param.data.float()

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_hf,
    eval_dataset=val_hf.select(range(150)),   # small eval slice: loss signal only, keeps eval passes quick
    processing_class=tokenizer,
)

print("Starting fine-tuning...")
trainer.train()

Adding EOS to train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Starting fine-tuning...

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
WARNING:transformers_modules.microsoft.Phi_hyphen_3_dot_5_hyphen_mini_hyphen_instruct.2fe192450127e6a83f7441aef6e3ca586c338b77.modeling_phi3:You are not running the flash-attention implementation, expect numerical differences.

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

TrainOutput(global_step=346, training_loss=0.6687495770481969, metrics={'train_runtime': 6397.3872, 'train_samples_per_second': 0.432, 'train_steps_per_second': 0.054, 'total_flos': 3.767059145436365e+16, 'train_loss': 0.6687495770481969, 'epoch': 1.0})

In [ ]:
from transformers import GenerationConfig

In [ ]:
# Part 7: I think i lost count

# full test set with the finetuned model

# inference setup (the three things we always set)
tokenizer.padding_side = "left"          # was "right" for training
model_ft = trainer.model                 # best checkpoint (load_best_model_at_end)
model_ft.config.use_cache = False        # Phi cache bug

model_ft.generation_config = GenerationConfig.from_pretrained(MODEL_NAME, trust_remote_code=True)
# run YOUR predict function on the FULL test prompts
y_pred, y_generated = predict_phi3(X_test_prompts.reset_index(drop=True), model_ft, tokenizer)

  0%|          | 0/765 [00:00<?, ?it/s]

AttributeError: 'Phi3ForCausalLM' object has no attribute 'generate'

In [ ]:
#Part 7 Evaluate the finetuned model (run AFTER training completes)
# this is val

#flip padding back for inference (was "right" for training)
tokenizer.padding_side = "left"

# ft for finetuned
model_ft = trainer.model
model_ft.eval()
model_ft.config.use_cache = False   # Phi remote-code cache bug: keep cache off for generate

# Same predict function, same eval prompts
y_pred_ft, y_gen_ft = predict_phi3(X_val_prompts.iloc[:100].reset_index(drop=True), model_ft, tokenizer)

y_val_sample = y_val.values[:100]
valid = [i for i, p in enumerate(y_pred_ft) if p != -1]
yt = y_val_sample[valid]; yp = [y_pred_ft[i] for i in valid]

print(f"Parsed: {len(valid)}/100")
print(f"Accuracy : {accuracy_score(yt, yp):.4f}   (baseline was 0.5800)")
print(classification_report(yt, yp, labels=[0,1], target_names=["Fail","Pass"], zero_division=0))
print("Predicted-Pass fraction:", (pd.Series(yp)==1).mean(), " (baseline was ~0.68, true rate 0.42)")

  0%|          | 0/100 [00:00<?, ?it/s]

AttributeError: 'Phi3ForCausalLM' object has no attribute 'generation_config'

In [ ]:
# Final Evaluation

In [ ]:
# Part 7: val-100 eval of the finetuned model
tokenizer.padding_side = "left"           # flip back from training's "right"
model_ft = trainer.model
model_ft.eval()
model_ft.config.use_cache = False         # Phi cache bug

y_pred_ft, y_gen_ft = predict_phi3(
    X_val_prompts.iloc[:100].reset_index(drop=True), model_ft, tokenizer
)

y_val_sample = y_val.values[:100]
valid = [i for i, p in enumerate(y_pred_ft) if p != -1]
yt = y_val_sample[valid]; yp = [y_pred_ft[i] for i in valid]

print(f"Parsed: {len(valid)}/100")
print(f"Accuracy : {accuracy_score(yt, yp):.4f}   (zero-shot baseline: 0.5800)")
print(classification_report(yt, yp, labels=[0,1], target_names=["Fail","Pass"], zero_division=0))
print("Predicted-Pass fraction:", (pd.Series(yp)==1).mean(), " (baseline ~0.68, true rate 0.42)")

NameError: name 'predict_phi3' is not defined

In [ ]:
# Save locally
ADAPTER_PATH = "./phi3-lora-balanced-adapter"


trainer.model.save_pretrained(ADAPTER_PATH)
tokenizer.save_pretrained(ADAPTER_PATH)
print(f"   Saved locally: {ADAPTER_PATH}")
print(f"   Files: {os.listdir(ADAPTER_PATH)}")

   Saved locally: ./phi3-lora-balanced-adapter
   Files: ['adapter_model.safetensors', 'tokenizer_config.json', 'chat_template.jinja', 'adapter_config.json', 'README.md', 'tokenizer.json']

In [ ]:
import shutil, os
from google.colab import drive

drive.mount("/content/drive", force_remount=True)

LOCAL_ADAPTER_PATH = "./phi3-lora-balanced-adapter"
DRIVE_ADAPTER_PATH = "/content/drive/MyDrive/phi3-lora-balanced-adapter"


assert os.path.exists(LOCAL_ADAPTER_PATH), "No local adapter found did the save cell run?"

# replace any old version on Drive
if os.path.exists(DRIVE_ADAPTER_PATH):
    shutil.rmtree(DRIVE_ADAPTER_PATH)
    print("Removed old version from Drive")

shutil.copytree(LOCAL_ADAPTER_PATH, DRIVE_ADAPTER_PATH)
print(f"Backed up to Drive: {DRIVE_ADAPTER_PATH}")
print(f"   Files: {os.listdir(DRIVE_ADAPTER_PATH)}")

In [ ]:
# Cell 8 Load fine-tuned model for inference
gc.collect()
torch.cuda.empty_cache()

tokenizer.padding_side = "left"     # switch to left padding for inference

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
ft_model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
ft_model.eval()

X_test_prompts_phi2 = pd.DataFrame(
    test_df.apply(generate_phi2_test_prompt, axis=1), columns=["text"]
)
print(f"Test prompts : {len(X_test_prompts_phi2)}")
print("Last 50 chars:", repr(X_test_prompts_phi2["text"].iloc[0][-50:]))
# should end with '\nOutput:'

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Test prompts : 765
Last 50 chars: 't it would be very nice of you if you did.\nOutput:'

In [ ]:
# Step 1 imports
# from  new session
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel
import torch, shutil, os
from google.colab import drive

# Step 2 copy from Drive to local disk
drive.mount("/content/drive")

DRIVE_ADAPTER_PATH = "/content/drive/MyDrive/phi2-lora-balanced-adapter"  # exact folder name from your Drive
LOCAL_ADAPTER_PATH = "./phi2-lora-balanced-adapter"

if not os.path.exists(LOCAL_ADAPTER_PATH):
    shutil.copytree(DRIVE_ADAPTER_PATH, LOCAL_ADAPTER_PATH)
    print(f"Copied from Drive to local")
else:
    print(f" Already exists locally")

print(f"Files: {os.listdir(LOCAL_ADAPTER_PATH)}")

In [ ]:
# Step 3 load base model + adapter
MODEL_NAME = "microsoft/phi-2"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"     # left padding for inference

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.float16,
)
ft_model = PeftModel.from_pretrained(base_model, LOCAL_ADAPTER_PATH)
ft_model.eval()

print("✅ Model loaded")
print("   Device :", next(ft_model.parameters()).device)
print("   Memory :", round(ft_model.get_memory_footprint() / 1e6, 1), "MB")

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

✅ Model loaded
   Device : cuda:0
   Memory : 1878.9 MB

In [ ]:
# Cell 9: Predict
def predict_phi2(test, model, tokenizer, max_input_tokens=512):
    y_pred, y_generated = [], []
    model.eval()

    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]
        inputs = tokenizer(
            prompt, return_tensors="pt",
            truncation=True, max_length=max_input_tokens, padding=False,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=3,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
        generated  = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        result = {1: "Pass", 0: "Fail", -1: "???"}[y_pred[-1]]
        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {result}")

    return y_pred, y_generated

y_pred, y_generated = predict_phi2(X_test_prompts_phi2, ft_model, tokenizer)

NameError: name 'X_test_prompts_phi2' is not defined

In [ ]:
# Cell 10: Evaluate
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         0       0      fail         Fail         Fail
1         0       1      pass         Fail         Pass
2         0       0      fail         Fail         Fail
3         1       1      pass         Pass         Pass
4         0       0      fail         Fail         Fail
5         0       0      fail         Fail         Fail
6         1       1      pass         Pass         Pass
7         1       0      fail         Pass         Fail
8         1       1      pass         Pass         Pass
9         0       0      fail         Fail         Fail
10        0       0      fail         Fail         Fail
11        1       1      pass         Pass         Pass
12        1       0      fail         Pass         Fail
13        1       1      pass         Pass         Pass
14        1       1      pass         Pass         Pass
15        1       1      pass         Pass         Pass
16        1       0      fail         Pass         Fail
17        1       1      pass         Pass         Pass
18        0       0      fail         Fail         Fail
19        0       1      pass         Fail         Pass
20        0       0      fail         Fail         Fail
21        0       0      fail         Fail         Fail
22        0       0      fail         Fail         Fail
23        1       1      pass         Pass         Pass
24        1       1      pass         Pass         Pass
25        1       0      fail         Pass         Fail
26        0       0      fail         Fail         Fail
27        1       0      fail         Pass         Fail
28        1       1      pass         Pass         Pass
29        0       0      fail         Fail         Fail
30        1       1      pass         Pass         Pass
31        0       0      fail         Fail         Fail
32        1       1      pass         Pass         Pass
33        0       0      fail         Fail         Fail
34        0       0      fail         Fail         Fail
35        1       0      fail         Pass         Fail
36        1       1      pass         Pass         Pass
37        0       0      fail         Fail         Fail
38        1       1      pass         Pass         Pass
39        1       1      pass         Pass         Pass
40        1       1      pass         Pass         Pass
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        1       1      pass         Pass         Pass
44        0       0      fail         Fail         Fail
45        0       0      fail         Fail         Fail
46        0       1      pass         Fail         Pass
47        1       1      pass         Pass         Pass
48        0       0      fail         Fail         Fail
49        1       1      pass         Pass         Pass
50        0       1      pass         Fail         Pass
51        0       0      fail         Fail         Fail
52        1       1      pass         Pass         Pass
53        1       1      pass         Pass         Pass
54        0       0      fail         Fail         Fail
55        0       0      fail         Fail         Fail
56        0       0      fail         Fail         Fail
57        0       1      pass         Fail         Pass
58        0       1      pass         Fail         Pass
59        0       0      fail         Fail         Fail
60        1       1      pass         Pass         Pass
61        0       1      pass         Fail         Pass
62        1       1      pass         Pass         Pass
63        0       0      fail         Fail         Fail
64        0       0      fail         Fail         Fail
65        1       1      pass         Pass         Pass
66        1       1      pass         Pass         Pass
67        0       0      fail         Fail         Fail
68        1       0      fail         Pass         Fail
69        0       0      fail         Fail         Fail
70        0       0      fail         Fail         Fail
71        0       0      fail         Fail         Fail
72        0       0      fail         Fail         Fail
73        0       0      fail         Fail         Fail
74        0       0      fail         Fail         Fail
75        1       1      pass         Pass         Pass
76        0       0      fail         Fail         Fail
77        1       1      pass         Pass         Pass
78        0       0      fail         Fail         Fail
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        1       0      fail         Pass         Fail
82        1       1      pass         Pass         Pass
83        1       1      pass         Pass         Pass
84        0       0      fail         Fail         Fail
85        0       0      fail         Fail         Fail
86        0       0      fail         Fail         Fail
87        0       0      fail         Fail         Fail
88        1       1      pass         Pass         Pass
89        0       0      fail         Fail         Fail
90        1       1      pass         Pass         Pass
91        1       1      pass         Pass         Pass
92        1       1      pass         Pass         Pass
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       0      fail         Fail         Fail
96        0       0      fail         Fail         Fail
97        0       0      fail         Fail         Fail
98        0       1      pass         Fail         Pass
99        0       0      fail         Fail         Fail
100       0       0      fail         Fail         Fail
101       0       0      fail         Fail         Fail
102       0       0      fail         Fail         Fail
103       0       0      fail         Fail         Fail
104       0       0      fail         Fail         Fail
105       1       1      pass         Pass         Pass
106       1       1      pass         Pass         Pass
107       0       0      fail         Fail         Fail
108       1       1      pass         Pass         Pass
109       0       0      fail         Fail         Fail
110       0       0      fail         Fail         Fail
111       0       0      fail         Fail         Fail
112       1       1      pass         Pass         Pass
113       0       1      pass         Fail         Pass
114       0       0      fail         Fail         Fail
115       0       0      fail         Fail         Fail
116       1       1      pass         Pass         Pass
117       1       1      pass         Pass         Pass
118       0       0      fail         Fail         Fail
119       1       1      pass         Pass         Pass
120       1       1      pass         Pass         Pass
121       1       0      fail         Pass         Fail
122       1       1      pass         Pass         Pass
123       1       1      pass         Pass         Pass
124       0       0      fail         Fail         Fail
125       0       0      fail         Fail         Fail
126       0       0      fail         Fail         Fail
127       0       0      fail         Fail         Fail
128       0       0      fail         Fail         Fail
129       1       1      pass         Pass         Pass
130       0       0      fail         Fail         Fail
131       0       0      fail         Fail         Fail
132       0       0      fail         Fail         Fail
133       0       0      fail         Fail         Fail
134       0       0      fail         Fail         Fail
135       0       1      pass         Fail         Pass
136       1       1      pass         Pass         Pass
137       1       1      pass         Pass         Pass
138       1       1      pass         Pass         Pass
139       0       0      fail         Fail         Fail
140       0       0      fail         Fail         Fail
141       0       0      fail         Fail         Fail
142       1       0      fail         Pass         Fail
143       1       1      pass         Pass         Pass
144       0       1      pass         Fail         Pass
145       1       0      fail         Pass         Fail
146       1       1      pass         Pass         Pass
147       1       1      pass         Pass         Pass
148       1       1      pass         Pass         Pass
149       0       0      fail         Fail         Fail
150       1       1      pass         Pass         Pass
151       0       1      pass         Fail         Pass
152       1       0      fail         Pass         Fail
153       0       0      fail         Fail         Fail
154       0       1      pass         Fail         Pass
155       1       1      pass         Pass         Pass
156       0       1      pass         Fail         Pass
157       1       1      pass         Pass         Pass
158       1       1      pass         Pass         Pass
159       1       0      fail         Pass         Fail
160       0       0      fail         Fail         Fail
161       0       0      fail         Fail         Fail
162       0       0      fail         Fail         Fail
163       1       1      pass         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0      fail         Fail         Fail
166       0       0      fail         Fail         Fail
167       0       0      fail         Fail         Fail
168       1       1      pass         Pass         Pass
169       1       1      pass         Pass         Pass
170       1       1      pass         Pass         Pass
171       1       1      pass         Pass         Pass
172       1       1      pass         Pass         Pass
173       1       1      pass         Pass         Pass
174       0       0      fail         Fail         Fail
175       0       0      fail         Fail         Fail
176       0       0      fail         Fail         Fail
177       0       1      pass         Fail         Pass
178       1       1      pass         Pass         Pass
179       0       0      fail         Fail         Fail
180       0       0      fail         Fail         Fail
181       0       0      fail         Fail         Fail
182       0       0      fail         Fail         Fail
183       0       0      fail         Fail         Fail
184       1       1      pass         Pass         Pass
185       1       1      pass         Pass         Pass
186       0       1      pass         Fail         Pass
187       0       0      fail         Fail         Fail
188       1       1      pass         Pass         Pass
189       1       1      pass         Pass         Pass
190       0       1      pass         Fail         Pass
191       1       1      pass         Pass         Pass
192       0       0      fail         Fail         Fail
193       0       0      fail         Fail         Fail
194       1       1      pass         Pass         Pass
195       0       0      fail         Fail         Fail
196       1       1      pass         Pass         Pass
197       0       0      fail         Fail         Fail
198       1       1      pass         Pass         Pass
199       0       0      fail         Fail         Fail
200       0       0      fail         Fail         Fail
201       1       1      pass         Pass         Pass
202       0       0      fail         Fail         Fail
203       1       0      fail         Pass         Fail
204       0       0      fail         Fail         Fail
205       0       1      pass         Fail         Pass
206       1       1      pass         Pass         Pass
207       0       1      pass         Fail         Pass
208       0       0      fail         Fail         Fail
209       0       0      fail         Fail         Fail
210       0       0      fail         Fail         Fail
211       0       0      fail         Fail         Fail
212       1       1      pass         Pass         Pass
213       0       0      fail         Fail         Fail
214       0       1      pass         Fail         Pass
215       0       0      fail         Fail         Fail
216       0       0      fail         Fail         Fail
217       1       1      pass         Pass         Pass
218       1       1      pass         Pass         Pass
219       0       0      fail         Fail         Fail
220       0       0      fail         Fail         Fail
221       0       0      fail         Fail         Fail
222       1       1      pass         Pass         Pass
223       1       1      pass         Pass         Pass
224       0       0      fail         Fail         Fail
225       1       1      pass         Pass         Pass
226       0       0      fail         Fail         Fail
227       0       0      fail         Fail         Fail
228       0       0      fail         Fail         Fail
229       0       0      fail         Fail         Fail
230       1       1      pass         Pass         Pass
231       1       1      pass         Pass         Pass
232       0       0      fail         Fail         Fail
233       0       1      pass         Fail         Pass
234       1       1      pass         Pass         Pass
235       0       0      fail         Fail         Fail
236       0       0      fail         Fail         Fail
237       0       0      fail         Fail         Fail
238       1       1      pass         Pass         Pass
239       0       1      pass         Fail         Pass
240       0       1      pass         Fail         Pass
241       0       0      fail         Fail         Fail
242       0       0      fail         Fail         Fail
243       0       0      fail         Fail         Fail
244       0       0      fail         Fail         Fail
245       1       1      pass         Pass         Pass
246       1       1      pass         Pass         Pass
247       0       0      fail         Fail         Fail
248       1       1      pass         Pass         Pass
249       0       0      fail         Fail         Fail
250       0       0      fail         Fail         Fail
251       1       1      pass         Pass         Pass
252       1       0      fail         Pass         Fail
253       0       0      fail         Fail         Fail
254       1       1      pass         Pass         Pass
255       0       1      pass         Fail         Pass
256       1       0      fail         Pass         Fail
257       0       0      fail         Fail         Fail
258       0       0      fail         Fail         Fail
259       1       1      pass         Pass         Pass
260       0       0      fail         Fail         Fail
261       1       1      pass         Pass         Pass
262       1       1      pass         Pass         Pass
263       0       0      fail         Fail         Fail
264       1       1      pass         Pass         Pass
265       1       1      pass         Pass         Pass
266       1       1      pass         Pass         Pass
267       1       1      pass         Pass         Pass
268       1       1      pass         Pass         Pass
269       0       0      fail         Fail         Fail
270       0       0      fail         Fail         Fail
271       1       1      pass         Pass         Pass
272       0       0      fail         Fail         Fail
273       1       1      pass         Pass         Pass
274       1       1      pass         Pass         Pass
275       0       0      fail         Fail         Fail
276       0       0      fail         Fail         Fail
277       0       0      fail         Fail         Fail
278       1       1      pass         Pass         Pass
279       0       0      fail         Fail         Fail
280       1       1      pass         Pass         Pass
281       0       0      fail         Fail         Fail
282       1       1      pass         Pass         Pass
283       0       0      fail         Fail         Fail
284       0       0      fail         Fail         Fail
285       1       1      pass         Pass         Pass
286       0       0      fail         Fail         Fail
287       1       1      pass         Pass         Pass
288       0       0      fail         Fail         Fail
289       0       0      fail         Fail         Fail
290       0       0      fail         Fail         Fail
291       0       0      fail         Fail         Fail
292       1       1      pass         Pass         Pass
293       1       1      pass         Pass         Pass
294       0       0      fail         Fail         Fail
295       1       1      pass         Pass         Pass
296       1       1      pass         Pass         Pass
297       1       1      pass         Pass         Pass
298       1       1      pass         Pass         Pass
299       0       0      fail         Fail         Fail
300       0       0      fail         Fail         Fail
301       0       1      pass         Fail         Pass
302       1       1      pass         Pass         Pass
303       0       0      fail         Fail         Fail
304       0       0      fail         Fail         Fail
305       0       0      fail         Fail         Fail
306       0       0      fail         Fail         Fail
307       0       0      fail         Fail         Fail
308       1       1      pass         Pass         Pass
309       0       0      fail         Fail         Fail
310       0       0      fail         Fail         Fail
311       0       0      fail         Fail         Fail
312       1       0      fail         Pass         Fail
313       1       1      pass         Pass         Pass
314       0       0      fail         Fail         Fail
315       0       0      fail         Fail         Fail
316       0       1      pass         Fail         Pass
317       0       0      fail         Fail         Fail
318       1       0      fail         Pass         Fail
319       0       1      pass         Fail         Pass
320       0       0      fail         Fail         Fail
321       0       0      fail         Fail         Fail
322       0       1      pass         Fail         Pass
323       0       0      fail         Fail         Fail
324       1       0      fail         Pass         Fail
325       1       1      pass         Pass         Pass
326       0       0      fail         Fail         Fail
327       1       0      fail         Pass         Fail
328       0       0      fail         Fail         Fail
329       1       1      pass         Pass         Pass
330       0       0      fail         Fail         Fail
331       0       0      fail         Fail         Fail
332       0       0      fail         Fail         Fail
333       0       0      fail         Fail         Fail
334       0       0      fail         Fail         Fail
335       0       0      fail         Fail         Fail
336       1       1      pass         Pass         Pass
337       0       1      pass         Fail         Pass
338       1       1      pass         Pass         Pass
339       1       1      pass         Pass         Pass
340       1       1      pass         Pass         Pass
341       1       1      pass         Pass         Pass
342       1       1      pass         Pass         Pass
343       1       1      pass         Pass         Pass
344       1       1      pass         Pass         Pass
345       1       1      pass         Pass         Pass
346       0       0      fail         Fail         Fail
347       1       1      pass         Pass         Pass
348       0       0      fail         Fail         Fail
349       0       0      fail         Fail         Fail
350       0       0      fail         Fail         Fail
351       1       1      pass         Pass         Pass
352       0       0      fail         Fail         Fail
353       0       0      fail         Fail         Fail
354       1       1      pass         Pass         Pass
355       0       0      fail         Fail         Fail

### Not usre

In [ ]:
# clean reload: native transformers Phi3 (has generate), attach saved adapter
import gc
del model_ft
try: del model, trainer
except NameError: pass
gc.collect(); torch.cuda.empty_cache()

base = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    # NO trust_remote_code → library's built-in Phi3ForCausalLM, which HAS generate()
)

from peft import PeftModel
model_ft = PeftModel.from_pretrained(base, "./phi3-lora-balanced-adapter")
model_ft.eval()
model_ft.config.use_cache = False

tokenizer = AutoTokenizer.from_pretrained("./phi3-lora-balanced-adapter")
tokenizer.padding_side = "left"

# smoke test before any big run:
print(hasattr(model_ft, "generate"), hasattr(base, "generate"))

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

True True

In [ ]:
data1 = X_val_prompts.iloc[:1].reset_index(drop=True) #one essay to check
y_predict, y_generated = predict_phi3(data1, model_ft, tokenizer)
print("raw output:", repr(y_generated[0]), "→ parsed:", y_predict[0])

100%|██████████| 1/1 [00:01<00:00,  1.13s/it]

[  1/1]  raw='pass'  → → 1
raw output: 'pass' → parsed: 1

In [ ]:
# ── FINAL: full test set (765 essays), finetuned model ──

y_pred, y_generated = predict_phi3(
    X_test_prompts.reset_index(drop=True), model_ft, tokenizer
)

  0%|          | 1/765 [00:00<08:56,  1.42it/s]

[  1/765]  raw='fail'  → → 0

  0%|          | 2/765 [00:01<09:51,  1.29it/s]

[  2/765]  raw='fail'  → → 0

  0%|          | 3/765 [00:02<09:10,  1.38it/s]

[  3/765]  raw='fail'  → → 0

  1%|          | 4/765 [00:03<11:32,  1.10it/s]

[  4/765]  raw='pass'  → → 1

  1%|          | 5/765 [00:03<09:49,  1.29it/s]

[  5/765]  raw='fail'  → → 0

  1%|          | 6/765 [00:04<09:28,  1.34it/s]

[  6/765]  raw='fail'  → → 0

  1%|          | 7/765 [00:05<10:50,  1.17it/s]

[  7/765]  raw='pass'  → → 1

  1%|          | 8/765 [00:06<10:45,  1.17it/s]

[  8/765]  raw='fail'  → → 0

  1%|          | 9/765 [00:07<12:07,  1.04it/s]

[  9/765]  raw='pass'  → → 1

  1%|▏         | 10/765 [00:08<10:23,  1.21it/s]

[ 10/765]  raw='fail'  → → 0

  1%|▏         | 11/765 [00:09<10:21,  1.21it/s]

[ 11/765]  raw='fail'  → → 0

  2%|▏         | 12/765 [00:10<11:41,  1.07it/s]

[ 12/765]  raw='pass'  → → 1

  2%|▏         | 13/765 [00:11<11:18,  1.11it/s]

[ 13/765]  raw='pass'  → → 1

  2%|▏         | 14/765 [00:11<11:10,  1.12it/s]

[ 14/765]  raw='pass'  → → 1

  2%|▏         | 15/765 [00:12<10:51,  1.15it/s]

[ 15/765]  raw='pass'  → → 1

  2%|▏         | 16/765 [00:13<11:22,  1.10it/s]

[ 16/765]  raw='pass'  → → 1

  2%|▏         | 17/765 [00:14<11:08,  1.12it/s]

[ 17/765]  raw='pass'  → → 1

  2%|▏         | 18/765 [00:15<11:58,  1.04it/s]

[ 18/765]  raw='pass'  → → 1

  2%|▏         | 19/765 [00:16<10:44,  1.16it/s]

[ 19/765]  raw='fail'  → → 0

  3%|▎         | 20/765 [00:17<12:58,  1.04s/it]

[ 20/765]  raw='pass'  → → 1

  3%|▎         | 21/765 [00:18<11:22,  1.09it/s]

[ 21/765]  raw='fail'  → → 0

  3%|▎         | 22/765 [00:19<10:19,  1.20it/s]

[ 22/765]  raw='fail'  → → 0

  3%|▎         | 23/765 [00:19<09:17,  1.33it/s]

[ 23/765]  raw='fail'  → → 0

  3%|▎         | 24/765 [00:21<11:30,  1.07it/s]

[ 24/765]  raw='pass'  → → 1

  3%|▎         | 25/765 [00:22<11:52,  1.04it/s]

[ 25/765]  raw='pass'  → → 1

  3%|▎         | 26/765 [00:22<10:57,  1.12it/s]

[ 26/765]  raw='pass'  → → 1

  4%|▎         | 27/765 [00:23<10:07,  1.21it/s]

[ 27/765]  raw='fail'  → → 0

  4%|▎         | 28/765 [00:24<10:15,  1.20it/s]

[ 28/765]  raw='fail'  → → 0

  4%|▍         | 29/765 [00:25<10:25,  1.18it/s]

[ 29/765]  raw='pass'  → → 1

  4%|▍         | 30/765 [00:26<10:26,  1.17it/s]

[ 30/765]  raw='fail'  → → 0

  4%|▍         | 31/765 [00:26<10:35,  1.16it/s]

[ 31/765]  raw='pass'  → → 1

  4%|▍         | 32/765 [00:27<10:02,  1.22it/s]

[ 32/765]  raw='fail'  → → 0

  4%|▍         | 33/765 [00:29<12:06,  1.01it/s]

[ 33/765]  raw='pass'  → → 1

  4%|▍         | 34/765 [00:29<11:02,  1.10it/s]

[ 34/765]  raw='fail'  → → 0

  5%|▍         | 35/765 [00:30<10:20,  1.18it/s]

[ 35/765]  raw='fail'  → → 0

  5%|▍         | 36/765 [00:31<10:28,  1.16it/s]

[ 36/765]  raw='pass'  → → 1

  5%|▍         | 37/765 [00:32<10:42,  1.13it/s]

[ 37/765]  raw='pass'  → → 1

  5%|▍         | 38/765 [00:33<10:45,  1.13it/s]

[ 38/765]  raw='pass'  → → 1

  5%|▌         | 39/765 [00:34<11:30,  1.05it/s]

[ 39/765]  raw='pass'  → → 1

  5%|▌         | 40/765 [00:35<12:40,  1.05s/it]

[ 40/765]  raw='pass'  → → 1

  5%|▌         | 41/765 [00:37<15:13,  1.26s/it]

[ 41/765]  raw='pass'  → → 1

  5%|▌         | 42/765 [00:38<14:25,  1.20s/it]

[ 42/765]  raw='fail'  → → 0

  6%|▌         | 43/765 [00:38<12:06,  1.01s/it]

[ 43/765]  raw='fail'  → → 0

  6%|▌         | 44/765 [00:39<11:47,  1.02it/s]

[ 44/765]  raw='pass'  → → 1

  6%|▌         | 45/765 [00:40<10:21,  1.16it/s]

[ 45/765]  raw='fail'  → → 0

  6%|▌         | 46/765 [00:41<10:33,  1.13it/s]

[ 46/765]  raw='fail'  → → 0

  6%|▌         | 47/765 [00:42<10:37,  1.13it/s]

[ 47/765]  raw='pass'  → → 1

  6%|▋         | 48/765 [00:43<10:51,  1.10it/s]

[ 48/765]  raw='pass'  → → 1

  6%|▋         | 49/765 [00:44<10:17,  1.16it/s]

[ 49/765]  raw='fail'  → → 0

  7%|▋         | 50/765 [00:45<11:11,  1.06it/s]

[ 50/765]  raw='pass'  → → 1

  7%|▋         | 51/765 [00:46<11:07,  1.07it/s]

[ 51/765]  raw='pass'  → → 1

  7%|▋         | 52/765 [00:46<10:21,  1.15it/s]

[ 52/765]  raw='fail'  → → 0

  7%|▋         | 53/765 [00:47<10:37,  1.12it/s]

[ 53/765]  raw='pass'  → → 1

  7%|▋         | 54/765 [00:49<13:46,  1.16s/it]

[ 54/765]  raw='pass'  → → 1

  7%|▋         | 55/765 [00:50<12:50,  1.09s/it]

[ 55/765]  raw='fail'  → → 0

  7%|▋         | 56/765 [00:51<11:38,  1.02it/s]

[ 56/765]  raw='fail'  → → 0

  7%|▋         | 57/765 [00:52<11:18,  1.04it/s]

[ 57/765]  raw='pass'  → → 1

  8%|▊         | 58/765 [00:53<11:17,  1.04it/s]

[ 58/765]  raw='fail'  → → 0

  8%|▊         | 59/765 [00:54<11:51,  1.01s/it]

[ 59/765]  raw='pass'  → → 1

  8%|▊         | 60/765 [00:54<10:17,  1.14it/s]

[ 60/765]  raw='fail'  → → 0

  8%|▊         | 61/765 [00:55<11:09,  1.05it/s]

[ 61/765]  raw='pass'  → → 1

  8%|▊         | 62/765 [00:56<11:15,  1.04it/s]

[ 62/765]  raw='fail'  → → 0

  8%|▊         | 63/765 [00:58<12:16,  1.05s/it]

[ 63/765]  raw='pass'  → → 1

  8%|▊         | 64/765 [00:58<10:36,  1.10it/s]

[ 64/765]  raw='fail'  → → 0

  8%|▊         | 65/765 [00:59<09:25,  1.24it/s]

[ 65/765]  raw='fail'  → → 0

  9%|▊         | 66/765 [01:00<10:24,  1.12it/s]

[ 66/765]  raw='pass'  → → 1

  9%|▉         | 67/765 [01:01<11:45,  1.01s/it]

[ 67/765]  raw='pass'  → → 1

  9%|▉         | 68/765 [01:02<10:55,  1.06it/s]

[ 68/765]  raw='fail'  → → 0

  9%|▉         | 69/765 [01:03<10:45,  1.08it/s]

[ 69/765]  raw='fail'  → → 0

  9%|▉         | 70/765 [01:04<10:00,  1.16it/s]

[ 70/765]  raw='fail'  → → 0

  9%|▉         | 71/765 [01:04<10:08,  1.14it/s]

[ 71/765]  raw='fail'  → → 0

  9%|▉         | 72/765 [01:05<09:12,  1.25it/s]

[ 72/765]  raw='fail'  → → 0

 10%|▉         | 73/765 [01:06<08:59,  1.28it/s]

[ 73/765]  raw='fail'  → → 0

 10%|▉         | 74/765 [01:07<08:59,  1.28it/s]

[ 74/765]  raw='fail'  → → 0

 10%|▉         | 75/765 [01:07<08:47,  1.31it/s]

[ 75/765]  raw='fail'  → → 0

 10%|▉         | 76/765 [01:08<10:06,  1.14it/s]

[ 76/765]  raw='pass'  → → 1

 10%|█         | 77/765 [01:09<09:03,  1.27it/s]

[ 77/765]  raw='fail'  → → 0

 10%|█         | 78/765 [01:10<09:39,  1.19it/s]

[ 78/765]  raw='pass'  → → 1

 10%|█         | 79/765 [01:11<09:05,  1.26it/s]

[ 79/765]  raw='fail'  → → 0

 10%|█         | 80/765 [01:12<11:12,  1.02it/s]

[ 80/765]  raw='pass'  → → 1

 11%|█         | 81/765 [01:13<12:05,  1.06s/it]

[ 81/765]  raw='pass'  → → 1

 11%|█         | 82/765 [01:14<11:49,  1.04s/it]

[ 82/765]  raw='pass'  → → 1

 11%|█         | 83/765 [01:16<13:37,  1.20s/it]

[ 83/765]  raw='pass'  → → 1

 11%|█         | 84/765 [01:17<14:57,  1.32s/it]

[ 84/765]  raw='pass'  → → 1

 11%|█         | 85/765 [01:18<12:29,  1.10s/it]

[ 85/765]  raw='fail'  → → 0

 11%|█         | 86/765 [01:19<12:14,  1.08s/it]

[ 86/765]  raw='fail'  → → 0

 11%|█▏        | 87/765 [01:20<11:47,  1.04s/it]

[ 87/765]  raw='pass'  → → 1

 12%|█▏        | 88/765 [01:21<11:21,  1.01s/it]

[ 88/765]  raw='fail'  → → 0

 12%|█▏        | 89/765 [01:22<11:53,  1.06s/it]

[ 89/765]  raw='pass'  → → 1

 12%|█▏        | 90/765 [01:23<10:47,  1.04it/s]

[ 90/765]  raw='fail'  → → 0

 12%|█▏        | 91/765 [01:24<11:28,  1.02s/it]

[ 91/765]  raw='pass'  → → 1

 12%|█▏        | 92/765 [01:26<13:28,  1.20s/it]

[ 92/765]  raw='pass'  → → 1

 12%|█▏        | 93/765 [01:27<13:45,  1.23s/it]

[ 93/765]  raw='pass'  → → 1

 12%|█▏        | 94/765 [01:28<12:11,  1.09s/it]

[ 94/765]  raw='fail'  → → 0

 12%|█▏        | 95/765 [01:29<11:38,  1.04s/it]

[ 95/765]  raw='fail'  → → 0

 13%|█▎        | 96/765 [01:29<10:12,  1.09it/s]

[ 96/765]  raw='fail'  → → 0

 13%|█▎        | 97/765 [01:30<09:14,  1.21it/s]

[ 97/765]  raw='fail'  → → 0

 13%|█▎        | 98/765 [01:31<09:03,  1.23it/s]

[ 98/765]  raw='fail'  → → 0

 13%|█▎        | 99/765 [01:32<11:36,  1.05s/it]

[ 99/765]  raw='pass'  → → 1

 13%|█▎        | 100/765 [01:33<10:11,  1.09it/s]

[100/765]  raw='fail'  → → 0

 13%|█▎        | 101/765 [01:34<09:29,  1.17it/s]

[101/765]  raw='fail'  → → 0

 13%|█▎        | 102/765 [01:35<09:48,  1.13it/s]

[102/765]  raw='fail'  → → 0

 13%|█▎        | 103/765 [01:35<09:27,  1.17it/s]

[103/765]  raw='fail'  → → 0

 14%|█▎        | 104/765 [01:36<09:20,  1.18it/s]

[104/765]  raw='fail'  → → 0

 14%|█▎        | 105/765 [01:37<08:35,  1.28it/s]

[105/765]  raw='fail'  → → 0

 14%|█▍        | 106/765 [01:38<11:12,  1.02s/it]

[106/765]  raw='pass'  → → 1

 14%|█▍        | 107/765 [01:40<11:52,  1.08s/it]

[107/765]  raw='pass'  → → 1

 14%|█▍        | 108/765 [01:40<10:52,  1.01it/s]

[108/765]  raw='fail'  → → 0

 14%|█▍        | 109/765 [01:42<11:54,  1.09s/it]

[109/765]  raw='pass'  → → 1

 14%|█▍        | 110/765 [01:43<10:55,  1.00s/it]

[110/765]  raw='fail'  → → 0

 15%|█▍        | 111/765 [01:43<10:16,  1.06it/s]

[111/765]  raw='fail'  → → 0

 15%|█▍        | 112/765 [01:44<09:16,  1.17it/s]

[112/765]  raw='fail'  → → 0

 15%|█▍        | 113/765 [01:45<09:43,  1.12it/s]

[113/765]  raw='pass'  → → 1

 15%|█▍        | 114/765 [01:46<10:20,  1.05it/s]

[114/765]  raw='pass'  → → 1

 15%|█▌        | 115/765 [01:47<09:47,  1.11it/s]

[115/765]  raw='fail'  → → 0

 15%|█▌        | 116/765 [01:48<09:27,  1.14it/s]

[116/765]  raw='fail'  → → 0

 15%|█▌        | 117/765 [01:49<10:20,  1.04it/s]

[117/765]  raw='pass'  → → 1

 15%|█▌        | 118/765 [01:50<10:39,  1.01it/s]

[118/765]  raw='pass'  → → 1

 16%|█▌        | 119/765 [01:51<10:34,  1.02it/s]

[119/765]  raw='pass'  → → 1

 16%|█▌        | 120/765 [01:52<11:24,  1.06s/it]

[120/765]  raw='pass'  → → 1

 16%|█▌        | 121/765 [01:53<12:21,  1.15s/it]

[121/765]  raw='pass'  → → 1

 16%|█▌        | 122/765 [01:54<12:02,  1.12s/it]

[122/765]  raw='fail'  → → 0

 16%|█▌        | 123/765 [01:56<12:39,  1.18s/it]

[123/765]  raw='pass'  → → 1

 16%|█▌        | 124/765 [01:57<13:01,  1.22s/it]

[124/765]  raw='pass'  → → 1

 16%|█▋        | 125/765 [01:58<11:09,  1.05s/it]

[125/765]  raw='fail'  → → 0

 16%|█▋        | 126/765 [01:59<10:24,  1.02it/s]

[126/765]  raw='fail'  → → 0

 17%|█▋        | 127/765 [01:59<09:59,  1.06it/s]

[127/765]  raw='fail'  → → 0

 17%|█▋        | 128/765 [02:00<09:36,  1.10it/s]

[128/765]  raw='fail'  → → 0

 17%|█▋        | 129/765 [02:01<10:32,  1.01it/s]

[129/765]  raw='fail'  → → 0

 17%|█▋        | 130/765 [02:03<11:44,  1.11s/it]

[130/765]  raw='pass'  → → 1

 17%|█▋        | 131/765 [02:04<11:29,  1.09s/it]

[131/765]  raw='fail'  → → 0

 17%|█▋        | 132/765 [02:05<10:35,  1.00s/it]

[132/765]  raw='fail'  → → 0

 17%|█▋        | 133/765 [02:06<10:29,  1.00it/s]

[133/765]  raw='fail'  → → 0

 18%|█▊        | 134/765 [02:07<10:34,  1.01s/it]

[134/765]  raw='fail'  → → 0

 18%|█▊        | 135/765 [02:07<10:00,  1.05it/s]

[135/765]  raw='fail'  → → 0

 18%|█▊        | 136/765 [02:09<10:22,  1.01it/s]

[136/765]  raw='pass'  → → 1

 18%|█▊        | 137/765 [02:10<12:33,  1.20s/it]

[137/765]  raw='pass'  → → 1

 18%|█▊        | 138/765 [02:11<12:38,  1.21s/it]

[138/765]  raw='pass'  → → 1

 18%|█▊        | 139/765 [02:13<14:11,  1.36s/it]

[139/765]  raw='pass'  → → 1

 18%|█▊        | 140/765 [02:14<11:56,  1.15s/it]

[140/765]  raw='fail'  → → 0

 18%|█▊        | 141/765 [02:15<11:19,  1.09s/it]

[141/765]  raw='fail'  → → 0

 19%|█▊        | 142/765 [02:16<12:06,  1.17s/it]

[142/765]  raw='fail'  → → 0

 19%|█▊        | 143/765 [02:17<11:04,  1.07s/it]

[143/765]  raw='pass'  → → 1

 19%|█▉        | 144/765 [02:19<14:20,  1.39s/it]

[144/765]  raw='pass'  → → 1

 19%|█▉        | 145/765 [02:20<13:18,  1.29s/it]

[145/765]  raw='pass'  → → 1

 19%|█▉        | 146/765 [02:21<12:16,  1.19s/it]

[146/765]  raw='pass'  → → 1

 19%|█▉        | 147/765 [02:23<13:45,  1.34s/it]

[147/765]  raw='pass'  → → 1

 19%|█▉        | 148/765 [02:24<13:35,  1.32s/it]

[148/765]  raw='pass'  → → 1

 19%|█▉        | 149/765 [02:25<12:43,  1.24s/it]

[149/765]  raw='pass'  → → 1

 20%|█▉        | 150/765 [02:26<11:28,  1.12s/it]

[150/765]  raw='fail'  → → 0

 20%|█▉        | 151/765 [02:28<12:40,  1.24s/it]

[151/765]  raw='pass'  → → 1

 20%|█▉        | 152/765 [02:29<12:25,  1.22s/it]

[152/765]  raw='pass'  → → 1

 20%|██        | 153/765 [02:30<11:38,  1.14s/it]

[153/765]  raw='fail'  → → 0

 20%|██        | 154/765 [02:31<11:51,  1.17s/it]

[154/765]  raw='pass'  → → 1

 20%|██        | 155/765 [02:32<12:14,  1.20s/it]

[155/765]  raw='pass'  → → 1

 20%|██        | 156/765 [02:34<12:49,  1.26s/it]

[156/765]  raw='pass'  → → 1

 21%|██        | 157/765 [02:35<13:11,  1.30s/it]

[157/765]  raw='pass'  → → 1

 21%|██        | 158/765 [02:36<13:28,  1.33s/it]

[158/765]  raw='pass'  → → 1

 21%|██        | 159/765 [02:38<13:05,  1.30s/it]

[159/765]  raw='pass'  → → 1

 21%|██        | 160/765 [02:39<13:23,  1.33s/it]

[160/765]  raw='pass'  → → 1

 21%|██        | 161/765 [02:40<11:41,  1.16s/it]

[161/765]  raw='fail'  → → 0

 21%|██        | 162/765 [02:40<10:07,  1.01s/it]

[162/765]  raw='fail'  → → 0

 21%|██▏       | 163/765 [02:41<10:06,  1.01s/it]

[163/765]  raw='fail'  → → 0

 21%|██▏       | 164/765 [02:42<10:06,  1.01s/it]

[164/765]  raw='pass'  → → 1

 22%|██▏       | 165/765 [02:43<10:14,  1.02s/it]

[165/765]  raw='fail'  → → 0

 22%|██▏       | 166/765 [02:44<10:00,  1.00s/it]

[166/765]  raw='fail'  → → 0

 22%|██▏       | 167/765 [02:45<09:18,  1.07it/s]

[167/765]  raw='fail'  → → 0

 22%|██▏       | 168/765 [02:46<09:28,  1.05it/s]

[168/765]  raw='fail'  → → 0

 22%|██▏       | 169/765 [02:47<10:01,  1.01s/it]

[169/765]  raw='pass'  → → 1

 22%|██▏       | 170/765 [02:48<10:00,  1.01s/it]

[170/765]  raw='pass'  → → 1

 22%|██▏       | 171/765 [02:50<11:08,  1.12s/it]

[171/765]  raw='pass'  → → 1

 22%|██▏       | 172/765 [02:51<11:37,  1.18s/it]

[172/765]  raw='pass'  → → 1

 23%|██▎       | 173/765 [02:53<12:45,  1.29s/it]

[173/765]  raw='pass'  → → 1

 23%|██▎       | 174/765 [02:54<13:32,  1.37s/it]

[174/765]  raw='pass'  → → 1

 23%|██▎       | 175/765 [02:55<11:21,  1.16s/it]

[175/765]  raw='fail'  → → 0

 23%|██▎       | 176/765 [02:56<10:18,  1.05s/it]

[176/765]  raw='fail'  → → 0

 23%|██▎       | 177/765 [02:56<09:36,  1.02it/s]

[177/765]  raw='fail'  → → 0

 23%|██▎       | 178/765 [02:58<10:40,  1.09s/it]

[178/765]  raw='pass'  → → 1

 23%|██▎       | 179/765 [03:00<12:33,  1.29s/it]

[179/765]  raw='pass'  → → 1

 24%|██▎       | 180/765 [03:00<10:36,  1.09s/it]

[180/765]  raw='fail'  → → 0

 24%|██▎       | 181/765 [03:01<09:09,  1.06it/s]

[181/765]  raw='fail'  → → 0

 24%|██▍       | 182/765 [03:01<08:16,  1.17it/s]

[182/765]  raw='fail'  → → 0

 24%|██▍       | 183/765 [03:02<08:04,  1.20it/s]

[183/765]  raw='fail'  → → 0

 24%|██▍       | 184/765 [03:03<07:30,  1.29it/s]

[184/765]  raw='fail'  → → 0

 24%|██▍       | 185/765 [03:04<09:00,  1.07it/s]

[185/765]  raw='pass'  → → 1

 24%|██▍       | 186/765 [03:06<10:23,  1.08s/it]

[186/765]  raw='pass'  → → 1

 24%|██▍       | 187/765 [03:07<10:11,  1.06s/it]

[187/765]  raw='pass'  → → 1

 25%|██▍       | 188/765 [03:07<09:19,  1.03it/s]

[188/765]  raw='fail'  → → 0

 25%|██▍       | 189/765 [03:09<10:08,  1.06s/it]

[189/765]  raw='pass'  → → 1

 25%|██▍       | 190/765 [03:10<10:36,  1.11s/it]

[190/765]  raw='pass'  → → 1

 25%|██▍       | 191/765 [03:11<10:53,  1.14s/it]

[191/765]  raw='pass'  → → 1

 25%|██▌       | 192/765 [03:13<12:20,  1.29s/it]

[192/765]  raw='pass'  → → 1

 25%|██▌       | 193/765 [03:14<11:35,  1.22s/it]

[193/765]  raw='fail'  → → 0

 25%|██▌       | 194/765 [03:15<11:51,  1.25s/it]

[194/765]  raw='fail'  → → 0

 25%|██▌       | 195/765 [03:17<13:58,  1.47s/it]

[195/765]  raw='pass'  → → 1

 26%|██▌       | 196/765 [03:18<11:58,  1.26s/it]

[196/765]  raw='fail'  → → 0

 26%|██▌       | 197/765 [03:19<12:01,  1.27s/it]

[197/765]  raw='pass'  → → 1

 26%|██▌       | 198/765 [03:20<11:06,  1.18s/it]

[198/765]  raw='pass'  → → 1

 26%|██▌       | 199/765 [03:21<10:41,  1.13s/it]

[199/765]  raw='pass'  → → 1

 26%|██▌       | 200/765 [03:22<09:39,  1.03s/it]

[200/765]  raw='fail'  → → 0

 26%|██▋       | 201/765 [03:23<09:30,  1.01s/it]

[201/765]  raw='fail'  → → 0

 26%|██▋       | 202/765 [03:24<09:29,  1.01s/it]

[202/765]  raw='pass'  → → 1

 27%|██▋       | 203/765 [03:25<09:51,  1.05s/it]

[203/765]  raw='fail'  → → 0

 27%|██▋       | 204/765 [03:26<09:11,  1.02it/s]

[204/765]  raw='fail'  → → 0

 27%|██▋       | 205/765 [03:27<08:39,  1.08it/s]

[205/765]  raw='fail'  → → 0

 27%|██▋       | 206/765 [03:28<08:59,  1.04it/s]

[206/765]  raw='pass'  → → 1

 27%|██▋       | 207/765 [03:29<10:08,  1.09s/it]

[207/765]  raw='pass'  → → 1

 27%|██▋       | 208/765 [03:30<10:16,  1.11s/it]

[208/765]  raw='pass'  → → 1

 27%|██▋       | 209/765 [03:31<09:55,  1.07s/it]

[209/765]  raw='fail'  → → 0

 27%|██▋       | 210/765 [03:32<09:44,  1.05s/it]

[210/765]  raw='fail'  → → 0

 28%|██▊       | 211/765 [03:33<08:53,  1.04it/s]

[211/765]  raw='fail'  → → 0

 28%|██▊       | 212/765 [03:34<08:25,  1.09it/s]

[212/765]  raw='fail'  → → 0

 28%|██▊       | 213/765 [03:35<08:50,  1.04it/s]

[213/765]  raw='pass'  → → 1

 28%|██▊       | 214/765 [03:36<08:18,  1.10it/s]

[214/765]  raw='fail'  → → 0

 28%|██▊       | 215/765 [03:37<08:38,  1.06it/s]

[215/765]  raw='pass'  → → 1

 28%|██▊       | 216/765 [03:37<08:15,  1.11it/s]

[216/765]  raw='fail'  → → 0

 28%|██▊       | 217/765 [03:38<07:31,  1.21it/s]

[217/765]  raw='fail'  → → 0

 28%|██▊       | 218/765 [03:40<10:34,  1.16s/it]

[218/765]  raw='pass'  → → 1

 29%|██▊       | 219/765 [03:41<10:59,  1.21s/it]

[219/765]  raw='pass'  → → 1

 29%|██▉       | 220/765 [03:42<09:45,  1.07s/it]

[220/765]  raw='fail'  → → 0

 29%|██▉       | 221/765 [03:43<08:51,  1.02it/s]

[221/765]  raw='fail'  → → 0

 29%|██▉       | 222/765 [03:44<09:00,  1.01it/s]

[222/765]  raw='fail'  → → 0

 29%|██▉       | 223/765 [03:45<10:09,  1.12s/it]

[223/765]  raw='pass'  → → 1

 29%|██▉       | 224/765 [03:47<10:35,  1.17s/it]

[224/765]  raw='pass'  → → 1

 29%|██▉       | 225/765 [03:48<10:03,  1.12s/it]

[225/765]  raw='fail'  → → 0

 30%|██▉       | 226/765 [03:49<10:40,  1.19s/it]

[226/765]  raw='pass'  → → 1

 30%|██▉       | 227/765 [03:50<09:59,  1.11s/it]

[227/765]  raw='fail'  → → 0

 30%|██▉       | 228/765 [03:51<09:00,  1.01s/it]

[228/765]  raw='fail'  → → 0

 30%|██▉       | 229/765 [03:51<08:28,  1.05it/s]

[229/765]  raw='fail'  → → 0

 30%|███       | 230/765 [03:52<08:18,  1.07it/s]

[230/765]  raw='fail'  → → 0

 30%|███       | 231/765 [03:53<08:54,  1.00s/it]

[231/765]  raw='fail'  → → 0

 30%|███       | 232/765 [03:55<09:39,  1.09s/it]

[232/765]  raw='pass'  → → 1

 30%|███       | 233/765 [03:55<08:28,  1.05it/s]

[233/765]  raw='fail'  → → 0

 31%|███       | 234/765 [03:56<08:42,  1.02it/s]

[234/765]  raw='fail'  → → 0

 31%|███       | 235/765 [03:58<09:38,  1.09s/it]

[235/765]  raw='pass'  → → 1

 31%|███       | 236/765 [03:59<09:23,  1.06s/it]

[236/765]  raw='fail'  → → 0

 31%|███       | 237/765 [03:59<08:15,  1.07it/s]

[237/765]  raw='fail'  → → 0

 31%|███       | 238/765 [04:00<07:55,  1.11it/s]

[238/765]  raw='pass'  → → 1

 31%|███       | 239/765 [04:02<08:55,  1.02s/it]

[239/765]  raw='pass'  → → 1

 31%|███▏      | 240/765 [04:03<08:46,  1.00s/it]

[240/765]  raw='pass'  → → 1

 32%|███▏      | 241/765 [04:04<09:43,  1.11s/it]

[241/765]  raw='pass'  → → 1

 32%|███▏      | 242/765 [04:05<08:50,  1.01s/it]

[242/765]  raw='pass'  → → 1

 32%|███▏      | 243/765 [04:05<08:17,  1.05it/s]

[243/765]  raw='fail'  → → 0

 32%|███▏      | 244/765 [04:06<07:27,  1.16it/s]

[244/765]  raw='fail'  → → 0

 32%|███▏      | 245/765 [04:07<07:42,  1.12it/s]

[245/765]  raw='fail'  → → 0

 32%|███▏      | 246/765 [04:09<10:38,  1.23s/it]

[246/765]  raw='pass'  → → 1

 32%|███▏      | 247/765 [04:10<10:38,  1.23s/it]

[247/765]  raw='pass'  → → 1

 32%|███▏      | 248/765 [04:11<09:04,  1.05s/it]

[248/765]  raw='fail'  → → 0

 33%|███▎      | 249/765 [04:12<09:01,  1.05s/it]

[249/765]  raw='pass'  → → 1

 33%|███▎      | 250/765 [04:13<07:58,  1.08it/s]

[250/765]  raw='fail'  → → 0

 33%|███▎      | 251/765 [04:13<07:38,  1.12it/s]

[251/765]  raw='fail'  → → 0

 33%|███▎      | 252/765 [04:15<07:55,  1.08it/s]

[252/765]  raw='pass'  → → 1

 33%|███▎      | 253/765 [04:16<08:15,  1.03it/s]

[253/765]  raw='fail'  → → 0

 33%|███▎      | 254/765 [04:16<07:26,  1.15it/s]

[254/765]  raw='fail'  → → 0

 33%|███▎      | 255/765 [04:18<09:14,  1.09s/it]

[255/765]  raw='pass'  → → 1

 33%|███▎      | 256/765 [04:19<09:04,  1.07s/it]

[256/765]  raw='pass'  → → 1

 34%|███▎      | 257/765 [04:20<08:49,  1.04s/it]

[257/765]  raw='pass'  → → 1

 34%|███▎      | 258/765 [04:21<08:14,  1.02it/s]

[258/765]  raw='fail'  → → 0

 34%|███▍      | 259/765 [04:21<07:49,  1.08it/s]

[259/765]  raw='pass'  → → 1

 34%|███▍      | 260/765 [04:23<08:29,  1.01s/it]

[260/765]  raw='pass'  → → 1

 34%|███▍      | 261/765 [04:23<07:51,  1.07it/s]

[261/765]  raw='fail'  → → 0

 34%|███▍      | 262/765 [04:25<08:58,  1.07s/it]

[262/765]  raw='pass'  → → 1

 34%|███▍      | 263/765 [04:26<09:30,  1.14s/it]

[263/765]  raw='pass'  → → 1

 35%|███▍      | 264/765 [04:27<08:13,  1.01it/s]

[264/765]  raw='fail'  → → 0

 35%|███▍      | 265/765 [04:28<09:15,  1.11s/it]

[265/765]  raw='pass'  → → 1

 35%|███▍      | 266/765 [04:29<09:03,  1.09s/it]

[266/765]  raw='pass'  → → 1

 35%|███▍      | 267/765 [04:31<10:26,  1.26s/it]

[267/765]  raw='pass'  → → 1

 35%|███▌      | 268/765 [04:32<09:55,  1.20s/it]

[268/765]  raw='pass'  → → 1

 35%|███▌      | 269/765 [04:33<09:30,  1.15s/it]

[269/765]  raw='pass'  → → 1

 35%|███▌      | 270/765 [04:34<08:11,  1.01it/s]

[270/765]  raw='fail'  → → 0

 35%|███▌      | 271/765 [04:34<07:39,  1.07it/s]

[271/765]  raw='fail'  → → 0

 36%|███▌      | 272/765 [04:36<08:28,  1.03s/it]

[272/765]  raw='pass'  → → 1

 36%|███▌      | 273/765 [04:36<07:26,  1.10it/s]

[273/765]  raw='fail'  → → 0

 36%|███▌      | 274/765 [04:37<07:45,  1.05it/s]

[274/765]  raw='pass'  → → 1

 36%|███▌      | 275/765 [04:39<09:28,  1.16s/it]

[275/765]  raw='pass'  → → 1

 36%|███▌      | 276/765 [04:40<08:31,  1.05s/it]

[276/765]  raw='fail'  → → 0

 36%|███▌      | 277/765 [04:41<08:34,  1.05s/it]

[277/765]  raw='fail'  → → 0

 36%|███▋      | 278/765 [04:41<07:31,  1.08it/s]

[278/765]  raw='fail'  → → 0

 36%|███▋      | 279/765 [04:43<08:05,  1.00it/s]

[279/765]  raw='pass'  → → 1

 37%|███▋      | 280/765 [04:43<07:25,  1.09it/s]

[280/765]  raw='fail'  → → 0

 37%|███▋      | 281/765 [04:45<08:59,  1.11s/it]

[281/765]  raw='pass'  → → 1

 37%|███▋      | 282/765 [04:46<08:14,  1.02s/it]

[282/765]  raw='fail'  → → 0

 37%|███▋      | 283/765 [04:47<08:52,  1.10s/it]

[283/765]  raw='pass'  → → 1

 37%|███▋      | 284/765 [04:48<08:39,  1.08s/it]

[284/765]  raw='fail'  → → 0

 37%|███▋      | 285/765 [04:49<07:57,  1.01it/s]

[285/765]  raw='fail'  → → 0

 37%|███▋      | 286/765 [04:50<08:05,  1.01s/it]

[286/765]  raw='pass'  → → 1

 38%|███▊      | 287/765 [04:51<07:41,  1.04it/s]

[287/765]  raw='pass'  → → 1

 38%|███▊      | 288/765 [04:52<07:44,  1.03it/s]

[288/765]  raw='pass'  → → 1

 38%|███▊      | 289/765 [04:52<07:17,  1.09it/s]

[289/765]  raw='fail'  → → 0

 38%|███▊      | 290/765 [04:53<07:29,  1.06it/s]

[290/765]  raw='fail'  → → 0

 38%|███▊      | 291/765 [04:54<07:09,  1.10it/s]

[291/765]  raw='fail'  → → 0

 38%|███▊      | 292/765 [04:55<06:51,  1.15it/s]

[292/765]  raw='fail'  → → 0

 38%|███▊      | 293/765 [04:56<07:49,  1.00it/s]

[293/765]  raw='pass'  → → 1

 38%|███▊      | 294/765 [04:58<09:23,  1.20s/it]

[294/765]  raw='pass'  → → 1

 39%|███▊      | 295/765 [04:59<08:20,  1.06s/it]

[295/765]  raw='fail'  → → 0

 39%|███▊      | 296/765 [05:00<08:42,  1.11s/it]

[296/765]  raw='pass'  → → 1

 39%|███▉      | 297/765 [05:01<08:26,  1.08s/it]

[297/765]  raw='pass'  → → 1

 39%|███▉      | 298/765 [05:02<08:35,  1.10s/it]

[298/765]  raw='pass'  → → 1

 39%|███▉      | 299/765 [05:04<09:54,  1.28s/it]

[299/765]  raw='pass'  → → 1

 39%|███▉      | 300/765 [05:04<08:22,  1.08s/it]

[300/765]  raw='fail'  → → 0

 39%|███▉      | 301/765 [05:05<07:20,  1.05it/s]

[301/765]  raw='fail'  → → 0

 39%|███▉      | 302/765 [05:06<07:46,  1.01s/it]

[302/765]  raw='fail'  → → 0

 40%|███▉      | 303/765 [05:08<09:52,  1.28s/it]

[303/765]  raw='pass'  → → 1

 40%|███▉      | 304/765 [05:09<09:05,  1.18s/it]

[304/765]  raw='fail'  → → 0

 40%|███▉      | 305/765 [05:10<08:11,  1.07s/it]

[305/765]  raw='fail'  → → 0

 40%|████      | 306/765 [05:11<07:11,  1.06it/s]

[306/765]  raw='fail'  → → 0

 40%|████      | 307/765 [05:11<06:45,  1.13it/s]

[307/765]  raw='fail'  → → 0

 40%|████      | 308/765 [05:12<06:31,  1.17it/s]

[308/765]  raw='fail'  → → 0

 40%|████      | 309/765 [05:13<07:09,  1.06it/s]

[309/765]  raw='pass'  → → 1

 41%|████      | 310/765 [05:14<07:22,  1.03it/s]

[310/765]  raw='pass'  → → 1

 41%|████      | 311/765 [05:15<07:21,  1.03it/s]

[311/765]  raw='fail'  → → 0

 41%|████      | 312/765 [05:16<06:57,  1.09it/s]

[312/765]  raw='fail'  → → 0

 41%|████      | 313/765 [05:17<06:38,  1.13it/s]

[313/765]  raw='fail'  → → 0

 41%|████      | 314/765 [05:18<07:35,  1.01s/it]

[314/765]  raw='pass'  → → 1

 41%|████      | 315/765 [05:19<06:39,  1.13it/s]

[315/765]  raw='fail'  → → 0

 41%|████▏     | 316/765 [05:20<06:51,  1.09it/s]

[316/765]  raw='fail'  → → 0

 41%|████▏     | 317/765 [05:21<07:02,  1.06it/s]

[317/765]  raw='pass'  → → 1

 42%|████▏     | 318/765 [05:22<07:07,  1.04it/s]

[318/765]  raw='fail'  → → 0

 42%|████▏     | 319/765 [05:23<06:47,  1.09it/s]

[319/765]  raw='fail'  → → 0

 42%|████▏     | 320/765 [05:24<07:02,  1.05it/s]

[320/765]  raw='fail'  → → 0

 42%|████▏     | 321/765 [05:24<06:40,  1.11it/s]

[321/765]  raw='fail'  → → 0

 42%|████▏     | 322/765 [05:25<06:48,  1.08it/s]

[322/765]  raw='fail'  → → 0

 42%|████▏     | 323/765 [05:27<07:23,  1.00s/it]

[323/765]  raw='pass'  → → 1

 42%|████▏     | 324/765 [05:27<06:56,  1.06it/s]

[324/765]  raw='pass'  → → 1

 42%|████▏     | 325/765 [05:28<06:59,  1.05it/s]

[325/765]  raw='pass'  → → 1

 43%|████▎     | 326/765 [05:30<08:20,  1.14s/it]

[326/765]  raw='pass'  → → 1

 43%|████▎     | 327/765 [05:31<07:24,  1.02s/it]

[327/765]  raw='fail'  → → 0

 43%|████▎     | 328/765 [05:32<07:46,  1.07s/it]

[328/765]  raw='pass'  → → 1

 43%|████▎     | 329/765 [05:32<06:49,  1.06it/s]

[329/765]  raw='fail'  → → 0

 43%|████▎     | 330/765 [05:34<07:15,  1.00s/it]

[330/765]  raw='pass'  → → 1

 43%|████▎     | 331/765 [05:34<06:51,  1.05it/s]

[331/765]  raw='fail'  → → 0

 43%|████▎     | 332/765 [05:35<06:50,  1.05it/s]

[332/765]  raw='fail'  → → 0

 44%|████▎     | 333/765 [05:36<06:53,  1.05it/s]

[333/765]  raw='fail'  → → 0

 44%|████▎     | 334/765 [05:38<07:35,  1.06s/it]

[334/765]  raw='pass'  → → 1

 44%|████▍     | 335/765 [05:38<07:02,  1.02it/s]

[335/765]  raw='fail'  → → 0

 44%|████▍     | 336/765 [05:39<06:31,  1.09it/s]

[336/765]  raw='fail'  → → 0

 44%|████▍     | 337/765 [05:40<06:50,  1.04it/s]

[337/765]  raw='pass'  → → 1

 44%|████▍     | 338/765 [05:41<06:59,  1.02it/s]

[338/765]  raw='pass'  → → 1

 44%|████▍     | 339/765 [05:43<08:16,  1.16s/it]

[339/765]  raw='pass'  → → 1

 44%|████▍     | 340/765 [05:44<08:12,  1.16s/it]

[340/765]  raw='pass'  → → 1

 45%|████▍     | 341/765 [05:45<07:54,  1.12s/it]

[341/765]  raw='pass'  → → 1

 45%|████▍     | 342/765 [05:46<08:15,  1.17s/it]

[342/765]  raw='pass'  → → 1

 45%|████▍     | 343/765 [05:48<08:38,  1.23s/it]

[343/765]  raw='pass'  → → 1

 45%|████▍     | 344/765 [05:49<08:13,  1.17s/it]

[344/765]  raw='pass'  → → 1

 45%|████▌     | 345/765 [05:50<07:48,  1.12s/it]

[345/765]  raw='pass'  → → 1

 45%|████▌     | 346/765 [05:51<08:42,  1.25s/it]

[346/765]  raw='pass'  → → 1

 45%|████▌     | 347/765 [05:52<08:12,  1.18s/it]

[347/765]  raw='pass'  → → 1

 45%|████▌     | 348/765 [05:53<07:54,  1.14s/it]

[348/765]  raw='pass'  → → 1

 46%|████▌     | 349/765 [05:54<07:08,  1.03s/it]

[349/765]  raw='fail'  → → 0

 46%|████▌     | 350/765 [05:55<06:29,  1.06it/s]

[350/765]  raw='fail'  → → 0

 46%|████▌     | 351/765 [05:56<06:43,  1.03it/s]

[351/765]  raw='fail'  → → 0

 46%|████▌     | 352/765 [05:57<06:50,  1.01it/s]

[352/765]  raw='pass'  → → 1

 46%|████▌     | 353/765 [05:58<06:49,  1.01it/s]

[353/765]  raw='fail'  → → 0

 46%|████▋     | 354/765 [05:59<06:06,  1.12it/s]

[354/765]  raw='fail'  → → 0

 46%|████▋     | 355/765 [06:00<06:24,  1.07it/s]

[355/765]  raw='pass'  → → 1

 47%|████▋     | 356/765 [06:01<07:00,  1.03s/it]

[356/765]  raw='pass'  → → 1

 47%|████▋     | 357/765 [06:02<06:55,  1.02s/it]

[357/765]  raw='pass'  → → 1

 47%|████▋     | 358/765 [06:03<06:56,  1.02s/it]

[358/765]  raw='pass'  → → 1

 47%|████▋     | 359/765 [06:04<07:38,  1.13s/it]

[359/765]  raw='pass'  → → 1

 47%|████▋     | 360/765 [06:05<06:57,  1.03s/it]

[360/765]  raw='fail'  → → 0

 47%|████▋     | 361/765 [06:06<06:28,  1.04it/s]

[361/765]  raw='fail'  → → 0

 47%|████▋     | 362/765 [06:07<07:32,  1.12s/it]

[362/765]  raw='pass'  → → 1

 47%|████▋     | 363/765 [06:08<06:49,  1.02s/it]

[363/765]  raw='fail'  → → 0

 48%|████▊     | 364/765 [06:09<07:03,  1.06s/it]

[364/765]  raw='pass'  → → 1

 48%|████▊     | 365/765 [06:11<07:58,  1.20s/it]

[365/765]  raw='pass'  → → 1

 48%|████▊     | 366/765 [06:11<06:49,  1.03s/it]

[366/765]  raw='fail'  → → 0

 48%|████▊     | 367/765 [06:13<07:05,  1.07s/it]

[367/765]  raw='pass'  → → 1

 48%|████▊     | 368/765 [06:13<06:10,  1.07it/s]

[368/765]  raw='fail'  → → 0

 48%|████▊     | 369/765 [06:15<06:52,  1.04s/it]

[369/765]  raw='pass'  → → 1

 48%|████▊     | 370/765 [06:16<07:34,  1.15s/it]

[370/765]  raw='pass'  → → 1

 48%|████▊     | 371/765 [06:17<07:19,  1.12s/it]

[371/765]  raw='pass'  → → 1

 49%|████▊     | 372/765 [06:18<06:21,  1.03it/s]

[372/765]  raw='fail'  → → 0

 49%|████▉     | 373/765 [06:19<07:27,  1.14s/it]

[373/765]  raw='pass'  → → 1

 49%|████▉     | 374/765 [06:20<07:14,  1.11s/it]

[374/765]  raw='pass'  → → 1

 49%|████▉     | 375/765 [06:21<07:15,  1.12s/it]

[375/765]  raw='pass'  → → 1

 49%|████▉     | 376/765 [06:22<07:10,  1.11s/it]

[376/765]  raw='fail'  → → 0

 49%|████▉     | 377/765 [06:24<07:23,  1.14s/it]

[377/765]  raw='pass'  → → 1

 49%|████▉     | 378/765 [06:25<08:07,  1.26s/it]

[378/765]  raw='pass'  → → 1

 50%|████▉     | 379/765 [06:26<06:52,  1.07s/it]

[379/765]  raw='fail'  → → 0

 50%|████▉     | 380/765 [06:26<05:58,  1.07it/s]

[380/765]  raw='fail'  → → 0

 50%|████▉     | 381/765 [06:28<06:51,  1.07s/it]

[381/765]  raw='pass'  → → 1

 50%|████▉     | 382/765 [06:29<06:21,  1.00it/s]

[382/765]  raw='fail'  → → 0

 50%|█████     | 383/765 [06:29<05:39,  1.12it/s]

[383/765]  raw='fail'  → → 0

 50%|█████     | 384/765 [06:30<05:56,  1.07it/s]

[384/765]  raw='pass'  → → 1

 50%|█████     | 385/765 [06:31<05:18,  1.19it/s]

[385/765]  raw='fail'  → → 0

 50%|█████     | 386/765 [06:32<06:08,  1.03it/s]

[386/765]  raw='pass'  → → 1

 51%|█████     | 387/765 [06:33<05:47,  1.09it/s]

[387/765]  raw='fail'  → → 0

 51%|█████     | 388/765 [06:34<06:04,  1.03it/s]

[388/765]  raw='pass'  → → 1

 51%|█████     | 389/765 [06:35<06:35,  1.05s/it]

[389/765]  raw='pass'  → → 1

 51%|█████     | 390/765 [06:36<06:36,  1.06s/it]

[390/765]  raw='pass'  → → 1

 51%|█████     | 391/765 [06:37<06:07,  1.02it/s]

[391/765]  raw='fail'  → → 0

 51%|█████     | 392/765 [06:38<05:42,  1.09it/s]

[392/765]  raw='fail'  → → 0

 51%|█████▏    | 393/765 [06:39<05:49,  1.07it/s]

[393/765]  raw='pass'  → → 1

 52%|█████▏    | 394/765 [06:41<08:02,  1.30s/it]

[394/765]  raw='pass'  → → 1

 52%|█████▏    | 395/765 [06:42<07:50,  1.27s/it]

[395/765]  raw='pass'  → → 1

 52%|█████▏    | 396/765 [06:43<07:18,  1.19s/it]

[396/765]  raw='fail'  → → 0

 52%|█████▏    | 397/765 [06:45<07:25,  1.21s/it]

[397/765]  raw='pass'  → → 1

 52%|█████▏    | 398/765 [06:46<07:04,  1.16s/it]

[398/765]  raw='fail'  → → 0

 52%|█████▏    | 399/765 [06:47<06:48,  1.12s/it]

[399/765]  raw='fail'  → → 0

 52%|█████▏    | 400/765 [06:48<06:57,  1.14s/it]

[400/765]  raw='pass'  → → 1

 52%|█████▏    | 401/765 [06:49<06:38,  1.10s/it]

[401/765]  raw='fail'  → → 0

 53%|█████▎    | 402/765 [06:50<07:07,  1.18s/it]

[402/765]  raw='pass'  → → 1

 53%|█████▎    | 403/765 [06:51<06:07,  1.02s/it]

[403/765]  raw='fail'  → → 0

 53%|█████▎    | 404/765 [06:52<05:44,  1.05it/s]

[404/765]  raw='fail'  → → 0

 53%|█████▎    | 405/765 [06:52<05:26,  1.10it/s]

[405/765]  raw='fail'  → → 0

 53%|█████▎    | 406/765 [06:54<05:42,  1.05it/s]

[406/765]  raw='pass'  → → 1

 53%|█████▎    | 407/765 [06:55<06:53,  1.15s/it]

[407/765]  raw='pass'  → → 1

 53%|█████▎    | 408/765 [06:56<06:13,  1.05s/it]

[408/765]  raw='fail'  → → 0

 53%|█████▎    | 409/765 [06:57<06:02,  1.02s/it]

[409/765]  raw='pass'  → → 1

 54%|█████▎    | 410/765 [06:58<05:21,  1.10it/s]

[410/765]  raw='fail'  → → 0

 54%|█████▎    | 411/765 [06:58<04:51,  1.22it/s]

[411/765]  raw='fail'  → → 0

 54%|█████▍    | 412/765 [07:00<05:56,  1.01s/it]

[412/765]  raw='pass'  → → 1

 54%|█████▍    | 413/765 [07:01<06:25,  1.10s/it]

[413/765]  raw='pass'  → → 1

 54%|█████▍    | 414/765 [07:02<06:54,  1.18s/it]

[414/765]  raw='pass'  → → 1

 54%|█████▍    | 415/765 [07:03<06:09,  1.05s/it]

[415/765]  raw='fail'  → → 0

 54%|█████▍    | 416/765 [07:04<05:34,  1.04it/s]

[416/765]  raw='fail'  → → 0

 55%|█████▍    | 417/765 [07:04<04:56,  1.17it/s]

[417/765]  raw='fail'  → → 0

 55%|█████▍    | 418/765 [07:05<04:53,  1.18it/s]

[418/765]  raw='fail'  → → 0

 55%|█████▍    | 419/765 [07:06<05:24,  1.07it/s]

[419/765]  raw='fail'  → → 0

 55%|█████▍    | 420/765 [07:07<05:37,  1.02it/s]

[420/765]  raw='pass'  → → 1

 55%|█████▌    | 421/765 [07:08<05:16,  1.09it/s]

[421/765]  raw='fail'  → → 0

 55%|█████▌    | 422/765 [07:10<06:28,  1.13s/it]

[422/765]  raw='pass'  → → 1

 55%|█████▌    | 423/765 [07:11<06:52,  1.21s/it]

[423/765]  raw='pass'  → → 1

 55%|█████▌    | 424/765 [07:12<05:55,  1.04s/it]

[424/765]  raw='fail'  → → 0

 56%|█████▌    | 425/765 [07:13<05:52,  1.04s/it]

[425/765]  raw='fail'  → → 0

 56%|█████▌    | 426/765 [07:14<06:22,  1.13s/it]

[426/765]  raw='pass'  → → 1

 56%|█████▌    | 427/765 [07:16<07:52,  1.40s/it]

[427/765]  raw='pass'  → → 1

 56%|█████▌    | 428/765 [07:17<06:35,  1.17s/it]

[428/765]  raw='fail'  → → 0

 56%|█████▌    | 429/765 [07:18<06:33,  1.17s/it]

[429/765]  raw='fail'  → → 0

 56%|█████▌    | 430/765 [07:19<06:33,  1.17s/it]

[430/765]  raw='pass'  → → 1

 56%|█████▋    | 431/765 [07:20<06:29,  1.17s/it]

[431/765]  raw='pass'  → → 1

 56%|█████▋    | 432/765 [07:22<06:19,  1.14s/it]

[432/765]  raw='fail'  → → 0

 57%|█████▋    | 433/765 [07:23<06:09,  1.11s/it]

[433/765]  raw='pass'  → → 1

 57%|█████▋    | 434/765 [07:23<05:31,  1.00s/it]

[434/765]  raw='fail'  → → 0

 57%|█████▋    | 435/765 [07:24<05:06,  1.08it/s]

[435/765]  raw='fail'  → → 0

 57%|█████▋    | 436/765 [07:25<05:09,  1.06it/s]

[436/765]  raw='fail'  → → 0

 57%|█████▋    | 437/765 [07:26<04:56,  1.10it/s]

[437/765]  raw='fail'  → → 0

 57%|█████▋    | 438/765 [07:26<04:29,  1.21it/s]

[438/765]  raw='fail'  → → 0

 57%|█████▋    | 439/765 [07:28<04:52,  1.12it/s]

[439/765]  raw='pass'  → → 1

 58%|█████▊    | 440/765 [07:28<04:43,  1.15it/s]

[440/765]  raw='fail'  → → 0

 58%|█████▊    | 441/765 [07:29<05:02,  1.07it/s]

[441/765]  raw='pass'  → → 1

 58%|█████▊    | 442/765 [07:30<04:50,  1.11it/s]

[442/765]  raw='fail'  → → 0

 58%|█████▊    | 443/765 [07:31<04:22,  1.23it/s]

[443/765]  raw='fail'  → → 0

 58%|█████▊    | 444/765 [07:32<04:16,  1.25it/s]

[444/765]  raw='fail'  → → 0

 58%|█████▊    | 445/765 [07:33<04:58,  1.07it/s]

[445/765]  raw='pass'  → → 1

 58%|█████▊    | 446/765 [07:34<04:47,  1.11it/s]

[446/765]  raw='pass'  → → 1

 58%|█████▊    | 447/765 [07:35<05:16,  1.00it/s]

[447/765]  raw='pass'  → → 1

 59%|█████▊    | 448/765 [07:36<05:01,  1.05it/s]

[448/765]  raw='fail'  → → 0

 59%|█████▊    | 449/765 [07:37<04:50,  1.09it/s]

[449/765]  raw='fail'  → → 0

 59%|█████▉    | 450/765 [07:38<05:14,  1.00it/s]

[450/765]  raw='pass'  → → 1

 59%|█████▉    | 451/765 [07:38<04:39,  1.13it/s]

[451/765]  raw='fail'  → → 0

 59%|█████▉    | 452/765 [07:39<04:23,  1.19it/s]

[452/765]  raw='fail'  → → 0

 59%|█████▉    | 453/765 [07:40<04:41,  1.11it/s]

[453/765]  raw='fail'  → → 0

 59%|█████▉    | 454/765 [07:41<04:32,  1.14it/s]

[454/765]  raw='fail'  → → 0

 59%|█████▉    | 455/765 [07:42<05:09,  1.00it/s]

[455/765]  raw='pass'  → → 1

 60%|█████▉    | 456/765 [07:43<05:06,  1.01it/s]

[456/765]  raw='pass'  → → 1

 60%|█████▉    | 457/765 [07:45<05:25,  1.06s/it]

[457/765]  raw='fail'  → → 0

 60%|█████▉    | 458/765 [07:45<05:04,  1.01it/s]

[458/765]  raw='fail'  → → 0

 60%|██████    | 459/765 [07:46<04:46,  1.07it/s]

[459/765]  raw='fail'  → → 0

 60%|██████    | 460/765 [07:47<04:19,  1.18it/s]

[460/765]  raw='fail'  → → 0

 60%|██████    | 461/765 [07:48<05:02,  1.01it/s]

[461/765]  raw='pass'  → → 1

 60%|██████    | 462/765 [07:50<05:36,  1.11s/it]

[462/765]  raw='pass'  → → 1

 61%|██████    | 463/765 [07:50<04:50,  1.04it/s]

[463/765]  raw='fail'  → → 0

 61%|██████    | 464/765 [07:51<04:39,  1.08it/s]

[464/765]  raw='fail'  → → 0

 61%|██████    | 465/765 [07:52<04:58,  1.01it/s]

[465/765]  raw='pass'  → → 1

 61%|██████    | 466/765 [07:53<04:39,  1.07it/s]

[466/765]  raw='fail'  → → 0

 61%|██████    | 467/765 [07:54<04:48,  1.03it/s]

[467/765]  raw='pass'  → → 1

 61%|██████    | 468/765 [07:55<04:57,  1.00s/it]

[468/765]  raw='pass'  → → 1

 61%|██████▏   | 469/765 [07:56<04:39,  1.06it/s]

[469/765]  raw='fail'  → → 0

 61%|██████▏   | 470/765 [07:57<05:31,  1.12s/it]

[470/765]  raw='pass'  → → 1

 62%|██████▏   | 471/765 [07:58<04:58,  1.02s/it]

[471/765]  raw='fail'  → → 0

 62%|██████▏   | 472/765 [07:59<04:35,  1.06it/s]

[472/765]  raw='fail'  → → 0

 62%|██████▏   | 473/765 [08:00<04:31,  1.08it/s]

[473/765]  raw='fail'  → → 0

 62%|██████▏   | 474/765 [08:01<04:21,  1.11it/s]

[474/765]  raw='fail'  → → 0

 62%|██████▏   | 475/765 [08:02<04:29,  1.08it/s]

[475/765]  raw='pass'  → → 1

 62%|██████▏   | 476/765 [08:02<04:18,  1.12it/s]

[476/765]  raw='fail'  → → 0

 62%|██████▏   | 477/765 [08:04<05:28,  1.14s/it]

[477/765]  raw='fail'  → → 0

 62%|██████▏   | 478/765 [08:05<04:44,  1.01it/s]

[478/765]  raw='fail'  → → 0

 63%|██████▎   | 479/765 [08:06<04:50,  1.02s/it]

[479/765]  raw='pass'  → → 1

 63%|██████▎   | 480/765 [08:07<05:01,  1.06s/it]

[480/765]  raw='pass'  → → 1

 63%|██████▎   | 481/765 [08:08<05:13,  1.10s/it]

[481/765]  raw='pass'  → → 1

 63%|██████▎   | 482/765 [08:09<04:51,  1.03s/it]

[482/765]  raw='fail'  → → 0

 63%|██████▎   | 483/765 [08:10<04:16,  1.10it/s]

[483/765]  raw='fail'  → → 0

 63%|██████▎   | 484/765 [08:11<04:23,  1.07it/s]

[484/765]  raw='fail'  → → 0

 63%|██████▎   | 485/765 [08:12<04:30,  1.04it/s]

[485/765]  raw='pass'  → → 1

 64%|██████▎   | 486/765 [08:13<05:05,  1.09s/it]

[486/765]  raw='pass'  → → 1

 64%|██████▎   | 487/765 [08:14<04:26,  1.04it/s]

[487/765]  raw='fail'  → → 0

 64%|██████▍   | 488/765 [08:15<04:50,  1.05s/it]

[488/765]  raw='pass'  → → 1

 64%|██████▍   | 489/765 [08:16<04:47,  1.04s/it]

[489/765]  raw='fail'  → → 0

 64%|██████▍   | 490/765 [08:17<05:02,  1.10s/it]

[490/765]  raw='pass'  → → 1

 64%|██████▍   | 491/765 [08:18<04:55,  1.08s/it]

[491/765]  raw='pass'  → → 1

 64%|██████▍   | 492/765 [08:19<04:50,  1.06s/it]

[492/765]  raw='pass'  → → 1

 64%|██████▍   | 493/765 [08:20<04:44,  1.05s/it]

[493/765]  raw='fail'  → → 0

 65%|██████▍   | 494/765 [08:22<05:00,  1.11s/it]

[494/765]  raw='pass'  → → 1

 65%|██████▍   | 495/765 [08:22<04:32,  1.01s/it]

[495/765]  raw='fail'  → → 0

 65%|██████▍   | 496/765 [08:23<04:34,  1.02s/it]

[496/765]  raw='fail'  → → 0

 65%|██████▍   | 497/765 [08:25<04:34,  1.02s/it]

[497/765]  raw='pass'  → → 1

 65%|██████▌   | 498/765 [08:26<04:34,  1.03s/it]

[498/765]  raw='pass'  → → 1

 65%|██████▌   | 499/765 [08:27<04:43,  1.07s/it]

[499/765]  raw='pass'  → → 1

 65%|██████▌   | 500/765 [08:28<04:21,  1.01it/s]

[500/765]  raw='fail'  → → 0

 65%|██████▌   | 501/765 [08:28<04:10,  1.06it/s]

[501/765]  raw='fail'  → → 0

 66%|██████▌   | 502/765 [08:29<04:17,  1.02it/s]

[502/765]  raw='pass'  → → 1

 66%|██████▌   | 503/765 [08:31<04:30,  1.03s/it]

[503/765]  raw='pass'  → → 1

 66%|██████▌   | 504/765 [08:32<04:23,  1.01s/it]

[504/765]  raw='fail'  → → 0

 66%|██████▌   | 505/765 [08:32<03:52,  1.12it/s]

[505/765]  raw='fail'  → → 0

 66%|██████▌   | 506/765 [08:33<03:32,  1.22it/s]

[506/765]  raw='fail'  → → 0

 66%|██████▋   | 507/765 [08:34<03:42,  1.16it/s]

[507/765]  raw='fail'  → → 0

 66%|██████▋   | 508/765 [08:35<04:15,  1.01it/s]

[508/765]  raw='pass'  → → 1

 67%|██████▋   | 509/765 [08:36<04:37,  1.08s/it]

[509/765]  raw='pass'  → → 1

 67%|██████▋   | 510/765 [08:37<04:13,  1.00it/s]

[510/765]  raw='fail'  → → 0

 67%|██████▋   | 511/765 [08:39<04:52,  1.15s/it]

[511/765]  raw='pass'  → → 1

 67%|██████▋   | 512/765 [08:40<04:45,  1.13s/it]

[512/765]  raw='pass'  → → 1

 67%|██████▋   | 513/765 [08:41<04:37,  1.10s/it]

[513/765]  raw='fail'  → → 0

 67%|██████▋   | 514/765 [08:42<04:15,  1.02s/it]

[514/765]  raw='pass'  → → 1

 67%|██████▋   | 515/765 [08:43<04:16,  1.03s/it]

[515/765]  raw='fail'  → → 0

 67%|██████▋   | 516/765 [08:44<04:55,  1.19s/it]

[516/765]  raw='pass'  → → 1

 68%|██████▊   | 517/765 [08:45<04:13,  1.02s/it]

[517/765]  raw='fail'  → → 0

 68%|██████▊   | 518/765 [08:46<04:28,  1.09s/it]

[518/765]  raw='pass'  → → 1

 68%|██████▊   | 519/765 [08:47<04:19,  1.05s/it]

[519/765]  raw='fail'  → → 0

 68%|██████▊   | 520/765 [08:48<04:20,  1.06s/it]

[520/765]  raw='pass'  → → 1

 68%|██████▊   | 521/765 [08:50<04:40,  1.15s/it]

[521/765]  raw='pass'  → → 1

 68%|██████▊   | 522/765 [08:50<04:02,  1.00it/s]

[522/765]  raw='fail'  → → 0

 68%|██████▊   | 523/765 [08:51<03:49,  1.05it/s]

[523/765]  raw='fail'  → → 0

 68%|██████▊   | 524/765 [08:52<03:52,  1.04it/s]

[524/765]  raw='fail'  → → 0

 69%|██████▊   | 525/765 [08:54<04:38,  1.16s/it]

[525/765]  raw='pass'  → → 1

 69%|██████▉   | 526/765 [08:54<04:13,  1.06s/it]

[526/765]  raw='fail'  → → 0

 69%|██████▉   | 527/765 [08:55<03:42,  1.07it/s]

[527/765]  raw='fail'  → → 0

 69%|██████▉   | 528/765 [08:56<04:00,  1.01s/it]

[528/765]  raw='pass'  → → 1

 69%|██████▉   | 529/765 [08:57<03:41,  1.06it/s]

[529/765]  raw='fail'  → → 0

 69%|██████▉   | 530/765 [08:58<03:31,  1.11it/s]

[530/765]  raw='fail'  → → 0

 69%|██████▉   | 531/765 [08:58<03:12,  1.21it/s]

[531/765]  raw='fail'  → → 0

 70%|██████▉   | 532/765 [08:59<03:09,  1.23it/s]

[532/765]  raw='fail'  → → 0

 70%|██████▉   | 533/765 [09:00<03:22,  1.15it/s]

[533/765]  raw='pass'  → → 1

 70%|██████▉   | 534/765 [09:02<03:49,  1.00it/s]

[534/765]  raw='pass'  → → 1

 70%|██████▉   | 535/765 [09:03<03:58,  1.04s/it]

[535/765]  raw='pass'  → → 1

 70%|███████   | 536/765 [09:04<03:59,  1.05s/it]

[536/765]  raw='fail'  → → 0

 70%|███████   | 537/765 [09:05<03:43,  1.02it/s]

[537/765]  raw='fail'  → → 0

 70%|███████   | 538/765 [09:05<03:17,  1.15it/s]

[538/765]  raw='fail'  → → 0

 70%|███████   | 539/765 [09:07<04:09,  1.10s/it]

[539/765]  raw='fail'  → → 0

 71%|███████   | 540/765 [09:08<04:06,  1.10s/it]

[540/765]  raw='pass'  → → 1

 71%|███████   | 541/765 [09:09<04:01,  1.08s/it]

[541/765]  raw='pass'  → → 1

 71%|███████   | 542/765 [09:10<04:10,  1.12s/it]

[542/765]  raw='fail'  → → 0

 71%|███████   | 543/765 [09:12<04:25,  1.20s/it]

[543/765]  raw='pass'  → → 1

 71%|███████   | 544/765 [09:13<04:13,  1.15s/it]

[544/765]  raw='fail'  → → 0

 71%|███████   | 545/765 [09:14<04:05,  1.12s/it]

[545/765]  raw='fail'  → → 0

 71%|███████▏  | 546/765 [09:15<03:57,  1.08s/it]

[546/765]  raw='fail'  → → 0

 72%|███████▏  | 547/765 [09:15<03:38,  1.00s/it]

[547/765]  raw='fail'  → → 0

 72%|███████▏  | 548/765 [09:17<04:15,  1.18s/it]

[548/765]  raw='pass'  → → 1

 72%|███████▏  | 549/765 [09:18<04:03,  1.13s/it]

[549/765]  raw='pass'  → → 1

 72%|███████▏  | 550/765 [09:19<03:55,  1.10s/it]

[550/765]  raw='pass'  → → 1

 72%|███████▏  | 551/765 [09:20<03:36,  1.01s/it]

[551/765]  raw='fail'  → → 0

 72%|███████▏  | 552/765 [09:21<03:10,  1.12it/s]

[552/765]  raw='fail'  → → 0

 72%|███████▏  | 553/765 [09:22<03:20,  1.06it/s]

[553/765]  raw='pass'  → → 1

 72%|███████▏  | 554/765 [09:23<03:31,  1.00s/it]

[554/765]  raw='pass'  → → 1

 73%|███████▎  | 555/765 [09:24<03:33,  1.02s/it]

[555/765]  raw='pass'  → → 1

 73%|███████▎  | 556/765 [09:25<03:50,  1.10s/it]

[556/765]  raw='pass'  → → 1

 73%|███████▎  | 557/765 [09:26<04:02,  1.16s/it]

[557/765]  raw='pass'  → → 1

 73%|███████▎  | 558/765 [09:27<03:44,  1.08s/it]

[558/765]  raw='fail'  → → 0

 73%|███████▎  | 559/765 [09:29<03:55,  1.14s/it]

[559/765]  raw='pass'  → → 1

 73%|███████▎  | 560/765 [09:30<03:50,  1.12s/it]

[560/765]  raw='fail'  → → 0

 73%|███████▎  | 561/765 [09:31<04:04,  1.20s/it]

[561/765]  raw='pass'  → → 1

 73%|███████▎  | 562/765 [09:32<03:39,  1.08s/it]

[562/765]  raw='fail'  → → 0

 74%|███████▎  | 563/765 [09:33<03:34,  1.06s/it]

[563/765]  raw='pass'  → → 1

 74%|███████▎  | 564/765 [09:33<03:07,  1.07it/s]

[564/765]  raw='fail'  → → 0

 74%|███████▍  | 565/765 [09:35<03:30,  1.05s/it]

[565/765]  raw='pass'  → → 1

 74%|███████▍  | 566/765 [09:36<03:38,  1.10s/it]

[566/765]  raw='pass'  → → 1

 74%|███████▍  | 567/765 [09:37<03:41,  1.12s/it]

[567/765]  raw='pass'  → → 1

 74%|███████▍  | 568/765 [09:39<03:57,  1.21s/it]

[568/765]  raw='pass'  → → 1

 74%|███████▍  | 569/765 [09:39<03:23,  1.04s/it]

[569/765]  raw='fail'  → → 0

 75%|███████▍  | 570/765 [09:40<03:17,  1.01s/it]

[570/765]  raw='pass'  → → 1

 75%|███████▍  | 571/765 [09:41<03:06,  1.04it/s]

[571/765]  raw='fail'  → → 0

 75%|███████▍  | 572/765 [09:42<03:09,  1.02it/s]

[572/765]  raw='pass'  → → 1

 75%|███████▍  | 573/765 [09:43<03:11,  1.00it/s]

[573/765]  raw='pass'  → → 1

 75%|███████▌  | 574/765 [09:44<03:27,  1.09s/it]

[574/765]  raw='pass'  → → 1

 75%|███████▌  | 575/765 [09:45<03:22,  1.06s/it]

[575/765]  raw='pass'  → → 1

 75%|███████▌  | 576/765 [09:47<03:34,  1.13s/it]

[576/765]  raw='pass'  → → 1

 75%|███████▌  | 577/765 [09:47<03:11,  1.02s/it]

[577/765]  raw='fail'  → → 0

 76%|███████▌  | 578/765 [09:48<02:56,  1.06it/s]

[578/765]  raw='fail'  → → 0

 76%|███████▌  | 579/765 [09:49<02:59,  1.03it/s]

[579/765]  raw='fail'  → → 0

 76%|███████▌  | 580/765 [09:50<03:04,  1.00it/s]

[580/765]  raw='pass'  → → 1

 76%|███████▌  | 581/765 [09:51<02:53,  1.06it/s]

[581/765]  raw='fail'  → → 0

 76%|███████▌  | 582/765 [09:52<02:56,  1.04it/s]

[582/765]  raw='fail'  → → 0

 76%|███████▌  | 583/765 [09:53<02:45,  1.10it/s]

[583/765]  raw='fail'  → → 0

 76%|███████▋  | 584/765 [09:54<03:05,  1.03s/it]

[584/765]  raw='pass'  → → 1

 76%|███████▋  | 585/765 [09:56<03:23,  1.13s/it]

[585/765]  raw='pass'  → → 1

 77%|███████▋  | 586/765 [09:57<03:15,  1.09s/it]

[586/765]  raw='pass'  → → 1

 77%|███████▋  | 587/765 [09:58<03:07,  1.05s/it]

[587/765]  raw='fail'  → → 0

 77%|███████▋  | 588/765 [09:58<02:52,  1.03it/s]

[588/765]  raw='fail'  → → 0

 77%|███████▋  | 589/765 [09:59<02:54,  1.01it/s]

[589/765]  raw='pass'  → → 1

 77%|███████▋  | 590/765 [10:00<02:33,  1.14it/s]

[590/765]  raw='fail'  → → 0

 77%|███████▋  | 591/765 [10:01<02:27,  1.18it/s]

[591/765]  raw='fail'  → → 0

 77%|███████▋  | 592/765 [10:02<02:22,  1.21it/s]

[592/765]  raw='fail'  → → 0

 78%|███████▊  | 593/765 [10:02<02:12,  1.29it/s]

[593/765]  raw='fail'  → → 0

 78%|███████▊  | 594/765 [10:03<02:22,  1.20it/s]

[594/765]  raw='fail'  → → 0

 78%|███████▊  | 595/765 [10:04<02:45,  1.03it/s]

[595/765]  raw='pass'  → → 1

 78%|███████▊  | 596/765 [10:07<03:41,  1.31s/it]

[596/765]  raw='pass'  → → 1

 78%|███████▊  | 597/765 [10:08<03:39,  1.31s/it]

[597/765]  raw='pass'  → → 1

 78%|███████▊  | 598/765 [10:09<03:21,  1.21s/it]

[598/765]  raw='pass'  → → 1

 78%|███████▊  | 599/765 [10:10<03:21,  1.22s/it]

[599/765]  raw='pass'  → → 1

 78%|███████▊  | 600/765 [10:11<02:56,  1.07s/it]

[600/765]  raw='fail'  → → 0

 79%|███████▊  | 601/765 [10:12<02:43,  1.00it/s]

[601/765]  raw='pass'  → → 1

 79%|███████▊  | 602/765 [10:13<02:58,  1.09s/it]

[602/765]  raw='pass'  → → 1

 79%|███████▉  | 603/765 [10:14<03:09,  1.17s/it]

[603/765]  raw='pass'  → → 1

 79%|███████▉  | 604/765 [10:15<03:02,  1.13s/it]

[604/765]  raw='pass'  → → 1

 79%|███████▉  | 605/765 [10:17<03:05,  1.16s/it]

[605/765]  raw='pass'  → → 1

 79%|███████▉  | 606/765 [10:17<02:44,  1.04s/it]

[606/765]  raw='fail'  → → 0

 79%|███████▉  | 607/765 [10:18<02:42,  1.03s/it]

[607/765]  raw='fail'  → → 0

 79%|███████▉  | 608/765 [10:20<03:00,  1.15s/it]

[608/765]  raw='pass'  → → 1

 80%|███████▉  | 609/765 [10:21<02:51,  1.10s/it]

[609/765]  raw='pass'  → → 1

 80%|███████▉  | 610/765 [10:22<02:48,  1.09s/it]

[610/765]  raw='pass'  → → 1

 80%|███████▉  | 611/765 [10:23<02:57,  1.15s/it]

[611/765]  raw='pass'  → → 1

 80%|████████  | 612/765 [10:24<02:48,  1.10s/it]

[612/765]  raw='fail'  → → 0

 80%|████████  | 613/765 [10:25<02:49,  1.11s/it]

[613/765]  raw='pass'  → → 1

 80%|████████  | 614/765 [10:26<02:41,  1.07s/it]

[614/765]  raw='pass'  → → 1

 80%|████████  | 615/765 [10:27<02:20,  1.06it/s]

[615/765]  raw='fail'  → → 0

 81%|████████  | 616/765 [10:28<02:21,  1.05it/s]

[616/765]  raw='fail'  → → 0

 81%|████████  | 617/765 [10:28<02:05,  1.18it/s]

[617/765]  raw='fail'  → → 0

 81%|████████  | 618/765 [10:29<02:03,  1.19it/s]

[618/765]  raw='pass'  → → 1

 81%|████████  | 619/765 [10:30<01:53,  1.28it/s]

[619/765]  raw='fail'  → → 0

 81%|████████  | 620/765 [10:31<02:08,  1.12it/s]

[620/765]  raw='pass'  → → 1

 81%|████████  | 621/765 [10:33<02:41,  1.12s/it]

[621/765]  raw='pass'  → → 1

 81%|████████▏ | 622/765 [10:34<02:51,  1.20s/it]

[622/765]  raw='fail'  → → 0

 81%|████████▏ | 623/765 [10:35<02:44,  1.16s/it]

[623/765]  raw='pass'  → → 1

 82%|████████▏ | 624/765 [10:36<02:43,  1.16s/it]

[624/765]  raw='pass'  → → 1

 82%|████████▏ | 625/765 [10:37<02:20,  1.00s/it]

[625/765]  raw='fail'  → → 0

 82%|████████▏ | 626/765 [10:38<02:03,  1.12it/s]

[626/765]  raw='fail'  → → 0

 82%|████████▏ | 627/765 [10:39<02:08,  1.08it/s]

[627/765]  raw='pass'  → → 1

 82%|████████▏ | 628/765 [10:40<02:22,  1.04s/it]

[628/765]  raw='pass'  → → 1

 82%|████████▏ | 629/765 [10:41<02:20,  1.03s/it]

[629/765]  raw='pass'  → → 1

 82%|████████▏ | 630/765 [10:42<02:38,  1.18s/it]

[630/765]  raw='pass'  → → 1

 82%|████████▏ | 631/765 [10:45<03:24,  1.53s/it]

[631/765]  raw='pass'  → → 1

 83%|████████▎ | 632/765 [10:46<03:02,  1.37s/it]

[632/765]  raw='fail'  → → 0

 83%|████████▎ | 633/765 [10:47<03:06,  1.41s/it]

[633/765]  raw='pass'  → → 1

 83%|████████▎ | 634/765 [10:48<02:54,  1.33s/it]

[634/765]  raw='pass'  → → 1

 83%|████████▎ | 635/765 [10:49<02:43,  1.26s/it]

[635/765]  raw='pass'  → → 1

 83%|████████▎ | 636/765 [10:51<02:43,  1.27s/it]

[636/765]  raw='pass'  → → 1

 83%|████████▎ | 637/765 [10:52<02:43,  1.28s/it]

[637/765]  raw='pass'  → → 1

 83%|████████▎ | 638/765 [10:53<02:32,  1.20s/it]

[638/765]  raw='fail'  → → 0

 84%|████████▎ | 639/765 [10:54<02:16,  1.09s/it]

[639/765]  raw='fail'  → → 0

 84%|████████▎ | 640/765 [10:55<02:11,  1.05s/it]

[640/765]  raw='fail'  → → 0

 84%|████████▍ | 641/765 [10:56<02:03,  1.01it/s]

[641/765]  raw='fail'  → → 0

 84%|████████▍ | 642/765 [10:57<02:28,  1.21s/it]

[642/765]  raw='pass'  → → 1

 84%|████████▍ | 643/765 [10:58<02:12,  1.09s/it]

[643/765]  raw='pass'  → → 1

 84%|████████▍ | 644/765 [10:59<02:01,  1.00s/it]

[644/765]  raw='fail'  → → 0

 84%|████████▍ | 645/765 [11:00<01:45,  1.13it/s]

[645/765]  raw='fail'  → → 0

 84%|████████▍ | 646/765 [11:01<02:07,  1.07s/it]

[646/765]  raw='pass'  → → 1

 85%|████████▍ | 647/765 [11:03<02:24,  1.23s/it]

[647/765]  raw='pass'  → → 1

 85%|████████▍ | 648/765 [11:04<02:21,  1.21s/it]

[648/765]  raw='pass'  → → 1

 85%|████████▍ | 649/765 [11:05<02:07,  1.10s/it]

[649/765]  raw='fail'  → → 0

 85%|████████▍ | 650/765 [11:06<02:09,  1.13s/it]

[650/765]  raw='pass'  → → 1

 85%|████████▌ | 651/765 [11:07<01:57,  1.03s/it]

[651/765]  raw='fail'  → → 0

 85%|████████▌ | 652/765 [11:07<01:43,  1.10it/s]

[652/765]  raw='fail'  → → 0

 85%|████████▌ | 653/765 [11:08<01:48,  1.03it/s]

[653/765]  raw='pass'  → → 1

 85%|████████▌ | 654/765 [11:10<01:50,  1.00it/s]

[654/765]  raw='fail'  → → 0

 86%|████████▌ | 655/765 [11:11<01:50,  1.01s/it]

[655/765]  raw='fail'  → → 0

 86%|████████▌ | 656/765 [11:11<01:42,  1.07it/s]

[656/765]  raw='fail'  → → 0

 86%|████████▌ | 657/765 [11:12<01:42,  1.05it/s]

[657/765]  raw='fail'  → → 0

 86%|████████▌ | 658/765 [11:13<01:32,  1.16it/s]

[658/765]  raw='fail'  → → 0

 86%|████████▌ | 659/765 [11:14<01:23,  1.27it/s]

[659/765]  raw='fail'  → → 0

 86%|████████▋ | 660/765 [11:14<01:23,  1.26it/s]

[660/765]  raw='fail'  → → 0

 86%|████████▋ | 661/765 [11:16<01:49,  1.05s/it]

[661/765]  raw='pass'  → → 1

 87%|████████▋ | 662/765 [11:17<01:56,  1.13s/it]

[662/765]  raw='pass'  → → 1

 87%|████████▋ | 663/765 [11:18<01:45,  1.03s/it]

[663/765]  raw='fail'  → → 0

 87%|████████▋ | 664/765 [11:19<01:47,  1.06s/it]

[664/765]  raw='pass'  → → 1

 87%|████████▋ | 665/765 [11:20<01:37,  1.02it/s]

[665/765]  raw='fail'  → → 0

 87%|████████▋ | 666/765 [11:21<01:47,  1.09s/it]

[666/765]  raw='pass'  → → 1

 87%|████████▋ | 667/765 [11:22<01:32,  1.06it/s]

[667/765]  raw='fail'  → → 0

 87%|████████▋ | 668/765 [11:23<01:35,  1.02it/s]

[668/765]  raw='pass'  → → 1

 87%|████████▋ | 669/765 [11:24<01:43,  1.07s/it]

[669/765]  raw='pass'  → → 1

 88%|████████▊ | 670/765 [11:26<01:46,  1.12s/it]

[670/765]  raw='pass'  → → 1

 88%|████████▊ | 671/765 [11:27<02:00,  1.28s/it]

[671/765]  raw='pass'  → → 1

 88%|████████▊ | 672/765 [11:29<01:59,  1.28s/it]

[672/765]  raw='pass'  → → 1

 88%|████████▊ | 673/765 [11:29<01:42,  1.12s/it]

[673/765]  raw='fail'  → → 0

 88%|████████▊ | 674/765 [11:31<01:52,  1.24s/it]

[674/765]  raw='pass'  → → 1

 88%|████████▊ | 675/765 [11:32<01:39,  1.11s/it]

[675/765]  raw='fail'  → → 0

 88%|████████▊ | 676/765 [11:33<01:39,  1.12s/it]

[676/765]  raw='fail'  → → 0

 88%|████████▊ | 677/765 [11:34<01:35,  1.08s/it]

[677/765]  raw='pass'  → → 1

 89%|████████▊ | 678/765 [11:34<01:22,  1.05it/s]

[678/765]  raw='fail'  → → 0

 89%|████████▉ | 679/765 [11:36<01:29,  1.04s/it]

[679/765]  raw='pass'  → → 1

 89%|████████▉ | 680/765 [11:37<01:32,  1.09s/it]

[680/765]  raw='pass'  → → 1

 89%|████████▉ | 681/765 [11:38<01:35,  1.13s/it]

[681/765]  raw='pass'  → → 1

 89%|████████▉ | 682/765 [11:39<01:38,  1.18s/it]

[682/765]  raw='pass'  → → 1

 89%|████████▉ | 683/765 [11:40<01:32,  1.13s/it]

[683/765]  raw='pass'  → → 1

 89%|████████▉ | 684/765 [11:41<01:29,  1.10s/it]

[684/765]  raw='pass'  → → 1

 90%|████████▉ | 685/765 [11:43<01:27,  1.09s/it]

[685/765]  raw='pass'  → → 1

 90%|████████▉ | 686/765 [11:43<01:22,  1.05s/it]

[686/765]  raw='fail'  → → 0

 90%|████████▉ | 687/765 [11:45<01:25,  1.09s/it]

[687/765]  raw='pass'  → → 1

 90%|████████▉ | 688/765 [11:46<01:21,  1.06s/it]

[688/765]  raw='fail'  → → 0

 90%|█████████ | 689/765 [11:47<01:26,  1.14s/it]

[689/765]  raw='pass'  → → 1

 90%|█████████ | 690/765 [11:48<01:21,  1.09s/it]

[690/765]  raw='pass'  → → 1

 90%|█████████ | 691/765 [11:49<01:13,  1.00it/s]

[691/765]  raw='fail'  → → 0

 90%|█████████ | 692/765 [11:50<01:08,  1.06it/s]

[692/765]  raw='fail'  → → 0

 91%|█████████ | 693/765 [11:51<01:23,  1.16s/it]

[693/765]  raw='pass'  → → 1

 91%|█████████ | 694/765 [11:52<01:14,  1.04s/it]

[694/765]  raw='fail'  → → 0

 91%|█████████ | 695/765 [11:53<01:12,  1.03s/it]

[695/765]  raw='fail'  → → 0

 91%|█████████ | 696/765 [11:54<01:06,  1.04it/s]

[696/765]  raw='fail'  → → 0

 91%|█████████ | 697/765 [11:55<01:10,  1.04s/it]

[697/765]  raw='pass'  → → 1

 91%|█████████ | 698/765 [11:56<01:04,  1.05it/s]

[698/765]  raw='fail'  → → 0

 91%|█████████▏| 699/765 [11:57<01:00,  1.09it/s]

[699/765]  raw='fail'  → → 0

 92%|█████████▏| 700/765 [11:57<00:56,  1.15it/s]

[700/765]  raw='fail'  → → 0

 92%|█████████▏| 701/765 [11:58<00:55,  1.16it/s]

[701/765]  raw='fail'  → → 0

 92%|█████████▏| 702/765 [11:59<00:49,  1.27it/s]

[702/765]  raw='fail'  → → 0

 92%|█████████▏| 703/765 [12:00<00:49,  1.25it/s]

[703/765]  raw='pass'  → → 1

 92%|█████████▏| 704/765 [12:00<00:49,  1.24it/s]

[704/765]  raw='pass'  → → 1

 92%|█████████▏| 705/765 [12:01<00:48,  1.24it/s]

[705/765]  raw='fail'  → → 0

 92%|█████████▏| 706/765 [12:02<00:44,  1.34it/s]

[706/765]  raw='fail'  → → 0

 92%|█████████▏| 707/765 [12:04<00:58,  1.01s/it]

[707/765]  raw='pass'  → → 1

 93%|█████████▎| 708/765 [12:05<00:57,  1.01s/it]

[708/765]  raw='fail'  → → 0

 93%|█████████▎| 709/765 [12:05<00:53,  1.05it/s]

[709/765]  raw='fail'  → → 0

 93%|█████████▎| 710/765 [12:06<00:53,  1.02it/s]

[710/765]  raw='pass'  → → 1

 93%|█████████▎| 711/765 [12:07<00:48,  1.11it/s]

[711/765]  raw='fail'  → → 0

 93%|█████████▎| 712/765 [12:08<00:51,  1.03it/s]

[712/765]  raw='pass'  → → 1

 93%|█████████▎| 713/765 [12:10<00:56,  1.08s/it]

[713/765]  raw='pass'  → → 1

 93%|█████████▎| 714/765 [12:10<00:51,  1.00s/it]

[714/765]  raw='pass'  → → 1

 93%|█████████▎| 715/765 [12:11<00:44,  1.13it/s]

[715/765]  raw='fail'  → → 0

 94%|█████████▎| 716/765 [12:12<00:41,  1.18it/s]

[716/765]  raw='fail'  → → 0

 94%|█████████▎| 717/765 [12:13<00:43,  1.11it/s]

[717/765]  raw='pass'  → → 1

 94%|█████████▍| 718/765 [12:14<00:41,  1.14it/s]

[718/765]  raw='fail'  → → 0

 94%|█████████▍| 719/765 [12:15<00:41,  1.11it/s]

[719/765]  raw='fail'  → → 0

 94%|█████████▍| 720/765 [12:16<00:41,  1.09it/s]

[720/765]  raw='fail'  → → 0

 94%|█████████▍| 721/765 [12:17<00:43,  1.02it/s]

[721/765]  raw='pass'  → → 1

 94%|█████████▍| 722/765 [12:18<00:45,  1.06s/it]

[722/765]  raw='pass'  → → 1

 95%|█████████▍| 723/765 [12:19<00:39,  1.07it/s]

[723/765]  raw='fail'  → → 0

 95%|█████████▍| 724/765 [12:19<00:34,  1.19it/s]

[724/765]  raw='fail'  → → 0

 95%|█████████▍| 725/765 [12:20<00:31,  1.29it/s]

[725/765]  raw='fail'  → → 0

 95%|█████████▍| 726/765 [12:21<00:33,  1.17it/s]

[726/765]  raw='pass'  → → 1

 95%|█████████▌| 727/765 [12:22<00:33,  1.12it/s]

[727/765]  raw='fail'  → → 0

 95%|█████████▌| 728/765 [12:23<00:32,  1.15it/s]

[728/765]  raw='fail'  → → 0

 95%|█████████▌| 729/765 [12:24<00:34,  1.05it/s]

[729/765]  raw='pass'  → → 1

 95%|█████████▌| 730/765 [12:24<00:29,  1.17it/s]

[730/765]  raw='fail'  → → 0

 96%|█████████▌| 731/765 [12:25<00:28,  1.20it/s]

[731/765]  raw='fail'  → → 0

 96%|█████████▌| 732/765 [12:27<00:34,  1.04s/it]

[732/765]  raw='pass'  → → 1

 96%|█████████▌| 733/765 [12:27<00:29,  1.08it/s]

[733/765]  raw='fail'  → → 0

 96%|█████████▌| 734/765 [12:28<00:29,  1.04it/s]

[734/765]  raw='pass'  → → 1

 96%|█████████▌| 735/765 [12:29<00:25,  1.16it/s]

[735/765]  raw='fail'  → → 0

 96%|█████████▌| 736/765 [12:30<00:26,  1.10it/s]

[736/765]  raw='fail'  → → 0

 96%|█████████▋| 737/765 [12:31<00:26,  1.05it/s]

[737/765]  raw='fail'  → → 0

 96%|█████████▋| 738/765 [12:32<00:25,  1.04it/s]

[738/765]  raw='pass'  → → 1

 97%|█████████▋| 739/765 [12:33<00:22,  1.16it/s]

[739/765]  raw='fail'  → → 0

 97%|█████████▋| 740/765 [12:33<00:20,  1.19it/s]

[740/765]  raw='fail'  → → 0

 97%|█████████▋| 741/765 [12:34<00:21,  1.14it/s]

[741/765]  raw='fail'  → → 0

 97%|█████████▋| 742/765 [12:35<00:20,  1.10it/s]

[742/765]  raw='pass'  → → 1

 97%|█████████▋| 743/765 [12:36<00:20,  1.06it/s]

[743/765]  raw='fail'  → → 0

 97%|█████████▋| 744/765 [12:38<00:21,  1.03s/it]

[744/765]  raw='pass'  → → 1

 97%|█████████▋| 745/765 [12:38<00:18,  1.10it/s]

[745/765]  raw='fail'  → → 0

 98%|█████████▊| 746/765 [12:40<00:18,  1.00it/s]

[746/765]  raw='pass'  → → 1

 98%|█████████▊| 747/765 [12:41<00:18,  1.02s/it]

[747/765]  raw='fail'  → → 0

 98%|█████████▊| 748/765 [12:42<00:17,  1.05s/it]

[748/765]  raw='fail'  → → 0

 98%|█████████▊| 749/765 [12:43<00:15,  1.02it/s]

[749/765]  raw='fail'  → → 0

 98%|█████████▊| 750/765 [12:43<00:13,  1.08it/s]

[750/765]  raw='fail'  → → 0

 98%|█████████▊| 751/765 [12:44<00:12,  1.11it/s]

[751/765]  raw='pass'  → → 1

 98%|█████████▊| 752/765 [12:46<00:13,  1.06s/it]

[752/765]  raw='pass'  → → 1

 98%|█████████▊| 753/765 [12:46<00:11,  1.08it/s]

[753/765]  raw='fail'  → → 0

 99%|█████████▊| 754/765 [12:47<00:10,  1.06it/s]

[754/765]  raw='fail'  → → 0

 99%|█████████▊| 755/765 [12:49<00:10,  1.05s/it]

[755/765]  raw='pass'  → → 1

 99%|█████████▉| 756/765 [12:50<00:10,  1.13s/it]

[756/765]  raw='pass'  → → 1

 99%|█████████▉| 757/765 [12:51<00:09,  1.13s/it]

[757/765]  raw='pass'  → → 1

 99%|█████████▉| 758/765 [12:52<00:07,  1.10s/it]

[758/765]  raw='pass'  → → 1

 99%|█████████▉| 759/765 [12:53<00:07,  1.18s/it]

[759/765]  raw='pass'  → → 1

 99%|█████████▉| 760/765 [12:54<00:05,  1.14s/it]

[760/765]  raw='pass'  → → 1

 99%|█████████▉| 761/765 [12:56<00:04,  1.15s/it]

[761/765]  raw='pass'  → → 1

100%|█████████▉| 762/765 [12:57<00:03,  1.09s/it]

[762/765]  raw='fail'  → → 0

100%|█████████▉| 763/765 [12:58<00:02,  1.19s/it]

[763/765]  raw='pass'  → → 1

100%|█████████▉| 764/765 [12:59<00:01,  1.16s/it]

[764/765]  raw='pass'  → → 1

100%|██████████| 765/765 [13:00<00:00,  1.02s/it]

[765/765]  raw='fail'  → → 0

In [ ]:
if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

In [ ]:
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.head(20).to_string())                                # sample, not all 765

# save the full table — do this NOW so the run is never lost
results_df.to_csv("phi3_finetuned_test_results.csv", index=False)

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}   (zero-shot baseline was 0.5800)")
    print("\nClassification Report:")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")
    print(f"\nPredicted-Pass fraction: {(pd.Series(y_pred_valid)==1).mean():.3f}   (true rate: {(pd.Series(y_true_valid)==1).mean():.3f})")
else:
    print("No valid predictions to evaluate.")

    y_true  y_pred generated y_true_label y_pred_label
0        0       0      fail         Fail         Fail
1        0       0      fail         Fail         Fail
2        0       0      fail         Fail         Fail
3        1       1      pass         Pass         Pass
4        0       0      fail         Fail         Fail
5        0       0      fail         Fail         Fail
6        1       1      pass         Pass         Pass
7        1       0      fail         Pass         Fail
8        1       1      pass         Pass         Pass
9        0       0      fail         Fail         Fail
10       0       0      fail         Fail         Fail
11       1       1      pass         Pass         Pass
12       1       1      pass         Pass         Pass
13       1       1      pass         Pass         Pass
14       1       1      pass         Pass         Pass
15       1       1      pass         Pass         Pass
16       1       1      pass         Pass         Pass
17       1       1      pass         Pass         Pass
18       0       0      fail         Fail         Fail
19       0       1      pass         Fail         Pass

Parsed      : 765/765
Unparseable : 0

Accuracy : 0.8627   (zero-shot baseline was 0.5800)

Classification Report:
              precision    recall  f1-score   support

        Fail       0.94      0.81      0.87       442
        Pass       0.79      0.93      0.85       323

    accuracy                           0.86       765
   macro avg       0.86      0.87      0.86       765
weighted avg       0.87      0.86      0.86       765

Confusion Matrix (rows=true, cols=pred):
           Fail  Pass
True Fail : [360  82]
True Pass : [ 23 300]

Predicted-Pass fraction: 0.499   (true rate: 0.422)

##### Retesting

In [ ]:
# Step 1: reload full 25k dataset
import kagglehub
import pandas as pd
import os

path   = kagglehub.dataset_download("nbroad/persaude-corpus-2")
scores = pd.read_csv(os.path.join(path, "persuade_2.0_human_scores_demo_id_github.csv"))

PASS_THRESHOLD       = 4
scores["binary_score"] = (scores["holistic_essay_score"] >= PASS_THRESHOLD).astype(int)

print(f"Full dataset     : {len(scores):,}")
print(f"Class distribution:\n{scores['binary_score'].value_counts()}")

Using Colab cache for faster access to the 'persaude-corpus-2' dataset.
Full dataset     : 25,996
Class distribution:
binary_score
0    15095
1    10901
Name: count, dtype: int64

In [ ]:
scores

,essay_id_comp,full_text,holistic_essay_score,word_count,prompt_name,task,assignment,source_text,gender,grade_level,ell_status,race_ethnicity,economically_disadvantaged,student_disability_status,binary_score
0,423A1CA112E2,Phones\n\nModern humans today are always on th...,3,378,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN,0
1,BC75783F96E3,This essay will explain if drivers should or s...,4,432,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN,1
2,74C8BC7417DE,Driving while the use of cellular devices\n\nT...,2,179,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,F,NaN,NaN,White,NaN,NaN,0
3,A8445CABFECE,Phones & Driving\n\nDrivers should not be able...,3,221,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,Black/African American,NaN,NaN,0
4,6B4F7A0165B9,Cell Phone Operation While Driving\n\nThe abil...,4,334,Phones and driving,Independent,Today the majority of humans own and operate c...,NaN,M,NaN,NaN,White,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25991,18409261F5C2,80% of Americans believe seeking multiple opin...,5,1050,Seeking multiple opinions,Independent,"When people ask for advice, they sometimes tal...",NaN,M,8.0,No,Asian/Pacific Islander,Economically disadvantaged,Not identified as having disability,1
25992,D46BCB48440A,"When people ask for advice,they sometimes talk...",4,373,Seeking multiple opinions,Independent,"When people ask for advice, they sometimes tal...",NaN,F,8.0,No,Black/African American,Economically disadvantaged,Not identified as having disability,1
25993,0FB0700DAF44,"During a group project, have you ever asked a ...",4,631,Seeking multiple opinions,Independent,"When people ask for advice, they sometimes tal...",NaN,M,8.0,No,Asian/Pacific Islander,Not economically disadvantaged,Not identified as having disability,1
25994,D72CB1C11673,Making choices in life can be very difficult. ...,4,417,Seeking multiple opinions,Independent,"When people ask for advice, they sometimes tal...",NaN,F,8.0,No,Black/African American,Economically disadvantaged,Not identified as having disability,1
25995,DF920E0A7337,Have you ever asked more than one person for h...,4,706,Seeking multiple opinions,Independent,"When people ask for advice, they sometimes tal...",NaN,M,8.0,No,White,Not economically disadvantaged,Not identified as having disability,1

In [ ]:
# Step 2: exclude essays already used in original 5k sample
used_ids = set(sample["essay_id_comp"])   # sample = your original 5k pull

fresh = scores[~scores["essay_id_comp"].isin(used_ids)].reset_index(drop=True)

print(f"Already used     : {len(used_ids):,}")
print(f"Fresh essays left: {len(fresh):,}")
print(f"Class distribution:\n{fresh['binary_score'].value_counts()}")

Already used     : 5,100
Fresh essays left: 20,896
Class distribution:
binary_score
0    12145
1     8751
Name: count, dtype: int64

In [ ]:
#  Step 3: sample 500 fresh essays stratified by binary_score
from sklearn.model_selection import train_test_split

fresh_test, _ = train_test_split(
    fresh,
    train_size=500,
    random_state=99,               # different seed from original splits
    stratify=fresh["binary_score"]
)
fresh_test = fresh_test.reset_index(drop=True)

print(f"Fresh test size  : {len(fresh_test)}")
print(f"Class distribution:\n{fresh_test['binary_score'].value_counts()}")

Fresh test size  : 500
Class distribution:
binary_score
0    291
1    209
Name: count, dtype: int64

In [ ]:
# Step 4: build prompts
X_fresh_prompts = pd.DataFrame(
    fresh_test.apply(generate_phi2_test_prompt, axis=1), columns=["text"]
)
y_fresh_true = fresh_test["binary_score"].values

print(f"Prompts ready    : {len(X_fresh_prompts)}")
print(f"Last 50 chars    : {repr(X_fresh_prompts['text'].iloc[0][-50:])}")
# should end with '\nOutput:'

Prompts ready    : 500
Last 50 chars    : 'hen someone learns from other people, they\nOutput:'

In [ ]:
# ── Step 5: predict ───────────────────────────────────────────────────────────
y_fresh_pred, y_fresh_generated = predict_phi2(
    X_fresh_prompts, ft_model, tokenizer
)

  0%|          | 0/500 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
  0%|          | 1/500 [00:00<02:20,  3.54it/s]

[  1/500]  raw='pass'  →  Pass

  0%|          | 2/500 [00:00<02:19,  3.58it/s]

[  2/500]  raw='fail'  →  Fail

  1%|          | 3/500 [00:00<02:20,  3.54it/s]

[  3/500]  raw='pass'  →  Pass

  1%|          | 4/500 [00:01<02:21,  3.51it/s]

[  4/500]  raw='pass'  →  Pass

  1%|          | 5/500 [00:01<02:30,  3.28it/s]

[  5/500]  raw='pass'  →  Pass

  1%|          | 6/500 [00:01<02:27,  3.35it/s]

[  6/500]  raw='fail'  →  Fail

  1%|▏         | 7/500 [00:02<02:23,  3.43it/s]

[  7/500]  raw='fail'  →  Fail

  2%|▏         | 8/500 [00:02<02:21,  3.49it/s]

[  8/500]  raw='pass'  →  Pass

  2%|▏         | 9/500 [00:02<02:19,  3.53it/s]

[  9/500]  raw='fail'  →  Fail

  2%|▏         | 10/500 [00:02<02:17,  3.55it/s]

[ 10/500]  raw='pass'  →  Pass

  2%|▏         | 11/500 [00:03<02:17,  3.55it/s]

[ 11/500]  raw='fail'  →  Fail

  2%|▏         | 12/500 [00:03<02:17,  3.54it/s]

[ 12/500]  raw='pass'  →  Pass

  3%|▎         | 13/500 [00:03<02:17,  3.55it/s]

[ 13/500]  raw='fail'  →  Fail

  3%|▎         | 14/500 [00:03<02:16,  3.57it/s]

[ 14/500]  raw='pass'  →  Pass

  3%|▎         | 15/500 [00:04<02:15,  3.57it/s]

[ 15/500]  raw='fail'  →  Fail

  3%|▎         | 16/500 [00:04<02:15,  3.58it/s]

[ 16/500]  raw='fail'  →  Fail

  3%|▎         | 17/500 [00:04<02:15,  3.57it/s]

[ 17/500]  raw='fail'  →  Fail

  4%|▎         | 18/500 [00:05<02:15,  3.56it/s]

[ 18/500]  raw='fail'  →  Fail

  4%|▍         | 19/500 [00:05<02:14,  3.58it/s]

[ 19/500]  raw='fail'  →  Fail

  4%|▍         | 20/500 [00:05<02:13,  3.59it/s]

[ 20/500]  raw='fail'  →  Fail

  4%|▍         | 21/500 [00:05<02:13,  3.60it/s]

[ 21/500]  raw='fail'  →  Fail

  4%|▍         | 22/500 [00:06<02:12,  3.60it/s]

[ 22/500]  raw='fail'  →  Fail

  5%|▍         | 23/500 [00:06<02:11,  3.62it/s]

[ 23/500]  raw='fail'  →  Fail

  5%|▍         | 24/500 [00:06<02:11,  3.63it/s]

[ 24/500]  raw='fail'  →  Fail

  5%|▌         | 25/500 [00:07<02:10,  3.63it/s]

[ 25/500]  raw='pass'  →  Pass

  5%|▌         | 26/500 [00:07<02:10,  3.64it/s]

[ 26/500]  raw='fail'  →  Fail

  5%|▌         | 27/500 [00:07<02:10,  3.64it/s]

[ 27/500]  raw='pass'  →  Pass

  6%|▌         | 28/500 [00:07<02:09,  3.63it/s]

[ 28/500]  raw='pass'  →  Pass

  6%|▌         | 29/500 [00:08<02:09,  3.64it/s]

[ 29/500]  raw='fail'  →  Fail

  6%|▌         | 30/500 [00:08<02:09,  3.63it/s]

[ 30/500]  raw='pass'  →  Pass

  6%|▌         | 31/500 [00:08<02:09,  3.62it/s]

[ 31/500]  raw='fail'  →  Fail

  6%|▋         | 32/500 [00:08<02:08,  3.63it/s]

[ 32/500]  raw='pass'  →  Pass

  7%|▋         | 33/500 [00:09<02:08,  3.64it/s]

[ 33/500]  raw='fail'  →  Fail

  7%|▋         | 34/500 [00:09<02:08,  3.63it/s]

[ 34/500]  raw='pass'  →  Pass

  7%|▋         | 35/500 [00:09<02:08,  3.63it/s]

[ 35/500]  raw='pass'  →  Pass

  7%|▋         | 36/500 [00:10<02:07,  3.63it/s]

[ 36/500]  raw='fail'  →  Fail

  7%|▋         | 37/500 [00:10<02:07,  3.64it/s]

[ 37/500]  raw='pass'  →  Pass

  8%|▊         | 38/500 [00:10<02:07,  3.63it/s]

[ 38/500]  raw='fail'  →  Fail

  8%|▊         | 39/500 [00:10<02:06,  3.64it/s]

[ 39/500]  raw='fail'  →  Fail

  8%|▊         | 40/500 [00:11<02:06,  3.63it/s]

[ 40/500]  raw='pass'  →  Pass

  8%|▊         | 41/500 [00:11<02:06,  3.63it/s]

[ 41/500]  raw='pass'  →  Pass

  8%|▊         | 42/500 [00:11<02:06,  3.63it/s]

[ 42/500]  raw='pass'  →  Pass

  9%|▊         | 43/500 [00:11<02:05,  3.63it/s]

[ 43/500]  raw='pass'  →  Pass

  9%|▉         | 44/500 [00:12<02:05,  3.63it/s]

[ 44/500]  raw='fail'  →  Fail

  9%|▉         | 45/500 [00:12<02:05,  3.63it/s]

[ 45/500]  raw='pass'  →  Pass

  9%|▉         | 46/500 [00:12<02:04,  3.64it/s]

[ 46/500]  raw='fail'  →  Fail

  9%|▉         | 47/500 [00:13<02:04,  3.65it/s]

[ 47/500]  raw='fail'  →  Fail

 10%|▉         | 48/500 [00:13<02:03,  3.65it/s]

[ 48/500]  raw='fail'  →  Fail

 10%|▉         | 49/500 [00:13<02:04,  3.63it/s]

[ 49/500]  raw='fail'  →  Fail

 10%|█         | 50/500 [00:13<02:03,  3.63it/s]

[ 50/500]  raw='pass'  →  Pass

 10%|█         | 51/500 [00:14<02:03,  3.63it/s]

[ 51/500]  raw='fail'  →  Fail

 10%|█         | 52/500 [00:14<02:03,  3.64it/s]

[ 52/500]  raw='fail'  →  Fail

 11%|█         | 53/500 [00:14<02:02,  3.64it/s]

[ 53/500]  raw='fail'  →  Fail

 11%|█         | 54/500 [00:15<02:02,  3.64it/s]

[ 54/500]  raw='fail'  →  Fail

 11%|█         | 55/500 [00:15<02:02,  3.64it/s]

[ 55/500]  raw='pass'  →  Pass

 11%|█         | 56/500 [00:15<02:01,  3.64it/s]

[ 56/500]  raw='fail'  →  Fail

 11%|█▏        | 57/500 [00:15<02:01,  3.64it/s]

[ 57/500]  raw='fail'  →  Fail

 12%|█▏        | 58/500 [00:16<02:01,  3.64it/s]

[ 58/500]  raw='pass'  →  Pass

 12%|█▏        | 59/500 [00:16<02:00,  3.65it/s]

[ 59/500]  raw='fail'  →  Fail

 12%|█▏        | 60/500 [00:16<02:01,  3.64it/s]

[ 60/500]  raw='pass'  →  Pass

 12%|█▏        | 61/500 [00:16<02:00,  3.64it/s]

[ 61/500]  raw='pass'  →  Pass

 12%|█▏        | 62/500 [00:17<02:00,  3.64it/s]

[ 62/500]  raw='pass'  →  Pass

 13%|█▎        | 63/500 [00:17<01:59,  3.64it/s]

[ 63/500]  raw='fail'  →  Fail

 13%|█▎        | 64/500 [00:17<01:59,  3.64it/s]

[ 64/500]  raw='pass'  →  Pass

 13%|█▎        | 65/500 [00:18<01:59,  3.64it/s]

[ 65/500]  raw='fail'  →  Fail

 13%|█▎        | 66/500 [00:18<01:59,  3.64it/s]

[ 66/500]  raw='fail'  →  Fail

 13%|█▎        | 67/500 [00:18<01:58,  3.64it/s]

[ 67/500]  raw='pass'  →  Pass

 14%|█▎        | 68/500 [00:18<01:58,  3.64it/s]

[ 68/500]  raw='fail'  →  Fail

 14%|█▍        | 69/500 [00:19<01:58,  3.64it/s]

[ 69/500]  raw='pass'  →  Pass

 14%|█▍        | 70/500 [00:19<01:58,  3.62it/s]

[ 70/500]  raw='pass'  →  Pass

 14%|█▍        | 71/500 [00:19<01:58,  3.62it/s]

[ 71/500]  raw='fail'  →  Fail

 14%|█▍        | 72/500 [00:19<01:59,  3.59it/s]

[ 72/500]  raw='fail'  →  Fail

 15%|█▍        | 73/500 [00:20<01:59,  3.56it/s]

[ 73/500]  raw='fail'  →  Fail

 15%|█▍        | 74/500 [00:20<01:58,  3.59it/s]

[ 74/500]  raw='fail'  →  Fail

 15%|█▌        | 75/500 [00:20<01:58,  3.60it/s]

[ 75/500]  raw='fail'  →  Fail

 15%|█▌        | 76/500 [00:21<01:57,  3.59it/s]

[ 76/500]  raw='fail'  →  Fail

 15%|█▌        | 77/500 [00:21<01:58,  3.56it/s]

[ 77/500]  raw='pass'  →  Pass

 16%|█▌        | 78/500 [00:21<01:58,  3.55it/s]

[ 78/500]  raw='fail'  →  Fail

 16%|█▌        | 79/500 [00:21<01:58,  3.54it/s]

[ 79/500]  raw='pass'  →  Pass

 16%|█▌        | 80/500 [00:22<01:58,  3.54it/s]

[ 80/500]  raw='pass'  →  Pass

 16%|█▌        | 81/500 [00:22<01:58,  3.54it/s]

[ 81/500]  raw='pass'  →  Pass

 16%|█▋        | 82/500 [00:22<01:58,  3.54it/s]

[ 82/500]  raw='fail'  →  Fail

 17%|█▋        | 83/500 [00:23<01:57,  3.54it/s]

[ 83/500]  raw='fail'  →  Fail

 17%|█▋        | 84/500 [00:23<01:57,  3.54it/s]

[ 84/500]  raw='pass'  →  Pass

 17%|█▋        | 85/500 [00:23<01:57,  3.54it/s]

[ 85/500]  raw='pass'  →  Pass

 17%|█▋        | 86/500 [00:23<01:56,  3.54it/s]

[ 86/500]  raw='pass'  →  Pass

 17%|█▋        | 87/500 [00:24<01:56,  3.55it/s]

[ 87/500]  raw='fail'  →  Fail

 18%|█▊        | 88/500 [00:24<01:56,  3.55it/s]

[ 88/500]  raw='fail'  →  Fail

 18%|█▊        | 89/500 [00:24<01:55,  3.56it/s]

[ 89/500]  raw='fail'  →  Fail

 18%|█▊        | 90/500 [00:25<01:54,  3.57it/s]

[ 90/500]  raw='pass'  →  Pass

 18%|█▊        | 91/500 [00:25<01:54,  3.58it/s]

[ 91/500]  raw='pass'  →  Pass

 18%|█▊        | 92/500 [00:25<01:53,  3.60it/s]

[ 92/500]  raw='fail'  →  Fail

 19%|█▊        | 93/500 [00:25<01:52,  3.60it/s]

[ 93/500]  raw='pass'  →  Pass

 19%|█▉        | 94/500 [00:26<01:52,  3.60it/s]

[ 94/500]  raw='pass'  →  Pass

 19%|█▉        | 95/500 [00:26<01:52,  3.60it/s]

[ 95/500]  raw='fail'  →  Fail

 19%|█▉        | 96/500 [00:26<01:51,  3.61it/s]

[ 96/500]  raw='pass'  →  Pass

 19%|█▉        | 97/500 [00:26<01:51,  3.62it/s]

[ 97/500]  raw='fail'  →  Fail

 20%|█▉        | 98/500 [00:27<01:51,  3.61it/s]

[ 98/500]  raw='pass'  →  Pass

 20%|█▉        | 99/500 [00:27<01:50,  3.62it/s]

[ 99/500]  raw='pass'  →  Pass

 20%|██        | 100/500 [00:27<01:50,  3.62it/s]

[100/500]  raw='fail'  →  Fail

 20%|██        | 101/500 [00:28<01:50,  3.62it/s]

[101/500]  raw='pass'  →  Pass

 20%|██        | 102/500 [00:28<01:50,  3.62it/s]

[102/500]  raw='fail'  →  Fail

 21%|██        | 103/500 [00:28<01:49,  3.62it/s]

[103/500]  raw='fail'  →  Fail

 21%|██        | 104/500 [00:28<01:49,  3.63it/s]

[104/500]  raw='pass'  →  Pass

 21%|██        | 105/500 [00:29<01:48,  3.63it/s]

[105/500]  raw='pass'  →  Pass

 21%|██        | 106/500 [00:29<01:48,  3.63it/s]

[106/500]  raw='pass'  →  Pass

 21%|██▏       | 107/500 [00:29<01:48,  3.62it/s]

[107/500]  raw='fail'  →  Fail

 22%|██▏       | 108/500 [00:30<01:48,  3.61it/s]

[108/500]  raw='fail'  →  Fail

 22%|██▏       | 109/500 [00:30<01:48,  3.61it/s]

[109/500]  raw='fail'  →  Fail

 22%|██▏       | 110/500 [00:30<01:48,  3.59it/s]

[110/500]  raw='pass'  →  Pass

 22%|██▏       | 111/500 [00:30<01:48,  3.58it/s]

[111/500]  raw='pass'  →  Pass

 22%|██▏       | 112/500 [00:31<01:48,  3.58it/s]

[112/500]  raw='pass'  →  Pass

 23%|██▎       | 113/500 [00:31<01:47,  3.61it/s]

[113/500]  raw='pass'  →  Pass

 23%|██▎       | 114/500 [00:31<01:46,  3.63it/s]

[114/500]  raw='pass'  →  Pass

 23%|██▎       | 115/500 [00:31<01:45,  3.64it/s]

[115/500]  raw='fail'  →  Fail

 23%|██▎       | 116/500 [00:32<01:45,  3.62it/s]

[116/500]  raw='pass'  →  Pass

 23%|██▎       | 117/500 [00:32<01:45,  3.61it/s]

[117/500]  raw='fail'  →  Fail

 24%|██▎       | 118/500 [00:32<01:45,  3.60it/s]

[118/500]  raw='fail'  →  Fail

 24%|██▍       | 119/500 [00:33<01:45,  3.60it/s]

[119/500]  raw='fail'  →  Fail

 24%|██▍       | 120/500 [00:33<01:46,  3.58it/s]

[120/500]  raw='pass'  →  Pass

 24%|██▍       | 121/500 [00:33<01:45,  3.58it/s]

[121/500]  raw='fail'  →  Fail

 24%|██▍       | 122/500 [00:33<01:45,  3.57it/s]

[122/500]  raw='fail'  →  Fail

 25%|██▍       | 123/500 [00:34<01:45,  3.57it/s]

[123/500]  raw='pass'  →  Pass

 25%|██▍       | 124/500 [00:34<01:45,  3.56it/s]

[124/500]  raw='fail'  →  Fail

 25%|██▌       | 125/500 [00:34<01:45,  3.56it/s]

[125/500]  raw='fail'  →  Fail

 25%|██▌       | 126/500 [00:35<01:45,  3.56it/s]

[126/500]  raw='pass'  →  Pass

 25%|██▌       | 127/500 [00:35<01:44,  3.57it/s]

[127/500]  raw='pass'  →  Pass

 26%|██▌       | 128/500 [00:35<01:43,  3.59it/s]

[128/500]  raw='fail'  →  Fail

 26%|██▌       | 129/500 [00:35<01:42,  3.61it/s]

[129/500]  raw='pass'  →  Pass

 26%|██▌       | 130/500 [00:36<01:42,  3.61it/s]

[130/500]  raw='pass'  →  Pass

 26%|██▌       | 131/500 [00:36<01:42,  3.61it/s]

[131/500]  raw='pass'  →  Pass

 26%|██▋       | 132/500 [00:36<01:41,  3.61it/s]

[132/500]  raw='fail'  →  Fail

 27%|██▋       | 133/500 [00:36<01:41,  3.61it/s]

[133/500]  raw='fail'  →  Fail

 27%|██▋       | 134/500 [00:37<01:41,  3.61it/s]

[134/500]  raw='pass'  →  Pass

 27%|██▋       | 135/500 [00:37<01:41,  3.61it/s]

[135/500]  raw='fail'  →  Fail

 27%|██▋       | 136/500 [00:37<01:40,  3.61it/s]

[136/500]  raw='pass'  →  Pass

 27%|██▋       | 137/500 [00:38<01:40,  3.60it/s]

[137/500]  raw='fail'  →  Fail

 28%|██▊       | 138/500 [00:38<01:40,  3.61it/s]

[138/500]  raw='fail'  →  Fail

 28%|██▊       | 139/500 [00:38<01:40,  3.58it/s]

[139/500]  raw='fail'  →  Fail

 28%|██▊       | 140/500 [00:38<01:40,  3.59it/s]

[140/500]  raw='fail'  →  Fail

 28%|██▊       | 141/500 [00:39<01:39,  3.59it/s]

[141/500]  raw='pass'  →  Pass

 28%|██▊       | 142/500 [00:39<01:39,  3.60it/s]

[142/500]  raw='fail'  →  Fail

 29%|██▊       | 143/500 [00:39<01:39,  3.60it/s]

[143/500]  raw='pass'  →  Pass

 29%|██▉       | 144/500 [00:40<01:38,  3.60it/s]

[144/500]  raw='pass'  →  Pass

 29%|██▉       | 145/500 [00:40<01:38,  3.61it/s]

[145/500]  raw='fail'  →  Fail

 29%|██▉       | 146/500 [00:40<01:38,  3.60it/s]

[146/500]  raw='fail'  →  Fail

 29%|██▉       | 147/500 [00:40<01:38,  3.59it/s]

[147/500]  raw='fail'  →  Fail

 30%|██▉       | 148/500 [00:41<01:38,  3.59it/s]

[148/500]  raw='fail'  →  Fail

 30%|██▉       | 149/500 [00:41<01:37,  3.60it/s]

[149/500]  raw='pass'  →  Pass

 30%|███       | 150/500 [00:41<01:37,  3.60it/s]

[150/500]  raw='fail'  →  Fail

 30%|███       | 151/500 [00:41<01:36,  3.60it/s]

[151/500]  raw='fail'  →  Fail

 30%|███       | 152/500 [00:42<01:36,  3.61it/s]

[152/500]  raw='fail'  →  Fail

 31%|███       | 153/500 [00:42<01:36,  3.60it/s]

[153/500]  raw='pass'  →  Pass

 31%|███       | 154/500 [00:42<01:36,  3.60it/s]

[154/500]  raw='fail'  →  Fail

 31%|███       | 155/500 [00:43<01:35,  3.60it/s]

[155/500]  raw='pass'  →  Pass

 31%|███       | 156/500 [00:43<01:35,  3.60it/s]

[156/500]  raw='fail'  →  Fail

 31%|███▏      | 157/500 [00:43<01:35,  3.60it/s]

[157/500]  raw='fail'  →  Fail

 32%|███▏      | 158/500 [00:43<01:34,  3.60it/s]

[158/500]  raw='pass'  →  Pass

 32%|███▏      | 159/500 [00:44<01:34,  3.60it/s]

[159/500]  raw='fail'  →  Fail

 32%|███▏      | 160/500 [00:44<01:34,  3.59it/s]

[160/500]  raw='pass'  →  Pass

 32%|███▏      | 161/500 [00:44<01:34,  3.59it/s]

[161/500]  raw='fail'  →  Fail

 32%|███▏      | 162/500 [00:45<01:33,  3.60it/s]

[162/500]  raw='fail'  →  Fail

 33%|███▎      | 163/500 [00:45<01:33,  3.60it/s]

[163/500]  raw='fail'  →  Fail

 33%|███▎      | 164/500 [00:45<01:33,  3.60it/s]

[164/500]  raw='fail'  →  Fail

 33%|███▎      | 165/500 [00:45<01:33,  3.58it/s]

[165/500]  raw='pass'  →  Pass

 33%|███▎      | 166/500 [00:46<01:33,  3.58it/s]

[166/500]  raw='pass'  →  Pass

 33%|███▎      | 167/500 [00:46<01:33,  3.58it/s]

[167/500]  raw='fail'  →  Fail

 34%|███▎      | 168/500 [00:46<01:32,  3.58it/s]

[168/500]  raw='fail'  →  Fail

 34%|███▍      | 169/500 [00:46<01:32,  3.58it/s]

[169/500]  raw='fail'  →  Fail

 34%|███▍      | 170/500 [00:47<01:32,  3.57it/s]

[170/500]  raw='pass'  →  Pass

 34%|███▍      | 171/500 [00:47<01:31,  3.58it/s]

[171/500]  raw='fail'  →  Fail

 34%|███▍      | 172/500 [00:47<01:31,  3.57it/s]

[172/500]  raw='pass'  →  Pass

 35%|███▍      | 173/500 [00:48<01:31,  3.58it/s]

[173/500]  raw='pass'  →  Pass

 35%|███▍      | 174/500 [00:48<01:31,  3.58it/s]

[174/500]  raw='pass'  →  Pass

 35%|███▌      | 175/500 [00:48<01:30,  3.59it/s]

[175/500]  raw='fail'  →  Fail

 35%|███▌      | 176/500 [00:48<01:29,  3.60it/s]

[176/500]  raw='fail'  →  Fail

 35%|███▌      | 177/500 [00:49<01:29,  3.60it/s]

[177/500]  raw='fail'  →  Fail

 36%|███▌      | 178/500 [00:49<01:29,  3.60it/s]

[178/500]  raw='fail'  →  Fail

 36%|███▌      | 179/500 [00:49<01:28,  3.61it/s]

[179/500]  raw='fail'  →  Fail

 36%|███▌      | 180/500 [00:50<01:28,  3.61it/s]

[180/500]  raw='fail'  →  Fail

 36%|███▌      | 181/500 [00:50<01:29,  3.58it/s]

[181/500]  raw='fail'  →  Fail

 36%|███▋      | 182/500 [00:50<01:28,  3.59it/s]

[182/500]  raw='fail'  →  Fail

 37%|███▋      | 183/500 [00:50<01:28,  3.59it/s]

[183/500]  raw='fail'  →  Fail

 37%|███▋      | 184/500 [00:51<01:28,  3.57it/s]

[184/500]  raw='pass'  →  Pass

 37%|███▋      | 185/500 [00:51<01:28,  3.57it/s]

[185/500]  raw='fail'  →  Fail

 37%|███▋      | 186/500 [00:51<01:27,  3.58it/s]

[186/500]  raw='pass'  →  Pass

 37%|███▋      | 187/500 [00:52<01:27,  3.60it/s]

[187/500]  raw='fail'  →  Fail

 38%|███▊      | 188/500 [00:52<01:26,  3.61it/s]

[188/500]  raw='pass'  →  Pass

 38%|███▊      | 189/500 [00:52<01:25,  3.62it/s]

[189/500]  raw='pass'  →  Pass

 38%|███▊      | 190/500 [00:52<01:25,  3.61it/s]

[190/500]  raw='pass'  →  Pass

 38%|███▊      | 191/500 [00:53<01:25,  3.60it/s]

[191/500]  raw='pass'  →  Pass

 38%|███▊      | 192/500 [00:53<01:26,  3.57it/s]

[192/500]  raw='pass'  →  Pass

 39%|███▊      | 193/500 [00:53<01:25,  3.58it/s]

[193/500]  raw='pass'  →  Pass

 39%|███▉      | 194/500 [00:53<01:25,  3.58it/s]

[194/500]  raw='fail'  →  Fail

 39%|███▉      | 195/500 [00:54<01:25,  3.57it/s]

[195/500]  raw='fail'  →  Fail

 39%|███▉      | 196/500 [00:54<01:24,  3.58it/s]

[196/500]  raw='fail'  →  Fail

 39%|███▉      | 197/500 [00:54<01:24,  3.58it/s]

[197/500]  raw='pass'  →  Pass

 40%|███▉      | 198/500 [00:55<01:24,  3.56it/s]

[198/500]  raw='pass'  →  Pass

 40%|███▉      | 199/500 [00:55<01:24,  3.58it/s]

[199/500]  raw='fail'  →  Fail

 40%|████      | 200/500 [00:55<01:23,  3.60it/s]

[200/500]  raw='fail'  →  Fail

 40%|████      | 201/500 [00:55<01:22,  3.62it/s]

[201/500]  raw='fail'  →  Fail

 40%|████      | 202/500 [00:56<01:22,  3.63it/s]

[202/500]  raw='fail'  →  Fail

 41%|████      | 203/500 [00:56<01:21,  3.65it/s]

[203/500]  raw='fail'  →  Fail

 41%|████      | 204/500 [00:56<01:20,  3.66it/s]

[204/500]  raw='fail'  →  Fail

 41%|████      | 205/500 [00:56<01:20,  3.65it/s]

[205/500]  raw='pass'  →  Pass

 41%|████      | 206/500 [00:57<01:21,  3.62it/s]

[206/500]  raw='pass'  →  Pass

 41%|████▏     | 207/500 [00:57<01:21,  3.61it/s]

[207/500]  raw='fail'  →  Fail

 42%|████▏     | 208/500 [00:57<01:20,  3.62it/s]

[208/500]  raw='fail'  →  Fail

 42%|████▏     | 209/500 [00:58<01:20,  3.62it/s]

[209/500]  raw='fail'  →  Fail

 42%|████▏     | 210/500 [00:58<01:20,  3.60it/s]

[210/500]  raw='fail'  →  Fail

 42%|████▏     | 211/500 [00:58<01:20,  3.60it/s]

[211/500]  raw='pass'  →  Pass

 42%|████▏     | 212/500 [00:58<01:19,  3.61it/s]

[212/500]  raw='fail'  →  Fail

 43%|████▎     | 213/500 [00:59<01:19,  3.60it/s]

[213/500]  raw='pass'  →  Pass

 43%|████▎     | 214/500 [00:59<01:19,  3.60it/s]

[214/500]  raw='fail'  →  Fail

 43%|████▎     | 215/500 [00:59<01:19,  3.61it/s]

[215/500]  raw='fail'  →  Fail

 43%|████▎     | 216/500 [01:00<01:18,  3.61it/s]

[216/500]  raw='pass'  →  Pass

 43%|████▎     | 217/500 [01:00<01:18,  3.61it/s]

[217/500]  raw='pass'  →  Pass

 44%|████▎     | 218/500 [01:00<01:18,  3.61it/s]

[218/500]  raw='fail'  →  Fail

 44%|████▍     | 219/500 [01:00<01:17,  3.61it/s]

[219/500]  raw='fail'  →  Fail

 44%|████▍     | 220/500 [01:01<01:17,  3.61it/s]

[220/500]  raw='fail'  →  Fail

 44%|████▍     | 221/500 [01:01<01:17,  3.60it/s]

[221/500]  raw='fail'  →  Fail

 44%|████▍     | 222/500 [01:01<01:17,  3.61it/s]

[222/500]  raw='fail'  →  Fail

 45%|████▍     | 223/500 [01:01<01:16,  3.60it/s]

[223/500]  raw='pass'  →  Pass

 45%|████▍     | 224/500 [01:02<01:16,  3.59it/s]

[224/500]  raw='pass'  →  Pass

 45%|████▌     | 225/500 [01:02<01:16,  3.59it/s]

[225/500]  raw='pass'  →  Pass

 45%|████▌     | 226/500 [01:02<01:16,  3.60it/s]

[226/500]  raw='fail'  →  Fail

 45%|████▌     | 227/500 [01:03<01:15,  3.61it/s]

[227/500]  raw='pass'  →  Pass

 46%|████▌     | 228/500 [01:03<01:15,  3.60it/s]

[228/500]  raw='fail'  →  Fail

 46%|████▌     | 229/500 [01:03<01:15,  3.58it/s]

[229/500]  raw='pass'  →  Pass

 46%|████▌     | 230/500 [01:03<01:15,  3.58it/s]

[230/500]  raw='pass'  →  Pass

 46%|████▌     | 231/500 [01:04<01:15,  3.57it/s]

[231/500]  raw='pass'  →  Pass

 46%|████▋     | 232/500 [01:04<01:15,  3.57it/s]

[232/500]  raw='pass'  →  Pass

 47%|████▋     | 233/500 [01:04<01:14,  3.57it/s]

[233/500]  raw='pass'  →  Pass

 47%|████▋     | 234/500 [01:05<01:14,  3.57it/s]

[234/500]  raw='pass'  →  Pass

 47%|████▋     | 235/500 [01:05<01:14,  3.57it/s]

[235/500]  raw='pass'  →  Pass

 47%|████▋     | 236/500 [01:05<01:13,  3.57it/s]

[236/500]  raw='pass'  →  Pass

 47%|████▋     | 237/500 [01:05<01:13,  3.58it/s]

[237/500]  raw='fail'  →  Fail

 48%|████▊     | 238/500 [01:06<01:13,  3.58it/s]

[238/500]  raw='pass'  →  Pass

 48%|████▊     | 239/500 [01:06<01:12,  3.59it/s]

[239/500]  raw='fail'  →  Fail

 48%|████▊     | 240/500 [01:06<01:12,  3.59it/s]

[240/500]  raw='pass'  →  Pass

 48%|████▊     | 241/500 [01:07<01:12,  3.59it/s]

[241/500]  raw='fail'  →  Fail

 48%|████▊     | 242/500 [01:07<01:11,  3.59it/s]

[242/500]  raw='pass'  →  Pass

 49%|████▊     | 243/500 [01:07<01:11,  3.59it/s]

[243/500]  raw='pass'  →  Pass

 49%|████▉     | 244/500 [01:07<01:11,  3.59it/s]

[244/500]  raw='fail'  →  Fail

 49%|████▉     | 245/500 [01:08<01:10,  3.59it/s]

[245/500]  raw='pass'  →  Pass

 49%|████▉     | 246/500 [01:08<01:10,  3.58it/s]

[246/500]  raw='fail'  →  Fail

 49%|████▉     | 247/500 [01:08<01:10,  3.59it/s]

[247/500]  raw='fail'  →  Fail

 50%|████▉     | 248/500 [01:08<01:10,  3.60it/s]

[248/500]  raw='fail'  →  Fail

 50%|████▉     | 249/500 [01:09<01:09,  3.62it/s]

[249/500]  raw='fail'  →  Fail

 50%|█████     | 250/500 [01:09<01:08,  3.64it/s]

[250/500]  raw='fail'  →  Fail

 50%|█████     | 251/500 [01:09<01:08,  3.64it/s]

[251/500]  raw='pass'  →  Pass

 50%|█████     | 252/500 [01:10<01:08,  3.64it/s]

[252/500]  raw='fail'  →  Fail

 51%|█████     | 253/500 [01:10<01:07,  3.65it/s]

[253/500]  raw='fail'  →  Fail

 51%|█████     | 254/500 [01:10<01:07,  3.66it/s]

[254/500]  raw='fail'  →  Fail

 51%|█████     | 255/500 [01:10<01:06,  3.66it/s]

[255/500]  raw='fail'  →  Fail

 51%|█████     | 256/500 [01:11<01:06,  3.67it/s]

[256/500]  raw='fail'  →  Fail

 51%|█████▏    | 257/500 [01:11<01:06,  3.67it/s]

[257/500]  raw='fail'  →  Fail

 52%|█████▏    | 258/500 [01:11<01:05,  3.67it/s]

[258/500]  raw='fail'  →  Fail

 52%|█████▏    | 259/500 [01:11<01:05,  3.67it/s]

[259/500]  raw='fail'  →  Fail

 52%|█████▏    | 260/500 [01:12<01:05,  3.67it/s]

[260/500]  raw='fail'  →  Fail

 52%|█████▏    | 261/500 [01:12<01:05,  3.67it/s]

[261/500]  raw='fail'  →  Fail

 52%|█████▏    | 262/500 [01:12<01:04,  3.67it/s]

[262/500]  raw='pass'  →  Pass

 53%|█████▎    | 263/500 [01:13<01:04,  3.67it/s]

[263/500]  raw='fail'  →  Fail

 53%|█████▎    | 264/500 [01:13<01:04,  3.68it/s]

[264/500]  raw='fail'  →  Fail

 53%|█████▎    | 265/500 [01:13<01:04,  3.67it/s]

[265/500]  raw='pass'  →  Pass

 53%|█████▎    | 266/500 [01:13<01:03,  3.67it/s]

[266/500]  raw='fail'  →  Fail

 53%|█████▎    | 267/500 [01:14<01:03,  3.66it/s]

[267/500]  raw='pass'  →  Pass

 54%|█████▎    | 268/500 [01:14<01:03,  3.66it/s]

[268/500]  raw='pass'  →  Pass

 54%|█████▍    | 269/500 [01:14<01:03,  3.66it/s]

[269/500]  raw='fail'  →  Fail

 54%|█████▍    | 270/500 [01:14<01:02,  3.66it/s]

[270/500]  raw='pass'  →  Pass

 54%|█████▍    | 271/500 [01:15<01:02,  3.65it/s]

[271/500]  raw='fail'  →  Fail

 54%|█████▍    | 272/500 [01:15<01:02,  3.66it/s]

[272/500]  raw='pass'  →  Pass

 55%|█████▍    | 273/500 [01:15<01:01,  3.68it/s]

[273/500]  raw='fail'  →  Fail

 55%|█████▍    | 274/500 [01:16<01:01,  3.67it/s]

[274/500]  raw='pass'  →  Pass

 55%|█████▌    | 275/500 [01:16<01:01,  3.66it/s]

[275/500]  raw='pass'  →  Pass

 55%|█████▌    | 276/500 [01:16<01:01,  3.66it/s]

[276/500]  raw='fail'  →  Fail

 55%|█████▌    | 277/500 [01:16<01:00,  3.66it/s]

[277/500]  raw='pass'  →  Pass

 56%|█████▌    | 278/500 [01:17<01:00,  3.66it/s]

[278/500]  raw='pass'  →  Pass

 56%|█████▌    | 279/500 [01:17<01:00,  3.65it/s]

[279/500]  raw='fail'  →  Fail

 56%|█████▌    | 280/500 [01:17<01:00,  3.65it/s]

[280/500]  raw='pass'  →  Pass

 56%|█████▌    | 281/500 [01:17<01:00,  3.65it/s]

[281/500]  raw='fail'  →  Fail

 56%|█████▋    | 282/500 [01:18<00:59,  3.64it/s]

[282/500]  raw='pass'  →  Pass

 57%|█████▋    | 283/500 [01:18<00:59,  3.64it/s]

[283/500]  raw='fail'  →  Fail

 57%|█████▋    | 284/500 [01:18<00:59,  3.64it/s]

[284/500]  raw='pass'  →  Pass

 57%|█████▋    | 285/500 [01:19<00:59,  3.64it/s]

[285/500]  raw='fail'  →  Fail

 57%|█████▋    | 286/500 [01:19<00:58,  3.64it/s]

[286/500]  raw='fail'  →  Fail

 57%|█████▋    | 287/500 [01:19<00:58,  3.63it/s]

[287/500]  raw='pass'  →  Pass

 58%|█████▊    | 288/500 [01:19<00:58,  3.63it/s]

[288/500]  raw='pass'  →  Pass

 58%|█████▊    | 289/500 [01:20<00:58,  3.60it/s]

[289/500]  raw='fail'  →  Fail

 58%|█████▊    | 290/500 [01:20<00:58,  3.59it/s]

[290/500]  raw='fail'  →  Fail

 58%|█████▊    | 291/500 [01:20<00:58,  3.58it/s]

[291/500]  raw='pass'  →  Pass

 58%|█████▊    | 292/500 [01:21<00:57,  3.59it/s]

[292/500]  raw='pass'  →  Pass

 59%|█████▊    | 293/500 [01:21<00:57,  3.60it/s]

[293/500]  raw='fail'  →  Fail

 59%|█████▉    | 294/500 [01:21<00:57,  3.60it/s]

[294/500]  raw='fail'  →  Fail

 59%|█████▉    | 295/500 [01:21<00:56,  3.60it/s]

[295/500]  raw='fail'  →  Fail

 59%|█████▉    | 296/500 [01:22<00:56,  3.61it/s]

[296/500]  raw='pass'  →  Pass

 59%|█████▉    | 297/500 [01:22<00:56,  3.61it/s]

[297/500]  raw='pass'  →  Pass

 60%|█████▉    | 298/500 [01:22<00:55,  3.61it/s]

[298/500]  raw='pass'  →  Pass

 60%|█████▉    | 299/500 [01:22<00:55,  3.62it/s]

[299/500]  raw='pass'  →  Pass

 60%|██████    | 300/500 [01:23<00:55,  3.62it/s]

[300/500]  raw='pass'  →  Pass

 60%|██████    | 301/500 [01:23<00:54,  3.62it/s]

[301/500]  raw='pass'  →  Pass

 60%|██████    | 302/500 [01:23<00:54,  3.63it/s]

[302/500]  raw='fail'  →  Fail

 61%|██████    | 303/500 [01:24<00:54,  3.64it/s]

[303/500]  raw='fail'  →  Fail

 61%|██████    | 304/500 [01:24<00:53,  3.63it/s]

[304/500]  raw='pass'  →  Pass

 61%|██████    | 305/500 [01:24<00:53,  3.63it/s]

[305/500]  raw='pass'  →  Pass

 61%|██████    | 306/500 [01:24<00:53,  3.63it/s]

[306/500]  raw='fail'  →  Fail

 61%|██████▏   | 307/500 [01:25<00:53,  3.63it/s]

[307/500]  raw='pass'  →  Pass

 62%|██████▏   | 308/500 [01:25<00:52,  3.63it/s]

[308/500]  raw='pass'  →  Pass

 62%|██████▏   | 309/500 [01:25<00:52,  3.63it/s]

[309/500]  raw='pass'  →  Pass

 62%|██████▏   | 310/500 [01:25<00:52,  3.64it/s]

[310/500]  raw='fail'  →  Fail

 62%|██████▏   | 311/500 [01:26<00:51,  3.64it/s]

[311/500]  raw='fail'  →  Fail

 62%|██████▏   | 312/500 [01:26<00:51,  3.64it/s]

[312/500]  raw='pass'  →  Pass

 63%|██████▎   | 313/500 [01:26<00:51,  3.64it/s]

[313/500]  raw='fail'  →  Fail

 63%|██████▎   | 314/500 [01:27<00:51,  3.64it/s]

[314/500]  raw='pass'  →  Pass

 63%|██████▎   | 315/500 [01:27<00:50,  3.64it/s]

[315/500]  raw='pass'  →  Pass

 63%|██████▎   | 316/500 [01:27<00:50,  3.64it/s]

[316/500]  raw='fail'  →  Fail

 63%|██████▎   | 317/500 [01:27<00:50,  3.63it/s]

[317/500]  raw='pass'  →  Pass

 64%|██████▎   | 318/500 [01:28<00:50,  3.63it/s]

[318/500]  raw='pass'  →  Pass

 64%|██████▍   | 319/500 [01:28<00:50,  3.62it/s]

[319/500]  raw='pass'  →  Pass

 64%|██████▍   | 320/500 [01:28<00:49,  3.61it/s]

[320/500]  raw='pass'  →  Pass

 64%|██████▍   | 321/500 [01:29<00:49,  3.61it/s]

[321/500]  raw='fail'  →  Fail

 64%|██████▍   | 322/500 [01:29<00:49,  3.62it/s]

[322/500]  raw='fail'  →  Fail

 65%|██████▍   | 323/500 [01:29<00:48,  3.62it/s]

[323/500]  raw='pass'  →  Pass

 65%|██████▍   | 324/500 [01:29<00:49,  3.59it/s]

[324/500]  raw='fail'  →  Fail

 65%|██████▌   | 325/500 [01:30<00:48,  3.57it/s]

[325/500]  raw='pass'  →  Pass

 65%|██████▌   | 326/500 [01:30<00:48,  3.57it/s]

[326/500]  raw='pass'  →  Pass

 65%|██████▌   | 327/500 [01:30<00:48,  3.57it/s]

[327/500]  raw='fail'  →  Fail

 66%|██████▌   | 328/500 [01:30<00:48,  3.58it/s]

[328/500]  raw='fail'  →  Fail

 66%|██████▌   | 329/500 [01:31<00:47,  3.60it/s]

[329/500]  raw='pass'  →  Pass

 66%|██████▌   | 330/500 [01:31<00:47,  3.59it/s]

[330/500]  raw='pass'  →  Pass

 66%|██████▌   | 331/500 [01:31<00:46,  3.60it/s]

[331/500]  raw='pass'  →  Pass

 66%|██████▋   | 332/500 [01:32<00:46,  3.60it/s]

[332/500]  raw='pass'  →  Pass

 67%|██████▋   | 333/500 [01:32<00:46,  3.60it/s]

[333/500]  raw='pass'  →  Pass

 67%|██████▋   | 334/500 [01:32<00:45,  3.62it/s]

[334/500]  raw='fail'  →  Fail

 67%|██████▋   | 335/500 [01:32<00:45,  3.62it/s]

[335/500]  raw='fail'  →  Fail

 67%|██████▋   | 336/500 [01:33<00:45,  3.63it/s]

[336/500]  raw='pass'  →  Pass

 67%|██████▋   | 337/500 [01:33<00:44,  3.63it/s]

[337/500]  raw='fail'  →  Fail

 68%|██████▊   | 338/500 [01:33<00:44,  3.64it/s]

[338/500]  raw='pass'  →  Pass

 68%|██████▊   | 339/500 [01:34<00:44,  3.65it/s]

[339/500]  raw='fail'  →  Fail

 68%|██████▊   | 340/500 [01:34<00:43,  3.65it/s]

[340/500]  raw='pass'  →  Pass

 68%|██████▊   | 341/500 [01:34<00:43,  3.65it/s]

[341/500]  raw='fail'  →  Fail

 68%|██████▊   | 342/500 [01:34<00:43,  3.64it/s]

[342/500]  raw='fail'  →  Fail

 69%|██████▊   | 343/500 [01:35<00:43,  3.63it/s]

[343/500]  raw='pass'  →  Pass

 69%|██████▉   | 344/500 [01:35<00:42,  3.63it/s]

[344/500]  raw='pass'  →  Pass

 69%|██████▉   | 345/500 [01:35<00:42,  3.63it/s]

[345/500]  raw='fail'  →  Fail

 69%|██████▉   | 346/500 [01:35<00:42,  3.64it/s]

[346/500]  raw='fail'  →  Fail

 69%|██████▉   | 347/500 [01:36<00:41,  3.65it/s]

[347/500]  raw='fail'  →  Fail

 70%|██████▉   | 348/500 [01:36<00:41,  3.65it/s]

[348/500]  raw='fail'  →  Fail

 70%|██████▉   | 349/500 [01:36<00:41,  3.65it/s]

[349/500]  raw='pass'  →  Pass

 70%|███████   | 350/500 [01:37<00:41,  3.65it/s]

[350/500]  raw='pass'  →  Pass

 70%|███████   | 351/500 [01:37<00:40,  3.65it/s]

[351/500]  raw='fail'  →  Fail

 70%|███████   | 352/500 [01:37<00:41,  3.60it/s]

[352/500]  raw='fail'  →  Fail

 71%|███████   | 353/500 [01:37<00:40,  3.60it/s]

[353/500]  raw='fail'  →  Fail

 71%|███████   | 354/500 [01:38<00:40,  3.60it/s]

[354/500]  raw='pass'  →  Pass

 71%|███████   | 355/500 [01:38<00:40,  3.61it/s]

[355/500]  raw='fail'  →  Fail

 71%|███████   | 356/500 [01:38<00:39,  3.63it/s]

[356/500]  raw='fail'  →  Fail

 71%|███████▏  | 357/500 [01:38<00:39,  3.63it/s]

[357/500]  raw='pass'  →  Pass

 72%|███████▏  | 358/500 [01:39<00:39,  3.58it/s]

[358/500]  raw='fail'  →  Fail

 72%|███████▏  | 359/500 [01:39<00:39,  3.59it/s]

[359/500]  raw='fail'  →  Fail

 72%|███████▏  | 360/500 [01:39<00:38,  3.61it/s]

[360/500]  raw='fail'  →  Fail

 72%|███████▏  | 361/500 [01:40<00:38,  3.63it/s]

[361/500]  raw='pass'  →  Pass

 72%|███████▏  | 362/500 [01:40<00:37,  3.65it/s]

[362/500]  raw='fail'  →  Fail

 73%|███████▎  | 363/500 [01:40<00:37,  3.66it/s]

[363/500]  raw='fail'  →  Fail

 73%|███████▎  | 364/500 [01:40<00:37,  3.67it/s]

[364/500]  raw='fail'  →  Fail

 73%|███████▎  | 365/500 [01:41<00:37,  3.64it/s]

[365/500]  raw='pass'  →  Pass

 73%|███████▎  | 366/500 [01:41<00:36,  3.64it/s]

[366/500]  raw='pass'  →  Pass

 73%|███████▎  | 367/500 [01:41<00:36,  3.65it/s]

[367/500]  raw='pass'  →  Pass

 74%|███████▎  | 368/500 [01:41<00:36,  3.66it/s]

[368/500]  raw='fail'  →  Fail

 74%|███████▍  | 369/500 [01:42<00:35,  3.65it/s]

[369/500]  raw='fail'  →  Fail

 74%|███████▍  | 370/500 [01:42<00:35,  3.66it/s]

[370/500]  raw='fail'  →  Fail

 74%|███████▍  | 371/500 [01:42<00:35,  3.66it/s]

[371/500]  raw='pass'  →  Pass

 74%|███████▍  | 372/500 [01:43<00:35,  3.64it/s]

[372/500]  raw='fail'  →  Fail

 75%|███████▍  | 373/500 [01:43<00:35,  3.61it/s]

[373/500]  raw='pass'  →  Pass

 75%|███████▍  | 374/500 [01:43<00:34,  3.60it/s]

[374/500]  raw='fail'  →  Fail

 75%|███████▌  | 375/500 [01:43<00:34,  3.62it/s]

[375/500]  raw='pass'  →  Pass

 75%|███████▌  | 376/500 [01:44<00:34,  3.63it/s]

[376/500]  raw='fail'  →  Fail

 75%|███████▌  | 377/500 [01:44<00:33,  3.64it/s]

[377/500]  raw='fail'  →  Fail

 76%|███████▌  | 378/500 [01:44<00:33,  3.65it/s]

[378/500]  raw='fail'  →  Fail

 76%|███████▌  | 379/500 [01:45<00:33,  3.66it/s]

[379/500]  raw='fail'  →  Fail

 76%|███████▌  | 380/500 [01:45<00:32,  3.66it/s]

[380/500]  raw='pass'  →  Pass

 76%|███████▌  | 381/500 [01:45<00:32,  3.67it/s]

[381/500]  raw='fail'  →  Fail

 76%|███████▋  | 382/500 [01:45<00:32,  3.67it/s]

[382/500]  raw='fail'  →  Fail

 77%|███████▋  | 383/500 [01:46<00:31,  3.67it/s]

[383/500]  raw='pass'  →  Pass

 77%|███████▋  | 384/500 [01:46<00:31,  3.68it/s]

[384/500]  raw='fail'  →  Fail

 77%|███████▋  | 385/500 [01:46<00:31,  3.67it/s]

[385/500]  raw='fail'  →  Fail

 77%|███████▋  | 386/500 [01:46<00:31,  3.68it/s]

[386/500]  raw='fail'  →  Fail

 77%|███████▋  | 387/500 [01:47<00:30,  3.67it/s]

[387/500]  raw='pass'  →  Pass

 78%|███████▊  | 388/500 [01:47<00:30,  3.67it/s]

[388/500]  raw='pass'  →  Pass

 78%|███████▊  | 389/500 [01:47<00:30,  3.67it/s]

[389/500]  raw='pass'  →  Pass

 78%|███████▊  | 390/500 [01:47<00:29,  3.68it/s]

[390/500]  raw='pass'  →  Pass

 78%|███████▊  | 391/500 [01:48<00:29,  3.66it/s]

[391/500]  raw='fail'  →  Fail

 78%|███████▊  | 392/500 [01:48<00:29,  3.65it/s]

[392/500]  raw='pass'  →  Pass

 79%|███████▊  | 393/500 [01:48<00:29,  3.66it/s]

[393/500]  raw='fail'  →  Fail

 79%|███████▉  | 394/500 [01:49<00:29,  3.65it/s]

[394/500]  raw='fail'  →  Fail

 79%|███████▉  | 395/500 [01:49<00:28,  3.66it/s]

[395/500]  raw='fail'  →  Fail

 79%|███████▉  | 396/500 [01:49<00:28,  3.66it/s]

[396/500]  raw='fail'  →  Fail

 79%|███████▉  | 397/500 [01:49<00:28,  3.66it/s]

[397/500]  raw='pass'  →  Pass

 80%|███████▉  | 398/500 [01:50<00:27,  3.65it/s]

[398/500]  raw='fail'  →  Fail

 80%|███████▉  | 399/500 [01:50<00:27,  3.64it/s]

[399/500]  raw='fail'  →  Fail

 80%|████████  | 400/500 [01:50<00:27,  3.64it/s]

[400/500]  raw='fail'  →  Fail

 80%|████████  | 401/500 [01:51<00:27,  3.64it/s]

[401/500]  raw='pass'  →  Pass

 80%|████████  | 402/500 [01:51<00:26,  3.65it/s]

[402/500]  raw='fail'  →  Fail

 81%|████████  | 403/500 [01:51<00:26,  3.64it/s]

[403/500]  raw='pass'  →  Pass

 81%|████████  | 404/500 [01:51<00:26,  3.64it/s]

[404/500]  raw='fail'  →  Fail

 81%|████████  | 405/500 [01:52<00:26,  3.64it/s]

[405/500]  raw='fail'  →  Fail

 81%|████████  | 406/500 [01:52<00:25,  3.64it/s]

[406/500]  raw='pass'  →  Pass

 81%|████████▏ | 407/500 [01:52<00:25,  3.64it/s]

[407/500]  raw='fail'  →  Fail

 82%|████████▏ | 408/500 [01:52<00:25,  3.63it/s]

[408/500]  raw='fail'  →  Fail

 82%|████████▏ | 409/500 [01:53<00:25,  3.63it/s]

[409/500]  raw='fail'  →  Fail

 82%|████████▏ | 410/500 [01:53<00:24,  3.62it/s]

[410/500]  raw='pass'  →  Pass

 82%|████████▏ | 411/500 [01:53<00:24,  3.63it/s]

[411/500]  raw='pass'  →  Pass

 82%|████████▏ | 412/500 [01:54<00:24,  3.64it/s]

[412/500]  raw='pass'  →  Pass

 83%|████████▎ | 413/500 [01:54<00:24,  3.62it/s]

[413/500]  raw='fail'  →  Fail

 83%|████████▎ | 414/500 [01:54<00:23,  3.63it/s]

[414/500]  raw='fail'  →  Fail

 83%|████████▎ | 415/500 [01:54<00:23,  3.64it/s]

[415/500]  raw='pass'  →  Pass

 83%|████████▎ | 416/500 [01:55<00:23,  3.65it/s]

[416/500]  raw='fail'  →  Fail

 83%|████████▎ | 417/500 [01:55<00:22,  3.65it/s]

[417/500]  raw='pass'  →  Pass

 84%|████████▎ | 418/500 [01:55<00:22,  3.65it/s]

[418/500]  raw='pass'  →  Pass

 84%|████████▍ | 419/500 [01:55<00:22,  3.62it/s]

[419/500]  raw='fail'  →  Fail

 84%|████████▍ | 420/500 [01:56<00:22,  3.63it/s]

[420/500]  raw='fail'  →  Fail

 84%|████████▍ | 421/500 [01:56<00:21,  3.62it/s]

[421/500]  raw='pass'  →  Pass

 84%|████████▍ | 422/500 [01:56<00:21,  3.63it/s]

[422/500]  raw='pass'  →  Pass

 85%|████████▍ | 423/500 [01:57<00:21,  3.63it/s]

[423/500]  raw='pass'  →  Pass

 85%|████████▍ | 424/500 [01:57<00:20,  3.66it/s]

[424/500]  raw='pass'  →  Pass

 85%|████████▌ | 425/500 [01:57<00:20,  3.68it/s]

[425/500]  raw='fail'  →  Fail

 85%|████████▌ | 426/500 [01:57<00:20,  3.69it/s]

[426/500]  raw='fail'  →  Fail

 85%|████████▌ | 427/500 [01:58<00:19,  3.67it/s]

[427/500]  raw='pass'  →  Pass

 86%|████████▌ | 428/500 [01:58<00:19,  3.66it/s]

[428/500]  raw='pass'  →  Pass

 86%|████████▌ | 429/500 [01:58<00:19,  3.65it/s]

[429/500]  raw='fail'  →  Fail

 86%|████████▌ | 430/500 [01:58<00:19,  3.64it/s]

[430/500]  raw='pass'  →  Pass

 86%|████████▌ | 431/500 [01:59<00:18,  3.65it/s]

[431/500]  raw='fail'  →  Fail

 86%|████████▋ | 432/500 [01:59<00:18,  3.65it/s]

[432/500]  raw='pass'  →  Pass

 87%|████████▋ | 433/500 [01:59<00:18,  3.65it/s]

[433/500]  raw='pass'  →  Pass

 87%|████████▋ | 434/500 [02:00<00:18,  3.65it/s]

[434/500]  raw='fail'  →  Fail

 87%|████████▋ | 435/500 [02:00<00:17,  3.66it/s]

[435/500]  raw='fail'  →  Fail

 87%|████████▋ | 436/500 [02:00<00:17,  3.65it/s]

[436/500]  raw='fail'  →  Fail

 87%|████████▋ | 437/500 [02:00<00:17,  3.64it/s]

[437/500]  raw='fail'  →  Fail

 88%|████████▊ | 438/500 [02:01<00:17,  3.65it/s]

[438/500]  raw='pass'  →  Pass

 88%|████████▊ | 439/500 [02:01<00:16,  3.65it/s]

[439/500]  raw='fail'  →  Fail

 88%|████████▊ | 440/500 [02:01<00:16,  3.65it/s]

[440/500]  raw='pass'  →  Pass

 88%|████████▊ | 441/500 [02:01<00:16,  3.65it/s]

[441/500]  raw='fail'  →  Fail

 88%|████████▊ | 442/500 [02:02<00:15,  3.65it/s]

[442/500]  raw='pass'  →  Pass

 89%|████████▊ | 443/500 [02:02<00:15,  3.65it/s]

[443/500]  raw='pass'  →  Pass

 89%|████████▉ | 444/500 [02:02<00:15,  3.65it/s]

[444/500]  raw='pass'  →  Pass

 89%|████████▉ | 445/500 [02:03<00:15,  3.65it/s]

[445/500]  raw='fail'  →  Fail

 89%|████████▉ | 446/500 [02:03<00:14,  3.64it/s]

[446/500]  raw='fail'  →  Fail

 89%|████████▉ | 447/500 [02:03<00:14,  3.64it/s]

[447/500]  raw='pass'  →  Pass

 90%|████████▉ | 448/500 [02:03<00:14,  3.63it/s]

[448/500]  raw='fail'  →  Fail

 90%|████████▉ | 449/500 [02:04<00:14,  3.63it/s]

[449/500]  raw='pass'  →  Pass

 90%|█████████ | 450/500 [02:04<00:13,  3.63it/s]

[450/500]  raw='fail'  →  Fail

 90%|█████████ | 451/500 [02:04<00:13,  3.63it/s]

[451/500]  raw='pass'  →  Pass

 90%|█████████ | 452/500 [02:05<00:13,  3.64it/s]

[452/500]  raw='fail'  →  Fail

 91%|█████████ | 453/500 [02:05<00:12,  3.64it/s]

[453/500]  raw='pass'  →  Pass

 91%|█████████ | 454/500 [02:05<00:12,  3.64it/s]

[454/500]  raw='pass'  →  Pass

 91%|█████████ | 455/500 [02:05<00:12,  3.64it/s]

[455/500]  raw='pass'  →  Pass

 91%|█████████ | 456/500 [02:06<00:12,  3.62it/s]

[456/500]  raw='pass'  →  Pass

 91%|█████████▏| 457/500 [02:06<00:11,  3.63it/s]

[457/500]  raw='fail'  →  Fail

 92%|█████████▏| 458/500 [02:06<00:11,  3.64it/s]

[458/500]  raw='fail'  →  Fail

 92%|█████████▏| 459/500 [02:06<00:11,  3.63it/s]

[459/500]  raw='fail'  →  Fail

 92%|█████████▏| 460/500 [02:07<00:11,  3.62it/s]

[460/500]  raw='fail'  →  Fail

 92%|█████████▏| 461/500 [02:07<00:10,  3.60it/s]

[461/500]  raw='pass'  →  Pass

 92%|█████████▏| 462/500 [02:07<00:10,  3.61it/s]

[462/500]  raw='fail'  →  Fail

 93%|█████████▎| 463/500 [02:08<00:10,  3.59it/s]

[463/500]  raw='pass'  →  Pass

 93%|█████████▎| 464/500 [02:08<00:10,  3.58it/s]

[464/500]  raw='pass'  →  Pass

 93%|█████████▎| 465/500 [02:08<00:09,  3.58it/s]

[465/500]  raw='pass'  →  Pass

 93%|█████████▎| 466/500 [02:08<00:09,  3.59it/s]

[466/500]  raw='fail'  →  Fail

 93%|█████████▎| 467/500 [02:09<00:09,  3.61it/s]

[467/500]  raw='pass'  →  Pass

 94%|█████████▎| 468/500 [02:09<00:08,  3.62it/s]

[468/500]  raw='pass'  →  Pass

 94%|█████████▍| 469/500 [02:09<00:08,  3.64it/s]

[469/500]  raw='fail'  →  Fail

 94%|█████████▍| 470/500 [02:09<00:08,  3.65it/s]

[470/500]  raw='fail'  →  Fail

 94%|█████████▍| 471/500 [02:10<00:07,  3.67it/s]

[471/500]  raw='pass'  →  Pass

 94%|█████████▍| 472/500 [02:10<00:07,  3.67it/s]

[472/500]  raw='pass'  →  Pass

 95%|█████████▍| 473/500 [02:10<00:07,  3.68it/s]

[473/500]  raw='pass'  →  Pass

 95%|█████████▍| 474/500 [02:11<00:07,  3.68it/s]

[474/500]  raw='fail'  →  Fail

 95%|█████████▌| 475/500 [02:11<00:06,  3.65it/s]

[475/500]  raw='fail'  →  Fail

 95%|█████████▌| 476/500 [02:11<00:06,  3.64it/s]

[476/500]  raw='pass'  →  Pass

 95%|█████████▌| 477/500 [02:11<00:06,  3.64it/s]

[477/500]  raw='fail'  →  Fail

 96%|█████████▌| 478/500 [02:12<00:06,  3.60it/s]

[478/500]  raw='pass'  →  Pass

 96%|█████████▌| 479/500 [02:12<00:05,  3.58it/s]

[479/500]  raw='pass'  →  Pass

 96%|█████████▌| 480/500 [02:12<00:05,  3.58it/s]

[480/500]  raw='fail'  →  Fail

 96%|█████████▌| 481/500 [02:13<00:05,  3.57it/s]

[481/500]  raw='fail'  →  Fail

 96%|█████████▋| 482/500 [02:13<00:05,  3.58it/s]

[482/500]  raw='fail'  →  Fail

 97%|█████████▋| 483/500 [02:13<00:04,  3.59it/s]

[483/500]  raw='fail'  →  Fail

 97%|█████████▋| 484/500 [02:13<00:04,  3.60it/s]

[484/500]  raw='pass'  →  Pass

 97%|█████████▋| 485/500 [02:14<00:04,  3.59it/s]

[485/500]  raw='fail'  →  Fail

 97%|█████████▋| 486/500 [02:14<00:03,  3.62it/s]

[486/500]  raw='pass'  →  Pass

 97%|█████████▋| 487/500 [02:14<00:03,  3.63it/s]

[487/500]  raw='fail'  →  Fail

 98%|█████████▊| 488/500 [02:14<00:03,  3.64it/s]

[488/500]  raw='fail'  →  Fail

 98%|█████████▊| 489/500 [02:15<00:03,  3.61it/s]

[489/500]  raw='fail'  →  Fail

 98%|█████████▊| 490/500 [02:15<00:02,  3.60it/s]

[490/500]  raw='pass'  →  Pass

 98%|█████████▊| 491/500 [02:15<00:02,  3.62it/s]

[491/500]  raw='fail'  →  Fail

 98%|█████████▊| 492/500 [02:16<00:02,  3.62it/s]

[492/500]  raw='pass'  →  Pass

 99%|█████████▊| 493/500 [02:16<00:01,  3.63it/s]

[493/500]  raw='fail'  →  Fail

 99%|█████████▉| 494/500 [02:16<00:01,  3.65it/s]

[494/500]  raw='fail'  →  Fail

 99%|█████████▉| 495/500 [02:16<00:01,  3.66it/s]

[495/500]  raw='fail'  →  Fail

 99%|█████████▉| 496/500 [02:17<00:01,  3.65it/s]

[496/500]  raw='fail'  →  Fail

 99%|█████████▉| 497/500 [02:17<00:00,  3.63it/s]

[497/500]  raw='fail'  →  Fail

100%|█████████▉| 498/500 [02:17<00:00,  3.63it/s]

[498/500]  raw='pass'  →  Pass

100%|█████████▉| 499/500 [02:17<00:00,  3.63it/s]

[499/500]  raw='fail'  →  Fail

100%|██████████| 500/500 [02:18<00:00,  3.62it/s]

[500/500]  raw='pass'  →  Pass

In [ ]:
# Step 6: evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

results_fresh = pd.DataFrame({
    "y_true"    : y_fresh_true,
    "y_pred"    : y_fresh_pred,
    "generated" : y_fresh_generated,
})
results_fresh["y_true_label"] = results_fresh["y_true"].map({1: "Pass", 0: "Fail"})
results_fresh["y_pred_label"] = results_fresh["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_fresh.to_string())

valid_mask   = [i for i, p in enumerate(y_fresh_pred) if p != -1]
y_true_valid = y_fresh_true[valid_mask]
y_pred_valid = [y_fresh_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_fresh_pred)}")
print(f"Unparseable : {len(y_fresh_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         1       1      pass         Pass         Pass
1         1       0      fail         Pass         Fail
2         1       1      pass         Pass         Pass
3         1       1      pass         Pass         Pass
4         1       1      pass         Pass         Pass
5         0       0      fail         Fail         Fail
6         0       0      fail         Fail         Fail
7         1       1      pass         Pass         Pass
8         0       0      fail         Fail         Fail
9         1       1      pass         Pass         Pass
10        0       0      fail         Fail         Fail
11        1       1      pass         Pass         Pass
12        0       0      fail         Fail         Fail
13        0       1      pass         Fail         Pass
14        0       0      fail         Fail         Fail
15        0       0      fail         Fail         Fail
16        0       0      fail         Fail         Fail
17        0       0      fail         Fail         Fail
18        0       0      fail         Fail         Fail
19        0       0      fail         Fail         Fail
20        0       0      fail         Fail         Fail
21        0       0      fail         Fail         Fail
22        0       0      fail         Fail         Fail
23        0       0      fail         Fail         Fail
24        1       1      pass         Pass         Pass
25        0       0      fail         Fail         Fail
26        1       1      pass         Pass         Pass
27        1       1      pass         Pass         Pass
28        0       0      fail         Fail         Fail
29        0       1      pass         Fail         Pass
30        0       0      fail         Fail         Fail
31        1       1      pass         Pass         Pass
32        0       0      fail         Fail         Fail
33        1       1      pass         Pass         Pass
34        0       1      pass         Fail         Pass
35        0       0      fail         Fail         Fail
36        1       1      pass         Pass         Pass
37        0       0      fail         Fail         Fail
38        0       0      fail         Fail         Fail
39        1       1      pass         Pass         Pass
40        1       1      pass         Pass         Pass
41        1       1      pass         Pass         Pass
42        1       1      pass         Pass         Pass
43        0       0      fail         Fail         Fail
44        1       1      pass         Pass         Pass
45        1       0      fail         Pass         Fail
46        0       0      fail         Fail         Fail
47        0       0      fail         Fail         Fail
48        1       0      fail         Pass         Fail
49        1       1      pass         Pass         Pass
50        0       0      fail         Fail         Fail
51        0       0      fail         Fail         Fail
52        0       0      fail         Fail         Fail
53        0       0      fail         Fail         Fail
54        1       1      pass         Pass         Pass
55        0       0      fail         Fail         Fail
56        0       0      fail         Fail         Fail
57        1       1      pass         Pass         Pass
58        0       0      fail         Fail         Fail
59        1       1      pass         Pass         Pass
60        1       1      pass         Pass         Pass
61        1       1      pass         Pass         Pass
62        0       0      fail         Fail         Fail
63        1       1      pass         Pass         Pass
64        0       0      fail         Fail         Fail
65        1       0      fail         Pass         Fail
66        1       1      pass         Pass         Pass
67        1       0      fail         Pass         Fail
68        1       1      pass         Pass         Pass
69        1       1      pass         Pass         Pass
70        0       0      fail         Fail         Fail
71        0       0      fail         Fail         Fail
72        0       0      fail         Fail         Fail
73        0       0      fail         Fail         Fail
74        0       0      fail         Fail         Fail
75        1       0      fail         Pass         Fail
76        1       1      pass         Pass         Pass
77        0       0      fail         Fail         Fail
78        1       1      pass         Pass         Pass
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        0       0      fail         Fail         Fail
82        0       0      fail         Fail         Fail
83        1       1      pass         Pass         Pass
84        1       1      pass         Pass         Pass
85        0       1      pass         Fail         Pass
86        0       0      fail         Fail         Fail
87        0       0      fail         Fail         Fail
88        0       0      fail         Fail         Fail
89        1       1      pass         Pass         Pass
90        1       1      pass         Pass         Pass
91        0       0      fail         Fail         Fail
92        1       1      pass         Pass         Pass
93        1       1      pass         Pass         Pass
94        0       0      fail         Fail         Fail
95        1       1      pass         Pass         Pass
96        0       0      fail         Fail         Fail
97        1       1      pass         Pass         Pass
98        1       1      pass         Pass         Pass
99        0       0      fail         Fail         Fail
100       1       1      pass         Pass         Pass
101       0       0      fail         Fail         Fail
102       1       0      fail         Pass         Fail
103       1       1      pass         Pass         Pass
104       1       1      pass         Pass         Pass
105       1       1      pass         Pass         Pass
106       0       0      fail         Fail         Fail
107       0       0      fail         Fail         Fail
108       0       0      fail         Fail         Fail
109       1       1      pass         Pass         Pass
110       0       1      pass         Fail         Pass
111       1       1      pass         Pass         Pass
112       1       1      pass         Pass         Pass
113       0       1      pass         Fail         Pass
114       0       0      fail         Fail         Fail
115       1       1      pass         Pass         Pass
116       0       0      fail         Fail         Fail
117       0       0      fail         Fail         Fail
118       0       0      fail         Fail         Fail
119       0       1      pass         Fail         Pass
120       0       0      fail         Fail         Fail
121       0       0      fail         Fail         Fail
122       1       1      pass         Pass         Pass
123       0       0      fail         Fail         Fail
124       0       0      fail         Fail         Fail
125       1       1      pass         Pass         Pass
126       1       1      pass         Pass         Pass
127       0       0      fail         Fail         Fail
128       1       1      pass         Pass         Pass
129       1       1      pass         Pass         Pass
130       0       1      pass         Fail         Pass
131       0       0      fail         Fail         Fail
132       0       0      fail         Fail         Fail
133       1       1      pass         Pass         Pass
134       0       0      fail         Fail         Fail
135       1       1      pass         Pass         Pass
136       0       0      fail         Fail         Fail
137       1       0      fail         Pass         Fail
138       0       0      fail         Fail         Fail
139       0       0      fail         Fail         Fail
140       1       1      pass         Pass         Pass
141       0       0      fail         Fail         Fail
142       1       1      pass         Pass         Pass
143       1       1      pass         Pass         Pass
144       0       0      fail         Fail         Fail
145       0       0      fail         Fail         Fail
146       0       0      fail         Fail         Fail
147       0       0      fail         Fail         Fail
148       1       1      pass         Pass         Pass
149       0       0      fail         Fail         Fail
150       0       0      fail         Fail         Fail
151       0       0      fail         Fail         Fail
152       1       1      pass         Pass         Pass
153       0       0      fail         Fail         Fail
154       1       1      pass         Pass         Pass
155       0       0      fail         Fail         Fail
156       0       0      fail         Fail         Fail
157       1       1      pass         Pass         Pass
158       0       0      fail         Fail         Fail
159       1       1      pass         Pass         Pass
160       0       0      fail         Fail         Fail
161       0       0      fail         Fail         Fail
162       0       0      fail         Fail         Fail
163       0       0      fail         Fail         Fail
164       1       1      pass         Pass         Pass
165       1       1      pass         Pass         Pass
166       0       0      fail         Fail         Fail
167       0       0      fail         Fail         Fail
168       0       0      fail         Fail         Fail
169       1       1      pass         Pass         Pass
170       0       0      fail         Fail         Fail
171       1       1      pass         Pass         Pass
172       1       1      pass         Pass         Pass
173       1       1      pass         Pass         Pass
174       0       0      fail         Fail         Fail
175       0       0      fail         Fail         Fail
176       0       0      fail         Fail         Fail
177       0       0      fail         Fail         Fail
178       0       0      fail         Fail         Fail
179       0       0      fail         Fail         Fail
180       0       0      fail         Fail         Fail
181       0       0      fail         Fail         Fail
182       1       0      fail         Pass         Fail
183       1       1      pass         Pass         Pass
184       0       0      fail         Fail         Fail
185       1       1      pass         Pass         Pass
186       1       0      fail         Pass         Fail
187       1       1      pass         Pass         Pass
188       1       1      pass         Pass         Pass
189       1       1      pass         Pass         Pass
190       1       1      pass         Pass         Pass
191       1       1      pass         Pass         Pass
192       1       1      pass         Pass         Pass
193       0       0      fail         Fail         Fail
194       0       0      fail         Fail         Fail
195       0       0      fail         Fail         Fail
196       0       1      pass         Fail         Pass
197       0       1      pass         Fail         Pass
198       0       0      fail         Fail         Fail
199       0       0      fail         Fail         Fail
200       0       0      fail         Fail         Fail
201       0       0      fail         Fail         Fail
202       0       0      fail         Fail         Fail
203       0       0      fail         Fail         Fail
204       1       1      pass         Pass         Pass
205       0       1      pass         Fail         Pass
206       1       0      fail         Pass         Fail
207       0       0      fail         Fail         Fail
208       0       0      fail         Fail         Fail
209       0       0      fail         Fail         Fail
210       1       1      pass         Pass         Pass
211       0       0      fail         Fail         Fail
212       0       1      pass         Fail         Pass
213       0       0      fail         Fail         Fail
214       0       0      fail         Fail         Fail
215       0       1      pass         Fail         Pass
216       0       1      pass         Fail         Pass
217       0       0      fail         Fail         Fail
218       0       0      fail         Fail         Fail
219       0       0      fail         Fail         Fail
220       0       0      fail         Fail         Fail
221       0       0      fail         Fail         Fail
222       1       1      pass         Pass         Pass
223       1       1      pass         Pass         Pass
224       1       1      pass         Pass         Pass
225       0       0      fail         Fail         Fail
226       1       1      pass         Pass         Pass
227       0       0      fail         Fail         Fail
228       1       1      pass         Pass         Pass
229       0       1      pass         Fail         Pass
230       0       1      pass         Fail         Pass
231       1       1      pass         Pass         Pass
232       0       1      pass         Fail         Pass
233       1       1      pass         Pass         Pass
234       1       1      pass         Pass         Pass
235       0       1      pass         Fail         Pass
236       1       0      fail         Pass         Fail
237       0       1      pass         Fail         Pass
238       0       0      fail         Fail         Fail
239       0       1      pass         Fail         Pass
240       0       0      fail         Fail         Fail
241       1       1      pass         Pass         Pass
242       0       1      pass         Fail         Pass
243       0       0      fail         Fail         Fail
244       0       1      pass         Fail         Pass
245       0       0      fail         Fail         Fail
246       0       0      fail         Fail         Fail
247       0       0      fail         Fail         Fail
248       0       0      fail         Fail         Fail
249       0       0      fail         Fail         Fail
250       1       1      pass         Pass         Pass
251       0       0      fail         Fail         Fail
252       0       0      fail         Fail         Fail
253       0       0      fail         Fail         Fail
254       0       0      fail         Fail         Fail
255       0       0      fail         Fail         Fail
256       0       0      fail         Fail         Fail
257       1       0      fail         Pass         Fail
258       0       0      fail         Fail         Fail
259       0       0      fail         Fail         Fail
260       0       0      fail         Fail         Fail
261       1       1      pass         Pass         Pass
262       0       0      fail         Fail         Fail
263       0       0      fail         Fail         Fail
264       0       1      pass         Fail         Pass
265       0       0      fail         Fail         Fail
266       1       1      pass         Pass         Pass
267       1       1      pass         Pass         Pass
268       0       0      fail         Fail         Fail
269       1       1      pass         Pass         Pass
270       0       0      fail         Fail         Fail
271       1       1      pass         Pass         Pass
272       0       0      fail         Fail         Fail
273       0       1      pass         Fail         Pass
274       0       1      pass         Fail         Pass
275       0       0      fail         Fail         Fail
276       0       1      pass         Fail         Pass
277       0       1      pass         Fail         Pass
278       0       0      fail         Fail         Fail
279       1       1      pass         Pass         Pass
280       0       0      fail         Fail         Fail
281       1       1      pass         Pass         Pass
282       0       0      fail         Fail         Fail
283       0       1      pass         Fail         Pass
284       0       0      fail         Fail         Fail
285       0       0      fail         Fail         Fail
286       0       1      pass         Fail         Pass
287       1       1      pass         Pass         Pass
288       0       0      fail         Fail         Fail
289       0       0      fail         Fail         Fail
290       1       1      pass         Pass         Pass
291       1       1      pass         Pass         Pass
292       0       0      fail         Fail         Fail
293       0       0      fail         Fail         Fail
294       1       0      fail         Pass         Fail
295       1       1      pass         Pass         Pass
296       1       1      pass         Pass         Pass
297       1       1      pass         Pass         Pass
298       1       1      pass         Pass         Pass
299       1       1      pass         Pass         Pass
300       0       1      pass         Fail         Pass
301       0       0      fail         Fail         Fail
302       0       0      fail         Fail         Fail
303       1       1      pass         Pass         Pass
304       1       1      pass         Pass         Pass
305       0       0      fail         Fail         Fail
306       1       1      pass         Pass         Pass
307       1       1      pass         Pass         Pass
308       1       1      pass         Pass         Pass
309       0       0      fail         Fail         Fail
310       1       0      fail         Pass         Fail
311       1       1      pass         Pass         Pass
312       0       0      fail         Fail         Fail
313       0       1      pass         Fail         Pass
314       1       1      pass         Pass         Pass
315       0       0      fail         Fail         Fail
316       1       1      pass         Pass         Pass
317       1       1      pass         Pass         Pass
318       1       1      pass         Pass         Pass
319       1       1      pass         Pass         Pass
320       0       0      fail         Fail         Fail
321       0       0      fail         Fail         Fail
322       1       1      pass         Pass         Pass
323       0       0      fail         Fail         Fail
324       1       1      pass         Pass         Pass
325       1       1      pass         Pass         Pass
326       0       0      fail         Fail         Fail
327       0       0      fail         Fail         Fail
328       1       1      pass         Pass         Pass
329       1       1      pass         Pass         Pass
330       1       1      pass         Pass         Pass
331       1       1      pass         Pass         Pass
332       1       1      pass         Pass         Pass
333       0       0      fail         Fail         Fail
334       0       0      fail         Fail         Fail
335       1       1      pass         Pass         Pass
336       0       0      fail         Fail         Fail
337       1       1      pass         Pass         Pass
338       0       0      fail         Fail         Fail
339       0       1      pass         Fail         Pass
340       0       0      fail         Fail         Fail
341       0       0      fail         Fail         Fail
342       1       1      pass         Pass         Pass
343       1       1      pass         Pass         Pass
344       0       0      fail         Fail         Fail
345       0       0      fail         Fail         Fail
346       0       0      fail         Fail         Fail
347       0       0      fail         Fail         Fail
348       1       1      pass         Pass         Pass
349       1       1      pass         Pass         Pass
350       0       0      fail         Fail         Fail
351       0       0      fail         Fail         Fail
352       1       0      fail         Pass         Fail
353       1       1      pass         Pass         Pass
354       0       0      fail         Fail         Fail
355       0       0      fail         Fail         Fail

#### Getting the Finetuned-Adapters

In [ ]:
# Step 1: load fresh test data
import kagglehub
import pandas as pd
import os

path   = kagglehub.dataset_download("nbroad/persaude-corpus-2")
scores = pd.read_csv(os.path.join(path, "persuade_2.0_human_scores_demo_id_github.csv"))

PASS_THRESHOLD         = 4
scores["binary_score"] = (scores["holistic_essay_score"] >= PASS_THRESHOLD).astype(int)

print(f"Full dataset: {len(scores):,}")

Using Colab cache for faster access to the 'persaude-corpus-2' dataset.
Full dataset: 25,996

In [ ]:
# Step 2: sample 500 fresh essays
from sklearn.model_selection import train_test_split

fresh_test, _ = train_test_split(
    scores,
    train_size=1000,
    random_state=99,
    stratify=scores["binary_score"]
)
fresh_test = fresh_test.reset_index(drop=True)

print(f"Fresh test size: {len(fresh_test)}")
print(fresh_test["binary_score"].value_counts())

Fresh test size: 1000
binary_score
0    581
1    419
Name: count, dtype: int64

In [ ]:
#  Step 3: build prompts
X_fresh_prompts = pd.DataFrame(
    fresh_test.apply(generate_phi2_test_prompt, axis=1), columns=["text"]
)
y_true = fresh_test["binary_score"].values   #  this creates y_true

print(f"Prompts ready: {len(X_fresh_prompts)}")
print("Last 50 chars:", repr(X_fresh_prompts["text"].iloc[0][-50:]))
# should end with '\nOutput:'

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CodeGenTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Prompts ready: 1000
Last 50 chars: 'nse plates could drive on certain days and\nOutput:'

In [ ]:
# ── Step 4: predict — this creates y_pred and y_generated ────────────────────
y_pred, y_generated = predict_phi2(X_fresh_prompts, ft_model, tokenizer)

  0%|          | 0/1000 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
  0%|          | 1/1000 [00:00<13:05,  1.27it/s]

[  1/1000]  raw='pass'  →  Pass

  0%|          | 2/1000 [00:01<08:05,  2.06it/s]

[  2/1000]  raw='fail'  →  Fail

  0%|          | 3/1000 [00:01<06:28,  2.56it/s]

[  3/1000]  raw='fail'  →  Fail

  0%|          | 4/1000 [00:01<05:44,  2.89it/s]

[  4/1000]  raw='pass'  →  Pass

  0%|          | 5/1000 [00:01<05:20,  3.10it/s]

[  5/1000]  raw='fail'  →  Fail

  1%|          | 6/1000 [00:02<05:04,  3.27it/s]

[  6/1000]  raw='pass'  →  Pass

  1%|          | 7/1000 [00:02<04:56,  3.35it/s]

[  7/1000]  raw='pass'  →  Pass

  1%|          | 8/1000 [00:02<04:50,  3.41it/s]

[  8/1000]  raw='fail'  →  Fail

  1%|          | 9/1000 [00:03<04:48,  3.43it/s]

[  9/1000]  raw='fail'  →  Fail

  1%|          | 10/1000 [00:03<04:44,  3.48it/s]

[ 10/1000]  raw='fail'  →  Fail

  1%|          | 11/1000 [00:03<04:39,  3.54it/s]

[ 11/1000]  raw='fail'  →  Fail

  1%|          | 12/1000 [00:03<04:35,  3.58it/s]

[ 12/1000]  raw='fail'  →  Fail

  1%|▏         | 13/1000 [00:04<04:33,  3.61it/s]

[ 13/1000]  raw='pass'  →  Pass

  1%|▏         | 14/1000 [00:04<04:32,  3.62it/s]

[ 14/1000]  raw='fail'  →  Fail

  2%|▏         | 15/1000 [00:04<04:30,  3.64it/s]

[ 15/1000]  raw='pass'  →  Pass

  2%|▏         | 16/1000 [00:04<04:29,  3.65it/s]

[ 16/1000]  raw='pass'  →  Pass

  2%|▏         | 17/1000 [00:05<04:28,  3.66it/s]

[ 17/1000]  raw='pass'  →  Pass

  2%|▏         | 18/1000 [00:05<04:27,  3.67it/s]

[ 18/1000]  raw='fail'  →  Fail

  2%|▏         | 19/1000 [00:05<04:26,  3.69it/s]

[ 19/1000]  raw='pass'  →  Pass

  2%|▏         | 20/1000 [00:06<04:24,  3.70it/s]

[ 20/1000]  raw='pass'  →  Pass

  2%|▏         | 21/1000 [00:06<04:23,  3.72it/s]

[ 21/1000]  raw='fail'  →  Fail

  2%|▏         | 22/1000 [00:06<04:23,  3.72it/s]

[ 22/1000]  raw='pass'  →  Pass

  2%|▏         | 23/1000 [00:06<04:23,  3.70it/s]

[ 23/1000]  raw='pass'  →  Pass

  2%|▏         | 24/1000 [00:07<04:24,  3.70it/s]

[ 24/1000]  raw='pass'  →  Pass

  2%|▎         | 25/1000 [00:07<04:24,  3.69it/s]

[ 25/1000]  raw='fail'  →  Fail

  3%|▎         | 26/1000 [00:07<04:24,  3.69it/s]

[ 26/1000]  raw='pass'  →  Pass

  3%|▎         | 27/1000 [00:07<04:24,  3.68it/s]

[ 27/1000]  raw='pass'  →  Pass

  3%|▎         | 28/1000 [00:08<04:24,  3.68it/s]

[ 28/1000]  raw='fail'  →  Fail

  3%|▎         | 29/1000 [00:08<04:23,  3.68it/s]

[ 29/1000]  raw='pass'  →  Pass

  3%|▎         | 30/1000 [00:08<04:23,  3.68it/s]

[ 30/1000]  raw='pass'  →  Pass

  3%|▎         | 31/1000 [00:08<04:22,  3.69it/s]

[ 31/1000]  raw='pass'  →  Pass

  3%|▎         | 32/1000 [00:09<04:22,  3.69it/s]

[ 32/1000]  raw='pass'  →  Pass

  3%|▎         | 33/1000 [00:09<04:22,  3.69it/s]

[ 33/1000]  raw='pass'  →  Pass

  3%|▎         | 34/1000 [00:09<04:22,  3.68it/s]

[ 34/1000]  raw='fail'  →  Fail

  4%|▎         | 35/1000 [00:10<04:22,  3.68it/s]

[ 35/1000]  raw='pass'  →  Pass

  4%|▎         | 36/1000 [00:10<04:21,  3.69it/s]

[ 36/1000]  raw='fail'  →  Fail

  4%|▎         | 37/1000 [00:10<04:21,  3.69it/s]

[ 37/1000]  raw='pass'  →  Pass

  4%|▍         | 38/1000 [00:10<04:20,  3.69it/s]

[ 38/1000]  raw='fail'  →  Fail

  4%|▍         | 39/1000 [00:11<04:21,  3.68it/s]

[ 39/1000]  raw='fail'  →  Fail

  4%|▍         | 40/1000 [00:11<04:20,  3.69it/s]

[ 40/1000]  raw='pass'  →  Pass

  4%|▍         | 41/1000 [00:11<04:19,  3.69it/s]

[ 41/1000]  raw='fail'  →  Fail

  4%|▍         | 42/1000 [00:11<04:19,  3.69it/s]

[ 42/1000]  raw='fail'  →  Fail

  4%|▍         | 43/1000 [00:12<04:18,  3.70it/s]

[ 43/1000]  raw='fail'  →  Fail

  4%|▍         | 44/1000 [00:12<04:17,  3.71it/s]

[ 44/1000]  raw='fail'  →  Fail

  4%|▍         | 45/1000 [00:12<04:16,  3.72it/s]

[ 45/1000]  raw='fail'  →  Fail

  5%|▍         | 46/1000 [00:13<04:15,  3.73it/s]

[ 46/1000]  raw='fail'  →  Fail

  5%|▍         | 47/1000 [00:13<04:15,  3.73it/s]

[ 47/1000]  raw='fail'  →  Fail

  5%|▍         | 48/1000 [00:13<04:15,  3.72it/s]

[ 48/1000]  raw='fail'  →  Fail

  5%|▍         | 49/1000 [00:13<04:15,  3.72it/s]

[ 49/1000]  raw='fail'  →  Fail

  5%|▌         | 50/1000 [00:14<04:14,  3.73it/s]

[ 50/1000]  raw='fail'  →  Fail

  5%|▌         | 51/1000 [00:14<04:13,  3.74it/s]

[ 51/1000]  raw='pass'  →  Pass

  5%|▌         | 52/1000 [00:14<04:15,  3.71it/s]

[ 52/1000]  raw='fail'  →  Fail

  5%|▌         | 53/1000 [00:14<04:17,  3.68it/s]

[ 53/1000]  raw='pass'  →  Pass

  5%|▌         | 54/1000 [00:15<04:17,  3.68it/s]

[ 54/1000]  raw='pass'  →  Pass

  6%|▌         | 55/1000 [00:15<04:17,  3.67it/s]

[ 55/1000]  raw='pass'  →  Pass

  6%|▌         | 56/1000 [00:15<04:20,  3.63it/s]

[ 56/1000]  raw='pass'  →  Pass

  6%|▌         | 57/1000 [00:16<04:19,  3.64it/s]

[ 57/1000]  raw='fail'  →  Fail

  6%|▌         | 58/1000 [00:16<04:18,  3.65it/s]

[ 58/1000]  raw='pass'  →  Pass

  6%|▌         | 59/1000 [00:16<04:17,  3.66it/s]

[ 59/1000]  raw='pass'  →  Pass

  6%|▌         | 60/1000 [00:16<04:17,  3.65it/s]

[ 60/1000]  raw='pass'  →  Pass

  6%|▌         | 61/1000 [00:17<04:16,  3.66it/s]

[ 61/1000]  raw='pass'  →  Pass

  6%|▌         | 62/1000 [00:17<04:15,  3.67it/s]

[ 62/1000]  raw='fail'  →  Fail

  6%|▋         | 63/1000 [00:17<04:15,  3.67it/s]

[ 63/1000]  raw='fail'  →  Fail

  6%|▋         | 64/1000 [00:17<04:13,  3.69it/s]

[ 64/1000]  raw='pass'  →  Pass

  6%|▋         | 65/1000 [00:18<04:12,  3.71it/s]

[ 65/1000]  raw='pass'  →  Pass

  7%|▋         | 66/1000 [00:18<04:13,  3.69it/s]

[ 66/1000]  raw='fail'  →  Fail

  7%|▋         | 67/1000 [00:18<04:14,  3.66it/s]

[ 67/1000]  raw='pass'  →  Pass

  7%|▋         | 68/1000 [00:19<04:14,  3.67it/s]

[ 68/1000]  raw='fail'  →  Fail

  7%|▋         | 69/1000 [00:19<04:13,  3.67it/s]

[ 69/1000]  raw='fail'  →  Fail

  7%|▋         | 70/1000 [00:19<04:13,  3.66it/s]

[ 70/1000]  raw='fail'  →  Fail

  7%|▋         | 71/1000 [00:19<04:12,  3.67it/s]

[ 71/1000]  raw='fail'  →  Fail

  7%|▋         | 72/1000 [00:20<04:12,  3.67it/s]

[ 72/1000]  raw='fail'  →  Fail

  7%|▋         | 73/1000 [00:20<04:11,  3.69it/s]

[ 73/1000]  raw='fail'  →  Fail

  7%|▋         | 74/1000 [00:20<04:09,  3.71it/s]

[ 74/1000]  raw='pass'  →  Pass

  8%|▊         | 75/1000 [00:20<04:08,  3.73it/s]

[ 75/1000]  raw='pass'  →  Pass

  8%|▊         | 76/1000 [00:21<04:07,  3.74it/s]

[ 76/1000]  raw='fail'  →  Fail

  8%|▊         | 77/1000 [00:21<04:06,  3.75it/s]

[ 77/1000]  raw='fail'  →  Fail

  8%|▊         | 78/1000 [00:21<04:05,  3.75it/s]

[ 78/1000]  raw='pass'  →  Pass

  8%|▊         | 79/1000 [00:21<04:05,  3.76it/s]

[ 79/1000]  raw='pass'  →  Pass

  8%|▊         | 80/1000 [00:22<04:04,  3.76it/s]

[ 80/1000]  raw='pass'  →  Pass

  8%|▊         | 81/1000 [00:22<04:04,  3.76it/s]

[ 81/1000]  raw='pass'  →  Pass

  8%|▊         | 82/1000 [00:22<04:03,  3.77it/s]

[ 82/1000]  raw='pass'  →  Pass

  8%|▊         | 83/1000 [00:23<04:03,  3.77it/s]

[ 83/1000]  raw='fail'  →  Fail

  8%|▊         | 84/1000 [00:23<04:02,  3.78it/s]

[ 84/1000]  raw='pass'  →  Pass

  8%|▊         | 85/1000 [00:23<04:01,  3.78it/s]

[ 85/1000]  raw='fail'  →  Fail

  9%|▊         | 86/1000 [00:23<04:01,  3.79it/s]

[ 86/1000]  raw='fail'  →  Fail

  9%|▊         | 87/1000 [00:24<04:01,  3.78it/s]

[ 87/1000]  raw='pass'  →  Pass

  9%|▉         | 88/1000 [00:24<04:01,  3.78it/s]

[ 88/1000]  raw='pass'  →  Pass

  9%|▉         | 89/1000 [00:24<04:01,  3.78it/s]

[ 89/1000]  raw='fail'  →  Fail

  9%|▉         | 90/1000 [00:24<04:01,  3.77it/s]

[ 90/1000]  raw='fail'  →  Fail

  9%|▉         | 91/1000 [00:25<04:01,  3.77it/s]

[ 91/1000]  raw='pass'  →  Pass

  9%|▉         | 92/1000 [00:25<04:00,  3.77it/s]

[ 92/1000]  raw='pass'  →  Pass

  9%|▉         | 93/1000 [00:25<04:02,  3.74it/s]

[ 93/1000]  raw='fail'  →  Fail

  9%|▉         | 94/1000 [00:25<04:04,  3.71it/s]

[ 94/1000]  raw='fail'  →  Fail

 10%|▉         | 95/1000 [00:26<04:04,  3.69it/s]

[ 95/1000]  raw='fail'  →  Fail

 10%|▉         | 96/1000 [00:26<04:04,  3.69it/s]

[ 96/1000]  raw='fail'  →  Fail

 10%|▉         | 97/1000 [00:26<04:04,  3.69it/s]

[ 97/1000]  raw='fail'  →  Fail

 10%|▉         | 98/1000 [00:27<04:05,  3.67it/s]

[ 98/1000]  raw='fail'  →  Fail

 10%|▉         | 99/1000 [00:27<04:05,  3.66it/s]

[ 99/1000]  raw='pass'  →  Pass

 10%|█         | 100/1000 [00:27<04:08,  3.62it/s]

[100/1000]  raw='fail'  →  Fail

 10%|█         | 101/1000 [00:27<04:08,  3.62it/s]

[101/1000]  raw='fail'  →  Fail

 10%|█         | 102/1000 [00:28<04:07,  3.62it/s]

[102/1000]  raw='fail'  →  Fail

 10%|█         | 103/1000 [00:28<04:06,  3.64it/s]

[103/1000]  raw='pass'  →  Pass

 10%|█         | 104/1000 [00:28<04:05,  3.65it/s]

[104/1000]  raw='pass'  →  Pass

 10%|█         | 105/1000 [00:28<04:04,  3.66it/s]

[105/1000]  raw='fail'  →  Fail

 11%|█         | 106/1000 [00:29<04:03,  3.67it/s]

[106/1000]  raw='fail'  →  Fail

 11%|█         | 107/1000 [00:29<04:03,  3.67it/s]

[107/1000]  raw='pass'  →  Pass

 11%|█         | 108/1000 [00:29<04:02,  3.68it/s]

[108/1000]  raw='fail'  →  Fail

 11%|█         | 109/1000 [00:30<04:03,  3.67it/s]

[109/1000]  raw='pass'  →  Pass

 11%|█         | 110/1000 [00:30<04:01,  3.68it/s]

[110/1000]  raw='fail'  →  Fail

 11%|█         | 111/1000 [00:30<04:01,  3.69it/s]

[111/1000]  raw='pass'  →  Pass

 11%|█         | 112/1000 [00:30<04:00,  3.69it/s]

[112/1000]  raw='pass'  →  Pass

 11%|█▏        | 113/1000 [00:31<04:00,  3.69it/s]

[113/1000]  raw='pass'  →  Pass

 11%|█▏        | 114/1000 [00:31<03:59,  3.70it/s]

[114/1000]  raw='fail'  →  Fail

 12%|█▏        | 115/1000 [00:31<03:59,  3.70it/s]

[115/1000]  raw='pass'  →  Pass

 12%|█▏        | 116/1000 [00:31<03:58,  3.70it/s]

[116/1000]  raw='pass'  →  Pass

 12%|█▏        | 117/1000 [00:32<03:58,  3.71it/s]

[117/1000]  raw='fail'  →  Fail

 12%|█▏        | 118/1000 [00:32<03:57,  3.71it/s]

[118/1000]  raw='fail'  →  Fail

 12%|█▏        | 119/1000 [00:32<03:57,  3.72it/s]

[119/1000]  raw='pass'  →  Pass

 12%|█▏        | 120/1000 [00:33<03:56,  3.72it/s]

[120/1000]  raw='fail'  →  Fail

 12%|█▏        | 121/1000 [00:33<03:55,  3.73it/s]

[121/1000]  raw='fail'  →  Fail

 12%|█▏        | 122/1000 [00:33<03:55,  3.73it/s]

[122/1000]  raw='pass'  →  Pass

 12%|█▏        | 123/1000 [00:33<03:55,  3.73it/s]

[123/1000]  raw='fail'  →  Fail

 12%|█▏        | 124/1000 [00:34<03:55,  3.73it/s]

[124/1000]  raw='pass'  →  Pass

 12%|█▎        | 125/1000 [00:34<03:54,  3.72it/s]

[125/1000]  raw='pass'  →  Pass

 13%|█▎        | 126/1000 [00:34<03:54,  3.73it/s]

[126/1000]  raw='fail'  →  Fail

 13%|█▎        | 127/1000 [00:34<03:54,  3.73it/s]

[127/1000]  raw='fail'  →  Fail

 13%|█▎        | 128/1000 [00:35<03:53,  3.73it/s]

[128/1000]  raw='pass'  →  Pass

 13%|█▎        | 129/1000 [00:35<03:53,  3.73it/s]

[129/1000]  raw='fail'  →  Fail

 13%|█▎        | 130/1000 [00:35<03:53,  3.73it/s]

[130/1000]  raw='pass'  →  Pass

 13%|█▎        | 131/1000 [00:35<03:53,  3.73it/s]

[131/1000]  raw='fail'  →  Fail

 13%|█▎        | 132/1000 [00:36<03:52,  3.73it/s]

[132/1000]  raw='fail'  →  Fail

 13%|█▎        | 133/1000 [00:36<03:52,  3.73it/s]

[133/1000]  raw='pass'  →  Pass

 13%|█▎        | 134/1000 [00:36<03:52,  3.72it/s]

[134/1000]  raw='pass'  →  Pass

 14%|█▎        | 135/1000 [00:37<03:51,  3.73it/s]

[135/1000]  raw='fail'  →  Fail

 14%|█▎        | 136/1000 [00:37<03:51,  3.73it/s]

[136/1000]  raw='pass'  →  Pass

 14%|█▎        | 137/1000 [00:37<03:51,  3.73it/s]

[137/1000]  raw='fail'  →  Fail

 14%|█▍        | 138/1000 [00:37<03:51,  3.72it/s]

[138/1000]  raw='fail'  →  Fail

 14%|█▍        | 139/1000 [00:38<03:52,  3.70it/s]

[139/1000]  raw='fail'  →  Fail

 14%|█▍        | 140/1000 [00:38<03:52,  3.70it/s]

[140/1000]  raw='fail'  →  Fail

 14%|█▍        | 141/1000 [00:38<03:52,  3.69it/s]

[141/1000]  raw='pass'  →  Pass

 14%|█▍        | 142/1000 [00:38<03:51,  3.71it/s]

[142/1000]  raw='pass'  →  Pass

 14%|█▍        | 143/1000 [00:39<03:49,  3.74it/s]

[143/1000]  raw='fail'  →  Fail

 14%|█▍        | 144/1000 [00:39<03:50,  3.71it/s]

[144/1000]  raw='fail'  →  Fail

 14%|█▍        | 145/1000 [00:39<03:50,  3.71it/s]

[145/1000]  raw='pass'  →  Pass

 15%|█▍        | 146/1000 [00:40<03:48,  3.73it/s]

[146/1000]  raw='fail'  →  Fail

 15%|█▍        | 147/1000 [00:40<03:46,  3.76it/s]

[147/1000]  raw='fail'  →  Fail

 15%|█▍        | 148/1000 [00:40<03:47,  3.74it/s]

[148/1000]  raw='fail'  →  Fail

 15%|█▍        | 149/1000 [00:40<03:48,  3.72it/s]

[149/1000]  raw='fail'  →  Fail

 15%|█▌        | 150/1000 [00:41<03:46,  3.75it/s]

[150/1000]  raw='pass'  →  Pass

 15%|█▌        | 151/1000 [00:41<03:45,  3.76it/s]

[151/1000]  raw='fail'  →  Fail

 15%|█▌        | 152/1000 [00:41<03:44,  3.77it/s]

[152/1000]  raw='fail'  →  Fail

 15%|█▌        | 153/1000 [00:41<03:44,  3.78it/s]

[153/1000]  raw='pass'  →  Pass

 15%|█▌        | 154/1000 [00:42<03:43,  3.79it/s]

[154/1000]  raw='fail'  →  Fail

 16%|█▌        | 155/1000 [00:42<03:43,  3.79it/s]

[155/1000]  raw='fail'  →  Fail

 16%|█▌        | 156/1000 [00:42<03:43,  3.78it/s]

[156/1000]  raw='pass'  →  Pass

 16%|█▌        | 157/1000 [00:42<03:42,  3.78it/s]

[157/1000]  raw='pass'  →  Pass

 16%|█▌        | 158/1000 [00:43<03:42,  3.78it/s]

[158/1000]  raw='fail'  →  Fail

 16%|█▌        | 159/1000 [00:43<03:41,  3.79it/s]

[159/1000]  raw='fail'  →  Fail

 16%|█▌        | 160/1000 [00:43<03:42,  3.78it/s]

[160/1000]  raw='pass'  →  Pass

 16%|█▌        | 161/1000 [00:43<03:41,  3.78it/s]

[161/1000]  raw='pass'  →  Pass

 16%|█▌        | 162/1000 [00:44<03:41,  3.79it/s]

[162/1000]  raw='pass'  →  Pass

 16%|█▋        | 163/1000 [00:44<03:40,  3.80it/s]

[163/1000]  raw='fail'  →  Fail

 16%|█▋        | 164/1000 [00:44<03:40,  3.80it/s]

[164/1000]  raw='pass'  →  Pass

 16%|█▋        | 165/1000 [00:45<03:39,  3.81it/s]

[165/1000]  raw='fail'  →  Fail

 17%|█▋        | 166/1000 [00:45<03:39,  3.80it/s]

[166/1000]  raw='fail'  →  Fail

 17%|█▋        | 167/1000 [00:45<03:41,  3.77it/s]

[167/1000]  raw='pass'  →  Pass

 17%|█▋        | 168/1000 [00:45<03:41,  3.76it/s]

[168/1000]  raw='pass'  →  Pass

 17%|█▋        | 169/1000 [00:46<03:41,  3.75it/s]

[169/1000]  raw='pass'  →  Pass

 17%|█▋        | 170/1000 [00:46<03:41,  3.75it/s]

[170/1000]  raw='pass'  →  Pass

 17%|█▋        | 171/1000 [00:46<03:41,  3.75it/s]

[171/1000]  raw='fail'  →  Fail

 17%|█▋        | 172/1000 [00:46<03:41,  3.75it/s]

[172/1000]  raw='fail'  →  Fail

 17%|█▋        | 173/1000 [00:47<03:40,  3.75it/s]

[173/1000]  raw='pass'  →  Pass

 17%|█▋        | 174/1000 [00:47<03:40,  3.75it/s]

[174/1000]  raw='pass'  →  Pass

 18%|█▊        | 175/1000 [00:47<03:40,  3.75it/s]

[175/1000]  raw='pass'  →  Pass

 18%|█▊        | 176/1000 [00:47<03:40,  3.74it/s]

[176/1000]  raw='pass'  →  Pass

 18%|█▊        | 177/1000 [00:48<03:39,  3.74it/s]

[177/1000]  raw='pass'  →  Pass

 18%|█▊        | 178/1000 [00:48<03:39,  3.75it/s]

[178/1000]  raw='fail'  →  Fail

 18%|█▊        | 179/1000 [00:48<03:38,  3.75it/s]

[179/1000]  raw='fail'  →  Fail

 18%|█▊        | 180/1000 [00:49<03:38,  3.75it/s]

[180/1000]  raw='fail'  →  Fail

 18%|█▊        | 181/1000 [00:49<03:38,  3.75it/s]

[181/1000]  raw='fail'  →  Fail

 18%|█▊        | 182/1000 [00:49<03:38,  3.75it/s]

[182/1000]  raw='fail'  →  Fail

 18%|█▊        | 183/1000 [00:49<03:38,  3.75it/s]

[183/1000]  raw='pass'  →  Pass

 18%|█▊        | 184/1000 [00:50<03:38,  3.74it/s]

[184/1000]  raw='fail'  →  Fail

 18%|█▊        | 185/1000 [00:50<03:38,  3.74it/s]

[185/1000]  raw='fail'  →  Fail

 19%|█▊        | 186/1000 [00:50<03:37,  3.74it/s]

[186/1000]  raw='fail'  →  Fail

 19%|█▊        | 187/1000 [00:50<03:38,  3.72it/s]

[187/1000]  raw='pass'  →  Pass

 19%|█▉        | 188/1000 [00:51<03:39,  3.70it/s]

[188/1000]  raw='fail'  →  Fail

 19%|█▉        | 189/1000 [00:51<03:38,  3.71it/s]

[189/1000]  raw='fail'  →  Fail

 19%|█▉        | 190/1000 [00:51<03:38,  3.71it/s]

[190/1000]  raw='pass'  →  Pass

 19%|█▉        | 191/1000 [00:52<03:39,  3.69it/s]

[191/1000]  raw='pass'  →  Pass

 19%|█▉        | 192/1000 [00:52<03:38,  3.70it/s]

[192/1000]  raw='pass'  →  Pass

 19%|█▉        | 193/1000 [00:52<03:37,  3.72it/s]

[193/1000]  raw='fail'  →  Fail

 19%|█▉        | 194/1000 [00:52<03:36,  3.73it/s]

[194/1000]  raw='fail'  →  Fail

 20%|█▉        | 195/1000 [00:53<03:36,  3.72it/s]

[195/1000]  raw='pass'  →  Pass

 20%|█▉        | 196/1000 [00:53<03:36,  3.71it/s]

[196/1000]  raw='pass'  →  Pass

 20%|█▉        | 197/1000 [00:53<03:36,  3.71it/s]

[197/1000]  raw='pass'  →  Pass

 20%|█▉        | 198/1000 [00:53<03:36,  3.71it/s]

[198/1000]  raw='pass'  →  Pass

 20%|█▉        | 199/1000 [00:54<03:35,  3.71it/s]

[199/1000]  raw='pass'  →  Pass

 20%|██        | 200/1000 [00:54<03:35,  3.71it/s]

[200/1000]  raw='pass'  →  Pass

 20%|██        | 201/1000 [00:54<03:35,  3.71it/s]

[201/1000]  raw='pass'  →  Pass

 20%|██        | 202/1000 [00:54<03:35,  3.71it/s]

[202/1000]  raw='pass'  →  Pass

 20%|██        | 203/1000 [00:55<03:34,  3.71it/s]

[203/1000]  raw='pass'  →  Pass

 20%|██        | 204/1000 [00:55<03:34,  3.72it/s]

[204/1000]  raw='fail'  →  Fail

 20%|██        | 205/1000 [00:55<03:33,  3.72it/s]

[205/1000]  raw='pass'  →  Pass

 21%|██        | 206/1000 [00:56<03:33,  3.72it/s]

[206/1000]  raw='pass'  →  Pass

 21%|██        | 207/1000 [00:56<03:31,  3.75it/s]

[207/1000]  raw='fail'  →  Fail

 21%|██        | 208/1000 [00:56<03:31,  3.74it/s]

[208/1000]  raw='fail'  →  Fail

 21%|██        | 209/1000 [00:56<03:31,  3.73it/s]

[209/1000]  raw='fail'  →  Fail

 21%|██        | 210/1000 [00:57<03:31,  3.73it/s]

[210/1000]  raw='pass'  →  Pass

 21%|██        | 211/1000 [00:57<03:31,  3.74it/s]

[211/1000]  raw='fail'  →  Fail

 21%|██        | 212/1000 [00:57<03:31,  3.73it/s]

[212/1000]  raw='fail'  →  Fail

 21%|██▏       | 213/1000 [00:57<03:32,  3.71it/s]

[213/1000]  raw='fail'  →  Fail

 21%|██▏       | 214/1000 [00:58<03:31,  3.71it/s]

[214/1000]  raw='pass'  →  Pass

 22%|██▏       | 215/1000 [00:58<03:31,  3.71it/s]

[215/1000]  raw='pass'  →  Pass

 22%|██▏       | 216/1000 [00:58<03:31,  3.71it/s]

[216/1000]  raw='pass'  →  Pass

 22%|██▏       | 217/1000 [00:58<03:30,  3.72it/s]

[217/1000]  raw='fail'  →  Fail

 22%|██▏       | 218/1000 [00:59<03:29,  3.73it/s]

[218/1000]  raw='pass'  →  Pass

 22%|██▏       | 219/1000 [00:59<03:29,  3.73it/s]

[219/1000]  raw='pass'  →  Pass

 22%|██▏       | 220/1000 [00:59<03:29,  3.73it/s]

[220/1000]  raw='pass'  →  Pass

 22%|██▏       | 221/1000 [01:00<03:28,  3.73it/s]

[221/1000]  raw='pass'  →  Pass

 22%|██▏       | 222/1000 [01:00<03:28,  3.73it/s]

[222/1000]  raw='pass'  →  Pass

 22%|██▏       | 223/1000 [01:00<03:28,  3.72it/s]

[223/1000]  raw='pass'  →  Pass

 22%|██▏       | 224/1000 [01:00<03:28,  3.73it/s]

[224/1000]  raw='fail'  →  Fail

 22%|██▎       | 225/1000 [01:01<03:27,  3.74it/s]

[225/1000]  raw='fail'  →  Fail

 23%|██▎       | 226/1000 [01:01<03:26,  3.74it/s]

[226/1000]  raw='pass'  →  Pass

 23%|██▎       | 227/1000 [01:01<03:26,  3.74it/s]

[227/1000]  raw='pass'  →  Pass

 23%|██▎       | 228/1000 [01:01<03:26,  3.74it/s]

[228/1000]  raw='pass'  →  Pass

 23%|██▎       | 229/1000 [01:02<03:25,  3.75it/s]

[229/1000]  raw='fail'  →  Fail

 23%|██▎       | 230/1000 [01:02<03:25,  3.74it/s]

[230/1000]  raw='fail'  →  Fail

 23%|██▎       | 231/1000 [01:02<03:26,  3.73it/s]

[231/1000]  raw='pass'  →  Pass

 23%|██▎       | 232/1000 [01:03<03:25,  3.73it/s]

[232/1000]  raw='pass'  →  Pass

 23%|██▎       | 233/1000 [01:03<03:25,  3.73it/s]

[233/1000]  raw='fail'  →  Fail

 23%|██▎       | 234/1000 [01:03<03:26,  3.72it/s]

[234/1000]  raw='pass'  →  Pass

 24%|██▎       | 235/1000 [01:03<03:26,  3.71it/s]

[235/1000]  raw='pass'  →  Pass

 24%|██▎       | 236/1000 [01:04<03:25,  3.72it/s]

[236/1000]  raw='pass'  →  Pass

 24%|██▎       | 237/1000 [01:04<03:24,  3.72it/s]

[237/1000]  raw='fail'  →  Fail

 24%|██▍       | 238/1000 [01:04<03:25,  3.70it/s]

[238/1000]  raw='pass'  →  Pass

 24%|██▍       | 239/1000 [01:04<03:25,  3.70it/s]

[239/1000]  raw='fail'  →  Fail

 24%|██▍       | 240/1000 [01:05<03:25,  3.70it/s]

[240/1000]  raw='pass'  →  Pass

 24%|██▍       | 241/1000 [01:05<03:25,  3.69it/s]

[241/1000]  raw='fail'  →  Fail

 24%|██▍       | 242/1000 [01:05<03:25,  3.69it/s]

[242/1000]  raw='fail'  →  Fail

 24%|██▍       | 243/1000 [01:05<03:25,  3.68it/s]

[243/1000]  raw='fail'  →  Fail

 24%|██▍       | 244/1000 [01:06<03:25,  3.68it/s]

[244/1000]  raw='pass'  →  Pass

 24%|██▍       | 245/1000 [01:06<03:24,  3.69it/s]

[245/1000]  raw='pass'  →  Pass

 25%|██▍       | 246/1000 [01:06<03:24,  3.69it/s]

[246/1000]  raw='pass'  →  Pass

 25%|██▍       | 247/1000 [01:07<03:23,  3.70it/s]

[247/1000]  raw='fail'  →  Fail

 25%|██▍       | 248/1000 [01:07<03:23,  3.70it/s]

[248/1000]  raw='fail'  →  Fail

 25%|██▍       | 249/1000 [01:07<03:22,  3.71it/s]

[249/1000]  raw='fail'  →  Fail

 25%|██▌       | 250/1000 [01:07<03:21,  3.71it/s]

[250/1000]  raw='pass'  →  Pass

 25%|██▌       | 251/1000 [01:08<03:21,  3.72it/s]

[251/1000]  raw='fail'  →  Fail

 25%|██▌       | 252/1000 [01:08<03:20,  3.72it/s]

[252/1000]  raw='pass'  →  Pass

 25%|██▌       | 253/1000 [01:08<03:20,  3.72it/s]

[253/1000]  raw='pass'  →  Pass

 25%|██▌       | 254/1000 [01:08<03:20,  3.71it/s]

[254/1000]  raw='fail'  →  Fail

 26%|██▌       | 255/1000 [01:09<03:20,  3.71it/s]

[255/1000]  raw='fail'  →  Fail

 26%|██▌       | 256/1000 [01:09<03:20,  3.71it/s]

[256/1000]  raw='pass'  →  Pass

 26%|██▌       | 257/1000 [01:09<03:20,  3.70it/s]

[257/1000]  raw='pass'  →  Pass

 26%|██▌       | 258/1000 [01:10<03:20,  3.71it/s]

[258/1000]  raw='pass'  →  Pass

 26%|██▌       | 259/1000 [01:10<03:19,  3.71it/s]

[259/1000]  raw='fail'  →  Fail

 26%|██▌       | 260/1000 [01:10<03:19,  3.71it/s]

[260/1000]  raw='fail'  →  Fail

 26%|██▌       | 261/1000 [01:10<03:19,  3.70it/s]

[261/1000]  raw='pass'  →  Pass

 26%|██▌       | 262/1000 [01:11<03:19,  3.70it/s]

[262/1000]  raw='pass'  →  Pass

 26%|██▋       | 263/1000 [01:11<03:19,  3.70it/s]

[263/1000]  raw='pass'  →  Pass

 26%|██▋       | 264/1000 [01:11<03:19,  3.69it/s]

[264/1000]  raw='pass'  →  Pass

 26%|██▋       | 265/1000 [01:11<03:18,  3.70it/s]

[265/1000]  raw='fail'  →  Fail

 27%|██▋       | 266/1000 [01:12<03:18,  3.69it/s]

[266/1000]  raw='pass'  →  Pass

 27%|██▋       | 267/1000 [01:12<03:18,  3.70it/s]

[267/1000]  raw='pass'  →  Pass

 27%|██▋       | 268/1000 [01:12<03:18,  3.69it/s]

[268/1000]  raw='fail'  →  Fail

 27%|██▋       | 269/1000 [01:13<03:17,  3.69it/s]

[269/1000]  raw='pass'  →  Pass

 27%|██▋       | 270/1000 [01:13<03:17,  3.70it/s]

[270/1000]  raw='fail'  →  Fail

 27%|██▋       | 271/1000 [01:13<03:16,  3.71it/s]

[271/1000]  raw='pass'  →  Pass

 27%|██▋       | 272/1000 [01:13<03:16,  3.71it/s]

[272/1000]  raw='pass'  →  Pass

 27%|██▋       | 273/1000 [01:14<03:16,  3.71it/s]

[273/1000]  raw='pass'  →  Pass

 27%|██▋       | 274/1000 [01:14<03:15,  3.71it/s]

[274/1000]  raw='fail'  →  Fail

 28%|██▊       | 275/1000 [01:14<03:15,  3.71it/s]

[275/1000]  raw='fail'  →  Fail

 28%|██▊       | 276/1000 [01:14<03:16,  3.69it/s]

[276/1000]  raw='pass'  →  Pass

 28%|██▊       | 277/1000 [01:15<03:15,  3.70it/s]

[277/1000]  raw='fail'  →  Fail

 28%|██▊       | 278/1000 [01:15<03:15,  3.69it/s]

[278/1000]  raw='fail'  →  Fail

 28%|██▊       | 279/1000 [01:15<03:15,  3.69it/s]

[279/1000]  raw='fail'  →  Fail

 28%|██▊       | 280/1000 [01:15<03:16,  3.66it/s]

[280/1000]  raw='pass'  →  Pass

 28%|██▊       | 281/1000 [01:16<03:16,  3.67it/s]

[281/1000]  raw='pass'  →  Pass

 28%|██▊       | 282/1000 [01:16<03:15,  3.68it/s]

[282/1000]  raw='fail'  →  Fail

 28%|██▊       | 283/1000 [01:16<03:15,  3.68it/s]

[283/1000]  raw='pass'  →  Pass

 28%|██▊       | 284/1000 [01:17<03:14,  3.68it/s]

[284/1000]  raw='fail'  →  Fail

 28%|██▊       | 285/1000 [01:17<03:13,  3.69it/s]

[285/1000]  raw='fail'  →  Fail

 29%|██▊       | 286/1000 [01:17<03:13,  3.69it/s]

[286/1000]  raw='fail'  →  Fail

 29%|██▊       | 287/1000 [01:17<03:12,  3.71it/s]

[287/1000]  raw='pass'  →  Pass

 29%|██▉       | 288/1000 [01:18<03:12,  3.70it/s]

[288/1000]  raw='pass'  →  Pass

 29%|██▉       | 289/1000 [01:18<03:12,  3.70it/s]

[289/1000]  raw='pass'  →  Pass

 29%|██▉       | 290/1000 [01:18<03:11,  3.70it/s]

[290/1000]  raw='pass'  →  Pass

 29%|██▉       | 291/1000 [01:18<03:10,  3.72it/s]

[291/1000]  raw='pass'  →  Pass

 29%|██▉       | 292/1000 [01:19<03:10,  3.72it/s]

[292/1000]  raw='pass'  →  Pass

 29%|██▉       | 293/1000 [01:19<03:09,  3.72it/s]

[293/1000]  raw='fail'  →  Fail

 29%|██▉       | 294/1000 [01:19<03:09,  3.72it/s]

[294/1000]  raw='pass'  →  Pass

 30%|██▉       | 295/1000 [01:20<03:09,  3.72it/s]

[295/1000]  raw='pass'  →  Pass

 30%|██▉       | 296/1000 [01:20<03:09,  3.72it/s]

[296/1000]  raw='pass'  →  Pass

 30%|██▉       | 297/1000 [01:20<03:08,  3.73it/s]

[297/1000]  raw='pass'  →  Pass

 30%|██▉       | 298/1000 [01:20<03:08,  3.73it/s]

[298/1000]  raw='fail'  →  Fail

 30%|██▉       | 299/1000 [01:21<03:07,  3.73it/s]

[299/1000]  raw='fail'  →  Fail

 30%|███       | 300/1000 [01:21<03:07,  3.74it/s]

[300/1000]  raw='pass'  →  Pass

 30%|███       | 301/1000 [01:21<03:07,  3.74it/s]

[301/1000]  raw='pass'  →  Pass

 30%|███       | 302/1000 [01:21<03:06,  3.74it/s]

[302/1000]  raw='pass'  →  Pass

 30%|███       | 303/1000 [01:22<03:06,  3.74it/s]

[303/1000]  raw='fail'  →  Fail

 30%|███       | 304/1000 [01:22<03:06,  3.74it/s]

[304/1000]  raw='fail'  →  Fail

 30%|███       | 305/1000 [01:22<03:05,  3.74it/s]

[305/1000]  raw='pass'  →  Pass

 31%|███       | 306/1000 [01:22<03:05,  3.74it/s]

[306/1000]  raw='pass'  →  Pass

 31%|███       | 307/1000 [01:23<03:05,  3.74it/s]

[307/1000]  raw='pass'  →  Pass

 31%|███       | 308/1000 [01:23<03:04,  3.75it/s]

[308/1000]  raw='fail'  →  Fail

 31%|███       | 309/1000 [01:23<03:03,  3.76it/s]

[309/1000]  raw='fail'  →  Fail

 31%|███       | 310/1000 [01:24<03:03,  3.75it/s]

[310/1000]  raw='fail'  →  Fail

 31%|███       | 311/1000 [01:24<03:03,  3.75it/s]

[311/1000]  raw='pass'  →  Pass

 31%|███       | 312/1000 [01:24<03:03,  3.74it/s]

[312/1000]  raw='pass'  →  Pass

 31%|███▏      | 313/1000 [01:24<03:03,  3.75it/s]

[313/1000]  raw='fail'  →  Fail

 31%|███▏      | 314/1000 [01:25<03:03,  3.75it/s]

[314/1000]  raw='pass'  →  Pass

 32%|███▏      | 315/1000 [01:25<03:02,  3.75it/s]

[315/1000]  raw='pass'  →  Pass

 32%|███▏      | 316/1000 [01:25<03:02,  3.74it/s]

[316/1000]  raw='fail'  →  Fail

 32%|███▏      | 317/1000 [01:25<03:02,  3.74it/s]

[317/1000]  raw='pass'  →  Pass

 32%|███▏      | 318/1000 [01:26<03:02,  3.74it/s]

[318/1000]  raw='fail'  →  Fail

 32%|███▏      | 319/1000 [01:26<03:01,  3.74it/s]

[319/1000]  raw='fail'  →  Fail

 32%|███▏      | 320/1000 [01:26<03:01,  3.74it/s]

[320/1000]  raw='fail'  →  Fail

 32%|███▏      | 321/1000 [01:26<03:01,  3.74it/s]

[321/1000]  raw='pass'  →  Pass

 32%|███▏      | 322/1000 [01:27<03:01,  3.74it/s]

[322/1000]  raw='pass'  →  Pass

 32%|███▏      | 323/1000 [01:27<03:01,  3.74it/s]

[323/1000]  raw='fail'  →  Fail

 32%|███▏      | 324/1000 [01:27<03:00,  3.74it/s]

[324/1000]  raw='fail'  →  Fail

 32%|███▎      | 325/1000 [01:28<03:00,  3.74it/s]

[325/1000]  raw='fail'  →  Fail

 33%|███▎      | 326/1000 [01:28<03:00,  3.73it/s]

[326/1000]  raw='fail'  →  Fail

 33%|███▎      | 327/1000 [01:28<03:01,  3.70it/s]

[327/1000]  raw='fail'  →  Fail

 33%|███▎      | 328/1000 [01:28<03:01,  3.71it/s]

[328/1000]  raw='fail'  →  Fail

 33%|███▎      | 329/1000 [01:29<03:00,  3.71it/s]

[329/1000]  raw='fail'  →  Fail

 33%|███▎      | 330/1000 [01:29<03:01,  3.70it/s]

[330/1000]  raw='pass'  →  Pass

 33%|███▎      | 331/1000 [01:29<03:00,  3.70it/s]

[331/1000]  raw='fail'  →  Fail

 33%|███▎      | 332/1000 [01:29<03:01,  3.69it/s]

[332/1000]  raw='pass'  →  Pass

 33%|███▎      | 333/1000 [01:30<03:00,  3.69it/s]

[333/1000]  raw='pass'  →  Pass

 33%|███▎      | 334/1000 [01:30<02:59,  3.70it/s]

[334/1000]  raw='fail'  →  Fail

 34%|███▎      | 335/1000 [01:30<02:59,  3.70it/s]

[335/1000]  raw='pass'  →  Pass

 34%|███▎      | 336/1000 [01:31<02:59,  3.69it/s]

[336/1000]  raw='fail'  →  Fail

 34%|███▎      | 337/1000 [01:31<02:59,  3.69it/s]

[337/1000]  raw='fail'  →  Fail

 34%|███▍      | 338/1000 [01:31<02:59,  3.69it/s]

[338/1000]  raw='fail'  →  Fail

 34%|███▍      | 339/1000 [01:31<02:59,  3.68it/s]

[339/1000]  raw='fail'  →  Fail

 34%|███▍      | 340/1000 [01:32<02:59,  3.69it/s]

[340/1000]  raw='pass'  →  Pass

 34%|███▍      | 341/1000 [01:32<02:58,  3.69it/s]

[341/1000]  raw='pass'  →  Pass

 34%|███▍      | 342/1000 [01:32<02:57,  3.70it/s]

[342/1000]  raw='fail'  →  Fail

 34%|███▍      | 343/1000 [01:32<02:57,  3.70it/s]

[343/1000]  raw='pass'  →  Pass

 34%|███▍      | 344/1000 [01:33<02:57,  3.71it/s]

[344/1000]  raw='fail'  →  Fail

 34%|███▍      | 345/1000 [01:33<02:57,  3.70it/s]

[345/1000]  raw='pass'  →  Pass

 35%|███▍      | 346/1000 [01:33<02:57,  3.69it/s]

[346/1000]  raw='pass'  →  Pass

 35%|███▍      | 347/1000 [01:34<02:56,  3.70it/s]

[347/1000]  raw='fail'  →  Fail

 35%|███▍      | 348/1000 [01:34<02:56,  3.70it/s]

[348/1000]  raw='fail'  →  Fail

 35%|███▍      | 349/1000 [01:34<02:55,  3.71it/s]

[349/1000]  raw='pass'  →  Pass

 35%|███▌      | 350/1000 [01:34<02:55,  3.69it/s]

[350/1000]  raw='pass'  →  Pass

 35%|███▌      | 351/1000 [01:35<02:55,  3.70it/s]

[351/1000]  raw='fail'  →  Fail

 35%|███▌      | 352/1000 [01:35<02:54,  3.71it/s]

[352/1000]  raw='fail'  →  Fail

 35%|███▌      | 353/1000 [01:35<02:53,  3.72it/s]

[353/1000]  raw='fail'  →  Fail

 35%|███▌      | 354/1000 [01:35<02:54,  3.71it/s]

[354/1000]  raw='fail'  →  Fail

 36%|███▌      | 355/1000 [01:36<02:53,  3.71it/s]

[355/1000]  raw='fail'  →  Fail

 36%|███▌      | 356/1000 [01:36<02:53,  3.71it/s]

[356/1000]  raw='pass'  →  Pass

 36%|███▌      | 357/1000 [01:36<02:53,  3.71it/s]

[357/1000]  raw='pass'  →  Pass

 36%|███▌      | 358/1000 [01:36<02:53,  3.70it/s]

[358/1000]  raw='pass'  →  Pass

 36%|███▌      | 359/1000 [01:37<02:53,  3.70it/s]

[359/1000]  raw='fail'  →  Fail

 36%|███▌      | 360/1000 [01:37<02:52,  3.70it/s]

[360/1000]  raw='fail'  →  Fail

 36%|███▌      | 361/1000 [01:37<02:53,  3.69it/s]

[361/1000]  raw='pass'  →  Pass

 36%|███▌      | 362/1000 [01:38<02:53,  3.68it/s]

[362/1000]  raw='fail'  →  Fail

 36%|███▋      | 363/1000 [01:38<02:52,  3.69it/s]

[363/1000]  raw='pass'  →  Pass

 36%|███▋      | 364/1000 [01:38<02:52,  3.69it/s]

[364/1000]  raw='fail'  →  Fail

 36%|███▋      | 365/1000 [01:38<02:52,  3.68it/s]

[365/1000]  raw='pass'  →  Pass

 37%|███▋      | 366/1000 [01:39<02:52,  3.68it/s]

[366/1000]  raw='fail'  →  Fail

 37%|███▋      | 367/1000 [01:39<02:52,  3.67it/s]

[367/1000]  raw='fail'  →  Fail

 37%|███▋      | 368/1000 [01:39<02:52,  3.65it/s]

[368/1000]  raw='pass'  →  Pass

 37%|███▋      | 369/1000 [01:39<02:51,  3.68it/s]

[369/1000]  raw='fail'  →  Fail

 37%|███▋      | 370/1000 [01:40<02:51,  3.67it/s]

[370/1000]  raw='fail'  →  Fail

 37%|███▋      | 371/1000 [01:40<02:51,  3.67it/s]

[371/1000]  raw='pass'  →  Pass

 37%|███▋      | 372/1000 [01:40<02:51,  3.67it/s]

[372/1000]  raw='fail'  →  Fail

 37%|███▋      | 373/1000 [01:41<02:51,  3.65it/s]

[373/1000]  raw='fail'  →  Fail

 37%|███▋      | 374/1000 [01:41<02:50,  3.67it/s]

[374/1000]  raw='pass'  →  Pass

 38%|███▊      | 375/1000 [01:41<02:49,  3.68it/s]

[375/1000]  raw='pass'  →  Pass

 38%|███▊      | 376/1000 [01:41<02:49,  3.68it/s]

[376/1000]  raw='fail'  →  Fail

 38%|███▊      | 377/1000 [01:42<02:48,  3.69it/s]

[377/1000]  raw='pass'  →  Pass

 38%|███▊      | 378/1000 [01:42<02:48,  3.69it/s]

[378/1000]  raw='fail'  →  Fail

 38%|███▊      | 379/1000 [01:42<02:47,  3.70it/s]

[379/1000]  raw='fail'  →  Fail

 38%|███▊      | 380/1000 [01:42<02:47,  3.70it/s]

[380/1000]  raw='pass'  →  Pass

 38%|███▊      | 381/1000 [01:43<02:47,  3.69it/s]

[381/1000]  raw='fail'  →  Fail

 38%|███▊      | 382/1000 [01:43<02:47,  3.68it/s]

[382/1000]  raw='fail'  →  Fail

 38%|███▊      | 383/1000 [01:43<02:47,  3.69it/s]

[383/1000]  raw='pass'  →  Pass

 38%|███▊      | 384/1000 [01:44<02:47,  3.69it/s]

[384/1000]  raw='fail'  →  Fail

 38%|███▊      | 385/1000 [01:44<02:46,  3.69it/s]

[385/1000]  raw='fail'  →  Fail

 39%|███▊      | 386/1000 [01:44<02:46,  3.69it/s]

[386/1000]  raw='fail'  →  Fail

 39%|███▊      | 387/1000 [01:44<02:45,  3.69it/s]

[387/1000]  raw='fail'  →  Fail

 39%|███▉      | 388/1000 [01:45<02:45,  3.69it/s]

[388/1000]  raw='fail'  →  Fail

 39%|███▉      | 389/1000 [01:45<02:45,  3.70it/s]

[389/1000]  raw='fail'  →  Fail

 39%|███▉      | 390/1000 [01:45<02:44,  3.71it/s]

[390/1000]  raw='fail'  →  Fail

 39%|███▉      | 391/1000 [01:45<02:44,  3.71it/s]

[391/1000]  raw='fail'  →  Fail

 39%|███▉      | 392/1000 [01:46<02:43,  3.71it/s]

[392/1000]  raw='fail'  →  Fail

 39%|███▉      | 393/1000 [01:46<02:43,  3.70it/s]

[393/1000]  raw='pass'  →  Pass

 39%|███▉      | 394/1000 [01:46<02:43,  3.70it/s]

[394/1000]  raw='fail'  →  Fail

 40%|███▉      | 395/1000 [01:47<02:43,  3.70it/s]

[395/1000]  raw='pass'  →  Pass

 40%|███▉      | 396/1000 [01:47<02:43,  3.70it/s]

[396/1000]  raw='pass'  →  Pass

 40%|███▉      | 397/1000 [01:47<02:42,  3.70it/s]

[397/1000]  raw='pass'  →  Pass

 40%|███▉      | 398/1000 [01:47<02:42,  3.71it/s]

[398/1000]  raw='fail'  →  Fail

 40%|███▉      | 399/1000 [01:48<02:42,  3.71it/s]

[399/1000]  raw='pass'  →  Pass

 40%|████      | 400/1000 [01:48<02:41,  3.72it/s]

[400/1000]  raw='fail'  →  Fail

 40%|████      | 401/1000 [01:48<02:40,  3.72it/s]

[401/1000]  raw='pass'  →  Pass

 40%|████      | 402/1000 [01:48<02:40,  3.73it/s]

[402/1000]  raw='fail'  →  Fail

 40%|████      | 403/1000 [01:49<02:39,  3.74it/s]

[403/1000]  raw='fail'  →  Fail

 40%|████      | 404/1000 [01:49<02:39,  3.73it/s]

[404/1000]  raw='fail'  →  Fail

 40%|████      | 405/1000 [01:49<02:39,  3.73it/s]

[405/1000]  raw='fail'  →  Fail

 41%|████      | 406/1000 [01:49<02:39,  3.74it/s]

[406/1000]  raw='fail'  →  Fail

 41%|████      | 407/1000 [01:50<02:38,  3.73it/s]

[407/1000]  raw='fail'  →  Fail

 41%|████      | 408/1000 [01:50<02:39,  3.72it/s]

[408/1000]  raw='fail'  →  Fail

 41%|████      | 409/1000 [01:50<02:39,  3.71it/s]

[409/1000]  raw='pass'  →  Pass

 41%|████      | 410/1000 [01:51<02:39,  3.71it/s]

[410/1000]  raw='pass'  →  Pass

 41%|████      | 411/1000 [01:51<02:38,  3.71it/s]

[411/1000]  raw='fail'  →  Fail

 41%|████      | 412/1000 [01:51<02:38,  3.71it/s]

[412/1000]  raw='pass'  →  Pass

 41%|████▏     | 413/1000 [01:51<02:37,  3.72it/s]

[413/1000]  raw='pass'  →  Pass

 41%|████▏     | 414/1000 [01:52<02:37,  3.72it/s]

[414/1000]  raw='pass'  →  Pass

 42%|████▏     | 415/1000 [01:52<02:36,  3.73it/s]

[415/1000]  raw='pass'  →  Pass

 42%|████▏     | 416/1000 [01:52<02:36,  3.74it/s]

[416/1000]  raw='pass'  →  Pass

 42%|████▏     | 417/1000 [01:52<02:35,  3.75it/s]

[417/1000]  raw='fail'  →  Fail

 42%|████▏     | 418/1000 [01:53<02:35,  3.75it/s]

[418/1000]  raw='pass'  →  Pass

 42%|████▏     | 419/1000 [01:53<02:35,  3.73it/s]

[419/1000]  raw='fail'  →  Fail

 42%|████▏     | 420/1000 [01:53<02:36,  3.71it/s]

[420/1000]  raw='fail'  →  Fail

 42%|████▏     | 421/1000 [01:53<02:36,  3.70it/s]

[421/1000]  raw='fail'  →  Fail

 42%|████▏     | 422/1000 [01:54<02:36,  3.70it/s]

[422/1000]  raw='fail'  →  Fail

 42%|████▏     | 423/1000 [01:54<02:36,  3.69it/s]

[423/1000]  raw='pass'  →  Pass

 42%|████▏     | 424/1000 [01:54<02:36,  3.68it/s]

[424/1000]  raw='pass'  →  Pass

 42%|████▎     | 425/1000 [01:55<02:35,  3.69it/s]

[425/1000]  raw='fail'  →  Fail

 43%|████▎     | 426/1000 [01:55<02:35,  3.69it/s]

[426/1000]  raw='fail'  →  Fail

 43%|████▎     | 427/1000 [01:55<02:35,  3.69it/s]

[427/1000]  raw='pass'  →  Pass

 43%|████▎     | 428/1000 [01:55<02:35,  3.68it/s]

[428/1000]  raw='fail'  →  Fail

 43%|████▎     | 429/1000 [01:56<02:35,  3.68it/s]

[429/1000]  raw='pass'  →  Pass

 43%|████▎     | 430/1000 [01:56<02:34,  3.68it/s]

[430/1000]  raw='fail'  →  Fail

 43%|████▎     | 431/1000 [01:56<02:34,  3.69it/s]

[431/1000]  raw='pass'  →  Pass

 43%|████▎     | 432/1000 [01:56<02:34,  3.69it/s]

[432/1000]  raw='pass'  →  Pass

 43%|████▎     | 433/1000 [01:57<02:33,  3.69it/s]

[433/1000]  raw='pass'  →  Pass

 43%|████▎     | 434/1000 [01:57<02:33,  3.69it/s]

[434/1000]  raw='pass'  →  Pass

 44%|████▎     | 435/1000 [01:57<02:33,  3.69it/s]

[435/1000]  raw='fail'  →  Fail

 44%|████▎     | 436/1000 [01:58<02:32,  3.69it/s]

[436/1000]  raw='fail'  →  Fail

 44%|████▎     | 437/1000 [01:58<02:32,  3.69it/s]

[437/1000]  raw='fail'  →  Fail

 44%|████▍     | 438/1000 [01:58<02:32,  3.69it/s]

[438/1000]  raw='pass'  →  Pass

 44%|████▍     | 439/1000 [01:58<02:32,  3.68it/s]

[439/1000]  raw='pass'  →  Pass

 44%|████▍     | 440/1000 [01:59<02:32,  3.68it/s]

[440/1000]  raw='fail'  →  Fail

 44%|████▍     | 441/1000 [01:59<02:31,  3.68it/s]

[441/1000]  raw='pass'  →  Pass

 44%|████▍     | 442/1000 [01:59<02:31,  3.68it/s]

[442/1000]  raw='pass'  →  Pass

 44%|████▍     | 443/1000 [01:59<02:31,  3.69it/s]

[443/1000]  raw='pass'  →  Pass

 44%|████▍     | 444/1000 [02:00<02:30,  3.69it/s]

[444/1000]  raw='fail'  →  Fail

 44%|████▍     | 445/1000 [02:00<02:30,  3.69it/s]

[445/1000]  raw='pass'  →  Pass

 45%|████▍     | 446/1000 [02:00<02:30,  3.68it/s]

[446/1000]  raw='fail'  →  Fail

 45%|████▍     | 447/1000 [02:01<02:30,  3.68it/s]

[447/1000]  raw='pass'  →  Pass

 45%|████▍     | 448/1000 [02:01<02:29,  3.68it/s]

[448/1000]  raw='fail'  →  Fail

 45%|████▍     | 449/1000 [02:01<02:29,  3.70it/s]

[449/1000]  raw='fail'  →  Fail

 45%|████▌     | 450/1000 [02:01<02:28,  3.70it/s]

[450/1000]  raw='fail'  →  Fail

 45%|████▌     | 451/1000 [02:02<02:28,  3.69it/s]

[451/1000]  raw='pass'  →  Pass

 45%|████▌     | 452/1000 [02:02<02:28,  3.69it/s]

[452/1000]  raw='pass'  →  Pass

 45%|████▌     | 453/1000 [02:02<02:28,  3.69it/s]

[453/1000]  raw='fail'  →  Fail

 45%|████▌     | 454/1000 [02:02<02:28,  3.69it/s]

[454/1000]  raw='pass'  →  Pass

 46%|████▌     | 455/1000 [02:03<02:27,  3.69it/s]

[455/1000]  raw='pass'  →  Pass

 46%|████▌     | 456/1000 [02:03<02:27,  3.68it/s]

[456/1000]  raw='pass'  →  Pass

 46%|████▌     | 457/1000 [02:03<02:27,  3.68it/s]

[457/1000]  raw='pass'  →  Pass

 46%|████▌     | 458/1000 [02:04<02:27,  3.68it/s]

[458/1000]  raw='fail'  →  Fail

 46%|████▌     | 459/1000 [02:04<02:26,  3.69it/s]

[459/1000]  raw='pass'  →  Pass

 46%|████▌     | 460/1000 [02:04<02:26,  3.68it/s]

[460/1000]  raw='fail'  →  Fail

 46%|████▌     | 461/1000 [02:04<02:26,  3.67it/s]

[461/1000]  raw='fail'  →  Fail

 46%|████▌     | 462/1000 [02:05<02:26,  3.68it/s]

[462/1000]  raw='fail'  →  Fail

 46%|████▋     | 463/1000 [02:05<02:25,  3.69it/s]

[463/1000]  raw='fail'  →  Fail

 46%|████▋     | 464/1000 [02:05<02:24,  3.70it/s]

[464/1000]  raw='pass'  →  Pass

 46%|████▋     | 465/1000 [02:05<02:24,  3.69it/s]

[465/1000]  raw='fail'  →  Fail

 47%|████▋     | 466/1000 [02:06<02:24,  3.68it/s]

[466/1000]  raw='pass'  →  Pass

 47%|████▋     | 467/1000 [02:06<02:24,  3.68it/s]

[467/1000]  raw='fail'  →  Fail

 47%|████▋     | 468/1000 [02:06<02:24,  3.69it/s]

[468/1000]  raw='pass'  →  Pass

 47%|████▋     | 469/1000 [02:07<02:23,  3.69it/s]

[469/1000]  raw='fail'  →  Fail

 47%|████▋     | 470/1000 [02:07<02:23,  3.70it/s]

[470/1000]  raw='fail'  →  Fail

 47%|████▋     | 471/1000 [02:07<02:22,  3.71it/s]

[471/1000]  raw='pass'  →  Pass

 47%|████▋     | 472/1000 [02:07<02:22,  3.71it/s]

[472/1000]  raw='pass'  →  Pass

 47%|████▋     | 473/1000 [02:08<02:22,  3.70it/s]

[473/1000]  raw='fail'  →  Fail

 47%|████▋     | 474/1000 [02:08<02:22,  3.70it/s]

[474/1000]  raw='fail'  →  Fail

 48%|████▊     | 475/1000 [02:08<02:21,  3.71it/s]

[475/1000]  raw='pass'  →  Pass

 48%|████▊     | 476/1000 [02:08<02:21,  3.71it/s]

[476/1000]  raw='fail'  →  Fail

 48%|████▊     | 477/1000 [02:09<02:20,  3.72it/s]

[477/1000]  raw='fail'  →  Fail

 48%|████▊     | 478/1000 [02:09<02:20,  3.72it/s]

[478/1000]  raw='fail'  →  Fail

 48%|████▊     | 479/1000 [02:09<02:20,  3.72it/s]

[479/1000]  raw='fail'  →  Fail

 48%|████▊     | 480/1000 [02:09<02:19,  3.72it/s]

[480/1000]  raw='pass'  →  Pass

 48%|████▊     | 481/1000 [02:10<02:19,  3.71it/s]

[481/1000]  raw='pass'  →  Pass

 48%|████▊     | 482/1000 [02:10<02:19,  3.72it/s]

[482/1000]  raw='fail'  →  Fail

 48%|████▊     | 483/1000 [02:10<02:19,  3.72it/s]

[483/1000]  raw='pass'  →  Pass

 48%|████▊     | 484/1000 [02:11<02:18,  3.72it/s]

[484/1000]  raw='pass'  →  Pass

 48%|████▊     | 485/1000 [02:11<02:18,  3.71it/s]

[485/1000]  raw='pass'  →  Pass

 49%|████▊     | 486/1000 [02:11<02:17,  3.73it/s]

[486/1000]  raw='fail'  →  Fail

 49%|████▊     | 487/1000 [02:11<02:17,  3.73it/s]

[487/1000]  raw='pass'  →  Pass

 49%|████▉     | 488/1000 [02:12<02:17,  3.72it/s]

[488/1000]  raw='pass'  →  Pass

 49%|████▉     | 489/1000 [02:12<02:17,  3.71it/s]

[489/1000]  raw='fail'  →  Fail

 49%|████▉     | 490/1000 [02:12<02:17,  3.72it/s]

[490/1000]  raw='fail'  →  Fail

 49%|████▉     | 491/1000 [02:12<02:16,  3.73it/s]

[491/1000]  raw='fail'  →  Fail

 49%|████▉     | 492/1000 [02:13<02:16,  3.72it/s]

[492/1000]  raw='pass'  →  Pass

 49%|████▉     | 493/1000 [02:13<02:16,  3.72it/s]

[493/1000]  raw='fail'  →  Fail

 49%|████▉     | 494/1000 [02:13<02:16,  3.72it/s]

[494/1000]  raw='fail'  →  Fail

 50%|████▉     | 495/1000 [02:14<02:15,  3.72it/s]

[495/1000]  raw='pass'  →  Pass

 50%|████▉     | 496/1000 [02:14<02:15,  3.72it/s]

[496/1000]  raw='pass'  →  Pass

 50%|████▉     | 497/1000 [02:14<02:15,  3.71it/s]

[497/1000]  raw='fail'  →  Fail

 50%|████▉     | 498/1000 [02:14<02:15,  3.71it/s]

[498/1000]  raw='fail'  →  Fail

 50%|████▉     | 499/1000 [02:15<02:14,  3.71it/s]

[499/1000]  raw='fail'  →  Fail

 50%|█████     | 500/1000 [02:15<02:15,  3.70it/s]

[500/1000]  raw='fail'  →  Fail

 50%|█████     | 501/1000 [02:15<02:14,  3.70it/s]

[501/1000]  raw='fail'  →  Fail

 50%|█████     | 502/1000 [02:15<02:15,  3.69it/s]

[502/1000]  raw='pass'  →  Pass

 50%|█████     | 503/1000 [02:16<02:14,  3.69it/s]

[503/1000]  raw='pass'  →  Pass

 50%|█████     | 504/1000 [02:16<02:14,  3.69it/s]

[504/1000]  raw='fail'  →  Fail

 50%|█████     | 505/1000 [02:16<02:14,  3.69it/s]

[505/1000]  raw='fail'  →  Fail

 51%|█████     | 506/1000 [02:16<02:13,  3.69it/s]

[506/1000]  raw='fail'  →  Fail

 51%|█████     | 507/1000 [02:17<02:13,  3.70it/s]

[507/1000]  raw='pass'  →  Pass

 51%|█████     | 508/1000 [02:17<02:12,  3.70it/s]

[508/1000]  raw='fail'  →  Fail

 51%|█████     | 509/1000 [02:17<02:12,  3.71it/s]

[509/1000]  raw='fail'  →  Fail

 51%|█████     | 510/1000 [02:18<02:12,  3.71it/s]

[510/1000]  raw='pass'  →  Pass

 51%|█████     | 511/1000 [02:18<02:12,  3.70it/s]

[511/1000]  raw='fail'  →  Fail

 51%|█████     | 512/1000 [02:18<02:12,  3.68it/s]

[512/1000]  raw='pass'  →  Pass

 51%|█████▏    | 513/1000 [02:18<02:12,  3.68it/s]

[513/1000]  raw='pass'  →  Pass

 51%|█████▏    | 514/1000 [02:19<02:11,  3.69it/s]

[514/1000]  raw='pass'  →  Pass

 52%|█████▏    | 515/1000 [02:19<02:11,  3.68it/s]

[515/1000]  raw='fail'  →  Fail

 52%|█████▏    | 516/1000 [02:19<02:11,  3.68it/s]

[516/1000]  raw='pass'  →  Pass

 52%|█████▏    | 517/1000 [02:19<02:11,  3.68it/s]

[517/1000]  raw='fail'  →  Fail

 52%|█████▏    | 518/1000 [02:20<02:10,  3.68it/s]

[518/1000]  raw='fail'  →  Fail

 52%|█████▏    | 519/1000 [02:20<02:10,  3.68it/s]

[519/1000]  raw='pass'  →  Pass

 52%|█████▏    | 520/1000 [02:20<02:10,  3.68it/s]

[520/1000]  raw='fail'  →  Fail

 52%|█████▏    | 521/1000 [02:21<02:10,  3.68it/s]

[521/1000]  raw='pass'  →  Pass

 52%|█████▏    | 522/1000 [02:21<02:10,  3.68it/s]

[522/1000]  raw='fail'  →  Fail

 52%|█████▏    | 523/1000 [02:21<02:09,  3.68it/s]

[523/1000]  raw='pass'  →  Pass

 52%|█████▏    | 524/1000 [02:21<02:09,  3.68it/s]

[524/1000]  raw='pass'  →  Pass

 52%|█████▎    | 525/1000 [02:22<02:09,  3.68it/s]

[525/1000]  raw='fail'  →  Fail

 53%|█████▎    | 526/1000 [02:22<02:08,  3.67it/s]

[526/1000]  raw='pass'  →  Pass

 53%|█████▎    | 527/1000 [02:22<02:08,  3.68it/s]

[527/1000]  raw='pass'  →  Pass

 53%|█████▎    | 528/1000 [02:22<02:08,  3.68it/s]

[528/1000]  raw='fail'  →  Fail

 53%|█████▎    | 529/1000 [02:23<02:07,  3.69it/s]

[529/1000]  raw='fail'  →  Fail

 53%|█████▎    | 530/1000 [02:23<02:07,  3.68it/s]

[530/1000]  raw='fail'  →  Fail

 53%|█████▎    | 531/1000 [02:23<02:07,  3.68it/s]

[531/1000]  raw='pass'  →  Pass

 53%|█████▎    | 532/1000 [02:24<02:06,  3.69it/s]

[532/1000]  raw='fail'  →  Fail

 53%|█████▎    | 533/1000 [02:24<02:06,  3.69it/s]

[533/1000]  raw='pass'  →  Pass

 53%|█████▎    | 534/1000 [02:24<02:06,  3.69it/s]

[534/1000]  raw='pass'  →  Pass

 54%|█████▎    | 535/1000 [02:24<02:06,  3.69it/s]

[535/1000]  raw='pass'  →  Pass

 54%|█████▎    | 536/1000 [02:25<02:05,  3.69it/s]

[536/1000]  raw='pass'  →  Pass

 54%|█████▎    | 537/1000 [02:25<02:05,  3.69it/s]

[537/1000]  raw='pass'  →  Pass

 54%|█████▍    | 538/1000 [02:25<02:05,  3.68it/s]

[538/1000]  raw='fail'  →  Fail

 54%|█████▍    | 539/1000 [02:25<02:05,  3.67it/s]

[539/1000]  raw='fail'  →  Fail

 54%|█████▍    | 540/1000 [02:26<02:05,  3.67it/s]

[540/1000]  raw='pass'  →  Pass

 54%|█████▍    | 541/1000 [02:26<02:05,  3.66it/s]

[541/1000]  raw='pass'  →  Pass

 54%|█████▍    | 542/1000 [02:26<02:04,  3.67it/s]

[542/1000]  raw='fail'  →  Fail

 54%|█████▍    | 543/1000 [02:27<02:04,  3.67it/s]

[543/1000]  raw='pass'  →  Pass

 54%|█████▍    | 544/1000 [02:27<02:03,  3.68it/s]

[544/1000]  raw='fail'  →  Fail

 55%|█████▍    | 545/1000 [02:27<02:03,  3.69it/s]

[545/1000]  raw='fail'  →  Fail

 55%|█████▍    | 546/1000 [02:27<02:03,  3.68it/s]

[546/1000]  raw='pass'  →  Pass

 55%|█████▍    | 547/1000 [02:28<02:02,  3.68it/s]

[547/1000]  raw='fail'  →  Fail

 55%|█████▍    | 548/1000 [02:28<02:02,  3.68it/s]

[548/1000]  raw='pass'  →  Pass

 55%|█████▍    | 549/1000 [02:28<02:02,  3.69it/s]

[549/1000]  raw='fail'  →  Fail

 55%|█████▌    | 550/1000 [02:28<02:01,  3.70it/s]

[550/1000]  raw='fail'  →  Fail

 55%|█████▌    | 551/1000 [02:29<02:01,  3.69it/s]

[551/1000]  raw='pass'  →  Pass

 55%|█████▌    | 552/1000 [02:29<02:01,  3.69it/s]

[552/1000]  raw='pass'  →  Pass

 55%|█████▌    | 553/1000 [02:29<02:01,  3.69it/s]

[553/1000]  raw='pass'  →  Pass

 55%|█████▌    | 554/1000 [02:30<02:00,  3.69it/s]

[554/1000]  raw='pass'  →  Pass

 56%|█████▌    | 555/1000 [02:30<02:00,  3.70it/s]

[555/1000]  raw='pass'  →  Pass

 56%|█████▌    | 556/1000 [02:30<02:00,  3.70it/s]

[556/1000]  raw='fail'  →  Fail

 56%|█████▌    | 557/1000 [02:30<01:59,  3.69it/s]

[557/1000]  raw='fail'  →  Fail

 56%|█████▌    | 558/1000 [02:31<02:00,  3.67it/s]

[558/1000]  raw='fail'  →  Fail

 56%|█████▌    | 559/1000 [02:31<02:00,  3.67it/s]

[559/1000]  raw='fail'  →  Fail

 56%|█████▌    | 560/1000 [02:31<01:59,  3.68it/s]

[560/1000]  raw='fail'  →  Fail

 56%|█████▌    | 561/1000 [02:31<01:59,  3.68it/s]

[561/1000]  raw='fail'  →  Fail

 56%|█████▌    | 562/1000 [02:32<01:59,  3.66it/s]

[562/1000]  raw='pass'  →  Pass

 56%|█████▋    | 563/1000 [02:32<02:00,  3.64it/s]

[563/1000]  raw='fail'  →  Fail

 56%|█████▋    | 564/1000 [02:32<01:59,  3.65it/s]

[564/1000]  raw='pass'  →  Pass

 56%|█████▋    | 565/1000 [02:33<01:59,  3.65it/s]

[565/1000]  raw='pass'  →  Pass

 57%|█████▋    | 566/1000 [02:33<01:59,  3.64it/s]

[566/1000]  raw='pass'  →  Pass

 57%|█████▋    | 567/1000 [02:33<01:58,  3.65it/s]

[567/1000]  raw='fail'  →  Fail

 57%|█████▋    | 568/1000 [02:33<01:58,  3.66it/s]

[568/1000]  raw='fail'  →  Fail

 57%|█████▋    | 569/1000 [02:34<01:57,  3.67it/s]

[569/1000]  raw='fail'  →  Fail

 57%|█████▋    | 570/1000 [02:34<01:56,  3.68it/s]

[570/1000]  raw='pass'  →  Pass

 57%|█████▋    | 571/1000 [02:34<01:56,  3.68it/s]

[571/1000]  raw='fail'  →  Fail

 57%|█████▋    | 572/1000 [02:34<01:56,  3.68it/s]

[572/1000]  raw='fail'  →  Fail

 57%|█████▋    | 573/1000 [02:35<01:55,  3.69it/s]

[573/1000]  raw='pass'  →  Pass

 57%|█████▋    | 574/1000 [02:35<01:55,  3.68it/s]

[574/1000]  raw='fail'  →  Fail

 57%|█████▊    | 575/1000 [02:35<01:55,  3.67it/s]

[575/1000]  raw='fail'  →  Fail

 58%|█████▊    | 576/1000 [02:36<01:55,  3.67it/s]

[576/1000]  raw='pass'  →  Pass

 58%|█████▊    | 577/1000 [02:36<01:55,  3.67it/s]

[577/1000]  raw='pass'  →  Pass

 58%|█████▊    | 578/1000 [02:36<01:54,  3.68it/s]

[578/1000]  raw='fail'  →  Fail

 58%|█████▊    | 579/1000 [02:36<01:54,  3.68it/s]

[579/1000]  raw='fail'  →  Fail

 58%|█████▊    | 580/1000 [02:37<01:54,  3.68it/s]

[580/1000]  raw='pass'  →  Pass

 58%|█████▊    | 581/1000 [02:37<01:53,  3.69it/s]

[581/1000]  raw='pass'  →  Pass

 58%|█████▊    | 582/1000 [02:37<01:53,  3.67it/s]

[582/1000]  raw='fail'  →  Fail

 58%|█████▊    | 583/1000 [02:37<01:53,  3.68it/s]

[583/1000]  raw='pass'  →  Pass

 58%|█████▊    | 584/1000 [02:38<01:52,  3.69it/s]

[584/1000]  raw='pass'  →  Pass

 58%|█████▊    | 585/1000 [02:38<01:52,  3.70it/s]

[585/1000]  raw='pass'  →  Pass

 59%|█████▊    | 586/1000 [02:38<01:52,  3.69it/s]

[586/1000]  raw='fail'  →  Fail

 59%|█████▊    | 587/1000 [02:38<01:51,  3.69it/s]

[587/1000]  raw='fail'  →  Fail

 59%|█████▉    | 588/1000 [02:39<01:51,  3.68it/s]

[588/1000]  raw='fail'  →  Fail

 59%|█████▉    | 589/1000 [02:39<01:51,  3.67it/s]

[589/1000]  raw='fail'  →  Fail

 59%|█████▉    | 590/1000 [02:39<01:51,  3.67it/s]

[590/1000]  raw='pass'  →  Pass

 59%|█████▉    | 591/1000 [02:40<01:51,  3.68it/s]

[591/1000]  raw='pass'  →  Pass

 59%|█████▉    | 592/1000 [02:40<01:50,  3.69it/s]

[592/1000]  raw='pass'  →  Pass

 59%|█████▉    | 593/1000 [02:40<01:50,  3.70it/s]

[593/1000]  raw='pass'  →  Pass

 59%|█████▉    | 594/1000 [02:40<01:50,  3.68it/s]

[594/1000]  raw='fail'  →  Fail

 60%|█████▉    | 595/1000 [02:41<01:49,  3.69it/s]

[595/1000]  raw='pass'  →  Pass

 60%|█████▉    | 596/1000 [02:41<01:49,  3.68it/s]

[596/1000]  raw='fail'  →  Fail

 60%|█████▉    | 597/1000 [02:41<01:49,  3.68it/s]

[597/1000]  raw='pass'  →  Pass

 60%|█████▉    | 598/1000 [02:41<01:48,  3.69it/s]

[598/1000]  raw='fail'  →  Fail

 60%|█████▉    | 599/1000 [02:42<01:48,  3.70it/s]

[599/1000]  raw='pass'  →  Pass

 60%|██████    | 600/1000 [02:42<01:48,  3.69it/s]

[600/1000]  raw='pass'  →  Pass

 60%|██████    | 601/1000 [02:42<01:47,  3.70it/s]

[601/1000]  raw='pass'  →  Pass

 60%|██████    | 602/1000 [02:43<01:47,  3.71it/s]

[602/1000]  raw='fail'  →  Fail

 60%|██████    | 603/1000 [02:43<01:46,  3.72it/s]

[603/1000]  raw='fail'  →  Fail

 60%|██████    | 604/1000 [02:43<01:46,  3.71it/s]

[604/1000]  raw='fail'  →  Fail

 60%|██████    | 605/1000 [02:43<01:46,  3.72it/s]

[605/1000]  raw='fail'  →  Fail

 61%|██████    | 606/1000 [02:44<01:45,  3.73it/s]

[606/1000]  raw='pass'  →  Pass

 61%|██████    | 607/1000 [02:44<01:45,  3.73it/s]

[607/1000]  raw='pass'  →  Pass

 61%|██████    | 608/1000 [02:44<01:45,  3.72it/s]

[608/1000]  raw='fail'  →  Fail

 61%|██████    | 609/1000 [02:44<01:45,  3.71it/s]

[609/1000]  raw='pass'  →  Pass

 61%|██████    | 610/1000 [02:45<01:44,  3.72it/s]

[610/1000]  raw='fail'  →  Fail

 61%|██████    | 611/1000 [02:45<01:44,  3.72it/s]

[611/1000]  raw='fail'  →  Fail

 61%|██████    | 612/1000 [02:45<01:44,  3.72it/s]

[612/1000]  raw='fail'  →  Fail

 61%|██████▏   | 613/1000 [02:46<01:44,  3.72it/s]

[613/1000]  raw='pass'  →  Pass

 61%|██████▏   | 614/1000 [02:46<01:43,  3.72it/s]

[614/1000]  raw='pass'  →  Pass

 62%|██████▏   | 615/1000 [02:46<01:43,  3.72it/s]

[615/1000]  raw='fail'  →  Fail

 62%|██████▏   | 616/1000 [02:46<01:43,  3.73it/s]

[616/1000]  raw='fail'  →  Fail

 62%|██████▏   | 617/1000 [02:47<01:42,  3.72it/s]

[617/1000]  raw='pass'  →  Pass

 62%|██████▏   | 618/1000 [02:47<01:42,  3.72it/s]

[618/1000]  raw='pass'  →  Pass

 62%|██████▏   | 619/1000 [02:47<01:42,  3.73it/s]

[619/1000]  raw='fail'  →  Fail

 62%|██████▏   | 620/1000 [02:47<01:42,  3.71it/s]

[620/1000]  raw='fail'  →  Fail

 62%|██████▏   | 621/1000 [02:48<01:42,  3.71it/s]

[621/1000]  raw='pass'  →  Pass

 62%|██████▏   | 622/1000 [02:48<01:42,  3.70it/s]

[622/1000]  raw='fail'  →  Fail

 62%|██████▏   | 623/1000 [02:48<01:42,  3.69it/s]

[623/1000]  raw='fail'  →  Fail

 62%|██████▏   | 624/1000 [02:48<01:41,  3.69it/s]

[624/1000]  raw='pass'  →  Pass

 62%|██████▎   | 625/1000 [02:49<01:41,  3.69it/s]

[625/1000]  raw='fail'  →  Fail

 63%|██████▎   | 626/1000 [02:49<01:41,  3.70it/s]

[626/1000]  raw='fail'  →  Fail

 63%|██████▎   | 627/1000 [02:49<01:41,  3.68it/s]

[627/1000]  raw='fail'  →  Fail

 63%|██████▎   | 628/1000 [02:50<01:41,  3.68it/s]

[628/1000]  raw='pass'  →  Pass

 63%|██████▎   | 629/1000 [02:50<01:40,  3.68it/s]

[629/1000]  raw='fail'  →  Fail

 63%|██████▎   | 630/1000 [02:50<01:40,  3.69it/s]

[630/1000]  raw='fail'  →  Fail

 63%|██████▎   | 631/1000 [02:50<01:40,  3.68it/s]

[631/1000]  raw='pass'  →  Pass

 63%|██████▎   | 632/1000 [02:51<01:39,  3.69it/s]

[632/1000]  raw='pass'  →  Pass

 63%|██████▎   | 633/1000 [02:51<01:39,  3.69it/s]

[633/1000]  raw='fail'  →  Fail

 63%|██████▎   | 634/1000 [02:51<01:39,  3.69it/s]

[634/1000]  raw='fail'  →  Fail

 64%|██████▎   | 635/1000 [02:51<01:38,  3.69it/s]

[635/1000]  raw='pass'  →  Pass

 64%|██████▎   | 636/1000 [02:52<01:38,  3.70it/s]

[636/1000]  raw='pass'  →  Pass

 64%|██████▎   | 637/1000 [02:52<01:37,  3.71it/s]

[637/1000]  raw='fail'  →  Fail

 64%|██████▍   | 638/1000 [02:52<01:37,  3.71it/s]

[638/1000]  raw='fail'  →  Fail

 64%|██████▍   | 639/1000 [02:53<01:37,  3.71it/s]

[639/1000]  raw='fail'  →  Fail

 64%|██████▍   | 640/1000 [02:53<01:36,  3.72it/s]

[640/1000]  raw='pass'  →  Pass

 64%|██████▍   | 641/1000 [02:53<01:36,  3.72it/s]

[641/1000]  raw='fail'  →  Fail

 64%|██████▍   | 642/1000 [02:53<01:36,  3.72it/s]

[642/1000]  raw='pass'  →  Pass

 64%|██████▍   | 643/1000 [02:54<01:35,  3.72it/s]

[643/1000]  raw='pass'  →  Pass

 64%|██████▍   | 644/1000 [02:54<01:35,  3.72it/s]

[644/1000]  raw='pass'  →  Pass

 64%|██████▍   | 645/1000 [02:54<01:35,  3.72it/s]

[645/1000]  raw='pass'  →  Pass

 65%|██████▍   | 646/1000 [02:54<01:35,  3.71it/s]

[646/1000]  raw='pass'  →  Pass

 65%|██████▍   | 647/1000 [02:55<01:35,  3.71it/s]

[647/1000]  raw='fail'  →  Fail

 65%|██████▍   | 648/1000 [02:55<01:35,  3.70it/s]

[648/1000]  raw='fail'  →  Fail

 65%|██████▍   | 649/1000 [02:55<01:34,  3.70it/s]

[649/1000]  raw='fail'  →  Fail

 65%|██████▌   | 650/1000 [02:56<01:35,  3.68it/s]

[650/1000]  raw='pass'  →  Pass

 65%|██████▌   | 651/1000 [02:56<01:34,  3.69it/s]

[651/1000]  raw='fail'  →  Fail

 65%|██████▌   | 652/1000 [02:56<01:34,  3.69it/s]

[652/1000]  raw='fail'  →  Fail

 65%|██████▌   | 653/1000 [02:56<01:33,  3.71it/s]

[653/1000]  raw='pass'  →  Pass

 65%|██████▌   | 654/1000 [02:57<01:32,  3.73it/s]

[654/1000]  raw='fail'  →  Fail

 66%|██████▌   | 655/1000 [02:57<01:31,  3.75it/s]

[655/1000]  raw='fail'  →  Fail

 66%|██████▌   | 656/1000 [02:57<01:31,  3.76it/s]

[656/1000]  raw='fail'  →  Fail

 66%|██████▌   | 657/1000 [02:57<01:31,  3.76it/s]

[657/1000]  raw='fail'  →  Fail

 66%|██████▌   | 658/1000 [02:58<01:30,  3.76it/s]

[658/1000]  raw='fail'  →  Fail

 66%|██████▌   | 659/1000 [02:58<01:30,  3.76it/s]

[659/1000]  raw='fail'  →  Fail

 66%|██████▌   | 660/1000 [02:58<01:30,  3.77it/s]

[660/1000]  raw='fail'  →  Fail

 66%|██████▌   | 661/1000 [02:58<01:29,  3.78it/s]

[661/1000]  raw='pass'  →  Pass

 66%|██████▌   | 662/1000 [02:59<01:29,  3.78it/s]

[662/1000]  raw='pass'  →  Pass

 66%|██████▋   | 663/1000 [02:59<01:28,  3.79it/s]

[663/1000]  raw='fail'  →  Fail

 66%|██████▋   | 664/1000 [02:59<01:28,  3.78it/s]

[664/1000]  raw='pass'  →  Pass

 66%|██████▋   | 665/1000 [02:59<01:28,  3.79it/s]

[665/1000]  raw='pass'  →  Pass

 67%|██████▋   | 666/1000 [03:00<01:28,  3.79it/s]

[666/1000]  raw='fail'  →  Fail

 67%|██████▋   | 667/1000 [03:00<01:28,  3.78it/s]

[667/1000]  raw='pass'  →  Pass

 67%|██████▋   | 668/1000 [03:00<01:27,  3.78it/s]

[668/1000]  raw='fail'  →  Fail

 67%|██████▋   | 669/1000 [03:01<01:27,  3.79it/s]

[669/1000]  raw='pass'  →  Pass

 67%|██████▋   | 670/1000 [03:01<01:26,  3.80it/s]

[670/1000]  raw='fail'  →  Fail

 67%|██████▋   | 671/1000 [03:01<01:26,  3.79it/s]

[671/1000]  raw='pass'  →  Pass

 67%|██████▋   | 672/1000 [03:01<01:26,  3.79it/s]

[672/1000]  raw='fail'  →  Fail

 67%|██████▋   | 673/1000 [03:02<01:26,  3.79it/s]

[673/1000]  raw='fail'  →  Fail

 67%|██████▋   | 674/1000 [03:02<01:25,  3.79it/s]

[674/1000]  raw='pass'  →  Pass

 68%|██████▊   | 675/1000 [03:02<01:26,  3.78it/s]

[675/1000]  raw='fail'  →  Fail

 68%|██████▊   | 676/1000 [03:02<01:25,  3.78it/s]

[676/1000]  raw='fail'  →  Fail

 68%|██████▊   | 677/1000 [03:03<01:25,  3.78it/s]

[677/1000]  raw='fail'  →  Fail

 68%|██████▊   | 678/1000 [03:03<01:25,  3.79it/s]

[678/1000]  raw='pass'  →  Pass

 68%|██████▊   | 679/1000 [03:03<01:24,  3.80it/s]

[679/1000]  raw='fail'  →  Fail

 68%|██████▊   | 680/1000 [03:03<01:24,  3.81it/s]

[680/1000]  raw='fail'  →  Fail

 68%|██████▊   | 681/1000 [03:04<01:23,  3.80it/s]

[681/1000]  raw='fail'  →  Fail

 68%|██████▊   | 682/1000 [03:04<01:23,  3.80it/s]

[682/1000]  raw='pass'  →  Pass

 68%|██████▊   | 683/1000 [03:04<01:23,  3.81it/s]

[683/1000]  raw='fail'  →  Fail

 68%|██████▊   | 684/1000 [03:04<01:22,  3.81it/s]

[684/1000]  raw='pass'  →  Pass

 68%|██████▊   | 685/1000 [03:05<01:22,  3.80it/s]

[685/1000]  raw='pass'  →  Pass

 69%|██████▊   | 686/1000 [03:05<01:22,  3.80it/s]

[686/1000]  raw='pass'  →  Pass

 69%|██████▊   | 687/1000 [03:05<01:22,  3.80it/s]

[687/1000]  raw='pass'  →  Pass

 69%|██████▉   | 688/1000 [03:06<01:22,  3.80it/s]

[688/1000]  raw='pass'  →  Pass

 69%|██████▉   | 689/1000 [03:06<01:21,  3.80it/s]

[689/1000]  raw='fail'  →  Fail

 69%|██████▉   | 690/1000 [03:06<01:21,  3.80it/s]

[690/1000]  raw='fail'  →  Fail

 69%|██████▉   | 691/1000 [03:06<01:21,  3.80it/s]

[691/1000]  raw='pass'  →  Pass

 69%|██████▉   | 692/1000 [03:07<01:20,  3.81it/s]

[692/1000]  raw='fail'  →  Fail

 69%|██████▉   | 693/1000 [03:07<01:20,  3.81it/s]

[693/1000]  raw='fail'  →  Fail

 69%|██████▉   | 694/1000 [03:07<01:20,  3.80it/s]

[694/1000]  raw='pass'  →  Pass

 70%|██████▉   | 695/1000 [03:07<01:20,  3.81it/s]

[695/1000]  raw='pass'  →  Pass

 70%|██████▉   | 696/1000 [03:08<01:19,  3.81it/s]

[696/1000]  raw='pass'  →  Pass

 70%|██████▉   | 697/1000 [03:08<01:19,  3.79it/s]

[697/1000]  raw='pass'  →  Pass

 70%|██████▉   | 698/1000 [03:08<01:19,  3.78it/s]

[698/1000]  raw='pass'  →  Pass

 70%|██████▉   | 699/1000 [03:08<01:19,  3.79it/s]

[699/1000]  raw='pass'  →  Pass

 70%|███████   | 700/1000 [03:09<01:19,  3.80it/s]

[700/1000]  raw='pass'  →  Pass

 70%|███████   | 701/1000 [03:09<01:18,  3.79it/s]

[701/1000]  raw='pass'  →  Pass

 70%|███████   | 702/1000 [03:09<01:18,  3.78it/s]

[702/1000]  raw='fail'  →  Fail

 70%|███████   | 703/1000 [03:10<01:18,  3.78it/s]

[703/1000]  raw='pass'  →  Pass

 70%|███████   | 704/1000 [03:10<01:18,  3.78it/s]

[704/1000]  raw='fail'  →  Fail

 70%|███████   | 705/1000 [03:10<01:18,  3.77it/s]

[705/1000]  raw='pass'  →  Pass

 71%|███████   | 706/1000 [03:10<01:19,  3.70it/s]

[706/1000]  raw='fail'  →  Fail

 71%|███████   | 707/1000 [03:11<01:19,  3.71it/s]

[707/1000]  raw='pass'  →  Pass

 71%|███████   | 708/1000 [03:11<01:18,  3.72it/s]

[708/1000]  raw='pass'  →  Pass

 71%|███████   | 709/1000 [03:11<01:18,  3.73it/s]

[709/1000]  raw='fail'  →  Fail

 71%|███████   | 710/1000 [03:11<01:17,  3.74it/s]

[710/1000]  raw='fail'  →  Fail

 71%|███████   | 711/1000 [03:12<01:17,  3.74it/s]

[711/1000]  raw='pass'  →  Pass

 71%|███████   | 712/1000 [03:12<01:17,  3.74it/s]

[712/1000]  raw='fail'  →  Fail

 71%|███████▏  | 713/1000 [03:12<01:16,  3.74it/s]

[713/1000]  raw='fail'  →  Fail

 71%|███████▏  | 714/1000 [03:12<01:16,  3.75it/s]

[714/1000]  raw='pass'  →  Pass

 72%|███████▏  | 715/1000 [03:13<01:15,  3.75it/s]

[715/1000]  raw='pass'  →  Pass

 72%|███████▏  | 716/1000 [03:13<01:15,  3.75it/s]

[716/1000]  raw='fail'  →  Fail

 72%|███████▏  | 717/1000 [03:13<01:15,  3.76it/s]

[717/1000]  raw='fail'  →  Fail

 72%|███████▏  | 718/1000 [03:14<01:15,  3.74it/s]

[718/1000]  raw='pass'  →  Pass

 72%|███████▏  | 719/1000 [03:14<01:15,  3.74it/s]

[719/1000]  raw='fail'  →  Fail

 72%|███████▏  | 720/1000 [03:14<01:15,  3.71it/s]

[720/1000]  raw='fail'  →  Fail

 72%|███████▏  | 721/1000 [03:14<01:15,  3.71it/s]

[721/1000]  raw='fail'  →  Fail

 72%|███████▏  | 722/1000 [03:15<01:14,  3.71it/s]

[722/1000]  raw='pass'  →  Pass

 72%|███████▏  | 723/1000 [03:15<01:14,  3.72it/s]

[723/1000]  raw='pass'  →  Pass

 72%|███████▏  | 724/1000 [03:15<01:14,  3.71it/s]

[724/1000]  raw='fail'  →  Fail

 72%|███████▎  | 725/1000 [03:15<01:14,  3.71it/s]

[725/1000]  raw='fail'  →  Fail

 73%|███████▎  | 726/1000 [03:16<01:13,  3.72it/s]

[726/1000]  raw='fail'  →  Fail

 73%|███████▎  | 727/1000 [03:16<01:13,  3.73it/s]

[727/1000]  raw='fail'  →  Fail

 73%|███████▎  | 728/1000 [03:16<01:13,  3.72it/s]

[728/1000]  raw='fail'  →  Fail

 73%|███████▎  | 729/1000 [03:16<01:13,  3.71it/s]

[729/1000]  raw='pass'  →  Pass

 73%|███████▎  | 730/1000 [03:17<01:12,  3.72it/s]

[730/1000]  raw='fail'  →  Fail

 73%|███████▎  | 731/1000 [03:17<01:12,  3.72it/s]

[731/1000]  raw='fail'  →  Fail

 73%|███████▎  | 732/1000 [03:17<01:12,  3.72it/s]

[732/1000]  raw='fail'  →  Fail

 73%|███████▎  | 733/1000 [03:18<01:11,  3.71it/s]

[733/1000]  raw='pass'  →  Pass

 73%|███████▎  | 734/1000 [03:18<01:11,  3.71it/s]

[734/1000]  raw='pass'  →  Pass

 74%|███████▎  | 735/1000 [03:18<01:11,  3.72it/s]

[735/1000]  raw='pass'  →  Pass

 74%|███████▎  | 736/1000 [03:18<01:10,  3.73it/s]

[736/1000]  raw='fail'  →  Fail

 74%|███████▎  | 737/1000 [03:19<01:09,  3.76it/s]

[737/1000]  raw='pass'  →  Pass

 74%|███████▍  | 738/1000 [03:19<01:09,  3.77it/s]

[738/1000]  raw='fail'  →  Fail

 74%|███████▍  | 739/1000 [03:19<01:09,  3.75it/s]

[739/1000]  raw='pass'  →  Pass

 74%|███████▍  | 740/1000 [03:19<01:09,  3.75it/s]

[740/1000]  raw='fail'  →  Fail

 74%|███████▍  | 741/1000 [03:20<01:08,  3.75it/s]

[741/1000]  raw='pass'  →  Pass

 74%|███████▍  | 742/1000 [03:20<01:08,  3.75it/s]

[742/1000]  raw='fail'  →  Fail

 74%|███████▍  | 743/1000 [03:20<01:08,  3.73it/s]

[743/1000]  raw='fail'  →  Fail

 74%|███████▍  | 744/1000 [03:21<01:09,  3.70it/s]

[744/1000]  raw='fail'  →  Fail

 74%|███████▍  | 745/1000 [03:21<01:09,  3.68it/s]

[745/1000]  raw='pass'  →  Pass

 75%|███████▍  | 746/1000 [03:21<01:08,  3.69it/s]

[746/1000]  raw='fail'  →  Fail

 75%|███████▍  | 747/1000 [03:21<01:08,  3.68it/s]

[747/1000]  raw='pass'  →  Pass

 75%|███████▍  | 748/1000 [03:22<01:09,  3.65it/s]

[748/1000]  raw='fail'  →  Fail

 75%|███████▍  | 749/1000 [03:22<01:08,  3.66it/s]

[749/1000]  raw='fail'  →  Fail

 75%|███████▌  | 750/1000 [03:22<01:08,  3.66it/s]

[750/1000]  raw='fail'  →  Fail

 75%|███████▌  | 751/1000 [03:22<01:08,  3.66it/s]

[751/1000]  raw='fail'  →  Fail

 75%|███████▌  | 752/1000 [03:23<01:09,  3.59it/s]

[752/1000]  raw='pass'  →  Pass

 75%|███████▌  | 753/1000 [03:23<01:09,  3.58it/s]

[753/1000]  raw='fail'  →  Fail

 75%|███████▌  | 754/1000 [03:23<01:08,  3.59it/s]

[754/1000]  raw='fail'  →  Fail

 76%|███████▌  | 755/1000 [03:24<01:07,  3.63it/s]

[755/1000]  raw='fail'  →  Fail

 76%|███████▌  | 756/1000 [03:24<01:06,  3.66it/s]

[756/1000]  raw='fail'  →  Fail

 76%|███████▌  | 757/1000 [03:24<01:06,  3.67it/s]

[757/1000]  raw='pass'  →  Pass

 76%|███████▌  | 758/1000 [03:24<01:05,  3.67it/s]

[758/1000]  raw='pass'  →  Pass

 76%|███████▌  | 759/1000 [03:25<01:05,  3.67it/s]

[759/1000]  raw='pass'  →  Pass

 76%|███████▌  | 760/1000 [03:25<01:05,  3.68it/s]

[760/1000]  raw='pass'  →  Pass

 76%|███████▌  | 761/1000 [03:25<01:04,  3.68it/s]

[761/1000]  raw='fail'  →  Fail

 76%|███████▌  | 762/1000 [03:25<01:04,  3.68it/s]

[762/1000]  raw='fail'  →  Fail

 76%|███████▋  | 763/1000 [03:26<01:04,  3.68it/s]

[763/1000]  raw='pass'  →  Pass

 76%|███████▋  | 764/1000 [03:26<01:04,  3.67it/s]

[764/1000]  raw='fail'  →  Fail

 76%|███████▋  | 765/1000 [03:26<01:04,  3.67it/s]

[765/1000]  raw='fail'  →  Fail

 77%|███████▋  | 766/1000 [03:27<01:03,  3.68it/s]

[766/1000]  raw='pass'  →  Pass

 77%|███████▋  | 767/1000 [03:27<01:03,  3.67it/s]

[767/1000]  raw='pass'  →  Pass

 77%|███████▋  | 768/1000 [03:27<01:03,  3.68it/s]

[768/1000]  raw='fail'  →  Fail

 77%|███████▋  | 769/1000 [03:27<01:02,  3.69it/s]

[769/1000]  raw='fail'  →  Fail

 77%|███████▋  | 770/1000 [03:28<01:02,  3.69it/s]

[770/1000]  raw='pass'  →  Pass

 77%|███████▋  | 771/1000 [03:28<01:02,  3.69it/s]

[771/1000]  raw='fail'  →  Fail

 77%|███████▋  | 772/1000 [03:28<01:01,  3.68it/s]

[772/1000]  raw='pass'  →  Pass

 77%|███████▋  | 773/1000 [03:28<01:01,  3.69it/s]

[773/1000]  raw='fail'  →  Fail

 77%|███████▋  | 774/1000 [03:29<01:01,  3.69it/s]

[774/1000]  raw='fail'  →  Fail

 78%|███████▊  | 775/1000 [03:29<01:00,  3.70it/s]

[775/1000]  raw='pass'  →  Pass

 78%|███████▊  | 776/1000 [03:29<01:00,  3.70it/s]

[776/1000]  raw='pass'  →  Pass

 78%|███████▊  | 777/1000 [03:29<01:00,  3.70it/s]

[777/1000]  raw='pass'  →  Pass

 78%|███████▊  | 778/1000 [03:30<01:00,  3.69it/s]

[778/1000]  raw='pass'  →  Pass

 78%|███████▊  | 779/1000 [03:30<00:59,  3.69it/s]

[779/1000]  raw='fail'  →  Fail

 78%|███████▊  | 780/1000 [03:30<00:59,  3.69it/s]

[780/1000]  raw='fail'  →  Fail

 78%|███████▊  | 781/1000 [03:31<00:59,  3.69it/s]

[781/1000]  raw='fail'  →  Fail

 78%|███████▊  | 782/1000 [03:31<00:59,  3.69it/s]

[782/1000]  raw='pass'  →  Pass

 78%|███████▊  | 783/1000 [03:31<00:58,  3.70it/s]

[783/1000]  raw='pass'  →  Pass

 78%|███████▊  | 784/1000 [03:31<00:58,  3.68it/s]

[784/1000]  raw='fail'  →  Fail

 78%|███████▊  | 785/1000 [03:32<00:58,  3.68it/s]

[785/1000]  raw='pass'  →  Pass

 79%|███████▊  | 786/1000 [03:32<00:58,  3.68it/s]

[786/1000]  raw='fail'  →  Fail

 79%|███████▊  | 787/1000 [03:32<00:57,  3.70it/s]

[787/1000]  raw='fail'  →  Fail

 79%|███████▉  | 788/1000 [03:32<00:57,  3.69it/s]

[788/1000]  raw='fail'  →  Fail

 79%|███████▉  | 789/1000 [03:33<00:57,  3.69it/s]

[789/1000]  raw='fail'  →  Fail

 79%|███████▉  | 790/1000 [03:33<00:57,  3.67it/s]

[790/1000]  raw='pass'  →  Pass

 79%|███████▉  | 791/1000 [03:33<00:56,  3.67it/s]

[791/1000]  raw='fail'  →  Fail

 79%|███████▉  | 792/1000 [03:34<00:56,  3.66it/s]

[792/1000]  raw='fail'  →  Fail

 79%|███████▉  | 793/1000 [03:34<00:56,  3.67it/s]

[793/1000]  raw='pass'  →  Pass

 79%|███████▉  | 794/1000 [03:34<00:56,  3.66it/s]

[794/1000]  raw='fail'  →  Fail

 80%|███████▉  | 795/1000 [03:34<00:55,  3.67it/s]

[795/1000]  raw='fail'  →  Fail

 80%|███████▉  | 796/1000 [03:35<00:55,  3.66it/s]

[796/1000]  raw='pass'  →  Pass

 80%|███████▉  | 797/1000 [03:35<00:55,  3.67it/s]

[797/1000]  raw='pass'  →  Pass

 80%|███████▉  | 798/1000 [03:35<00:54,  3.68it/s]

[798/1000]  raw='fail'  →  Fail

 80%|███████▉  | 799/1000 [03:35<00:54,  3.68it/s]

[799/1000]  raw='pass'  →  Pass

 80%|████████  | 800/1000 [03:36<00:54,  3.68it/s]

[800/1000]  raw='pass'  →  Pass

 80%|████████  | 801/1000 [03:36<00:54,  3.68it/s]

[801/1000]  raw='fail'  →  Fail

 80%|████████  | 802/1000 [03:36<00:53,  3.68it/s]

[802/1000]  raw='fail'  →  Fail

 80%|████████  | 803/1000 [03:37<00:53,  3.68it/s]

[803/1000]  raw='fail'  →  Fail

 80%|████████  | 804/1000 [03:37<00:53,  3.69it/s]

[804/1000]  raw='pass'  →  Pass

 80%|████████  | 805/1000 [03:37<00:52,  3.69it/s]

[805/1000]  raw='pass'  →  Pass

 81%|████████  | 806/1000 [03:37<00:52,  3.69it/s]

[806/1000]  raw='pass'  →  Pass

 81%|████████  | 807/1000 [03:38<00:52,  3.69it/s]

[807/1000]  raw='pass'  →  Pass

 81%|████████  | 808/1000 [03:38<00:52,  3.68it/s]

[808/1000]  raw='pass'  →  Pass

 81%|████████  | 809/1000 [03:38<00:51,  3.68it/s]

[809/1000]  raw='fail'  →  Fail

 81%|████████  | 810/1000 [03:38<00:51,  3.69it/s]

[810/1000]  raw='pass'  →  Pass

 81%|████████  | 811/1000 [03:39<00:51,  3.69it/s]

[811/1000]  raw='pass'  →  Pass

 81%|████████  | 812/1000 [03:39<00:51,  3.69it/s]

[812/1000]  raw='fail'  →  Fail

 81%|████████▏ | 813/1000 [03:39<00:50,  3.69it/s]

[813/1000]  raw='pass'  →  Pass

 81%|████████▏ | 814/1000 [03:40<00:50,  3.69it/s]

[814/1000]  raw='pass'  →  Pass

 82%|████████▏ | 815/1000 [03:40<00:50,  3.69it/s]

[815/1000]  raw='pass'  →  Pass

 82%|████████▏ | 816/1000 [03:40<00:49,  3.70it/s]

[816/1000]  raw='fail'  →  Fail

 82%|████████▏ | 817/1000 [03:40<00:49,  3.69it/s]

[817/1000]  raw='fail'  →  Fail

 82%|████████▏ | 818/1000 [03:41<00:49,  3.69it/s]

[818/1000]  raw='fail'  →  Fail

 82%|████████▏ | 819/1000 [03:41<00:49,  3.69it/s]

[819/1000]  raw='pass'  →  Pass

 82%|████████▏ | 820/1000 [03:41<00:48,  3.69it/s]

[820/1000]  raw='fail'  →  Fail

 82%|████████▏ | 821/1000 [03:41<00:48,  3.70it/s]

[821/1000]  raw='fail'  →  Fail

 82%|████████▏ | 822/1000 [03:42<00:48,  3.69it/s]

[822/1000]  raw='fail'  →  Fail

 82%|████████▏ | 823/1000 [03:42<00:47,  3.69it/s]

[823/1000]  raw='fail'  →  Fail

 82%|████████▏ | 824/1000 [03:42<00:47,  3.70it/s]

[824/1000]  raw='fail'  →  Fail

 82%|████████▎ | 825/1000 [03:43<00:47,  3.71it/s]

[825/1000]  raw='fail'  →  Fail

 83%|████████▎ | 826/1000 [03:43<00:46,  3.72it/s]

[826/1000]  raw='fail'  →  Fail

 83%|████████▎ | 827/1000 [03:43<00:46,  3.72it/s]

[827/1000]  raw='fail'  →  Fail

 83%|████████▎ | 828/1000 [03:43<00:46,  3.72it/s]

[828/1000]  raw='pass'  →  Pass

 83%|████████▎ | 829/1000 [03:44<00:45,  3.73it/s]

[829/1000]  raw='fail'  →  Fail

 83%|████████▎ | 830/1000 [03:44<00:45,  3.74it/s]

[830/1000]  raw='fail'  →  Fail

 83%|████████▎ | 831/1000 [03:44<00:45,  3.74it/s]

[831/1000]  raw='pass'  →  Pass

 83%|████████▎ | 832/1000 [03:44<00:44,  3.74it/s]

[832/1000]  raw='pass'  →  Pass

 83%|████████▎ | 833/1000 [03:45<00:44,  3.74it/s]

[833/1000]  raw='pass'  →  Pass

 83%|████████▎ | 834/1000 [03:45<00:44,  3.73it/s]

[834/1000]  raw='fail'  →  Fail

 84%|████████▎ | 835/1000 [03:45<00:44,  3.71it/s]

[835/1000]  raw='pass'  →  Pass

 84%|████████▎ | 836/1000 [03:45<00:44,  3.71it/s]

[836/1000]  raw='fail'  →  Fail

 84%|████████▎ | 837/1000 [03:46<00:44,  3.69it/s]

[837/1000]  raw='fail'  →  Fail

 84%|████████▍ | 838/1000 [03:46<00:44,  3.68it/s]

[838/1000]  raw='pass'  →  Pass

 84%|████████▍ | 839/1000 [03:46<00:43,  3.68it/s]

[839/1000]  raw='fail'  →  Fail

 84%|████████▍ | 840/1000 [03:47<00:43,  3.66it/s]

[840/1000]  raw='pass'  →  Pass

 84%|████████▍ | 841/1000 [03:47<00:43,  3.68it/s]

[841/1000]  raw='pass'  →  Pass

 84%|████████▍ | 842/1000 [03:47<00:42,  3.70it/s]

[842/1000]  raw='fail'  →  Fail

 84%|████████▍ | 843/1000 [03:47<00:42,  3.70it/s]

[843/1000]  raw='pass'  →  Pass

 84%|████████▍ | 844/1000 [03:48<00:42,  3.70it/s]

[844/1000]  raw='fail'  →  Fail

 84%|████████▍ | 845/1000 [03:48<00:42,  3.69it/s]

[845/1000]  raw='fail'  →  Fail

 85%|████████▍ | 846/1000 [03:48<00:41,  3.67it/s]

[846/1000]  raw='fail'  →  Fail

 85%|████████▍ | 847/1000 [03:48<00:41,  3.68it/s]

[847/1000]  raw='fail'  →  Fail

 85%|████████▍ | 848/1000 [03:49<00:41,  3.69it/s]

[848/1000]  raw='pass'  →  Pass

 85%|████████▍ | 849/1000 [03:49<00:41,  3.67it/s]

[849/1000]  raw='pass'  →  Pass

 85%|████████▌ | 850/1000 [03:49<00:41,  3.66it/s]

[850/1000]  raw='fail'  →  Fail

 85%|████████▌ | 851/1000 [03:50<00:40,  3.66it/s]

[851/1000]  raw='pass'  →  Pass

 85%|████████▌ | 852/1000 [03:50<00:40,  3.67it/s]

[852/1000]  raw='pass'  →  Pass

 85%|████████▌ | 853/1000 [03:50<00:39,  3.68it/s]

[853/1000]  raw='fail'  →  Fail

 85%|████████▌ | 854/1000 [03:50<00:39,  3.69it/s]

[854/1000]  raw='pass'  →  Pass

 86%|████████▌ | 855/1000 [03:51<00:38,  3.73it/s]

[855/1000]  raw='fail'  →  Fail

 86%|████████▌ | 856/1000 [03:51<00:38,  3.73it/s]

[856/1000]  raw='pass'  →  Pass

 86%|████████▌ | 857/1000 [03:51<00:38,  3.75it/s]

[857/1000]  raw='pass'  →  Pass

 86%|████████▌ | 858/1000 [03:51<00:37,  3.76it/s]

[858/1000]  raw='fail'  →  Fail

 86%|████████▌ | 859/1000 [03:52<00:37,  3.76it/s]

[859/1000]  raw='pass'  →  Pass

 86%|████████▌ | 860/1000 [03:52<00:37,  3.76it/s]

[860/1000]  raw='pass'  →  Pass

 86%|████████▌ | 861/1000 [03:52<00:36,  3.77it/s]

[861/1000]  raw='fail'  →  Fail

 86%|████████▌ | 862/1000 [03:52<00:36,  3.78it/s]

[862/1000]  raw='pass'  →  Pass

 86%|████████▋ | 863/1000 [03:53<00:36,  3.77it/s]

[863/1000]  raw='fail'  →  Fail

 86%|████████▋ | 864/1000 [03:53<00:36,  3.77it/s]

[864/1000]  raw='fail'  →  Fail

 86%|████████▋ | 865/1000 [03:53<00:35,  3.77it/s]

[865/1000]  raw='pass'  →  Pass

 87%|████████▋ | 866/1000 [03:54<00:35,  3.78it/s]

[866/1000]  raw='fail'  →  Fail

 87%|████████▋ | 867/1000 [03:54<00:35,  3.78it/s]

[867/1000]  raw='fail'  →  Fail

 87%|████████▋ | 868/1000 [03:54<00:34,  3.78it/s]

[868/1000]  raw='pass'  →  Pass

 87%|████████▋ | 869/1000 [03:54<00:34,  3.78it/s]

[869/1000]  raw='pass'  →  Pass

 87%|████████▋ | 870/1000 [03:55<00:34,  3.78it/s]

[870/1000]  raw='pass'  →  Pass

 87%|████████▋ | 871/1000 [03:55<00:33,  3.80it/s]

[871/1000]  raw='fail'  →  Fail

 87%|████████▋ | 872/1000 [03:55<00:33,  3.79it/s]

[872/1000]  raw='fail'  →  Fail

 87%|████████▋ | 873/1000 [03:55<00:33,  3.79it/s]

[873/1000]  raw='fail'  →  Fail

 87%|████████▋ | 874/1000 [03:56<00:33,  3.79it/s]

[874/1000]  raw='fail'  →  Fail

 88%|████████▊ | 875/1000 [03:56<00:32,  3.79it/s]

[875/1000]  raw='fail'  →  Fail

 88%|████████▊ | 876/1000 [03:56<00:32,  3.79it/s]

[876/1000]  raw='fail'  →  Fail

 88%|████████▊ | 877/1000 [03:56<00:32,  3.79it/s]

[877/1000]  raw='fail'  →  Fail

 88%|████████▊ | 878/1000 [03:57<00:32,  3.80it/s]

[878/1000]  raw='fail'  →  Fail

 88%|████████▊ | 879/1000 [03:57<00:31,  3.80it/s]

[879/1000]  raw='fail'  →  Fail

 88%|████████▊ | 880/1000 [03:57<00:31,  3.80it/s]

[880/1000]  raw='pass'  →  Pass

 88%|████████▊ | 881/1000 [03:58<00:31,  3.77it/s]

[881/1000]  raw='fail'  →  Fail

 88%|████████▊ | 882/1000 [03:58<00:31,  3.74it/s]

[882/1000]  raw='fail'  →  Fail

 88%|████████▊ | 883/1000 [03:58<00:31,  3.72it/s]

[883/1000]  raw='pass'  →  Pass

 88%|████████▊ | 884/1000 [03:58<00:31,  3.70it/s]

[884/1000]  raw='pass'  →  Pass

 88%|████████▊ | 885/1000 [03:59<00:31,  3.69it/s]

[885/1000]  raw='fail'  →  Fail

 89%|████████▊ | 886/1000 [03:59<00:30,  3.69it/s]

[886/1000]  raw='fail'  →  Fail

 89%|████████▊ | 887/1000 [03:59<00:30,  3.68it/s]

[887/1000]  raw='pass'  →  Pass

 89%|████████▉ | 888/1000 [03:59<00:30,  3.67it/s]

[888/1000]  raw='fail'  →  Fail

 89%|████████▉ | 889/1000 [04:00<00:30,  3.65it/s]

[889/1000]  raw='pass'  →  Pass

 89%|████████▉ | 890/1000 [04:00<00:30,  3.65it/s]

[890/1000]  raw='pass'  →  Pass

 89%|████████▉ | 891/1000 [04:00<00:29,  3.64it/s]

[891/1000]  raw='fail'  →  Fail

 89%|████████▉ | 892/1000 [04:01<00:29,  3.64it/s]

[892/1000]  raw='fail'  →  Fail

 89%|████████▉ | 893/1000 [04:01<00:29,  3.67it/s]

[893/1000]  raw='fail'  →  Fail

 89%|████████▉ | 894/1000 [04:01<00:28,  3.70it/s]

[894/1000]  raw='fail'  →  Fail

 90%|████████▉ | 895/1000 [04:01<00:28,  3.72it/s]

[895/1000]  raw='fail'  →  Fail

 90%|████████▉ | 896/1000 [04:02<00:27,  3.72it/s]

[896/1000]  raw='pass'  →  Pass

 90%|████████▉ | 897/1000 [04:02<00:27,  3.73it/s]

[897/1000]  raw='fail'  →  Fail

 90%|████████▉ | 898/1000 [04:02<00:27,  3.74it/s]

[898/1000]  raw='fail'  →  Fail

 90%|████████▉ | 899/1000 [04:02<00:27,  3.71it/s]

[899/1000]  raw='fail'  →  Fail

 90%|█████████ | 900/1000 [04:03<00:26,  3.71it/s]

[900/1000]  raw='pass'  →  Pass

 90%|█████████ | 901/1000 [04:03<00:26,  3.68it/s]

[901/1000]  raw='pass'  →  Pass

 90%|█████████ | 902/1000 [04:03<00:26,  3.67it/s]

[902/1000]  raw='fail'  →  Fail

 90%|█████████ | 903/1000 [04:03<00:26,  3.68it/s]

[903/1000]  raw='fail'  →  Fail

 90%|█████████ | 904/1000 [04:04<00:26,  3.69it/s]

[904/1000]  raw='fail'  →  Fail

 90%|█████████ | 905/1000 [04:04<00:25,  3.68it/s]

[905/1000]  raw='fail'  →  Fail

 91%|█████████ | 906/1000 [04:04<00:25,  3.67it/s]

[906/1000]  raw='pass'  →  Pass

 91%|█████████ | 907/1000 [04:05<00:25,  3.67it/s]

[907/1000]  raw='pass'  →  Pass

 91%|█████████ | 908/1000 [04:05<00:24,  3.68it/s]

[908/1000]  raw='pass'  →  Pass

 91%|█████████ | 909/1000 [04:05<00:24,  3.69it/s]

[909/1000]  raw='fail'  →  Fail

 91%|█████████ | 910/1000 [04:05<00:24,  3.70it/s]

[910/1000]  raw='fail'  →  Fail

 91%|█████████ | 911/1000 [04:06<00:24,  3.71it/s]

[911/1000]  raw='fail'  →  Fail

 91%|█████████ | 912/1000 [04:06<00:23,  3.70it/s]

[912/1000]  raw='pass'  →  Pass

 91%|█████████▏| 913/1000 [04:06<00:23,  3.70it/s]

[913/1000]  raw='fail'  →  Fail

 91%|█████████▏| 914/1000 [04:06<00:23,  3.71it/s]

[914/1000]  raw='fail'  →  Fail

 92%|█████████▏| 915/1000 [04:07<00:22,  3.72it/s]

[915/1000]  raw='fail'  →  Fail

 92%|█████████▏| 916/1000 [04:07<00:22,  3.72it/s]

[916/1000]  raw='pass'  →  Pass

 92%|█████████▏| 917/1000 [04:07<00:22,  3.71it/s]

[917/1000]  raw='fail'  →  Fail

 92%|█████████▏| 918/1000 [04:08<00:22,  3.72it/s]

[918/1000]  raw='pass'  →  Pass

 92%|█████████▏| 919/1000 [04:08<00:21,  3.74it/s]

[919/1000]  raw='pass'  →  Pass

 92%|█████████▏| 920/1000 [04:08<00:21,  3.72it/s]

[920/1000]  raw='pass'  →  Pass

 92%|█████████▏| 921/1000 [04:08<00:21,  3.72it/s]

[921/1000]  raw='fail'  →  Fail

 92%|█████████▏| 922/1000 [04:09<00:21,  3.71it/s]

[922/1000]  raw='fail'  →  Fail

 92%|█████████▏| 923/1000 [04:09<00:20,  3.70it/s]

[923/1000]  raw='fail'  →  Fail

 92%|█████████▏| 924/1000 [04:09<00:20,  3.69it/s]

[924/1000]  raw='fail'  →  Fail

 92%|█████████▎| 925/1000 [04:09<00:20,  3.72it/s]

[925/1000]  raw='fail'  →  Fail

 93%|█████████▎| 926/1000 [04:10<00:19,  3.74it/s]

[926/1000]  raw='pass'  →  Pass

 93%|█████████▎| 927/1000 [04:10<00:19,  3.77it/s]

[927/1000]  raw='fail'  →  Fail

 93%|█████████▎| 928/1000 [04:10<00:19,  3.75it/s]

[928/1000]  raw='pass'  →  Pass

 93%|█████████▎| 929/1000 [04:10<00:18,  3.74it/s]

[929/1000]  raw='fail'  →  Fail

 93%|█████████▎| 930/1000 [04:11<00:18,  3.72it/s]

[930/1000]  raw='fail'  →  Fail

 93%|█████████▎| 931/1000 [04:11<00:18,  3.71it/s]

[931/1000]  raw='fail'  →  Fail

 93%|█████████▎| 932/1000 [04:11<00:18,  3.71it/s]

[932/1000]  raw='pass'  →  Pass

 93%|█████████▎| 933/1000 [04:12<00:18,  3.72it/s]

[933/1000]  raw='fail'  →  Fail

 93%|█████████▎| 934/1000 [04:12<00:17,  3.72it/s]

[934/1000]  raw='pass'  →  Pass

 94%|█████████▎| 935/1000 [04:12<00:17,  3.72it/s]

[935/1000]  raw='fail'  →  Fail

 94%|█████████▎| 936/1000 [04:12<00:17,  3.72it/s]

[936/1000]  raw='fail'  →  Fail

 94%|█████████▎| 937/1000 [04:13<00:17,  3.70it/s]

[937/1000]  raw='fail'  →  Fail

 94%|█████████▍| 938/1000 [04:13<00:16,  3.70it/s]

[938/1000]  raw='fail'  →  Fail

 94%|█████████▍| 939/1000 [04:13<00:16,  3.70it/s]

[939/1000]  raw='pass'  →  Pass

 94%|█████████▍| 940/1000 [04:13<00:16,  3.72it/s]

[940/1000]  raw='fail'  →  Fail

 94%|█████████▍| 941/1000 [04:14<00:15,  3.73it/s]

[941/1000]  raw='fail'  →  Fail

 94%|█████████▍| 942/1000 [04:14<00:15,  3.72it/s]

[942/1000]  raw='fail'  →  Fail

 94%|█████████▍| 943/1000 [04:14<00:15,  3.71it/s]

[943/1000]  raw='pass'  →  Pass

 94%|█████████▍| 944/1000 [04:15<00:15,  3.71it/s]

[944/1000]  raw='pass'  →  Pass

 94%|█████████▍| 945/1000 [04:15<00:14,  3.72it/s]

[945/1000]  raw='fail'  →  Fail

 95%|█████████▍| 946/1000 [04:15<00:14,  3.73it/s]

[946/1000]  raw='fail'  →  Fail

 95%|█████████▍| 947/1000 [04:15<00:14,  3.72it/s]

[947/1000]  raw='fail'  →  Fail

 95%|█████████▍| 948/1000 [04:16<00:13,  3.73it/s]

[948/1000]  raw='fail'  →  Fail

 95%|█████████▍| 949/1000 [04:16<00:13,  3.72it/s]

[949/1000]  raw='fail'  →  Fail

 95%|█████████▌| 950/1000 [04:16<00:13,  3.71it/s]

[950/1000]  raw='pass'  →  Pass

 95%|█████████▌| 951/1000 [04:16<00:13,  3.71it/s]

[951/1000]  raw='fail'  →  Fail

 95%|█████████▌| 952/1000 [04:17<00:12,  3.71it/s]

[952/1000]  raw='fail'  →  Fail

 95%|█████████▌| 953/1000 [04:17<00:12,  3.71it/s]

[953/1000]  raw='pass'  →  Pass

 95%|█████████▌| 954/1000 [04:17<00:12,  3.70it/s]

[954/1000]  raw='fail'  →  Fail

 96%|█████████▌| 955/1000 [04:17<00:12,  3.71it/s]

[955/1000]  raw='fail'  →  Fail

 96%|█████████▌| 956/1000 [04:18<00:11,  3.70it/s]

[956/1000]  raw='fail'  →  Fail

 96%|█████████▌| 957/1000 [04:18<00:11,  3.71it/s]

[957/1000]  raw='fail'  →  Fail

 96%|█████████▌| 958/1000 [04:18<00:11,  3.72it/s]

[958/1000]  raw='fail'  →  Fail

 96%|█████████▌| 959/1000 [04:19<00:11,  3.72it/s]

[959/1000]  raw='fail'  →  Fail

 96%|█████████▌| 960/1000 [04:19<00:10,  3.71it/s]

[960/1000]  raw='pass'  →  Pass

 96%|█████████▌| 961/1000 [04:19<00:10,  3.70it/s]

[961/1000]  raw='fail'  →  Fail

 96%|█████████▌| 962/1000 [04:19<00:10,  3.69it/s]

[962/1000]  raw='fail'  →  Fail

 96%|█████████▋| 963/1000 [04:20<00:10,  3.68it/s]

[963/1000]  raw='fail'  →  Fail

 96%|█████████▋| 964/1000 [04:20<00:09,  3.68it/s]

[964/1000]  raw='fail'  →  Fail

 96%|█████████▋| 965/1000 [04:20<00:09,  3.66it/s]

[965/1000]  raw='pass'  →  Pass

 97%|█████████▋| 966/1000 [04:20<00:09,  3.67it/s]

[966/1000]  raw='fail'  →  Fail

 97%|█████████▋| 967/1000 [04:21<00:09,  3.65it/s]

[967/1000]  raw='pass'  →  Pass

 97%|█████████▋| 968/1000 [04:21<00:08,  3.66it/s]

[968/1000]  raw='pass'  →  Pass

 97%|█████████▋| 969/1000 [04:21<00:08,  3.65it/s]

[969/1000]  raw='fail'  →  Fail

 97%|█████████▋| 970/1000 [04:22<00:08,  3.65it/s]

[970/1000]  raw='fail'  →  Fail

 97%|█████████▋| 971/1000 [04:22<00:07,  3.68it/s]

[971/1000]  raw='pass'  →  Pass

 97%|█████████▋| 972/1000 [04:22<00:07,  3.68it/s]

[972/1000]  raw='fail'  →  Fail

 97%|█████████▋| 973/1000 [04:22<00:07,  3.69it/s]

[973/1000]  raw='pass'  →  Pass

 97%|█████████▋| 974/1000 [04:23<00:07,  3.70it/s]

[974/1000]  raw='pass'  →  Pass

 98%|█████████▊| 975/1000 [04:23<00:06,  3.70it/s]

[975/1000]  raw='fail'  →  Fail

 98%|█████████▊| 976/1000 [04:23<00:06,  3.68it/s]

[976/1000]  raw='fail'  →  Fail

 98%|█████████▊| 977/1000 [04:23<00:06,  3.68it/s]

[977/1000]  raw='pass'  →  Pass

 98%|█████████▊| 978/1000 [04:24<00:05,  3.68it/s]

[978/1000]  raw='fail'  →  Fail

 98%|█████████▊| 979/1000 [04:24<00:05,  3.67it/s]

[979/1000]  raw='pass'  →  Pass

 98%|█████████▊| 980/1000 [04:24<00:05,  3.64it/s]

[980/1000]  raw='fail'  →  Fail

 98%|█████████▊| 981/1000 [04:25<00:05,  3.66it/s]

[981/1000]  raw='fail'  →  Fail

 98%|█████████▊| 982/1000 [04:25<00:04,  3.66it/s]

[982/1000]  raw='fail'  →  Fail

 98%|█████████▊| 983/1000 [04:25<00:04,  3.65it/s]

[983/1000]  raw='pass'  →  Pass

 98%|█████████▊| 984/1000 [04:25<00:04,  3.65it/s]

[984/1000]  raw='fail'  →  Fail

 98%|█████████▊| 985/1000 [04:26<00:04,  3.67it/s]

[985/1000]  raw='pass'  →  Pass

 99%|█████████▊| 986/1000 [04:26<00:03,  3.70it/s]

[986/1000]  raw='pass'  →  Pass

 99%|█████████▊| 987/1000 [04:26<00:03,  3.71it/s]

[987/1000]  raw='pass'  →  Pass

 99%|█████████▉| 988/1000 [04:26<00:03,  3.73it/s]

[988/1000]  raw='pass'  →  Pass

 99%|█████████▉| 989/1000 [04:27<00:02,  3.74it/s]

[989/1000]  raw='pass'  →  Pass

 99%|█████████▉| 990/1000 [04:27<00:02,  3.76it/s]

[990/1000]  raw='fail'  →  Fail

 99%|█████████▉| 991/1000 [04:27<00:02,  3.77it/s]

[991/1000]  raw='fail'  →  Fail

 99%|█████████▉| 992/1000 [04:28<00:02,  3.77it/s]

[992/1000]  raw='fail'  →  Fail

 99%|█████████▉| 993/1000 [04:28<00:01,  3.77it/s]

[993/1000]  raw='pass'  →  Pass

 99%|█████████▉| 994/1000 [04:28<00:01,  3.77it/s]

[994/1000]  raw='fail'  →  Fail

100%|█████████▉| 995/1000 [04:28<00:01,  3.78it/s]

[995/1000]  raw='fail'  →  Fail

100%|█████████▉| 996/1000 [04:29<00:01,  3.79it/s]

[996/1000]  raw='pass'  →  Pass

100%|█████████▉| 997/1000 [04:29<00:00,  3.80it/s]

[997/1000]  raw='pass'  →  Pass

100%|█████████▉| 998/1000 [04:29<00:00,  3.79it/s]

[998/1000]  raw='fail'  →  Fail

100%|█████████▉| 999/1000 [04:29<00:00,  3.77it/s]

[999/1000]  raw='pass'  →  Pass

100%|██████████| 1000/1000 [04:30<00:00,  3.70it/s]

[1000/1000]  raw='fail'  →  Fail

In [ ]:
# Step 5: evaluate now y_true, y_pred, y_generated all exist
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         1       1      pass         Pass         Pass
1         0       0      fail         Fail         Fail
2         0       0      fail         Fail         Fail
3         1       1      pass         Pass         Pass
4         0       0      fail         Fail         Fail
5         1       1      pass         Pass         Pass
6         0       1      pass         Fail         Pass
7         0       0      fail         Fail         Fail
8         0       0      fail         Fail         Fail
9         0       0      fail         Fail         Fail
10        0       0      fail         Fail         Fail
11        0       0      fail         Fail         Fail
12        0       1      pass         Fail         Pass
13        1       0      fail         Pass         Fail
14        1       1      pass         Pass         Pass
15        1       1      pass         Pass         Pass
16        1       1      pass         Pass         Pass
17        0       0      fail         Fail         Fail
18        1       1      pass         Pass         Pass
19        1       1      pass         Pass         Pass
20        0       0      fail         Fail         Fail
21        1       1      pass         Pass         Pass
22        1       1      pass         Pass         Pass
23        1       1      pass         Pass         Pass
24        1       0      fail         Pass         Fail
25        1       1      pass         Pass         Pass
26        1       1      pass         Pass         Pass
27        0       0      fail         Fail         Fail
28        0       1      pass         Fail         Pass
29        1       1      pass         Pass         Pass
30        0       1      pass         Fail         Pass
31        1       1      pass         Pass         Pass
32        0       1      pass         Fail         Pass
33        0       0      fail         Fail         Fail
34        1       1      pass         Pass         Pass
35        0       0      fail         Fail         Fail
36        1       1      pass         Pass         Pass
37        0       0      fail         Fail         Fail
38        0       0      fail         Fail         Fail
39        1       1      pass         Pass         Pass
40        0       0      fail         Fail         Fail
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        0       0      fail         Fail         Fail
44        0       0      fail         Fail         Fail
45        0       0      fail         Fail         Fail
46        0       0      fail         Fail         Fail
47        0       0      fail         Fail         Fail
48        0       0      fail         Fail         Fail
49        0       0      fail         Fail         Fail
50        1       1      pass         Pass         Pass
51        0       0      fail         Fail         Fail
52        1       1      pass         Pass         Pass
53        1       1      pass         Pass         Pass
54        1       1      pass         Pass         Pass
55        1       1      pass         Pass         Pass
56        1       0      fail         Pass         Fail
57        1       1      pass         Pass         Pass
58        1       1      pass         Pass         Pass
59        1       1      pass         Pass         Pass
60        1       1      pass         Pass         Pass
61        0       0      fail         Fail         Fail
62        0       0      fail         Fail         Fail
63        0       1      pass         Fail         Pass
64        1       1      pass         Pass         Pass
65        0       0      fail         Fail         Fail
66        1       1      pass         Pass         Pass
67        0       0      fail         Fail         Fail
68        0       0      fail         Fail         Fail
69        0       0      fail         Fail         Fail
70        0       0      fail         Fail         Fail
71        0       0      fail         Fail         Fail
72        0       0      fail         Fail         Fail
73        1       1      pass         Pass         Pass
74        1       1      pass         Pass         Pass
75        0       0      fail         Fail         Fail
76        0       0      fail         Fail         Fail
77        1       1      pass         Pass         Pass
78        0       1      pass         Fail         Pass
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        1       1      pass         Pass         Pass
82        0       0      fail         Fail         Fail
83        0       1      pass         Fail         Pass
84        0       0      fail         Fail         Fail
85        0       0      fail         Fail         Fail
86        1       1      pass         Pass         Pass
87        1       1      pass         Pass         Pass
88        0       0      fail         Fail         Fail
89        0       0      fail         Fail         Fail
90        1       1      pass         Pass         Pass
91        1       1      pass         Pass         Pass
92        1       0      fail         Pass         Fail
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       0      fail         Fail         Fail
96        1       0      fail         Pass         Fail
97        0       0      fail         Fail         Fail
98        1       1      pass         Pass         Pass
99        0       0      fail         Fail         Fail
100       0       0      fail         Fail         Fail
101       0       0      fail         Fail         Fail
102       1       1      pass         Pass         Pass
103       1       1      pass         Pass         Pass
104       0       0      fail         Fail         Fail
105       0       0      fail         Fail         Fail
106       1       1      pass         Pass         Pass
107       0       0      fail         Fail         Fail
108       0       1      pass         Fail         Pass
109       0       0      fail         Fail         Fail
110       0       1      pass         Fail         Pass
111       1       1      pass         Pass         Pass
112       1       1      pass         Pass         Pass
113       0       0      fail         Fail         Fail
114       1       1      pass         Pass         Pass
115       1       1      pass         Pass         Pass
116       0       0      fail         Fail         Fail
117       0       0      fail         Fail         Fail
118       1       1      pass         Pass         Pass
119       0       0      fail         Fail         Fail
120       0       0      fail         Fail         Fail
121       1       1      pass         Pass         Pass
122       0       0      fail         Fail         Fail
123       1       1      pass         Pass         Pass
124       1       1      pass         Pass         Pass
125       0       0      fail         Fail         Fail
126       0       0      fail         Fail         Fail
127       1       1      pass         Pass         Pass
128       0       0      fail         Fail         Fail
129       1       1      pass         Pass         Pass
130       0       0      fail         Fail         Fail
131       0       0      fail         Fail         Fail
132       1       1      pass         Pass         Pass
133       1       1      pass         Pass         Pass
134       0       0      fail         Fail         Fail
135       1       1      pass         Pass         Pass
136       0       0      fail         Fail         Fail
137       0       0      fail         Fail         Fail
138       0       0      fail         Fail         Fail
139       0       0      fail         Fail         Fail
140       1       1      pass         Pass         Pass
141       1       1      pass         Pass         Pass
142       0       0      fail         Fail         Fail
143       0       0      fail         Fail         Fail
144       1       1      pass         Pass         Pass
145       0       0      fail         Fail         Fail
146       0       0      fail         Fail         Fail
147       0       0      fail         Fail         Fail
148       0       0      fail         Fail         Fail
149       1       1      pass         Pass         Pass
150       0       0      fail         Fail         Fail
151       0       0      fail         Fail         Fail
152       1       1      pass         Pass         Pass
153       0       0      fail         Fail         Fail
154       0       0      fail         Fail         Fail
155       1       1      pass         Pass         Pass
156       1       1      pass         Pass         Pass
157       0       0      fail         Fail         Fail
158       0       0      fail         Fail         Fail
159       1       1      pass         Pass         Pass
160       0       1      pass         Fail         Pass
161       1       1      pass         Pass         Pass
162       0       0      fail         Fail         Fail
163       1       1      pass         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0      fail         Fail         Fail
166       1       1      pass         Pass         Pass
167       1       1      pass         Pass         Pass
168       1       1      pass         Pass         Pass
169       1       1      pass         Pass         Pass
170       0       0      fail         Fail         Fail
171       0       0      fail         Fail         Fail
172       0       1      pass         Fail         Pass
173       1       1      pass         Pass         Pass
174       1       1      pass         Pass         Pass
175       1       1      pass         Pass         Pass
176       1       1      pass         Pass         Pass
177       0       0      fail         Fail         Fail
178       0       0      fail         Fail         Fail
179       0       0      fail         Fail         Fail
180       0       0      fail         Fail         Fail
181       0       0      fail         Fail         Fail
182       0       1      pass         Fail         Pass
183       0       0      fail         Fail         Fail
184       0       0      fail         Fail         Fail
185       0       0      fail         Fail         Fail
186       1       1      pass         Pass         Pass
187       0       0      fail         Fail         Fail
188       0       0      fail         Fail         Fail
189       1       1      pass         Pass         Pass
190       1       1      pass         Pass         Pass
191       1       1      pass         Pass         Pass
192       0       0      fail         Fail         Fail
193       0       0      fail         Fail         Fail
194       1       1      pass         Pass         Pass
195       1       1      pass         Pass         Pass
196       0       1      pass         Fail         Pass
197       0       1      pass         Fail         Pass
198       1       1      pass         Pass         Pass
199       1       1      pass         Pass         Pass
200       0       1      pass         Fail         Pass
201       0       1      pass         Fail         Pass
202       0       1      pass         Fail         Pass
203       0       0      fail         Fail         Fail
204       1       1      pass         Pass         Pass
205       0       1      pass         Fail         Pass
206       0       0      fail         Fail         Fail
207       0       0      fail         Fail         Fail
208       1       0      fail         Pass         Fail
209       1       1      pass         Pass         Pass
210       0       0      fail         Fail         Fail
211       0       0      fail         Fail         Fail
212       0       0      fail         Fail         Fail
213       1       1      pass         Pass         Pass
214       0       1      pass         Fail         Pass
215       1       1      pass         Pass         Pass
216       0       0      fail         Fail         Fail
217       1       1      pass         Pass         Pass
218       1       1      pass         Pass         Pass
219       1       1      pass         Pass         Pass
220       1       1      pass         Pass         Pass
221       1       1      pass         Pass         Pass
222       1       1      pass         Pass         Pass
223       0       0      fail         Fail         Fail
224       0       0      fail         Fail         Fail
225       1       1      pass         Pass         Pass
226       1       1      pass         Pass         Pass
227       1       1      pass         Pass         Pass
228       0       0      fail         Fail         Fail
229       0       0      fail         Fail         Fail
230       0       1      pass         Fail         Pass
231       1       1      pass         Pass         Pass
232       0       0      fail         Fail         Fail
233       1       1      pass         Pass         Pass
234       0       1      pass         Fail         Pass
235       1       1      pass         Pass         Pass
236       0       0      fail         Fail         Fail
237       1       1      pass         Pass         Pass
238       0       0      fail         Fail         Fail
239       1       1      pass         Pass         Pass
240       1       0      fail         Pass         Fail
241       0       0      fail         Fail         Fail
242       0       0      fail         Fail         Fail
243       1       1      pass         Pass         Pass
244       1       1      pass         Pass         Pass
245       1       1      pass         Pass         Pass
246       0       0      fail         Fail         Fail
247       0       0      fail         Fail         Fail
248       0       0      fail         Fail         Fail
249       1       1      pass         Pass         Pass
250       0       0      fail         Fail         Fail
251       1       1      pass         Pass         Pass
252       1       1      pass         Pass         Pass
253       0       0      fail         Fail         Fail
254       0       0      fail         Fail         Fail
255       1       1      pass         Pass         Pass
256       0       1      pass         Fail         Pass
257       1       1      pass         Pass         Pass
258       0       0      fail         Fail         Fail
259       1       0      fail         Pass         Fail
260       1       1      pass         Pass         Pass
261       1       1      pass         Pass         Pass
262       1       1      pass         Pass         Pass
263       1       1      pass         Pass         Pass
264       0       0      fail         Fail         Fail
265       1       1      pass         Pass         Pass
266       0       1      pass         Fail         Pass
267       0       0      fail         Fail         Fail
268       1       1      pass         Pass         Pass
269       0       0      fail         Fail         Fail
270       0       1      pass         Fail         Pass
271       1       1      pass         Pass         Pass
272       0       1      pass         Fail         Pass
273       0       0      fail         Fail         Fail
274       0       0      fail         Fail         Fail
275       0       1      pass         Fail         Pass
276       0       0      fail         Fail         Fail
277       1       0      fail         Pass         Fail
278       0       0      fail         Fail         Fail
279       1       1      pass         Pass         Pass
280       1       1      pass         Pass         Pass
281       0       0      fail         Fail         Fail
282       0       1      pass         Fail         Pass
283       0       0      fail         Fail         Fail
284       0       0      fail         Fail         Fail
285       0       0      fail         Fail         Fail
286       1       1      pass         Pass         Pass
287       1       1      pass         Pass         Pass
288       0       1      pass         Fail         Pass
289       1       1      pass         Pass         Pass
290       1       1      pass         Pass         Pass
291       1       1      pass         Pass         Pass
292       0       0      fail         Fail         Fail
293       0       1      pass         Fail         Pass
294       1       1      pass         Pass         Pass
295       1       1      pass         Pass         Pass
296       0       1      pass         Fail         Pass
297       0       0      fail         Fail         Fail
298       0       0      fail         Fail         Fail
299       1       1      pass         Pass         Pass
300       1       1      pass         Pass         Pass
301       1       1      pass         Pass         Pass
302       0       0      fail         Fail         Fail
303       0       0      fail         Fail         Fail
304       0       1      pass         Fail         Pass
305       1       1      pass         Pass         Pass
306       1       1      pass         Pass         Pass
307       0       0      fail         Fail         Fail
308       0       0      fail         Fail         Fail
309       0       0      fail         Fail         Fail
310       1       1      pass         Pass         Pass
311       1       1      pass         Pass         Pass
312       0       0      fail         Fail         Fail
313       1       1      pass         Pass         Pass
314       1       1      pass         Pass         Pass
315       0       0      fail         Fail         Fail
316       1       1      pass         Pass         Pass
317       0       0      fail         Fail         Fail
318       0       0      fail         Fail         Fail
319       0       0      fail         Fail         Fail
320       1       1      pass         Pass         Pass
321       1       1      pass         Pass         Pass
322       0       0      fail         Fail         Fail
323       0       0      fail         Fail         Fail
324       0       0      fail         Fail         Fail
325       1       0      fail         Pass         Fail
326       0       0      fail         Fail         Fail
327       0       0      fail         Fail         Fail
328       0       0      fail         Fail         Fail
329       0       1      pass         Fail         Pass
330       0       0      fail         Fail         Fail
331       1       1      pass         Pass         Pass
332       1       1      pass         Pass         Pass
333       0       0      fail         Fail         Fail
334       1       1      pass         Pass         Pass
335       0       0      fail         Fail         Fail
336       0       0      fail         Fail         Fail
337       0       0      fail         Fail         Fail
338       0       0      fail         Fail         Fail
339       0       1      pass         Fail         Pass
340       1       1      pass         Pass         Pass
341       0       0      fail         Fail         Fail
342       0       1      pass         Fail         Pass
343       0       0      fail         Fail         Fail
344       1       1      pass         Pass         Pass
345       1       1      pass         Pass         Pass
346       0       0      fail         Fail         Fail
347       0       0      fail         Fail         Fail
348       1       1      pass         Pass         Pass
349       1       1      pass         Pass         Pass
350       0       0      fail         Fail         Fail
351       1       0      fail         Pass         Fail
352       0       0      fail         Fail         Fail
353       0       0      fail         Fail         Fail
354       0       0      fail         Fail         Fail
355       1       1      pass         Pass         Pass

In [ ]:
# Cell 1: installs
!pip install -q transformers peft trl bitsandbytes accelerate datasets kagglehub

In [ ]:
# Cell 2: imports
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel
import torch, shutil, os, pandas as pd
from google.colab import drive
from tqdm import tqdm

In [ ]:
# Cell 3: copy adapter from Drive to local
drive.mount("/content/drive")

# get exact folder name
print("phi2 folders in Drive:")
for f in os.listdir("/content/drive/MyDrive"):
    if "phi2" in f.lower() or "lora" in f.lower():
        print(f"  → '{f}'")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
phi2 folders in Drive:
  → 'phi2-lora-balanced-adapter'

In [ ]:
# Cell 4: copy to local disk
DRIVE_ADAPTER_PATH = "/content/drive/MyDrive/phi2-lora-balanced-adapter"  # confirm name from Cell 3
LOCAL_ADAPTER_PATH = "./phi2-lora-balanced-adapter"

if not os.path.exists(LOCAL_ADAPTER_PATH):
    shutil.copytree(DRIVE_ADAPTER_PATH, LOCAL_ADAPTER_PATH)
    print(f"Copied from Drive to local")
else:
    print(f"Already exists locally")

print(f"Files: {os.listdir(LOCAL_ADAPTER_PATH)}")
# should show: adapter_model.safetensors, adapter_config.json, tokenizer files

In [ ]:
# Cell 5: load base model + adapter
MODEL_NAME = "microsoft/phi-2"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"     # left padding for inference

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.float16,
)
ft_model = PeftModel.from_pretrained(base_model, LOCAL_ADAPTER_PATH)
ft_model.eval()

print(" Model ready")
print("   Device :", next(ft_model.parameters()).device)
print("   Memory :", round(ft_model.get_memory_footprint() / 1e6, 1), "MB")

In [ ]:
# Cell 6: prompt function
def generate_phi2_test_prompt(row):
    instruction = (
        f"Instruct: You are a reasonable essay grader.\n"
        f"Prompt name: {row['prompt_name']}\n"
        f"Task type: {row['task']}\n\n"
        f"Classify the essay as Pass or Fail.\n"
        f"Pass = proficient or above. Fail = developing or below.\n"
        f"Respond with one word only: Pass or Fail.\n\n"
        f"Essay: "
    )
    suffix = "\nOutput:"

    instruction_tokens = tokenizer(instruction, return_tensors="pt")["input_ids"].shape[1]
    suffix_tokens      = tokenizer(suffix,      return_tensors="pt")["input_ids"].shape[1]
    essay_budget       = 512 - instruction_tokens - suffix_tokens - 5

    essay_ids   = tokenizer(row["full_text"], max_length=essay_budget,
                            truncation=True, add_special_tokens=False)["input_ids"]
    essay_trunc = tokenizer.decode(essay_ids, skip_special_tokens=True)
    return instruction + essay_trunc + suffix

## predict_phi
def predict_phi2(test, model, tokenizer, max_input_tokens=512):
    y_pred, y_generated = [], []
    model.eval()

    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]
        inputs = tokenizer(
            prompt, return_tensors="pt",
            truncation=True, max_length=max_input_tokens, padding=False,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=3,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
        generated  = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        result = {1: "Pass", 0: "Fail", -1: "???"}[y_pred[-1]]
        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {result}")

    return y_pred, y_generated

In [ ]:
# Evaluate
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         1       1      pass         Pass         Pass
1         0       0      fail         Fail         Fail
2         0       0      fail         Fail         Fail
3         1       1      pass         Pass         Pass
4         0       0      fail         Fail         Fail
5         1       1      pass         Pass         Pass
6         0       1      pass         Fail         Pass
7         0       0      fail         Fail         Fail
8         0       0      fail         Fail         Fail
9         0       0      fail         Fail         Fail
10        0       0      fail         Fail         Fail
11        0       0      fail         Fail         Fail
12        0       1      pass         Fail         Pass
13        1       0      fail         Pass         Fail
14        1       1      pass         Pass         Pass
15        1       1      pass         Pass         Pass
16        1       1      pass         Pass         Pass
17        0       0      fail         Fail         Fail
18        1       1      pass         Pass         Pass
19        1       1      pass         Pass         Pass
20        0       0      fail         Fail         Fail
21        1       1      pass         Pass         Pass
22        1       1      pass         Pass         Pass
23        1       1      pass         Pass         Pass
24        1       0      fail         Pass         Fail
25        1       1      pass         Pass         Pass
26        1       1      pass         Pass         Pass
27        0       0      fail         Fail         Fail
28        0       1      pass         Fail         Pass
29        1       1      pass         Pass         Pass
30        0       1      pass         Fail         Pass
31        1       1      pass         Pass         Pass
32        0       1      pass         Fail         Pass
33        0       0      fail         Fail         Fail
34        1       1      pass         Pass         Pass
35        0       0      fail         Fail         Fail
36        1       1      pass         Pass         Pass
37        0       0      fail         Fail         Fail
38        0       0      fail         Fail         Fail
39        1       1      pass         Pass         Pass
40        0       0      fail         Fail         Fail
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        0       0      fail         Fail         Fail
44        0       0      fail         Fail         Fail
45        0       0      fail         Fail         Fail
46        0       0      fail         Fail         Fail
47        0       0      fail         Fail         Fail
48        0       0      fail         Fail         Fail
49        0       0      fail         Fail         Fail
50        1       1      pass         Pass         Pass
51        0       0      fail         Fail         Fail
52        1       1      pass         Pass         Pass
53        1       1      pass         Pass         Pass
54        1       1      pass         Pass         Pass
55        1       1      pass         Pass         Pass
56        1       0      fail         Pass         Fail
57        1       1      pass         Pass         Pass
58        1       1      pass         Pass         Pass
59        1       1      pass         Pass         Pass
60        1       1      pass         Pass         Pass
61        0       0      fail         Fail         Fail
62        0       0      fail         Fail         Fail
63        0       1      pass         Fail         Pass
64        1       1      pass         Pass         Pass
65        0       0      fail         Fail         Fail
66        1       1      pass         Pass         Pass
67        0       0      fail         Fail         Fail
68        0       0      fail         Fail         Fail
69        0       0      fail         Fail         Fail
70        0       0      fail         Fail         Fail
71        0       0      fail         Fail         Fail
72        0       0      fail         Fail         Fail
73        1       1      pass         Pass         Pass
74        1       1      pass         Pass         Pass
75        0       0      fail         Fail         Fail
76        0       0      fail         Fail         Fail
77        1       1      pass         Pass         Pass
78        0       1      pass         Fail         Pass
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        1       1      pass         Pass         Pass
82        0       0      fail         Fail         Fail
83        0       1      pass         Fail         Pass
84        0       0      fail         Fail         Fail
85        0       0      fail         Fail         Fail
86        1       1      pass         Pass         Pass
87        1       1      pass         Pass         Pass
88        0       0      fail         Fail         Fail
89        0       0      fail         Fail         Fail
90        1       1      pass         Pass         Pass
91        1       1      pass         Pass         Pass
92        1       0      fail         Pass         Fail
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       0      fail         Fail         Fail
96        1       0      fail         Pass         Fail
97        0       0      fail         Fail         Fail
98        1       1      pass         Pass         Pass
99        0       0      fail         Fail         Fail
100       0       0      fail         Fail         Fail
101       0       0      fail         Fail         Fail
102       1       1      pass         Pass         Pass
103       1       1      pass         Pass         Pass
104       0       0      fail         Fail         Fail
105       0       0      fail         Fail         Fail
106       1       1      pass         Pass         Pass
107       0       0      fail         Fail         Fail
108       0       1      pass         Fail         Pass
109       0       0      fail         Fail         Fail
110       0       1      pass         Fail         Pass
111       1       1      pass         Pass         Pass
112       1       1      pass         Pass         Pass
113       0       0      fail         Fail         Fail
114       1       1      pass         Pass         Pass
115       1       1      pass         Pass         Pass
116       0       0      fail         Fail         Fail
117       0       0      fail         Fail         Fail
118       1       1      pass         Pass         Pass
119       0       0      fail         Fail         Fail
120       0       0      fail         Fail         Fail
121       1       1      pass         Pass         Pass
122       0       0      fail         Fail         Fail
123       1       1      pass         Pass         Pass
124       1       1      pass         Pass         Pass
125       0       0      fail         Fail         Fail
126       0       0      fail         Fail         Fail
127       1       1      pass         Pass         Pass
128       0       0      fail         Fail         Fail
129       1       1      pass         Pass         Pass
130       0       0      fail         Fail         Fail
131       0       0      fail         Fail         Fail
132       1       1      pass         Pass         Pass
133       1       1      pass         Pass         Pass
134       0       0      fail         Fail         Fail
135       1       1      pass         Pass         Pass
136       0       0      fail         Fail         Fail
137       0       0      fail         Fail         Fail
138       0       0      fail         Fail         Fail
139       0       0      fail         Fail         Fail
140       1       1      pass         Pass         Pass
141       1       1      pass         Pass         Pass
142       0       0      fail         Fail         Fail
143       0       0      fail         Fail         Fail
144       1       1      pass         Pass         Pass
145       0       0      fail         Fail         Fail
146       0       0      fail         Fail         Fail
147       0       0      fail         Fail         Fail
148       0       0      fail         Fail         Fail
149       1       1      pass         Pass         Pass
150       0       0      fail         Fail         Fail
151       0       0      fail         Fail         Fail
152       1       1      pass         Pass         Pass
153       0       0      fail         Fail         Fail
154       0       0      fail         Fail         Fail
155       1       1      pass         Pass         Pass
156       1       1      pass         Pass         Pass
157       0       0      fail         Fail         Fail
158       0       0      fail         Fail         Fail
159       1       1      pass         Pass         Pass
160       0       1      pass         Fail         Pass
161       1       1      pass         Pass         Pass
162       0       0      fail         Fail         Fail
163       1       1      pass         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0      fail         Fail         Fail
166       1       1      pass         Pass         Pass
167       1       1      pass         Pass         Pass
168       1       1      pass         Pass         Pass
169       1       1      pass         Pass         Pass
170       0       0      fail         Fail         Fail
171       0       0      fail         Fail         Fail
172       0       1      pass         Fail         Pass
173       1       1      pass         Pass         Pass
174       1       1      pass         Pass         Pass
175       1       1      pass         Pass         Pass
176       1       1      pass         Pass         Pass
177       0       0      fail         Fail         Fail
178       0       0      fail         Fail         Fail
179       0       0      fail         Fail         Fail
180       0       0      fail         Fail         Fail
181       0       0      fail         Fail         Fail
182       0       1      pass         Fail         Pass
183       0       0      fail         Fail         Fail
184       0       0      fail         Fail         Fail
185       0       0      fail         Fail         Fail
186       1       1      pass         Pass         Pass
187       0       0      fail         Fail         Fail
188       0       0      fail         Fail         Fail
189       1       1      pass         Pass         Pass
190       1       1      pass         Pass         Pass
191       1       1      pass         Pass         Pass
192       0       0      fail         Fail         Fail
193       0       0      fail         Fail         Fail
194       1       1      pass         Pass         Pass
195       1       1      pass         Pass         Pass
196       0       1      pass         Fail         Pass
197       0       1      pass         Fail         Pass
198       1       1      pass         Pass         Pass
199       1       1      pass         Pass         Pass
200       0       1      pass         Fail         Pass
201       0       1      pass         Fail         Pass
202       0       1      pass         Fail         Pass
203       0       0      fail         Fail         Fail
204       1       1      pass         Pass         Pass
205       0       1      pass         Fail         Pass
206       0       0      fail         Fail         Fail
207       0       0      fail         Fail         Fail
208       1       0      fail         Pass         Fail
209       1       1      pass         Pass         Pass
210       0       0      fail         Fail         Fail
211       0       0      fail         Fail         Fail
212       0       0      fail         Fail         Fail
213       1       1      pass         Pass         Pass
214       0       1      pass         Fail         Pass
215       1       1      pass         Pass         Pass
216       0       0      fail         Fail         Fail
217       1       1      pass         Pass         Pass
218       1       1      pass         Pass         Pass
219       1       1      pass         Pass         Pass
220       1       1      pass         Pass         Pass
221       1       1      pass         Pass         Pass
222       1       1      pass         Pass         Pass
223       0       0      fail         Fail         Fail
224       0       0      fail         Fail         Fail
225       1       1      pass         Pass         Pass
226       1       1      pass         Pass         Pass
227       1       1      pass         Pass         Pass
228       0       0      fail         Fail         Fail
229       0       0      fail         Fail         Fail
230       0       1      pass         Fail         Pass
231       1       1      pass         Pass         Pass
232       0       0      fail         Fail         Fail
233       1       1      pass         Pass         Pass
234       0       1      pass         Fail         Pass
235       1       1      pass         Pass         Pass
236       0       0      fail         Fail         Fail
237       1       1      pass         Pass         Pass
238       0       0      fail         Fail         Fail
239       1       1      pass         Pass         Pass
240       1       0      fail         Pass         Fail
241       0       0      fail         Fail         Fail
242       0       0      fail         Fail         Fail
243       1       1      pass         Pass         Pass
244       1       1      pass         Pass         Pass
245       1       1      pass         Pass         Pass
246       0       0      fail         Fail         Fail
247       0       0      fail         Fail         Fail
248       0       0      fail         Fail         Fail
249       1       1      pass         Pass         Pass
250       0       0      fail         Fail         Fail
251       1       1      pass         Pass         Pass
252       1       1      pass         Pass         Pass
253       0       0      fail         Fail         Fail
254       0       0      fail         Fail         Fail
255       1       1      pass         Pass         Pass
256       0       1      pass         Fail         Pass
257       1       1      pass         Pass         Pass
258       0       0      fail         Fail         Fail
259       1       0      fail         Pass         Fail
260       1       1      pass         Pass         Pass
261       1       1      pass         Pass         Pass
262       1       1      pass         Pass         Pass
263       1       1      pass         Pass         Pass
264       0       0      fail         Fail         Fail
265       1       1      pass         Pass         Pass
266       0       1      pass         Fail         Pass
267       0       0      fail         Fail         Fail
268       1       1      pass         Pass         Pass
269       0       0      fail         Fail         Fail
270       0       1      pass         Fail         Pass
271       1       1      pass         Pass         Pass
272       0       1      pass         Fail         Pass
273       0       0      fail         Fail         Fail
274       0       0      fail         Fail         Fail
275       0       1      pass         Fail         Pass
276       0       0      fail         Fail         Fail
277       1       0      fail         Pass         Fail
278       0       0      fail         Fail         Fail
279       1       1      pass         Pass         Pass
280       1       1      pass         Pass         Pass
281       0       0      fail         Fail         Fail
282       0       1      pass         Fail         Pass
283       0       0      fail         Fail         Fail
284       0       0      fail         Fail         Fail
285       0       0      fail         Fail         Fail
286       1       1      pass         Pass         Pass
287       1       1      pass         Pass         Pass
288       0       1      pass         Fail         Pass
289       1       1      pass         Pass         Pass
290       1       1      pass         Pass         Pass
291       1       1      pass         Pass         Pass
292       0       0      fail         Fail         Fail
293       0       1      pass         Fail         Pass
294       1       1      pass         Pass         Pass
295       1       1      pass         Pass         Pass
296       0       1      pass         Fail         Pass
297       0       0      fail         Fail         Fail
298       0       0      fail         Fail         Fail
299       1       1      pass         Pass         Pass
300       1       1      pass         Pass         Pass
301       1       1      pass         Pass         Pass
302       0       0      fail         Fail         Fail
303       0       0      fail         Fail         Fail
304       0       1      pass         Fail         Pass
305       1       1      pass         Pass         Pass
306       1       1      pass         Pass         Pass
307       0       0      fail         Fail         Fail
308       0       0      fail         Fail         Fail
309       0       0      fail         Fail         Fail
310       1       1      pass         Pass         Pass
311       1       1      pass         Pass         Pass
312       0       0      fail         Fail         Fail
313       1       1      pass         Pass         Pass
314       1       1      pass         Pass         Pass
315       0       0      fail         Fail         Fail
316       1       1      pass         Pass         Pass
317       0       0      fail         Fail         Fail
318       0       0      fail         Fail         Fail
319       0       0      fail         Fail         Fail
320       1       1      pass         Pass         Pass
321       1       1      pass         Pass         Pass
322       0       0      fail         Fail         Fail
323       0       0      fail         Fail         Fail
324       0       0      fail         Fail         Fail
325       1       0      fail         Pass         Fail
326       0       0      fail         Fail         Fail
327       0       0      fail         Fail         Fail
328       0       0      fail         Fail         Fail
329       0       1      pass         Fail         Pass
330       0       0      fail         Fail         Fail
331       1       1      pass         Pass         Pass
332       1       1      pass         Pass         Pass
333       0       0      fail         Fail         Fail
334       1       1      pass         Pass         Pass
335       0       0      fail         Fail         Fail
336       0       0      fail         Fail         Fail
337       0       0      fail         Fail         Fail
338       0       0      fail         Fail         Fail
339       0       1      pass         Fail         Pass
340       1       1      pass         Pass         Pass
341       0       0      fail         Fail         Fail
342       0       1      pass         Fail         Pass
343       0       0      fail         Fail         Fail
344       1       1      pass         Pass         Pass
345       1       1      pass         Pass         Pass
346       0       0      fail         Fail         Fail
347       0       0      fail         Fail         Fail
348       1       1      pass         Pass         Pass
349       1       1      pass         Pass         Pass
350       0       0      fail         Fail         Fail
351       1       0      fail         Pass         Fail
352       0       0      fail         Fail         Fail
353       0       0      fail         Fail         Fail
354       0       0      fail         Fail         Fail
355       1       1      pass         Pass         Pass

## Llama 3.1 8B Instruct

# Part one

In [ ]:
# Part 1 Llama-3.1-8B-Instruct, 4bit, zero-shot
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch, os, gc

# auth (gated model license must be accepted on the HF page)
from google.colab import userdata
os.environ["HF_TOKEN"] = userdata.get("B-Llama-3.1-8B-Access")   # hf secret's exact name
from huggingface_hub import whoami
print("logged in as:", whoami()["name"])            # verify BEFORE loading

model_name = "meta-llama/Llama-3.1-8B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,   # A100: bf16 compute because we have A100 becareful with this
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
print("pad:", tokenizer.pad_token, tokenizer.pad_token_id,
      "| eos:", tokenizer.eos_token, tokenizer.eos_token_id)

# Llama 3.1 has NO dedicated pad so we can use eos similar eos to TinyLlama/Mistral situation
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"              # inference first

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.pad_token_id = tokenizer.pad_token_id
print("Memory (MB):", round(model.get_memory_footprint() / 1e6, 1))

logged in as: Claudiaventura

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

pad: None None | eos: <|eot_id|> 128009

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

Memory (MB): 5591.5

In [ ]:
# zero-shot: test, then full test-765
one_samsple = X_val_prompts.iloc[:1].reset_index(drop=True)
_, g = predict_decoder_only(one_samsple, model, tokenizer)
print(repr(g[0]))                            # eyeball the raw output first

y_pred, y_generated = predict_decoder_only(X_test_prompts.reset_index(drop=True), model, tokenizer)

pd.DataFrame({"y_true": y_true, "y_pred": y_pred, "generated": y_generated}) \
  .to_csv("/content/drive/MyDrive/llama31_zeroshot_test_results.csv", index=False)

valid = [i for i, p in enumerate(y_pred) if p != -1]
yt = y_true[valid]; yp = [y_pred[i] for i in valid]
print(f"Parsed: {len(valid)}/{len(y_pred)}")
print(f"Accuracy: {accuracy_score(yt, yp):.4f}")
print(classification_report(yt, yp, target_names=["Fail","Pass"]))
print("Predicted-Pass fraction:", (pd.Series(yp)==1).mean(), " (true rate 0.42)")

  0%|          | 0/1 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
100%|██████████| 1/1 [00:00<00:00,  4.53it/s]

[  1/1]  raw='pass'  → → 1
'pass'

  0%|          | 1/765 [00:00<02:13,  5.74it/s]

[  1/765]  raw='pass'  → → 1

  0%|          | 2/765 [00:00<02:11,  5.79it/s]

[  2/765]  raw='pass'  → → 1

  0%|          | 3/765 [00:00<02:10,  5.82it/s]

[  3/765]  raw='fail'  → → 0

  1%|          | 4/765 [00:00<02:17,  5.52it/s]

[  4/765]  raw='pass'  → → 1

  1%|          | 5/765 [00:00<02:15,  5.61it/s]

[  5/765]  raw='fail'  → → 0

  1%|          | 6/765 [00:01<02:15,  5.62it/s]

[  6/765]  raw='pass'  → → 1

  1%|          | 7/765 [00:01<02:14,  5.64it/s]

[  7/765]  raw='pass'  → → 1

  1%|          | 8/765 [00:01<02:12,  5.71it/s]

[  8/765]  raw='fail'  → → 0

  1%|          | 9/765 [00:01<02:17,  5.49it/s]

[  9/765]  raw='pass'  → → 1

  1%|▏         | 10/765 [00:01<02:14,  5.61it/s]

[ 10/765]  raw='pass'  → → 1

  1%|▏         | 11/765 [00:01<02:13,  5.63it/s]

[ 11/765]  raw='fail'  → → 0

  2%|▏         | 12/765 [00:02<02:17,  5.46it/s]

[ 12/765]  raw='pass'  → → 1

  2%|▏         | 13/765 [00:02<02:15,  5.53it/s]

[ 13/765]  raw='pass'  → → 1

  2%|▏         | 14/765 [00:02<02:16,  5.50it/s]

[ 14/765]  raw='pass'  → → 1

  2%|▏         | 15/765 [00:02<02:18,  5.41it/s]

[ 15/765]  raw='pass'  → → 1

  2%|▏         | 16/765 [00:02<02:15,  5.52it/s]

[ 16/765]  raw='pass'  → → 1

  2%|▏         | 17/765 [00:03<02:13,  5.61it/s]

[ 17/765]  raw='pass'  → → 1

  2%|▏         | 18/765 [00:03<02:11,  5.67it/s]

[ 18/765]  raw='pass'  → → 1

  2%|▏         | 19/765 [00:03<02:10,  5.72it/s]

[ 19/765]  raw='fail'  → → 0

  3%|▎         | 21/765 [00:03<02:15,  5.50it/s]

[ 20/765]  raw='pass'  → → 1
[ 21/765]  raw='fail'  → → 0

  3%|▎         | 23/765 [00:04<02:08,  5.75it/s]

[ 22/765]  raw='fail'  → → 0
[ 23/765]  raw='pass'  → → 1

  3%|▎         | 25/765 [00:04<02:13,  5.55it/s]

[ 24/765]  raw='pass'  → → 1
[ 25/765]  raw='pass'  → → 1

  4%|▎         | 27/765 [00:04<02:07,  5.77it/s]

[ 26/765]  raw='pass'  → → 1
[ 27/765]  raw='fail'  → → 0

  4%|▍         | 29/765 [00:05<02:04,  5.90it/s]

[ 28/765]  raw='fail'  → → 0
[ 29/765]  raw='pass'  → → 1

  4%|▍         | 31/765 [00:05<02:04,  5.91it/s]

[ 30/765]  raw='pass'  → → 1
[ 31/765]  raw='pass'  → → 1

  4%|▍         | 32/765 [00:05<02:04,  5.88it/s]

[ 32/765]  raw='pass'  → → 1

  4%|▍         | 34/765 [00:06<02:10,  5.60it/s]

[ 33/765]  raw='fail'  → → 0
[ 34/765]  raw='fail'  → → 0

  5%|▍         | 36/765 [00:06<02:06,  5.74it/s]

[ 35/765]  raw='fail'  → → 0
[ 36/765]  raw='pass'  → → 1

  5%|▍         | 38/765 [00:06<02:05,  5.79it/s]

[ 37/765]  raw='pass'  → → 1
[ 38/765]  raw='fail'  → → 0

  5%|▌         | 40/765 [00:07<02:10,  5.57it/s]

[ 39/765]  raw='pass'  → → 1
[ 40/765]  raw='pass'  → → 1

  5%|▌         | 42/765 [00:07<02:15,  5.35it/s]

[ 41/765]  raw='pass'  → → 1
[ 42/765]  raw='fail'  → → 0

  6%|▌         | 44/765 [00:07<02:08,  5.60it/s]

[ 43/765]  raw='fail'  → → 0
[ 44/765]  raw='pass'  → → 1

  6%|▌         | 46/765 [00:08<02:05,  5.75it/s]

[ 45/765]  raw='fail'  → → 0
[ 46/765]  raw='fail'  → → 0

  6%|▋         | 48/765 [00:08<02:03,  5.82it/s]

[ 47/765]  raw='pass'  → → 1
[ 48/765]  raw='pass'  → → 1

  7%|▋         | 50/765 [00:08<02:02,  5.84it/s]

[ 49/765]  raw='pass'  → → 1
[ 50/765]  raw='pass'  → → 1

  7%|▋         | 52/765 [00:09<02:03,  5.79it/s]

[ 51/765]  raw='fail'  → → 0
[ 52/765]  raw='fail'  → → 0

  7%|▋         | 53/765 [00:09<02:02,  5.79it/s]

[ 53/765]  raw='pass'  → → 1

  7%|▋         | 55/765 [00:09<02:14,  5.30it/s]

[ 54/765]  raw='pass'  → → 1
[ 55/765]  raw='fail'  → → 0

  7%|▋         | 57/765 [00:10<02:08,  5.50it/s]

[ 56/765]  raw='fail'  → → 0
[ 57/765]  raw='pass'  → → 1

  8%|▊         | 59/765 [00:10<02:04,  5.66it/s]

[ 58/765]  raw='pass'  → → 1
[ 59/765]  raw='pass'  → → 1

  8%|▊         | 61/765 [00:10<02:03,  5.72it/s]

[ 60/765]  raw='fail'  → → 0
[ 61/765]  raw='pass'  → → 1

  8%|▊         | 63/765 [00:11<02:05,  5.58it/s]

[ 62/765]  raw='fail'  → → 0
[ 63/765]  raw='pass'  → → 1

  8%|▊         | 65/765 [00:11<02:02,  5.71it/s]

[ 64/765]  raw='fail'  → → 0
[ 65/765]  raw='fail'  → → 0

  9%|▉         | 67/765 [00:11<02:06,  5.53it/s]

[ 66/765]  raw='pass'  → → 1
[ 67/765]  raw='pass'  → → 1

  9%|▉         | 69/765 [00:12<02:02,  5.66it/s]

[ 68/765]  raw='fail'  → → 0
[ 69/765]  raw='fail'  → → 0

  9%|▉         | 71/765 [00:12<02:00,  5.74it/s]

[ 70/765]  raw='fail'  → → 0
[ 71/765]  raw='pass'  → → 1

 10%|▉         | 73/765 [00:12<02:00,  5.75it/s]

[ 72/765]  raw='fail'  → → 0
[ 73/765]  raw='fail'  → → 0

 10%|▉         | 74/765 [00:13<02:00,  5.72it/s]

[ 74/765]  raw='fail'  → → 0

 10%|▉         | 75/765 [00:13<02:09,  5.34it/s]

[ 75/765]  raw='fail'  → → 0

 10%|▉         | 76/765 [00:13<02:15,  5.09it/s]

[ 76/765]  raw='pass'  → → 1

 10%|█         | 77/765 [00:13<02:19,  4.94it/s]

[ 77/765]  raw='fail'  → → 0

 10%|█         | 78/765 [00:13<02:22,  4.82it/s]

[ 78/765]  raw='pass'  → → 1

 10%|█         | 79/765 [00:14<02:25,  4.72it/s]

[ 79/765]  raw='pass'  → → 1

 11%|█         | 81/765 [00:14<02:17,  4.98it/s]

[ 80/765]  raw='pass'  → → 1
[ 81/765]  raw='pass'  → → 1

 11%|█         | 82/765 [00:14<02:10,  5.22it/s]

[ 82/765]  raw='pass'  → → 1

 11%|█         | 83/765 [00:14<02:17,  4.97it/s]

[ 83/765]  raw='pass'  → → 1

 11%|█         | 85/765 [00:15<02:14,  5.04it/s]

[ 84/765]  raw='pass'  → → 1
[ 85/765]  raw='fail'  → → 0

 11%|█▏        | 87/765 [00:15<02:06,  5.36it/s]

[ 86/765]  raw='pass'  → → 1
[ 87/765]  raw='pass'  → → 1

 12%|█▏        | 89/765 [00:16<02:00,  5.63it/s]

[ 88/765]  raw='pass'  → → 1
[ 89/765]  raw='pass'  → → 1

 12%|█▏        | 91/765 [00:16<01:57,  5.76it/s]

[ 90/765]  raw='pass'  → → 1
[ 91/765]  raw='pass'  → → 1

 12%|█▏        | 93/765 [00:16<02:03,  5.43it/s]

[ 92/765]  raw='pass'  → → 1
[ 93/765]  raw='pass'  → → 1

 12%|█▏        | 95/765 [00:17<01:58,  5.66it/s]

[ 94/765]  raw='fail'  → → 0
[ 95/765]  raw='fail'  → → 0

 13%|█▎        | 97/765 [00:17<01:54,  5.82it/s]

[ 96/765]  raw='fail'  → → 0
[ 97/765]  raw='pass'  → → 1

 13%|█▎        | 98/765 [00:17<01:54,  5.85it/s]

[ 98/765]  raw='fail'  → → 0

 13%|█▎        | 100/765 [00:18<01:58,  5.61it/s]

[ 99/765]  raw='pass'  → → 1
[100/765]  raw='fail'  → → 0

 13%|█▎        | 102/765 [00:18<01:55,  5.75it/s]

[101/765]  raw='pass'  → → 1
[102/765]  raw='pass'  → → 1

 14%|█▎        | 104/765 [00:18<01:57,  5.61it/s]

[103/765]  raw='fail'  → → 0
[104/765]  raw='pass'  → → 1

 14%|█▎        | 105/765 [00:18<02:04,  5.30it/s]

[105/765]  raw='fail'  → → 0

 14%|█▍        | 106/765 [00:19<02:10,  5.04it/s]

[106/765]  raw='pass'  → → 1

 14%|█▍        | 107/765 [00:19<02:13,  4.93it/s]

[107/765]  raw='pass'  → → 1

 14%|█▍        | 108/765 [00:19<02:15,  4.86it/s]

[108/765]  raw='fail'  → → 0

 14%|█▍        | 110/765 [00:20<02:14,  4.88it/s]

[109/765]  raw='pass'  → → 1
[110/765]  raw='pass'  → → 1

 15%|█▍        | 112/765 [00:20<02:01,  5.36it/s]

[111/765]  raw='pass'  → → 1
[112/765]  raw='fail'  → → 0

 15%|█▍        | 114/765 [00:20<01:55,  5.63it/s]

[113/765]  raw='pass'  → → 1
[114/765]  raw='pass'  → → 1

 15%|█▌        | 116/765 [00:21<01:52,  5.79it/s]

[115/765]  raw='pass'  → → 1
[116/765]  raw='pass'  → → 1

 15%|█▌        | 118/765 [00:21<01:49,  5.92it/s]

[117/765]  raw='pass'  → → 1
[118/765]  raw='pass'  → → 1

 16%|█▌        | 120/765 [00:21<01:48,  5.97it/s]

[119/765]  raw='pass'  → → 1
[120/765]  raw='pass'  → → 1

 16%|█▌        | 122/765 [00:22<01:54,  5.63it/s]

[121/765]  raw='pass'  → → 1
[122/765]  raw='pass'  → → 1

 16%|█▌        | 124/765 [00:22<01:55,  5.55it/s]

[123/765]  raw='pass'  → → 1
[124/765]  raw='pass'  → → 1

 16%|█▋        | 126/765 [00:22<01:55,  5.53it/s]

[125/765]  raw='fail'  → → 0
[126/765]  raw='pass'  → → 1

 17%|█▋        | 128/765 [00:23<01:52,  5.68it/s]

[127/765]  raw='fail'  → → 0
[128/765]  raw='fail'  → → 0

 17%|█▋        | 130/765 [00:23<01:54,  5.52it/s]

[129/765]  raw='pass'  → → 1
[130/765]  raw='pass'  → → 1

 17%|█▋        | 132/765 [00:23<01:52,  5.64it/s]

[131/765]  raw='pass'  → → 1
[132/765]  raw='pass'  → → 1

 18%|█▊        | 134/765 [00:24<01:51,  5.67it/s]

[133/765]  raw='fail'  → → 0
[134/765]  raw='fail'  → → 0

 18%|█▊        | 136/765 [00:24<01:48,  5.80it/s]

[135/765]  raw='pass'  → → 1
[136/765]  raw='pass'  → → 1

 18%|█▊        | 138/765 [00:24<01:54,  5.48it/s]

[137/765]  raw='pass'  → → 1
[138/765]  raw='fail'  → → 0

 18%|█▊        | 140/765 [00:25<01:55,  5.41it/s]

[139/765]  raw='pass'  → → 1
[140/765]  raw='fail'  → → 0

 19%|█▊        | 142/765 [00:25<01:54,  5.45it/s]

[141/765]  raw='fail'  → → 0
[142/765]  raw='fail'  → → 0

 19%|█▊        | 143/765 [00:25<01:51,  5.56it/s]

[143/765]  raw='pass'  → → 1

 19%|█▉        | 145/765 [00:26<01:59,  5.18it/s]

[144/765]  raw='pass'  → → 1
[145/765]  raw='pass'  → → 1

 19%|█▉        | 146/765 [00:26<01:54,  5.38it/s]

[146/765]  raw='pass'  → → 1

 19%|█▉        | 148/765 [00:26<01:56,  5.29it/s]

[147/765]  raw='pass'  → → 1
[148/765]  raw='pass'  → → 1

 20%|█▉        | 150/765 [00:27<01:49,  5.62it/s]

[149/765]  raw='pass'  → → 1
[150/765]  raw='fail'  → → 0

 20%|█▉        | 152/765 [00:27<01:51,  5.49it/s]

[151/765]  raw='pass'  → → 1
[152/765]  raw='pass'  → → 1

 20%|██        | 154/765 [00:27<01:47,  5.70it/s]

[153/765]  raw='fail'  → → 0
[154/765]  raw='pass'  → → 1

 20%|██        | 156/765 [00:28<01:51,  5.48it/s]

[155/765]  raw='fail'  → → 0
[156/765]  raw='pass'  → → 1

 21%|██        | 158/765 [00:28<01:54,  5.29it/s]

[157/765]  raw='fail'  → → 0
[158/765]  raw='pass'  → → 1

 21%|██        | 160/765 [00:29<01:53,  5.33it/s]

[159/765]  raw='pass'  → → 1
[160/765]  raw='pass'  → → 1

 21%|██        | 162/765 [00:29<01:46,  5.64it/s]

[161/765]  raw='pass'  → → 1
[162/765]  raw='pass'  → → 1

 21%|██▏       | 164/765 [00:29<01:43,  5.83it/s]

[163/765]  raw='pass'  → → 1
[164/765]  raw='fail'  → → 0

 22%|██▏       | 166/765 [00:30<01:41,  5.91it/s]

[165/765]  raw='fail'  → → 0
[166/765]  raw='fail'  → → 0

 22%|██▏       | 168/765 [00:30<01:40,  5.94it/s]

[167/765]  raw='fail'  → → 0
[168/765]  raw='fail'  → → 0

 22%|██▏       | 170/765 [00:30<01:39,  5.99it/s]

[169/765]  raw='pass'  → → 1
[170/765]  raw='pass'  → → 1

 22%|██▏       | 172/765 [00:31<01:45,  5.64it/s]

[171/765]  raw='pass'  → → 1
[172/765]  raw='pass'  → → 1

 23%|██▎       | 173/765 [00:31<01:51,  5.29it/s]

[173/765]  raw='pass'  → → 1

 23%|██▎       | 175/765 [00:31<01:50,  5.35it/s]

[174/765]  raw='pass'  → → 1
[175/765]  raw='pass'  → → 1

 23%|██▎       | 177/765 [00:32<01:44,  5.65it/s]

[176/765]  raw='pass'  → → 1
[177/765]  raw='fail'  → → 0

 23%|██▎       | 178/765 [00:32<01:46,  5.51it/s]

[178/765]  raw='fail'  → → 0

 24%|██▎       | 180/765 [00:32<01:48,  5.37it/s]

[179/765]  raw='pass'  → → 1
[180/765]  raw='fail'  → → 0

 24%|██▍       | 182/765 [00:32<01:42,  5.69it/s]

[181/765]  raw='fail'  → → 0
[182/765]  raw='fail'  → → 0

 24%|██▍       | 184/765 [00:33<01:38,  5.89it/s]

[183/765]  raw='pass'  → → 1
[184/765]  raw='fail'  → → 0

 24%|██▍       | 185/765 [00:33<01:38,  5.89it/s]

[185/765]  raw='fail'  → → 0

 24%|██▍       | 187/765 [00:33<01:43,  5.61it/s]

[186/765]  raw='pass'  → → 1
[187/765]  raw='pass'  → → 1

 25%|██▍       | 189/765 [00:34<01:40,  5.76it/s]

[188/765]  raw='fail'  → → 0
[189/765]  raw='pass'  → → 1

 25%|██▍       | 191/765 [00:34<01:38,  5.81it/s]

[190/765]  raw='pass'  → → 1
[191/765]  raw='fail'  → → 0

 25%|██▌       | 193/765 [00:34<01:44,  5.48it/s]

[192/765]  raw='pass'  → → 1
[193/765]  raw='fail'  → → 0

 25%|██▌       | 194/765 [00:35<01:41,  5.60it/s]

[194/765]  raw='fail'  → → 0

 26%|██▌       | 196/765 [00:35<01:49,  5.19it/s]

[195/765]  raw='pass'  → → 1
[196/765]  raw='pass'  → → 1

 26%|██▌       | 198/765 [00:35<01:42,  5.54it/s]

[197/765]  raw='pass'  → → 1
[198/765]  raw='pass'  → → 1

 26%|██▌       | 200/765 [00:36<01:38,  5.73it/s]

[199/765]  raw='pass'  → → 1
[200/765]  raw='pass'  → → 1

 26%|██▋       | 202/765 [00:36<01:35,  5.89it/s]

[201/765]  raw='pass'  → → 1
[202/765]  raw='pass'  → → 1

 27%|██▋       | 204/765 [00:36<01:34,  5.92it/s]

[203/765]  raw='fail'  → → 0
[204/765]  raw='pass'  → → 1

 27%|██▋       | 206/765 [00:37<01:33,  5.95it/s]

[205/765]  raw='fail'  → → 0
[206/765]  raw='fail'  → → 0

 27%|██▋       | 208/765 [00:37<01:37,  5.73it/s]

[207/765]  raw='pass'  → → 1
[208/765]  raw='pass'  → → 1

 27%|██▋       | 210/765 [00:37<01:33,  5.93it/s]

[209/765]  raw='fail'  → → 0
[210/765]  raw='pass'  → → 1

 28%|██▊       | 212/765 [00:38<01:31,  6.04it/s]

[211/765]  raw='fail'  → → 0
[212/765]  raw='pass'  → → 1

 28%|██▊       | 214/765 [00:38<01:31,  6.02it/s]

[213/765]  raw='pass'  → → 1
[214/765]  raw='fail'  → → 0

 28%|██▊       | 216/765 [00:38<01:32,  5.95it/s]

[215/765]  raw='pass'  → → 1
[216/765]  raw='fail'  → → 0

 28%|██▊       | 217/765 [00:39<01:32,  5.93it/s]

[217/765]  raw='fail'  → → 0

 29%|██▊       | 219/765 [00:39<01:45,  5.20it/s]

[218/765]  raw='pass'  → → 1
[219/765]  raw='pass'  → → 1

 29%|██▉       | 221/765 [00:39<01:36,  5.61it/s]

[220/765]  raw='pass'  → → 1
[221/765]  raw='fail'  → → 0

 29%|██▉       | 223/765 [00:40<01:38,  5.48it/s]

[222/765]  raw='fail'  → → 0
[223/765]  raw='pass'  → → 1

 29%|██▉       | 225/765 [00:40<01:38,  5.50it/s]

[224/765]  raw='pass'  → → 1
[225/765]  raw='pass'  → → 1

 30%|██▉       | 227/765 [00:40<01:38,  5.46it/s]

[226/765]  raw='pass'  → → 1
[227/765]  raw='pass'  → → 1

 30%|██▉       | 229/765 [00:41<01:35,  5.63it/s]

[228/765]  raw='fail'  → → 0
[229/765]  raw='fail'  → → 0

 30%|███       | 231/765 [00:41<01:32,  5.75it/s]

[230/765]  raw='pass'  → → 1
[231/765]  raw='fail'  → → 0

 30%|███       | 233/765 [00:41<01:30,  5.86it/s]

[232/765]  raw='pass'  → → 1
[233/765]  raw='fail'  → → 0

 31%|███       | 235/765 [00:42<01:33,  5.67it/s]

[234/765]  raw='pass'  → → 1
[235/765]  raw='pass'  → → 1

 31%|███       | 237/765 [00:42<01:30,  5.84it/s]

[236/765]  raw='fail'  → → 0
[237/765]  raw='fail'  → → 0

 31%|███       | 239/765 [00:42<01:29,  5.88it/s]

[238/765]  raw='pass'  → → 1
[239/765]  raw='pass'  → → 1

 32%|███▏      | 241/765 [00:43<01:32,  5.68it/s]

[240/765]  raw='pass'  → → 1
[241/765]  raw='pass'  → → 1

 32%|███▏      | 243/765 [00:43<01:28,  5.92it/s]

[242/765]  raw='pass'  → → 1
[243/765]  raw='fail'  → → 0

 32%|███▏      | 245/765 [00:43<01:26,  6.03it/s]

[244/765]  raw='pass'  → → 1
[245/765]  raw='pass'  → → 1

 32%|███▏      | 247/765 [00:44<01:36,  5.35it/s]

[246/765]  raw='pass'  → → 1
[247/765]  raw='pass'  → → 1

 33%|███▎      | 249/765 [00:44<01:30,  5.71it/s]

[248/765]  raw='fail'  → → 0
[249/765]  raw='pass'  → → 1

 33%|███▎      | 251/765 [00:45<01:26,  5.91it/s]

[250/765]  raw='pass'  → → 1
[251/765]  raw='fail'  → → 0

 33%|███▎      | 253/765 [00:45<01:25,  5.99it/s]

[252/765]  raw='fail'  → → 0
[253/765]  raw='fail'  → → 0

 33%|███▎      | 254/765 [00:45<01:25,  6.01it/s]

[254/765]  raw='fail'  → → 0

 33%|███▎      | 256/765 [00:45<01:29,  5.69it/s]

[255/765]  raw='pass'  → → 1
[256/765]  raw='pass'  → → 1

 34%|███▎      | 258/765 [00:46<01:27,  5.83it/s]

[257/765]  raw='pass'  → → 1
[258/765]  raw='fail'  → → 0

 34%|███▍      | 260/765 [00:46<01:25,  5.88it/s]

[259/765]  raw='pass'  → → 1
[260/765]  raw='pass'  → → 1

 34%|███▍      | 262/765 [00:46<01:28,  5.66it/s]

[261/765]  raw='fail'  → → 0
[262/765]  raw='pass'  → → 1

 35%|███▍      | 264/765 [00:47<01:26,  5.80it/s]

[263/765]  raw='pass'  → → 1
[264/765]  raw='pass'  → → 1

 35%|███▍      | 266/765 [00:47<01:27,  5.68it/s]

[265/765]  raw='pass'  → → 1
[266/765]  raw='pass'  → → 1

 35%|███▌      | 268/765 [00:48<01:30,  5.48it/s]

[267/765]  raw='pass'  → → 1
[268/765]  raw='fail'  → → 0

 35%|███▌      | 270/765 [00:48<01:27,  5.69it/s]

[269/765]  raw='pass'  → → 1
[270/765]  raw='fail'  → → 0

 36%|███▌      | 272/765 [00:48<01:24,  5.82it/s]

[271/765]  raw='pass'  → → 1
[272/765]  raw='pass'  → → 1

 36%|███▌      | 274/765 [00:49<01:23,  5.90it/s]

[273/765]  raw='fail'  → → 0
[274/765]  raw='pass'  → → 1

 36%|███▌      | 276/765 [00:49<01:28,  5.52it/s]

[275/765]  raw='pass'  → → 1
[276/765]  raw='fail'  → → 0

 36%|███▋      | 278/765 [00:49<01:24,  5.76it/s]

[277/765]  raw='fail'  → → 0
[278/765]  raw='fail'  → → 0

 37%|███▋      | 280/765 [00:50<01:22,  5.86it/s]

[279/765]  raw='pass'  → → 1
[280/765]  raw='fail'  → → 0

 37%|███▋      | 282/765 [00:50<01:26,  5.58it/s]

[281/765]  raw='pass'  → → 1
[282/765]  raw='fail'  → → 0

 37%|███▋      | 284/765 [00:50<01:25,  5.62it/s]

[283/765]  raw='pass'  → → 1
[284/765]  raw='pass'  → → 1

 37%|███▋      | 286/765 [00:51<01:22,  5.79it/s]

[285/765]  raw='fail'  → → 0
[286/765]  raw='pass'  → → 1

 38%|███▊      | 288/765 [00:51<01:21,  5.84it/s]

[287/765]  raw='pass'  → → 1
[288/765]  raw='pass'  → → 1

 38%|███▊      | 290/765 [00:51<01:20,  5.90it/s]

[289/765]  raw='pass'  → → 1
[290/765]  raw='pass'  → → 1

 38%|███▊      | 292/765 [00:52<01:19,  5.92it/s]

[291/765]  raw='fail'  → → 0
[292/765]  raw='fail'  → → 0

 38%|███▊      | 293/765 [00:52<01:22,  5.70it/s]

[293/765]  raw='pass'  → → 1

 39%|███▊      | 295/765 [00:52<01:26,  5.45it/s]

[294/765]  raw='pass'  → → 1
[295/765]  raw='pass'  → → 1

 39%|███▉      | 297/765 [00:53<01:22,  5.68it/s]

[296/765]  raw='pass'  → → 1
[297/765]  raw='pass'  → → 1

 39%|███▉      | 298/765 [00:53<01:21,  5.76it/s]

[298/765]  raw='pass'  → → 1

 39%|███▉      | 300/765 [00:53<01:24,  5.48it/s]

[299/765]  raw='pass'  → → 1
[300/765]  raw='pass'  → → 1

 39%|███▉      | 302/765 [00:54<01:21,  5.71it/s]

[301/765]  raw='fail'  → → 0
[302/765]  raw='fail'  → → 0

 40%|███▉      | 304/765 [00:54<01:26,  5.33it/s]

[303/765]  raw='pass'  → → 1
[304/765]  raw='pass'  → → 1

 40%|████      | 306/765 [00:54<01:20,  5.70it/s]

[305/765]  raw='pass'  → → 1
[306/765]  raw='fail'  → → 0

 40%|████      | 308/765 [00:55<01:18,  5.82it/s]

[307/765]  raw='pass'  → → 1
[308/765]  raw='fail'  → → 0

 41%|████      | 310/765 [00:55<01:17,  5.86it/s]

[309/765]  raw='fail'  → → 0
[310/765]  raw='pass'  → → 1

 41%|████      | 312/765 [00:55<01:17,  5.84it/s]

[311/765]  raw='pass'  → → 1
[312/765]  raw='fail'  → → 0

 41%|████      | 314/765 [00:56<01:19,  5.67it/s]

[313/765]  raw='pass'  → → 1
[314/765]  raw='pass'  → → 1

 41%|████▏     | 316/765 [00:56<01:17,  5.83it/s]

[315/765]  raw='pass'  → → 1
[316/765]  raw='pass'  → → 1

 42%|████▏     | 318/765 [00:56<01:14,  5.98it/s]

[317/765]  raw='pass'  → → 1
[318/765]  raw='pass'  → → 1

 42%|████▏     | 320/765 [00:57<01:13,  6.04it/s]

[319/765]  raw='pass'  → → 1
[320/765]  raw='fail'  → → 0

 42%|████▏     | 322/765 [00:57<01:12,  6.07it/s]

[321/765]  raw='fail'  → → 0
[322/765]  raw='pass'  → → 1

 42%|████▏     | 324/765 [00:57<01:13,  6.02it/s]

[323/765]  raw='pass'  → → 1
[324/765]  raw='pass'  → → 1

 42%|████▏     | 325/765 [00:57<01:12,  6.03it/s]

[325/765]  raw='pass'  → → 1

 43%|████▎     | 327/765 [00:58<01:17,  5.65it/s]

[326/765]  raw='pass'  → → 1
[327/765]  raw='pass'  → → 1

 43%|████▎     | 329/765 [00:58<01:14,  5.83it/s]

[328/765]  raw='fail'  → → 0
[329/765]  raw='fail'  → → 0

 43%|████▎     | 331/765 [00:59<01:13,  5.92it/s]

[330/765]  raw='pass'  → → 1
[331/765]  raw='fail'  → → 0

 44%|████▎     | 333/765 [00:59<01:12,  5.96it/s]

[332/765]  raw='pass'  → → 1
[333/765]  raw='pass'  → → 1

 44%|████▍     | 335/765 [00:59<01:12,  5.92it/s]

[334/765]  raw='pass'  → → 1
[335/765]  raw='fail'  → → 0

 44%|████▍     | 337/765 [01:00<01:12,  5.92it/s]

[336/765]  raw='fail'  → → 0
[337/765]  raw='pass'  → → 1

 44%|████▍     | 338/765 [01:00<01:12,  5.90it/s]

[338/765]  raw='pass'  → → 1

 44%|████▍     | 340/765 [01:00<01:16,  5.57it/s]

[339/765]  raw='pass'  → → 1
[340/765]  raw='pass'  → → 1

 45%|████▍     | 342/765 [01:00<01:14,  5.68it/s]

[341/765]  raw='fail'  → → 0
[342/765]  raw='pass'  → → 1

 45%|████▍     | 344/765 [01:01<01:15,  5.61it/s]

[343/765]  raw='pass'  → → 1
[344/765]  raw='pass'  → → 1

 45%|████▌     | 345/765 [01:01<01:13,  5.70it/s]

[345/765]  raw='pass'  → → 1

 45%|████▌     | 347/765 [01:01<01:15,  5.53it/s]

[346/765]  raw='pass'  → → 1
[347/765]  raw='pass'  → → 1

 46%|████▌     | 349/765 [01:02<01:12,  5.75it/s]

[348/765]  raw='fail'  → → 0
[349/765]  raw='fail'  → → 0

 46%|████▌     | 351/765 [01:02<01:10,  5.88it/s]

[350/765]  raw='fail'  → → 0
[351/765]  raw='pass'  → → 1

 46%|████▌     | 353/765 [01:02<01:09,  5.91it/s]

[352/765]  raw='pass'  → → 1
[353/765]  raw='pass'  → → 1

 46%|████▋     | 355/765 [01:03<01:09,  5.93it/s]

[354/765]  raw='fail'  → → 0
[355/765]  raw='pass'  → → 1

 47%|████▋     | 357/765 [01:03<01:09,  5.89it/s]

[356/765]  raw='fail'  → → 0
[357/765]  raw='pass'  → → 1

 47%|████▋     | 359/765 [01:03<01:11,  5.65it/s]

[358/765]  raw='pass'  → → 1
[359/765]  raw='pass'  → → 1

 47%|████▋     | 361/765 [01:04<01:09,  5.79it/s]

[360/765]  raw='fail'  → → 0
[361/765]  raw='fail'  → → 0

 47%|████▋     | 363/765 [01:04<01:12,  5.54it/s]

[362/765]  raw='pass'  → → 1
[363/765]  raw='pass'  → → 1

 48%|████▊     | 364/765 [01:04<01:11,  5.63it/s]

[364/765]  raw='pass'  → → 1

 48%|████▊     | 366/765 [01:05<01:12,  5.50it/s]

[365/765]  raw='pass'  → → 1
[366/765]  raw='fail'  → → 0

 48%|████▊     | 368/765 [01:05<01:09,  5.71it/s]

[367/765]  raw='pass'  → → 1
[368/765]  raw='pass'  → → 1

 48%|████▊     | 370/765 [01:05<01:11,  5.51it/s]

[369/765]  raw='pass'  → → 1
[370/765]  raw='pass'  → → 1

 49%|████▊     | 372/765 [01:06<01:09,  5.67it/s]

[371/765]  raw='pass'  → → 1
[372/765]  raw='fail'  → → 0

 49%|████▉     | 374/765 [01:06<01:11,  5.49it/s]

[373/765]  raw='pass'  → → 1
[374/765]  raw='pass'  → → 1

 49%|████▉     | 376/765 [01:06<01:09,  5.58it/s]

[375/765]  raw='pass'  → → 1
[376/765]  raw='pass'  → → 1

 49%|████▉     | 377/765 [01:07<01:08,  5.65it/s]

[377/765]  raw='fail'  → → 0

 50%|████▉     | 379/765 [01:07<01:10,  5.50it/s]

[378/765]  raw='pass'  → → 1
[379/765]  raw='pass'  → → 1

 50%|████▉     | 381/765 [01:07<01:10,  5.44it/s]

[380/765]  raw='fail'  → → 0
[381/765]  raw='pass'  → → 1

 50%|█████     | 383/765 [01:08<01:06,  5.70it/s]

[382/765]  raw='fail'  → → 0
[383/765]  raw='fail'  → → 0

 50%|█████     | 385/765 [01:08<01:05,  5.84it/s]

[384/765]  raw='pass'  → → 1
[385/765]  raw='fail'  → → 0

 51%|█████     | 387/765 [01:08<01:04,  5.87it/s]

[386/765]  raw='pass'  → → 1
[387/765]  raw='fail'  → → 0

 51%|█████     | 389/765 [01:09<01:03,  5.90it/s]

[388/765]  raw='fail'  → → 0
[389/765]  raw='pass'  → → 1

 51%|█████     | 391/765 [01:09<01:03,  5.90it/s]

[390/765]  raw='pass'  → → 1
[391/765]  raw='pass'  → → 1

 51%|█████▏    | 393/765 [01:09<01:03,  5.88it/s]

[392/765]  raw='fail'  → → 0
[393/765]  raw='pass'  → → 1

 52%|█████▏    | 395/765 [01:10<01:10,  5.25it/s]

[394/765]  raw='pass'  → → 1
[395/765]  raw='fail'  → → 0

 52%|█████▏    | 397/765 [01:10<01:06,  5.55it/s]

[396/765]  raw='pass'  → → 1
[397/765]  raw='pass'  → → 1

 52%|█████▏    | 399/765 [01:10<01:03,  5.76it/s]

[398/765]  raw='fail'  → → 0
[399/765]  raw='fail'  → → 0

 52%|█████▏    | 401/765 [01:11<01:02,  5.83it/s]

[400/765]  raw='pass'  → → 1
[401/765]  raw='pass'  → → 1

 53%|█████▎    | 403/765 [01:11<01:03,  5.72it/s]

[402/765]  raw='fail'  → → 0
[403/765]  raw='fail'  → → 0

 53%|█████▎    | 405/765 [01:12<01:01,  5.88it/s]

[404/765]  raw='pass'  → → 1
[405/765]  raw='pass'  → → 1

 53%|█████▎    | 406/765 [01:12<01:00,  5.93it/s]

[406/765]  raw='pass'  → → 1

 53%|█████▎    | 408/765 [01:12<01:03,  5.66it/s]

[407/765]  raw='pass'  → → 1
[408/765]  raw='fail'  → → 0

 54%|█████▎    | 410/765 [01:12<01:01,  5.80it/s]

[409/765]  raw='pass'  → → 1
[410/765]  raw='pass'  → → 1

 54%|█████▎    | 411/765 [01:13<01:00,  5.90it/s]

[411/765]  raw='fail'  → → 0

 54%|█████▍    | 413/765 [01:13<01:03,  5.58it/s]

[412/765]  raw='pass'  → → 1
[413/765]  raw='fail'  → → 0

 54%|█████▍    | 415/765 [01:13<01:02,  5.62it/s]

[414/765]  raw='fail'  → → 0
[415/765]  raw='fail'  → → 0

 55%|█████▍    | 417/765 [01:14<00:59,  5.83it/s]

[416/765]  raw='fail'  → → 0
[417/765]  raw='pass'  → → 1

 55%|█████▍    | 419/765 [01:14<00:58,  5.89it/s]

[418/765]  raw='pass'  → → 1
[419/765]  raw='pass'  → → 1

 55%|█████▌    | 421/765 [01:14<00:57,  6.00it/s]

[420/765]  raw='fail'  → → 0
[421/765]  raw='pass'  → → 1

 55%|█████▌    | 423/765 [01:15<01:03,  5.37it/s]

[422/765]  raw='pass'  → → 1
[423/765]  raw='pass'  → → 1

 56%|█████▌    | 425/765 [01:15<00:59,  5.70it/s]

[424/765]  raw='pass'  → → 1
[425/765]  raw='fail'  → → 0

 56%|█████▌    | 426/765 [01:15<01:01,  5.54it/s]

[426/765]  raw='fail'  → → 0

 56%|█████▌    | 428/765 [01:16<01:05,  5.15it/s]

[427/765]  raw='pass'  → → 1
[428/765]  raw='fail'  → → 0

 56%|█████▌    | 430/765 [01:16<01:00,  5.52it/s]

[429/765]  raw='pass'  → → 1
[430/765]  raw='pass'  → → 1

 56%|█████▋    | 432/765 [01:16<00:57,  5.74it/s]

[431/765]  raw='pass'  → → 1
[432/765]  raw='pass'  → → 1

 57%|█████▋    | 434/765 [01:17<00:56,  5.85it/s]

[433/765]  raw='pass'  → → 1
[434/765]  raw='fail'  → → 0

 57%|█████▋    | 436/765 [01:17<00:55,  5.90it/s]

[435/765]  raw='pass'  → → 1
[436/765]  raw='pass'  → → 1

 57%|█████▋    | 438/765 [01:17<00:54,  5.95it/s]

[437/765]  raw='fail'  → → 0
[438/765]  raw='pass'  → → 1

 58%|█████▊    | 440/765 [01:18<00:54,  5.97it/s]

[439/765]  raw='pass'  → → 1
[440/765]  raw='pass'  → → 1

 58%|█████▊    | 442/765 [01:18<00:53,  6.00it/s]

[441/765]  raw='pass'  → → 1
[442/765]  raw='pass'  → → 1

 58%|█████▊    | 444/765 [01:18<00:53,  6.03it/s]

[443/765]  raw='fail'  → → 0
[444/765]  raw='fail'  → → 0

 58%|█████▊    | 446/765 [01:19<00:53,  5.95it/s]

[445/765]  raw='fail'  → → 0
[446/765]  raw='pass'  → → 1

 59%|█████▊    | 448/765 [01:19<00:53,  5.93it/s]

[447/765]  raw='pass'  → → 1
[448/765]  raw='pass'  → → 1

 59%|█████▉    | 450/765 [01:19<00:53,  5.93it/s]

[449/765]  raw='fail'  → → 0
[450/765]  raw='fail'  → → 0

 59%|█████▉    | 452/765 [01:20<00:52,  5.96it/s]

[451/765]  raw='fail'  → → 0
[452/765]  raw='fail'  → → 0

 59%|█████▉    | 454/765 [01:20<00:52,  5.97it/s]

[453/765]  raw='pass'  → → 1
[454/765]  raw='fail'  → → 0

 60%|█████▉    | 456/765 [01:20<00:51,  5.98it/s]

[455/765]  raw='pass'  → → 1
[456/765]  raw='pass'  → → 1

 60%|█████▉    | 458/765 [01:21<00:51,  5.98it/s]

[457/765]  raw='fail'  → → 0
[458/765]  raw='fail'  → → 0

 60%|██████    | 460/765 [01:21<00:50,  6.02it/s]

[459/765]  raw='fail'  → → 0
[460/765]  raw='fail'  → → 0

 60%|██████    | 462/765 [01:21<00:53,  5.68it/s]

[461/765]  raw='fail'  → → 0
[462/765]  raw='fail'  → → 0

 61%|██████    | 464/765 [01:22<00:51,  5.84it/s]

[463/765]  raw='fail'  → → 0
[464/765]  raw='fail'  → → 0

 61%|██████    | 466/765 [01:22<00:50,  5.93it/s]

[465/765]  raw='fail'  → → 0
[466/765]  raw='pass'  → → 1

 61%|██████    | 468/765 [01:22<00:49,  5.98it/s]

[467/765]  raw='pass'  → → 1
[468/765]  raw='pass'  → → 1

 61%|██████▏   | 469/765 [01:23<00:49,  6.00it/s]

[469/765]  raw='fail'  → → 0

 62%|██████▏   | 471/765 [01:23<00:51,  5.70it/s]

[470/765]  raw='pass'  → → 1
[471/765]  raw='fail'  → → 0

 62%|██████▏   | 473/765 [01:23<00:49,  5.84it/s]

[472/765]  raw='fail'  → → 0
[473/765]  raw='fail'  → → 0

 62%|██████▏   | 475/765 [01:24<00:48,  5.94it/s]

[474/765]  raw='fail'  → → 0
[475/765]  raw='pass'  → → 1

 62%|██████▏   | 477/765 [01:24<00:48,  5.95it/s]

[476/765]  raw='pass'  → → 1
[477/765]  raw='fail'  → → 0

 63%|██████▎   | 479/765 [01:24<00:47,  6.03it/s]

[478/765]  raw='fail'  → → 0
[479/765]  raw='pass'  → → 1

 63%|██████▎   | 481/765 [01:25<00:47,  6.02it/s]

[480/765]  raw='pass'  → → 1
[481/765]  raw='pass'  → → 1

 63%|██████▎   | 483/765 [01:25<00:46,  6.02it/s]

[482/765]  raw='fail'  → → 0
[483/765]  raw='fail'  → → 0

 63%|██████▎   | 485/765 [01:25<00:46,  6.05it/s]

[484/765]  raw='fail'  → → 0
[485/765]  raw='pass'  → → 1

 64%|██████▎   | 487/765 [01:26<00:47,  5.87it/s]

[486/765]  raw='pass'  → → 1
[487/765]  raw='fail'  → → 0

 64%|██████▍   | 489/765 [01:26<00:46,  5.93it/s]

[488/765]  raw='pass'  → → 1
[489/765]  raw='fail'  → → 0

 64%|██████▍   | 491/765 [01:26<00:45,  5.96it/s]

[490/765]  raw='pass'  → → 1
[491/765]  raw='pass'  → → 1

 64%|██████▍   | 493/765 [01:27<00:45,  6.02it/s]

[492/765]  raw='pass'  → → 1
[493/765]  raw='fail'  → → 0

 65%|██████▍   | 495/765 [01:27<00:44,  6.02it/s]

[494/765]  raw='pass'  → → 1
[495/765]  raw='fail'  → → 0

 65%|██████▍   | 497/765 [01:27<00:44,  6.05it/s]

[496/765]  raw='pass'  → → 1
[497/765]  raw='pass'  → → 1

 65%|██████▌   | 499/765 [01:28<00:43,  6.05it/s]

[498/765]  raw='pass'  → → 1
[499/765]  raw='pass'  → → 1

 65%|██████▌   | 501/765 [01:28<00:43,  6.06it/s]

[500/765]  raw='pass'  → → 1
[501/765]  raw='fail'  → → 0

 66%|██████▌   | 503/765 [01:28<00:43,  6.03it/s]

[502/765]  raw='fail'  → → 0
[503/765]  raw='pass'  → → 1

 66%|██████▌   | 505/765 [01:29<00:42,  6.06it/s]

[504/765]  raw='pass'  → → 1
[505/765]  raw='fail'  → → 0

 66%|██████▋   | 507/765 [01:29<00:42,  6.00it/s]

[506/765]  raw='fail'  → → 0
[507/765]  raw='fail'  → → 0

 67%|██████▋   | 509/765 [01:29<00:44,  5.70it/s]

[508/765]  raw='pass'  → → 1
[509/765]  raw='pass'  → → 1

 67%|██████▋   | 510/765 [01:29<00:44,  5.77it/s]

[510/765]  raw='fail'  → → 0

 67%|██████▋   | 512/765 [01:30<00:45,  5.56it/s]

[511/765]  raw='pass'  → → 1
[512/765]  raw='pass'  → → 1

 67%|██████▋   | 514/765 [01:30<00:43,  5.77it/s]

[513/765]  raw='fail'  → → 0
[514/765]  raw='pass'  → → 1

 67%|██████▋   | 515/765 [01:30<00:42,  5.83it/s]

[515/765]  raw='pass'  → → 1

 68%|██████▊   | 517/765 [01:31<00:44,  5.63it/s]

[516/765]  raw='pass'  → → 1
[517/765]  raw='fail'  → → 0

 68%|██████▊   | 519/765 [01:31<00:42,  5.84it/s]

[518/765]  raw='pass'  → → 1
[519/765]  raw='fail'  → → 0

 68%|██████▊   | 521/765 [01:31<00:43,  5.67it/s]

[520/765]  raw='pass'  → → 1
[521/765]  raw='pass'  → → 1

 68%|██████▊   | 523/765 [01:32<00:41,  5.84it/s]

[522/765]  raw='pass'  → → 1
[523/765]  raw='pass'  → → 1

 68%|██████▊   | 524/765 [01:32<00:41,  5.85it/s]

[524/765]  raw='fail'  → → 0

 69%|██████▉   | 526/765 [01:32<00:42,  5.58it/s]

[525/765]  raw='pass'  → → 1
[526/765]  raw='fail'  → → 0

 69%|██████▉   | 528/765 [01:33<00:40,  5.80it/s]

[527/765]  raw='fail'  → → 0
[528/765]  raw='pass'  → → 1

 69%|██████▉   | 530/765 [01:33<00:39,  5.95it/s]

[529/765]  raw='fail'  → → 0
[530/765]  raw='fail'  → → 0

 70%|██████▉   | 532/765 [01:33<00:38,  6.04it/s]

[531/765]  raw='pass'  → → 1
[532/765]  raw='fail'  → → 0

 70%|██████▉   | 534/765 [01:34<00:38,  6.01it/s]

[533/765]  raw='pass'  → → 1
[534/765]  raw='pass'  → → 1

 70%|███████   | 536/765 [01:34<00:37,  6.05it/s]

[535/765]  raw='pass'  → → 1
[536/765]  raw='pass'  → → 1

 70%|███████   | 538/765 [01:34<00:37,  6.09it/s]

[537/765]  raw='pass'  → → 1
[538/765]  raw='fail'  → → 0

 71%|███████   | 540/765 [01:35<00:37,  6.08it/s]

[539/765]  raw='fail'  → → 0
[540/765]  raw='pass'  → → 1

 71%|███████   | 542/765 [01:35<00:36,  6.03it/s]

[541/765]  raw='pass'  → → 1
[542/765]  raw='fail'  → → 0

 71%|███████   | 544/765 [01:35<00:37,  5.84it/s]

[543/765]  raw='pass'  → → 1
[544/765]  raw='fail'  → → 0

 71%|███████▏  | 546/765 [01:36<00:36,  5.97it/s]

[545/765]  raw='pass'  → → 1
[546/765]  raw='fail'  → → 0

 72%|███████▏  | 547/765 [01:36<00:36,  5.96it/s]

[547/765]  raw='fail'  → → 0

 72%|███████▏  | 549/765 [01:36<00:38,  5.65it/s]

[548/765]  raw='pass'  → → 1
[549/765]  raw='pass'  → → 1

 72%|███████▏  | 551/765 [01:37<00:36,  5.87it/s]

[550/765]  raw='pass'  → → 1
[551/765]  raw='fail'  → → 0

 72%|███████▏  | 553/765 [01:37<00:35,  6.01it/s]

[552/765]  raw='fail'  → → 0
[553/765]  raw='fail'  → → 0

 73%|███████▎  | 555/765 [01:37<00:34,  6.05it/s]

[554/765]  raw='fail'  → → 0
[555/765]  raw='fail'  → → 0

 73%|███████▎  | 557/765 [01:38<00:35,  5.79it/s]

[556/765]  raw='pass'  → → 1
[557/765]  raw='fail'  → → 0

 73%|███████▎  | 559/765 [01:38<00:34,  5.90it/s]

[558/765]  raw='fail'  → → 0
[559/765]  raw='pass'  → → 1

 73%|███████▎  | 561/765 [01:38<00:35,  5.67it/s]

[560/765]  raw='pass'  → → 1
[561/765]  raw='pass'  → → 1

 74%|███████▎  | 563/765 [01:39<00:34,  5.90it/s]

[562/765]  raw='pass'  → → 1
[563/765]  raw='pass'  → → 1

 74%|███████▍  | 565/765 [01:39<00:34,  5.73it/s]

[564/765]  raw='fail'  → → 0
[565/765]  raw='pass'  → → 1

 74%|███████▍  | 567/765 [01:39<00:33,  5.86it/s]

[566/765]  raw='fail'  → → 0
[567/765]  raw='pass'  → → 1

 74%|███████▍  | 569/765 [01:40<00:34,  5.74it/s]

[568/765]  raw='pass'  → → 1
[569/765]  raw='fail'  → → 0

 75%|███████▍  | 571/765 [01:40<00:32,  5.89it/s]

[570/765]  raw='pass'  → → 1
[571/765]  raw='pass'  → → 1

 75%|███████▍  | 573/765 [01:40<00:32,  5.98it/s]

[572/765]  raw='pass'  → → 1
[573/765]  raw='pass'  → → 1

 75%|███████▌  | 575/765 [01:41<00:32,  5.84it/s]

[574/765]  raw='pass'  → → 1
[575/765]  raw='pass'  → → 1

 75%|███████▌  | 577/765 [01:41<00:31,  5.93it/s]

[576/765]  raw='pass'  → → 1
[577/765]  raw='fail'  → → 0

 76%|███████▌  | 579/765 [01:41<00:30,  6.02it/s]

[578/765]  raw='fail'  → → 0
[579/765]  raw='pass'  → → 1

 76%|███████▌  | 581/765 [01:42<00:30,  6.03it/s]

[580/765]  raw='pass'  → → 1
[581/765]  raw='pass'  → → 1

 76%|███████▌  | 583/765 [01:42<00:30,  6.04it/s]

[582/765]  raw='fail'  → → 0
[583/765]  raw='fail'  → → 0

 76%|███████▋  | 585/765 [01:42<00:32,  5.56it/s]

[584/765]  raw='pass'  → → 1
[585/765]  raw='pass'  → → 1

 77%|███████▋  | 587/765 [01:43<00:30,  5.75it/s]

[586/765]  raw='fail'  → → 0
[587/765]  raw='fail'  → → 0

 77%|███████▋  | 589/765 [01:43<00:29,  5.88it/s]

[588/765]  raw='pass'  → → 1
[589/765]  raw='fail'  → → 0

 77%|███████▋  | 591/765 [01:43<00:29,  5.96it/s]

[590/765]  raw='pass'  → → 1
[591/765]  raw='pass'  → → 1

 78%|███████▊  | 593/765 [01:44<00:28,  5.97it/s]

[592/765]  raw='pass'  → → 1
[593/765]  raw='pass'  → → 1

 78%|███████▊  | 595/765 [01:44<00:29,  5.83it/s]

[594/765]  raw='fail'  → → 0
[595/765]  raw='pass'  → → 1

 78%|███████▊  | 597/765 [01:44<00:32,  5.14it/s]

[596/765]  raw='pass'  → → 1
[597/765]  raw='pass'  → → 1

 78%|███████▊  | 599/765 [01:45<00:29,  5.54it/s]

[598/765]  raw='pass'  → → 1
[599/765]  raw='pass'  → → 1

 79%|███████▊  | 601/765 [01:45<00:28,  5.76it/s]

[600/765]  raw='pass'  → → 1
[601/765]  raw='pass'  → → 1

 79%|███████▉  | 603/765 [01:46<00:29,  5.44it/s]

[602/765]  raw='pass'  → → 1
[603/765]  raw='fail'  → → 0

 79%|███████▉  | 605/765 [01:46<00:28,  5.69it/s]

[604/765]  raw='pass'  → → 1
[605/765]  raw='pass'  → → 1

 79%|███████▉  | 607/765 [01:46<00:26,  5.89it/s]

[606/765]  raw='fail'  → → 0
[607/765]  raw='fail'  → → 0

 80%|███████▉  | 609/765 [01:47<00:27,  5.63it/s]

[608/765]  raw='pass'  → → 1
[609/765]  raw='pass'  → → 1

 80%|███████▉  | 611/765 [01:47<00:27,  5.58it/s]

[610/765]  raw='pass'  → → 1
[611/765]  raw='pass'  → → 1

 80%|████████  | 613/765 [01:47<00:26,  5.78it/s]

[612/765]  raw='fail'  → → 0
[613/765]  raw='pass'  → → 1

 80%|████████  | 615/765 [01:48<00:25,  5.93it/s]

[614/765]  raw='pass'  → → 1
[615/765]  raw='fail'  → → 0

 81%|████████  | 617/765 [01:48<00:24,  6.03it/s]

[616/765]  raw='fail'  → → 0
[617/765]  raw='pass'  → → 1

 81%|████████  | 619/765 [01:48<00:24,  6.06it/s]

[618/765]  raw='pass'  → → 1
[619/765]  raw='fail'  → → 0

 81%|████████  | 620/765 [01:48<00:23,  6.05it/s]

[620/765]  raw='pass'  → → 1

 81%|████████▏ | 622/765 [01:49<00:26,  5.35it/s]

[621/765]  raw='pass'  → → 1
[622/765]  raw='fail'  → → 0

 82%|████████▏ | 624/765 [01:49<00:24,  5.71it/s]

[623/765]  raw='pass'  → → 1
[624/765]  raw='pass'  → → 1

 82%|████████▏ | 626/765 [01:49<00:23,  5.90it/s]

[625/765]  raw='fail'  → → 0
[626/765]  raw='fail'  → → 0

 82%|████████▏ | 628/765 [01:50<00:23,  5.93it/s]

[627/765]  raw='pass'  → → 1
[628/765]  raw='pass'  → → 1

 82%|████████▏ | 629/765 [01:50<00:22,  5.97it/s]

[629/765]  raw='pass'  → → 1

 82%|████████▏ | 630/765 [01:50<00:24,  5.52it/s]

[630/765]  raw='pass'  → → 1

 83%|████████▎ | 632/765 [01:51<00:26,  5.02it/s]

[631/765]  raw='fail'  → → 0
[632/765]  raw='pass'  → → 1

 83%|████████▎ | 634/765 [01:51<00:25,  5.12it/s]

[633/765]  raw='pass'  → → 1
[634/765]  raw='pass'  → → 1

 83%|████████▎ | 636/765 [01:51<00:24,  5.25it/s]

[635/765]  raw='pass'  → → 1
[636/765]  raw='pass'  → → 1

 83%|████████▎ | 638/765 [01:52<00:23,  5.46it/s]

[637/765]  raw='pass'  → → 1
[638/765]  raw='fail'  → → 0

 84%|████████▎ | 640/765 [01:52<00:21,  5.75it/s]

[639/765]  raw='fail'  → → 0
[640/765]  raw='pass'  → → 1

 84%|████████▍ | 641/765 [01:52<00:21,  5.79it/s]

[641/765]  raw='fail'  → → 0

 84%|████████▍ | 643/765 [01:53<00:22,  5.52it/s]

[642/765]  raw='pass'  → → 1
[643/765]  raw='pass'  → → 1

 84%|████████▍ | 645/765 [01:53<00:20,  5.78it/s]

[644/765]  raw='fail'  → → 0
[645/765]  raw='fail'  → → 0

 84%|████████▍ | 646/765 [01:53<00:21,  5.55it/s]

[646/765]  raw='pass'  → → 1

 85%|████████▍ | 648/765 [01:54<00:21,  5.44it/s]

[647/765]  raw='pass'  → → 1
[648/765]  raw='pass'  → → 1

 85%|████████▍ | 650/765 [01:54<00:20,  5.68it/s]

[649/765]  raw='fail'  → → 0
[650/765]  raw='fail'  → → 0

 85%|████████▌ | 652/765 [01:54<00:19,  5.88it/s]

[651/765]  raw='fail'  → → 0
[652/765]  raw='fail'  → → 0

 85%|████████▌ | 654/765 [01:55<00:18,  5.96it/s]

[653/765]  raw='fail'  → → 0
[654/765]  raw='pass'  → → 1

 86%|████████▌ | 656/765 [01:55<00:18,  6.03it/s]

[655/765]  raw='fail'  → → 0
[656/765]  raw='fail'  → → 0

 86%|████████▌ | 658/765 [01:55<00:17,  6.03it/s]

[657/765]  raw='pass'  → → 1
[658/765]  raw='fail'  → → 0

 86%|████████▋ | 660/765 [01:56<00:17,  6.05it/s]

[659/765]  raw='fail'  → → 0
[660/765]  raw='fail'  → → 0

 87%|████████▋ | 662/765 [01:56<00:18,  5.62it/s]

[661/765]  raw='pass'  → → 1
[662/765]  raw='pass'  → → 1

 87%|████████▋ | 664/765 [01:56<00:17,  5.82it/s]

[663/765]  raw='fail'  → → 0
[664/765]  raw='pass'  → → 1

 87%|████████▋ | 666/765 [01:57<00:17,  5.64it/s]

[665/765]  raw='fail'  → → 0
[666/765]  raw='pass'  → → 1

 87%|████████▋ | 668/765 [01:57<00:16,  5.88it/s]

[667/765]  raw='pass'  → → 1
[668/765]  raw='fail'  → → 0

 88%|████████▊ | 670/765 [01:57<00:16,  5.73it/s]

[669/765]  raw='pass'  → → 1
[670/765]  raw='pass'  → → 1

 88%|████████▊ | 672/765 [01:58<00:16,  5.47it/s]

[671/765]  raw='fail'  → → 0
[672/765]  raw='pass'  → → 1

 88%|████████▊ | 673/765 [01:58<00:16,  5.64it/s]

[673/765]  raw='pass'  → → 1

 88%|████████▊ | 675/765 [01:58<00:16,  5.51it/s]

[674/765]  raw='pass'  → → 1
[675/765]  raw='fail'  → → 0

 88%|████████▊ | 677/765 [01:59<00:15,  5.76it/s]

[676/765]  raw='fail'  → → 0
[677/765]  raw='pass'  → → 1

 89%|████████▉ | 679/765 [01:59<00:14,  5.82it/s]

[678/765]  raw='pass'  → → 1
[679/765]  raw='pass'  → → 1

 89%|████████▉ | 681/765 [01:59<00:14,  5.85it/s]

[680/765]  raw='pass'  → → 1
[681/765]  raw='pass'  → → 1

 89%|████████▉ | 683/765 [02:00<00:13,  5.90it/s]

[682/765]  raw='fail'  → → 0
[683/765]  raw='pass'  → → 1

 90%|████████▉ | 685/765 [02:00<00:13,  5.97it/s]

[684/765]  raw='pass'  → → 1
[685/765]  raw='fail'  → → 0

 90%|████████▉ | 687/765 [02:00<00:13,  5.95it/s]

[686/765]  raw='pass'  → → 1
[687/765]  raw='pass'  → → 1

 90%|█████████ | 689/765 [02:01<00:12,  5.94it/s]

[688/765]  raw='pass'  → → 1
[689/765]  raw='pass'  → → 1

 90%|█████████ | 691/765 [02:01<00:12,  6.01it/s]

[690/765]  raw='pass'  → → 1
[691/765]  raw='pass'  → → 1

 90%|█████████ | 692/765 [02:01<00:12,  6.04it/s]

[692/765]  raw='fail'  → → 0

 91%|█████████ | 694/765 [02:01<00:12,  5.66it/s]

[693/765]  raw='pass'  → → 1
[694/765]  raw='pass'  → → 1

 91%|█████████ | 696/765 [02:02<00:11,  5.87it/s]

[695/765]  raw='fail'  → → 0
[696/765]  raw='fail'  → → 0

 91%|█████████ | 698/765 [02:02<00:11,  5.84it/s]

[697/765]  raw='pass'  → → 1
[698/765]  raw='fail'  → → 0

 92%|█████████▏| 700/765 [02:02<00:10,  5.91it/s]

[699/765]  raw='pass'  → → 1
[700/765]  raw='fail'  → → 0

 92%|█████████▏| 702/765 [02:03<00:10,  5.97it/s]

[701/765]  raw='pass'  → → 1
[702/765]  raw='fail'  → → 0

 92%|█████████▏| 704/765 [02:03<00:10,  6.03it/s]

[703/765]  raw='pass'  → → 1
[704/765]  raw='pass'  → → 1

 92%|█████████▏| 706/765 [02:03<00:09,  6.07it/s]

[705/765]  raw='fail'  → → 0
[706/765]  raw='fail'  → → 0

 93%|█████████▎| 708/765 [02:04<00:10,  5.65it/s]

[707/765]  raw='pass'  → → 1
[708/765]  raw='fail'  → → 0

 93%|█████████▎| 710/765 [02:04<00:09,  5.87it/s]

[709/765]  raw='fail'  → → 0
[710/765]  raw='pass'  → → 1

 93%|█████████▎| 712/765 [02:05<00:08,  5.96it/s]

[711/765]  raw='fail'  → → 0
[712/765]  raw='pass'  → → 1

 93%|█████████▎| 714/765 [02:05<00:08,  5.80it/s]

[713/765]  raw='fail'  → → 0
[714/765]  raw='pass'  → → 1

 94%|█████████▎| 716/765 [02:05<00:08,  5.93it/s]

[715/765]  raw='fail'  → → 0
[716/765]  raw='pass'  → → 1

 94%|█████████▍| 718/765 [02:06<00:07,  5.98it/s]

[717/765]  raw='pass'  → → 1
[718/765]  raw='pass'  → → 1

 94%|█████████▍| 720/765 [02:06<00:07,  5.96it/s]

[719/765]  raw='pass'  → → 1
[720/765]  raw='fail'  → → 0

 94%|█████████▍| 722/765 [02:06<00:07,  5.95it/s]

[721/765]  raw='pass'  → → 1
[722/765]  raw='fail'  → → 0

 95%|█████████▍| 724/765 [02:07<00:06,  5.99it/s]

[723/765]  raw='fail'  → → 0
[724/765]  raw='fail'  → → 0

 95%|█████████▍| 726/765 [02:07<00:06,  6.04it/s]

[725/765]  raw='fail'  → → 0
[726/765]  raw='pass'  → → 1

 95%|█████████▌| 728/765 [02:07<00:06,  6.04it/s]

[727/765]  raw='pass'  → → 1
[728/765]  raw='pass'  → → 1

 95%|█████████▌| 730/765 [02:08<00:05,  6.03it/s]

[729/765]  raw='pass'  → → 1
[730/765]  raw='pass'  → → 1

 96%|█████████▌| 731/765 [02:08<00:05,  6.04it/s]

[731/765]  raw='fail'  → → 0

 96%|█████████▌| 733/765 [02:08<00:05,  5.71it/s]

[732/765]  raw='pass'  → → 1
[733/765]  raw='fail'  → → 0

 96%|█████████▌| 735/765 [02:08<00:05,  5.89it/s]

[734/765]  raw='pass'  → → 1
[735/765]  raw='fail'  → → 0

 96%|█████████▋| 737/765 [02:09<00:04,  5.99it/s]

[736/765]  raw='fail'  → → 0
[737/765]  raw='pass'  → → 1

 97%|█████████▋| 739/765 [02:09<00:04,  6.03it/s]

[738/765]  raw='pass'  → → 1
[739/765]  raw='fail'  → → 0

 97%|█████████▋| 741/765 [02:09<00:03,  6.05it/s]

[740/765]  raw='fail'  → → 0
[741/765]  raw='pass'  → → 1

 97%|█████████▋| 743/765 [02:10<00:03,  6.07it/s]

[742/765]  raw='pass'  → → 1
[743/765]  raw='fail'  → → 0

 97%|█████████▋| 745/765 [02:10<00:03,  6.03it/s]

[744/765]  raw='pass'  → → 1
[745/765]  raw='fail'  → → 0

 98%|█████████▊| 747/765 [02:10<00:02,  6.01it/s]

[746/765]  raw='pass'  → → 1
[747/765]  raw='fail'  → → 0

 98%|█████████▊| 749/765 [02:11<00:02,  6.02it/s]

[748/765]  raw='pass'  → → 1
[749/765]  raw='fail'  → → 0

 98%|█████████▊| 751/765 [02:11<00:02,  6.05it/s]

[750/765]  raw='fail'  → → 0
[751/765]  raw='pass'  → → 1

 98%|█████████▊| 753/765 [02:11<00:02,  5.89it/s]

[752/765]  raw='pass'  → → 1
[753/765]  raw='fail'  → → 0

 99%|█████████▊| 755/765 [02:12<00:01,  5.87it/s]

[754/765]  raw='fail'  → → 0
[755/765]  raw='pass'  → → 1

 99%|█████████▉| 757/765 [02:12<00:01,  5.75it/s]

[756/765]  raw='pass'  → → 1
[757/765]  raw='pass'  → → 1

 99%|█████████▉| 759/765 [02:12<00:01,  5.64it/s]

[758/765]  raw='pass'  → → 1
[759/765]  raw='pass'  → → 1

 99%|█████████▉| 761/765 [02:13<00:00,  5.85it/s]

[760/765]  raw='pass'  → → 1
[761/765]  raw='pass'  → → 1

100%|█████████▉| 763/765 [02:13<00:00,  5.58it/s]

[762/765]  raw='fail'  → → 0
[763/765]  raw='pass'  → → 1

100%|██████████| 765/765 [02:13<00:00,  5.71it/s]

[764/765]  raw='pass'  → → 1
[765/765]  raw='pass'  → → 1
Parsed: 765/765
Accuracy: 0.6902
              precision    recall  f1-score   support

        Fail       0.85      0.56      0.68       442
        Pass       0.59      0.87      0.70       323

    accuracy                           0.69       765
   macro avg       0.72      0.71      0.69       765
weighted avg       0.74      0.69      0.69       765

Predicted-Pass fraction: 0.6196078431372549  (true rate 0.42)

First time i see this ACC of .69 no finetuned O_O

In [ ]:
#Part 2 lora
# Part 2: QLoRA finetune
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
from datasets import Dataset

# Llama architecture target modules
lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05, bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
)


tokenizer.padding_side = "right"             # training mode...remember why
train_hf = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in train_balanced.iterrows()])
val_hf   = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in val_df.iterrows()])
print(repr(train_hf[0]["prompt"][-90:]))     # want ...<|start_header_id|>assistant<|end_header_id|>...
print(repr(train_hf[0]["completion"]))       # 'Pass' or 'Fail'

model.config.use_cache = False
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()           # expect ~0.4-0.6%, NOT zero

'ith one word only (Fail or Pass):<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'
'Pass'
trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

In [ ]:
# A100 GPU, that it we rich today
# train the stabilized recipe (learned the hard way on Qwen)
sft_config = SFTConfig(
    output_dir="./llama31-lora-balanced",
    num_train_epochs=1,
    per_device_train_batch_size=4,           # 8B is heavier than 7B so lets start conservative
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=4,           # effective batch = 16
    warmup_steps=100,
    learning_rate=5e-5,
    max_grad_norm=0.3,
    fp16=False, bf16=True,                   # A100 GPU we
    logging_steps=10,
    eval_strategy="steps", eval_steps=50,
    save_strategy="steps", save_steps=50,
    load_best_model_at_end=True, metric_for_best_model="eval_loss",
    report_to="none",
    max_length=2000,                                  #i forgot to check llama context windown so im jusst putting 2000....
    completion_only_loss=True,
    optim="paged_adamw_8bit",
)

trainer = SFTTrainer(
    model=model, args=sft_config,
    train_dataset=train_hf,
    eval_dataset=val_hf.select(range(250)),
    processing_class=tokenizer,
)
trainer.train()

Adding EOS to train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 128009}.

TrainOutput(global_step=189, training_loss=0.1783652286680918, metrics={'train_runtime': 1284.9635, 'train_samples_per_second': 2.342, 'train_steps_per_second': 0.147, 'total_flos': 1.1647431114591437e+17, 'train_loss': 0.1783652286680918, 'epoch': 1.0})

In [ ]:
ADAPTER_PATH = "./llama31-lora-balanced-adapter"

trainer.model.save_pretrained(ADAPTER_PATH)
tokenizer.save_pretrained(ADAPTER_PATH)
print(f"Saved locally: {ADAPTER_PATH}")
print(f"Files: {os.listdir(ADAPTER_PATH)}")

Saved locally: ./llama31-lora-balanced-adapter
Files: ['adapter_model.safetensors', 'tokenizer_config.json', 'chat_template.jinja', 'adapter_config.json', 'README.md', 'tokenizer.json']

In [ ]:
import shutil, os
from google.colab import drive

drive.mount("/content/drive", force_remount=True)

LOCAL_ADAPTER_PATH = "./llama31-lora-balanced-adapter"
DRIVE_ADAPTER_PATH = "/content/drive/MyDrive/llama31-lora-balanced-adapter"

assert os.path.exists(LOCAL_ADAPTER_PATH), "No local adapter — did the save cell run?"

if os.path.exists(DRIVE_ADAPTER_PATH):
    shutil.rmtree(DRIVE_ADAPTER_PATH)
    print("Removed old version from Drive")

shutil.copytree(LOCAL_ADAPTER_PATH, DRIVE_ADAPTER_PATH)
print(f"   Backed up to Drive: {DRIVE_ADAPTER_PATH}")
print(f"   Files: {os.listdir(DRIVE_ADAPTER_PATH)}")

In [ ]:
tokenizer.padding_side = "left"          # flip back from training's "right"
model_ft = trainer.model                 # best checkpoint via load_best_model_at_end
model_ft.eval()
model_ft.config.use_cache = False

smoke = X_val_prompts.iloc[:1].reset_index(drop=True)
_, g = predict_decoder_only(smoke, model_ft, tokenizer)
print(repr(g[0]))    # want a clean 'pass' or 'fail'

100%|██████████| 1/1 [00:00<00:00,  2.89it/s]

[  1/1]  raw='pass'  → → 1
'pass'

In [ ]:
y_pred, y_generated = predict_decoder_only(
    X_test_prompts.reset_index(drop=True), model_ft, tokenizer
)

# results to Drive!!!!!!!!!!!!!!!!!!!!!!!!
pd.DataFrame({"y_true": y_true, "y_pred": y_pred, "generated": y_generated}) \
  .to_csv("/content/drive/MyDrive/llama31_finetuned_test_results.csv", index=False)

valid = [i for i, p in enumerate(y_pred) if p != -1]
yt = y_true[valid]; yp = [y_pred[i] for i in valid]

print(f"Parsed: {len(valid)}/{len(y_pred)}")
print(f"Accuracy: {accuracy_score(yt, yp):.4f}")
print(classification_report(yt, yp, target_names=["Fail", "Pass"]))
print(confusion_matrix(yt, yp))
print("Predicted-Pass fraction:", (pd.Series(yp)==1).mean(), " (true rate 0.42)")

  0%|          | 1/765 [00:00<03:59,  3.19it/s]

[  1/765]  raw='fail'  → → 0

  0%|          | 2/765 [00:00<03:59,  3.18it/s]

[  2/765]  raw='fail'  → → 0

  0%|          | 3/765 [00:00<03:56,  3.22it/s]

[  3/765]  raw='fail'  → → 0

  1%|          | 4/765 [00:01<04:17,  2.96it/s]

[  4/765]  raw='pass'  → → 1

  1%|          | 5/765 [00:01<04:08,  3.06it/s]

[  5/765]  raw='fail'  → → 0

  1%|          | 6/765 [00:01<04:04,  3.11it/s]

[  6/765]  raw='fail'  → → 0

  1%|          | 7/765 [00:02<04:01,  3.14it/s]

[  7/765]  raw='pass'  → → 1

  1%|          | 8/765 [00:02<04:00,  3.15it/s]

[  8/765]  raw='fail'  → → 0

  1%|          | 9/765 [00:02<04:15,  2.96it/s]

[  9/765]  raw='pass'  → → 1

  1%|▏         | 10/765 [00:03<04:09,  3.03it/s]

[ 10/765]  raw='fail'  → → 0

  1%|▏         | 11/765 [00:03<04:04,  3.09it/s]

[ 11/765]  raw='fail'  → → 0

  2%|▏         | 12/765 [00:03<04:15,  2.94it/s]

[ 12/765]  raw='pass'  → → 1

  2%|▏         | 13/765 [00:04<04:08,  3.03it/s]

[ 13/765]  raw='pass'  → → 1

  2%|▏         | 14/765 [00:04<04:02,  3.10it/s]

[ 14/765]  raw='pass'  → → 1

  2%|▏         | 15/765 [00:04<03:58,  3.14it/s]

[ 15/765]  raw='fail'  → → 0

  2%|▏         | 16/765 [00:05<03:55,  3.17it/s]

[ 16/765]  raw='pass'  → → 1

  2%|▏         | 17/765 [00:05<03:54,  3.19it/s]

[ 17/765]  raw='fail'  → → 0

  2%|▏         | 18/765 [00:05<03:54,  3.19it/s]

[ 18/765]  raw='pass'  → → 1

  2%|▏         | 19/765 [00:06<03:51,  3.22it/s]

[ 19/765]  raw='fail'  → → 0

  3%|▎         | 20/765 [00:06<04:23,  2.83it/s]

[ 20/765]  raw='pass'  → → 1

  3%|▎         | 21/765 [00:06<04:11,  2.96it/s]

[ 21/765]  raw='fail'  → → 0

  3%|▎         | 22/765 [00:07<04:02,  3.06it/s]

[ 22/765]  raw='fail'  → → 0

  3%|▎         | 23/765 [00:07<03:56,  3.14it/s]

[ 23/765]  raw='fail'  → → 0

  3%|▎         | 24/765 [00:07<04:18,  2.86it/s]

[ 24/765]  raw='pass'  → → 1

  3%|▎         | 25/765 [00:08<04:07,  2.99it/s]

[ 25/765]  raw='pass'  → → 1

  3%|▎         | 26/765 [00:08<03:59,  3.08it/s]

[ 26/765]  raw='fail'  → → 0

  4%|▎         | 27/765 [00:08<03:56,  3.12it/s]

[ 27/765]  raw='fail'  → → 0

  4%|▎         | 28/765 [00:09<03:53,  3.16it/s]

[ 28/765]  raw='fail'  → → 0

  4%|▍         | 29/765 [00:09<03:50,  3.19it/s]

[ 29/765]  raw='pass'  → → 1

  4%|▍         | 30/765 [00:09<03:47,  3.24it/s]

[ 30/765]  raw='fail'  → → 0

  4%|▍         | 31/765 [00:10<03:45,  3.25it/s]

[ 31/765]  raw='pass'  → → 1

  4%|▍         | 32/765 [00:10<03:46,  3.24it/s]

[ 32/765]  raw='fail'  → → 0

  4%|▍         | 33/765 [00:10<04:11,  2.91it/s]

[ 33/765]  raw='pass'  → → 1

  4%|▍         | 34/765 [00:11<04:03,  3.00it/s]

[ 34/765]  raw='fail'  → → 0

  5%|▍         | 35/765 [00:11<03:58,  3.06it/s]

[ 35/765]  raw='fail'  → → 0

  5%|▍         | 36/765 [00:11<03:54,  3.10it/s]

[ 36/765]  raw='fail'  → → 0

  5%|▍         | 37/765 [00:11<03:50,  3.15it/s]

[ 37/765]  raw='pass'  → → 1

  5%|▍         | 38/765 [00:12<03:50,  3.16it/s]

[ 38/765]  raw='fail'  → → 0

  5%|▌         | 39/765 [00:12<03:47,  3.19it/s]

[ 39/765]  raw='pass'  → → 1

  5%|▌         | 40/765 [00:12<03:59,  3.02it/s]

[ 40/765]  raw='pass'  → → 1

  5%|▌         | 41/765 [00:13<04:30,  2.67it/s]

[ 41/765]  raw='pass'  → → 1

  5%|▌         | 42/765 [00:13<04:15,  2.83it/s]

[ 42/765]  raw='fail'  → → 0

  6%|▌         | 43/765 [00:14<04:04,  2.95it/s]

[ 43/765]  raw='fail'  → → 0

  6%|▌         | 44/765 [00:14<03:57,  3.04it/s]

[ 44/765]  raw='pass'  → → 1

  6%|▌         | 45/765 [00:14<03:51,  3.11it/s]

[ 45/765]  raw='fail'  → → 0

  6%|▌         | 46/765 [00:14<03:47,  3.16it/s]

[ 46/765]  raw='fail'  → → 0

  6%|▌         | 47/765 [00:15<03:44,  3.20it/s]

[ 47/765]  raw='pass'  → → 1

  6%|▋         | 48/765 [00:15<03:42,  3.23it/s]

[ 48/765]  raw='pass'  → → 1

  6%|▋         | 49/765 [00:15<03:40,  3.25it/s]

[ 49/765]  raw='fail'  → → 0

  7%|▋         | 50/765 [00:16<03:40,  3.24it/s]

[ 50/765]  raw='pass'  → → 1

  7%|▋         | 51/765 [00:16<03:38,  3.26it/s]

[ 51/765]  raw='fail'  → → 0

  7%|▋         | 52/765 [00:16<03:39,  3.25it/s]

[ 52/765]  raw='fail'  → → 0

  7%|▋         | 53/765 [00:17<03:37,  3.27it/s]

[ 53/765]  raw='pass'  → → 1

  7%|▋         | 54/765 [00:17<04:24,  2.69it/s]

[ 54/765]  raw='pass'  → → 1

  7%|▋         | 55/765 [00:17<04:09,  2.84it/s]

[ 55/765]  raw='fail'  → → 0

  7%|▋         | 56/765 [00:18<03:59,  2.96it/s]

[ 56/765]  raw='fail'  → → 0

  7%|▋         | 57/765 [00:18<03:53,  3.04it/s]

[ 57/765]  raw='fail'  → → 0

  8%|▊         | 58/765 [00:18<03:47,  3.11it/s]

[ 58/765]  raw='pass'  → → 1

  8%|▊         | 59/765 [00:19<03:43,  3.16it/s]

[ 59/765]  raw='pass'  → → 1

  8%|▊         | 60/765 [00:19<03:40,  3.20it/s]

[ 60/765]  raw='fail'  → → 0

  8%|▊         | 61/765 [00:19<03:38,  3.22it/s]

[ 61/765]  raw='pass'  → → 1

  8%|▊         | 62/765 [00:20<03:36,  3.24it/s]

[ 62/765]  raw='fail'  → → 0

  8%|▊         | 63/765 [00:20<03:47,  3.08it/s]

[ 63/765]  raw='pass'  → → 1

  8%|▊         | 64/765 [00:20<03:43,  3.13it/s]

[ 64/765]  raw='fail'  → → 0

  8%|▊         | 65/765 [00:21<03:42,  3.15it/s]

[ 65/765]  raw='fail'  → → 0

  9%|▊         | 66/765 [00:21<03:40,  3.18it/s]

[ 66/765]  raw='pass'  → → 1

  9%|▉         | 67/765 [00:21<03:50,  3.03it/s]

[ 67/765]  raw='pass'  → → 1

  9%|▉         | 68/765 [00:22<03:45,  3.10it/s]

[ 68/765]  raw='fail'  → → 0

  9%|▉         | 69/765 [00:22<03:41,  3.15it/s]

[ 69/765]  raw='fail'  → → 0

  9%|▉         | 70/765 [00:22<03:38,  3.18it/s]

[ 70/765]  raw='fail'  → → 0

  9%|▉         | 71/765 [00:22<03:38,  3.17it/s]

[ 71/765]  raw='fail'  → → 0

  9%|▉         | 72/765 [00:23<03:38,  3.17it/s]

[ 72/765]  raw='fail'  → → 0

 10%|▉         | 73/765 [00:23<03:38,  3.17it/s]

[ 73/765]  raw='fail'  → → 0

 10%|▉         | 74/765 [00:23<03:38,  3.17it/s]

[ 74/765]  raw='fail'  → → 0

 10%|▉         | 75/765 [00:24<03:37,  3.17it/s]

[ 75/765]  raw='fail'  → → 0

 10%|▉         | 76/765 [00:24<03:36,  3.18it/s]

[ 76/765]  raw='pass'  → → 1

 10%|█         | 77/765 [00:24<03:35,  3.19it/s]

[ 77/765]  raw='fail'  → → 0

 10%|█         | 78/765 [00:25<03:35,  3.19it/s]

[ 78/765]  raw='pass'  → → 1

 10%|█         | 79/765 [00:25<03:34,  3.19it/s]

[ 79/765]  raw='fail'  → → 0

 10%|█         | 80/765 [00:25<03:55,  2.91it/s]

[ 80/765]  raw='pass'  → → 1

 11%|█         | 81/765 [00:26<03:48,  2.99it/s]

[ 81/765]  raw='pass'  → → 1

 11%|█         | 82/765 [00:26<03:42,  3.07it/s]

[ 82/765]  raw='fail'  → → 0

 11%|█         | 83/765 [00:26<04:09,  2.73it/s]

[ 83/765]  raw='pass'  → → 1

 11%|█         | 84/765 [00:27<04:27,  2.55it/s]

[ 84/765]  raw='pass'  → → 1

 11%|█         | 85/765 [00:27<04:08,  2.73it/s]

[ 85/765]  raw='fail'  → → 0

 11%|█         | 86/765 [00:28<03:56,  2.88it/s]

[ 86/765]  raw='fail'  → → 0

 11%|█▏        | 87/765 [00:28<03:47,  2.98it/s]

[ 87/765]  raw='pass'  → → 1

 12%|█▏        | 88/765 [00:28<03:41,  3.06it/s]

[ 88/765]  raw='fail'  → → 0

 12%|█▏        | 89/765 [00:28<03:36,  3.12it/s]

[ 89/765]  raw='pass'  → → 1

 12%|█▏        | 90/765 [00:29<03:36,  3.12it/s]

[ 90/765]  raw='fail'  → → 0

 12%|█▏        | 91/765 [00:29<03:32,  3.17it/s]

[ 91/765]  raw='pass'  → → 1

 12%|█▏        | 92/765 [00:30<03:59,  2.81it/s]

[ 92/765]  raw='pass'  → → 1

 12%|█▏        | 93/765 [00:30<03:49,  2.92it/s]

[ 93/765]  raw='pass'  → → 1

 12%|█▏        | 94/765 [00:30<03:42,  3.02it/s]

[ 94/765]  raw='fail'  → → 0

 12%|█▏        | 95/765 [00:30<03:36,  3.09it/s]

[ 95/765]  raw='fail'  → → 0

 13%|█▎        | 96/765 [00:31<03:32,  3.14it/s]

[ 96/765]  raw='fail'  → → 0

 13%|█▎        | 97/765 [00:31<03:29,  3.18it/s]

[ 97/765]  raw='fail'  → → 0

 13%|█▎        | 98/765 [00:31<03:27,  3.21it/s]

[ 98/765]  raw='fail'  → → 0

 13%|█▎        | 99/765 [00:32<03:48,  2.91it/s]

[ 99/765]  raw='pass'  → → 1

 13%|█▎        | 100/765 [00:32<03:40,  3.01it/s]

[100/765]  raw='fail'  → → 0

 13%|█▎        | 101/765 [00:32<03:35,  3.09it/s]

[101/765]  raw='fail'  → → 0

 13%|█▎        | 102/765 [00:33<03:31,  3.14it/s]

[102/765]  raw='pass'  → → 1

 13%|█▎        | 103/765 [00:33<03:28,  3.18it/s]

[103/765]  raw='fail'  → → 0

 14%|█▎        | 104/765 [00:33<03:25,  3.21it/s]

[104/765]  raw='fail'  → → 0

 14%|█▎        | 105/765 [00:34<03:24,  3.23it/s]

[105/765]  raw='fail'  → → 0

 14%|█▍        | 106/765 [00:34<03:47,  2.90it/s]

[106/765]  raw='pass'  → → 1

 14%|█▍        | 107/765 [00:34<03:39,  3.00it/s]

[107/765]  raw='pass'  → → 1

 14%|█▍        | 108/765 [00:35<03:34,  3.07it/s]

[108/765]  raw='fail'  → → 0

 14%|█▍        | 109/765 [00:35<03:31,  3.10it/s]

[109/765]  raw='pass'  → → 1

 14%|█▍        | 110/765 [00:35<03:30,  3.12it/s]

[110/765]  raw='fail'  → → 0

 15%|█▍        | 111/765 [00:36<03:28,  3.13it/s]

[111/765]  raw='fail'  → → 0

 15%|█▍        | 112/765 [00:36<03:28,  3.14it/s]

[112/765]  raw='fail'  → → 0

 15%|█▍        | 113/765 [00:36<03:26,  3.15it/s]

[113/765]  raw='pass'  → → 1

 15%|█▍        | 114/765 [00:37<03:25,  3.17it/s]

[114/765]  raw='fail'  → → 0

 15%|█▌        | 115/765 [00:37<03:24,  3.17it/s]

[115/765]  raw='fail'  → → 0

 15%|█▌        | 116/765 [00:37<03:24,  3.17it/s]

[116/765]  raw='fail'  → → 0

 15%|█▌        | 117/765 [00:37<03:23,  3.18it/s]

[117/765]  raw='pass'  → → 1

 15%|█▌        | 118/765 [00:38<03:22,  3.20it/s]

[118/765]  raw='pass'  → → 1

 16%|█▌        | 119/765 [00:38<03:20,  3.23it/s]

[119/765]  raw='fail'  → → 0

 16%|█▌        | 120/765 [00:38<03:19,  3.24it/s]

[120/765]  raw='pass'  → → 1

 16%|█▌        | 121/765 [00:39<03:27,  3.10it/s]

[121/765]  raw='pass'  → → 1

 16%|█▌        | 122/765 [00:39<03:24,  3.15it/s]

[122/765]  raw='fail'  → → 0

 16%|█▌        | 123/765 [00:39<03:31,  3.04it/s]

[123/765]  raw='pass'  → → 1

 16%|█▌        | 124/765 [00:40<03:27,  3.08it/s]

[124/765]  raw='pass'  → → 1

 16%|█▋        | 125/765 [00:40<03:24,  3.13it/s]

[125/765]  raw='fail'  → → 0

 16%|█▋        | 126/765 [00:40<03:21,  3.17it/s]

[126/765]  raw='fail'  → → 0

 17%|█▋        | 127/765 [00:41<03:19,  3.19it/s]

[127/765]  raw='fail'  → → 0

 17%|█▋        | 128/765 [00:41<03:18,  3.21it/s]

[128/765]  raw='fail'  → → 0

 17%|█▋        | 129/765 [00:41<03:16,  3.23it/s]

[129/765]  raw='fail'  → → 0

 17%|█▋        | 130/765 [00:42<03:26,  3.07it/s]

[130/765]  raw='pass'  → → 1

 17%|█▋        | 131/765 [00:42<03:22,  3.13it/s]

[131/765]  raw='fail'  → → 0

 17%|█▋        | 132/765 [00:42<03:19,  3.17it/s]

[132/765]  raw='fail'  → → 0

 17%|█▋        | 133/765 [00:43<03:16,  3.21it/s]

[133/765]  raw='fail'  → → 0

 18%|█▊        | 134/765 [00:43<03:15,  3.23it/s]

[134/765]  raw='fail'  → → 0

 18%|█▊        | 135/765 [00:43<03:14,  3.24it/s]

[135/765]  raw='fail'  → → 0

 18%|█▊        | 136/765 [00:43<03:13,  3.26it/s]

[136/765]  raw='fail'  → → 0

 18%|█▊        | 137/765 [00:44<03:42,  2.83it/s]

[137/765]  raw='pass'  → → 1

 18%|█▊        | 138/765 [00:44<03:35,  2.91it/s]

[138/765]  raw='pass'  → → 1

 18%|█▊        | 139/765 [00:45<03:56,  2.64it/s]

[139/765]  raw='pass'  → → 1

 18%|█▊        | 140/765 [00:45<03:42,  2.80it/s]

[140/765]  raw='fail'  → → 0

 18%|█▊        | 141/765 [00:45<03:33,  2.93it/s]

[141/765]  raw='fail'  → → 0

 19%|█▊        | 142/765 [00:46<03:36,  2.88it/s]

[142/765]  raw='fail'  → → 0

 19%|█▊        | 143/765 [00:46<03:28,  2.98it/s]

[143/765]  raw='pass'  → → 1

 19%|█▉        | 144/765 [00:47<04:14,  2.44it/s]

[144/765]  raw='pass'  → → 1

 19%|█▉        | 145/765 [00:47<03:55,  2.63it/s]

[145/765]  raw='fail'  → → 0

 19%|█▉        | 146/765 [00:47<03:41,  2.80it/s]

[146/765]  raw='pass'  → → 1

 19%|█▉        | 147/765 [00:48<04:00,  2.57it/s]

[147/765]  raw='pass'  → → 1

 19%|█▉        | 148/765 [00:48<03:47,  2.71it/s]

[148/765]  raw='pass'  → → 1

 19%|█▉        | 149/765 [00:48<03:37,  2.83it/s]

[149/765]  raw='pass'  → → 1

 20%|█▉        | 150/765 [00:49<03:30,  2.92it/s]

[150/765]  raw='fail'  → → 0

 20%|█▉        | 151/765 [00:49<03:44,  2.74it/s]

[151/765]  raw='pass'  → → 1

 20%|█▉        | 152/765 [00:49<03:35,  2.85it/s]

[152/765]  raw='pass'  → → 1

 20%|██        | 153/765 [00:50<03:27,  2.94it/s]

[153/765]  raw='fail'  → → 0

 20%|██        | 154/765 [00:50<03:23,  3.01it/s]

[154/765]  raw='pass'  → → 1

 20%|██        | 155/765 [00:50<03:20,  3.05it/s]

[155/765]  raw='pass'  → → 1

 20%|██        | 156/765 [00:51<03:29,  2.90it/s]

[156/765]  raw='pass'  → → 1

 21%|██        | 157/765 [00:51<03:32,  2.86it/s]

[157/765]  raw='pass'  → → 1

 21%|██        | 158/765 [00:51<03:37,  2.79it/s]

[158/765]  raw='pass'  → → 1

 21%|██        | 159/765 [00:52<03:28,  2.91it/s]

[159/765]  raw='pass'  → → 1

 21%|██        | 160/765 [00:52<03:34,  2.82it/s]

[160/765]  raw='pass'  → → 1

 21%|██        | 161/765 [00:52<03:25,  2.94it/s]

[161/765]  raw='fail'  → → 0

 21%|██        | 162/765 [00:53<03:19,  3.03it/s]

[162/765]  raw='fail'  → → 0

 21%|██▏       | 163/765 [00:53<03:14,  3.10it/s]

[163/765]  raw='fail'  → → 0

 21%|██▏       | 164/765 [00:53<03:10,  3.15it/s]

[164/765]  raw='pass'  → → 1

 22%|██▏       | 165/765 [00:54<03:08,  3.19it/s]

[165/765]  raw='fail'  → → 0

 22%|██▏       | 166/765 [00:54<03:06,  3.22it/s]

[166/765]  raw='fail'  → → 0

 22%|██▏       | 167/765 [00:54<03:05,  3.23it/s]

[167/765]  raw='fail'  → → 0

 22%|██▏       | 168/765 [00:55<03:03,  3.25it/s]

[168/765]  raw='fail'  → → 0

 22%|██▏       | 169/765 [00:55<03:02,  3.26it/s]

[169/765]  raw='pass'  → → 1

 22%|██▏       | 170/765 [00:55<03:02,  3.26it/s]

[170/765]  raw='fail'  → → 0

 22%|██▏       | 171/765 [00:56<03:13,  3.06it/s]

[171/765]  raw='pass'  → → 1

 22%|██▏       | 172/765 [00:56<03:14,  3.05it/s]

[172/765]  raw='pass'  → → 1

 23%|██▎       | 173/765 [00:56<03:33,  2.78it/s]

[173/765]  raw='pass'  → → 1

 23%|██▎       | 174/765 [00:57<03:42,  2.65it/s]

[174/765]  raw='pass'  → → 1

 23%|██▎       | 175/765 [00:57<03:30,  2.81it/s]

[175/765]  raw='fail'  → → 0

 23%|██▎       | 176/765 [00:57<03:21,  2.92it/s]

[176/765]  raw='fail'  → → 0

 23%|██▎       | 177/765 [00:58<03:14,  3.02it/s]

[177/765]  raw='fail'  → → 0

 23%|██▎       | 178/765 [00:58<03:19,  2.94it/s]

[178/765]  raw='fail'  → → 0

 23%|██▎       | 179/765 [00:58<03:42,  2.63it/s]

[179/765]  raw='pass'  → → 1

 24%|██▎       | 180/765 [00:59<03:29,  2.80it/s]

[180/765]  raw='fail'  → → 0

 24%|██▎       | 181/765 [00:59<03:19,  2.93it/s]

[181/765]  raw='fail'  → → 0

 24%|██▍       | 182/765 [00:59<03:13,  3.02it/s]

[182/765]  raw='fail'  → → 0

 24%|██▍       | 183/765 [01:00<03:08,  3.08it/s]

[183/765]  raw='fail'  → → 0

 24%|██▍       | 184/765 [01:00<03:04,  3.14it/s]

[184/765]  raw='fail'  → → 0

 24%|██▍       | 185/765 [01:00<03:03,  3.17it/s]

[185/765]  raw='pass'  → → 1

 24%|██▍       | 186/765 [01:01<03:19,  2.90it/s]

[186/765]  raw='pass'  → → 1

 24%|██▍       | 187/765 [01:01<03:14,  2.97it/s]

[187/765]  raw='fail'  → → 0

 25%|██▍       | 188/765 [01:01<03:10,  3.02it/s]

[188/765]  raw='fail'  → → 0

 25%|██▍       | 189/765 [01:02<03:07,  3.07it/s]

[189/765]  raw='pass'  → → 1

 25%|██▍       | 190/765 [01:02<03:03,  3.13it/s]

[190/765]  raw='pass'  → → 1

 25%|██▍       | 191/765 [01:02<03:00,  3.17it/s]

[191/765]  raw='fail'  → → 0

 25%|██▌       | 192/765 [01:03<03:24,  2.80it/s]

[192/765]  raw='pass'  → → 1

 25%|██▌       | 193/765 [01:03<03:16,  2.90it/s]

[193/765]  raw='fail'  → → 0

 25%|██▌       | 194/765 [01:03<03:10,  3.00it/s]

[194/765]  raw='fail'  → → 0

 25%|██▌       | 195/765 [01:04<03:52,  2.46it/s]

[195/765]  raw='pass'  → → 1

 26%|██▌       | 196/765 [01:04<03:34,  2.65it/s]

[196/765]  raw='fail'  → → 0

 26%|██▌       | 197/765 [01:05<03:23,  2.79it/s]

[197/765]  raw='pass'  → → 1

 26%|██▌       | 198/765 [01:05<03:13,  2.93it/s]

[198/765]  raw='pass'  → → 1

 26%|██▌       | 199/765 [01:05<03:07,  3.02it/s]

[199/765]  raw='pass'  → → 1

 26%|██▌       | 200/765 [01:05<03:02,  3.09it/s]

[200/765]  raw='fail'  → → 0

 26%|██▋       | 201/765 [01:06<02:59,  3.14it/s]

[201/765]  raw='fail'  → → 0

 26%|██▋       | 202/765 [01:06<02:56,  3.19it/s]

[202/765]  raw='pass'  → → 1

 27%|██▋       | 203/765 [01:06<02:55,  3.21it/s]

[203/765]  raw='fail'  → → 0

 27%|██▋       | 204/765 [01:07<02:53,  3.23it/s]

[204/765]  raw='fail'  → → 0

 27%|██▋       | 205/765 [01:07<02:52,  3.24it/s]

[205/765]  raw='fail'  → → 0

 27%|██▋       | 206/765 [01:07<02:52,  3.25it/s]

[206/765]  raw='fail'  → → 0

 27%|██▋       | 207/765 [01:08<03:04,  3.03it/s]

[207/765]  raw='pass'  → → 1

 27%|██▋       | 208/765 [01:08<02:59,  3.10it/s]

[208/765]  raw='pass'  → → 1

 27%|██▋       | 209/765 [01:08<02:56,  3.15it/s]

[209/765]  raw='fail'  → → 0

 27%|██▋       | 210/765 [01:09<02:53,  3.19it/s]

[210/765]  raw='pass'  → → 1

 28%|██▊       | 211/765 [01:09<02:51,  3.22it/s]

[211/765]  raw='fail'  → → 0

 28%|██▊       | 212/765 [01:09<02:50,  3.24it/s]

[212/765]  raw='fail'  → → 0

 28%|██▊       | 213/765 [01:10<02:49,  3.25it/s]

[213/765]  raw='pass'  → → 1

 28%|██▊       | 214/765 [01:10<02:49,  3.26it/s]

[214/765]  raw='fail'  → → 0

 28%|██▊       | 215/765 [01:10<02:47,  3.28it/s]

[215/765]  raw='fail'  → → 0

 28%|██▊       | 216/765 [01:10<02:48,  3.27it/s]

[216/765]  raw='fail'  → → 0

 28%|██▊       | 217/765 [01:11<02:47,  3.28it/s]

[217/765]  raw='fail'  → → 0

 28%|██▊       | 218/765 [01:11<03:22,  2.70it/s]

[218/765]  raw='pass'  → → 1

 29%|██▊       | 219/765 [01:12<03:19,  2.73it/s]

[219/765]  raw='pass'  → → 1

 29%|██▉       | 220/765 [01:12<03:09,  2.88it/s]

[220/765]  raw='fail'  → → 0

 29%|██▉       | 221/765 [01:12<03:01,  3.00it/s]

[221/765]  raw='fail'  → → 0

 29%|██▉       | 222/765 [01:13<02:55,  3.09it/s]

[222/765]  raw='fail'  → → 0

 29%|██▉       | 223/765 [01:13<03:04,  2.93it/s]

[223/765]  raw='pass'  → → 1

 29%|██▉       | 224/765 [01:13<03:03,  2.95it/s]

[224/765]  raw='pass'  → → 1

 29%|██▉       | 225/765 [01:14<02:58,  3.02it/s]

[225/765]  raw='fail'  → → 0

 30%|██▉       | 226/765 [01:14<03:04,  2.92it/s]

[226/765]  raw='pass'  → → 1

 30%|██▉       | 227/765 [01:14<03:00,  2.99it/s]

[227/765]  raw='pass'  → → 1

 30%|██▉       | 228/765 [01:15<02:56,  3.05it/s]

[228/765]  raw='fail'  → → 0

 30%|██▉       | 229/765 [01:15<02:54,  3.08it/s]

[229/765]  raw='fail'  → → 0

 30%|███       | 230/765 [01:15<02:51,  3.11it/s]

[230/765]  raw='fail'  → → 0

 30%|███       | 231/765 [01:15<02:50,  3.14it/s]

[231/765]  raw='pass'  → → 1

 30%|███       | 232/765 [01:16<02:49,  3.15it/s]

[232/765]  raw='pass'  → → 1

 30%|███       | 233/765 [01:16<02:46,  3.19it/s]

[233/765]  raw='fail'  → → 0

 31%|███       | 234/765 [01:16<02:45,  3.22it/s]

[234/765]  raw='fail'  → → 0

 31%|███       | 235/765 [01:17<02:52,  3.07it/s]

[235/765]  raw='pass'  → → 1

 31%|███       | 236/765 [01:17<02:48,  3.15it/s]

[236/765]  raw='fail'  → → 0

 31%|███       | 237/765 [01:17<02:44,  3.20it/s]

[237/765]  raw='fail'  → → 0

 31%|███       | 238/765 [01:18<02:43,  3.22it/s]

[238/765]  raw='fail'  → → 0

 31%|███       | 239/765 [01:18<02:43,  3.22it/s]

[239/765]  raw='pass'  → → 1

 31%|███▏      | 240/765 [01:18<02:41,  3.25it/s]

[240/765]  raw='pass'  → → 1

 32%|███▏      | 241/765 [01:19<02:50,  3.08it/s]

[241/765]  raw='pass'  → → 1

 32%|███▏      | 242/765 [01:19<02:47,  3.13it/s]

[242/765]  raw='fail'  → → 0

 32%|███▏      | 243/765 [01:19<02:44,  3.17it/s]

[243/765]  raw='fail'  → → 0

 32%|███▏      | 244/765 [01:20<02:42,  3.21it/s]

[244/765]  raw='fail'  → → 0

 32%|███▏      | 245/765 [01:20<02:41,  3.22it/s]

[245/765]  raw='fail'  → → 0

 32%|███▏      | 246/765 [01:20<03:22,  2.56it/s]

[246/765]  raw='pass'  → → 1

 32%|███▏      | 247/765 [01:21<03:08,  2.75it/s]

[247/765]  raw='pass'  → → 1

 32%|███▏      | 248/765 [01:21<02:58,  2.89it/s]

[248/765]  raw='fail'  → → 0

 33%|███▎      | 249/765 [01:21<02:51,  3.01it/s]

[249/765]  raw='pass'  → → 1

 33%|███▎      | 250/765 [01:22<02:46,  3.10it/s]

[250/765]  raw='fail'  → → 0

 33%|███▎      | 251/765 [01:22<02:43,  3.15it/s]

[251/765]  raw='fail'  → → 0

 33%|███▎      | 252/765 [01:22<02:41,  3.18it/s]

[252/765]  raw='fail'  → → 0

 33%|███▎      | 253/765 [01:23<02:39,  3.22it/s]

[253/765]  raw='fail'  → → 0

 33%|███▎      | 254/765 [01:23<02:37,  3.24it/s]

[254/765]  raw='fail'  → → 0

 33%|███▎      | 255/765 [01:23<02:55,  2.91it/s]

[255/765]  raw='pass'  → → 1

 33%|███▎      | 256/765 [01:24<02:49,  3.01it/s]

[256/765]  raw='fail'  → → 0

 34%|███▎      | 257/765 [01:24<02:44,  3.09it/s]

[257/765]  raw='fail'  → → 0

 34%|███▎      | 258/765 [01:24<02:41,  3.14it/s]

[258/765]  raw='fail'  → → 0

 34%|███▍      | 259/765 [01:25<02:39,  3.18it/s]

[259/765]  raw='fail'  → → 0

 34%|███▍      | 260/765 [01:25<02:37,  3.20it/s]

[260/765]  raw='pass'  → → 1

 34%|███▍      | 261/765 [01:25<02:36,  3.22it/s]

[261/765]  raw='fail'  → → 0

 34%|███▍      | 262/765 [01:25<02:44,  3.05it/s]

[262/765]  raw='pass'  → → 1

 34%|███▍      | 263/765 [01:26<02:42,  3.10it/s]

[263/765]  raw='pass'  → → 1

 35%|███▍      | 264/765 [01:26<02:40,  3.13it/s]

[264/765]  raw='fail'  → → 0

 35%|███▍      | 265/765 [01:26<02:48,  2.96it/s]

[265/765]  raw='pass'  → → 1

 35%|███▍      | 266/765 [01:27<02:44,  3.03it/s]

[266/765]  raw='pass'  → → 1

 35%|███▍      | 267/765 [01:27<02:59,  2.78it/s]

[267/765]  raw='pass'  → → 1

 35%|███▌      | 268/765 [01:28<02:52,  2.89it/s]

[268/765]  raw='pass'  → → 1

 35%|███▌      | 269/765 [01:28<02:45,  2.99it/s]

[269/765]  raw='pass'  → → 1

 35%|███▌      | 270/765 [01:28<02:42,  3.05it/s]

[270/765]  raw='fail'  → → 0

 35%|███▌      | 271/765 [01:28<02:40,  3.08it/s]

[271/765]  raw='fail'  → → 0

 36%|███▌      | 272/765 [01:29<02:37,  3.12it/s]

[272/765]  raw='pass'  → → 1

 36%|███▌      | 273/765 [01:29<02:35,  3.17it/s]

[273/765]  raw='fail'  → → 0

 36%|███▌      | 274/765 [01:29<02:33,  3.21it/s]

[274/765]  raw='pass'  → → 1

 36%|███▌      | 275/765 [01:30<02:53,  2.83it/s]

[275/765]  raw='pass'  → → 1

 36%|███▌      | 276/765 [01:30<02:46,  2.94it/s]

[276/765]  raw='fail'  → → 0

 36%|███▌      | 277/765 [01:30<02:40,  3.04it/s]

[277/765]  raw='fail'  → → 0

 36%|███▋      | 278/765 [01:31<02:36,  3.12it/s]

[278/765]  raw='fail'  → → 0

 36%|███▋      | 279/765 [01:31<02:33,  3.17it/s]

[279/765]  raw='pass'  → → 1

 37%|███▋      | 280/765 [01:31<02:31,  3.20it/s]

[280/765]  raw='fail'  → → 0

 37%|███▋      | 281/765 [01:32<02:47,  2.90it/s]

[281/765]  raw='pass'  → → 1

 37%|███▋      | 282/765 [01:32<02:41,  2.99it/s]

[282/765]  raw='fail'  → → 0

 37%|███▋      | 283/765 [01:32<02:43,  2.95it/s]

[283/765]  raw='pass'  → → 1

 37%|███▋      | 284/765 [01:33<02:37,  3.05it/s]

[284/765]  raw='fail'  → → 0

 37%|███▋      | 285/765 [01:33<02:34,  3.11it/s]

[285/765]  raw='fail'  → → 0

 37%|███▋      | 286/765 [01:33<02:31,  3.17it/s]

[286/765]  raw='pass'  → → 1

 38%|███▊      | 287/765 [01:34<02:29,  3.21it/s]

[287/765]  raw='fail'  → → 0

 38%|███▊      | 288/765 [01:34<02:27,  3.24it/s]

[288/765]  raw='pass'  → → 1

 38%|███▊      | 289/765 [01:34<02:26,  3.25it/s]

[289/765]  raw='fail'  → → 0

 38%|███▊      | 290/765 [01:35<02:25,  3.27it/s]

[290/765]  raw='fail'  → → 0

 38%|███▊      | 291/765 [01:35<02:24,  3.28it/s]

[291/765]  raw='fail'  → → 0

 38%|███▊      | 292/765 [01:35<02:24,  3.28it/s]

[292/765]  raw='fail'  → → 0

 38%|███▊      | 293/765 [01:36<02:30,  3.14it/s]

[293/765]  raw='pass'  → → 1

 38%|███▊      | 294/765 [01:36<02:49,  2.78it/s]

[294/765]  raw='pass'  → → 1

 39%|███▊      | 295/765 [01:36<02:41,  2.90it/s]

[295/765]  raw='fail'  → → 0

 39%|███▊      | 296/765 [01:37<02:35,  3.01it/s]

[296/765]  raw='pass'  → → 1

 39%|███▉      | 297/765 [01:37<02:31,  3.09it/s]

[297/765]  raw='pass'  → → 1

 39%|███▉      | 298/765 [01:37<02:28,  3.14it/s]

[298/765]  raw='pass'  → → 1

 39%|███▉      | 299/765 [01:38<02:47,  2.78it/s]

[299/765]  raw='pass'  → → 1

 39%|███▉      | 300/765 [01:38<02:39,  2.91it/s]

[300/765]  raw='fail'  → → 0

 39%|███▉      | 301/765 [01:38<02:34,  3.01it/s]

[301/765]  raw='fail'  → → 0

 39%|███▉      | 302/765 [01:39<02:29,  3.09it/s]

[302/765]  raw='pass'  → → 1

 40%|███▉      | 303/765 [01:39<02:56,  2.62it/s]

[303/765]  raw='pass'  → → 1

 40%|███▉      | 304/765 [01:39<02:46,  2.76it/s]

[304/765]  raw='fail'  → → 0

 40%|███▉      | 305/765 [01:40<02:39,  2.88it/s]

[305/765]  raw='fail'  → → 0

 40%|████      | 306/765 [01:40<02:34,  2.97it/s]

[306/765]  raw='fail'  → → 0

 40%|████      | 307/765 [01:40<02:30,  3.03it/s]

[307/765]  raw='fail'  → → 0

 40%|████      | 308/765 [01:41<02:29,  3.07it/s]

[308/765]  raw='fail'  → → 0

 40%|████      | 309/765 [01:41<02:27,  3.10it/s]

[309/765]  raw='pass'  → → 1

 41%|████      | 310/765 [01:41<02:25,  3.13it/s]

[310/765]  raw='fail'  → → 0

 41%|████      | 311/765 [01:42<02:23,  3.17it/s]

[311/765]  raw='fail'  → → 0

 41%|████      | 312/765 [01:42<02:21,  3.20it/s]

[312/765]  raw='fail'  → → 0

 41%|████      | 313/765 [01:42<02:23,  3.15it/s]

[313/765]  raw='fail'  → → 0

 41%|████      | 314/765 [01:43<02:29,  3.02it/s]

[314/765]  raw='pass'  → → 1

 41%|████      | 315/765 [01:43<02:25,  3.09it/s]

[315/765]  raw='fail'  → → 0

 41%|████▏     | 316/765 [01:43<02:22,  3.15it/s]

[316/765]  raw='fail'  → → 0

 41%|████▏     | 317/765 [01:44<02:20,  3.19it/s]

[317/765]  raw='fail'  → → 0

 42%|████▏     | 318/765 [01:44<02:18,  3.23it/s]

[318/765]  raw='fail'  → → 0

 42%|████▏     | 319/765 [01:44<02:17,  3.25it/s]

[319/765]  raw='fail'  → → 0

 42%|████▏     | 320/765 [01:44<02:15,  3.27it/s]

[320/765]  raw='fail'  → → 0

 42%|████▏     | 321/765 [01:45<02:15,  3.28it/s]

[321/765]  raw='fail'  → → 0

 42%|████▏     | 322/765 [01:45<02:14,  3.28it/s]

[322/765]  raw='fail'  → → 0

 42%|████▏     | 323/765 [01:45<02:14,  3.28it/s]

[323/765]  raw='pass'  → → 1

 42%|████▏     | 324/765 [01:46<02:14,  3.27it/s]

[324/765]  raw='pass'  → → 1

 42%|████▏     | 325/765 [01:46<02:14,  3.28it/s]

[325/765]  raw='fail'  → → 0

 43%|████▎     | 326/765 [01:46<02:29,  2.94it/s]

[326/765]  raw='pass'  → → 1

 43%|████▎     | 327/765 [01:47<02:24,  3.03it/s]

[327/765]  raw='fail'  → → 0

 43%|████▎     | 328/765 [01:47<02:21,  3.10it/s]

[328/765]  raw='fail'  → → 0

 43%|████▎     | 329/765 [01:47<02:18,  3.15it/s]

[329/765]  raw='fail'  → → 0

 43%|████▎     | 330/765 [01:48<02:16,  3.19it/s]

[330/765]  raw='pass'  → → 1

 43%|████▎     | 331/765 [01:48<02:15,  3.20it/s]

[331/765]  raw='fail'  → → 0

 43%|████▎     | 332/765 [01:48<02:14,  3.22it/s]

[332/765]  raw='fail'  → → 0

 44%|████▎     | 333/765 [01:49<02:13,  3.24it/s]

[333/765]  raw='fail'  → → 0

 44%|████▎     | 334/765 [01:49<02:12,  3.25it/s]

[334/765]  raw='pass'  → → 1

 44%|████▍     | 335/765 [01:49<02:11,  3.26it/s]

[335/765]  raw='fail'  → → 0

 44%|████▍     | 336/765 [01:49<02:11,  3.27it/s]

[336/765]  raw='fail'  → → 0

 44%|████▍     | 337/765 [01:50<02:10,  3.27it/s]

[337/765]  raw='pass'  → → 1

 44%|████▍     | 338/765 [01:50<02:10,  3.26it/s]

[338/765]  raw='fail'  → → 0

 44%|████▍     | 339/765 [01:50<02:24,  2.94it/s]

[339/765]  raw='pass'  → → 1

 44%|████▍     | 340/765 [01:51<02:20,  3.02it/s]

[340/765]  raw='pass'  → → 1

 45%|████▍     | 341/765 [01:51<02:17,  3.09it/s]

[341/765]  raw='pass'  → → 1

 45%|████▍     | 342/765 [01:51<02:15,  3.11it/s]

[342/765]  raw='pass'  → → 1

 45%|████▍     | 343/765 [01:52<02:21,  2.97it/s]

[343/765]  raw='pass'  → → 1

 45%|████▍     | 344/765 [01:52<02:18,  3.05it/s]

[344/765]  raw='pass'  → → 1

 45%|████▌     | 345/765 [01:52<02:15,  3.11it/s]

[345/765]  raw='pass'  → → 1

 45%|████▌     | 346/765 [01:53<02:27,  2.84it/s]

[346/765]  raw='pass'  → → 1

 45%|████▌     | 347/765 [01:53<02:23,  2.91it/s]

[347/765]  raw='fail'  → → 0

 45%|████▌     | 348/765 [01:53<02:19,  2.98it/s]

[348/765]  raw='fail'  → → 0

 46%|████▌     | 349/765 [01:54<02:16,  3.04it/s]

[349/765]  raw='fail'  → → 0

 46%|████▌     | 350/765 [01:54<02:14,  3.09it/s]

[350/765]  raw='fail'  → → 0

 46%|████▌     | 351/765 [01:54<02:11,  3.15it/s]

[351/765]  raw='fail'  → → 0

 46%|████▌     | 352/765 [01:55<02:09,  3.19it/s]

[352/765]  raw='pass'  → → 1

 46%|████▌     | 353/765 [01:55<02:08,  3.22it/s]

[353/765]  raw='fail'  → → 0

 46%|████▋     | 354/765 [01:55<02:07,  3.23it/s]

[354/765]  raw='fail'  → → 0

 46%|████▋     | 355/765 [01:56<02:06,  3.25it/s]

[355/765]  raw='pass'  → → 1

 47%|████▋     | 356/765 [01:56<02:06,  3.24it/s]

[356/765]  raw='fail'  → → 0

 47%|████▋     | 357/765 [01:56<02:05,  3.26it/s]

[357/765]  raw='fail'  → → 0

 47%|████▋     | 358/765 [01:57<02:04,  3.28it/s]

[358/765]  raw='pass'  → → 1

 47%|████▋     | 359/765 [01:57<02:10,  3.11it/s]

[359/765]  raw='pass'  → → 1

 47%|████▋     | 360/765 [01:57<02:07,  3.17it/s]

[360/765]  raw='fail'  → → 0

 47%|████▋     | 361/765 [01:57<02:05,  3.21it/s]

[361/765]  raw='fail'  → → 0

 47%|████▋     | 362/765 [01:58<02:16,  2.95it/s]

[362/765]  raw='pass'  → → 1

 47%|████▋     | 363/765 [01:58<02:12,  3.04it/s]

[363/765]  raw='fail'  → → 0

 48%|████▊     | 364/765 [01:58<02:08,  3.12it/s]

[364/765]  raw='pass'  → → 1

 48%|████▊     | 365/765 [01:59<02:19,  2.87it/s]

[365/765]  raw='fail'  → → 0

 48%|████▊     | 366/765 [01:59<02:13,  2.99it/s]

[366/765]  raw='fail'  → → 0

 48%|████▊     | 367/765 [01:59<02:09,  3.08it/s]

[367/765]  raw='pass'  → → 1

 48%|████▊     | 368/765 [02:00<02:06,  3.14it/s]

[368/765]  raw='fail'  → → 0

 48%|████▊     | 369/765 [02:00<02:04,  3.17it/s]

[369/765]  raw='pass'  → → 1

 48%|████▊     | 370/765 [02:00<02:11,  3.01it/s]

[370/765]  raw='pass'  → → 1

 48%|████▊     | 371/765 [02:01<02:07,  3.09it/s]

[371/765]  raw='pass'  → → 1

 49%|████▊     | 372/765 [02:01<02:04,  3.16it/s]

[372/765]  raw='fail'  → → 0

 49%|████▉     | 373/765 [02:01<02:15,  2.89it/s]

[373/765]  raw='pass'  → → 1

 49%|████▉     | 374/765 [02:02<02:09,  3.01it/s]

[374/765]  raw='pass'  → → 1

 49%|████▉     | 375/765 [02:02<02:05,  3.10it/s]

[375/765]  raw='pass'  → → 1

 49%|████▉     | 376/765 [02:02<02:02,  3.17it/s]

[376/765]  raw='fail'  → → 0

 49%|████▉     | 377/765 [02:03<02:00,  3.22it/s]

[377/765]  raw='fail'  → → 0

 49%|████▉     | 378/765 [02:03<02:13,  2.91it/s]

[378/765]  raw='pass'  → → 1

 50%|████▉     | 379/765 [02:03<02:07,  3.02it/s]

[379/765]  raw='fail'  → → 0

 50%|████▉     | 380/765 [02:04<02:04,  3.10it/s]

[380/765]  raw='fail'  → → 0

 50%|████▉     | 381/765 [02:04<02:10,  2.95it/s]

[381/765]  raw='pass'  → → 1

 50%|████▉     | 382/765 [02:04<02:07,  3.01it/s]

[382/765]  raw='fail'  → → 0

 50%|█████     | 383/765 [02:05<02:04,  3.07it/s]

[383/765]  raw='fail'  → → 0

 50%|█████     | 384/765 [02:05<02:01,  3.13it/s]

[384/765]  raw='fail'  → → 0

 50%|█████     | 385/765 [02:05<01:59,  3.17it/s]

[385/765]  raw='fail'  → → 0

 50%|█████     | 386/765 [02:06<01:59,  3.18it/s]

[386/765]  raw='pass'  → → 1

 51%|█████     | 387/765 [02:06<01:59,  3.18it/s]

[387/765]  raw='fail'  → → 0

 51%|█████     | 388/765 [02:06<01:58,  3.18it/s]

[388/765]  raw='pass'  → → 1

 51%|█████     | 389/765 [02:07<01:58,  3.18it/s]

[389/765]  raw='pass'  → → 1

 51%|█████     | 390/765 [02:07<01:57,  3.19it/s]

[390/765]  raw='pass'  → → 1

 51%|█████     | 391/765 [02:07<01:57,  3.19it/s]

[391/765]  raw='fail'  → → 0

 51%|█████     | 392/765 [02:08<01:56,  3.21it/s]

[392/765]  raw='fail'  → → 0

 51%|█████▏    | 393/765 [02:08<01:55,  3.22it/s]

[393/765]  raw='pass'  → → 1

 52%|█████▏    | 394/765 [02:08<02:26,  2.52it/s]

[394/765]  raw='pass'  → → 1

 52%|█████▏    | 395/765 [02:09<02:16,  2.71it/s]

[395/765]  raw='pass'  → → 1

 52%|█████▏    | 396/765 [02:09<02:09,  2.86it/s]

[396/765]  raw='fail'  → → 0

 52%|█████▏    | 397/765 [02:09<02:04,  2.96it/s]

[397/765]  raw='pass'  → → 1

 52%|█████▏    | 398/765 [02:10<01:59,  3.07it/s]

[398/765]  raw='fail'  → → 0

 52%|█████▏    | 399/765 [02:10<01:56,  3.13it/s]

[399/765]  raw='fail'  → → 0

 52%|█████▏    | 400/765 [02:10<01:55,  3.16it/s]

[400/765]  raw='pass'  → → 1

 52%|█████▏    | 401/765 [02:11<01:53,  3.20it/s]

[401/765]  raw='fail'  → → 0

 53%|█████▎    | 402/765 [02:11<01:58,  3.06it/s]

[402/765]  raw='fail'  → → 0

 53%|█████▎    | 403/765 [02:11<01:55,  3.12it/s]

[403/765]  raw='fail'  → → 0

 53%|█████▎    | 404/765 [02:12<01:53,  3.17it/s]

[404/765]  raw='fail'  → → 0

 53%|█████▎    | 405/765 [02:12<01:52,  3.20it/s]

[405/765]  raw='fail'  → → 0

 53%|█████▎    | 406/765 [02:12<01:51,  3.22it/s]

[406/765]  raw='pass'  → → 1

 53%|█████▎    | 407/765 [02:13<02:03,  2.91it/s]

[407/765]  raw='pass'  → → 1

 53%|█████▎    | 408/765 [02:13<01:58,  3.01it/s]

[408/765]  raw='fail'  → → 0

 53%|█████▎    | 409/765 [02:13<01:55,  3.09it/s]

[409/765]  raw='pass'  → → 1

 54%|█████▎    | 410/765 [02:13<01:52,  3.15it/s]

[410/765]  raw='fail'  → → 0

 54%|█████▎    | 411/765 [02:14<01:50,  3.20it/s]

[411/765]  raw='fail'  → → 0

 54%|█████▍    | 412/765 [02:14<02:00,  2.93it/s]

[412/765]  raw='pass'  → → 1

 54%|█████▍    | 413/765 [02:14<01:57,  3.00it/s]

[413/765]  raw='fail'  → → 0

 54%|█████▍    | 414/765 [02:15<01:59,  2.94it/s]

[414/765]  raw='pass'  → → 1

 54%|█████▍    | 415/765 [02:15<01:55,  3.04it/s]

[415/765]  raw='fail'  → → 0

 54%|█████▍    | 416/765 [02:15<01:52,  3.10it/s]

[416/765]  raw='fail'  → → 0

 55%|█████▍    | 417/765 [02:16<01:50,  3.16it/s]

[417/765]  raw='fail'  → → 0

 55%|█████▍    | 418/765 [02:16<01:48,  3.19it/s]

[418/765]  raw='fail'  → → 0

 55%|█████▍    | 419/765 [02:16<01:47,  3.22it/s]

[419/765]  raw='fail'  → → 0

 55%|█████▍    | 420/765 [02:17<01:46,  3.24it/s]

[420/765]  raw='fail'  → → 0

 55%|█████▌    | 421/765 [02:17<01:46,  3.24it/s]

[421/765]  raw='fail'  → → 0

 55%|█████▌    | 422/765 [02:17<02:00,  2.85it/s]

[422/765]  raw='pass'  → → 1

 55%|█████▌    | 423/765 [02:18<02:00,  2.83it/s]

[423/765]  raw='pass'  → → 1

 55%|█████▌    | 424/765 [02:18<01:56,  2.92it/s]

[424/765]  raw='fail'  → → 0

 56%|█████▌    | 425/765 [02:18<01:53,  3.00it/s]

[425/765]  raw='fail'  → → 0

 56%|█████▌    | 426/765 [02:19<01:55,  2.93it/s]

[426/765]  raw='pass'  → → 1

 56%|█████▌    | 427/765 [02:19<02:20,  2.40it/s]

[427/765]  raw='pass'  → → 1

 56%|█████▌    | 428/765 [02:20<02:09,  2.59it/s]

[428/765]  raw='fail'  → → 0

 56%|█████▌    | 429/765 [02:20<02:02,  2.75it/s]

[429/765]  raw='fail'  → → 0

 56%|█████▌    | 430/765 [02:20<01:57,  2.84it/s]

[430/765]  raw='pass'  → → 1

 56%|█████▋    | 431/765 [02:21<01:53,  2.94it/s]

[431/765]  raw='pass'  → → 1

 56%|█████▋    | 432/765 [02:21<01:49,  3.03it/s]

[432/765]  raw='fail'  → → 0

 57%|█████▋    | 433/765 [02:21<01:47,  3.10it/s]

[433/765]  raw='pass'  → → 1

 57%|█████▋    | 434/765 [02:22<01:44,  3.15it/s]

[434/765]  raw='fail'  → → 0

 57%|█████▋    | 435/765 [02:22<01:43,  3.19it/s]

[435/765]  raw='fail'  → → 0

 57%|█████▋    | 436/765 [02:22<01:42,  3.22it/s]

[436/765]  raw='fail'  → → 0

 57%|█████▋    | 437/765 [02:22<01:41,  3.24it/s]

[437/765]  raw='fail'  → → 0

 57%|█████▋    | 438/765 [02:23<01:40,  3.27it/s]

[438/765]  raw='fail'  → → 0

 57%|█████▋    | 439/765 [02:23<01:39,  3.29it/s]

[439/765]  raw='fail'  → → 0

 58%|█████▊    | 440/765 [02:23<01:39,  3.28it/s]

[440/765]  raw='fail'  → → 0

 58%|█████▊    | 441/765 [02:24<01:38,  3.28it/s]

[441/765]  raw='pass'  → → 1

 58%|█████▊    | 442/765 [02:24<01:38,  3.29it/s]

[442/765]  raw='fail'  → → 0

 58%|█████▊    | 443/765 [02:24<01:37,  3.29it/s]

[443/765]  raw='fail'  → → 0

 58%|█████▊    | 444/765 [02:25<01:37,  3.29it/s]

[444/765]  raw='fail'  → → 0

 58%|█████▊    | 445/765 [02:25<01:37,  3.29it/s]

[445/765]  raw='fail'  → → 0

 58%|█████▊    | 446/765 [02:25<01:37,  3.27it/s]

[446/765]  raw='fail'  → → 0

 58%|█████▊    | 447/765 [02:26<01:36,  3.28it/s]

[447/765]  raw='pass'  → → 1

 59%|█████▊    | 448/765 [02:26<01:36,  3.27it/s]

[448/765]  raw='fail'  → → 0

 59%|█████▊    | 449/765 [02:26<01:36,  3.28it/s]

[449/765]  raw='fail'  → → 0

 59%|█████▉    | 450/765 [02:26<01:36,  3.27it/s]

[450/765]  raw='pass'  → → 1

 59%|█████▉    | 451/765 [02:27<01:36,  3.26it/s]

[451/765]  raw='fail'  → → 0

 59%|█████▉    | 452/765 [02:27<01:36,  3.25it/s]

[452/765]  raw='fail'  → → 0

 59%|█████▉    | 453/765 [02:27<01:35,  3.26it/s]

[453/765]  raw='fail'  → → 0

 59%|█████▉    | 454/765 [02:28<01:35,  3.25it/s]

[454/765]  raw='fail'  → → 0

 59%|█████▉    | 455/765 [02:28<01:35,  3.23it/s]

[455/765]  raw='pass'  → → 1

 60%|█████▉    | 456/765 [02:28<01:35,  3.24it/s]

[456/765]  raw='fail'  → → 0

 60%|█████▉    | 457/765 [02:29<01:34,  3.25it/s]

[457/765]  raw='fail'  → → 0

 60%|█████▉    | 458/765 [02:29<01:34,  3.23it/s]

[458/765]  raw='fail'  → → 0

 60%|██████    | 459/765 [02:29<01:34,  3.23it/s]

[459/765]  raw='fail'  → → 0

 60%|██████    | 460/765 [02:30<01:34,  3.24it/s]

[460/765]  raw='fail'  → → 0

 60%|██████    | 461/765 [02:30<01:34,  3.21it/s]

[461/765]  raw='pass'  → → 1

 60%|██████    | 462/765 [02:30<01:38,  3.06it/s]

[462/765]  raw='pass'  → → 1

 61%|██████    | 463/765 [02:31<01:37,  3.11it/s]

[463/765]  raw='fail'  → → 0

 61%|██████    | 464/765 [02:31<01:35,  3.14it/s]

[464/765]  raw='fail'  → → 0

 61%|██████    | 465/765 [02:31<01:34,  3.18it/s]

[465/765]  raw='pass'  → → 1

 61%|██████    | 466/765 [02:31<01:33,  3.20it/s]

[466/765]  raw='fail'  → → 0

 61%|██████    | 467/765 [02:32<01:32,  3.23it/s]

[467/765]  raw='pass'  → → 1

 61%|██████    | 468/765 [02:32<01:31,  3.24it/s]

[468/765]  raw='pass'  → → 1

 61%|██████▏   | 469/765 [02:32<01:30,  3.26it/s]

[469/765]  raw='fail'  → → 0

 61%|██████▏   | 470/765 [02:33<01:39,  2.96it/s]

[470/765]  raw='pass'  → → 1

 62%|██████▏   | 471/765 [02:33<01:36,  3.05it/s]

[471/765]  raw='fail'  → → 0

 62%|██████▏   | 472/765 [02:33<01:34,  3.11it/s]

[472/765]  raw='fail'  → → 0

 62%|██████▏   | 473/765 [02:34<01:32,  3.17it/s]

[473/765]  raw='fail'  → → 0

 62%|██████▏   | 474/765 [02:34<01:31,  3.20it/s]

[474/765]  raw='fail'  → → 0

 62%|██████▏   | 475/765 [02:34<01:30,  3.22it/s]

[475/765]  raw='pass'  → → 1

 62%|██████▏   | 476/765 [02:35<01:29,  3.24it/s]

[476/765]  raw='fail'  → → 0

 62%|██████▏   | 477/765 [02:35<01:28,  3.25it/s]

[477/765]  raw='fail'  → → 0

 62%|██████▏   | 478/765 [02:35<01:27,  3.27it/s]

[478/765]  raw='fail'  → → 0

 63%|██████▎   | 479/765 [02:35<01:27,  3.28it/s]

[479/765]  raw='fail'  → → 0

 63%|██████▎   | 480/765 [02:36<01:26,  3.30it/s]

[480/765]  raw='pass'  → → 1

 63%|██████▎   | 481/765 [02:36<01:26,  3.28it/s]

[481/765]  raw='fail'  → → 0

 63%|██████▎   | 482/765 [02:36<01:26,  3.28it/s]

[482/765]  raw='fail'  → → 0

 63%|██████▎   | 483/765 [02:37<01:25,  3.29it/s]

[483/765]  raw='fail'  → → 0

 63%|██████▎   | 484/765 [02:37<01:25,  3.28it/s]

[484/765]  raw='fail'  → → 0

 63%|██████▎   | 485/765 [02:37<01:25,  3.29it/s]

[485/765]  raw='pass'  → → 1

 64%|██████▎   | 486/765 [02:38<01:29,  3.11it/s]

[486/765]  raw='pass'  → → 1

 64%|██████▎   | 487/765 [02:38<01:28,  3.16it/s]

[487/765]  raw='fail'  → → 0

 64%|██████▍   | 488/765 [02:38<01:27,  3.18it/s]

[488/765]  raw='pass'  → → 1

 64%|██████▍   | 489/765 [02:39<01:26,  3.21it/s]

[489/765]  raw='fail'  → → 0

 64%|██████▍   | 490/765 [02:39<01:25,  3.21it/s]

[490/765]  raw='pass'  → → 1

 64%|██████▍   | 491/765 [02:39<01:24,  3.23it/s]

[491/765]  raw='pass'  → → 1

 64%|██████▍   | 492/765 [02:40<01:24,  3.24it/s]

[492/765]  raw='pass'  → → 1

 64%|██████▍   | 493/765 [02:40<01:23,  3.25it/s]

[493/765]  raw='fail'  → → 0

 65%|██████▍   | 494/765 [02:40<01:24,  3.22it/s]

[494/765]  raw='pass'  → → 1

 65%|██████▍   | 495/765 [02:40<01:23,  3.25it/s]

[495/765]  raw='fail'  → → 0

 65%|██████▍   | 496/765 [02:41<01:22,  3.27it/s]

[496/765]  raw='fail'  → → 0

 65%|██████▍   | 497/765 [02:41<01:21,  3.27it/s]

[497/765]  raw='fail'  → → 0

 65%|██████▌   | 498/765 [02:41<01:22,  3.25it/s]

[498/765]  raw='fail'  → → 0

 65%|██████▌   | 499/765 [02:42<01:21,  3.26it/s]

[499/765]  raw='pass'  → → 1

 65%|██████▌   | 500/765 [02:42<01:21,  3.27it/s]

[500/765]  raw='fail'  → → 0

 65%|██████▌   | 501/765 [02:42<01:21,  3.25it/s]

[501/765]  raw='fail'  → → 0

 66%|██████▌   | 502/765 [02:43<01:20,  3.25it/s]

[502/765]  raw='fail'  → → 0

 66%|██████▌   | 503/765 [02:43<01:20,  3.26it/s]

[503/765]  raw='pass'  → → 1

 66%|██████▌   | 504/765 [02:43<01:20,  3.25it/s]

[504/765]  raw='fail'  → → 0

 66%|██████▌   | 505/765 [02:44<01:19,  3.25it/s]

[505/765]  raw='fail'  → → 0

 66%|██████▌   | 506/765 [02:44<01:19,  3.26it/s]

[506/765]  raw='fail'  → → 0

 66%|██████▋   | 507/765 [02:44<01:19,  3.25it/s]

[507/765]  raw='fail'  → → 0

 66%|██████▋   | 508/765 [02:44<01:19,  3.22it/s]

[508/765]  raw='pass'  → → 1

 67%|██████▋   | 509/765 [02:45<01:22,  3.09it/s]

[509/765]  raw='pass'  → → 1

 67%|██████▋   | 510/765 [02:45<01:21,  3.13it/s]

[510/765]  raw='fail'  → → 0

 67%|██████▋   | 511/765 [02:46<01:28,  2.87it/s]

[511/765]  raw='pass'  → → 1

 67%|██████▋   | 512/765 [02:46<01:25,  2.97it/s]

[512/765]  raw='pass'  → → 1

 67%|██████▋   | 513/765 [02:46<01:22,  3.07it/s]

[513/765]  raw='fail'  → → 0

 67%|██████▋   | 514/765 [02:46<01:19,  3.14it/s]

[514/765]  raw='fail'  → → 0

 67%|██████▋   | 515/765 [02:47<01:18,  3.19it/s]

[515/765]  raw='pass'  → → 1

 67%|██████▋   | 516/765 [02:47<01:26,  2.88it/s]

[516/765]  raw='pass'  → → 1

 68%|██████▊   | 517/765 [02:47<01:23,  2.99it/s]

[517/765]  raw='fail'  → → 0

 68%|██████▊   | 518/765 [02:48<01:21,  3.04it/s]

[518/765]  raw='pass'  → → 1

 68%|██████▊   | 519/765 [02:48<01:19,  3.11it/s]

[519/765]  raw='fail'  → → 0

 68%|██████▊   | 520/765 [02:48<01:17,  3.15it/s]

[520/765]  raw='pass'  → → 1

 68%|██████▊   | 521/765 [02:49<01:20,  3.05it/s]

[521/765]  raw='fail'  → → 0

 68%|██████▊   | 522/765 [02:49<01:17,  3.12it/s]

[522/765]  raw='fail'  → → 0

 68%|██████▊   | 523/765 [02:49<01:16,  3.15it/s]

[523/765]  raw='fail'  → → 0

 68%|██████▊   | 524/765 [02:50<01:15,  3.19it/s]

[524/765]  raw='fail'  → → 0

 69%|██████▊   | 525/765 [02:50<01:23,  2.87it/s]

[525/765]  raw='pass'  → → 1

 69%|██████▉   | 526/765 [02:50<01:20,  2.98it/s]

[526/765]  raw='fail'  → → 0

 69%|██████▉   | 527/765 [02:51<01:17,  3.06it/s]

[527/765]  raw='fail'  → → 0

 69%|██████▉   | 528/765 [02:51<01:15,  3.13it/s]

[528/765]  raw='pass'  → → 1

 69%|██████▉   | 529/765 [02:51<01:14,  3.19it/s]

[529/765]  raw='fail'  → → 0

 69%|██████▉   | 530/765 [02:52<01:12,  3.22it/s]

[530/765]  raw='fail'  → → 0

 69%|██████▉   | 531/765 [02:52<01:12,  3.24it/s]

[531/765]  raw='fail'  → → 0

 70%|██████▉   | 532/765 [02:52<01:11,  3.27it/s]

[532/765]  raw='fail'  → → 0

 70%|██████▉   | 533/765 [02:53<01:10,  3.29it/s]

[533/765]  raw='pass'  → → 1

 70%|██████▉   | 534/765 [02:53<01:10,  3.29it/s]

[534/765]  raw='pass'  → → 1

 70%|██████▉   | 535/765 [02:53<01:09,  3.29it/s]

[535/765]  raw='pass'  → → 1

 70%|███████   | 536/765 [02:53<01:09,  3.29it/s]

[536/765]  raw='fail'  → → 0

 70%|███████   | 537/765 [02:54<01:09,  3.29it/s]

[537/765]  raw='fail'  → → 0

 70%|███████   | 538/765 [02:54<01:08,  3.30it/s]

[538/765]  raw='fail'  → → 0

 70%|███████   | 539/765 [02:54<01:08,  3.30it/s]

[539/765]  raw='fail'  → → 0

 71%|███████   | 540/765 [02:55<01:08,  3.30it/s]

[540/765]  raw='pass'  → → 1

 71%|███████   | 541/765 [02:55<01:07,  3.30it/s]

[541/765]  raw='fail'  → → 0

 71%|███████   | 542/765 [02:55<01:07,  3.28it/s]

[542/765]  raw='fail'  → → 0

 71%|███████   | 543/765 [02:56<01:12,  3.08it/s]

[543/765]  raw='pass'  → → 1

 71%|███████   | 544/765 [02:56<01:10,  3.14it/s]

[544/765]  raw='fail'  → → 0

 71%|███████   | 545/765 [02:56<01:09,  3.17it/s]

[545/765]  raw='fail'  → → 0

 71%|███████▏  | 546/765 [02:57<01:08,  3.20it/s]

[546/765]  raw='fail'  → → 0

 72%|███████▏  | 547/765 [02:57<01:07,  3.23it/s]

[547/765]  raw='fail'  → → 0

 72%|███████▏  | 548/765 [02:57<01:15,  2.89it/s]

[548/765]  raw='pass'  → → 1

 72%|███████▏  | 549/765 [02:58<01:12,  2.99it/s]

[549/765]  raw='pass'  → → 1

 72%|███████▏  | 550/765 [02:58<01:09,  3.07it/s]

[550/765]  raw='pass'  → → 1

 72%|███████▏  | 551/765 [02:58<01:08,  3.14it/s]

[551/765]  raw='fail'  → → 0

 72%|███████▏  | 552/765 [02:58<01:06,  3.18it/s]

[552/765]  raw='fail'  → → 0

 72%|███████▏  | 553/765 [02:59<01:06,  3.21it/s]

[553/765]  raw='pass'  → → 1

 72%|███████▏  | 554/765 [02:59<01:05,  3.23it/s]

[554/765]  raw='pass'  → → 1

 73%|███████▎  | 555/765 [02:59<01:04,  3.24it/s]

[555/765]  raw='fail'  → → 0

 73%|███████▎  | 556/765 [03:00<01:07,  3.10it/s]

[556/765]  raw='pass'  → → 1

 73%|███████▎  | 557/765 [03:00<01:06,  3.13it/s]

[557/765]  raw='pass'  → → 1

 73%|███████▎  | 558/765 [03:00<01:05,  3.18it/s]

[558/765]  raw='fail'  → → 0

 73%|███████▎  | 559/765 [03:01<01:04,  3.21it/s]

[559/765]  raw='fail'  → → 0

 73%|███████▎  | 560/765 [03:01<01:02,  3.26it/s]

[560/765]  raw='fail'  → → 0

 73%|███████▎  | 561/765 [03:01<01:06,  3.05it/s]

[561/765]  raw='pass'  → → 1

 73%|███████▎  | 562/765 [03:02<01:05,  3.11it/s]

[562/765]  raw='fail'  → → 0

 74%|███████▎  | 563/765 [03:02<01:03,  3.18it/s]

[563/765]  raw='fail'  → → 0

 74%|███████▎  | 564/765 [03:02<01:02,  3.24it/s]

[564/765]  raw='fail'  → → 0

 74%|███████▍  | 565/765 [03:03<01:04,  3.11it/s]

[565/765]  raw='pass'  → → 1

 74%|███████▍  | 566/765 [03:03<01:02,  3.19it/s]

[566/765]  raw='pass'  → → 1

 74%|███████▍  | 567/765 [03:03<01:01,  3.23it/s]

[567/765]  raw='pass'  → → 1

 74%|███████▍  | 568/765 [03:04<01:05,  3.02it/s]

[568/765]  raw='pass'  → → 1

 74%|███████▍  | 569/765 [03:04<01:03,  3.10it/s]

[569/765]  raw='fail'  → → 0

 75%|███████▍  | 570/765 [03:04<01:01,  3.16it/s]

[570/765]  raw='pass'  → → 1

 75%|███████▍  | 571/765 [03:05<01:01,  3.17it/s]

[571/765]  raw='fail'  → → 0

 75%|███████▍  | 572/765 [03:05<01:00,  3.21it/s]

[572/765]  raw='pass'  → → 1

 75%|███████▍  | 573/765 [03:05<00:59,  3.25it/s]

[573/765]  raw='pass'  → → 1

 75%|███████▌  | 574/765 [03:05<01:01,  3.11it/s]

[574/765]  raw='pass'  → → 1

 75%|███████▌  | 575/765 [03:06<00:59,  3.18it/s]

[575/765]  raw='pass'  → → 1

 75%|███████▌  | 576/765 [03:06<00:58,  3.21it/s]

[576/765]  raw='pass'  → → 1

 75%|███████▌  | 577/765 [03:06<00:58,  3.23it/s]

[577/765]  raw='fail'  → → 0

 76%|███████▌  | 578/765 [03:07<00:57,  3.24it/s]

[578/765]  raw='fail'  → → 0

 76%|███████▌  | 579/765 [03:07<00:57,  3.25it/s]

[579/765]  raw='fail'  → → 0

 76%|███████▌  | 580/765 [03:07<00:56,  3.25it/s]

[580/765]  raw='pass'  → → 1

 76%|███████▌  | 581/765 [03:08<00:56,  3.25it/s]

[581/765]  raw='fail'  → → 0

 76%|███████▌  | 582/765 [03:08<00:56,  3.24it/s]

[582/765]  raw='fail'  → → 0

 76%|███████▌  | 583/765 [03:08<00:56,  3.24it/s]

[583/765]  raw='fail'  → → 0

 76%|███████▋  | 584/765 [03:09<00:58,  3.09it/s]

[584/765]  raw='pass'  → → 1

 76%|███████▋  | 585/765 [03:09<01:00,  2.98it/s]

[585/765]  raw='pass'  → → 1

 77%|███████▋  | 586/765 [03:09<00:58,  3.06it/s]

[586/765]  raw='pass'  → → 1

 77%|███████▋  | 587/765 [03:10<00:56,  3.13it/s]

[587/765]  raw='fail'  → → 0

 77%|███████▋  | 588/765 [03:10<00:55,  3.16it/s]

[588/765]  raw='fail'  → → 0

 77%|███████▋  | 589/765 [03:10<00:55,  3.18it/s]

[589/765]  raw='fail'  → → 0

 77%|███████▋  | 590/765 [03:10<00:54,  3.21it/s]

[590/765]  raw='fail'  → → 0

 77%|███████▋  | 591/765 [03:11<00:54,  3.21it/s]

[591/765]  raw='fail'  → → 0

 77%|███████▋  | 592/765 [03:11<00:53,  3.23it/s]

[592/765]  raw='fail'  → → 0

 78%|███████▊  | 593/765 [03:11<00:52,  3.25it/s]

[593/765]  raw='fail'  → → 0

 78%|███████▊  | 594/765 [03:12<00:52,  3.27it/s]

[594/765]  raw='fail'  → → 0

 78%|███████▊  | 595/765 [03:12<00:53,  3.18it/s]

[595/765]  raw='pass'  → → 1

 78%|███████▊  | 596/765 [03:13<01:03,  2.64it/s]

[596/765]  raw='fail'  → → 0

 78%|███████▊  | 597/765 [03:13<01:02,  2.70it/s]

[597/765]  raw='pass'  → → 1

 78%|███████▊  | 598/765 [03:13<00:58,  2.85it/s]

[598/765]  raw='pass'  → → 1

 78%|███████▊  | 599/765 [03:14<00:55,  2.97it/s]

[599/765]  raw='pass'  → → 1

 78%|███████▊  | 600/765 [03:14<00:54,  3.06it/s]

[600/765]  raw='fail'  → → 0

 79%|███████▊  | 601/765 [03:14<00:52,  3.10it/s]

[601/765]  raw='fail'  → → 0

 79%|███████▊  | 602/765 [03:14<00:54,  3.01it/s]

[602/765]  raw='pass'  → → 1

 79%|███████▉  | 603/765 [03:15<00:55,  2.91it/s]

[603/765]  raw='pass'  → → 1

 79%|███████▉  | 604/765 [03:15<00:53,  3.00it/s]

[604/765]  raw='pass'  → → 1

 79%|███████▉  | 605/765 [03:15<00:52,  3.07it/s]

[605/765]  raw='pass'  → → 1

 79%|███████▉  | 606/765 [03:16<00:50,  3.13it/s]

[606/765]  raw='fail'  → → 0

 79%|███████▉  | 607/765 [03:16<00:49,  3.17it/s]

[607/765]  raw='fail'  → → 0

 79%|███████▉  | 608/765 [03:17<00:54,  2.90it/s]

[608/765]  raw='pass'  → → 1

 80%|███████▉  | 609/765 [03:17<00:51,  3.00it/s]

[609/765]  raw='pass'  → → 1

 80%|███████▉  | 610/765 [03:17<00:50,  3.07it/s]

[610/765]  raw='pass'  → → 1

 80%|███████▉  | 611/765 [03:17<00:51,  3.00it/s]

[611/765]  raw='pass'  → → 1

 80%|████████  | 612/765 [03:18<00:49,  3.07it/s]

[612/765]  raw='fail'  → → 0

 80%|████████  | 613/765 [03:18<00:48,  3.12it/s]

[613/765]  raw='pass'  → → 1

 80%|████████  | 614/765 [03:18<00:47,  3.16it/s]

[614/765]  raw='fail'  → → 0

 80%|████████  | 615/765 [03:19<00:47,  3.18it/s]

[615/765]  raw='fail'  → → 0

 81%|████████  | 616/765 [03:19<00:46,  3.19it/s]

[616/765]  raw='fail'  → → 0

 81%|████████  | 617/765 [03:19<00:46,  3.21it/s]

[617/765]  raw='fail'  → → 0

 81%|████████  | 618/765 [03:20<00:45,  3.21it/s]

[618/765]  raw='pass'  → → 1

 81%|████████  | 619/765 [03:20<00:45,  3.22it/s]

[619/765]  raw='fail'  → → 0

 81%|████████  | 620/765 [03:20<00:45,  3.21it/s]

[620/765]  raw='pass'  → → 1

 81%|████████  | 621/765 [03:21<00:50,  2.83it/s]

[621/765]  raw='pass'  → → 1

 81%|████████▏ | 622/765 [03:21<00:51,  2.78it/s]

[622/765]  raw='fail'  → → 0

 81%|████████▏ | 623/765 [03:21<00:48,  2.90it/s]

[623/765]  raw='pass'  → → 1

 82%|████████▏ | 624/765 [03:22<00:47,  3.00it/s]

[624/765]  raw='pass'  → → 1

 82%|████████▏ | 625/765 [03:22<00:45,  3.05it/s]

[625/765]  raw='fail'  → → 0

 82%|████████▏ | 626/765 [03:22<00:44,  3.11it/s]

[626/765]  raw='fail'  → → 0

 82%|████████▏ | 627/765 [03:23<00:43,  3.14it/s]

[627/765]  raw='pass'  → → 1

 82%|████████▏ | 628/765 [03:23<00:43,  3.15it/s]

[628/765]  raw='pass'  → → 1

 82%|████████▏ | 629/765 [03:23<00:43,  3.16it/s]

[629/765]  raw='fail'  → → 0

 82%|████████▏ | 630/765 [03:24<00:46,  2.88it/s]

[630/765]  raw='pass'  → → 1

 82%|████████▏ | 631/765 [03:24<00:58,  2.28it/s]

[631/765]  raw='pass'  → → 1

 83%|████████▎ | 632/765 [03:25<00:53,  2.50it/s]

[632/765]  raw='fail'  → → 0

 83%|████████▎ | 633/765 [03:25<00:53,  2.49it/s]

[633/765]  raw='pass'  → → 1

 83%|████████▎ | 634/765 [03:25<00:48,  2.68it/s]

[634/765]  raw='pass'  → → 1

 83%|████████▎ | 635/765 [03:26<00:46,  2.82it/s]

[635/765]  raw='pass'  → → 1

 83%|████████▎ | 636/765 [03:26<00:45,  2.82it/s]

[636/765]  raw='pass'  → → 1

 83%|████████▎ | 637/765 [03:26<00:45,  2.81it/s]

[637/765]  raw='pass'  → → 1

 83%|████████▎ | 638/765 [03:27<00:43,  2.89it/s]

[638/765]  raw='fail'  → → 0

 84%|████████▎ | 639/765 [03:27<00:42,  2.98it/s]

[639/765]  raw='fail'  → → 0

 84%|████████▎ | 640/765 [03:27<00:40,  3.05it/s]

[640/765]  raw='fail'  → → 0

 84%|████████▍ | 641/765 [03:28<00:39,  3.10it/s]

[641/765]  raw='fail'  → → 0

 84%|████████▍ | 642/765 [03:28<00:44,  2.75it/s]

[642/765]  raw='pass'  → → 1

 84%|████████▍ | 643/765 [03:28<00:42,  2.88it/s]

[643/765]  raw='fail'  → → 0

 84%|████████▍ | 644/765 [03:29<00:40,  2.99it/s]

[644/765]  raw='fail'  → → 0

 84%|████████▍ | 645/765 [03:29<00:38,  3.08it/s]

[645/765]  raw='fail'  → → 0

 84%|████████▍ | 646/765 [03:29<00:40,  2.95it/s]

[646/765]  raw='pass'  → → 1

 85%|████████▍ | 647/765 [03:30<00:43,  2.74it/s]

[647/765]  raw='pass'  → → 1

 85%|████████▍ | 648/765 [03:30<00:40,  2.87it/s]

[648/765]  raw='pass'  → → 1

 85%|████████▍ | 649/765 [03:30<00:39,  2.97it/s]

[649/765]  raw='fail'  → → 0

 85%|████████▍ | 650/765 [03:31<00:37,  3.06it/s]

[650/765]  raw='pass'  → → 1

 85%|████████▌ | 651/765 [03:31<00:36,  3.14it/s]

[651/765]  raw='fail'  → → 0

 85%|████████▌ | 652/765 [03:31<00:35,  3.21it/s]

[652/765]  raw='fail'  → → 0

 85%|████████▌ | 653/765 [03:32<00:34,  3.25it/s]

[653/765]  raw='pass'  → → 1

 85%|████████▌ | 654/765 [03:32<00:33,  3.29it/s]

[654/765]  raw='fail'  → → 0

 86%|████████▌ | 655/765 [03:32<00:33,  3.30it/s]

[655/765]  raw='fail'  → → 0

 86%|████████▌ | 656/765 [03:33<00:32,  3.31it/s]

[656/765]  raw='fail'  → → 0

 86%|████████▌ | 657/765 [03:33<00:32,  3.30it/s]

[657/765]  raw='fail'  → → 0

 86%|████████▌ | 658/765 [03:33<00:32,  3.29it/s]

[658/765]  raw='fail'  → → 0

 86%|████████▌ | 659/765 [03:33<00:32,  3.27it/s]

[659/765]  raw='fail'  → → 0

 86%|████████▋ | 660/765 [03:34<00:32,  3.26it/s]

[660/765]  raw='fail'  → → 0

 86%|████████▋ | 661/765 [03:34<00:35,  2.90it/s]

[661/765]  raw='pass'  → → 1

 87%|████████▋ | 662/765 [03:34<00:34,  2.97it/s]

[662/765]  raw='pass'  → → 1

 87%|████████▋ | 663/765 [03:35<00:33,  3.05it/s]

[663/765]  raw='fail'  → → 0

 87%|████████▋ | 664/765 [03:35<00:32,  3.12it/s]

[664/765]  raw='pass'  → → 1

 87%|████████▋ | 665/765 [03:35<00:31,  3.17it/s]

[665/765]  raw='fail'  → → 0

 87%|████████▋ | 666/765 [03:36<00:32,  3.05it/s]

[666/765]  raw='pass'  → → 1

 87%|████████▋ | 667/765 [03:36<00:31,  3.13it/s]

[667/765]  raw='fail'  → → 0

 87%|████████▋ | 668/765 [03:36<00:30,  3.17it/s]

[668/765]  raw='pass'  → → 1

 87%|████████▋ | 669/765 [03:37<00:31,  3.05it/s]

[669/765]  raw='pass'  → → 1

 88%|████████▊ | 670/765 [03:37<00:30,  3.09it/s]

[670/765]  raw='pass'  → → 1

 88%|████████▊ | 671/765 [03:37<00:33,  2.80it/s]

[671/765]  raw='pass'  → → 1

 88%|████████▊ | 672/765 [03:38<00:31,  2.91it/s]

[672/765]  raw='pass'  → → 1

 88%|████████▊ | 673/765 [03:38<00:30,  3.02it/s]

[673/765]  raw='fail'  → → 0

 88%|████████▊ | 674/765 [03:39<00:32,  2.81it/s]

[674/765]  raw='pass'  → → 1

 88%|████████▊ | 675/765 [03:39<00:30,  2.94it/s]

[675/765]  raw='fail'  → → 0

 88%|████████▊ | 676/765 [03:39<00:29,  3.05it/s]

[676/765]  raw='fail'  → → 0

 88%|████████▊ | 677/765 [03:39<00:28,  3.12it/s]

[677/765]  raw='fail'  → → 0

 89%|████████▊ | 678/765 [03:40<00:27,  3.18it/s]

[678/765]  raw='fail'  → → 0

 89%|████████▉ | 679/765 [03:40<00:26,  3.21it/s]

[679/765]  raw='pass'  → → 1

 89%|████████▉ | 680/765 [03:40<00:26,  3.25it/s]

[680/765]  raw='pass'  → → 1

 89%|████████▉ | 681/765 [03:41<00:25,  3.26it/s]

[681/765]  raw='pass'  → → 1

 89%|████████▉ | 682/765 [03:41<00:25,  3.25it/s]

[682/765]  raw='pass'  → → 1

 89%|████████▉ | 683/765 [03:41<00:25,  3.25it/s]

[683/765]  raw='pass'  → → 1

 89%|████████▉ | 684/765 [03:42<00:24,  3.27it/s]

[684/765]  raw='pass'  → → 1

 90%|████████▉ | 685/765 [03:42<00:24,  3.27it/s]

[685/765]  raw='pass'  → → 1

 90%|████████▉ | 686/765 [03:42<00:24,  3.27it/s]

[686/765]  raw='fail'  → → 0

 90%|████████▉ | 687/765 [03:42<00:24,  3.24it/s]

[687/765]  raw='pass'  → → 1

 90%|████████▉ | 688/765 [03:43<00:23,  3.27it/s]

[688/765]  raw='fail'  → → 0

 90%|█████████ | 689/765 [03:43<00:23,  3.27it/s]

[689/765]  raw='pass'  → → 1

 90%|█████████ | 690/765 [03:43<00:22,  3.27it/s]

[690/765]  raw='fail'  → → 0

 90%|█████████ | 691/765 [03:44<00:22,  3.28it/s]

[691/765]  raw='fail'  → → 0

 90%|█████████ | 692/765 [03:44<00:22,  3.28it/s]

[692/765]  raw='fail'  → → 0

 91%|█████████ | 693/765 [03:44<00:25,  2.87it/s]

[693/765]  raw='pass'  → → 1

 91%|█████████ | 694/765 [03:45<00:23,  2.98it/s]

[694/765]  raw='fail'  → → 0

 91%|█████████ | 695/765 [03:45<00:22,  3.07it/s]

[695/765]  raw='fail'  → → 0

 91%|█████████ | 696/765 [03:45<00:22,  3.13it/s]

[696/765]  raw='fail'  → → 0

 91%|█████████ | 697/765 [03:46<00:21,  3.16it/s]

[697/765]  raw='pass'  → → 1

 91%|█████████ | 698/765 [03:46<00:20,  3.19it/s]

[698/765]  raw='fail'  → → 0

 91%|█████████▏| 699/765 [03:46<00:20,  3.21it/s]

[699/765]  raw='fail'  → → 0

 92%|█████████▏| 700/765 [03:47<00:20,  3.24it/s]

[700/765]  raw='fail'  → → 0

 92%|█████████▏| 701/765 [03:47<00:19,  3.26it/s]

[701/765]  raw='fail'  → → 0

 92%|█████████▏| 702/765 [03:47<00:19,  3.29it/s]

[702/765]  raw='fail'  → → 0

 92%|█████████▏| 703/765 [03:47<00:18,  3.30it/s]

[703/765]  raw='pass'  → → 1

 92%|█████████▏| 704/765 [03:48<00:18,  3.29it/s]

[704/765]  raw='pass'  → → 1

 92%|█████████▏| 705/765 [03:48<00:18,  3.30it/s]

[705/765]  raw='fail'  → → 0

 92%|█████████▏| 706/765 [03:48<00:17,  3.29it/s]

[706/765]  raw='fail'  → → 0

 92%|█████████▏| 707/765 [03:49<00:20,  2.88it/s]

[707/765]  raw='pass'  → → 1

 93%|█████████▎| 708/765 [03:49<00:19,  2.96it/s]

[708/765]  raw='fail'  → → 0

 93%|█████████▎| 709/765 [03:49<00:18,  3.03it/s]

[709/765]  raw='fail'  → → 0

 93%|█████████▎| 710/765 [03:50<00:17,  3.12it/s]

[710/765]  raw='pass'  → → 1

 93%|█████████▎| 711/765 [03:50<00:17,  3.17it/s]

[711/765]  raw='fail'  → → 0

 93%|█████████▎| 712/765 [03:50<00:16,  3.21it/s]

[712/765]  raw='pass'  → → 1

 93%|█████████▎| 713/765 [03:51<00:16,  3.07it/s]

[713/765]  raw='pass'  → → 1

 93%|█████████▎| 714/765 [03:51<00:16,  3.12it/s]

[714/765]  raw='fail'  → → 0

 93%|█████████▎| 715/765 [03:51<00:15,  3.18it/s]

[715/765]  raw='fail'  → → 0

 94%|█████████▎| 716/765 [03:52<00:15,  3.21it/s]

[716/765]  raw='fail'  → → 0

 94%|█████████▎| 717/765 [03:52<00:14,  3.25it/s]

[717/765]  raw='pass'  → → 1

 94%|█████████▍| 718/765 [03:52<00:14,  3.24it/s]

[718/765]  raw='fail'  → → 0

 94%|█████████▍| 719/765 [03:53<00:14,  3.26it/s]

[719/765]  raw='fail'  → → 0

 94%|█████████▍| 720/765 [03:53<00:13,  3.26it/s]

[720/765]  raw='fail'  → → 0

 94%|█████████▍| 721/765 [03:53<00:13,  3.27it/s]

[721/765]  raw='pass'  → → 1

 94%|█████████▍| 722/765 [03:53<00:13,  3.27it/s]

[722/765]  raw='fail'  → → 0

 95%|█████████▍| 723/765 [03:54<00:12,  3.29it/s]

[723/765]  raw='fail'  → → 0

 95%|█████████▍| 724/765 [03:54<00:12,  3.31it/s]

[724/765]  raw='fail'  → → 0

 95%|█████████▍| 725/765 [03:54<00:12,  3.32it/s]

[725/765]  raw='fail'  → → 0

 95%|█████████▍| 726/765 [03:55<00:11,  3.31it/s]

[726/765]  raw='pass'  → → 1

 95%|█████████▌| 727/765 [03:55<00:11,  3.31it/s]

[727/765]  raw='fail'  → → 0

 95%|█████████▌| 728/765 [03:55<00:11,  3.30it/s]

[728/765]  raw='fail'  → → 0

 95%|█████████▌| 729/765 [03:56<00:10,  3.32it/s]

[729/765]  raw='pass'  → → 1

 95%|█████████▌| 730/765 [03:56<00:10,  3.34it/s]

[730/765]  raw='fail'  → → 0

 96%|█████████▌| 731/765 [03:56<00:10,  3.35it/s]

[731/765]  raw='fail'  → → 0

 96%|█████████▌| 732/765 [03:57<00:11,  2.99it/s]

[732/765]  raw='pass'  → → 1

 96%|█████████▌| 733/765 [03:57<00:10,  3.10it/s]

[733/765]  raw='fail'  → → 0

 96%|█████████▌| 734/765 [03:57<00:09,  3.17it/s]

[734/765]  raw='pass'  → → 1

 96%|█████████▌| 735/765 [03:57<00:09,  3.23it/s]

[735/765]  raw='fail'  → → 0

 96%|█████████▌| 736/765 [03:58<00:08,  3.24it/s]

[736/765]  raw='fail'  → → 0

 96%|█████████▋| 737/765 [03:58<00:08,  3.25it/s]

[737/765]  raw='fail'  → → 0

 96%|█████████▋| 738/765 [03:58<00:08,  3.24it/s]

[738/765]  raw='pass'  → → 1

 97%|█████████▋| 739/765 [03:59<00:08,  3.23it/s]

[739/765]  raw='fail'  → → 0

 97%|█████████▋| 740/765 [03:59<00:07,  3.21it/s]

[740/765]  raw='fail'  → → 0

 97%|█████████▋| 741/765 [03:59<00:07,  3.20it/s]

[741/765]  raw='fail'  → → 0

 97%|█████████▋| 742/765 [04:00<00:07,  3.21it/s]

[742/765]  raw='pass'  → → 1

 97%|█████████▋| 743/765 [04:00<00:06,  3.18it/s]

[743/765]  raw='fail'  → → 0

 97%|█████████▋| 744/765 [04:00<00:06,  3.18it/s]

[744/765]  raw='pass'  → → 1

 97%|█████████▋| 745/765 [04:01<00:06,  3.20it/s]

[745/765]  raw='fail'  → → 0

 98%|█████████▊| 746/765 [04:01<00:05,  3.20it/s]

[746/765]  raw='pass'  → → 1

 98%|█████████▊| 747/765 [04:01<00:05,  3.20it/s]

[747/765]  raw='fail'  → → 0

 98%|█████████▊| 748/765 [04:02<00:05,  3.20it/s]

[748/765]  raw='fail'  → → 0

 98%|█████████▊| 749/765 [04:02<00:04,  3.21it/s]

[749/765]  raw='fail'  → → 0

 98%|█████████▊| 750/765 [04:02<00:04,  3.22it/s]

[750/765]  raw='fail'  → → 0

 98%|█████████▊| 751/765 [04:02<00:04,  3.22it/s]

[751/765]  raw='fail'  → → 0

 98%|█████████▊| 752/765 [04:03<00:04,  3.08it/s]

[752/765]  raw='pass'  → → 1

 98%|█████████▊| 753/765 [04:03<00:03,  3.14it/s]

[753/765]  raw='fail'  → → 0

 99%|█████████▊| 754/765 [04:03<00:03,  3.17it/s]

[754/765]  raw='fail'  → → 0

 99%|█████████▊| 755/765 [04:04<00:03,  3.19it/s]

[755/765]  raw='pass'  → → 1

 99%|█████████▉| 756/765 [04:04<00:02,  3.06it/s]

[756/765]  raw='pass'  → → 1

 99%|█████████▉| 757/765 [04:04<00:02,  3.13it/s]

[757/765]  raw='pass'  → → 1

 99%|█████████▉| 758/765 [04:05<00:02,  3.18it/s]

[758/765]  raw='pass'  → → 1

 99%|█████████▉| 759/765 [04:05<00:01,  3.04it/s]

[759/765]  raw='pass'  → → 1

 99%|█████████▉| 760/765 [04:05<00:01,  3.11it/s]

[760/765]  raw='pass'  → → 1

 99%|█████████▉| 761/765 [04:06<00:01,  3.14it/s]

[761/765]  raw='pass'  → → 1

100%|█████████▉| 762/765 [04:06<00:00,  3.17it/s]

[762/765]  raw='fail'  → → 0

100%|█████████▉| 763/765 [04:06<00:00,  2.98it/s]

[763/765]  raw='pass'  → → 1

100%|█████████▉| 764/765 [04:07<00:00,  3.07it/s]

[764/765]  raw='pass'  → → 1

100%|██████████| 765/765 [04:07<00:00,  3.09it/s]

[765/765]  raw='fail'  → → 0
Parsed: 765/765
Accuracy: 0.8876
              precision    recall  f1-score   support

        Fail       0.90      0.90      0.90       442
        Pass       0.87      0.87      0.87       323

    accuracy                           0.89       765
   macro avg       0.88      0.88      0.88       765
weighted avg       0.89      0.89      0.89       765

[[399  43]
 [ 43 280]]
Predicted-Pass fraction: 0.4222222222222222  (true rate 0.42)

.89 O_O

In [ ]:
from google.colab import runtime
print("Everything saved. Releasing the runtime.")
runtime.unassign()
# stop the runtime

Everything saved. Releasing the runtime.

## HuggingGaceH4 4bit

In [ ]:
# Zephyr 7B with 4bit quantization (required for T4 16GB)
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "HuggingFaceH4/zephyr-7b-beta"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.pad_token_id = tokenizer.eos_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

Model loaded on: cuda:0
Memory (MB)    : 4014.5

In [ ]:
#not doing this anymore

# Zephyr uses a ChatML-style template
def generate_zephyr_prompt(row):
    system_msg = "You are a strict essay grader. Respond with one word only: Pass or Fail."
    user_msg = (
        f"Prompt name: {row['prompt_name']}\n"
        f"Task type: {row['task']}\n\n"
        f"Classify the essay as Pass or Fail.\n"
        f"Pass = proficient or above. Fail = developing or below.\n"
        f"Respond with one word only: Pass or Fail.\n\n"
        f"Essay: {row['full_text']}"
    )
    # Zephyr ChatML format
    return (
        f"<|system|>\n{system_msg}</s>\n"
        f"<|user|>\n{user_msg}</s>\n"
        f"<|assistant|>\n"
    )

X_test_prompts_zephyr = pd.DataFrame(
    test_df.apply(generate_zephyr_prompt, axis=1), columns=["text"]
)
print(f"Test prompts: {len(X_test_prompts_zephyr)}")
print("\nExample (first 300 chars):")
print(X_test_prompts_zephyr["text"].iloc[0][:300])

Test prompts: 765

Example (first 300 chars):
<|system|>
You are a strict essay grader. Respond with one word only: Pass or Fail.</s>
<|user|>
Prompt name: Cell phones at school
Task type: Independent

Classify the essay as Pass or Fail.
Pass = proficient or above. Fail = developing or below.
Respond with one word only: Pass or Fail.

Essay: I

In [ ]:
# Predict function for Zephyr
def predict_zephyr(test, model, tokenizer, max_input_tokens=3500):
    y_pred      = []
    y_generated = []

    model.eval()
    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]

        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=max_input_tokens,
            padding=False,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=5,
                do_sample=False,        # greedy — deterministic
                pad_token_id=tokenizer.eos_token_id,
            )

        # decode only newly generated tokens
        new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
        generated  = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        result = {1: "Pass", 0: "Fail", -1: "???"}[y_pred[-1]]
        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {result}")

    return y_pred, y_generated


# run on full test set
#y_pred, y_generated = predict_zephyr(X_test_prompts_zephyr, model, tokenizer)

In [ ]:
# run on full test set
y_pred, y_generated = predict_zephyr(X_test_prompts_zephyr, model, tokenizer)

  0%|          | 0/765 [00:00<?, ?it/s]
  0%|          | 1/765 [00:01<15:44,  1.24s/it]

[  1/765]  raw='pass.'  →  Pass

  0%|          | 2/765 [00:02<16:50,  1.32s/it]

[  2/765]  raw='pass.'  →  Pass

  0%|          | 3/765 [00:03<16:09,  1.27s/it]

[  3/765]  raw='pass.'  →  Pass

  1%|          | 4/765 [00:05<18:16,  1.44s/it]

[  4/765]  raw='pass.'  →  Pass

  1%|          | 5/765 [00:06<16:33,  1.31s/it]

[  5/765]  raw='pass.'  →  Pass

  1%|          | 6/765 [00:07<15:59,  1.26s/it]

[  6/765]  raw='pass.'  →  Pass

  1%|          | 7/765 [00:09<17:07,  1.36s/it]

[  7/765]  raw='pass.'  →  Pass

  1%|          | 8/765 [00:10<16:12,  1.29s/it]

[  8/765]  raw='pass.'  →  Pass

  1%|          | 9/765 [00:12<17:24,  1.38s/it]

[  9/765]  raw='pass.'  →  Pass

  1%|▏         | 10/765 [00:12<15:15,  1.21s/it]

[ 10/765]  raw='pass.'  →  Pass

  1%|▏         | 11/765 [00:14<15:03,  1.20s/it]

[ 11/765]  raw='pass.'  →  Pass

  2%|▏         | 12/765 [00:15<16:46,  1.34s/it]

[ 12/765]  raw='pass.'  →  Pass

  2%|▏         | 13/765 [00:16<15:55,  1.27s/it]

[ 13/765]  raw='pass.'  →  Pass

  2%|▏         | 14/765 [00:18<15:37,  1.25s/it]

[ 14/765]  raw='pass.'  →  Pass

  2%|▏         | 15/765 [00:19<15:06,  1.21s/it]

[ 15/765]  raw='pass.'  →  Pass

  2%|▏         | 16/765 [00:20<15:39,  1.25s/it]

[ 16/765]  raw='pass.'  →  Pass

  2%|▏         | 17/765 [00:21<15:15,  1.22s/it]

[ 17/765]  raw='pass.'  →  Pass

  2%|▏         | 18/765 [00:23<16:12,  1.30s/it]

[ 18/765]  raw='pass.'  →  Pass

  2%|▏         | 19/765 [00:24<14:49,  1.19s/it]

[ 19/765]  raw='pass.'  →  Pass

  3%|▎         | 20/765 [00:26<17:42,  1.43s/it]

[ 20/765]  raw='pass.'  →  Pass

  3%|▎         | 21/765 [00:27<16:02,  1.29s/it]

[ 21/765]  raw='pass.'  →  Pass

  3%|▎         | 22/765 [00:28<15:10,  1.23s/it]

[ 22/765]  raw='pass.'  →  Pass

  3%|▎         | 23/765 [00:29<14:05,  1.14s/it]

[ 23/765]  raw='pass.'  →  Pass

  3%|▎         | 24/765 [00:30<16:46,  1.36s/it]

[ 24/765]  raw='fail.'  →  Fail

  3%|▎         | 25/765 [00:32<16:53,  1.37s/it]

[ 25/765]  raw='pass.'  →  Pass

  3%|▎         | 26/765 [00:33<15:39,  1.27s/it]

[ 26/765]  raw='pass.'  →  Pass

  4%|▎         | 27/765 [00:34<14:36,  1.19s/it]

[ 27/765]  raw='pass.'  →  Pass

  4%|▎         | 28/765 [00:35<14:28,  1.18s/it]

[ 28/765]  raw='pass.'  →  Pass

  4%|▍         | 29/765 [00:36<14:28,  1.18s/it]

[ 29/765]  raw='pass.'  →  Pass

  4%|▍         | 30/765 [00:37<14:18,  1.17s/it]

[ 30/765]  raw='pass.'  →  Pass

  4%|▍         | 31/765 [00:39<14:30,  1.19s/it]

[ 31/765]  raw='pass.'  →  Pass

  4%|▍         | 32/765 [00:40<14:15,  1.17s/it]

[ 32/765]  raw='pass.'  →  Pass

  4%|▍         | 33/765 [00:41<16:36,  1.36s/it]

[ 33/765]  raw='pass.'  →  Pass

  4%|▍         | 34/765 [00:42<15:12,  1.25s/it]

[ 34/765]  raw='pass.'  →  Pass

  5%|▍         | 35/765 [00:43<14:19,  1.18s/it]

[ 35/765]  raw='pass.'  →  Pass

  5%|▍         | 36/765 [00:45<14:06,  1.16s/it]

[ 36/765]  raw='pass.'  →  Pass

  5%|▍         | 37/765 [00:46<14:03,  1.16s/it]

[ 37/765]  raw='fail.'  →  Fail

  5%|▍         | 38/765 [00:47<13:58,  1.15s/it]

[ 38/765]  raw='pass.'  →  Pass

  5%|▌         | 39/765 [00:48<14:41,  1.21s/it]

[ 39/765]  raw='pass.'  →  Pass

  5%|▌         | 40/765 [00:50<15:51,  1.31s/it]

[ 40/765]  raw='pass.'  →  Pass

  5%|▌         | 41/765 [00:52<19:46,  1.64s/it]

[ 41/765]  raw='pass. the essay presents'  →  Pass

  5%|▌         | 42/765 [00:54<19:14,  1.60s/it]

[ 42/765]  raw='pass. the essay demonstr'  →  Pass

  6%|▌         | 43/765 [00:55<16:28,  1.37s/it]

[ 43/765]  raw='pass.'  →  Pass

  6%|▌         | 44/765 [00:56<15:34,  1.30s/it]

[ 44/765]  raw='pass.'  →  Pass

  6%|▌         | 45/765 [00:56<13:53,  1.16s/it]

[ 45/765]  raw='pass.'  →  Pass

  6%|▌         | 46/765 [00:58<14:22,  1.20s/it]

[ 46/765]  raw='fail.

ex'  →  Fail

  6%|▌         | 47/765 [00:59<14:33,  1.22s/it]

[ 47/765]  raw='prompt name: ph'  →  ???

  6%|▋         | 48/765 [01:00<14:16,  1.19s/it]

[ 48/765]  raw='pass.'  →  Pass

  6%|▋         | 49/765 [01:01<13:27,  1.13s/it]

[ 49/765]  raw='fail.'  →  Fail

  7%|▋         | 50/765 [01:03<14:22,  1.21s/it]

[ 50/765]  raw='pass.'  →  Pass

  7%|▋         | 51/765 [01:04<14:15,  1.20s/it]

[ 51/765]  raw='pass.'  →  Pass

  7%|▋         | 52/765 [01:05<13:21,  1.12s/it]

[ 52/765]  raw='fail.'  →  Fail

  7%|▋         | 53/765 [01:06<13:58,  1.18s/it]

[ 53/765]  raw='pass.

ex'  →  Pass

  7%|▋         | 54/765 [01:08<16:47,  1.42s/it]

[ 54/765]  raw='pass.'  →  Pass

  7%|▋         | 55/765 [01:09<15:33,  1.32s/it]

[ 55/765]  raw='pass.'  →  Pass

  7%|▋         | 56/765 [01:10<14:15,  1.21s/it]

[ 56/765]  raw='pass.'  →  Pass

  7%|▋         | 57/765 [01:11<13:28,  1.14s/it]

[ 57/765]  raw='pass.'  →  Pass

  8%|▊         | 58/765 [01:12<13:17,  1.13s/it]

[ 58/765]  raw='pass.'  →  Pass

  8%|▊         | 59/765 [01:13<13:50,  1.18s/it]

[ 59/765]  raw='pass.'  →  Pass

  8%|▊         | 60/765 [01:14<12:37,  1.07s/it]

[ 60/765]  raw='pass.'  →  Pass

  8%|▊         | 61/765 [01:16<14:22,  1.23s/it]

[ 61/765]  raw='pass.

ex'  →  Pass

  8%|▊         | 62/765 [01:17<14:04,  1.20s/it]

[ 62/765]  raw='pass.'  →  Pass

  8%|▊         | 63/765 [01:19<15:37,  1.34s/it]

[ 63/765]  raw='fail. the essay presents'  →  Fail

  8%|▊         | 64/765 [01:19<13:53,  1.19s/it]

[ 64/765]  raw='fail.'  →  Fail

  8%|▊         | 65/765 [01:20<12:38,  1.08s/it]

[ 65/765]  raw='pass.'  →  Pass

  9%|▊         | 66/765 [01:22<13:18,  1.14s/it]

[ 66/765]  raw='pass.'  →  Pass

  9%|▉         | 67/765 [01:23<14:28,  1.24s/it]

[ 67/765]  raw='pass.'  →  Pass

  9%|▉         | 68/765 [01:24<13:28,  1.16s/it]

[ 68/765]  raw='pass.'  →  Pass

  9%|▉         | 69/765 [01:25<13:05,  1.13s/it]

[ 69/765]  raw='pass.'  →  Pass

  9%|▉         | 70/765 [01:26<12:20,  1.07s/it]

[ 70/765]  raw='pass.'  →  Pass

  9%|▉         | 71/765 [01:27<12:28,  1.08s/it]

[ 71/765]  raw='pass.'  →  Pass

  9%|▉         | 72/765 [01:28<11:52,  1.03s/it]

[ 72/765]  raw='fail.'  →  Fail

 10%|▉         | 73/765 [01:29<12:10,  1.06s/it]

[ 73/765]  raw='fail. safety concerns and'  →  Fail

 10%|▉         | 74/765 [01:30<12:31,  1.09s/it]

[ 74/765]  raw='fail. flaws out'  →  Fail

 10%|▉         | 75/765 [01:31<12:33,  1.09s/it]

[ 75/765]  raw='pass.

e'  →  Pass

 10%|▉         | 76/765 [01:33<13:22,  1.17s/it]

[ 76/765]  raw='pass.'  →  Pass

 10%|█         | 77/765 [01:34<12:15,  1.07s/it]

[ 77/765]  raw='pass.'  →  Pass

 10%|█         | 78/765 [01:35<12:28,  1.09s/it]

[ 78/765]  raw='fail.'  →  Fail

 10%|█         | 79/765 [01:36<11:43,  1.03s/it]

[ 79/765]  raw='pass.'  →  Pass

 10%|█         | 80/765 [01:37<13:39,  1.20s/it]

[ 80/765]  raw='pass.'  →  Pass

 11%|█         | 81/765 [01:39<14:12,  1.25s/it]

[ 81/765]  raw='fail.'  →  Fail

 11%|█         | 82/765 [01:40<14:03,  1.24s/it]

[ 82/765]  raw='pass.'  →  Pass

 11%|█         | 83/765 [01:42<16:38,  1.46s/it]

[ 83/765]  raw='pass. the essay presents'  →  Pass

 11%|█         | 84/765 [01:44<18:31,  1.63s/it]

[ 84/765]  raw='pass. the essay demonstr'  →  Pass

 11%|█         | 85/765 [01:45<15:54,  1.40s/it]

[ 85/765]  raw='pass.'  →  Pass

 11%|█         | 86/765 [01:46<15:30,  1.37s/it]

[ 86/765]  raw='pass.'  →  Pass

 11%|█▏        | 87/765 [01:47<14:34,  1.29s/it]

[ 87/765]  raw='pass.'  →  Pass

 12%|█▏        | 88/765 [01:48<13:38,  1.21s/it]

[ 88/765]  raw='pass.'  →  Pass

 12%|█▏        | 89/765 [01:49<14:03,  1.25s/it]

[ 89/765]  raw='pass.'  →  Pass

 12%|█▏        | 90/765 [01:50<13:03,  1.16s/it]

[ 90/765]  raw='pass.'  →  Pass

 12%|█▏        | 91/765 [01:52<13:45,  1.23s/it]

[ 91/765]  raw='pass.'  →  Pass

 12%|█▏        | 92/765 [01:54<15:51,  1.41s/it]

[ 92/765]  raw='pass.'  →  Pass

 12%|█▏        | 93/765 [01:55<16:03,  1.43s/it]

[ 93/765]  raw='pass.'  →  Pass

 12%|█▏        | 94/765 [01:56<14:24,  1.29s/it]

[ 94/765]  raw='pass.'  →  Pass

 12%|█▏        | 95/765 [01:57<13:42,  1.23s/it]

[ 95/765]  raw='fail.'  →  Fail

 13%|█▎        | 96/765 [01:58<12:28,  1.12s/it]

[ 96/765]  raw='pass.'  →  Pass

 13%|█▎        | 97/765 [01:59<11:40,  1.05s/it]

[ 97/765]  raw='fail.'  →  Fail

 13%|█▎        | 98/765 [02:00<11:21,  1.02s/it]

[ 98/765]  raw='pass.'  →  Pass

 13%|█▎        | 99/765 [02:02<13:54,  1.25s/it]

[ 99/765]  raw='pass.'  →  Pass

 13%|█▎        | 100/765 [02:02<12:37,  1.14s/it]

[100/765]  raw='fail.'  →  Fail

 13%|█▎        | 101/765 [02:03<12:01,  1.09s/it]

[101/765]  raw='pass.'  →  Pass

 13%|█▎        | 102/765 [02:05<12:12,  1.10s/it]

[102/765]  raw='pass.'  →  Pass

 13%|█▎        | 103/765 [02:06<11:50,  1.07s/it]

[103/765]  raw='pass.'  →  Pass

 14%|█▎        | 104/765 [02:07<11:34,  1.05s/it]

[104/765]  raw='pass.'  →  Pass

 14%|█▎        | 105/765 [02:07<10:55,  1.01it/s]

[105/765]  raw='pass.'  →  Pass

 14%|█▍        | 106/765 [02:09<13:27,  1.23s/it]

[106/765]  raw='pass.'  →  Pass

 14%|█▍        | 107/765 [02:11<13:51,  1.26s/it]

[107/765]  raw='pass.'  →  Pass

 14%|█▍        | 108/765 [02:11<12:48,  1.17s/it]

[108/765]  raw='pass.'  →  Pass

 14%|█▍        | 109/765 [02:13<13:40,  1.25s/it]

[109/765]  raw='pass.'  →  Pass

 14%|█▍        | 110/765 [02:14<12:39,  1.16s/it]

[110/765]  raw='pass.'  →  Pass

 15%|█▍        | 111/765 [02:15<12:00,  1.10s/it]

[111/765]  raw='pass.'  →  Pass

 15%|█▍        | 112/765 [02:16<11:30,  1.06s/it]

[112/765]  raw='pass.'  →  Pass

 15%|█▍        | 113/765 [02:17<11:50,  1.09s/it]

[113/765]  raw='pass.'  →  Pass

 15%|█▍        | 114/765 [02:18<12:25,  1.15s/it]

[114/765]  raw='pass.'  →  Pass

 15%|█▌        | 115/765 [02:19<11:44,  1.08s/it]

[115/765]  raw='pass.'  →  Pass

 15%|█▌        | 116/765 [02:20<11:19,  1.05s/it]

[116/765]  raw='pass.'  →  Pass

 15%|█▌        | 117/765 [02:21<11:38,  1.08s/it]

[117/765]  raw='fail.'  →  Fail

 15%|█▌        | 118/765 [02:22<11:52,  1.10s/it]

[118/765]  raw='pass.'  →  Pass

 16%|█▌        | 119/765 [02:24<11:50,  1.10s/it]

[119/765]  raw='pass.'  →  Pass

 16%|█▌        | 120/765 [02:25<13:10,  1.23s/it]

[120/765]  raw='pass.

e'  →  Pass

 16%|█▌        | 121/765 [02:27<14:01,  1.31s/it]

[121/765]  raw='pass.'  →  Pass

 16%|█▌        | 122/765 [02:28<13:33,  1.27s/it]

[122/765]  raw='pass.'  →  Pass

 16%|█▌        | 123/765 [02:29<14:14,  1.33s/it]

[123/765]  raw='pass.'  →  Pass

 16%|█▌        | 124/765 [02:31<14:32,  1.36s/it]

[124/765]  raw='pass.'  →  Pass

 16%|█▋        | 125/765 [02:31<12:55,  1.21s/it]

[125/765]  raw='pass.'  →  Pass

 16%|█▋        | 126/765 [02:32<12:07,  1.14s/it]

[126/765]  raw='pass.'  →  Pass

 17%|█▋        | 127/765 [02:33<11:38,  1.09s/it]

[127/765]  raw='pass.'  →  Pass

 17%|█▋        | 128/765 [02:34<11:14,  1.06s/it]

[128/765]  raw='pass.'  →  Pass

 17%|█▋        | 129/765 [02:36<11:56,  1.13s/it]

[129/765]  raw='pass.'  →  Pass

 17%|█▋        | 130/765 [02:37<13:00,  1.23s/it]

[130/765]  raw='pass.'  →  Pass

 17%|█▋        | 131/765 [02:38<12:37,  1.19s/it]

[131/765]  raw='pass.'  →  Pass

 17%|█▋        | 132/765 [02:39<11:49,  1.12s/it]

[132/765]  raw='pass.'  →  Pass

 17%|█▋        | 133/765 [02:41<12:36,  1.20s/it]

[133/765]  raw='pass.

ex'  →  Pass

 18%|█▊        | 134/765 [02:42<12:34,  1.20s/it]

[134/765]  raw='fail.'  →  Fail

 18%|█▊        | 135/765 [02:43<11:56,  1.14s/it]

[135/765]  raw='pass.'  →  Pass

 18%|█▊        | 136/765 [02:44<11:57,  1.14s/it]

[136/765]  raw='pass.'  →  Pass

 18%|█▊        | 137/765 [02:46<14:04,  1.34s/it]

[137/765]  raw='pass.'  →  Pass

 18%|█▊        | 138/765 [02:47<13:58,  1.34s/it]

[138/765]  raw='fail.'  →  Fail

 18%|█▊        | 139/765 [02:49<15:26,  1.48s/it]

[139/765]  raw='pass.'  →  Pass

 18%|█▊        | 140/765 [02:50<13:32,  1.30s/it]

[140/765]  raw='pass.'  →  Pass

 18%|█▊        | 141/765 [02:51<12:35,  1.21s/it]

[141/765]  raw='pass.'  →  Pass

 19%|█▊        | 142/765 [02:53<14:14,  1.37s/it]

[142/765]  raw='pass. the essay demonstr'  →  Pass

 19%|█▊        | 143/765 [02:54<14:00,  1.35s/it]

[143/765]  raw='pass.

prom'  →  Pass

 19%|█▉        | 144/765 [02:56<17:01,  1.64s/it]

[144/765]  raw='pass.'  →  Pass

 19%|█▉        | 145/765 [02:57<15:27,  1.50s/it]

[145/765]  raw='pass.'  →  Pass

 19%|█▉        | 146/765 [02:58<13:55,  1.35s/it]

[146/765]  raw='pass.'  →  Pass

 19%|█▉        | 147/765 [03:00<15:22,  1.49s/it]

[147/765]  raw='pass.'  →  Pass

 19%|█▉        | 148/765 [03:02<15:03,  1.46s/it]

[148/765]  raw='pass.'  →  Pass

 19%|█▉        | 149/765 [03:03<14:04,  1.37s/it]

[149/765]  raw='pass.'  →  Pass

 20%|█▉        | 150/765 [03:04<12:54,  1.26s/it]

[150/765]  raw='pass.'  →  Pass

 20%|█▉        | 151/765 [03:05<14:27,  1.41s/it]

[151/765]  raw='pass.'  →  Pass

 20%|█▉        | 152/765 [03:07<14:52,  1.46s/it]

[152/765]  raw='pass.

e'  →  Pass

 20%|██        | 153/765 [03:08<13:46,  1.35s/it]

[153/765]  raw='pass.'  →  Pass

 20%|██        | 154/765 [03:10<14:20,  1.41s/it]

[154/765]  raw='pass.

ex'  →  Pass

 20%|██        | 155/765 [03:11<14:08,  1.39s/it]

[155/765]  raw='pass.'  →  Pass

 20%|██        | 156/765 [03:13<14:37,  1.44s/it]

[156/765]  raw='pass.'  →  Pass

 21%|██        | 157/765 [03:14<15:26,  1.52s/it]

[157/765]  raw='fail. the essay presents'  →  Fail

 21%|██        | 158/765 [03:16<16:09,  1.60s/it]

[158/765]  raw='fail.

ex'  →  Fail

 21%|██        | 159/765 [03:18<15:36,  1.55s/it]

[159/765]  raw='pass.'  →  Pass

 21%|██        | 160/765 [03:19<16:23,  1.63s/it]

[160/765]  raw='fail. developing.'  →  Fail

 21%|██        | 161/765 [03:20<14:17,  1.42s/it]

[161/765]  raw='pass.'  →  Pass

 21%|██        | 162/765 [03:21<12:38,  1.26s/it]

[162/765]  raw='pass.'  →  Pass

 21%|██▏       | 163/765 [03:22<12:14,  1.22s/it]

[163/765]  raw='pass.'  →  Pass

 21%|██▏       | 164/765 [03:23<11:54,  1.19s/it]

[164/765]  raw='pass.'  →  Pass

 22%|██▏       | 165/765 [03:25<12:22,  1.24s/it]

[165/765]  raw='pass.

ex'  →  Pass

 22%|██▏       | 166/765 [03:26<11:56,  1.20s/it]

[166/765]  raw='fail.'  →  Fail

 22%|██▏       | 167/765 [03:27<11:12,  1.13s/it]

[167/765]  raw='pass.'  →  Pass

 22%|██▏       | 168/765 [03:28<11:12,  1.13s/it]

[168/765]  raw='pass.'  →  Pass

 22%|██▏       | 169/765 [03:29<11:58,  1.21s/it]

[169/765]  raw='pass.'  →  Pass

 22%|██▏       | 170/765 [03:30<11:51,  1.20s/it]

[170/765]  raw='pass.'  →  Pass

 22%|██▏       | 171/765 [03:32<12:51,  1.30s/it]

[171/765]  raw='pass.'  →  Pass

 22%|██▏       | 172/765 [03:33<13:15,  1.34s/it]

[172/765]  raw='pass.'  →  Pass

 23%|██▎       | 173/765 [03:35<14:28,  1.47s/it]

[173/765]  raw='pass.'  →  Pass

 23%|██▎       | 174/765 [03:37<15:17,  1.55s/it]

[174/765]  raw='pass.'  →  Pass

 23%|██▎       | 175/765 [03:38<13:17,  1.35s/it]

[175/765]  raw='pass.'  →  Pass

 23%|██▎       | 176/765 [03:39<12:06,  1.23s/it]

[176/765]  raw='pass.'  →  Pass

 23%|██▎       | 177/765 [03:40<11:22,  1.16s/it]

[177/765]  raw='pass.'  →  Pass

 23%|██▎       | 178/765 [03:41<12:27,  1.27s/it]

[178/765]  raw='pass.'  →  Pass

 23%|██▎       | 179/765 [03:43<14:48,  1.52s/it]

[179/765]  raw='pass.'  →  Pass

 24%|██▎       | 180/765 [03:44<13:25,  1.38s/it]

[180/765]  raw='pass.

ex'  →  Pass

 24%|██▎       | 181/765 [03:45<11:51,  1.22s/it]

[181/765]  raw='pass.'  →  Pass

 24%|██▍       | 182/765 [03:46<10:50,  1.12s/it]

[182/765]  raw='fail.'  →  Fail

 24%|██▍       | 183/765 [03:47<10:19,  1.07s/it]

[183/765]  raw='pass.'  →  Pass

 24%|██▍       | 184/765 [03:48<09:40,  1.00it/s]

[184/765]  raw='pass.'  →  Pass

 24%|██▍       | 185/765 [03:49<10:59,  1.14s/it]

[185/765]  raw='pass.'  →  Pass

 24%|██▍       | 186/765 [03:51<12:15,  1.27s/it]

[186/765]  raw='pass.'  →  Pass

 24%|██▍       | 187/765 [03:52<11:50,  1.23s/it]

[187/765]  raw='pass.'  →  Pass

 25%|██▍       | 188/765 [03:53<10:56,  1.14s/it]

[188/765]  raw='pass.'  →  Pass

 25%|██▍       | 189/765 [03:54<11:38,  1.21s/it]

[189/765]  raw='pass.'  →  Pass

 25%|██▍       | 190/765 [03:56<12:10,  1.27s/it]

[190/765]  raw='pass.'  →  Pass

 25%|██▍       | 191/765 [03:57<12:20,  1.29s/it]

[191/765]  raw='pass.'  →  Pass

 25%|██▌       | 192/765 [03:59<13:52,  1.45s/it]

[192/765]  raw='pass.'  →  Pass

 25%|██▌       | 193/765 [04:00<13:00,  1.36s/it]

[193/765]  raw='pass.'  →  Pass

 25%|██▌       | 194/765 [04:02<12:56,  1.36s/it]

[194/765]  raw='pass.'  →  Pass

 25%|██▌       | 195/765 [04:04<15:45,  1.66s/it]

[195/765]  raw='pass. the essay presents'  →  Pass

 26%|██▌       | 196/765 [04:05<14:10,  1.50s/it]

[196/765]  raw='pass.

ex'  →  Pass

 26%|██▌       | 197/765 [04:07<14:07,  1.49s/it]

[197/765]  raw='pass.'  →  Pass

 26%|██▌       | 198/765 [04:08<13:07,  1.39s/it]

[198/765]  raw='pass.'  →  Pass

 26%|██▌       | 199/765 [04:09<12:26,  1.32s/it]

[199/765]  raw='pass.'  →  Pass

 26%|██▌       | 200/765 [04:10<11:52,  1.26s/it]

[200/765]  raw='pass (essay demonstr'  →  Pass

 26%|██▋       | 201/765 [04:11<11:21,  1.21s/it]

[201/765]  raw='pass.'  →  Pass

 26%|██▋       | 202/765 [04:12<11:41,  1.25s/it]

[202/765]  raw='pass.

ex'  →  Pass

 27%|██▋       | 203/765 [04:14<12:24,  1.32s/it]

[203/765]  raw='fail. essay lack'  →  Fail

 27%|██▋       | 204/765 [04:15<11:26,  1.22s/it]

[204/765]  raw='pass.'  →  Pass

 27%|██▋       | 205/765 [04:16<11:14,  1.20s/it]

[205/765]  raw='pass.

ex'  →  Pass

 27%|██▋       | 206/765 [04:17<11:04,  1.19s/it]

[206/765]  raw='pass.'  →  Pass

 27%|██▋       | 207/765 [04:19<12:11,  1.31s/it]

[207/765]  raw='pass.'  →  Pass

 27%|██▋       | 208/765 [04:20<12:23,  1.33s/it]

[208/765]  raw='pass.'  →  Pass

 27%|██▋       | 209/765 [04:21<11:47,  1.27s/it]

[209/765]  raw='fail.'  →  Fail

 27%|██▋       | 210/765 [04:22<11:20,  1.23s/it]

[210/765]  raw='pass.'  →  Pass

 28%|██▊       | 211/765 [04:23<10:23,  1.13s/it]

[211/765]  raw='pass.'  →  Pass

 28%|██▊       | 212/765 [04:24<09:54,  1.07s/it]

[212/765]  raw='pass.'  →  Pass

 28%|██▊       | 213/765 [04:26<10:26,  1.13s/it]

[213/765]  raw='pass.'  →  Pass

 28%|██▊       | 214/765 [04:27<10:25,  1.13s/it]

[214/765]  raw='pass.

ex'  →  Pass

 28%|██▊       | 215/765 [04:28<10:24,  1.14s/it]

[215/765]  raw='pass.'  →  Pass

 28%|██▊       | 216/765 [04:29<09:55,  1.09s/it]

[216/765]  raw='pass.'  →  Pass

 28%|██▊       | 217/765 [04:30<09:48,  1.07s/it]

[217/765]  raw='pass.

e'  →  Pass

 28%|██▊       | 218/765 [04:32<13:10,  1.45s/it]

[218/765]  raw='fail. distance learning'  →  Fail

 29%|██▊       | 219/765 [04:34<13:44,  1.51s/it]

[219/765]  raw='prompt name: mand'  →  ???

 29%|██▉       | 220/765 [04:35<12:08,  1.34s/it]

[220/765]  raw='pass.'  →  Pass

 29%|██▉       | 221/765 [04:36<10:53,  1.20s/it]

[221/765]  raw='pass.'  →  Pass

 29%|██▉       | 222/765 [04:37<11:14,  1.24s/it]

[222/765]  raw='fail.

e'  →  Fail

 29%|██▉       | 223/765 [04:39<12:35,  1.39s/it]

[223/765]  raw='fail.

ex'  →  Fail

 29%|██▉       | 224/765 [04:40<12:37,  1.40s/it]

[224/765]  raw='pass.'  →  Pass

 29%|██▉       | 225/765 [04:41<11:44,  1.30s/it]

[225/765]  raw='pass.'  →  Pass

 30%|██▉       | 226/765 [04:43<12:18,  1.37s/it]

[226/765]  raw='pass.'  →  Pass

 30%|██▉       | 227/765 [04:44<11:30,  1.28s/it]

[227/765]  raw='pass.'  →  Pass

 30%|██▉       | 228/765 [04:45<11:25,  1.28s/it]

[228/765]  raw='pass. the essay demonstr'  →  Pass

 30%|██▉       | 229/765 [04:46<11:03,  1.24s/it]

[229/765]  raw='fail. essay lack'  →  Fail

 30%|███       | 230/765 [04:47<10:25,  1.17s/it]

[230/765]  raw='pass.'  →  Pass

 30%|███       | 231/765 [04:49<10:51,  1.22s/it]

[231/765]  raw='pass.'  →  Pass

 30%|███       | 232/765 [04:50<11:26,  1.29s/it]

[232/765]  raw='pass.'  →  Pass

 30%|███       | 233/765 [04:51<10:22,  1.17s/it]

[233/765]  raw='pass.'  →  Pass

 31%|███       | 234/765 [04:52<10:21,  1.17s/it]

[234/765]  raw='pass.'  →  Pass

 31%|███       | 235/765 [04:54<11:08,  1.26s/it]

[235/765]  raw='pass.'  →  Pass

 31%|███       | 236/765 [04:55<10:43,  1.22s/it]

[236/765]  raw='pass.'  →  Pass

 31%|███       | 237/765 [04:56<09:51,  1.12s/it]

[237/765]  raw='pass.'  →  Pass

 31%|███       | 238/765 [04:57<09:42,  1.10s/it]

[238/765]  raw='pass.'  →  Pass

 31%|███       | 239/765 [04:58<10:22,  1.18s/it]

[239/765]  raw='pass.'  →  Pass

 31%|███▏      | 240/765 [04:59<10:33,  1.21s/it]

[240/765]  raw='fail. extrac'  →  Fail

 32%|███▏      | 241/765 [05:01<11:49,  1.35s/it]

[241/765]  raw='pass.

ex'  →  Pass

 32%|███▏      | 242/765 [05:02<10:44,  1.23s/it]

[242/765]  raw='pass.'  →  Pass

 32%|███▏      | 243/765 [05:03<10:01,  1.15s/it]

[243/765]  raw='pass.'  →  Pass

 32%|███▏      | 244/765 [05:04<09:13,  1.06s/it]

[244/765]  raw='pass.'  →  Pass

 32%|███▏      | 245/765 [05:05<09:14,  1.07s/it]

[245/765]  raw='pass.'  →  Pass

 32%|███▏      | 246/765 [05:07<12:29,  1.44s/it]

[246/765]  raw='pass.'  →  Pass

 32%|███▏      | 247/765 [05:08<12:16,  1.42s/it]

[247/765]  raw='pass.'  →  Pass

 32%|███▏      | 248/765 [05:10<11:39,  1.35s/it]

[248/765]  raw='fail.

e'  →  Fail

 33%|███▎      | 249/765 [05:11<11:06,  1.29s/it]

[249/765]  raw='pass.'  →  Pass

 33%|███▎      | 250/765 [05:12<09:54,  1.15s/it]

[250/765]  raw='pass.'  →  Pass

 33%|███▎      | 251/765 [05:13<09:22,  1.09s/it]

[251/765]  raw='pass.'  →  Pass

 33%|███▎      | 252/765 [05:14<09:24,  1.10s/it]

[252/765]  raw='pass.'  →  Pass

 33%|███▎      | 253/765 [05:15<09:29,  1.11s/it]

[253/765]  raw='fail.'  →  Fail

 33%|███▎      | 254/765 [05:16<09:20,  1.10s/it]

[254/765]  raw='pass.

prom'  →  Pass

 33%|███▎      | 255/765 [05:18<11:30,  1.35s/it]

[255/765]  raw='pass. the essay demonstr'  →  Pass

 33%|███▎      | 256/765 [05:19<10:51,  1.28s/it]

[256/765]  raw='pass.'  →  Pass

 34%|███▎      | 257/765 [05:20<10:32,  1.24s/it]

[257/765]  raw='pass.'  →  Pass

 34%|███▎      | 258/765 [05:22<10:47,  1.28s/it]

[258/765]  raw='pass.

ex'  →  Pass

 34%|███▍      | 259/765 [05:22<09:59,  1.18s/it]

[259/765]  raw='pass.'  →  Pass

 34%|███▍      | 260/765 [05:24<10:19,  1.23s/it]

[260/765]  raw='pass.'  →  Pass

 34%|███▍      | 261/765 [05:25<09:25,  1.12s/it]

[261/765]  raw='pass.'  →  Pass

 34%|███▍      | 262/765 [05:26<10:19,  1.23s/it]

[262/765]  raw='pass.'  →  Pass

 34%|███▍      | 263/765 [05:28<10:47,  1.29s/it]

[263/765]  raw='pass.'  →  Pass

 35%|███▍      | 264/765 [05:29<10:11,  1.22s/it]

[264/765]  raw='pass.

prom'  →  Pass

 35%|███▍      | 265/765 [05:30<11:01,  1.32s/it]

[265/765]  raw='pass.'  →  Pass

 35%|███▍      | 266/765 [05:31<10:31,  1.26s/it]

[266/765]  raw='pass.'  →  Pass

 35%|███▍      | 267/765 [05:33<11:50,  1.43s/it]

[267/765]  raw='pass.'  →  Pass

 35%|███▌      | 268/765 [05:34<11:09,  1.35s/it]

[268/765]  raw='pass.'  →  Pass

 35%|███▌      | 269/765 [05:35<10:36,  1.28s/it]

[269/765]  raw='pass.'  →  Pass

 35%|███▌      | 270/765 [05:36<09:30,  1.15s/it]

[270/765]  raw='pass.'  →  Pass

 35%|███▌      | 271/765 [05:37<08:58,  1.09s/it]

[271/765]  raw='pass.'  →  Pass

 36%|███▌      | 272/765 [05:39<09:38,  1.17s/it]

[272/765]  raw='pass.'  →  Pass

 36%|███▌      | 273/765 [05:39<08:49,  1.08s/it]

[273/765]  raw='pass.'  →  Pass

 36%|███▌      | 274/765 [05:41<09:01,  1.10s/it]

[274/765]  raw='pass.'  →  Pass

 36%|███▌      | 275/765 [05:42<10:45,  1.32s/it]

[275/765]  raw='pass.'  →  Pass

 36%|███▌      | 276/765 [05:43<09:49,  1.21s/it]

[276/765]  raw='fail.'  →  Fail

 36%|███▌      | 277/765 [05:45<10:25,  1.28s/it]

[277/765]  raw='pass.

ex'  →  Pass

 36%|███▋      | 278/765 [05:46<09:35,  1.18s/it]

[278/765]  raw='pass.'  →  Pass

 36%|███▋      | 279/765 [05:47<10:23,  1.28s/it]

[279/765]  raw='pass.

ex'  →  Pass

 37%|███▋      | 280/765 [05:48<09:25,  1.17s/it]

[280/765]  raw='fail.'  →  Fail

 37%|███▋      | 281/765 [05:50<10:49,  1.34s/it]

[281/765]  raw='pass.'  →  Pass

 37%|███▋      | 282/765 [05:51<09:52,  1.23s/it]

[282/765]  raw='pass.'  →  Pass

 37%|███▋      | 283/765 [05:52<10:23,  1.29s/it]

[283/765]  raw='pass.'  →  Pass

 37%|███▋      | 284/765 [05:53<09:59,  1.25s/it]

[284/765]  raw='pass.'  →  Pass

 37%|███▋      | 285/765 [05:55<09:44,  1.22s/it]

[285/765]  raw='prompt name: does'  →  ???

 37%|███▋      | 286/765 [05:56<09:49,  1.23s/it]

[286/765]  raw='pass.'  →  Pass

 38%|███▊      | 287/765 [05:57<09:25,  1.18s/it]

[287/765]  raw='pass.'  →  Pass

 38%|███▊      | 288/765 [05:58<09:23,  1.18s/it]

[288/765]  raw='pass.'  →  Pass

 38%|███▊      | 289/765 [05:59<08:50,  1.11s/it]

[289/765]  raw='pass.'  →  Pass

 38%|███▊      | 290/765 [06:00<08:49,  1.11s/it]

[290/765]  raw='fail.'  →  Fail

 38%|███▊      | 291/765 [06:01<08:28,  1.07s/it]

[291/765]  raw='pass.'  →  Pass

 38%|███▊      | 292/765 [06:02<08:35,  1.09s/it]

[292/765]  raw='pass.

ex'  →  Pass

 38%|███▊      | 293/765 [06:04<09:25,  1.20s/it]

[293/765]  raw='pass.'  →  Pass

 38%|███▊      | 294/765 [06:06<10:51,  1.38s/it]

[294/765]  raw='pass.'  →  Pass

 39%|███▊      | 295/765 [06:07<09:46,  1.25s/it]

[295/765]  raw='pass.'  →  Pass

 39%|███▊      | 296/765 [06:08<10:00,  1.28s/it]

[296/765]  raw='pass.'  →  Pass

 39%|███▉      | 297/765 [06:09<09:44,  1.25s/it]

[297/765]  raw='pass.'  →  Pass

 39%|███▉      | 298/765 [06:10<10:06,  1.30s/it]

[298/765]  raw='fail.'  →  Fail

 39%|███▉      | 299/765 [06:12<11:17,  1.45s/it]

[299/765]  raw='pass.'  →  Pass

 39%|███▉      | 300/765 [06:13<09:52,  1.28s/it]

[300/765]  raw='pass.'  →  Pass

 39%|███▉      | 301/765 [06:14<08:56,  1.16s/it]

[301/765]  raw='pass.'  →  Pass

 39%|███▉      | 302/765 [06:15<09:13,  1.20s/it]

[302/765]  raw='fail.'  →  Fail

 40%|███▉      | 303/765 [06:17<11:06,  1.44s/it]

[303/765]  raw='pass.'  →  Pass

 40%|███▉      | 304/765 [06:18<10:08,  1.32s/it]

[304/765]  raw='pass.'  →  Pass

 40%|███▉      | 305/765 [06:19<09:18,  1.21s/it]

[305/765]  raw='pass.'  →  Pass

 40%|████      | 306/765 [06:20<08:58,  1.17s/it]

[306/765]  raw='pass.

ex'  →  Pass

 40%|████      | 307/765 [06:21<08:35,  1.13s/it]

[307/765]  raw='pass.'  →  Pass

 40%|████      | 308/765 [06:22<08:24,  1.10s/it]

[308/765]  raw='pass.'  →  Pass

 40%|████      | 309/765 [06:24<08:46,  1.16s/it]

[309/765]  raw='pass.'  →  Pass

 41%|████      | 310/765 [06:25<08:45,  1.16s/it]

[310/765]  raw='pass.'  →  Pass

 41%|████      | 311/765 [06:26<08:34,  1.13s/it]

[311/765]  raw='pass.'  →  Pass

 41%|████      | 312/765 [06:27<08:11,  1.08s/it]

[312/765]  raw='pass.'  →  Pass

 41%|████      | 313/765 [06:28<07:52,  1.04s/it]

[313/765]  raw='pass.'  →  Pass

 41%|████      | 314/765 [06:29<08:49,  1.17s/it]

[314/765]  raw='pass.'  →  Pass

 41%|████      | 315/765 [06:30<08:02,  1.07s/it]

[315/765]  raw='pass.'  →  Pass

 41%|████▏     | 316/765 [06:31<08:02,  1.08s/it]

[316/765]  raw='pass.'  →  Pass

 41%|████▏     | 317/765 [06:32<08:07,  1.09s/it]

[317/765]  raw='pass.'  →  Pass

 42%|████▏     | 318/765 [06:34<08:14,  1.11s/it]

[318/765]  raw='pass.'  →  Pass

 42%|████▏     | 319/765 [06:35<08:02,  1.08s/it]

[319/765]  raw='pass.'  →  Pass

 42%|████▏     | 320/765 [06:36<08:11,  1.10s/it]

[320/765]  raw='fail.'  →  Fail

 42%|████▏     | 321/765 [06:37<07:48,  1.06s/it]

[321/765]  raw='pass.'  →  Pass

 42%|████▏     | 322/765 [06:38<08:21,  1.13s/it]

[322/765]  raw='prompt name: summer'  →  ???

 42%|████▏     | 323/765 [06:39<08:40,  1.18s/it]

[323/765]  raw='pass.'  →  Pass

 42%|████▏     | 324/765 [06:40<08:11,  1.12s/it]

[324/765]  raw='pass.'  →  Pass

 42%|████▏     | 325/765 [06:41<08:06,  1.11s/it]

[325/765]  raw='pass.'  →  Pass

 43%|████▎     | 326/765 [06:43<09:29,  1.30s/it]

[326/765]  raw='pass.'  →  Pass

 43%|████▎     | 327/765 [06:44<08:59,  1.23s/it]

[327/765]  raw='pass.

ex'  →  Pass

 43%|████▎     | 328/765 [06:46<09:17,  1.28s/it]

[328/765]  raw='pass.'  →  Pass

 43%|████▎     | 329/765 [06:47<08:37,  1.19s/it]

[329/765]  raw='pass.'  →  Pass

 43%|████▎     | 330/765 [06:48<08:50,  1.22s/it]

[330/765]  raw='pass.'  →  Pass

 43%|████▎     | 331/765 [06:49<08:43,  1.21s/it]

[331/765]  raw='pass.

ex'  →  Pass

 43%|████▎     | 332/765 [06:50<08:19,  1.15s/it]

[332/765]  raw='pass.'  →  Pass

 44%|████▎     | 333/765 [06:51<08:10,  1.14s/it]

[333/765]  raw='pass.'  →  Pass

 44%|████▎     | 334/765 [06:52<08:40,  1.21s/it]

[334/765]  raw='pass.'  →  Pass

 44%|████▍     | 335/765 [06:53<08:08,  1.14s/it]

[335/765]  raw='pass.'  →  Pass

 44%|████▍     | 336/765 [06:54<07:40,  1.07s/it]

[336/765]  raw='fail.'  →  Fail

 44%|████▍     | 337/765 [06:56<08:06,  1.14s/it]

[337/765]  raw='pass.'  →  Pass

 44%|████▍     | 338/765 [06:57<08:05,  1.14s/it]

[338/765]  raw='pass.'  →  Pass

 44%|████▍     | 339/765 [06:59<09:30,  1.34s/it]

[339/765]  raw='pass.'  →  Pass

 44%|████▍     | 340/765 [07:00<09:38,  1.36s/it]

[340/765]  raw='pass.'  →  Pass

 45%|████▍     | 341/765 [07:01<09:06,  1.29s/it]

[341/765]  raw='pass.'  →  Pass

 45%|████▍     | 342/765 [07:03<09:23,  1.33s/it]

[342/765]  raw='pass.'  →  Pass

 45%|████▍     | 343/765 [07:04<09:42,  1.38s/it]

[343/765]  raw='pass.'  →  Pass

 45%|████▍     | 344/765 [07:05<09:11,  1.31s/it]

[344/765]  raw='pass.'  →  Pass

 45%|████▌     | 345/765 [07:06<08:42,  1.24s/it]

[345/765]  raw='pass.'  →  Pass

 45%|████▌     | 346/765 [07:08<10:06,  1.45s/it]

[346/765]  raw='fail. the essay presents'  →  Fail

 45%|████▌     | 347/765 [07:09<09:24,  1.35s/it]

[347/765]  raw='pass.'  →  Pass

 45%|████▌     | 348/765 [07:11<09:06,  1.31s/it]

[348/765]  raw='fail.'  →  Fail

 46%|████▌     | 349/765 [07:12<08:26,  1.22s/it]

[349/765]  raw='pass.'  →  Pass

 46%|████▌     | 350/765 [07:12<07:45,  1.12s/it]

[350/765]  raw='pass.'  →  Pass

 46%|████▌     | 351/765 [07:14<07:48,  1.13s/it]

[351/765]  raw='pass.'  →  Pass

 46%|████▌     | 352/765 [07:15<07:48,  1.13s/it]

[352/765]  raw='pass.'  →  Pass

 46%|████▌     | 353/765 [07:16<07:41,  1.12s/it]

[353/765]  raw='pass.'  →  Pass

 46%|████▋     | 354/765 [07:17<07:11,  1.05s/it]

[354/765]  raw='pass.'  →  Pass

 46%|████▋     | 355/765 [07:18<07:22,  1.08s/it]

[355/765]  raw='pass.'  →  Pass

 47%|████▋     | 356/765 [07:19<07:53,  1.16s/it]

[356/765]  raw='pass.'  →  Pass

 47%|████▋     | 357/765 [07:20<07:44,  1.14s/it]

[357/765]  raw='pass.'  →  Pass

 47%|████▋     | 358/765 [07:21<07:41,  1.13s/it]

[358/765]  raw='fail.'  →  Fail

 47%|████▋     | 359/765 [07:23<08:29,  1.25s/it]

[359/765]  raw='pass.'  →  Pass

 47%|████▋     | 360/765 [07:24<08:04,  1.20s/it]

[360/765]  raw='pass.'  →  Pass

 47%|████▋     | 361/765 [07:25<07:33,  1.12s/it]

[361/765]  raw='pass.'  →  Pass

 47%|████▋     | 362/765 [07:27<08:49,  1.31s/it]

[362/765]  raw='pass. the essay presents'  →  Pass

 47%|████▋     | 363/765 [07:28<08:02,  1.20s/it]

[363/765]  raw='pass.'  →  Pass

 48%|████▊     | 364/765 [07:29<08:12,  1.23s/it]

[364/765]  raw='pass.'  →  Pass

 48%|████▊     | 365/765 [07:31<09:08,  1.37s/it]

[365/765]  raw='pass.'  →  Pass

 48%|████▊     | 366/765 [07:32<08:27,  1.27s/it]

[366/765]  raw='fail.

prom'  →  Fail

 48%|████▊     | 367/765 [07:33<08:29,  1.28s/it]

[367/765]  raw='pass.'  →  Pass

 48%|████▊     | 368/765 [07:34<07:36,  1.15s/it]

[368/765]  raw='pass.'  →  Pass

 48%|████▊     | 369/765 [07:35<08:05,  1.23s/it]

[369/765]  raw='pass.'  →  Pass

 48%|████▊     | 370/765 [07:37<08:47,  1.34s/it]

[370/765]  raw='pass.'  →  Pass

 48%|████▊     | 371/765 [07:38<08:25,  1.28s/it]

[371/765]  raw='pass.'  →  Pass

 49%|████▊     | 372/765 [07:39<07:34,  1.16s/it]

[372/765]  raw='fail.'  →  Fail

 49%|████▉     | 373/765 [07:41<08:39,  1.32s/it]

[373/765]  raw='pass.'  →  Pass

 49%|████▉     | 374/765 [07:42<08:17,  1.27s/it]

[374/765]  raw='pass.'  →  Pass

 49%|████▉     | 375/765 [07:43<08:37,  1.33s/it]

[375/765]  raw='pass.

ex'  →  Pass

 49%|████▉     | 376/765 [07:45<08:33,  1.32s/it]

[376/765]  raw='pass.'  →  Pass

 49%|████▉     | 377/765 [07:46<08:32,  1.32s/it]

[377/765]  raw='pass.'  →  Pass

 49%|████▉     | 378/765 [07:48<09:51,  1.53s/it]

[378/765]  raw='pass.

ex'  →  Pass

 50%|████▉     | 379/765 [07:49<08:42,  1.35s/it]

[379/765]  raw='pass.'  →  Pass

 50%|████▉     | 380/765 [07:50<07:45,  1.21s/it]

[380/765]  raw='pass.'  →  Pass

 50%|████▉     | 381/765 [07:51<08:19,  1.30s/it]

[381/765]  raw='pass.'  →  Pass

 50%|████▉     | 382/765 [07:52<07:39,  1.20s/it]

[382/765]  raw='pass.'  →  Pass

 50%|█████     | 383/765 [07:53<07:00,  1.10s/it]

[383/765]  raw='pass.'  →  Pass

 50%|█████     | 384/765 [07:54<07:03,  1.11s/it]

[384/765]  raw='pass.'  →  Pass

 50%|█████     | 385/765 [07:55<06:52,  1.09s/it]

[385/765]  raw='prompt name: how'  →  ???

 50%|█████     | 386/765 [07:57<07:22,  1.17s/it]

[386/765]  raw='fail.'  →  Fail

 51%|█████     | 387/765 [07:58<06:57,  1.11s/it]

[387/765]  raw='pass.'  →  Pass

 51%|█████     | 388/765 [07:59<07:03,  1.12s/it]

[388/765]  raw='pass.'  →  Pass

 51%|█████     | 389/765 [08:00<07:37,  1.22s/it]

[389/765]  raw='pass.'  →  Pass

 51%|█████     | 390/765 [08:01<07:42,  1.23s/it]

[390/765]  raw='pass.'  →  Pass

 51%|█████     | 391/765 [08:02<07:12,  1.16s/it]

[391/765]  raw='pass.'  →  Pass

 51%|█████     | 392/765 [08:03<06:48,  1.10s/it]

[392/765]  raw='fail.'  →  Fail

 51%|█████▏    | 393/765 [08:04<06:46,  1.09s/it]

[393/765]  raw='pass.'  →  Pass

 52%|█████▏    | 394/765 [08:07<09:15,  1.50s/it]

[394/765]  raw='pass.'  →  Pass

 52%|█████▏    | 395/765 [08:08<08:54,  1.45s/it]

[395/765]  raw='pass.'  →  Pass

 52%|█████▏    | 396/765 [08:09<08:13,  1.34s/it]

[396/765]  raw='pass.'  →  Pass

 52%|█████▏    | 397/765 [08:11<08:14,  1.34s/it]

[397/765]  raw='fail.'  →  Fail

 52%|█████▏    | 398/765 [08:12<07:59,  1.31s/it]

[398/765]  raw='pass.'  →  Pass

 52%|█████▏    | 399/765 [08:13<08:13,  1.35s/it]

[399/765]  raw='fail.

ex'  →  Fail

 52%|█████▏    | 400/765 [08:15<08:30,  1.40s/it]

[400/765]  raw='pass.

ex'  →  Pass

 52%|█████▏    | 401/765 [08:16<07:55,  1.31s/it]

[401/765]  raw='pass.'  →  Pass

 53%|█████▎    | 402/765 [08:17<08:14,  1.36s/it]

[402/765]  raw='pass.'  →  Pass

 53%|█████▎    | 403/765 [08:18<07:39,  1.27s/it]

[403/765]  raw='prompt name: how'  →  ???

 53%|█████▎    | 404/765 [08:19<07:04,  1.18s/it]

[404/765]  raw='pass.'  →  Pass

 53%|█████▎    | 405/765 [08:20<06:37,  1.10s/it]

[405/765]  raw='pass.'  →  Pass

 53%|█████▎    | 406/765 [08:21<06:41,  1.12s/it]

[406/765]  raw='fail.'  →  Fail

 53%|█████▎    | 407/765 [08:23<07:50,  1.31s/it]

[407/765]  raw='pass.'  →  Pass

 53%|█████▎    | 408/765 [08:24<07:17,  1.22s/it]

[408/765]  raw='pass.'  →  Pass

 53%|█████▎    | 409/765 [08:25<06:58,  1.17s/it]

[409/765]  raw='pass.'  →  Pass

 54%|█████▎    | 410/765 [08:26<06:35,  1.11s/it]

[410/765]  raw='pass.'  →  Pass

 54%|█████▎    | 411/765 [08:27<06:09,  1.04s/it]

[411/765]  raw='pass.'  →  Pass

 54%|█████▍    | 412/765 [08:29<07:05,  1.21s/it]

[412/765]  raw='pass.'  →  Pass

 54%|█████▍    | 413/765 [08:30<07:30,  1.28s/it]

[413/765]  raw='pass.'  →  Pass

 54%|█████▍    | 414/765 [08:32<07:50,  1.34s/it]

[414/765]  raw='pass.'  →  Pass

 54%|█████▍    | 415/765 [08:33<07:03,  1.21s/it]

[415/765]  raw='pass.'  →  Pass

 54%|█████▍    | 416/765 [08:33<06:29,  1.12s/it]

[416/765]  raw='pass.'  →  Pass

 55%|█████▍    | 417/765 [08:35<06:20,  1.09s/it]

[417/765]  raw='pass.

prom'  →  Pass

 55%|█████▍    | 418/765 [08:36<06:09,  1.07s/it]

[418/765]  raw='pass.'  →  Pass

 55%|█████▍    | 419/765 [08:37<06:38,  1.15s/it]

[419/765]  raw='pass.'  →  Pass

 55%|█████▍    | 420/765 [08:38<07:19,  1.27s/it]

[420/765]  raw='prompt name: ph'  →  ???

 55%|█████▌    | 421/765 [08:39<06:44,  1.17s/it]

[421/765]  raw='pass.'  →  Pass

 55%|█████▌    | 422/765 [08:41<07:43,  1.35s/it]

[422/765]  raw='pass.'  →  Pass

 55%|█████▌    | 423/765 [08:43<07:58,  1.40s/it]

[423/765]  raw='pass.'  →  Pass

 55%|█████▌    | 424/765 [08:43<07:00,  1.23s/it]

[424/765]  raw='pass.'  →  Pass

 56%|█████▌    | 425/765 [08:45<07:08,  1.26s/it]

[425/765]  raw='pass.

ex'  →  Pass

 56%|█████▌    | 426/765 [08:46<07:48,  1.38s/it]

[426/765]  raw='fail.

ex'  →  Fail

 56%|█████▌    | 427/765 [08:49<09:29,  1.68s/it]

[427/765]  raw='pass.'  →  Pass

 56%|█████▌    | 428/765 [08:50<08:11,  1.46s/it]

[428/765]  raw='pass.'  →  Pass

 56%|█████▌    | 429/765 [08:51<07:56,  1.42s/it]

[429/765]  raw='pass.'  →  Pass

 56%|█████▌    | 430/765 [08:52<07:43,  1.38s/it]

[430/765]  raw='pass.'  →  Pass

 56%|█████▋    | 431/765 [08:54<07:33,  1.36s/it]

[431/765]  raw='pass.'  →  Pass

 56%|█████▋    | 432/765 [08:55<07:12,  1.30s/it]

[432/765]  raw='pass.'  →  Pass

 57%|█████▋    | 433/765 [08:56<07:15,  1.31s/it]

[433/765]  raw='fail.

ex'  →  Fail

 57%|█████▋    | 434/765 [08:57<06:31,  1.18s/it]

[434/765]  raw='pass.'  →  Pass

 57%|█████▋    | 435/765 [08:58<06:01,  1.09s/it]

[435/765]  raw='pass.'  →  Pass

 57%|█████▋    | 436/765 [08:59<05:59,  1.09s/it]

[436/765]  raw='pass.'  →  Pass

 57%|█████▋    | 437/765 [09:00<05:45,  1.05s/it]

[437/765]  raw='fail.'  →  Fail

 57%|█████▋    | 438/765 [09:01<05:25,  1.00it/s]

[438/765]  raw='pass.'  →  Pass

 57%|█████▋    | 439/765 [09:02<05:44,  1.06s/it]

[439/765]  raw='pass.'  →  Pass

 58%|█████▊    | 440/765 [09:03<05:46,  1.07s/it]

[440/765]  raw='pass.'  →  Pass

 58%|█████▊    | 441/765 [09:05<06:12,  1.15s/it]

[441/765]  raw='pass.

ex'  →  Pass

 58%|█████▊    | 442/765 [09:06<05:54,  1.10s/it]

[442/765]  raw='pass.'  →  Pass

 58%|█████▊    | 443/765 [09:06<05:29,  1.02s/it]

[443/765]  raw='pass.'  →  Pass

 58%|█████▊    | 444/765 [09:07<05:15,  1.02it/s]

[444/765]  raw='pass.'  →  Pass

 58%|█████▊    | 445/765 [09:09<05:49,  1.09s/it]

[445/765]  raw='pass.'  →  Pass

 58%|█████▊    | 446/765 [09:10<05:38,  1.06s/it]

[446/765]  raw='pass.'  →  Pass

 58%|█████▊    | 447/765 [09:11<05:59,  1.13s/it]

[447/765]  raw='pass.'  →  Pass

 59%|█████▊    | 448/765 [09:12<05:46,  1.09s/it]

[448/765]  raw='pass.'  →  Pass

 59%|█████▊    | 449/765 [09:13<05:37,  1.07s/it]

[449/765]  raw='pass.'  →  Pass

 59%|█████▉    | 450/765 [09:14<06:06,  1.16s/it]

[450/765]  raw='fail.'  →  Fail

 59%|█████▉    | 451/765 [09:15<05:44,  1.10s/it]

[451/765]  raw='pass.'  →  Pass

 59%|█████▉    | 452/765 [09:16<05:23,  1.04s/it]

[452/765]  raw='pass.'  →  Pass

 59%|█████▉    | 453/765 [09:17<05:33,  1.07s/it]

[453/765]  raw='pass.'  →  Pass

 59%|█████▉    | 454/765 [09:18<05:39,  1.09s/it]

[454/765]  raw='prompt name: does'  →  ???

 59%|█████▉    | 455/765 [09:20<06:02,  1.17s/it]

[455/765]  raw='fail.'  →  Fail

 60%|█████▉    | 456/765 [09:21<05:53,  1.14s/it]

[456/765]  raw='pass.'  →  Pass

 60%|█████▉    | 457/765 [09:22<06:06,  1.19s/it]

[457/765]  raw='fail.'  →  Fail

 60%|█████▉    | 458/765 [09:23<05:46,  1.13s/it]

[458/765]  raw='pass.'  →  Pass

 60%|██████    | 459/765 [09:24<05:29,  1.08s/it]

[459/765]  raw='pass.'  →  Pass

 60%|██████    | 460/765 [09:25<05:06,  1.01s/it]

[460/765]  raw='pass.'  →  Pass

 60%|██████    | 461/765 [09:26<05:52,  1.16s/it]

[461/765]  raw='fail.'  →  Fail

 60%|██████    | 462/765 [09:28<06:21,  1.26s/it]

[462/765]  raw='fail.'  →  Fail

 61%|██████    | 463/765 [09:29<05:41,  1.13s/it]

[463/765]  raw='pass.'  →  Pass

 61%|██████    | 464/765 [09:30<05:27,  1.09s/it]

[464/765]  raw='pass.'  →  Pass

 61%|██████    | 465/765 [09:31<05:44,  1.15s/it]

[465/765]  raw='fail.'  →  Fail

 61%|██████    | 466/765 [09:32<05:25,  1.09s/it]

[466/765]  raw='pass.'  →  Pass

 61%|██████    | 467/765 [09:33<05:29,  1.10s/it]

[467/765]  raw='pass.'  →  Pass

 61%|██████    | 468/765 [09:34<05:50,  1.18s/it]

[468/765]  raw='pass.

ex'  →  Pass

 61%|██████▏   | 469/765 [09:35<05:31,  1.12s/it]

[469/765]  raw='pass.'  →  Pass

 61%|██████▏   | 470/765 [09:37<06:35,  1.34s/it]

[470/765]  raw='fail.

ex'  →  Fail

 62%|██████▏   | 471/765 [09:38<06:02,  1.23s/it]

[471/765]  raw='pass.'  →  Pass

 62%|██████▏   | 472/765 [09:39<05:57,  1.22s/it]

[472/765]  raw='pass.

ex'  →  Pass

 62%|██████▏   | 473/765 [09:40<05:36,  1.15s/it]

[473/765]  raw='pass.'  →  Pass

 62%|██████▏   | 474/765 [09:41<05:21,  1.10s/it]

[474/765]  raw='pass.'  →  Pass

 62%|██████▏   | 475/765 [09:43<05:20,  1.10s/it]

[475/765]  raw='pass.'  →  Pass

 62%|██████▏   | 476/765 [09:44<05:12,  1.08s/it]

[476/765]  raw='pass.'  →  Pass

 62%|██████▏   | 477/765 [09:47<08:12,  1.71s/it]

[477/765]  raw='pass.

ex'  →  Pass

 62%|██████▏   | 478/765 [09:48<06:55,  1.45s/it]

[478/765]  raw='pass.'  →  Pass

 63%|██████▎   | 479/765 [09:49<06:28,  1.36s/it]

[479/765]  raw='pass.'  →  Pass

 63%|██████▎   | 480/765 [09:50<06:25,  1.35s/it]

[480/765]  raw='pass.'  →  Pass

 63%|██████▎   | 481/765 [09:51<06:26,  1.36s/it]

[481/765]  raw='pass.'  →  Pass

 63%|██████▎   | 482/765 [09:52<05:55,  1.25s/it]

[482/765]  raw='pass.'  →  Pass

 63%|██████▎   | 483/765 [09:53<05:20,  1.14s/it]

[483/765]  raw='pass.'  →  Pass

 63%|██████▎   | 484/765 [09:54<05:17,  1.13s/it]

[484/765]  raw='fail.'  →  Fail

 63%|██████▎   | 485/765 [09:56<05:14,  1.12s/it]

[485/765]  raw='pass.'  →  Pass

 64%|██████▎   | 486/765 [09:57<05:45,  1.24s/it]

[486/765]  raw='pass.'  →  Pass

 64%|██████▎   | 487/765 [09:58<05:10,  1.12s/it]

[487/765]  raw='pass.'  →  Pass

 64%|██████▍   | 488/765 [09:59<05:29,  1.19s/it]

[488/765]  raw='pass.'  →  Pass

 64%|██████▍   | 489/765 [10:00<05:21,  1.17s/it]

[489/765]  raw='pass.'  →  Pass

 64%|██████▍   | 490/765 [10:02<05:35,  1.22s/it]

[490/765]  raw='pass.'  →  Pass

 64%|██████▍   | 491/765 [10:03<05:31,  1.21s/it]

[491/765]  raw='pass.'  →  Pass

 64%|██████▍   | 492/765 [10:04<05:30,  1.21s/it]

[492/765]  raw='pass.'  →  Pass

 64%|██████▍   | 493/765 [10:05<05:40,  1.25s/it]

[493/765]  raw='fail.

ex'  →  Fail

 65%|██████▍   | 494/765 [10:07<05:46,  1.28s/it]

[494/765]  raw='pass.'  →  Pass

 65%|██████▍   | 495/765 [10:08<05:20,  1.19s/it]

[495/765]  raw='pass.'  →  Pass

 65%|██████▍   | 496/765 [10:09<05:16,  1.18s/it]

[496/765]  raw='pass.'  →  Pass

 65%|██████▍   | 497/765 [10:10<05:26,  1.22s/it]

[497/765]  raw='fail.

ex'  →  Fail

 65%|██████▌   | 498/765 [10:11<05:20,  1.20s/it]

[498/765]  raw='pass.'  →  Pass

 65%|██████▌   | 499/765 [10:13<05:28,  1.24s/it]

[499/765]  raw='pass.'  →  Pass

 65%|██████▌   | 500/765 [10:14<05:04,  1.15s/it]

[500/765]  raw='pass.'  →  Pass

 65%|██████▌   | 501/765 [10:15<04:57,  1.13s/it]

[501/765]  raw='pass.'  →  Pass

 66%|██████▌   | 502/765 [10:16<05:04,  1.16s/it]

[502/765]  raw='pass.'  →  Pass

 66%|██████▌   | 503/765 [10:17<05:15,  1.20s/it]

[503/765]  raw='pass.'  →  Pass

 66%|██████▌   | 504/765 [10:18<04:59,  1.15s/it]

[504/765]  raw='fail.'  →  Fail

 66%|██████▌   | 505/765 [10:19<04:34,  1.06s/it]

[505/765]  raw='pass.'  →  Pass

 66%|██████▌   | 506/765 [10:20<04:16,  1.01it/s]

[506/765]  raw='pass.'  →  Pass

 66%|██████▋   | 507/765 [10:21<04:30,  1.05s/it]

[507/765]  raw='pass. the essay demonstr'  →  Pass

 66%|██████▋   | 508/765 [10:23<04:58,  1.16s/it]

[508/765]  raw='pass.'  →  Pass

 67%|██████▋   | 509/765 [10:24<05:18,  1.24s/it]

[509/765]  raw='pass.'  →  Pass

 67%|██████▋   | 510/765 [10:25<04:53,  1.15s/it]

[510/765]  raw='pass.'  →  Pass

 67%|██████▋   | 511/765 [10:27<05:42,  1.35s/it]

[511/765]  raw='fail.

ex'  →  Fail

 67%|██████▋   | 512/765 [10:28<05:38,  1.34s/it]

[512/765]  raw='pass.'  →  Pass

 67%|██████▋   | 513/765 [10:29<05:21,  1.28s/it]

[513/765]  raw='pass.'  →  Pass

 67%|██████▋   | 514/765 [10:30<04:58,  1.19s/it]

[514/765]  raw='pass.'  →  Pass

 67%|██████▋   | 515/765 [10:31<04:54,  1.18s/it]

[515/765]  raw='pass.'  →  Pass

 67%|██████▋   | 516/765 [10:33<05:32,  1.34s/it]

[516/765]  raw='pass.'  →  Pass

 68%|██████▊   | 517/765 [10:34<04:56,  1.19s/it]

[517/765]  raw='pass.'  →  Pass

 68%|██████▊   | 518/765 [10:35<05:05,  1.23s/it]

[518/765]  raw='pass.'  →  Pass

 68%|██████▊   | 519/765 [10:36<04:52,  1.19s/it]

[519/765]  raw='pass.'  →  Pass

 68%|██████▊   | 520/765 [10:38<04:57,  1.22s/it]

[520/765]  raw='pass.'  →  Pass

 68%|██████▊   | 521/765 [10:39<05:16,  1.30s/it]

[521/765]  raw='pass.'  →  Pass

 68%|██████▊   | 522/765 [10:40<04:46,  1.18s/it]

[522/765]  raw='pass.'  →  Pass

 68%|██████▊   | 523/765 [10:41<04:58,  1.23s/it]

[523/765]  raw='pass.

ex'  →  Pass

 68%|██████▊   | 524/765 [10:42<04:47,  1.19s/it]

[524/765]  raw='pass.'  →  Pass

 69%|██████▊   | 525/765 [10:44<05:32,  1.39s/it]

[525/765]  raw='pass.'  →  Pass

 69%|██████▉   | 526/765 [10:45<05:03,  1.27s/it]

[526/765]  raw='pass.'  →  Pass

 69%|██████▉   | 527/765 [10:46<04:33,  1.15s/it]

[527/765]  raw='fail.'  →  Fail

 69%|██████▉   | 528/765 [10:47<04:42,  1.19s/it]

[528/765]  raw='fail.'  →  Fail

 69%|██████▉   | 529/765 [10:48<04:24,  1.12s/it]

[529/765]  raw='pass.'  →  Pass

 69%|██████▉   | 530/765 [10:50<04:26,  1.13s/it]

[530/765]  raw='pass (proficient)'  →  Pass

 69%|██████▉   | 531/765 [10:51<04:21,  1.12s/it]

[531/765]  raw='fail. distracted'  →  Fail

 70%|██████▉   | 532/765 [10:52<04:14,  1.09s/it]

[532/765]  raw='pass.'  →  Pass

 70%|██████▉   | 533/765 [10:53<04:17,  1.11s/it]

[533/765]  raw='pass.'  →  Pass

 70%|██████▉   | 534/765 [10:54<04:38,  1.21s/it]

[534/765]  raw='pass.'  →  Pass

 70%|██████▉   | 535/765 [10:56<04:44,  1.24s/it]

[535/765]  raw='pass.'  →  Pass

 70%|███████   | 536/765 [10:57<04:37,  1.21s/it]

[536/765]  raw='pass.'  →  Pass

 70%|███████   | 537/765 [10:58<04:34,  1.21s/it]

[537/765]  raw='pass.

ex'  →  Pass

 70%|███████   | 538/765 [10:59<04:10,  1.11s/it]

[538/765]  raw='pass.'  →  Pass

 70%|███████   | 539/765 [11:05<10:07,  2.69s/it]

[539/765]  raw='pass.'  →  Pass

 71%|███████   | 540/765 [11:07<08:33,  2.28s/it]

[540/765]  raw='pass.'  →  Pass

 71%|███████   | 541/765 [11:08<07:15,  1.94s/it]

[541/765]  raw='pass.'  →  Pass

 71%|███████   | 542/765 [11:09<06:32,  1.76s/it]

[542/765]  raw='pass.'  →  Pass

 71%|███████   | 543/765 [11:11<06:13,  1.68s/it]

[543/765]  raw='fail.'  →  Fail

 71%|███████   | 544/765 [11:12<05:35,  1.52s/it]

[544/765]  raw='pass.'  →  Pass

 71%|███████   | 545/765 [11:13<05:08,  1.40s/it]

[545/765]  raw='pass.'  →  Pass

 71%|███████▏  | 546/765 [11:14<05:00,  1.37s/it]

[546/765]  raw='prompt name: does'  →  ???

 72%|███████▏  | 547/765 [11:15<04:32,  1.25s/it]

[547/765]  raw='pass.'  →  Pass

 72%|███████▏  | 548/765 [11:17<05:06,  1.41s/it]

[548/765]  raw='pass.'  →  Pass

 72%|███████▏  | 549/765 [11:18<05:07,  1.42s/it]

[549/765]  raw='fail.

e'  →  Fail

 72%|███████▏  | 550/765 [11:19<04:47,  1.34s/it]

[550/765]  raw='pass.'  →  Pass

 72%|███████▏  | 551/765 [11:20<04:21,  1.22s/it]

[551/765]  raw='pass.'  →  Pass

 72%|███████▏  | 552/765 [11:21<03:55,  1.11s/it]

[552/765]  raw='pass.'  →  Pass

 72%|███████▏  | 553/765 [11:22<04:05,  1.16s/it]

[553/765]  raw='fail.'  →  Fail

 72%|███████▏  | 554/765 [11:24<04:12,  1.20s/it]

[554/765]  raw='pass.'  →  Pass

 73%|███████▎  | 555/765 [11:25<04:08,  1.19s/it]

[555/765]  raw='pass.'  →  Pass

 73%|███████▎  | 556/765 [11:27<04:35,  1.32s/it]

[556/765]  raw='fail. the essay presents'  →  Fail

 73%|███████▎  | 557/765 [11:28<04:43,  1.36s/it]

[557/765]  raw='pass.'  →  Pass

 73%|███████▎  | 558/765 [11:29<04:23,  1.27s/it]

[558/765]  raw='pass.'  →  Pass

 73%|███████▎  | 559/765 [11:31<04:32,  1.32s/it]

[559/765]  raw='pass.'  →  Pass

 73%|███████▎  | 560/765 [11:32<04:21,  1.28s/it]

[560/765]  raw='pass.'  →  Pass

 73%|███████▎  | 561/765 [11:33<04:34,  1.35s/it]

[561/765]  raw='pass.'  →  Pass

 73%|███████▎  | 562/765 [11:34<04:12,  1.24s/it]

[562/765]  raw='pass.'  →  Pass

 74%|███████▎  | 563/765 [11:35<04:03,  1.21s/it]

[563/765]  raw='pass.'  →  Pass

 74%|███████▎  | 564/765 [11:36<03:41,  1.10s/it]

[564/765]  raw='pass.'  →  Pass

 74%|███████▍  | 565/765 [11:38<04:01,  1.21s/it]

[565/765]  raw='fail.'  →  Fail

 74%|███████▍  | 566/765 [11:39<04:06,  1.24s/it]

[566/765]  raw='fail.'  →  Fail

 74%|███████▍  | 567/765 [11:40<04:10,  1.27s/it]

[567/765]  raw='pass.'  →  Pass

 74%|███████▍  | 568/765 [11:42<04:27,  1.36s/it]

[568/765]  raw='pass.'  →  Pass

 74%|███████▍  | 569/765 [11:43<04:11,  1.29s/it]

[569/765]  raw='pass.

prom'  →  Pass

 75%|███████▍  | 570/765 [11:44<04:06,  1.26s/it]

[570/765]  raw='fail. while the essay'  →  Fail

 75%|███████▍  | 571/765 [11:45<04:00,  1.24s/it]

[571/765]  raw='pass (with conditions):'  →  Pass

 75%|███████▍  | 572/765 [11:47<03:56,  1.22s/it]

[572/765]  raw='pass.'  →  Pass

 75%|███████▍  | 573/765 [11:48<03:52,  1.21s/it]

[573/765]  raw='pass.'  →  Pass

 75%|███████▌  | 574/765 [11:49<04:05,  1.29s/it]

[574/765]  raw='pass.'  →  Pass

 75%|███████▌  | 575/765 [11:50<03:55,  1.24s/it]

[575/765]  raw='pass.'  →  Pass

 75%|███████▌  | 576/765 [11:52<04:05,  1.30s/it]

[576/765]  raw='pass.'  →  Pass

 75%|███████▌  | 577/765 [11:53<03:41,  1.18s/it]

[577/765]  raw='pass.'  →  Pass

 76%|███████▌  | 578/765 [11:54<03:44,  1.20s/it]

[578/765]  raw='pass.

ex'  →  Pass

 76%|███████▌  | 579/765 [11:55<03:41,  1.19s/it]

[579/765]  raw='pass.'  →  Pass

 76%|███████▌  | 580/765 [11:56<03:39,  1.19s/it]

[580/765]  raw='pass.'  →  Pass

 76%|███████▌  | 581/765 [11:57<03:25,  1.12s/it]

[581/765]  raw='pass.'  →  Pass

 76%|███████▌  | 582/765 [11:58<03:24,  1.12s/it]

[582/765]  raw='pass.'  →  Pass

 76%|███████▌  | 583/765 [11:59<03:24,  1.12s/it]

[583/765]  raw='pass.

ex'  →  Pass

 76%|███████▋  | 584/765 [12:01<03:42,  1.23s/it]

[584/765]  raw='pass.'  →  Pass

 76%|███████▋  | 585/765 [12:02<03:55,  1.31s/it]

[585/765]  raw='pass.'  →  Pass

 77%|███████▋  | 586/765 [12:04<03:44,  1.26s/it]

[586/765]  raw='pass.'  →  Pass

 77%|███████▋  | 587/765 [12:05<03:30,  1.18s/it]

[587/765]  raw='pass.'  →  Pass

 77%|███████▋  | 588/765 [12:06<03:21,  1.14s/it]

[588/765]  raw='pass.'  →  Pass

 77%|███████▋  | 589/765 [12:07<03:25,  1.17s/it]

[589/765]  raw='pass.'  →  Pass

 77%|███████▋  | 590/765 [12:08<03:08,  1.07s/it]

[590/765]  raw='pass.'  →  Pass

 77%|███████▋  | 591/765 [12:09<02:59,  1.03s/it]

[591/765]  raw='pass.'  →  Pass

 77%|███████▋  | 592/765 [12:10<02:54,  1.01s/it]

[592/765]  raw='pass.'  →  Pass

 78%|███████▊  | 593/765 [12:11<02:47,  1.03it/s]

[593/765]  raw='pass.'  →  Pass

 78%|███████▊  | 594/765 [12:12<02:53,  1.02s/it]

[594/765]  raw='pass.'  →  Pass

 78%|███████▊  | 595/765 [12:13<03:10,  1.12s/it]

[595/765]  raw='pass.'  →  Pass

 78%|███████▊  | 596/765 [12:15<04:10,  1.48s/it]

[596/765]  raw='pass.'  →  Pass

 78%|███████▊  | 597/765 [12:17<04:07,  1.47s/it]

[597/765]  raw='pass.'  →  Pass

 78%|███████▊  | 598/765 [12:18<03:51,  1.38s/it]

[598/765]  raw='pass.'  →  Pass

 78%|███████▊  | 599/765 [12:19<03:51,  1.39s/it]

[599/765]  raw='pass.'  →  Pass

 78%|███████▊  | 600/765 [12:20<03:24,  1.24s/it]

[600/765]  raw='pass.'  →  Pass

 79%|███████▊  | 601/765 [12:21<03:11,  1.17s/it]

[601/765]  raw='pass.'  →  Pass

 79%|███████▊  | 602/765 [12:23<03:25,  1.26s/it]

[602/765]  raw='pass.'  →  Pass

 79%|███████▉  | 603/765 [12:24<03:43,  1.38s/it]

[603/765]  raw='prompt name: car'  →  ???

 79%|███████▉  | 604/765 [12:26<03:40,  1.37s/it]

[604/765]  raw='fail. community service should'  →  Fail

 79%|███████▉  | 605/765 [12:27<03:39,  1.37s/it]

[605/765]  raw='pass.'  →  Pass

 79%|███████▉  | 606/765 [12:28<03:15,  1.23s/it]

[606/765]  raw='pass.'  →  Pass

 79%|███████▉  | 607/765 [12:29<03:10,  1.20s/it]

[607/765]  raw='pass.'  →  Pass

 79%|███████▉  | 608/765 [12:31<03:30,  1.34s/it]

[608/765]  raw='fail.'  →  Fail

 80%|███████▉  | 609/765 [12:32<03:22,  1.30s/it]

[609/765]  raw='pass.'  →  Pass

 80%|███████▉  | 610/765 [12:33<03:15,  1.26s/it]

[610/765]  raw='pass.'  →  Pass

 80%|███████▉  | 611/765 [12:35<03:23,  1.32s/it]

[611/765]  raw='pass.'  →  Pass

 80%|████████  | 612/765 [12:36<03:11,  1.25s/it]

[612/765]  raw='fail.'  →  Fail

 80%|████████  | 613/765 [12:37<03:11,  1.26s/it]

[613/765]  raw='pass.'  →  Pass

 80%|████████  | 614/765 [12:38<03:02,  1.21s/it]

[614/765]  raw='pass.'  →  Pass

 80%|████████  | 615/765 [12:39<02:45,  1.10s/it]

[615/765]  raw='pass.'  →  Pass

 81%|████████  | 616/765 [12:40<02:43,  1.10s/it]

[616/765]  raw='pass.'  →  Pass

 81%|████████  | 617/765 [12:41<02:31,  1.02s/it]

[617/765]  raw='pass.'  →  Pass

 81%|████████  | 618/765 [12:42<02:28,  1.01s/it]

[618/765]  raw='pass.'  →  Pass

 81%|████████  | 619/765 [12:43<02:24,  1.01it/s]

[619/765]  raw='pass.'  →  Pass

 81%|████████  | 620/765 [12:44<02:43,  1.13s/it]

[620/765]  raw='pass.'  →  Pass

 81%|████████  | 621/765 [12:46<03:11,  1.33s/it]

[621/765]  raw='pass.'  →  Pass

 81%|████████▏ | 622/765 [12:48<03:18,  1.39s/it]

[622/765]  raw='pass.'  →  Pass

 81%|████████▏ | 623/765 [12:49<03:07,  1.32s/it]

[623/765]  raw='pass.'  →  Pass

 82%|████████▏ | 624/765 [12:50<03:04,  1.31s/it]

[624/765]  raw='pass.'  →  Pass

 82%|████████▏ | 625/765 [12:51<02:43,  1.17s/it]

[625/765]  raw='pass.'  →  Pass

 82%|████████▏ | 626/765 [12:52<02:29,  1.07s/it]

[626/765]  raw='pass.'  →  Pass

 82%|████████▏ | 627/765 [12:53<02:29,  1.09s/it]

[627/765]  raw='pass.'  →  Pass

 82%|████████▏ | 628/765 [12:54<02:43,  1.19s/it]

[628/765]  raw='pass.'  →  Pass

 82%|████████▏ | 629/765 [12:55<02:41,  1.19s/it]

[629/765]  raw='pass.'  →  Pass

 82%|████████▏ | 630/765 [12:57<03:00,  1.34s/it]

[630/765]  raw='pass.'  →  Pass

 82%|████████▏ | 631/765 [13:00<03:52,  1.73s/it]

[631/765]  raw='fail. the essay does'  →  Fail

 83%|████████▎ | 632/765 [13:01<03:25,  1.54s/it]

[632/765]  raw='pass.'  →  Pass

 83%|████████▎ | 633/765 [13:03<03:33,  1.62s/it]

[633/765]  raw='pass: proficient.'  →  Pass

 83%|████████▎ | 634/765 [13:04<03:18,  1.51s/it]

[634/765]  raw='pass.'  →  Pass

 83%|████████▎ | 635/765 [13:05<03:02,  1.41s/it]

[635/765]  raw='pass.'  →  Pass

 83%|████████▎ | 636/765 [13:07<03:03,  1.42s/it]

[636/765]  raw='pass.'  →  Pass

 83%|████████▎ | 637/765 [13:08<03:04,  1.44s/it]

[637/765]  raw='pass.'  →  Pass

 83%|████████▎ | 638/765 [13:09<02:51,  1.35s/it]

[638/765]  raw='pass.'  →  Pass

 84%|████████▎ | 639/765 [13:10<02:42,  1.29s/it]

[639/765]  raw='prompt name: gr'  →  ???

 84%|████████▎ | 640/765 [13:11<02:33,  1.23s/it]

[640/765]  raw='pass.'  →  Pass

 84%|████████▍ | 641/765 [13:12<02:23,  1.16s/it]

[641/765]  raw='pass.'  →  Pass

 84%|████████▍ | 642/765 [13:14<02:46,  1.36s/it]

[642/765]  raw='pass.'  →  Pass

 84%|████████▍ | 643/765 [13:15<02:30,  1.24s/it]

[643/765]  raw='pass.'  →  Pass

 84%|████████▍ | 644/765 [13:16<02:20,  1.16s/it]

[644/765]  raw='pass.'  →  Pass

 84%|████████▍ | 645/765 [13:17<02:09,  1.08s/it]

[645/765]  raw='pass.'  →  Pass

 84%|████████▍ | 646/765 [13:19<02:27,  1.24s/it]

[646/765]  raw='pass.'  →  Pass

 85%|████████▍ | 647/765 [13:20<02:45,  1.40s/it]

[647/765]  raw='pass.'  →  Pass

 85%|████████▍ | 648/765 [13:22<02:40,  1.37s/it]

[648/765]  raw='pass.'  →  Pass

 85%|████████▍ | 649/765 [13:23<02:32,  1.32s/it]

[649/765]  raw='pass.

e'  →  Pass

 85%|████████▍ | 650/765 [13:24<02:31,  1.32s/it]

[650/765]  raw='fail.'  →  Fail

 85%|████████▌ | 651/765 [13:25<02:17,  1.21s/it]

[651/765]  raw='pass.'  →  Pass

 85%|████████▌ | 652/765 [13:26<02:04,  1.10s/it]

[652/765]  raw='fail.'  →  Fail

 85%|████████▌ | 653/765 [13:27<02:10,  1.16s/it]

[653/765]  raw='fail.'  →  Fail

 85%|████████▌ | 654/765 [13:29<02:08,  1.16s/it]

[654/765]  raw='fail.'  →  Fail

 86%|████████▌ | 655/765 [13:30<02:06,  1.15s/it]

[655/765]  raw='pass.'  →  Pass

 86%|████████▌ | 656/765 [13:31<01:58,  1.09s/it]

[656/765]  raw='pass.'  →  Pass

 86%|████████▌ | 657/765 [13:32<02:07,  1.18s/it]

[657/765]  raw='pass (opinion'  →  Pass

 86%|████████▌ | 658/765 [13:33<02:07,  1.19s/it]

[658/765]  raw='pass.

ex'  →  Pass

 86%|████████▌ | 659/765 [13:34<02:01,  1.14s/it]

[659/765]  raw='pass.

e'  →  Pass

 86%|████████▋ | 660/765 [13:35<02:00,  1.15s/it]

[660/765]  raw='pass.

e'  →  Pass

 86%|████████▋ | 661/765 [13:37<02:19,  1.34s/it]

[661/765]  raw='pass.'  →  Pass

 87%|████████▋ | 662/765 [13:39<02:20,  1.36s/it]

[662/765]  raw='pass.'  →  Pass

 87%|████████▋ | 663/765 [13:40<02:06,  1.24s/it]

[663/765]  raw='pass.'  →  Pass

 87%|████████▋ | 664/765 [13:41<02:02,  1.22s/it]

[664/765]  raw='pass.'  →  Pass

 87%|████████▋ | 665/765 [13:42<01:52,  1.13s/it]

[665/765]  raw='pass.'  →  Pass

 87%|████████▋ | 666/765 [13:43<02:02,  1.23s/it]

[666/765]  raw='pass.'  →  Pass

 87%|████████▋ | 667/765 [13:44<01:51,  1.14s/it]

[667/765]  raw='pass.'  →  Pass

 87%|████████▋ | 668/765 [13:45<01:53,  1.17s/it]

[668/765]  raw='pass.'  →  Pass

 87%|████████▋ | 669/765 [13:47<02:00,  1.25s/it]

[669/765]  raw='pass.'  →  Pass

 88%|████████▊ | 670/765 [13:48<02:01,  1.28s/it]

[670/765]  raw='pass.'  →  Pass

 88%|████████▊ | 671/765 [13:50<02:14,  1.43s/it]

[671/765]  raw='fail.'  →  Fail

 88%|████████▊ | 672/765 [13:51<02:13,  1.43s/it]

[672/765]  raw='pass.'  →  Pass

 88%|████████▊ | 673/765 [13:52<01:56,  1.27s/it]

[673/765]  raw='pass.'  →  Pass

 88%|████████▊ | 674/765 [13:54<02:12,  1.45s/it]

[674/765]  raw='pass. the essay demonstr'  →  Pass

 88%|████████▊ | 675/765 [13:55<01:57,  1.30s/it]

[675/765]  raw='pass.'  →  Pass

 88%|████████▊ | 676/765 [13:57<02:03,  1.39s/it]

[676/765]  raw='pass.

ex'  →  Pass

 88%|████████▊ | 677/765 [13:58<01:57,  1.33s/it]

[677/765]  raw='fail.'  →  Fail

 89%|████████▊ | 678/765 [13:59<01:44,  1.20s/it]

[678/765]  raw='pass.'  →  Pass

 89%|████████▉ | 679/765 [14:00<01:46,  1.23s/it]

[679/765]  raw='pass.'  →  Pass

 89%|████████▉ | 680/765 [14:01<01:46,  1.26s/it]

[680/765]  raw='pass.'  →  Pass

 89%|████████▉ | 681/765 [14:03<01:47,  1.28s/it]

[681/765]  raw='pass.'  →  Pass

 89%|████████▉ | 682/765 [14:04<01:49,  1.32s/it]

[682/765]  raw='fail.'  →  Fail

 89%|████████▉ | 683/765 [14:05<01:42,  1.25s/it]

[683/765]  raw='pass.'  →  Pass

 89%|████████▉ | 684/765 [14:06<01:38,  1.22s/it]

[684/765]  raw='pass.'  →  Pass

 90%|████████▉ | 685/765 [14:07<01:35,  1.20s/it]

[685/765]  raw='fail.'  →  Fail

 90%|████████▉ | 686/765 [14:09<01:32,  1.17s/it]

[686/765]  raw='pass.'  →  Pass

 90%|████████▉ | 687/765 [14:10<01:36,  1.23s/it]

[687/765]  raw='pass.'  →  Pass

 90%|████████▉ | 688/765 [14:11<01:32,  1.20s/it]

[688/765]  raw='pass.'  →  Pass

 90%|█████████ | 689/765 [14:12<01:35,  1.25s/it]

[689/765]  raw='pass.'  →  Pass

 90%|█████████ | 690/765 [14:13<01:30,  1.21s/it]

[690/765]  raw='pass.'  →  Pass

 90%|█████████ | 691/765 [14:14<01:23,  1.13s/it]

[691/765]  raw='pass.'  →  Pass

 90%|█████████ | 692/765 [14:15<01:18,  1.08s/it]

[692/765]  raw='pass.'  →  Pass

 91%|█████████ | 693/765 [14:17<01:37,  1.35s/it]

[693/765]  raw='pass.

e'  →  Pass

 91%|█████████ | 694/765 [14:18<01:27,  1.23s/it]

[694/765]  raw='pass.'  →  Pass

 91%|█████████ | 695/765 [14:19<01:23,  1.20s/it]

[695/765]  raw='pass.'  →  Pass

 91%|█████████ | 696/765 [14:20<01:18,  1.14s/it]

[696/765]  raw='pass.'  →  Pass

 91%|█████████ | 697/765 [14:22<01:22,  1.21s/it]

[697/765]  raw='pass.'  →  Pass

 91%|█████████ | 698/765 [14:23<01:17,  1.15s/it]

[698/765]  raw='pass.'  →  Pass

 91%|█████████▏| 699/765 [14:24<01:12,  1.10s/it]

[699/765]  raw='fail.'  →  Fail

 92%|█████████▏| 700/765 [14:25<01:08,  1.05s/it]

[700/765]  raw='pass.'  →  Pass

 92%|█████████▏| 701/765 [14:26<01:06,  1.04s/it]

[701/765]  raw='pass.'  →  Pass

 92%|█████████▏| 702/765 [14:27<01:02,  1.01it/s]

[702/765]  raw='fail.'  →  Fail

 92%|█████████▏| 703/765 [14:28<01:01,  1.01it/s]

[703/765]  raw='pass.'  →  Pass

 92%|█████████▏| 704/765 [14:29<01:00,  1.01it/s]

[704/765]  raw='pass.'  →  Pass

 92%|█████████▏| 705/765 [14:30<01:02,  1.04s/it]

[705/765]  raw='pass.

ex'  →  Pass

 92%|█████████▏| 706/765 [14:31<00:58,  1.02it/s]

[706/765]  raw='pass.'  →  Pass

 92%|█████████▏| 707/765 [14:32<01:11,  1.22s/it]

[707/765]  raw='pass.'  →  Pass

 93%|█████████▎| 708/765 [14:34<01:08,  1.20s/it]

[708/765]  raw='pass.'  →  Pass

 93%|█████████▎| 709/765 [14:35<01:05,  1.17s/it]

[709/765]  raw='pass.'  →  Pass

 93%|█████████▎| 710/765 [14:36<01:03,  1.16s/it]

[710/765]  raw='pass.'  →  Pass

 93%|█████████▎| 711/765 [14:37<01:01,  1.13s/it]

[711/765]  raw='pass.

ex'  →  Pass

 93%|█████████▎| 712/765 [14:38<01:02,  1.19s/it]

[712/765]  raw='pass.'  →  Pass

 93%|█████████▎| 713/765 [14:40<01:06,  1.28s/it]

[713/765]  raw='pass.'  →  Pass

 93%|█████████▎| 714/765 [14:41<01:00,  1.19s/it]

[714/765]  raw='pass.'  →  Pass

 93%|█████████▎| 715/765 [14:42<00:54,  1.09s/it]

[715/765]  raw='pass.'  →  Pass

 94%|█████████▎| 716/765 [14:42<00:51,  1.05s/it]

[716/765]  raw='pass.'  →  Pass

 94%|█████████▎| 717/765 [14:44<00:51,  1.08s/it]

[717/765]  raw='pass.'  →  Pass

 94%|█████████▍| 718/765 [14:45<00:49,  1.05s/it]

[718/765]  raw='pass.'  →  Pass

 94%|█████████▍| 719/765 [14:46<00:49,  1.07s/it]

[719/765]  raw='pass.'  →  Pass

 94%|█████████▍| 720/765 [14:47<00:48,  1.08s/it]

[720/765]  raw='fail.'  →  Fail

 94%|█████████▍| 721/765 [14:48<00:51,  1.16s/it]

[721/765]  raw='pass.'  →  Pass

 94%|█████████▍| 722/765 [14:50<00:52,  1.22s/it]

[722/765]  raw='pass.'  →  Pass

 95%|█████████▍| 723/765 [14:51<00:48,  1.17s/it]

[723/765]  raw='fail.

prom'  →  Fail

 95%|█████████▍| 724/765 [14:51<00:44,  1.08s/it]

[724/765]  raw='pass.'  →  Pass

 95%|█████████▍| 725/765 [14:52<00:40,  1.01s/it]

[725/765]  raw='fail.'  →  Fail

 95%|█████████▍| 726/765 [14:53<00:41,  1.06s/it]

[726/765]  raw='pass.'  →  Pass

 95%|█████████▌| 727/765 [14:55<00:40,  1.07s/it]

[727/765]  raw='pass.'  →  Pass

 95%|█████████▌| 728/765 [14:56<00:38,  1.05s/it]

[728/765]  raw='pass.'  →  Pass

 95%|█████████▌| 729/765 [14:57<00:40,  1.12s/it]

[729/765]  raw='pass.'  →  Pass

 95%|█████████▌| 730/765 [14:58<00:37,  1.06s/it]

[730/765]  raw='pass.'  →  Pass

 96%|█████████▌| 731/765 [14:59<00:35,  1.04s/it]

[731/765]  raw='pass.'  →  Pass

 96%|█████████▌| 732/765 [15:00<00:40,  1.21s/it]

[732/765]  raw='pass.'  →  Pass

 96%|█████████▌| 733/765 [15:01<00:35,  1.11s/it]

[733/765]  raw='pass.'  →  Pass

 96%|█████████▌| 734/765 [15:02<00:34,  1.12s/it]

[734/765]  raw='pass.'  →  Pass

 96%|█████████▌| 735/765 [15:03<00:31,  1.05s/it]

[735/765]  raw='pass.'  →  Pass

 96%|█████████▌| 736/765 [15:05<00:32,  1.13s/it]

[736/765]  raw='prompt name: does'  →  ???

 96%|█████████▋| 737/765 [15:06<00:31,  1.14s/it]

[737/765]  raw='pass.'  →  Pass

 96%|█████████▋| 738/765 [15:07<00:30,  1.12s/it]

[738/765]  raw='pass.'  →  Pass

 97%|█████████▋| 739/765 [15:08<00:28,  1.10s/it]

[739/765]  raw='pass.

prom'  →  Pass

 97%|█████████▋| 740/765 [15:09<00:27,  1.11s/it]

[740/765]  raw='pass.

ex'  →  Pass

 97%|█████████▋| 741/765 [15:10<00:26,  1.12s/it]

[741/765]  raw='pass.'  →  Pass

 97%|█████████▋| 742/765 [15:11<00:26,  1.13s/it]

[742/765]  raw='pass.'  →  Pass

 97%|█████████▋| 743/765 [15:13<00:25,  1.14s/it]

[743/765]  raw='pass.'  →  Pass

 97%|█████████▋| 744/765 [15:14<00:25,  1.20s/it]

[744/765]  raw='pass.'  →  Pass

 97%|█████████▋| 745/765 [15:15<00:21,  1.10s/it]

[745/765]  raw='pass.'  →  Pass

 98%|█████████▊| 746/765 [15:16<00:22,  1.16s/it]

[746/765]  raw='pass.'  →  Pass

 98%|█████████▊| 747/765 [15:17<00:20,  1.16s/it]

[747/765]  raw='pass.'  →  Pass

 98%|█████████▊| 748/765 [15:19<00:20,  1.20s/it]

[748/765]  raw='fail.'  →  Fail

 98%|█████████▊| 749/765 [15:19<00:18,  1.14s/it]

[749/765]  raw='pass.'  →  Pass

 98%|█████████▊| 750/765 [15:20<00:16,  1.09s/it]

[750/765]  raw='pass.'  →  Pass

 98%|█████████▊| 751/765 [15:21<00:14,  1.06s/it]

[751/765]  raw='pass.'  →  Pass

 98%|█████████▊| 752/765 [15:23<00:15,  1.22s/it]

[752/765]  raw='pass.'  →  Pass

 98%|█████████▊| 753/765 [15:24<00:13,  1.14s/it]

[753/765]  raw='pass.'  →  Pass

 99%|█████████▊| 754/765 [15:25<00:12,  1.10s/it]

[754/765]  raw='fail.'  →  Fail

 99%|█████████▊| 755/765 [15:26<00:12,  1.21s/it]

[755/765]  raw='pass.'  →  Pass

 99%|█████████▉| 756/765 [15:28<00:11,  1.29s/it]

[756/765]  raw='pass.'  →  Pass

 99%|█████████▉| 757/765 [15:29<00:10,  1.30s/it]

[757/765]  raw='pass.'  →  Pass

 99%|█████████▉| 758/765 [15:30<00:08,  1.24s/it]

[758/765]  raw='pass.'  →  Pass

 99%|█████████▉| 759/765 [15:32<00:07,  1.31s/it]

[759/765]  raw='pass.'  →  Pass

 99%|█████████▉| 760/765 [15:33<00:06,  1.26s/it]

[760/765]  raw='pass.'  →  Pass

 99%|█████████▉| 761/765 [15:34<00:05,  1.29s/it]

[761/765]  raw='fail.'  →  Fail

100%|█████████▉| 762/765 [15:35<00:03,  1.22s/it]

[762/765]  raw='pass.'  →  Pass

100%|█████████▉| 763/765 [15:37<00:02,  1.33s/it]

[763/765]  raw='pass.'  →  Pass

100%|█████████▉| 764/765 [15:38<00:01,  1.31s/it]

[764/765]  raw='pass.'  →  Pass

100%|██████████| 765/765 [15:39<00:00,  1.23s/it]

[765/765]  raw='pass.'  →  Pass

In [ ]:
# Evaluate
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred                       generated y_true_label y_pred_label
0         0       1                           pass.         Fail         Pass
1         0       1                           pass.         Fail         Pass
2         0       1                           pass.         Fail         Pass
3         1       1                           pass.         Pass         Pass
4         0       1                           pass.         Fail         Pass
5         0       1                           pass.         Fail         Pass
6         1       1                           pass.         Pass         Pass
7         1       1                           pass.         Pass         Pass
8         1       1                           pass.         Pass         Pass
9         0       1                           pass.         Fail         Pass
10        0       1                           pass.         Fail         Pass
11        1       1                           pass.         Pass         Pass
12        1       1                           pass.         Pass         Pass
13        1       1                           pass.         Pass         Pass
14        1       1                           pass.         Pass         Pass
15        1       1                           pass.         Pass         Pass
16        1       1                           pass.         Pass         Pass
17        1       1                           pass.         Pass         Pass
18        0       1                           pass.         Fail         Pass
19        0       1                           pass.         Fail         Pass
20        0       1                           pass.         Fail         Pass
21        0       1                           pass.         Fail         Pass
22        0       1                           pass.         Fail         Pass
23        1       0                           fail.         Pass         Fail
24        1       1                           pass.         Pass         Pass
25        1       1                           pass.         Pass         Pass
26        0       1                           pass.         Fail         Pass
27        1       1                           pass.         Pass         Pass
28        1       1                           pass.         Pass         Pass
29        0       1                           pass.         Fail         Pass
30        1       1                           pass.         Pass         Pass
31        0       1                           pass.         Fail         Pass
32        1       1                           pass.         Pass         Pass
33        0       1                           pass.         Fail         Pass
34        0       1                           pass.         Fail         Pass
35        1       1                           pass.         Pass         Pass
36        1       0                           fail.         Pass         Fail
37        0       1                           pass.         Fail         Pass
38        1       1                           pass.         Pass         Pass
39        1       1                           pass.         Pass         Pass
40        1       1        pass. the essay presents         Pass         Pass
41        0       1        pass. the essay demonstr         Fail         Pass
42        0       1                           pass.         Fail         Pass
43        1       1                           pass.         Pass         Pass
44        0       1                           pass.         Fail         Pass
45        0       0                     fail.\n\nex         Fail         Fail
46        0      -1                 prompt name: ph         Fail          ???
47        1       1                           pass.         Pass         Pass
48        0       0                           fail.         Fail         Fail
49        1       1                           pass.         Pass         Pass
50        0       1                           pass.         Fail         Pass
51        0       0                           fail.         Fail         Fail
52        1       1                     pass.\n\nex         Pass         Pass
53        1       1                           pass.         Pass         Pass
54        0       1                           pass.         Fail         Pass
55        0       1                           pass.         Fail         Pass
56        0       1                           pass.         Fail         Pass
57        0       1                           pass.         Fail         Pass
58        0       1                           pass.         Fail         Pass
59        0       1                           pass.         Fail         Pass
60        1       1                     pass.\n\nex         Pass         Pass
61        0       1                           pass.         Fail         Pass
62        1       0        fail. the essay presents         Pass         Fail
63        0       0                           fail.         Fail         Fail
64        0       1                           pass.         Fail         Pass
65        1       1                           pass.         Pass         Pass
66        1       1                           pass.         Pass         Pass
67        0       1                           pass.         Fail         Pass
68        1       1                           pass.         Pass         Pass
69        0       1                           pass.         Fail         Pass
70        0       1                           pass.         Fail         Pass
71        0       0                           fail.         Fail         Fail
72        0       0       fail. safety concerns and         Fail         Fail
73        0       0                 fail. flaws out         Fail         Fail
74        0       1                      pass.\n\ne         Fail         Pass
75        1       1                           pass.         Pass         Pass
76        0       1                           pass.         Fail         Pass
77        1       0                           fail.         Pass         Fail
78        0       1                           pass.         Fail         Pass
79        1       1                           pass.         Pass         Pass
80        1       0                           fail.         Pass         Fail
81        1       1                           pass.         Pass         Pass
82        1       1        pass. the essay presents         Pass         Pass
83        1       1        pass. the essay demonstr         Pass         Pass
84        0       1                           pass.         Fail         Pass
85        0       1                           pass.         Fail         Pass
86        0       1                           pass.         Fail         Pass
87        0       1                           pass.         Fail         Pass
88        1       1                           pass.         Pass         Pass
89        0       1                           pass.         Fail         Pass
90        1       1                           pass.         Pass         Pass
91        1       1                           pass.         Pass         Pass
92        1       1                           pass.         Pass         Pass
93        0       1                           pass.         Fail         Pass
94        0       0                           fail.         Fail         Fail
95        0       1                           pass.         Fail         Pass
96        0       0                           fail.         Fail         Fail
97        0       1                           pass.         Fail         Pass
98        0       1                           pass.         Fail         Pass
99        0       0                           fail.         Fail         Fail
100       0       1                           pass.         Fail         Pass
101       0       1                           pass.         Fail         Pass
102       0       1                           pass.         Fail         Pass
103       0       1                           pass.         Fail         Pass
104       0       1                           pass.         Fail         Pass
105       1       1                           pass.         Pass         Pass
106       1       1                           pass.         Pass         Pass
107       0       1                           pass.         Fail         Pass
108       1       1                           pass.         Pass         Pass
109       0       1                           pass.         Fail         Pass
110       0       1                           pass.         Fail         Pass
111       0       1                           pass.         Fail         Pass
112       1       1                           pass.         Pass         Pass
113       0       1                           pass.         Fail         Pass
114       0       1                           pass.         Fail         Pass
115       0       1                           pass.         Fail         Pass
116       1       0                           fail.         Pass         Fail
117       1       1                           pass.         Pass         Pass
118       0       1                           pass.         Fail         Pass
119       1       1                      pass.\n\ne         Pass         Pass
120       1       1                           pass.         Pass         Pass
121       1       1                           pass.         Pass         Pass
122       1       1                           pass.         Pass         Pass
123       1       1                           pass.         Pass         Pass
124       0       1                           pass.         Fail         Pass
125       0       1                           pass.         Fail         Pass
126       0       1                           pass.         Fail         Pass
127       0       1                           pass.         Fail         Pass
128       0       1                           pass.         Fail         Pass
129       1       1                           pass.         Pass         Pass
130       0       1                           pass.         Fail         Pass
131       0       1                           pass.         Fail         Pass
132       0       1                     pass.\n\nex         Fail         Pass
133       0       0                           fail.         Fail         Fail
134       0       1                           pass.         Fail         Pass
135       0       1                           pass.         Fail         Pass
136       1       1                           pass.         Pass         Pass
137       1       0                           fail.         Pass         Fail
138       1       1                           pass.         Pass         Pass
139       0       1                           pass.         Fail         Pass
140       0       1                           pass.         Fail         Pass
141       0       1        pass. the essay demonstr         Fail         Pass
142       1       1                   pass.\n\nprom         Pass         Pass
143       1       1                           pass.         Pass         Pass
144       0       1                           pass.         Fail         Pass
145       1       1                           pass.         Pass         Pass
146       1       1                           pass.         Pass         Pass
147       1       1                           pass.         Pass         Pass
148       1       1                           pass.         Pass         Pass
149       0       1                           pass.         Fail         Pass
150       1       1                           pass.         Pass         Pass
151       0       1                      pass.\n\ne         Fail         Pass
152       1       1                           pass.         Pass         Pass
153       0       1                     pass.\n\nex         Fail         Pass
154       0       1                           pass.         Fail         Pass
155       1       1                           pass.         Pass         Pass
156       0       0        fail. the essay presents         Fail         Fail
157       1       0                     fail.\n\nex         Pass         Fail
158       1       1                           pass.         Pass         Pass
159       1       0               fail. developing.         Pass         Fail
160       0       1                           pass.         Fail         Pass
161       0       1                           pass.         Fail         Pass
162       0       1                           pass.         Fail         Pass
163       1       1                           pass.         Pass         Pass
164       0       1                     pass.\n\nex         Fail         Pass
165       0       0                           fail.         Fail         Fail
166       0       1                           pass.         Fail         Pass
167       0       1                           pass.         Fail         Pass
168       1       1                           pass.         Pass         Pass
169       1       1                           pass.         Pass         Pass
170       1       1                           pass.         Pass         Pass
171       1       1                           pass.         Pass         Pass
172       1       1                           pass.         Pass         Pass
173       1       1                           pass.         Pass         Pass
174       0       1                           pass.         Fail         Pass
175       0       1                           pass.         Fail         Pass
176       0       1                           pass.         Fail         Pass
177       0       1                           pass.         Fail         Pass
178       1       1                           pass.         Pass         Pass
179       0       1                     pass.\n\nex         Fail         Pass
180       0       1                           pass.         Fail         Pass
181       0       0                           fail.         Fail         Fail
182       0       1                           pass.         Fail         Pass
183       0       1                           pass.         Fail         Pass
184       1       1                           pass.         Pass         Pass
185       1       1                           pass.         Pass         Pass
186       0       1                           pass.         Fail         Pass
187       0       1                           pass.         Fail         Pass
188       1       1                           pass.         Pass         Pass
189       1       1                           pass.         Pass         Pass
190       0       1                           pass.         Fail         Pass
191       1       1                           pass.         Pass         Pass
192       0       1                           pass.         Fail         Pass
193       0       1                           pass.         Fail         Pass
194       1       1        pass. the essay presents         Pass         Pass
195       0       1                     pass.\n\nex         Fail         Pass
196       1       1                           pass.         Pass         Pass
197       0       1                           pass.         Fail         Pass
198       1       1                           pass.         Pass         Pass
199       0       1            pass (essay demonstr         Fail         Pass
200       0       1                           pass.         Fail         Pass
201       1       1                     pass.\n\nex         Pass         Pass
202       0       0                fail. essay lack         Fail         Fail
203       1       1                           pass.         Pass         Pass
204       0       1                     pass.\n\nex         Fail         Pass
205       0       1                           pass.         Fail         Pass
206       1       1                           pass.         Pass         Pass
207       0       1                           pass.         Fail         Pass
208       0       0                           fail.         Fail         Fail
209       0       1                           pass.         Fail         Pass
210       0       1                           pass.         Fail         Pass
211       0       1                           pass.         Fail         Pass
212       1       1                           pass.         Pass         Pass
213       0       1                     pass.\n\nex         Fail         Pass
214       0       1                           pass.         Fail         Pass
215       0       1                           pass.         Fail         Pass
216       0       1                      pass.\n\ne         Fail         Pass
217       1       0         fail. distance learning         Pass         Fail
218       1      -1               prompt name: mand         Pass          ???
219       0       1                           pass.         Fail         Pass
220       0       1                           pass.         Fail         Pass
221       0       0                      fail.\n\ne         Fail         Fail
222       1       0                     fail.\n\nex         Pass         Fail
223       1       1                           pass.         Pass         Pass
224       0       1                           pass.         Fail         Pass
225       1       1                           pass.         Pass         Pass
226       0       1                           pass.         Fail         Pass
227       0       1        pass. the essay demonstr         Fail         Pass
228       0       0                fail. essay lack         Fail         Fail
229       0       1                           pass.         Fail         Pass
230       1       1                           pass.         Pass         Pass
231       1       1                           pass.         Pass         Pass
232       0       1                           pass.         Fail         Pass
233       0       1                           pass.         Fail         Pass
234       1       1                           pass.         Pass         Pass
235       0       1                           pass.         Fail         Pass
236       0       1                           pass.         Fail         Pass
237       0       1                           pass.         Fail         Pass
238       1       1                           pass.         Pass         Pass
239       0       0                    fail. extrac         Fail         Fail
240       0       1                     pass.\n\nex         Fail         Pass
241       0       1                           pass.         Fail         Pass
242       0       1                           pass.         Fail         Pass
243       0       1                           pass.         Fail         Pass
244       0       1                           pass.         Fail         Pass
245       1       1                           pass.         Pass         Pass
246       1       1                           pass.         Pass         Pass
247       0       0                      fail.\n\ne         Fail         Fail
248       1       1                           pass.         Pass         Pass
249       0       1                           pass.         Fail         Pass
250       0       1                           pass.         Fail         Pass
251       1       1                           pass.         Pass         Pass
252       1       0                           fail.         Pass         Fail
253       0       1                   pass.\n\nprom         Fail         Pass
254       1       1        pass. the essay demonstr         Pass         Pass

## Qwen/Qwen2 7B 4bit

PADDING (tokenizer)

What is padding
I guess it is about filling extra space like placeholders tokens because we need that every sequence in a batch ends up with the same length
 * this is for processing GPU process barches as rectangular grids of numbers can not handle rows with different lengths in a single batch
GPU needs every sequence of token lenght to be the same lenght. But lets say essays are of different lenghts.
 * Essay A: "I think cars ar bad."
    * 6 tokens

 * Essay B: "Online school is great."
    * 5 tokens

To Batch, the model will need to pad to length 6
(so we need to padding, this is what i understands)
- Essay A: [i] [think] [cars] [are] [bad] [.]

- Essay B: [online] [school] [is] [great] [.] [PAD]

So now that these are all the same length, they can be stacked into one tensor the GPU can process in parallel. Also, i need to remember that pad has no meeaning when we mask i looks something lik
- Essay 1 input: [I] [like] [cars] [.] [PAD] [PAD]

- Essay 1 input: 1 1 1 1 0 0

(The masking allow the model to ignore the padded positions when computing attention and loss)

In [ ]:
!pip install -U peft trl bitsandbytes accelerate transformers

Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Collecting trl
  Downloading trl-1.9.0-py3-none-any.whl.metadata (12 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.50.0-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.13.1)
Collecting transformers
  Downloading transformers-5.14.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.11.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.8.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.23.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.13.0->peft) (1.5.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Downloading trl-1.9.0-py3-none-any.whl (884 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 885.0/885.0 kB 63.3 MB/s eta 0:00:00
Downloading bitsandbytes-0.50.0-py3-none-manylinux_2_24_x86_64.whl (40.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 60.1 MB/s eta 0:00:00
Downloading transformers-5.14.1-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 127.8 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 48.4 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 44.1 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, transformers, bitsandbytes, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.13.1
    Uninstalling transformers-5.13.1:
      Successfully uninstalled transformers-5.13.1
Successfully installed bitsandbytes-0.50.0 datasets-5.0.0 pyarrow-25.0.0 transformers-5.14.1 trl-1.9.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import userdata
from huggingface_hub import login

HF_TOKEN = userdata.get('B-Llama-3.1-8B-Access')   # stored securely in Colab secrets
login(token=HF_TOKEN)

What is Padding?
* When we need to process multiple sequences at once (that is a batch like lets say multiple essay)
 * Differetn essays tokenize to differetn lenghts but tensor calculations are must be rectangular so the shorter one (essay) get filled with pad tokens up to the longest one.
 * But Padding asks wehre do we put the filler on? Like which side?
 * NOW for decoder only model
   * remember decoder only model, the whole output extraction section, like a decoder contintues the seque3nce from its end
    * Generation appends new tokens after the last position (the last position of each row is very important.

**So Right Padding**

```
Essay A: [tok tok tok ... tok PAD PAD PAD PAD]
# real content ends early
Essay B: [tok tok tok ... tok tok tok tok tok]  
#full length
```

* If essay A's sequence ends in padding, when the model generates "the next token after the end," it's continuing from a pile of filler and we get -1

**So Left Padding**
* it puts the fillers at the front

```
Essay A: [PAD PAD PAD PAD tok tok tok ... tok]
#real content flush against the END
Essay B: [tok tok tok tok tok tok tok ... tok]
```
But remember
* Now every row ends with its real prompt, and the assistant marker sits at the final position for every essay in the batch
  * and now generation for each one begins exactly where it should.


SO KEEP this in mind, Why training uses right padding?
* padding_side = "right"
  * training doesnt happen from the en, it is computing the whole system and expect real content from the start position 0
   * training padding to the right
   * generation padding to the left

forgetting this would produce the garbage-continuation bug

In [ ]:

# Loading Qwen2 7B with 4-bit quantization (required for T4 16GB)
# I need to chck for  L4 GPU
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "Qwen/Qwen2-7B-Instruct"

#Quantization code
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

## toknizer and PADDING

#convert text into numbers, tokenIDs that the model understands
#every model have their own matching tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

#this is about padding [PAD]
#each model has a dedicated PAD only a <EOS> end of sequence token
# tokenizer.pad_token = tokenizer.eos_token see below why not


# where the padding goes
# to the left if for inferences
tokenizer.padding_side = "left"


#auto.. to call a causal language model a model that predicts th next token
#from_pretrained, downloads the pretrained weights for th model
model = AutoModelForCausalLM.from_pretrained( # remember this is from huggingface to call the model
    model_name,                               # the name of the model
    quantization_config=bnb_config,
    device_map="auto",                        # auto tells hf to decide on the avaliable resources: in our case: change "cpu" to "auto" so T4 GPU is used
    token=HF_TOKEN,
)

# model and tokenizer aggreement
#model.config.pad_token_id = tokenizer.eos_token_id
model.config.pad_token_id = tokenizer.pad_token_id

print("Model loaded on:", next(model.parameters()).device)
print("Memory (MB)    :", round(model.get_memory_footprint() / 1e6, 1))

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Model loaded on: cuda:0
Memory (MB)    : 5443.3

Qwen has a  dedicated pad token so
* lets not overwrite it
  * tokenizer.pad_token = tokenizer.eos_token
    * so we not doing this

In [ ]:
#check the pad and oes
tokenizer = AutoTokenizer.from_pretrained(model_name)
print("pad:", tokenizer.pad_token, tokenizer.pad_token_id, "| eos:", tokenizer.eos_token, tokenizer.eos_token_id)

pad: <|endoftext|> 151643 | eos: <|im_end|> 151645

In [ ]:
X = sample.drop(columns=["holistic_essay_score", "binary_score"])
y = sample["binary_score"].copy()          # binary 0/1 instead of 1 to 6, th 1 to 6 was not working at all

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print(f"Train : {len(X_train):,}  ({len(X_train)/len(sample)*100:.1f}%)")
print(f"Val   : {len(X_val):,}   ({len(X_val)/len(sample)*100:.1f}%)")
print(f"Test  : {len(X_test):,}   ({len(X_test)/len(sample)*100:.1f}%)")
print("\nClass distribution (stratification check):")
for name, y_split in [("Train", y_train), ("Val", y_val), ("Test", y_test)]:
    counts = y_split.value_counts().rename({0: "Fail", 1: "Pass"})
    print(f"  {name}: {counts.to_dict()}")

Train : 3,570  (70.0%)
Val   : 765   (15.0%)
Test  : 765   (15.0%)

Class distribution (stratification check):
  Train: {'Fail': 2065, 'Pass': 1505}
  Val: {'Fail': 443, 'Pass': 322}
  Test: {'Fail': 442, 'Pass': 323}

In [ ]:
#Part 2
#better version to keep things consistent
def generate_test_prompt(row):
    return (
        f"You are an expert essay grader. Read the essay and respond with exactly one word.\n"
        f"Your response must be either the word Fail or Pass. No other words.\n\n"
        f"Rules:\n"
        f"- Fail: the essay is weak, underdeveloped, or below standard\n"
        f"- Pass: the essay is proficient, strong, or excellent\n\n"
        f"Prompt: {row['prompt_name']}\n"
        f"Task: {row['task']}\n"
        f"Essay: {row['full_text']}\n\n"
        f"Respond with one word only (Fail or Pass): "
    )


def make_prompt_completion(row, tokenizer):
    user_content = generate_test_prompt(row)   # same wording
    prompt = tokenizer.apply_chat_template(
        [{"role": "user", "content": user_content}],
        tokenize=False, add_generation_prompt=True,
    )
    completion = "Pass" if row["binary_score"] == 1 else "Fail"
    return {"prompt": prompt, "completion": completion}

#Train
train_df = X_train.copy()
train_df["binary_score"] = y_train.values

# eval prompt
val_df = X_val.copy()
val_df["binary_score"] = y_val.values
X_val_prompts = pd.DataFrame(val_df.apply(generate_test_prompt, axis=1), columns=["text"])

test_df = X_test.copy()
test_df["binary_score"] = y_test.values
y_true = test_df["binary_score"].values
X_test_prompts = pd.DataFrame(test_df.apply(generate_test_prompt, axis=1), columns=["text"])

In [ ]:
def predict_decoder_only(test, model, tokenizer):
    y_pred      = []
    y_generated = []

    model.eval()  # disable training only behavior (we not training here)

    # loop through every prompt in the test set
    for i in tqdm(range(len(test))):  # tqdm gives the progress bar, really helpful

        messages = [{"role": "user", "content": test.iloc[i]["text"]}]
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        # convert the prompt string into token IDs (numeric)
        # we are giving all of this to our model in a language it can understand (tokenize)
        inputs = tokenizer(
            prompt,             #this is the prompt
            return_tensors="pt",  #tensor
            truncation=True,      # cut, not sure how this affect the evaluation
            max_length=10000,   # Llama handles longer context than T5's 512, anything more 2048 bye bye
            padding=False      # one essay at a time, nothing to pad against, less problems
        ).to(model.device)     # move the tokenized prompt to wherever the model lives (cpu/gpu)

        # remember how long the INPUT was, in tokens
        # decoder-only models return input + answer glued together,
        # so we need this to cut the input back off afterwards

        input_len = inputs["input_ids"].shape[1]

        # no gradient tracking, we are not training
        with torch.no_grad():
            # Llama GPT are decoder only no not forget this so --->>>input and output share one stream,
            # so .generate() APPENDS the answer onto the prompt tokens
            outputs = model.generate(
                **inputs,
                max_new_tokens=10,         # only need a word or two ("Pass"/"Fail")
                do_sample=False,           # greedy = deterministic, reproducible in a workshop
                #pad_token_id=tokenizer.eos_token_id,  #this has to be changed
                pad_token_id=tokenizer.pad_token_id,

                use_cache=False,
            )
        # Where the answerrrrr
        # The key step here: keep only the tokens AFTER the prompt.
        # outputs[0] = [ ...prompt tokens... , ...new answer tokens... ]
        # so lets slice from input_len onward to get ONLY what the model added.

        new_tokens = outputs[0][input_len:]

        # turn those new token IDs back into text
        # skip_special_tokens drops <|assistant|>, </s>, etc.
        generated = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()

        y_generated.append(generated)

        # map the text answer to a label, So
        # contains "pass" -> 1, contains "fail" -> 0, neither -> -1 (unparseable problems)
        if "pass" in generated: y_pred.append(1)
        elif "fail" in generated: y_pred.append(0)
        else: y_pred.append(-1)

        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  → → {y_pred[-1]}")

    return y_pred, y_generated

.generate() is actually a universal method available for every hf model that can produce text
   * I thought it was only for encoder-decoder model
   * Qwen is a decoder only model lik GPT and llama

Also, remember
* Decoder only model: genera text by predicting th next words based on previous words
* Encoder-decoder models are the input sequence and translate it into an entirely different output sequence. translation model english to spanish

In [ ]:
# zero-shot Qwen baseline — same 100 val essays as Phi's 0.58 baseline
val_sample   = X_val_prompts.iloc[:100].reset_index(drop=True)
y_val_sample = y_val.values[:100]

y_pred, y_generated = predict_decoder_only(val_sample, model, tokenizer)

valid = [i for i, p in enumerate(y_pred) if p != -1]
yt = y_val_sample[valid]
yp = [y_pred[i] for i in valid]

print(f"Parsed: {len(valid)}/100")
print(f"Accuracy: {accuracy_score(yt, yp):.4f}   (Phi-3.5 zero-shot was 0.58)")
print(classification_report(yt, yp, target_names=["Fail", "Pass"]))
print(confusion_matrix(yt, yp))
print("Predicted-Pass fraction:", (pd.Series(yp) == 1).mean(), " (true rate 0.42)")

  1%|          | 1/100 [00:01<02:41,  1.63s/it]

[  1/100]  raw='pass'  → → 1

  2%|▏         | 2/100 [00:02<02:04,  1.27s/it]

[  2/100]  raw='pass'  → → 1

  3%|▎         | 3/100 [00:04<02:10,  1.35s/it]

[  3/100]  raw='fail'  → → 0

  4%|▍         | 4/100 [00:04<01:48,  1.13s/it]

[  4/100]  raw='pass'  → → 1

  5%|▌         | 5/100 [00:05<01:35,  1.01s/it]

[  5/100]  raw='pass'  → → 1

  6%|▌         | 6/100 [00:07<01:57,  1.25s/it]

[  6/100]  raw='fail'  → → 0

  7%|▋         | 7/100 [00:08<01:48,  1.17s/it]

[  7/100]  raw='fail'  → → 0

  8%|▊         | 8/100 [00:10<02:08,  1.39s/it]

[  8/100]  raw='pass'  → → 1

  9%|▉         | 9/100 [00:11<01:50,  1.22s/it]

[  9/100]  raw='fail'  → → 0

 10%|█         | 10/100 [00:12<02:03,  1.37s/it]

[ 10/100]  raw='pass'  → → 1

 11%|█         | 11/100 [00:13<01:45,  1.19s/it]

[ 11/100]  raw='pass'  → → 1

 12%|█▏        | 12/100 [00:14<01:47,  1.22s/it]

[ 12/100]  raw='fail'  → → 0

 13%|█▎        | 13/100 [00:16<01:45,  1.21s/it]

[ 13/100]  raw='pass'  → → 1

 14%|█▍        | 14/100 [00:16<01:34,  1.10s/it]

[ 14/100]  raw='pass'  → → 1

 15%|█▌        | 15/100 [00:17<01:26,  1.02s/it]

[ 15/100]  raw='pass'  → → 1

 16%|█▌        | 16/100 [00:18<01:24,  1.00s/it]

[ 16/100]  raw='pass'  → → 1

 17%|█▋        | 17/100 [00:20<01:42,  1.24s/it]

[ 17/100]  raw='pass'  → → 1

 18%|█▊        | 18/100 [00:21<01:37,  1.19s/it]

[ 18/100]  raw='pass'  → → 1

 19%|█▉        | 19/100 [00:22<01:32,  1.14s/it]

[ 19/100]  raw='pass'  → → 1

 20%|██        | 20/100 [00:24<01:47,  1.34s/it]

[ 20/100]  raw='pass'  → → 1

 21%|██        | 21/100 [00:26<01:53,  1.44s/it]

[ 21/100]  raw='pass'  → → 1

 22%|██▏       | 22/100 [00:26<01:37,  1.25s/it]

[ 22/100]  raw='fail'  → → 0

 23%|██▎       | 23/100 [00:28<01:37,  1.27s/it]

[ 23/100]  raw='pass'  → → 1

 24%|██▍       | 24/100 [00:29<01:27,  1.15s/it]

[ 24/100]  raw='pass'  → → 1

 25%|██▌       | 25/100 [00:30<01:41,  1.35s/it]

[ 25/100]  raw='pass'  → → 1

 26%|██▌       | 26/100 [00:32<01:47,  1.46s/it]

[ 26/100]  raw='fail'  → → 0

 27%|██▋       | 27/100 [00:33<01:32,  1.26s/it]

[ 27/100]  raw='fail'  → → 0

 28%|██▊       | 28/100 [00:34<01:21,  1.13s/it]

[ 28/100]  raw='fail'  → → 0

 29%|██▉       | 29/100 [00:35<01:17,  1.09s/it]

[ 29/100]  raw='pass'  → → 1

 30%|███       | 30/100 [00:36<01:22,  1.18s/it]

[ 30/100]  raw='pass'  → → 1

 31%|███       | 31/100 [00:38<01:32,  1.34s/it]

[ 31/100]  raw='pass'  → → 1

 32%|███▏      | 32/100 [00:39<01:20,  1.19s/it]

[ 32/100]  raw='pass'  → → 1

 33%|███▎      | 33/100 [00:40<01:25,  1.28s/it]

[ 33/100]  raw='pass'  → → 1

 34%|███▍      | 34/100 [00:43<01:59,  1.81s/it]

[ 34/100]  raw='pass'  → → 1

 35%|███▌      | 35/100 [00:44<01:39,  1.52s/it]

[ 35/100]  raw='pass'  → → 1

 36%|███▌      | 36/100 [00:45<01:25,  1.33s/it]

[ 36/100]  raw='fail'  → → 0

 37%|███▋      | 37/100 [00:46<01:24,  1.33s/it]

[ 37/100]  raw='fail'  → → 0

 38%|███▊      | 38/100 [00:47<01:19,  1.28s/it]

[ 38/100]  raw='pass'  → → 1

 39%|███▉      | 39/100 [00:49<01:18,  1.29s/it]

[ 39/100]  raw='fail'  → → 0

 40%|████      | 40/100 [00:50<01:14,  1.24s/it]

[ 40/100]  raw='pass'  → → 1

 41%|████      | 41/100 [00:53<01:38,  1.67s/it]

[ 41/100]  raw='fail'  → → 0

 42%|████▏     | 42/100 [00:53<01:22,  1.43s/it]

[ 42/100]  raw='fail'  → → 0

 43%|████▎     | 43/100 [00:54<01:12,  1.27s/it]

[ 43/100]  raw='fail'  → → 0

 44%|████▍     | 44/100 [00:56<01:22,  1.48s/it]

[ 44/100]  raw='pass'  → → 1

 45%|████▌     | 45/100 [00:57<01:10,  1.28s/it]

[ 45/100]  raw='fail'  → → 0

 46%|████▌     | 46/100 [00:58<01:09,  1.30s/it]

[ 46/100]  raw='fail'  → → 0

 47%|████▋     | 47/100 [01:00<01:10,  1.33s/it]

[ 47/100]  raw='fail'  → → 0

 48%|████▊     | 48/100 [01:01<01:01,  1.19s/it]

[ 48/100]  raw='pass'  → → 1

 49%|████▉     | 49/100 [01:02<00:59,  1.18s/it]

[ 49/100]  raw='pass'  → → 1

 50%|█████     | 50/100 [01:03<00:54,  1.09s/it]

[ 50/100]  raw='pass'  → → 1

 51%|█████     | 51/100 [01:04<00:52,  1.07s/it]

[ 51/100]  raw='pass'  → → 1

 52%|█████▏    | 52/100 [01:05<00:55,  1.16s/it]

[ 52/100]  raw='pass'  → → 1

 53%|█████▎    | 53/100 [01:06<00:53,  1.14s/it]

[ 53/100]  raw='pass'  → → 1

 54%|█████▍    | 54/100 [01:08<01:02,  1.36s/it]

[ 54/100]  raw='fail'  → → 0

 55%|█████▌    | 55/100 [01:09<01:01,  1.36s/it]

[ 55/100]  raw='pass'  → → 1

 56%|█████▌    | 56/100 [01:13<01:28,  2.02s/it]

[ 56/100]  raw='pass'  → → 1

 57%|█████▋    | 57/100 [01:15<01:23,  1.93s/it]

[ 57/100]  raw='pass'  → → 1

 58%|█████▊    | 58/100 [01:17<01:23,  2.00s/it]

[ 58/100]  raw='pass'  → → 1

 59%|█████▉    | 59/100 [01:19<01:18,  1.91s/it]

[ 59/100]  raw='fail'  → → 0

 60%|██████    | 60/100 [01:19<01:03,  1.60s/it]

[ 60/100]  raw='fail'  → → 0

 61%|██████    | 61/100 [01:21<01:06,  1.70s/it]

[ 61/100]  raw='pass'  → → 1

 62%|██████▏   | 62/100 [01:23<01:02,  1.64s/it]

[ 62/100]  raw='pass'  → → 1

 63%|██████▎   | 63/100 [01:24<00:54,  1.46s/it]

[ 63/100]  raw='pass'  → → 1

 64%|██████▍   | 64/100 [01:25<00:48,  1.35s/it]

[ 64/100]  raw='fail'  → → 0

 65%|██████▌   | 65/100 [01:26<00:47,  1.37s/it]

[ 65/100]  raw='pass'  → → 1

 66%|██████▌   | 66/100 [01:27<00:41,  1.24s/it]

[ 66/100]  raw='fail'  → → 0

 67%|██████▋   | 67/100 [01:29<00:48,  1.48s/it]

[ 67/100]  raw='pass'  → → 1

 68%|██████▊   | 68/100 [01:30<00:42,  1.31s/it]

[ 68/100]  raw='fail'  → → 0

 69%|██████▉   | 69/100 [01:32<00:47,  1.52s/it]

[ 69/100]  raw='pass'  → → 1

 70%|███████   | 70/100 [01:33<00:41,  1.39s/it]

[ 70/100]  raw='fail'  → → 0

 71%|███████   | 71/100 [01:35<00:42,  1.46s/it]

[ 71/100]  raw='pass'  → → 1

 72%|███████▏  | 72/100 [01:36<00:36,  1.29s/it]

[ 72/100]  raw='pass'  → → 1

 73%|███████▎  | 73/100 [01:38<00:39,  1.45s/it]

[ 73/100]  raw='pass'  → → 1

 74%|███████▍  | 74/100 [01:39<00:35,  1.36s/it]

[ 74/100]  raw='pass'  → → 1

 75%|███████▌  | 75/100 [01:42<00:43,  1.75s/it]

[ 75/100]  raw='fail'  → → 0

 76%|███████▌  | 76/100 [01:43<00:43,  1.79s/it]

[ 76/100]  raw='pass'  → → 1

 77%|███████▋  | 77/100 [01:45<00:39,  1.71s/it]

[ 77/100]  raw='fail'  → → 0

 78%|███████▊  | 78/100 [01:46<00:32,  1.48s/it]

[ 78/100]  raw='fail'  → → 0

 79%|███████▉  | 79/100 [01:47<00:28,  1.36s/it]

[ 79/100]  raw='pass'  → → 1

 80%|████████  | 80/100 [01:48<00:27,  1.37s/it]

[ 80/100]  raw='fail'  → → 0

 81%|████████  | 81/100 [01:51<00:30,  1.58s/it]

[ 81/100]  raw='pass'  → → 1

 82%|████████▏ | 82/100 [01:51<00:24,  1.38s/it]

[ 82/100]  raw='pass'  → → 1

 83%|████████▎ | 83/100 [01:54<00:31,  1.88s/it]

[ 83/100]  raw='pass'  → → 1

 84%|████████▍ | 84/100 [01:57<00:31,  1.97s/it]

[ 84/100]  raw='pass'  → → 1

 85%|████████▌ | 85/100 [01:58<00:27,  1.82s/it]

[ 85/100]  raw='pass'  → → 1

 86%|████████▌ | 86/100 [02:00<00:23,  1.69s/it]

[ 86/100]  raw='pass'  → → 1

 87%|████████▋ | 87/100 [02:01<00:21,  1.67s/it]

[ 87/100]  raw='pass'  → → 1

 88%|████████▊ | 88/100 [02:03<00:20,  1.70s/it]

[ 88/100]  raw='pass'  → → 1

 89%|████████▉ | 89/100 [02:05<00:18,  1.68s/it]

[ 89/100]  raw='pass'  → → 1

 90%|█████████ | 90/100 [02:06<00:15,  1.52s/it]

[ 90/100]  raw='pass'  → → 1

 91%|█████████ | 91/100 [02:07<00:12,  1.41s/it]

[ 91/100]  raw='fail'  → → 0

 92%|█████████▏| 92/100 [02:08<00:11,  1.49s/it]

[ 92/100]  raw='fail'  → → 0

 93%|█████████▎| 93/100 [02:11<00:11,  1.67s/it]

[ 93/100]  raw='pass'  → → 1

 94%|█████████▍| 94/100 [02:12<00:09,  1.63s/it]

[ 94/100]  raw='pass'  → → 1

 95%|█████████▌| 95/100 [02:14<00:08,  1.67s/it]

[ 95/100]  raw='pass'  → → 1

 96%|█████████▌| 96/100 [02:15<00:05,  1.45s/it]

[ 96/100]  raw='pass'  → → 1

 97%|█████████▋| 97/100 [02:16<00:03,  1.30s/it]

[ 97/100]  raw='fail'  → → 0

 98%|█████████▊| 98/100 [02:17<00:02,  1.25s/it]

[ 98/100]  raw='pass'  → → 1

 99%|█████████▉| 99/100 [02:19<00:01,  1.41s/it]

[ 99/100]  raw='fail'  → → 0

100%|██████████| 100/100 [02:20<00:00,  1.40s/it]

[100/100]  raw='fail'  → → 0
Parsed: 100/100
Accuracy: 0.5600   (Phi-3.5 zero-shot was 0.58)
              precision    recall  f1-score   support

        Fail       0.71      0.41      0.52        58
        Pass       0.48      0.76      0.59        42

    accuracy                           0.56       100
   macro avg       0.60      0.59      0.56       100
weighted avg       0.61      0.56      0.55       100

[[24 34]
 [10 32]]
Predicted-Pass fraction: 0.66  (true rate 0.42)

In [ ]:
y_pred, y_generated = predict_decoder_only(X_test_prompts.reset_index(drop=True), model, tokenizer)

  0%|          | 2/765 [00:01<08:26,  1.51it/s]

[  1/765]  raw='pass'  → → 1
[  2/765]  raw='pass'  → → 1

  1%|          | 4/765 [00:01<04:17,  2.96it/s]

[  3/765]  raw='pass'  → → 1
[  4/765]  raw='pass'  → → 1

  1%|          | 6/765 [00:02<03:04,  4.10it/s]

[  5/765]  raw='pass'  → → 1
[  6/765]  raw='pass'  → → 1

  1%|          | 8/765 [00:02<02:35,  4.86it/s]

[  7/765]  raw='pass'  → → 1
[  8/765]  raw='pass'  → → 1

  1%|▏         | 10/765 [00:02<02:23,  5.26it/s]

[  9/765]  raw='pass'  → → 1
[ 10/765]  raw='pass'  → → 1

  2%|▏         | 12/765 [00:03<02:20,  5.35it/s]

[ 11/765]  raw='fail'  → → 0
[ 12/765]  raw='pass'  → → 1

  2%|▏         | 14/765 [00:03<02:13,  5.63it/s]

[ 13/765]  raw='pass'  → → 1
[ 14/765]  raw='pass'  → → 1

  2%|▏         | 16/765 [00:03<02:09,  5.76it/s]

[ 15/765]  raw='pass'  → → 1
[ 16/765]  raw='pass'  → → 1

  2%|▏         | 18/765 [00:04<02:10,  5.72it/s]

[ 17/765]  raw='pass'  → → 1
[ 18/765]  raw='pass'  → → 1

  2%|▏         | 19/765 [00:04<02:10,  5.74it/s]

[ 19/765]  raw='pass'  → → 1

  3%|▎         | 21/765 [00:04<02:18,  5.37it/s]

[ 20/765]  raw='pass'  → → 1
[ 21/765]  raw='pass'  → → 1

  3%|▎         | 23/765 [00:05<02:12,  5.62it/s]

[ 22/765]  raw='fail'  → → 0
[ 23/765]  raw='pass'  → → 1

  3%|▎         | 25/765 [00:05<02:16,  5.43it/s]

[ 24/765]  raw='fail'  → → 0
[ 25/765]  raw='pass'  → → 1

  4%|▎         | 27/765 [00:05<02:11,  5.63it/s]

[ 26/765]  raw='pass'  → → 1
[ 27/765]  raw='pass'  → → 1

  4%|▍         | 29/765 [00:06<02:08,  5.71it/s]

[ 28/765]  raw='pass'  → → 1
[ 29/765]  raw='pass'  → → 1

  4%|▍         | 31/765 [00:06<02:06,  5.78it/s]

[ 30/765]  raw='pass'  → → 1
[ 31/765]  raw='pass'  → → 1

  4%|▍         | 32/765 [00:06<02:06,  5.81it/s]

[ 32/765]  raw='pass'  → → 1

  4%|▍         | 34/765 [00:07<02:11,  5.57it/s]

[ 33/765]  raw='pass'  → → 1
[ 34/765]  raw='pass'  → → 1

  5%|▍         | 36/765 [00:07<02:08,  5.68it/s]

[ 35/765]  raw='fail'  → → 0
[ 36/765]  raw='pass'  → → 1

  5%|▍         | 38/765 [00:07<02:06,  5.76it/s]

[ 37/765]  raw='fail'  → → 0
[ 38/765]  raw='pass'  → → 1

  5%|▌         | 40/765 [00:08<02:08,  5.63it/s]

[ 39/765]  raw='pass'  → → 1
[ 40/765]  raw='pass'  → → 1

  5%|▌         | 42/765 [00:08<02:15,  5.35it/s]

[ 41/765]  raw='pass'  → → 1
[ 42/765]  raw='fail'  → → 0

  6%|▌         | 44/765 [00:09<02:08,  5.62it/s]

[ 43/765]  raw='fail'  → → 0
[ 44/765]  raw='pass'  → → 1

  6%|▌         | 46/765 [00:09<02:04,  5.78it/s]

[ 45/765]  raw='pass'  → → 1
[ 46/765]  raw='fail'  → → 0

  6%|▋         | 48/765 [00:09<02:03,  5.83it/s]

[ 47/765]  raw='pass'  → → 1
[ 48/765]  raw='pass'  → → 1

  7%|▋         | 50/765 [00:10<02:02,  5.84it/s]

[ 49/765]  raw='fail'  → → 0
[ 50/765]  raw='pass'  → → 1

  7%|▋         | 52/765 [00:10<02:00,  5.90it/s]

[ 51/765]  raw='pass'  → → 1
[ 52/765]  raw='fail'  → → 0

  7%|▋         | 53/765 [00:10<02:01,  5.87it/s]

[ 53/765]  raw='pass'  → → 1

  7%|▋         | 55/765 [00:10<02:11,  5.41it/s]

[ 54/765]  raw='pass'  → → 1
[ 55/765]  raw='pass'  → → 1

  7%|▋         | 57/765 [00:11<02:04,  5.70it/s]

[ 56/765]  raw='pass'  → → 1
[ 57/765]  raw='pass'  → → 1

  8%|▊         | 59/765 [00:11<02:01,  5.83it/s]

[ 58/765]  raw='pass'  → → 1
[ 59/765]  raw='pass'  → → 1

  8%|▊         | 61/765 [00:11<01:59,  5.89it/s]

[ 60/765]  raw='fail'  → → 0
[ 61/765]  raw='pass'  → → 1

  8%|▊         | 63/765 [00:12<02:01,  5.76it/s]

[ 62/765]  raw='pass'  → → 1
[ 63/765]  raw='fail'  → → 0

  8%|▊         | 65/765 [00:12<01:57,  5.95it/s]

[ 64/765]  raw='fail'  → → 0
[ 65/765]  raw='fail'  → → 0

  9%|▉         | 67/765 [00:12<02:00,  5.78it/s]

[ 66/765]  raw='pass'  → → 1
[ 67/765]  raw='pass'  → → 1

  9%|▉         | 69/765 [00:13<01:57,  5.93it/s]

[ 68/765]  raw='pass'  → → 1
[ 69/765]  raw='pass'  → → 1

  9%|▉         | 71/765 [00:13<01:55,  6.03it/s]

[ 70/765]  raw='pass'  → → 1
[ 71/765]  raw='pass'  → → 1

 10%|▉         | 73/765 [00:13<01:54,  6.06it/s]

[ 72/765]  raw='fail'  → → 0
[ 73/765]  raw='fail'  → → 0

 10%|▉         | 75/765 [00:14<01:53,  6.06it/s]

[ 74/765]  raw='fail'  → → 0
[ 75/765]  raw='fail'  → → 0

 10%|█         | 77/765 [00:14<01:54,  6.03it/s]

[ 76/765]  raw='pass'  → → 1
[ 77/765]  raw='fail'  → → 0

 10%|█         | 79/765 [00:14<01:53,  6.04it/s]

[ 78/765]  raw='fail'  → → 0
[ 79/765]  raw='fail'  → → 0

 11%|█         | 81/765 [00:15<02:01,  5.64it/s]

[ 80/765]  raw='pass'  → → 1
[ 81/765]  raw='fail'  → → 0

 11%|█         | 82/765 [00:15<01:58,  5.76it/s]

[ 82/765]  raw='pass'  → → 1

 11%|█         | 83/765 [00:15<02:08,  5.29it/s]

[ 83/765]  raw='pass'  → → 1

 11%|█         | 85/765 [00:16<02:08,  5.29it/s]

[ 84/765]  raw='pass'  → → 1
[ 85/765]  raw='pass'  → → 1

 11%|█▏        | 87/765 [00:16<01:59,  5.68it/s]

[ 86/765]  raw='fail'  → → 0
[ 87/765]  raw='fail'  → → 0

 12%|█▏        | 89/765 [00:16<01:55,  5.87it/s]

[ 88/765]  raw='pass'  → → 1
[ 89/765]  raw='pass'  → → 1

 12%|█▏        | 91/765 [00:17<01:53,  5.93it/s]

[ 90/765]  raw='fail'  → → 0
[ 91/765]  raw='pass'  → → 1

 12%|█▏        | 93/765 [00:17<02:01,  5.51it/s]

[ 92/765]  raw='pass'  → → 1
[ 93/765]  raw='fail'  → → 0

 12%|█▏        | 95/765 [00:17<01:55,  5.79it/s]

[ 94/765]  raw='fail'  → → 0
[ 95/765]  raw='fail'  → → 0

 13%|█▎        | 97/765 [00:18<01:52,  5.94it/s]

[ 96/765]  raw='pass'  → → 1
[ 97/765]  raw='fail'  → → 0

 13%|█▎        | 98/765 [00:18<01:51,  5.99it/s]

[ 98/765]  raw='pass'  → → 1

 13%|█▎        | 100/765 [00:18<01:56,  5.71it/s]

[ 99/765]  raw='fail'  → → 0
[100/765]  raw='fail'  → → 0

 13%|█▎        | 102/765 [00:19<01:52,  5.89it/s]

[101/765]  raw='pass'  → → 1
[102/765]  raw='pass'  → → 1

 14%|█▎        | 104/765 [00:19<01:50,  6.00it/s]

[103/765]  raw='pass'  → → 1
[104/765]  raw='pass'  → → 1

 14%|█▎        | 105/765 [00:19<01:49,  6.02it/s]

[105/765]  raw='fail'  → → 0

 14%|█▍        | 107/765 [00:19<01:57,  5.61it/s]

[106/765]  raw='pass'  → → 1
[107/765]  raw='pass'  → → 1

 14%|█▍        | 109/765 [00:20<01:54,  5.73it/s]

[108/765]  raw='fail'  → → 0
[109/765]  raw='pass'  → → 1

 15%|█▍        | 111/765 [00:20<01:51,  5.86it/s]

[110/765]  raw='pass'  → → 1
[111/765]  raw='pass'  → → 1

 15%|█▍        | 113/765 [00:20<01:50,  5.91it/s]

[112/765]  raw='pass'  → → 1
[113/765]  raw='pass'  → → 1

 15%|█▌        | 115/765 [00:21<01:50,  5.91it/s]

[114/765]  raw='pass'  → → 1
[115/765]  raw='pass'  → → 1

 15%|█▌        | 117/765 [00:21<01:49,  5.93it/s]

[116/765]  raw='pass'  → → 1
[117/765]  raw='fail'  → → 0

 16%|█▌        | 119/765 [00:21<01:49,  5.92it/s]

[118/765]  raw='pass'  → → 1
[119/765]  raw='pass'  → → 1

 16%|█▌        | 121/765 [00:22<01:52,  5.74it/s]

[120/765]  raw='pass'  → → 1
[121/765]  raw='pass'  → → 1

 16%|█▌        | 123/765 [00:22<01:53,  5.68it/s]

[122/765]  raw='pass'  → → 1
[123/765]  raw='pass'  → → 1

 16%|█▋        | 125/765 [00:22<01:50,  5.79it/s]

[124/765]  raw='pass'  → → 1
[125/765]  raw='pass'  → → 1

 17%|█▋        | 127/765 [00:23<01:47,  5.92it/s]

[126/765]  raw='pass'  → → 1
[127/765]  raw='pass'  → → 1

 17%|█▋        | 129/765 [00:23<01:46,  5.98it/s]

[128/765]  raw='pass'  → → 1
[129/765]  raw='fail'  → → 0

 17%|█▋        | 131/765 [00:24<01:48,  5.86it/s]

[130/765]  raw='pass'  → → 1
[131/765]  raw='pass'  → → 1

 17%|█▋        | 133/765 [00:24<01:45,  5.96it/s]

[132/765]  raw='pass'  → → 1
[133/765]  raw='pass'  → → 1

 18%|█▊        | 135/765 [00:24<01:44,  6.03it/s]

[134/765]  raw='fail'  → → 0
[135/765]  raw='pass'  → → 1

 18%|█▊        | 136/765 [00:24<01:44,  6.03it/s]

[136/765]  raw='pass'  → → 1

 18%|█▊        | 138/765 [00:25<01:52,  5.58it/s]

[137/765]  raw='pass'  → → 1
[138/765]  raw='fail'  → → 0

 18%|█▊        | 140/765 [00:25<01:54,  5.44it/s]

[139/765]  raw='pass'  → → 1
[140/765]  raw='pass'  → → 1

 19%|█▊        | 142/765 [00:25<01:51,  5.58it/s]

[141/765]  raw='fail'  → → 0
[142/765]  raw='fail'  → → 0

 19%|█▊        | 143/765 [00:26<01:49,  5.70it/s]

[143/765]  raw='pass'  → → 1

 19%|█▉        | 145/765 [00:26<01:58,  5.24it/s]

[144/765]  raw='pass'  → → 1
[145/765]  raw='pass'  → → 1

 19%|█▉        | 146/765 [00:26<01:53,  5.46it/s]

[146/765]  raw='fail'  → → 0

 19%|█▉        | 148/765 [00:27<01:56,  5.28it/s]

[147/765]  raw='pass'  → → 1
[148/765]  raw='pass'  → → 1

 20%|█▉        | 150/765 [00:27<01:49,  5.62it/s]

[149/765]  raw='fail'  → → 0
[150/765]  raw='fail'  → → 0

 20%|█▉        | 152/765 [00:27<01:51,  5.48it/s]

[151/765]  raw='pass'  → → 1
[152/765]  raw='fail'  → → 0

 20%|██        | 154/765 [00:28<01:47,  5.67it/s]

[153/765]  raw='pass'  → → 1
[154/765]  raw='fail'  → → 0

 20%|██        | 156/765 [00:28<01:49,  5.57it/s]

[155/765]  raw='pass'  → → 1
[156/765]  raw='pass'  → → 1

 21%|██        | 158/765 [00:28<01:51,  5.45it/s]

[157/765]  raw='fail'  → → 0
[158/765]  raw='fail'  → → 0

 21%|██        | 160/765 [00:29<01:50,  5.48it/s]

[159/765]  raw='pass'  → → 1
[160/765]  raw='fail'  → → 0

 21%|██        | 162/765 [00:29<01:44,  5.76it/s]

[161/765]  raw='pass'  → → 1
[162/765]  raw='pass'  → → 1

 21%|██▏       | 164/765 [00:29<01:42,  5.87it/s]

[163/765]  raw='pass'  → → 1
[164/765]  raw='pass'  → → 1

 22%|██▏       | 166/765 [00:30<01:40,  5.96it/s]

[165/765]  raw='fail'  → → 0
[166/765]  raw='fail'  → → 0

 22%|██▏       | 168/765 [00:30<01:39,  5.97it/s]

[167/765]  raw='pass'  → → 1
[168/765]  raw='fail'  → → 0

 22%|██▏       | 170/765 [00:30<01:39,  5.95it/s]

[169/765]  raw='pass'  → → 1
[170/765]  raw='pass'  → → 1

 22%|██▏       | 172/765 [00:31<01:43,  5.75it/s]

[171/765]  raw='pass'  → → 1
[172/765]  raw='pass'  → → 1

 23%|██▎       | 173/765 [00:31<01:51,  5.33it/s]

[173/765]  raw='pass'  → → 1

 23%|██▎       | 175/765 [00:31<01:49,  5.38it/s]

[174/765]  raw='pass'  → → 1
[175/765]  raw='pass'  → → 1

 23%|██▎       | 177/765 [00:32<01:43,  5.69it/s]

[176/765]  raw='pass'  → → 1
[177/765]  raw='fail'  → → 0

 23%|██▎       | 178/765 [00:32<01:44,  5.61it/s]

[178/765]  raw='pass'  → → 1

 24%|██▎       | 180/765 [00:32<01:47,  5.42it/s]

[179/765]  raw='pass'  → → 1
[180/765]  raw='fail'  → → 0

 24%|██▍       | 182/765 [00:33<01:40,  5.80it/s]

[181/765]  raw='pass'  → → 1
[182/765]  raw='fail'  → → 0

 24%|██▍       | 184/765 [00:33<01:38,  5.91it/s]

[183/765]  raw='pass'  → → 1
[184/765]  raw='fail'  → → 0

 24%|██▍       | 185/765 [00:33<01:38,  5.86it/s]

[185/765]  raw='fail'  → → 0

 24%|██▍       | 187/765 [00:34<01:42,  5.62it/s]

[186/765]  raw='pass'  → → 1
[187/765]  raw='pass'  → → 1

 25%|██▍       | 189/765 [00:34<01:39,  5.77it/s]

[188/765]  raw='fail'  → → 0
[189/765]  raw='pass'  → → 1

 25%|██▍       | 191/765 [00:34<01:39,  5.79it/s]

[190/765]  raw='pass'  → → 1
[191/765]  raw='pass'  → → 1

 25%|██▌       | 193/765 [00:35<01:43,  5.50it/s]

[192/765]  raw='pass'  → → 1
[193/765]  raw='pass'  → → 1

 25%|██▌       | 194/765 [00:35<01:41,  5.60it/s]

[194/765]  raw='pass'  → → 1

 26%|██▌       | 196/765 [00:35<01:48,  5.24it/s]

[195/765]  raw='pass'  → → 1
[196/765]  raw='fail'  → → 0

 26%|██▌       | 198/765 [00:36<01:42,  5.53it/s]

[197/765]  raw='pass'  → → 1
[198/765]  raw='pass'  → → 1

 26%|██▌       | 200/765 [00:36<01:38,  5.76it/s]

[199/765]  raw='pass'  → → 1
[200/765]  raw='fail'  → → 0

 26%|██▋       | 202/765 [00:36<01:36,  5.85it/s]

[201/765]  raw='pass'  → → 1
[202/765]  raw='fail'  → → 0

 27%|██▋       | 204/765 [00:37<01:34,  5.92it/s]

[203/765]  raw='fail'  → → 0
[204/765]  raw='pass'  → → 1

 27%|██▋       | 206/765 [00:37<01:34,  5.94it/s]

[205/765]  raw='pass'  → → 1
[206/765]  raw='pass'  → → 1

 27%|██▋       | 208/765 [00:37<01:36,  5.76it/s]

[207/765]  raw='pass'  → → 1
[208/765]  raw='pass'  → → 1

 27%|██▋       | 210/765 [00:38<01:35,  5.84it/s]

[209/765]  raw='fail'  → → 0
[210/765]  raw='pass'  → → 1

 28%|██▊       | 212/765 [00:38<01:33,  5.91it/s]

[211/765]  raw='fail'  → → 0
[212/765]  raw='pass'  → → 1

 28%|██▊       | 214/765 [00:38<01:31,  6.02it/s]

[213/765]  raw='fail'  → → 0
[214/765]  raw='fail'  → → 0

 28%|██▊       | 216/765 [00:39<01:29,  6.12it/s]

[215/765]  raw='pass'  → → 1
[216/765]  raw='pass'  → → 1

 28%|██▊       | 217/765 [00:39<01:29,  6.12it/s]

[217/765]  raw='fail'  → → 0

 29%|██▊       | 219/765 [00:39<01:41,  5.36it/s]

[218/765]  raw='fail'  → → 0
[219/765]  raw='pass'  → → 1

 29%|██▉       | 221/765 [00:39<01:34,  5.77it/s]

[220/765]  raw='pass'  → → 1
[221/765]  raw='pass'  → → 1

 29%|██▉       | 223/765 [00:40<01:35,  5.69it/s]

[222/765]  raw='fail'  → → 0
[223/765]  raw='fail'  → → 0

 29%|██▉       | 225/765 [00:40<01:32,  5.82it/s]

[224/765]  raw='pass'  → → 1
[225/765]  raw='pass'  → → 1

 30%|██▉       | 227/765 [00:41<01:32,  5.79it/s]

[226/765]  raw='pass'  → → 1
[227/765]  raw='pass'  → → 1

 30%|██▉       | 229/765 [00:41<01:30,  5.95it/s]

[228/765]  raw='fail'  → → 0
[229/765]  raw='fail'  → → 0

 30%|███       | 231/765 [00:41<01:29,  5.99it/s]

[230/765]  raw='pass'  → → 1
[231/765]  raw='pass'  → → 1

 30%|███       | 233/765 [00:41<01:28,  5.99it/s]

[232/765]  raw='pass'  → → 1
[233/765]  raw='fail'  → → 0

 31%|███       | 235/765 [00:42<01:31,  5.82it/s]

[234/765]  raw='pass'  → → 1
[235/765]  raw='pass'  → → 1

 31%|███       | 237/765 [00:42<01:28,  5.98it/s]

[236/765]  raw='fail'  → → 0
[237/765]  raw='pass'  → → 1

 31%|███       | 239/765 [00:43<01:28,  5.95it/s]

[238/765]  raw='pass'  → → 1
[239/765]  raw='fail'  → → 0

 32%|███▏      | 241/765 [00:43<01:30,  5.77it/s]

[240/765]  raw='fail'  → → 0
[241/765]  raw='pass'  → → 1

 32%|███▏      | 243/765 [00:43<01:28,  5.87it/s]

[242/765]  raw='pass'  → → 1
[243/765]  raw='pass'  → → 1

 32%|███▏      | 245/765 [00:44<01:26,  5.99it/s]

[244/765]  raw='pass'  → → 1
[245/765]  raw='pass'  → → 1

 32%|███▏      | 247/765 [00:44<01:37,  5.29it/s]

[246/765]  raw='pass'  → → 1
[247/765]  raw='pass'  → → 1

 33%|███▎      | 249/765 [00:44<01:31,  5.64it/s]

[248/765]  raw='fail'  → → 0
[249/765]  raw='pass'  → → 1

 33%|███▎      | 251/765 [00:45<01:28,  5.82it/s]

[250/765]  raw='pass'  → → 1
[251/765]  raw='fail'  → → 0

 33%|███▎      | 253/765 [00:45<01:26,  5.91it/s]

[252/765]  raw='fail'  → → 0
[253/765]  raw='fail'  → → 0

 33%|███▎      | 254/765 [00:45<01:25,  5.94it/s]

[254/765]  raw='fail'  → → 0

 33%|███▎      | 256/765 [00:46<01:31,  5.55it/s]

[255/765]  raw='pass'  → → 1
[256/765]  raw='pass'  → → 1

 34%|███▎      | 258/765 [00:46<01:31,  5.55it/s]

[257/765]  raw='pass'  → → 1
[258/765]  raw='pass'  → → 1

 34%|███▍      | 260/765 [00:46<01:29,  5.66it/s]

[259/765]  raw='fail'  → → 0
[260/765]  raw='pass'  → → 1

 34%|███▍      | 262/765 [00:47<01:29,  5.60it/s]

[261/765]  raw='pass'  → → 1
[262/765]  raw='pass'  → → 1

 35%|███▍      | 264/765 [00:47<01:27,  5.70it/s]

[263/765]  raw='pass'  → → 1
[264/765]  raw='fail'  → → 0

 35%|███▍      | 266/765 [00:47<01:28,  5.66it/s]

[265/765]  raw='pass'  → → 1
[266/765]  raw='pass'  → → 1

 35%|███▌      | 268/765 [00:48<01:32,  5.39it/s]

[267/765]  raw='pass'  → → 1
[268/765]  raw='pass'  → → 1

 35%|███▌      | 270/765 [00:48<01:28,  5.62it/s]

[269/765]  raw='pass'  → → 1
[270/765]  raw='pass'  → → 1

 36%|███▌      | 272/765 [00:48<01:25,  5.74it/s]

[271/765]  raw='pass'  → → 1
[272/765]  raw='pass'  → → 1

 36%|███▌      | 274/765 [00:49<01:23,  5.87it/s]

[273/765]  raw='pass'  → → 1
[274/765]  raw='pass'  → → 1

 36%|███▌      | 276/765 [00:49<01:28,  5.54it/s]

[275/765]  raw='pass'  → → 1
[276/765]  raw='fail'  → → 0

 36%|███▋      | 278/765 [00:49<01:24,  5.76it/s]

[277/765]  raw='fail'  → → 0
[278/765]  raw='pass'  → → 1

 37%|███▋      | 280/765 [00:50<01:23,  5.83it/s]

[279/765]  raw='fail'  → → 0
[280/765]  raw='fail'  → → 0

 37%|███▋      | 282/765 [00:50<01:27,  5.53it/s]

[281/765]  raw='pass'  → → 1
[282/765]  raw='fail'  → → 0

 37%|███▋      | 284/765 [00:51<01:25,  5.65it/s]

[283/765]  raw='pass'  → → 1
[284/765]  raw='pass'  → → 1

 37%|███▋      | 286/765 [00:51<01:22,  5.81it/s]

[285/765]  raw='fail'  → → 0
[286/765]  raw='fail'  → → 0

 38%|███▊      | 288/765 [00:51<01:20,  5.90it/s]

[287/765]  raw='pass'  → → 1
[288/765]  raw='pass'  → → 1

 38%|███▊      | 290/765 [00:52<01:20,  5.91it/s]

[289/765]  raw='pass'  → → 1
[290/765]  raw='fail'  → → 0

 38%|███▊      | 292/765 [00:52<01:20,  5.89it/s]

[291/765]  raw='pass'  → → 1
[292/765]  raw='fail'  → → 0

 38%|███▊      | 293/765 [00:52<01:21,  5.81it/s]

[293/765]  raw='pass'  → → 1

 39%|███▊      | 295/765 [00:52<01:25,  5.51it/s]

[294/765]  raw='pass'  → → 1
[295/765]  raw='fail'  → → 0

 39%|███▉      | 297/765 [00:53<01:22,  5.70it/s]

[296/765]  raw='pass'  → → 1
[297/765]  raw='pass'  → → 1

 39%|███▉      | 298/765 [00:53<01:20,  5.77it/s]

[298/765]  raw='fail'  → → 0

 39%|███▉      | 300/765 [00:53<01:24,  5.47it/s]

[299/765]  raw='pass'  → → 1
[300/765]  raw='pass'  → → 1

 39%|███▉      | 302/765 [00:54<01:21,  5.68it/s]

[301/765]  raw='pass'  → → 1
[302/765]  raw='fail'  → → 0

 40%|███▉      | 304/765 [00:54<01:27,  5.30it/s]

[303/765]  raw='pass'  → → 1
[304/765]  raw='pass'  → → 1

 40%|████      | 306/765 [00:54<01:21,  5.66it/s]

[305/765]  raw='pass'  → → 1
[306/765]  raw='fail'  → → 0

 40%|████      | 308/765 [00:55<01:18,  5.82it/s]

[307/765]  raw='pass'  → → 1
[308/765]  raw='fail'  → → 0

 41%|████      | 310/765 [00:55<01:17,  5.88it/s]

[309/765]  raw='fail'  → → 0
[310/765]  raw='pass'  → → 1

 41%|████      | 312/765 [00:55<01:16,  5.91it/s]

[311/765]  raw='fail'  → → 0
[312/765]  raw='fail'  → → 0

 41%|████      | 314/765 [00:56<01:18,  5.74it/s]

[313/765]  raw='pass'  → → 1
[314/765]  raw='pass'  → → 1

 41%|████▏     | 316/765 [00:56<01:15,  5.91it/s]

[315/765]  raw='pass'  → → 1
[316/765]  raw='pass'  → → 1

 42%|████▏     | 318/765 [00:56<01:15,  5.90it/s]

[317/765]  raw='pass'  → → 1
[318/765]  raw='fail'  → → 0

 42%|████▏     | 320/765 [00:57<01:14,  5.99it/s]

[319/765]  raw='pass'  → → 1
[320/765]  raw='fail'  → → 0

 42%|████▏     | 322/765 [00:57<01:13,  6.07it/s]

[321/765]  raw='pass'  → → 1
[322/765]  raw='pass'  → → 1

 42%|████▏     | 324/765 [00:57<01:13,  6.04it/s]

[323/765]  raw='fail'  → → 0
[324/765]  raw='pass'  → → 1

 42%|████▏     | 325/765 [00:58<01:13,  5.99it/s]

[325/765]  raw='pass'  → → 1

 43%|████▎     | 327/765 [00:58<01:17,  5.68it/s]

[326/765]  raw='pass'  → → 1
[327/765]  raw='pass'  → → 1

 43%|████▎     | 329/765 [00:58<01:15,  5.77it/s]

[328/765]  raw='pass'  → → 1
[329/765]  raw='pass'  → → 1

 43%|████▎     | 331/765 [00:59<01:15,  5.78it/s]

[330/765]  raw='pass'  → → 1
[331/765]  raw='fail'  → → 0

 44%|████▎     | 333/765 [00:59<01:13,  5.84it/s]

[332/765]  raw='pass'  → → 1
[333/765]  raw='pass'  → → 1

 44%|████▍     | 335/765 [00:59<01:13,  5.81it/s]

[334/765]  raw='pass'  → → 1
[335/765]  raw='pass'  → → 1

 44%|████▍     | 337/765 [01:00<01:14,  5.78it/s]

[336/765]  raw='fail'  → → 0
[337/765]  raw='pass'  → → 1

 44%|████▍     | 338/765 [01:00<01:13,  5.79it/s]

[338/765]  raw='pass'  → → 1

 44%|████▍     | 340/765 [01:00<01:17,  5.51it/s]

[339/765]  raw='pass'  → → 1
[340/765]  raw='pass'  → → 1

 45%|████▍     | 342/765 [01:01<01:15,  5.62it/s]

[341/765]  raw='fail'  → → 0
[342/765]  raw='pass'  → → 1

 45%|████▍     | 344/765 [01:01<01:15,  5.60it/s]

[343/765]  raw='pass'  → → 1
[344/765]  raw='pass'  → → 1

 45%|████▌     | 345/765 [01:01<01:14,  5.65it/s]

[345/765]  raw='fail'  → → 0

 45%|████▌     | 347/765 [01:02<01:16,  5.45it/s]

[346/765]  raw='fail'  → → 0
[347/765]  raw='pass'  → → 1

 46%|████▌     | 349/765 [01:02<01:13,  5.62it/s]

[348/765]  raw='fail'  → → 0
[349/765]  raw='pass'  → → 1

 46%|████▌     | 351/765 [01:02<01:11,  5.75it/s]

[350/765]  raw='fail'  → → 0
[351/765]  raw='pass'  → → 1

 46%|████▌     | 353/765 [01:03<01:11,  5.75it/s]

[352/765]  raw='pass'  → → 1
[353/765]  raw='pass'  → → 1

 46%|████▋     | 355/765 [01:03<01:11,  5.75it/s]

[354/765]  raw='fail'  → → 0
[355/765]  raw='pass'  → → 1

 47%|████▋     | 357/765 [01:03<01:10,  5.77it/s]

[356/765]  raw='pass'  → → 1
[357/765]  raw='pass'  → → 1

 47%|████▋     | 359/765 [01:04<01:11,  5.65it/s]

[358/765]  raw='fail'  → → 0
[359/765]  raw='pass'  → → 1

 47%|████▋     | 361/765 [01:04<01:10,  5.77it/s]

[360/765]  raw='fail'  → → 0
[361/765]  raw='fail'  → → 0

 47%|████▋     | 363/765 [01:04<01:10,  5.69it/s]

[362/765]  raw='pass'  → → 1
[363/765]  raw='pass'  → → 1

 48%|████▊     | 364/765 [01:04<01:10,  5.73it/s]

[364/765]  raw='pass'  → → 1

 48%|████▊     | 366/765 [01:05<01:12,  5.50it/s]

[365/765]  raw='pass'  → → 1
[366/765]  raw='fail'  → → 0

 48%|████▊     | 368/765 [01:05<01:09,  5.73it/s]

[367/765]  raw='pass'  → → 1
[368/765]  raw='pass'  → → 1

 48%|████▊     | 370/765 [01:06<01:10,  5.59it/s]

[369/765]  raw='pass'  → → 1
[370/765]  raw='pass'  → → 1

 49%|████▊     | 372/765 [01:06<01:08,  5.75it/s]

[371/765]  raw='pass'  → → 1
[372/765]  raw='fail'  → → 0

 49%|████▉     | 374/765 [01:06<01:10,  5.52it/s]

[373/765]  raw='pass'  → → 1
[374/765]  raw='pass'  → → 1

 49%|████▉     | 376/765 [01:07<01:08,  5.71it/s]

[375/765]  raw='pass'  → → 1
[376/765]  raw='pass'  → → 1

 49%|████▉     | 377/765 [01:07<01:07,  5.78it/s]

[377/765]  raw='pass'  → → 1

 50%|████▉     | 379/765 [01:07<01:09,  5.54it/s]

[378/765]  raw='fail'  → → 0
[379/765]  raw='pass'  → → 1

 50%|████▉     | 381/765 [01:08<01:09,  5.56it/s]

[380/765]  raw='fail'  → → 0
[381/765]  raw='pass'  → → 1

 50%|█████     | 383/765 [01:08<01:05,  5.81it/s]

[382/765]  raw='pass'  → → 1
[383/765]  raw='pass'  → → 1

 50%|█████     | 385/765 [01:08<01:04,  5.85it/s]

[384/765]  raw='pass'  → → 1
[385/765]  raw='fail'  → → 0

 51%|█████     | 387/765 [01:09<01:05,  5.78it/s]

[386/765]  raw='fail'  → → 0
[387/765]  raw='pass'  → → 1

 51%|█████     | 389/765 [01:09<01:04,  5.83it/s]

[388/765]  raw='pass'  → → 1
[389/765]  raw='pass'  → → 1

 51%|█████     | 391/765 [01:09<01:03,  5.86it/s]

[390/765]  raw='pass'  → → 1
[391/765]  raw='pass'  → → 1

 51%|█████▏    | 393/765 [01:10<01:02,  5.94it/s]

[392/765]  raw='fail'  → → 0
[393/765]  raw='pass'  → → 1

 52%|█████▏    | 395/765 [01:10<01:10,  5.24it/s]

[394/765]  raw='pass'  → → 1
[395/765]  raw='pass'  → → 1

 52%|█████▏    | 397/765 [01:10<01:06,  5.52it/s]

[396/765]  raw='pass'  → → 1
[397/765]  raw='fail'  → → 0

 52%|█████▏    | 399/765 [01:11<01:03,  5.76it/s]

[398/765]  raw='pass'  → → 1
[399/765]  raw='fail'  → → 0

 52%|█████▏    | 401/765 [01:11<01:03,  5.78it/s]

[400/765]  raw='fail'  → → 0
[401/765]  raw='pass'  → → 1

 53%|█████▎    | 403/765 [01:11<01:03,  5.74it/s]

[402/765]  raw='fail'  → → 0
[403/765]  raw='fail'  → → 0

 53%|█████▎    | 405/765 [01:12<01:02,  5.78it/s]

[404/765]  raw='pass'  → → 1
[405/765]  raw='pass'  → → 1

 53%|█████▎    | 406/765 [01:12<01:01,  5.81it/s]

[406/765]  raw='fail'  → → 0

 53%|█████▎    | 408/765 [01:12<01:03,  5.58it/s]

[407/765]  raw='pass'  → → 1
[408/765]  raw='pass'  → → 1

 54%|█████▎    | 410/765 [01:13<01:01,  5.81it/s]

[409/765]  raw='pass'  → → 1
[410/765]  raw='pass'  → → 1

 54%|█████▍    | 412/765 [01:13<01:03,  5.57it/s]

[411/765]  raw='pass'  → → 1
[412/765]  raw='pass'  → → 1

 54%|█████▍    | 414/765 [01:13<01:04,  5.48it/s]

[413/765]  raw='fail'  → → 0
[414/765]  raw='pass'  → → 1

 54%|█████▍    | 416/765 [01:14<01:00,  5.79it/s]

[415/765]  raw='fail'  → → 0
[416/765]  raw='pass'  → → 1

 55%|█████▍    | 418/765 [01:14<00:58,  5.93it/s]

[417/765]  raw='fail'  → → 0
[418/765]  raw='fail'  → → 0

 55%|█████▍    | 420/765 [01:14<00:57,  6.00it/s]

[419/765]  raw='fail'  → → 0
[420/765]  raw='fail'  → → 0

 55%|█████▌    | 421/765 [01:15<00:56,  6.04it/s]

[421/765]  raw='pass'  → → 1

 55%|█████▌    | 423/765 [01:15<01:02,  5.46it/s]

[422/765]  raw='pass'  → → 1
[423/765]  raw='pass'  → → 1

 56%|█████▌    | 425/765 [01:15<00:59,  5.75it/s]

[424/765]  raw='pass'  → → 1
[425/765]  raw='fail'  → → 0

 56%|█████▌    | 426/765 [01:15<00:59,  5.65it/s]

[426/765]  raw='fail'  → → 0

 56%|█████▌    | 428/765 [01:16<01:04,  5.22it/s]

[427/765]  raw='pass'  → → 1
[428/765]  raw='pass'  → → 1

 56%|█████▌    | 430/765 [01:16<00:59,  5.60it/s]

[429/765]  raw='pass'  → → 1
[430/765]  raw='pass'  → → 1

 56%|█████▋    | 432/765 [01:17<00:57,  5.79it/s]

[431/765]  raw='pass'  → → 1
[432/765]  raw='pass'  → → 1

 57%|█████▋    | 434/765 [01:17<00:55,  5.92it/s]

[433/765]  raw='fail'  → → 0
[434/765]  raw='pass'  → → 1

 57%|█████▋    | 436/765 [01:17<00:54,  6.04it/s]

[435/765]  raw='pass'  → → 1
[436/765]  raw='fail'  → → 0

 57%|█████▋    | 438/765 [01:17<00:53,  6.13it/s]

[437/765]  raw='fail'  → → 0
[438/765]  raw='pass'  → → 1

 58%|█████▊    | 440/765 [01:18<00:52,  6.13it/s]

[439/765]  raw='pass'  → → 1
[440/765]  raw='pass'  → → 1

 58%|█████▊    | 442/765 [01:18<00:52,  6.14it/s]

[441/765]  raw='fail'  → → 0
[442/765]  raw='pass'  → → 1

 58%|█████▊    | 444/765 [01:18<00:52,  6.08it/s]

[443/765]  raw='pass'  → → 1
[444/765]  raw='fail'  → → 0

 58%|█████▊    | 446/765 [01:19<00:53,  6.00it/s]

[445/765]  raw='pass'  → → 1
[446/765]  raw='pass'  → → 1

 59%|█████▊    | 448/765 [01:19<00:53,  5.96it/s]

[447/765]  raw='pass'  → → 1
[448/765]  raw='pass'  → → 1

 59%|█████▉    | 450/765 [01:19<00:52,  5.99it/s]

[449/765]  raw='fail'  → → 0
[450/765]  raw='fail'  → → 0

 59%|█████▉    | 452/765 [01:20<00:51,  6.04it/s]

[451/765]  raw='pass'  → → 1
[452/765]  raw='pass'  → → 1

 59%|█████▉    | 454/765 [01:20<00:51,  6.06it/s]

[453/765]  raw='fail'  → → 0
[454/765]  raw='fail'  → → 0

 60%|█████▉    | 456/765 [01:20<00:51,  6.01it/s]

[455/765]  raw='fail'  → → 0
[456/765]  raw='fail'  → → 0

 60%|█████▉    | 458/765 [01:21<00:51,  6.01it/s]

[457/765]  raw='fail'  → → 0
[458/765]  raw='pass'  → → 1

 60%|██████    | 460/765 [01:21<00:50,  6.05it/s]

[459/765]  raw='pass'  → → 1
[460/765]  raw='pass'  → → 1

 60%|██████    | 462/765 [01:22<00:52,  5.75it/s]

[461/765]  raw='fail'  → → 0
[462/765]  raw='fail'  → → 0

 61%|██████    | 464/765 [01:22<00:50,  5.96it/s]

[463/765]  raw='pass'  → → 1
[464/765]  raw='fail'  → → 0

 61%|██████    | 466/765 [01:22<00:49,  6.00it/s]

[465/765]  raw='fail'  → → 0
[466/765]  raw='pass'  → → 1

 61%|██████    | 468/765 [01:22<00:49,  6.02it/s]

[467/765]  raw='pass'  → → 1
[468/765]  raw='pass'  → → 1

 61%|██████▏   | 469/765 [01:23<00:49,  6.03it/s]

[469/765]  raw='pass'  → → 1

 62%|██████▏   | 471/765 [01:23<00:51,  5.74it/s]

[470/765]  raw='fail'  → → 0
[471/765]  raw='pass'  → → 1

 62%|██████▏   | 473/765 [01:23<00:49,  5.92it/s]

[472/765]  raw='fail'  → → 0
[473/765]  raw='fail'  → → 0

 62%|██████▏   | 475/765 [01:24<00:48,  5.95it/s]

[474/765]  raw='pass'  → → 1
[475/765]  raw='pass'  → → 1

 62%|██████▏   | 477/765 [01:24<00:48,  5.91it/s]

[476/765]  raw='pass'  → → 1
[477/765]  raw='pass'  → → 1

 63%|██████▎   | 479/765 [01:24<00:47,  6.01it/s]

[478/765]  raw='fail'  → → 0
[479/765]  raw='pass'  → → 1

 63%|██████▎   | 481/765 [01:25<00:47,  5.98it/s]

[480/765]  raw='fail'  → → 0
[481/765]  raw='fail'  → → 0

 63%|██████▎   | 483/765 [01:25<00:46,  6.02it/s]

[482/765]  raw='pass'  → → 1
[483/765]  raw='pass'  → → 1

 63%|██████▎   | 485/765 [01:25<00:46,  6.01it/s]

[484/765]  raw='fail'  → → 0
[485/765]  raw='pass'  → → 1

 64%|██████▎   | 487/765 [01:26<00:47,  5.90it/s]

[486/765]  raw='pass'  → → 1
[487/765]  raw='fail'  → → 0

 64%|██████▍   | 489/765 [01:26<00:46,  5.90it/s]

[488/765]  raw='pass'  → → 1
[489/765]  raw='fail'  → → 0

 64%|██████▍   | 491/765 [01:26<00:46,  5.88it/s]

[490/765]  raw='pass'  → → 1
[491/765]  raw='pass'  → → 1

 64%|██████▍   | 493/765 [01:27<00:45,  5.94it/s]

[492/765]  raw='pass'  → → 1
[493/765]  raw='fail'  → → 0

 65%|██████▍   | 495/765 [01:27<00:44,  6.00it/s]

[494/765]  raw='pass'  → → 1
[495/765]  raw='pass'  → → 1

 65%|██████▍   | 497/765 [01:27<00:45,  5.93it/s]

[496/765]  raw='pass'  → → 1
[497/765]  raw='fail'  → → 0

 65%|██████▌   | 499/765 [01:28<00:45,  5.89it/s]

[498/765]  raw='pass'  → → 1
[499/765]  raw='pass'  → → 1

 65%|██████▌   | 501/765 [01:28<00:44,  5.90it/s]

[500/765]  raw='pass'  → → 1
[501/765]  raw='pass'  → → 1

 66%|██████▌   | 503/765 [01:28<00:44,  5.92it/s]

[502/765]  raw='pass'  → → 1
[503/765]  raw='pass'  → → 1

 66%|██████▌   | 505/765 [01:29<00:43,  5.96it/s]

[504/765]  raw='fail'  → → 0
[505/765]  raw='pass'  → → 1

 66%|██████▋   | 507/765 [01:29<00:43,  5.97it/s]

[506/765]  raw='pass'  → → 1
[507/765]  raw='fail'  → → 0

 67%|██████▋   | 509/765 [01:29<00:44,  5.74it/s]

[508/765]  raw='pass'  → → 1
[509/765]  raw='pass'  → → 1

 67%|██████▋   | 510/765 [01:30<00:44,  5.78it/s]

[510/765]  raw='pass'  → → 1

 67%|██████▋   | 512/765 [01:30<00:45,  5.57it/s]

[511/765]  raw='fail'  → → 0
[512/765]  raw='pass'  → → 1

 67%|██████▋   | 514/765 [01:30<00:43,  5.79it/s]

[513/765]  raw='fail'  → → 0
[514/765]  raw='pass'  → → 1

 67%|██████▋   | 515/765 [01:30<00:42,  5.88it/s]

[515/765]  raw='fail'  → → 0

 68%|██████▊   | 517/765 [01:31<00:43,  5.64it/s]

[516/765]  raw='pass'  → → 1
[517/765]  raw='fail'  → → 0

 68%|██████▊   | 519/765 [01:31<00:42,  5.80it/s]

[518/765]  raw='pass'  → → 1
[519/765]  raw='pass'  → → 1

 68%|██████▊   | 521/765 [01:32<00:42,  5.73it/s]

[520/765]  raw='pass'  → → 1
[521/765]  raw='pass'  → → 1

 68%|██████▊   | 523/765 [01:32<00:40,  5.92it/s]

[522/765]  raw='pass'  → → 1
[523/765]  raw='fail'  → → 0

 68%|██████▊   | 524/765 [01:32<00:40,  5.95it/s]

[524/765]  raw='pass'  → → 1

 69%|██████▉   | 526/765 [01:32<00:42,  5.67it/s]

[525/765]  raw='pass'  → → 1
[526/765]  raw='fail'  → → 0

 69%|██████▉   | 528/765 [01:33<00:40,  5.87it/s]

[527/765]  raw='fail'  → → 0
[528/765]  raw='fail'  → → 0

 69%|██████▉   | 530/765 [01:33<00:38,  6.06it/s]

[529/765]  raw='fail'  → → 0
[530/765]  raw='fail'  → → 0

 70%|██████▉   | 532/765 [01:33<00:37,  6.16it/s]

[531/765]  raw='pass'  → → 1
[532/765]  raw='pass'  → → 1

 70%|██████▉   | 534/765 [01:34<00:38,  6.05it/s]

[533/765]  raw='pass'  → → 1
[534/765]  raw='pass'  → → 1

 70%|███████   | 536/765 [01:34<00:38,  6.00it/s]

[535/765]  raw='pass'  → → 1
[536/765]  raw='pass'  → → 1

 70%|███████   | 538/765 [01:34<00:37,  6.09it/s]

[537/765]  raw='pass'  → → 1
[538/765]  raw='fail'  → → 0

 71%|███████   | 540/765 [01:35<00:37,  5.94it/s]

[539/765]  raw='pass'  → → 1
[540/765]  raw='pass'  → → 1

 71%|███████   | 542/765 [01:35<00:37,  5.95it/s]

[541/765]  raw='pass'  → → 1
[542/765]  raw='pass'  → → 1

 71%|███████   | 544/765 [01:35<00:37,  5.85it/s]

[543/765]  raw='pass'  → → 1
[544/765]  raw='fail'  → → 0

 71%|███████▏  | 546/765 [01:36<00:36,  5.94it/s]

[545/765]  raw='pass'  → → 1
[546/765]  raw='fail'  → → 0

 72%|███████▏  | 547/765 [01:36<00:36,  5.98it/s]

[547/765]  raw='fail'  → → 0

 72%|███████▏  | 549/765 [01:36<00:38,  5.60it/s]

[548/765]  raw='pass'  → → 1
[549/765]  raw='fail'  → → 0

 72%|███████▏  | 551/765 [01:37<00:36,  5.81it/s]

[550/765]  raw='pass'  → → 1
[551/765]  raw='pass'  → → 1

 72%|███████▏  | 553/765 [01:37<00:35,  5.90it/s]

[552/765]  raw='pass'  → → 1
[553/765]  raw='fail'  → → 0

 73%|███████▎  | 555/765 [01:37<00:35,  5.95it/s]

[554/765]  raw='pass'  → → 1
[555/765]  raw='pass'  → → 1

 73%|███████▎  | 557/765 [01:38<00:35,  5.78it/s]

[556/765]  raw='fail'  → → 0
[557/765]  raw='pass'  → → 1

 73%|███████▎  | 559/765 [01:38<00:35,  5.85it/s]

[558/765]  raw='pass'  → → 1
[559/765]  raw='pass'  → → 1

 73%|███████▎  | 561/765 [01:38<00:35,  5.70it/s]

[560/765]  raw='pass'  → → 1
[561/765]  raw='pass'  → → 1

 74%|███████▎  | 563/765 [01:39<00:34,  5.83it/s]

[562/765]  raw='fail'  → → 0
[563/765]  raw='pass'  → → 1

 74%|███████▍  | 565/765 [01:39<00:34,  5.77it/s]

[564/765]  raw='pass'  → → 1
[565/765]  raw='fail'  → → 0

 74%|███████▍  | 567/765 [01:39<00:33,  5.86it/s]

[566/765]  raw='fail'  → → 0
[567/765]  raw='pass'  → → 1

 74%|███████▍  | 569/765 [01:40<00:33,  5.81it/s]

[568/765]  raw='pass'  → → 1
[569/765]  raw='fail'  → → 0

 75%|███████▍  | 571/765 [01:40<00:32,  5.92it/s]

[570/765]  raw='pass'  → → 1
[571/765]  raw='fail'  → → 0

 75%|███████▍  | 573/765 [01:40<00:32,  5.95it/s]

[572/765]  raw='pass'  → → 1
[573/765]  raw='pass'  → → 1

 75%|███████▌  | 575/765 [01:41<00:32,  5.85it/s]

[574/765]  raw='pass'  → → 1
[575/765]  raw='pass'  → → 1

 75%|███████▌  | 577/765 [01:41<00:31,  5.89it/s]

[576/765]  raw='pass'  → → 1
[577/765]  raw='pass'  → → 1

 76%|███████▌  | 579/765 [01:41<00:31,  5.95it/s]

[578/765]  raw='fail'  → → 0
[579/765]  raw='pass'  → → 1

 76%|███████▌  | 581/765 [01:42<00:30,  5.99it/s]

[580/765]  raw='pass'  → → 1
[581/765]  raw='pass'  → → 1

 76%|███████▌  | 583/765 [01:42<00:30,  6.01it/s]

[582/765]  raw='pass'  → → 1
[583/765]  raw='fail'  → → 0

 76%|███████▋  | 585/765 [01:42<00:31,  5.69it/s]

[584/765]  raw='pass'  → → 1
[585/765]  raw='fail'  → → 0

 77%|███████▋  | 587/765 [01:43<00:30,  5.83it/s]

[586/765]  raw='fail'  → → 0
[587/765]  raw='pass'  → → 1

 77%|███████▋  | 589/765 [01:43<00:29,  5.91it/s]

[588/765]  raw='pass'  → → 1
[589/765]  raw='pass'  → → 1

 77%|███████▋  | 591/765 [01:43<00:28,  6.02it/s]

[590/765]  raw='pass'  → → 1
[591/765]  raw='pass'  → → 1

 78%|███████▊  | 593/765 [01:44<00:28,  6.12it/s]

[592/765]  raw='pass'  → → 1
[593/765]  raw='pass'  → → 1

 78%|███████▊  | 595/765 [01:44<00:28,  6.03it/s]

[594/765]  raw='fail'  → → 0
[595/765]  raw='pass'  → → 1

 78%|███████▊  | 597/765 [01:45<00:31,  5.32it/s]

[596/765]  raw='pass'  → → 1
[597/765]  raw='pass'  → → 1

 78%|███████▊  | 599/765 [01:45<00:29,  5.64it/s]

[598/765]  raw='pass'  → → 1
[599/765]  raw='pass'  → → 1

 79%|███████▊  | 601/765 [01:45<00:27,  5.94it/s]

[600/765]  raw='pass'  → → 1
[601/765]  raw='pass'  → → 1

 79%|███████▉  | 603/765 [01:46<00:28,  5.64it/s]

[602/765]  raw='pass'  → → 1
[603/765]  raw='pass'  → → 1

 79%|███████▉  | 605/765 [01:46<00:27,  5.79it/s]

[604/765]  raw='fail'  → → 0
[605/765]  raw='pass'  → → 1

 79%|███████▉  | 607/765 [01:46<00:26,  6.00it/s]

[606/765]  raw='fail'  → → 0
[607/765]  raw='pass'  → → 1

 80%|███████▉  | 609/765 [01:47<00:27,  5.69it/s]

[608/765]  raw='fail'  → → 0
[609/765]  raw='pass'  → → 1

 80%|███████▉  | 611/765 [01:47<00:27,  5.70it/s]

[610/765]  raw='pass'  → → 1
[611/765]  raw='pass'  → → 1

 80%|████████  | 613/765 [01:47<00:26,  5.84it/s]

[612/765]  raw='fail'  → → 0
[613/765]  raw='pass'  → → 1

 80%|████████  | 615/765 [01:48<00:24,  6.06it/s]

[614/765]  raw='pass'  → → 1
[615/765]  raw='pass'  → → 1

 81%|████████  | 617/765 [01:48<00:23,  6.17it/s]

[616/765]  raw='pass'  → → 1
[617/765]  raw='pass'  → → 1

 81%|████████  | 619/765 [01:48<00:23,  6.13it/s]

[618/765]  raw='pass'  → → 1
[619/765]  raw='pass'  → → 1

 81%|████████  | 620/765 [01:48<00:23,  6.10it/s]

[620/765]  raw='pass'  → → 1

 81%|████████▏ | 622/765 [01:49<00:26,  5.44it/s]

[621/765]  raw='pass'  → → 1
[622/765]  raw='pass'  → → 1

 82%|████████▏ | 624/765 [01:49<00:24,  5.72it/s]

[623/765]  raw='pass'  → → 1
[624/765]  raw='pass'  → → 1

 82%|████████▏ | 626/765 [01:49<00:23,  5.97it/s]

[625/765]  raw='pass'  → → 1
[626/765]  raw='fail'  → → 0

 82%|████████▏ | 628/765 [01:50<00:23,  5.94it/s]

[627/765]  raw='pass'  → → 1
[628/765]  raw='pass'  → → 1

 82%|████████▏ | 629/765 [01:50<00:22,  5.99it/s]

[629/765]  raw='pass'  → → 1

 82%|████████▏ | 630/765 [01:50<00:24,  5.52it/s]

[630/765]  raw='pass'  → → 1

 83%|████████▎ | 632/765 [01:51<00:26,  4.97it/s]

[631/765]  raw='fail'  → → 0
[632/765]  raw='pass'  → → 1

 83%|████████▎ | 634/765 [01:51<00:25,  5.21it/s]

[633/765]  raw='pass'  → → 1
[634/765]  raw='pass'  → → 1

 83%|████████▎ | 636/765 [01:51<00:23,  5.49it/s]

[635/765]  raw='pass'  → → 1
[636/765]  raw='pass'  → → 1

 83%|████████▎ | 638/765 [01:52<00:22,  5.65it/s]

[637/765]  raw='pass'  → → 1
[638/765]  raw='pass'  → → 1

 84%|████████▎ | 640/765 [01:52<00:21,  5.92it/s]

[639/765]  raw='fail'  → → 0
[640/765]  raw='fail'  → → 0

 84%|████████▍ | 641/765 [01:52<00:20,  5.97it/s]

[641/765]  raw='fail'  → → 0

 84%|████████▍ | 643/765 [01:53<00:21,  5.56it/s]

[642/765]  raw='pass'  → → 1
[643/765]  raw='pass'  → → 1

 84%|████████▍ | 645/765 [01:53<00:20,  5.88it/s]

[644/765]  raw='pass'  → → 1
[645/765]  raw='fail'  → → 0

 84%|████████▍ | 646/765 [01:53<00:20,  5.70it/s]

[646/765]  raw='pass'  → → 1

 85%|████████▍ | 648/765 [01:53<00:21,  5.50it/s]

[647/765]  raw='pass'  → → 1
[648/765]  raw='pass'  → → 1

 85%|████████▍ | 650/765 [01:54<00:20,  5.74it/s]

[649/765]  raw='fail'  → → 0
[650/765]  raw='fail'  → → 0

 85%|████████▌ | 652/765 [01:54<00:19,  5.93it/s]

[651/765]  raw='fail'  → → 0
[652/765]  raw='fail'  → → 0

 85%|████████▌ | 654/765 [01:54<00:18,  5.98it/s]

[653/765]  raw='fail'  → → 0
[654/765]  raw='fail'  → → 0

 86%|████████▌ | 656/765 [01:55<00:18,  6.02it/s]

[655/765]  raw='fail'  → → 0
[656/765]  raw='pass'  → → 1

 86%|████████▌ | 658/765 [01:55<00:17,  6.07it/s]

[657/765]  raw='fail'  → → 0
[658/765]  raw='fail'  → → 0

 86%|████████▋ | 660/765 [01:55<00:17,  6.08it/s]

[659/765]  raw='fail'  → → 0
[660/765]  raw='fail'  → → 0

 87%|████████▋ | 662/765 [01:56<00:18,  5.60it/s]

[661/765]  raw='pass'  → → 1
[662/765]  raw='pass'  → → 1

 87%|████████▋ | 664/765 [01:56<00:17,  5.81it/s]

[663/765]  raw='pass'  → → 1
[664/765]  raw='pass'  → → 1

 87%|████████▋ | 666/765 [01:57<00:17,  5.72it/s]

[665/765]  raw='fail'  → → 0
[666/765]  raw='pass'  → → 1

 87%|████████▋ | 668/765 [01:57<00:16,  5.86it/s]

[667/765]  raw='pass'  → → 1
[668/765]  raw='fail'  → → 0

 88%|████████▊ | 670/765 [01:57<00:16,  5.74it/s]

[669/765]  raw='pass'  → → 1
[670/765]  raw='pass'  → → 1

 88%|████████▊ | 672/765 [01:58<00:17,  5.43it/s]

[671/765]  raw='fail'  → → 0
[672/765]  raw='pass'  → → 1

 88%|████████▊ | 673/765 [01:58<00:16,  5.64it/s]

[673/765]  raw='fail'  → → 0

 88%|████████▊ | 675/765 [01:58<00:16,  5.57it/s]

[674/765]  raw='pass'  → → 1
[675/765]  raw='pass'  → → 1

 88%|████████▊ | 677/765 [01:58<00:14,  5.88it/s]

[676/765]  raw='fail'  → → 0
[677/765]  raw='fail'  → → 0

 89%|████████▉ | 679/765 [01:59<00:14,  5.96it/s]

[678/765]  raw='pass'  → → 1
[679/765]  raw='pass'  → → 1

 89%|████████▉ | 681/765 [01:59<00:14,  5.93it/s]

[680/765]  raw='pass'  → → 1
[681/765]  raw='pass'  → → 1

 89%|████████▉ | 683/765 [01:59<00:13,  5.98it/s]

[682/765]  raw='fail'  → → 0
[683/765]  raw='pass'  → → 1

 90%|████████▉ | 685/765 [02:00<00:13,  6.09it/s]

[684/765]  raw='pass'  → → 1
[685/765]  raw='fail'  → → 0

 90%|████████▉ | 687/765 [02:00<00:12,  6.07it/s]

[686/765]  raw='pass'  → → 1
[687/765]  raw='pass'  → → 1

 90%|█████████ | 689/765 [02:00<00:12,  6.02it/s]

[688/765]  raw='pass'  → → 1
[689/765]  raw='pass'  → → 1

 90%|█████████ | 691/765 [02:01<00:12,  6.12it/s]

[690/765]  raw='pass'  → → 1
[691/765]  raw='pass'  → → 1

 90%|█████████ | 692/765 [02:01<00:11,  6.15it/s]

[692/765]  raw='fail'  → → 0

 91%|█████████ | 694/765 [02:01<00:12,  5.74it/s]

[693/765]  raw='fail'  → → 0
[694/765]  raw='fail'  → → 0

 91%|█████████ | 696/765 [02:02<00:11,  5.95it/s]

[695/765]  raw='pass'  → → 1
[696/765]  raw='pass'  → → 1

 91%|█████████ | 698/765 [02:02<00:11,  6.03it/s]

[697/765]  raw='pass'  → → 1
[698/765]  raw='fail'  → → 0

 92%|█████████▏| 700/765 [02:02<00:10,  6.16it/s]

[699/765]  raw='fail'  → → 0
[700/765]  raw='fail'  → → 0

 92%|█████████▏| 702/765 [02:03<00:10,  6.15it/s]

[701/765]  raw='pass'  → → 1
[702/765]  raw='fail'  → → 0

 92%|█████████▏| 704/765 [02:03<00:09,  6.19it/s]

[703/765]  raw='pass'  → → 1
[704/765]  raw='pass'  → → 1

 92%|█████████▏| 706/765 [02:03<00:09,  6.24it/s]

[705/765]  raw='fail'  → → 0
[706/765]  raw='pass'  → → 1

 93%|█████████▎| 708/765 [02:04<00:10,  5.69it/s]

[707/765]  raw='pass'  → → 1
[708/765]  raw='pass'  → → 1

 93%|█████████▎| 710/765 [02:04<00:09,  5.84it/s]

[709/765]  raw='pass'  → → 1
[710/765]  raw='pass'  → → 1

 93%|█████████▎| 712/765 [02:04<00:08,  5.94it/s]

[711/765]  raw='fail'  → → 0
[712/765]  raw='pass'  → → 1

 93%|█████████▎| 714/765 [02:05<00:08,  5.88it/s]

[713/765]  raw='pass'  → → 1
[714/765]  raw='fail'  → → 0

 94%|█████████▎| 716/765 [02:05<00:08,  6.02it/s]

[715/765]  raw='fail'  → → 0
[716/765]  raw='pass'  → → 1

 94%|█████████▍| 718/765 [02:05<00:07,  6.11it/s]

[717/765]  raw='pass'  → → 1
[718/765]  raw='pass'  → → 1

 94%|█████████▍| 720/765 [02:06<00:07,  6.12it/s]

[719/765]  raw='pass'  → → 1
[720/765]  raw='fail'  → → 0

 94%|█████████▍| 722/765 [02:06<00:07,  6.04it/s]

[721/765]  raw='pass'  → → 1
[722/765]  raw='fail'  → → 0

 95%|█████████▍| 724/765 [02:06<00:06,  6.12it/s]

[723/765]  raw='fail'  → → 0
[724/765]  raw='pass'  → → 1

 95%|█████████▍| 726/765 [02:07<00:06,  6.13it/s]

[725/765]  raw='fail'  → → 0
[726/765]  raw='pass'  → → 1

 95%|█████████▌| 728/765 [02:07<00:05,  6.20it/s]

[727/765]  raw='pass'  → → 1
[728/765]  raw='pass'  → → 1

 95%|█████████▌| 730/765 [02:07<00:05,  6.21it/s]

[729/765]  raw='pass'  → → 1
[730/765]  raw='fail'  → → 0

 96%|█████████▌| 731/765 [02:07<00:05,  6.23it/s]

[731/765]  raw='pass'  → → 1

 96%|█████████▌| 733/765 [02:08<00:05,  5.86it/s]

[732/765]  raw='pass'  → → 1
[733/765]  raw='fail'  → → 0

 96%|█████████▌| 735/765 [02:08<00:04,  6.08it/s]

[734/765]  raw='pass'  → → 1
[735/765]  raw='fail'  → → 0

 96%|█████████▋| 737/765 [02:08<00:04,  6.07it/s]

[736/765]  raw='fail'  → → 0
[737/765]  raw='pass'  → → 1

 97%|█████████▋| 739/765 [02:09<00:04,  6.12it/s]

[738/765]  raw='pass'  → → 1
[739/765]  raw='fail'  → → 0

 97%|█████████▋| 741/765 [02:09<00:03,  6.14it/s]

[740/765]  raw='fail'  → → 0
[741/765]  raw='pass'  → → 1

 97%|█████████▋| 743/765 [02:09<00:03,  6.15it/s]

[742/765]  raw='pass'  → → 1
[743/765]  raw='fail'  → → 0

 97%|█████████▋| 745/765 [02:10<00:03,  6.09it/s]

[744/765]  raw='pass'  → → 1
[745/765]  raw='pass'  → → 1

 98%|█████████▊| 747/765 [02:10<00:02,  6.06it/s]

[746/765]  raw='fail'  → → 0
[747/765]  raw='pass'  → → 1

 98%|█████████▊| 749/765 [02:10<00:02,  6.04it/s]

[748/765]  raw='pass'  → → 1
[749/765]  raw='pass'  → → 1

 98%|█████████▊| 751/765 [02:11<00:02,  6.00it/s]

[750/765]  raw='fail'  → → 0
[751/765]  raw='fail'  → → 0

 98%|█████████▊| 753/765 [02:11<00:02,  5.91it/s]

[752/765]  raw='pass'  → → 1
[753/765]  raw='pass'  → → 1

 99%|█████████▊| 755/765 [02:11<00:01,  5.89it/s]

[754/765]  raw='fail'  → → 0
[755/765]  raw='pass'  → → 1

 99%|█████████▉| 757/765 [02:12<00:01,  5.84it/s]

[756/765]  raw='pass'  → → 1
[757/765]  raw='pass'  → → 1

 99%|█████████▉| 759/765 [02:12<00:01,  5.75it/s]

[758/765]  raw='fail'  → → 0
[759/765]  raw='fail'  → → 0

 99%|█████████▉| 761/765 [02:12<00:00,  5.93it/s]

[760/765]  raw='pass'  → → 1
[761/765]  raw='fail'  → → 0

100%|█████████▉| 763/765 [02:13<00:00,  5.76it/s]

[762/765]  raw='pass'  → → 1
[763/765]  raw='pass'  → → 1

100%|██████████| 765/765 [02:13<00:00,  5.72it/s]

[764/765]  raw='pass'  → → 1
[765/765]  raw='pass'  → → 1

In [ ]:
# Evaluate
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         0       1      pass         Fail         Pass
1         0       1      pass         Fail         Pass
2         0       1      pass         Fail         Pass
3         1       1      pass         Pass         Pass
4         0       1      pass         Fail         Pass
5         0       1      pass         Fail         Pass
6         1       1      pass         Pass         Pass
7         1       1      pass         Pass         Pass
8         1       1      pass         Pass         Pass
9         0       1      pass         Fail         Pass
10        0       0      fail         Fail         Fail
11        1       1      pass         Pass         Pass
12        1       1      pass         Pass         Pass
13        1       1      pass         Pass         Pass
14        1       1      pass         Pass         Pass
15        1       1      pass         Pass         Pass
16        1       1      pass         Pass         Pass
17        1       1      pass         Pass         Pass
18        0       1      pass         Fail         Pass
19        0       1      pass         Fail         Pass
20        0       1      pass         Fail         Pass
21        0       0      fail         Fail         Fail
22        0       1      pass         Fail         Pass
23        1       0      fail         Pass         Fail
24        1       1      pass         Pass         Pass
25        1       1      pass         Pass         Pass
26        0       1      pass         Fail         Pass
27        1       1      pass         Pass         Pass
28        1       1      pass         Pass         Pass
29        0       1      pass         Fail         Pass
30        1       1      pass         Pass         Pass
31        0       1      pass         Fail         Pass
32        1       1      pass         Pass         Pass
33        0       1      pass         Fail         Pass
34        0       0      fail         Fail         Fail
35        1       1      pass         Pass         Pass
36        1       0      fail         Pass         Fail
37        0       1      pass         Fail         Pass
38        1       1      pass         Pass         Pass
39        1       1      pass         Pass         Pass
40        1       1      pass         Pass         Pass
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        1       1      pass         Pass         Pass
44        0       1      pass         Fail         Pass
45        0       0      fail         Fail         Fail
46        0       1      pass         Fail         Pass
47        1       1      pass         Pass         Pass
48        0       0      fail         Fail         Fail
49        1       1      pass         Pass         Pass
50        0       1      pass         Fail         Pass
51        0       0      fail         Fail         Fail
52        1       1      pass         Pass         Pass
53        1       1      pass         Pass         Pass
54        0       1      pass         Fail         Pass
55        0       1      pass         Fail         Pass
56        0       1      pass         Fail         Pass
57        0       1      pass         Fail         Pass
58        0       1      pass         Fail         Pass
59        0       0      fail         Fail         Fail
60        1       1      pass         Pass         Pass
61        0       1      pass         Fail         Pass
62        1       0      fail         Pass         Fail
63        0       0      fail         Fail         Fail
64        0       0      fail         Fail         Fail
65        1       1      pass         Pass         Pass
66        1       1      pass         Pass         Pass
67        0       1      pass         Fail         Pass
68        1       1      pass         Pass         Pass
69        0       1      pass         Fail         Pass
70        0       1      pass         Fail         Pass
71        0       0      fail         Fail         Fail
72        0       0      fail         Fail         Fail
73        0       0      fail         Fail         Fail
74        0       0      fail         Fail         Fail
75        1       1      pass         Pass         Pass
76        0       0      fail         Fail         Fail
77        1       0      fail         Pass         Fail
78        0       0      fail         Fail         Fail
79        1       1      pass         Pass         Pass
80        1       0      fail         Pass         Fail
81        1       1      pass         Pass         Pass
82        1       1      pass         Pass         Pass
83        1       1      pass         Pass         Pass
84        0       1      pass         Fail         Pass
85        0       0      fail         Fail         Fail
86        0       0      fail         Fail         Fail
87        0       1      pass         Fail         Pass
88        1       1      pass         Pass         Pass
89        0       0      fail         Fail         Fail
90        1       1      pass         Pass         Pass
91        1       1      pass         Pass         Pass
92        1       0      fail         Pass         Fail
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       1      pass         Fail         Pass
96        0       0      fail         Fail         Fail
97        0       1      pass         Fail         Pass
98        0       0      fail         Fail         Fail
99        0       0      fail         Fail         Fail
100       0       1      pass         Fail         Pass
101       0       1      pass         Fail         Pass
102       0       1      pass         Fail         Pass
103       0       1      pass         Fail         Pass
104       0       0      fail         Fail         Fail
105       1       1      pass         Pass         Pass
106       1       1      pass         Pass         Pass
107       0       0      fail         Fail         Fail
108       1       1      pass         Pass         Pass
109       0       1      pass         Fail         Pass
110       0       1      pass         Fail         Pass
111       0       1      pass         Fail         Pass
112       1       1      pass         Pass         Pass
113       0       1      pass         Fail         Pass
114       0       1      pass         Fail         Pass
115       0       1      pass         Fail         Pass
116       1       0      fail         Pass         Fail
117       1       1      pass         Pass         Pass
118       0       1      pass         Fail         Pass
119       1       1      pass         Pass         Pass
120       1       1      pass         Pass         Pass
121       1       1      pass         Pass         Pass
122       1       1      pass         Pass         Pass
123       1       1      pass         Pass         Pass
124       0       1      pass         Fail         Pass
125       0       1      pass         Fail         Pass
126       0       1      pass         Fail         Pass
127       0       1      pass         Fail         Pass
128       0       0      fail         Fail         Fail
129       1       1      pass         Pass         Pass
130       0       1      pass         Fail         Pass
131       0       1      pass         Fail         Pass
132       0       1      pass         Fail         Pass
133       0       0      fail         Fail         Fail
134       0       1      pass         Fail         Pass
135       0       1      pass         Fail         Pass
136       1       1      pass         Pass         Pass
137       1       0      fail         Pass         Fail
138       1       1      pass         Pass         Pass
139       0       1      pass         Fail         Pass
140       0       0      fail         Fail         Fail
141       0       0      fail         Fail         Fail
142       1       1      pass         Pass         Pass
143       1       1      pass         Pass         Pass
144       0       1      pass         Fail         Pass
145       1       0      fail         Pass         Fail
146       1       1      pass         Pass         Pass
147       1       1      pass         Pass         Pass
148       1       0      fail         Pass         Fail
149       0       0      fail         Fail         Fail
150       1       1      pass         Pass         Pass
151       0       0      fail         Fail         Fail
152       1       1      pass         Pass         Pass
153       0       0      fail         Fail         Fail
154       0       1      pass         Fail         Pass
155       1       1      pass         Pass         Pass
156       0       0      fail         Fail         Fail
157       1       0      fail         Pass         Fail
158       1       1      pass         Pass         Pass
159       1       0      fail         Pass         Fail
160       0       1      pass         Fail         Pass
161       0       1      pass         Fail         Pass
162       0       1      pass         Fail         Pass
163       1       1      pass         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0      fail         Fail         Fail
166       0       1      pass         Fail         Pass
167       0       0      fail         Fail         Fail
168       1       1      pass         Pass         Pass
169       1       1      pass         Pass         Pass
170       1       1      pass         Pass         Pass
171       1       1      pass         Pass         Pass
172       1       1      pass         Pass         Pass
173       1       1      pass         Pass         Pass
174       0       1      pass         Fail         Pass
175       0       1      pass         Fail         Pass
176       0       0      fail         Fail         Fail
177       0       1      pass         Fail         Pass
178       1       1      pass         Pass         Pass
179       0       0      fail         Fail         Fail
180       0       1      pass         Fail         Pass
181       0       0      fail         Fail         Fail
182       0       1      pass         Fail         Pass
183       0       0      fail         Fail         Fail
184       1       0      fail         Pass         Fail
185       1       1      pass         Pass         Pass
186       0       1      pass         Fail         Pass
187       0       0      fail         Fail         Fail
188       1       1      pass         Pass         Pass
189       1       1      pass         Pass         Pass
190       0       1      pass         Fail         Pass
191       1       1      pass         Pass         Pass
192       0       1      pass         Fail         Pass
193       0       1      pass         Fail         Pass
194       1       1      pass         Pass         Pass
195       0       0      fail         Fail         Fail
196       1       1      pass         Pass         Pass
197       0       1      pass         Fail         Pass
198       1       1      pass         Pass         Pass
199       0       0      fail         Fail         Fail
200       0       1      pass         Fail         Pass
201       1       0      fail         Pass         Fail
202       0       0      fail         Fail         Fail
203       1       1      pass         Pass         Pass
204       0       1      pass         Fail         Pass
205       0       1      pass         Fail         Pass
206       1       1      pass         Pass         Pass
207       0       1      pass         Fail         Pass
208       0       0      fail         Fail         Fail
209       0       1      pass         Fail         Pass
210       0       0      fail         Fail         Fail
211       0       1      pass         Fail         Pass
212       1       0      fail         Pass         Fail
213       0       0      fail         Fail         Fail
214       0       1      pass         Fail         Pass
215       0       1      pass         Fail         Pass
216       0       0      fail         Fail         Fail
217       1       0      fail         Pass         Fail
218       1       1      pass         Pass         Pass
219       0       1      pass         Fail         Pass
220       0       1      pass         Fail         Pass
221       0       0      fail         Fail         Fail
222       1       0      fail         Pass         Fail
223       1       1      pass         Pass         Pass
224       0       1      pass         Fail         Pass
225       1       1      pass         Pass         Pass
226       0       1      pass         Fail         Pass
227       0       0      fail         Fail         Fail
228       0       0      fail         Fail         Fail
229       0       1      pass         Fail         Pass
230       1       1      pass         Pass         Pass
231       1       1      pass         Pass         Pass
232       0       0      fail         Fail         Fail
233       0       1      pass         Fail         Pass
234       1       1      pass         Pass         Pass
235       0       0      fail         Fail         Fail
236       0       1      pass         Fail         Pass
237       0       1      pass         Fail         Pass
238       1       0      fail         Pass         Fail
239       0       0      fail         Fail         Fail
240       0       1      pass         Fail         Pass
241       0       1      pass         Fail         Pass
242       0       1      pass         Fail         Pass
243       0       1      pass         Fail         Pass
244       0       1      pass         Fail         Pass
245       1       1      pass         Pass         Pass
246       1       1      pass         Pass         Pass
247       0       0      fail         Fail         Fail
248       1       1      pass         Pass         Pass
249       0       1      pass         Fail         Pass
250       0       0      fail         Fail         Fail
251       1       0      fail         Pass         Fail
252       1       0      fail         Pass         Fail
253       0       0      fail         Fail         Fail
254       1       1      pass         Pass         Pass
255       0       1      pass         Fail         Pass
256       1       1      pass         Pass         Pass
257       0       1      pass         Fail         Pass
258       0       0      fail         Fail         Fail
259       1       1      pass         Pass         Pass
260       0       1      pass         Fail         Pass
261       1       1      pass         Pass         Pass
262       1       1      pass         Pass         Pass
263       0       0      fail         Fail         Fail
264       1       1      pass         Pass         Pass
265       1       1      pass         Pass         Pass
266       1       1      pass         Pass         Pass
267       1       1      pass         Pass         Pass
268       1       1      pass         Pass         Pass
269       0       1      pass         Fail         Pass
270       0       1      pass         Fail         Pass
271       1       1      pass         Pass         Pass
272       0       1      pass         Fail         Pass
273       1       1      pass         Pass         Pass
274       1       1      pass         Pass         Pass
275       0       0      fail         Fail         Fail
276       0       0      fail         Fail         Fail
277       0       1      pass         Fail         Pass
278       1       0      fail         Pass         Fail
279       0       0      fail         Fail         Fail
280       1       1      pass         Pass         Pass
281       0       0      fail         Fail         Fail
282       1       1      pass         Pass         Pass
283       0       1      pass         Fail         Pass
284       0       0      fail         Fail         Fail
285       1       0      fail         Pass         Fail
286       0       1      pass         Fail         Pass
287       1       1      pass         Pass         Pass
288       0       1      pass         Fail         Pass
289       0       0      fail         Fail         Fail
290       0       1      pass         Fail         Pass
291       0       0      fail         Fail         Fail
292       1       1      pass         Pass         Pass
293       1       1      pass         Pass         Pass
294       0       0      fail         Fail         Fail
295       1       1      pass         Pass         Pass
296       1       1      pass         Pass         Pass
297       1       0      fail         Pass         Fail
298       1       1      pass         Pass         Pass
299       0       1      pass         Fail         Pass
300       0       1      pass         Fail         Pass
301       0       0      fail         Fail         Fail
302       1       1      pass         Pass         Pass
303       0       1      pass         Fail         Pass
304       0       1      pass         Fail         Pass
305       0       0      fail         Fail         Fail
306       0       1      pass         Fail         Pass
307       0       0      fail         Fail         Fail
308       1       0      fail         Pass         Fail
309       0       1      pass         Fail         Pass
310       0       0      fail         Fail         Fail
311       0       0      fail         Fail         Fail
312       1       1      pass         Pass         Pass
313       1       1      pass         Pass         Pass
314       0       1      pass         Fail         Pass
315       0       1      pass         Fail         Pass
316       0       1      pass         Fail         Pass
317       0       0      fail         Fail         Fail
318       1       1      pass         Pass         Pass
319       0       0      fail         Fail         Fail
320       0       1      pass         Fail         Pass
321       0       1      pass         Fail         Pass
322       0       0      fail         Fail         Fail
323       0       1      pass         Fail         Pass
324       1       1      pass         Pass         Pass
325       1       1      pass         Pass         Pass
326       0       1      pass         Fail         Pass
327       1       1      pass         Pass         Pass
328       0       1      pass         Fail         Pass
329       1       1      pass         Pass         Pass
330       0       0      fail         Fail         Fail
331       0       1      pass         Fail         Pass
332       0       1      pass         Fail         Pass
333       0       1      pass         Fail         Pass
334       0       1      pass         Fail         Pass
335       0       0      fail         Fail         Fail
336       1       1      pass         Pass         Pass
337       0       1      pass         Fail         Pass
338       1       1      pass         Pass         Pass
339       1       1      pass         Pass         Pass
340       1       0      fail         Pass         Fail
341       1       1      pass         Pass         Pass
342       1       1      pass         Pass         Pass
343       1       1      pass         Pass         Pass
344       1       0      fail         Pass         Fail
345       1       0      fail         Pass         Fail
346       0       1      pass         Fail         Pass
347       1       0      fail         Pass         Fail
348       0       1      pass         Fail         Pass
349       0       0      fail         Fail         Fail
350       0       1      pass         Fail         Pass
351       1       1      pass         Pass         Pass
352       0       1      pass         Fail         Pass
353       0       0      fail         Fail         Fail
354       1       1      pass         Pass         Pass
355       0       1      pass         Fail         Pass

#### LoRA fintuning Qwen2 7B

import gc
import torch

In [ ]:
import gc
import torch

In [ ]:
# check which model variables exist in memory
model_vars = ["model", "ft_model", "base_model", "trainer"]
for var in model_vars:
    if var in dir():
        obj = eval(var)
        try:
            mb = round(obj.get_memory_footprint() / 1e6, 1)
            print(f"  {var:<12} → loaded  ({mb} MB)")
        except:
            print(f"  {var:<12} → loaded  (size unknown)")
    else:
        print(f"  {var:<12} → not in memory")

# overall GPU memory summary
print()
total  = torch.cuda.get_device_properties(0).total_memory / 1e9
free   = torch.cuda.mem_get_info()[0] / 1e9
used   = total - free
print(f"GPU total : {total:.2f} GB")
print(f"GPU used  : {used:.2f} GB")
print(f"GPU free  : {free:.2f} GB")

  model        → loaded  (5443.3 MB)
  ft_model     → not in memory
  base_model   → not in memory
  trainer      → not in memory

GPU total : 85.09 GB
GPU used  : 6.25 GB
GPU free  : 78.84 GB

In [ ]:
#  delete all loaded models
for var in ["model", "ft_model", "base_model", "trainer"]:
    if var in dir():
        exec(f"del {var}")
        print(f"  deleted {var}")

gc.collect()
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# check result
total = torch.cuda.get_device_properties(0).total_memory / 1e9
free  = torch.cuda.mem_get_info()[0] / 1e9
used  = total - free
print(f"\nGPU total : {total:.2f} GB")
print(f"GPU used  : {used:.2f} GB")
print(f"GPU free  : {free:.2f} GB")

  deleted model

GPU total : 15.64 GB
GPU used  : 10.57 GB
GPU free  : 5.06 GB

In [ ]:
import torch.nn as nn
print({n.split(".")[-1] for n, m in model.named_modules() if isinstance(m, nn.Linear)})
# expect: {'q_proj','k_proj','v_proj','o_proj','gate_proj','up_proj','down_proj','lm_head'}

{'v_proj', 'gate_proj', 'q_proj', 'o_proj', 'down_proj', 'up_proj', 'k_proj', 'lm_head'}

In [ ]:
# Cell 1: Imports & config
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training, PeftModel
from trl import SFTTrainer, SFTConfig
from datasets import Dataset
import torch
import gc

MODEL_NAME   = "Qwen/Qwen2-7B-Instruct"
ADAPTER_PATH = "./qwen2-lora-balanced-adapter"

# 4-bit quantization — float16 required for T4
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=[            # Qwen2 attention + MLP layers
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
)

In [ ]:
#Part ??????????

In [ ]:
train_df = X_train.copy();  train_df["binary_score"] = y_train.values
val_df   = X_val.copy();    val_df["binary_score"]   = y_val.values
X_val_prompts  = pd.DataFrame(val_df.apply(generate_test_prompt, axis=1), columns=["text"])
test_df  = X_test.copy();   test_df["binary_score"]  = y_test.values
y_true   = test_df["binary_score"].values
X_test_prompts = pd.DataFrame(test_df.apply(generate_test_prompt, axis=1), columns=["text"])

In [ ]:
fail_df = train_df[train_df["binary_score"] == 0]
pass_df = train_df[train_df["binary_score"] == 1]
train_balanced = pd.concat([
    fail_df.sample(n=len(pass_df), random_state=42),
    pass_df,
]).sample(frac=1, random_state=42).reset_index(drop=True)
print(train_balanced["binary_score"].value_counts().to_dict())

{1: 1505, 0: 1505}

In [ ]:
tokenizer.padding_side = "right"    # right for training (back to left for inference)

train_hf = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in train_balanced.iterrows()])
val_hf   = Dataset.from_list([make_prompt_completion(r, tokenizer) for _, r in val_df.iterrows()])

print(f"Train : {len(train_hf)}  Val : {len(val_hf)}")
print("Prompt ending:", repr(train_hf[0]["prompt"][-70:]))   # want ...<|im_end|>\n<|im_start|>assistant\n
print("Completion   :", repr(train_hf[0]["completion"]))     # 'Pass' or 'Fail'

Train : 3010  Val : 765
Prompt ending: 'd with one word only (Fail or Pass): <|im_end|>\n<|im_start|>assistant\n'
Completion   : 'Pass'

In [ ]:
model.config.use_cache = False
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

Notes

* increase max_length=3000, increases the timing like 1h more

In [ ]:
lens = [len(tokenizer.encode(ex["prompt"] + ex["completion"])) for ex in train_hf]
print("max:", max(lens), "| over 1024:", sum(l > 1024 for l in lens), "| over 3000:", sum(l > 3000 for l in lens))

max: 1949 | over 1024: 159 | over 3000: 0

In [ ]:
#A100 GPU, 20m
sft_config = SFTConfig(
    output_dir="./qwen2-lora-balanced",
    num_train_epochs=1,                      # verify this is what actually runs!
    per_device_train_batch_size=8,           # A100: real batches
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,           # effective batch = 16
    warmup_steps=100,                        # stability
    learning_rate=5e-5,
    max_grad_norm=0.3,
    fp16=False, bf16=True,                   # A100
    logging_steps=10,                        # more frequent logs on a shorter run
    eval_strategy="steps", eval_steps=50,
    save_strategy="steps", save_steps=50,
    load_best_model_at_end=True, metric_for_best_model="eval_loss",
    report_to="none",
    max_length=2000,                         # need to check qwen for sure its content window is not 2000
    completion_only_loss=True,
    optim="paged_adamw_8bit",
)



trainer = SFTTrainer(
    model=model, args=sft_config,
    train_dataset=train_hf,
    eval_dataset=val_hf.select(range(250)),
    processing_class=tokenizer,
)
trainer.train()

Adding EOS to train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

TrainOutput(global_step=189, training_loss=0.26061547748626224, metrics={'train_runtime': 1326.9615, 'train_samples_per_second': 2.268, 'train_steps_per_second': 0.142, 'total_flos': 1.243357050082345e+17, 'train_loss': 0.26061547748626224, 'epoch': 1.0})

In [ ]:
# inference setup + smoke test (defines model_ft)
tokenizer.padding_side = "left"
model_ft = trainer.model
model_ft.eval()
model_ft.config.use_cache = False

smoke = X_val_prompts.iloc[:1].reset_index(drop=True)
_, g = predict_decoder_only(smoke, model_ft, tokenizer)
print(repr(g[0]))    # want a clean 'pass' or 'fail'

100%|██████████| 1/1 [00:00<00:00,  1.56it/s]

[  1/1]  raw='pass'  → → 1
'pass'

In [ ]:
y_pred, y_generated = predict_decoder_only(X_test_prompts.reset_index(drop=True), model_ft, tokenizer)

pd.DataFrame({"y_true": y_true, "y_pred": y_pred, "generated": y_generated}) \
  .to_csv("/content/drive/MyDrive/qwen2_finetuned_test_results.csv", index=False)   # straight to Drive

valid = [i for i, p in enumerate(y_pred) if p != -1]
yt = y_true[valid]; yp = [y_pred[i] for i in valid]
print(f"Parsed: {len(valid)}/{len(y_pred)}")
print(f"Accuracy: {accuracy_score(yt, yp):.4f}")
print(classification_report(yt, yp, target_names=["Fail", "Pass"]))
print(confusion_matrix(yt, yp))

  0%|          | 1/765 [00:00<03:43,  3.43it/s]

[  1/765]  raw='fail'  → → 0

  0%|          | 2/765 [00:00<03:37,  3.51it/s]

[  2/765]  raw='pass'  → → 1

  0%|          | 3/765 [00:00<03:34,  3.55it/s]

[  3/765]  raw='fail'  → → 0

  1%|          | 4/765 [00:01<03:44,  3.39it/s]

[  4/765]  raw='pass'  → → 1

  1%|          | 5/765 [00:01<03:40,  3.44it/s]

[  5/765]  raw='fail'  → → 0

  1%|          | 6/765 [00:01<03:37,  3.49it/s]

[  6/765]  raw='fail'  → → 0

  1%|          | 7/765 [00:02<03:36,  3.50it/s]

[  7/765]  raw='pass'  → → 1

  1%|          | 8/765 [00:02<03:34,  3.52it/s]

[  8/765]  raw='fail'  → → 0

  1%|          | 9/765 [00:02<03:42,  3.40it/s]

[  9/765]  raw='pass'  → → 1

  1%|▏         | 10/765 [00:02<03:37,  3.47it/s]

[ 10/765]  raw='fail'  → → 0

  1%|▏         | 11/765 [00:03<03:40,  3.43it/s]

[ 11/765]  raw='fail'  → → 0

  2%|▏         | 12/765 [00:03<03:44,  3.36it/s]

[ 12/765]  raw='pass'  → → 1

  2%|▏         | 13/765 [00:03<03:39,  3.42it/s]

[ 13/765]  raw='pass'  → → 1

  2%|▏         | 14/765 [00:04<03:34,  3.50it/s]

[ 14/765]  raw='pass'  → → 1

  2%|▏         | 15/765 [00:04<03:32,  3.53it/s]

[ 15/765]  raw='fail'  → → 0

  2%|▏         | 16/765 [00:04<03:30,  3.56it/s]

[ 16/765]  raw='pass'  → → 1

  2%|▏         | 17/765 [00:04<03:29,  3.57it/s]

[ 17/765]  raw='fail'  → → 0

  2%|▏         | 18/765 [00:05<03:29,  3.56it/s]

[ 18/765]  raw='pass'  → → 1

  2%|▏         | 19/765 [00:05<03:31,  3.52it/s]

[ 19/765]  raw='fail'  → → 0

  3%|▎         | 20/765 [00:05<03:57,  3.14it/s]

[ 20/765]  raw='pass'  → → 1

  3%|▎         | 21/765 [00:06<03:48,  3.26it/s]

[ 21/765]  raw='fail'  → → 0

  3%|▎         | 22/765 [00:06<03:42,  3.34it/s]

[ 22/765]  raw='fail'  → → 0

  3%|▎         | 23/765 [00:06<03:36,  3.42it/s]

[ 23/765]  raw='fail'  → → 0

  3%|▎         | 24/765 [00:07<03:54,  3.17it/s]

[ 24/765]  raw='pass'  → → 1

  3%|▎         | 25/765 [00:07<03:47,  3.25it/s]

[ 25/765]  raw='pass'  → → 1

  3%|▎         | 26/765 [00:07<03:43,  3.30it/s]

[ 26/765]  raw='fail'  → → 0

  4%|▎         | 27/765 [00:07<03:38,  3.38it/s]

[ 27/765]  raw='fail'  → → 0

  4%|▎         | 28/765 [00:08<03:35,  3.43it/s]

[ 28/765]  raw='pass'  → → 1

  4%|▍         | 29/765 [00:08<03:33,  3.45it/s]

[ 29/765]  raw='pass'  → → 1

  4%|▍         | 30/765 [00:08<03:29,  3.50it/s]

[ 30/765]  raw='fail'  → → 0

  4%|▍         | 31/765 [00:09<03:27,  3.53it/s]

[ 31/765]  raw='pass'  → → 1

  4%|▍         | 32/765 [00:09<03:26,  3.55it/s]

[ 32/765]  raw='fail'  → → 0

  4%|▍         | 33/765 [00:09<03:45,  3.24it/s]

[ 33/765]  raw='pass'  → → 1

  4%|▍         | 34/765 [00:09<03:38,  3.34it/s]

[ 34/765]  raw='fail'  → → 0

  5%|▍         | 35/765 [00:10<03:33,  3.42it/s]

[ 35/765]  raw='fail'  → → 0

  5%|▍         | 36/765 [00:10<03:29,  3.48it/s]

[ 36/765]  raw='fail'  → → 0

  5%|▍         | 37/765 [00:10<03:26,  3.53it/s]

[ 37/765]  raw='pass'  → → 1

  5%|▍         | 38/765 [00:11<03:27,  3.51it/s]

[ 38/765]  raw='fail'  → → 0

  5%|▌         | 39/765 [00:11<03:25,  3.52it/s]

[ 39/765]  raw='pass'  → → 1

  5%|▌         | 40/765 [00:11<03:31,  3.43it/s]

[ 40/765]  raw='pass'  → → 1

  5%|▌         | 41/765 [00:12<03:58,  3.03it/s]

[ 41/765]  raw='pass'  → → 1

  5%|▌         | 42/765 [00:12<03:47,  3.18it/s]

[ 42/765]  raw='fail'  → → 0

  6%|▌         | 43/765 [00:12<03:38,  3.30it/s]

[ 43/765]  raw='fail'  → → 0

  6%|▌         | 44/765 [00:12<03:35,  3.35it/s]

[ 44/765]  raw='pass'  → → 1

  6%|▌         | 45/765 [00:13<03:30,  3.41it/s]

[ 45/765]  raw='fail'  → → 0

  6%|▌         | 46/765 [00:13<03:28,  3.44it/s]

[ 46/765]  raw='fail'  → → 0

  6%|▌         | 47/765 [00:13<03:25,  3.50it/s]

[ 47/765]  raw='pass'  → → 1

  6%|▋         | 48/765 [00:14<03:23,  3.52it/s]

[ 48/765]  raw='pass'  → → 1

  6%|▋         | 49/765 [00:14<03:22,  3.53it/s]

[ 49/765]  raw='fail'  → → 0

  7%|▋         | 50/765 [00:14<03:21,  3.55it/s]

[ 50/765]  raw='pass'  → → 1

  7%|▋         | 51/765 [00:14<03:20,  3.56it/s]

[ 51/765]  raw='pass'  → → 1

  7%|▋         | 52/765 [00:15<03:19,  3.57it/s]

[ 52/765]  raw='fail'  → → 0

  7%|▋         | 53/765 [00:15<03:19,  3.57it/s]

[ 53/765]  raw='pass'  → → 1

  7%|▋         | 54/765 [00:15<03:56,  3.00it/s]

[ 54/765]  raw='pass'  → → 1

  7%|▋         | 55/765 [00:16<03:45,  3.15it/s]

[ 55/765]  raw='fail'  → → 0

  7%|▋         | 56/765 [00:16<03:36,  3.27it/s]

[ 56/765]  raw='fail'  → → 0

  7%|▋         | 57/765 [00:16<03:29,  3.37it/s]

[ 57/765]  raw='fail'  → → 0

  8%|▊         | 58/765 [00:17<03:25,  3.44it/s]

[ 58/765]  raw='pass'  → → 1

  8%|▊         | 59/765 [00:17<03:22,  3.48it/s]

[ 59/765]  raw='pass'  → → 1

  8%|▊         | 60/765 [00:17<03:19,  3.54it/s]

[ 60/765]  raw='fail'  → → 0

  8%|▊         | 61/765 [00:17<03:19,  3.52it/s]

[ 61/765]  raw='pass'  → → 1

  8%|▊         | 62/765 [00:18<03:17,  3.57it/s]

[ 62/765]  raw='pass'  → → 1

  8%|▊         | 63/765 [00:18<03:21,  3.48it/s]

[ 63/765]  raw='pass'  → → 1

  8%|▊         | 64/765 [00:18<03:17,  3.55it/s]

[ 64/765]  raw='fail'  → → 0

  8%|▊         | 65/765 [00:18<03:15,  3.59it/s]

[ 65/765]  raw='fail'  → → 0

  9%|▊         | 66/765 [00:19<03:14,  3.59it/s]

[ 66/765]  raw='pass'  → → 1

  9%|▉         | 67/765 [00:19<03:19,  3.50it/s]

[ 67/765]  raw='pass'  → → 1

  9%|▉         | 68/765 [00:19<03:17,  3.52it/s]

[ 68/765]  raw='fail'  → → 0

  9%|▉         | 69/765 [00:20<03:14,  3.57it/s]

[ 69/765]  raw='fail'  → → 0

  9%|▉         | 70/765 [00:20<03:12,  3.61it/s]

[ 70/765]  raw='fail'  → → 0

  9%|▉         | 71/765 [00:20<03:11,  3.62it/s]

[ 71/765]  raw='fail'  → → 0

  9%|▉         | 72/765 [00:20<03:10,  3.65it/s]

[ 72/765]  raw='fail'  → → 0

 10%|▉         | 73/765 [00:21<03:09,  3.66it/s]

[ 73/765]  raw='fail'  → → 0

 10%|▉         | 74/765 [00:21<03:08,  3.66it/s]

[ 74/765]  raw='fail'  → → 0

 10%|▉         | 75/765 [00:21<03:08,  3.66it/s]

[ 75/765]  raw='fail'  → → 0

 10%|▉         | 76/765 [00:22<03:08,  3.65it/s]

[ 76/765]  raw='pass'  → → 1

 10%|█         | 77/765 [00:22<03:08,  3.64it/s]

[ 77/765]  raw='fail'  → → 0

 10%|█         | 78/765 [00:22<03:08,  3.64it/s]

[ 78/765]  raw='pass'  → → 1

 10%|█         | 79/765 [00:22<03:07,  3.66it/s]

[ 79/765]  raw='fail'  → → 0

 10%|█         | 80/765 [00:23<03:25,  3.33it/s]

[ 80/765]  raw='pass'  → → 1

 11%|█         | 81/765 [00:23<03:21,  3.39it/s]

[ 81/765]  raw='pass'  → → 1

 11%|█         | 82/765 [00:23<03:18,  3.44it/s]

[ 82/765]  raw='pass'  → → 1

 11%|█         | 83/765 [00:24<03:41,  3.08it/s]

[ 83/765]  raw='pass'  → → 1

 11%|█         | 84/765 [00:24<03:56,  2.88it/s]

[ 84/765]  raw='pass'  → → 1

 11%|█         | 85/765 [00:24<03:42,  3.05it/s]

[ 85/765]  raw='fail'  → → 0

 11%|█         | 86/765 [00:25<03:34,  3.17it/s]

[ 86/765]  raw='fail'  → → 0

 11%|█▏        | 87/765 [00:25<03:26,  3.28it/s]

[ 87/765]  raw='pass'  → → 1

 12%|█▏        | 88/765 [00:25<03:23,  3.33it/s]

[ 88/765]  raw='fail'  → → 0

 12%|█▏        | 89/765 [00:25<03:19,  3.39it/s]

[ 89/765]  raw='pass'  → → 1

 12%|█▏        | 90/765 [00:26<03:16,  3.43it/s]

[ 90/765]  raw='fail'  → → 0

 12%|█▏        | 91/765 [00:26<03:15,  3.44it/s]

[ 91/765]  raw='pass'  → → 1

 12%|█▏        | 92/765 [00:26<03:37,  3.09it/s]

[ 92/765]  raw='pass'  → → 1

 12%|█▏        | 93/765 [00:27<03:29,  3.20it/s]

[ 93/765]  raw='pass'  → → 1

 12%|█▏        | 94/765 [00:27<03:23,  3.30it/s]

[ 94/765]  raw='fail'  → → 0

 12%|█▏        | 95/765 [00:27<03:19,  3.35it/s]

[ 95/765]  raw='fail'  → → 0

 13%|█▎        | 96/765 [00:28<03:16,  3.41it/s]

[ 96/765]  raw='fail'  → → 0

 13%|█▎        | 97/765 [00:28<03:12,  3.46it/s]

[ 97/765]  raw='fail'  → → 0

 13%|█▎        | 98/765 [00:28<03:10,  3.51it/s]

[ 98/765]  raw='fail'  → → 0

 13%|█▎        | 99/765 [00:29<03:27,  3.21it/s]

[ 99/765]  raw='pass'  → → 1

 13%|█▎        | 100/765 [00:29<03:20,  3.31it/s]

[100/765]  raw='fail'  → → 0

 13%|█▎        | 101/765 [00:29<03:15,  3.39it/s]

[101/765]  raw='fail'  → → 0

 13%|█▎        | 102/765 [00:29<03:14,  3.42it/s]

[102/765]  raw='pass'  → → 1

 13%|█▎        | 103/765 [00:30<03:13,  3.42it/s]

[103/765]  raw='fail'  → → 0

 14%|█▎        | 104/765 [00:30<03:12,  3.44it/s]

[104/765]  raw='fail'  → → 0

 14%|█▎        | 105/765 [00:30<03:10,  3.46it/s]

[105/765]  raw='fail'  → → 0

 14%|█▍        | 106/765 [00:31<03:28,  3.16it/s]

[106/765]  raw='pass'  → → 1

 14%|█▍        | 107/765 [00:31<03:23,  3.24it/s]

[107/765]  raw='pass'  → → 1

 14%|█▍        | 108/765 [00:31<03:17,  3.33it/s]

[108/765]  raw='fail'  → → 0

 14%|█▍        | 109/765 [00:31<03:13,  3.39it/s]

[109/765]  raw='pass'  → → 1

 14%|█▍        | 110/765 [00:32<03:09,  3.45it/s]

[110/765]  raw='fail'  → → 0

 15%|█▍        | 111/765 [00:32<03:07,  3.49it/s]

[111/765]  raw='fail'  → → 0

 15%|█▍        | 112/765 [00:32<03:05,  3.53it/s]

[112/765]  raw='fail'  → → 0

 15%|█▍        | 113/765 [00:33<03:04,  3.54it/s]

[113/765]  raw='pass'  → → 1

 15%|█▍        | 114/765 [00:33<03:03,  3.54it/s]

[114/765]  raw='pass'  → → 1

 15%|█▌        | 115/765 [00:33<03:06,  3.48it/s]

[115/765]  raw='fail'  → → 0

 15%|█▌        | 116/765 [00:33<03:06,  3.49it/s]

[116/765]  raw='fail'  → → 0

 15%|█▌        | 117/765 [00:34<03:05,  3.50it/s]

[117/765]  raw='pass'  → → 1

 15%|█▌        | 118/765 [00:34<03:03,  3.52it/s]

[118/765]  raw='pass'  → → 1

 16%|█▌        | 119/765 [00:34<03:01,  3.56it/s]

[119/765]  raw='fail'  → → 0

 16%|█▌        | 120/765 [00:35<03:01,  3.55it/s]

[120/765]  raw='pass'  → → 1

 16%|█▌        | 121/765 [00:35<03:05,  3.47it/s]

[121/765]  raw='pass'  → → 1

 16%|█▌        | 122/765 [00:35<03:03,  3.51it/s]

[122/765]  raw='pass'  → → 1

 16%|█▌        | 123/765 [00:35<03:05,  3.46it/s]

[123/765]  raw='pass'  → → 1

 16%|█▌        | 124/765 [00:36<03:07,  3.42it/s]

[124/765]  raw='pass'  → → 1

 16%|█▋        | 125/765 [00:36<03:05,  3.46it/s]

[125/765]  raw='fail'  → → 0

 16%|█▋        | 126/765 [00:36<03:04,  3.47it/s]

[126/765]  raw='fail'  → → 0

 17%|█▋        | 127/765 [00:37<03:03,  3.49it/s]

[127/765]  raw='fail'  → → 0

 17%|█▋        | 128/765 [00:37<03:02,  3.50it/s]

[128/765]  raw='fail'  → → 0

 17%|█▋        | 129/765 [00:37<03:02,  3.49it/s]

[129/765]  raw='fail'  → → 0

 17%|█▋        | 130/765 [00:37<03:05,  3.42it/s]

[130/765]  raw='pass'  → → 1

 17%|█▋        | 131/765 [00:38<03:03,  3.45it/s]

[131/765]  raw='fail'  → → 0

 17%|█▋        | 132/765 [00:38<03:01,  3.48it/s]

[132/765]  raw='fail'  → → 0

 17%|█▋        | 133/765 [00:38<03:01,  3.49it/s]

[133/765]  raw='fail'  → → 0

 18%|█▊        | 134/765 [00:39<03:00,  3.49it/s]

[134/765]  raw='pass'  → → 1

 18%|█▊        | 135/765 [00:39<03:00,  3.48it/s]

[135/765]  raw='fail'  → → 0

 18%|█▊        | 136/765 [00:39<03:01,  3.47it/s]

[136/765]  raw='pass'  → → 1

 18%|█▊        | 137/765 [00:40<03:23,  3.09it/s]

[137/765]  raw='pass'  → → 1

 18%|█▊        | 138/765 [00:40<03:15,  3.20it/s]

[138/765]  raw='pass'  → → 1

 18%|█▊        | 139/765 [00:40<03:32,  2.94it/s]

[139/765]  raw='pass'  → → 1

 18%|█▊        | 140/765 [00:41<03:26,  3.03it/s]

[140/765]  raw='fail'  → → 0

 18%|█▊        | 141/765 [00:41<03:20,  3.11it/s]

[141/765]  raw='fail'  → → 0

 19%|█▊        | 142/765 [00:41<03:16,  3.17it/s]

[142/765]  raw='fail'  → → 0

 19%|█▊        | 143/765 [00:41<03:11,  3.26it/s]

[143/765]  raw='pass'  → → 1

 19%|█▉        | 144/765 [00:42<03:47,  2.73it/s]

[144/765]  raw='pass'  → → 1

 19%|█▉        | 145/765 [00:42<03:31,  2.93it/s]

[145/765]  raw='pass'  → → 1

 19%|█▉        | 146/765 [00:43<03:21,  3.08it/s]

[146/765]  raw='fail'  → → 0

 19%|█▉        | 147/765 [00:43<03:35,  2.86it/s]

[147/765]  raw='pass'  → → 1

 19%|█▉        | 148/765 [00:43<03:25,  3.01it/s]

[148/765]  raw='pass'  → → 1

 19%|█▉        | 149/765 [00:44<03:16,  3.13it/s]

[149/765]  raw='pass'  → → 1

 20%|█▉        | 150/765 [00:44<03:10,  3.23it/s]

[150/765]  raw='fail'  → → 0

 20%|█▉        | 151/765 [00:44<03:21,  3.05it/s]

[151/765]  raw='pass'  → → 1

 20%|█▉        | 152/765 [00:44<03:12,  3.18it/s]

[152/765]  raw='pass'  → → 1

 20%|██        | 153/765 [00:45<03:08,  3.24it/s]

[153/765]  raw='fail'  → → 0

 20%|██        | 154/765 [00:45<03:04,  3.30it/s]

[154/765]  raw='pass'  → → 1

 20%|██        | 155/765 [00:45<03:02,  3.35it/s]

[155/765]  raw='pass'  → → 1

 20%|██        | 156/765 [00:46<03:05,  3.29it/s]

[156/765]  raw='pass'  → → 1

 21%|██        | 157/765 [00:46<03:05,  3.28it/s]

[157/765]  raw='pass'  → → 1

 21%|██        | 158/765 [00:46<03:06,  3.25it/s]

[158/765]  raw='pass'  → → 1

 21%|██        | 159/765 [00:47<03:02,  3.32it/s]

[159/765]  raw='pass'  → → 1

 21%|██        | 160/765 [00:47<03:04,  3.28it/s]

[160/765]  raw='pass'  → → 1

 21%|██        | 161/765 [00:47<03:00,  3.35it/s]

[161/765]  raw='fail'  → → 0

 21%|██        | 162/765 [00:47<02:57,  3.41it/s]

[162/765]  raw='fail'  → → 0

 21%|██▏       | 163/765 [00:48<02:55,  3.43it/s]

[163/765]  raw='fail'  → → 0

 21%|██▏       | 164/765 [00:48<02:53,  3.46it/s]

[164/765]  raw='pass'  → → 1

 22%|██▏       | 165/765 [00:48<02:51,  3.49it/s]

[165/765]  raw='fail'  → → 0

 22%|██▏       | 166/765 [00:49<02:50,  3.50it/s]

[166/765]  raw='fail'  → → 0

 22%|██▏       | 167/765 [00:49<02:50,  3.52it/s]

[167/765]  raw='fail'  → → 0

 22%|██▏       | 168/765 [00:49<02:48,  3.54it/s]

[168/765]  raw='fail'  → → 0

 22%|██▏       | 169/765 [00:49<02:48,  3.53it/s]

[169/765]  raw='pass'  → → 1

 22%|██▏       | 170/765 [00:50<02:47,  3.55it/s]

[170/765]  raw='pass'  → → 1

 22%|██▏       | 171/765 [00:50<02:52,  3.45it/s]

[171/765]  raw='pass'  → → 1

 22%|██▏       | 172/765 [00:50<02:50,  3.48it/s]

[172/765]  raw='pass'  → → 1

 23%|██▎       | 173/765 [00:51<03:07,  3.17it/s]

[173/765]  raw='pass'  → → 1

 23%|██▎       | 174/765 [00:51<03:15,  3.02it/s]

[174/765]  raw='pass'  → → 1

 23%|██▎       | 175/765 [00:51<03:05,  3.19it/s]

[175/765]  raw='fail'  → → 0

 23%|██▎       | 176/765 [00:52<02:59,  3.29it/s]

[176/765]  raw='fail'  → → 0

 23%|██▎       | 177/765 [00:52<02:55,  3.34it/s]

[177/765]  raw='fail'  → → 0

 23%|██▎       | 178/765 [00:52<02:56,  3.33it/s]

[178/765]  raw='pass'  → → 1

 23%|██▎       | 179/765 [00:53<03:16,  2.98it/s]

[179/765]  raw='pass'  → → 1

 24%|██▎       | 180/765 [00:53<03:06,  3.14it/s]

[180/765]  raw='fail'  → → 0

 24%|██▎       | 181/765 [00:53<02:58,  3.27it/s]

[181/765]  raw='fail'  → → 0

 24%|██▍       | 182/765 [00:53<02:53,  3.36it/s]

[182/765]  raw='fail'  → → 0

 24%|██▍       | 183/765 [00:54<02:50,  3.42it/s]

[183/765]  raw='fail'  → → 0

 24%|██▍       | 184/765 [00:54<02:47,  3.46it/s]

[184/765]  raw='fail'  → → 0

 24%|██▍       | 185/765 [00:54<02:45,  3.49it/s]

[185/765]  raw='pass'  → → 1

 24%|██▍       | 186/765 [00:55<02:58,  3.25it/s]

[186/765]  raw='pass'  → → 1

 24%|██▍       | 187/765 [00:55<02:54,  3.32it/s]

[187/765]  raw='fail'  → → 0

 25%|██▍       | 188/765 [00:55<02:49,  3.40it/s]

[188/765]  raw='fail'  → → 0

 25%|██▍       | 189/765 [00:55<02:47,  3.44it/s]

[189/765]  raw='pass'  → → 1

 25%|██▍       | 190/765 [00:56<02:45,  3.47it/s]

[190/765]  raw='pass'  → → 1

 25%|██▍       | 191/765 [00:56<02:44,  3.50it/s]

[191/765]  raw='pass'  → → 1

 25%|██▌       | 192/765 [00:56<03:03,  3.13it/s]

[192/765]  raw='pass'  → → 1

 25%|██▌       | 193/765 [00:57<02:56,  3.23it/s]

[193/765]  raw='fail'  → → 0

 25%|██▌       | 194/765 [00:57<02:51,  3.33it/s]

[194/765]  raw='fail'  → → 0

 25%|██▌       | 195/765 [00:57<03:20,  2.84it/s]

[195/765]  raw='pass'  → → 1

 26%|██▌       | 196/765 [00:58<03:08,  3.01it/s]

[196/765]  raw='fail'  → → 0

 26%|██▌       | 197/765 [00:58<03:01,  3.13it/s]

[197/765]  raw='pass'  → → 1

 26%|██▌       | 198/765 [00:58<02:54,  3.25it/s]

[198/765]  raw='pass'  → → 1

 26%|██▌       | 199/765 [00:59<02:49,  3.34it/s]

[199/765]  raw='pass'  → → 1

 26%|██▌       | 200/765 [00:59<02:45,  3.41it/s]

[200/765]  raw='fail'  → → 0

 26%|██▋       | 201/765 [00:59<02:43,  3.45it/s]

[201/765]  raw='fail'  → → 0

 26%|██▋       | 202/765 [00:59<02:42,  3.47it/s]

[202/765]  raw='pass'  → → 1

 27%|██▋       | 203/765 [01:00<02:40,  3.49it/s]

[203/765]  raw='fail'  → → 0

 27%|██▋       | 204/765 [01:00<02:41,  3.47it/s]

[204/765]  raw='fail'  → → 0

 27%|██▋       | 205/765 [01:00<02:41,  3.48it/s]

[205/765]  raw='fail'  → → 0

 27%|██▋       | 206/765 [01:01<02:39,  3.50it/s]

[206/765]  raw='pass'  → → 1

 27%|██▋       | 207/765 [01:01<02:44,  3.39it/s]

[207/765]  raw='pass'  → → 1

 27%|██▋       | 208/765 [01:01<02:42,  3.43it/s]

[208/765]  raw='pass'  → → 1

 27%|██▋       | 209/765 [01:02<02:40,  3.46it/s]

[209/765]  raw='fail'  → → 0

 27%|██▋       | 210/765 [01:02<02:39,  3.48it/s]

[210/765]  raw='pass'  → → 1

 28%|██▊       | 211/765 [01:02<02:39,  3.48it/s]

[211/765]  raw='fail'  → → 0

 28%|██▊       | 212/765 [01:02<02:37,  3.51it/s]

[212/765]  raw='pass'  → → 1

 28%|██▊       | 213/765 [01:03<02:38,  3.49it/s]

[213/765]  raw='pass'  → → 1

 28%|██▊       | 214/765 [01:03<02:37,  3.51it/s]

[214/765]  raw='fail'  → → 0

 28%|██▊       | 215/765 [01:03<02:35,  3.53it/s]

[215/765]  raw='pass'  → → 1

 28%|██▊       | 216/765 [01:03<02:35,  3.53it/s]

[216/765]  raw='fail'  → → 0

 28%|██▊       | 217/765 [01:04<02:35,  3.53it/s]

[217/765]  raw='fail'  → → 0

 28%|██▊       | 218/765 [01:04<03:02,  2.99it/s]

[218/765]  raw='pass'  → → 1

 29%|██▊       | 219/765 [01:05<02:56,  3.09it/s]

[219/765]  raw='pass'  → → 1

 29%|██▉       | 220/765 [01:05<02:49,  3.22it/s]

[220/765]  raw='fail'  → → 0

 29%|██▉       | 221/765 [01:05<02:43,  3.33it/s]

[221/765]  raw='fail'  → → 0

 29%|██▉       | 222/765 [01:05<02:39,  3.39it/s]

[222/765]  raw='fail'  → → 0

 29%|██▉       | 223/765 [01:06<02:43,  3.32it/s]

[223/765]  raw='pass'  → → 1

 29%|██▉       | 224/765 [01:06<02:41,  3.36it/s]

[224/765]  raw='pass'  → → 1

 29%|██▉       | 225/765 [01:06<02:37,  3.42it/s]

[225/765]  raw='fail'  → → 0

 30%|██▉       | 226/765 [01:07<02:39,  3.38it/s]

[226/765]  raw='pass'  → → 1

 30%|██▉       | 227/765 [01:07<02:37,  3.43it/s]

[227/765]  raw='pass'  → → 1

 30%|██▉       | 228/765 [01:07<02:34,  3.47it/s]

[228/765]  raw='fail'  → → 0

 30%|██▉       | 229/765 [01:07<02:33,  3.50it/s]

[229/765]  raw='fail'  → → 0

 30%|███       | 230/765 [01:08<02:31,  3.53it/s]

[230/765]  raw='fail'  → → 0

 30%|███       | 231/765 [01:08<02:31,  3.52it/s]

[231/765]  raw='pass'  → → 1

 30%|███       | 232/765 [01:08<02:31,  3.52it/s]

[232/765]  raw='pass'  → → 1

 30%|███       | 233/765 [01:09<02:29,  3.55it/s]

[233/765]  raw='fail'  → → 0

 31%|███       | 234/765 [01:09<02:31,  3.51it/s]

[234/765]  raw='fail'  → → 0

 31%|███       | 235/765 [01:09<02:33,  3.45it/s]

[235/765]  raw='pass'  → → 1

 31%|███       | 236/765 [01:09<02:30,  3.50it/s]

[236/765]  raw='fail'  → → 0

 31%|███       | 237/765 [01:10<02:29,  3.53it/s]

[237/765]  raw='fail'  → → 0

 31%|███       | 238/765 [01:10<02:28,  3.55it/s]

[238/765]  raw='pass'  → → 1

 31%|███       | 239/765 [01:10<02:28,  3.55it/s]

[239/765]  raw='pass'  → → 1

 31%|███▏      | 240/765 [01:11<02:27,  3.57it/s]

[240/765]  raw='pass'  → → 1

 32%|███▏      | 241/765 [01:11<02:30,  3.47it/s]

[241/765]  raw='pass'  → → 1

 32%|███▏      | 242/765 [01:11<02:30,  3.47it/s]

[242/765]  raw='fail'  → → 0

 32%|███▏      | 243/765 [01:11<02:29,  3.50it/s]

[243/765]  raw='fail'  → → 0

 32%|███▏      | 244/765 [01:12<02:27,  3.53it/s]

[244/765]  raw='fail'  → → 0

 32%|███▏      | 245/765 [01:12<02:27,  3.53it/s]

[245/765]  raw='fail'  → → 0

 32%|███▏      | 246/765 [01:12<03:00,  2.87it/s]

[246/765]  raw='pass'  → → 1

 32%|███▏      | 247/765 [01:13<02:50,  3.03it/s]

[247/765]  raw='pass'  → → 1

 32%|███▏      | 248/765 [01:13<02:42,  3.18it/s]

[248/765]  raw='fail'  → → 0

 33%|███▎      | 249/765 [01:13<02:36,  3.31it/s]

[249/765]  raw='pass'  → → 1

 33%|███▎      | 250/765 [01:14<02:31,  3.40it/s]

[250/765]  raw='fail'  → → 0

 33%|███▎      | 251/765 [01:14<02:28,  3.47it/s]

[251/765]  raw='fail'  → → 0

 33%|███▎      | 252/765 [01:14<02:26,  3.50it/s]

[252/765]  raw='pass'  → → 1

 33%|███▎      | 253/765 [01:14<02:24,  3.54it/s]

[253/765]  raw='pass'  → → 1

 33%|███▎      | 254/765 [01:15<02:22,  3.58it/s]

[254/765]  raw='fail'  → → 0

 33%|███▎      | 255/765 [01:15<02:36,  3.26it/s]

[255/765]  raw='pass'  → → 1

 33%|███▎      | 256/765 [01:15<02:31,  3.36it/s]

[256/765]  raw='pass'  → → 1

 34%|███▎      | 257/765 [01:16<02:28,  3.42it/s]

[257/765]  raw='fail'  → → 0

 34%|███▎      | 258/765 [01:16<02:25,  3.48it/s]

[258/765]  raw='fail'  → → 0

 34%|███▍      | 259/765 [01:16<02:23,  3.52it/s]

[259/765]  raw='pass'  → → 1

 34%|███▍      | 260/765 [01:16<02:22,  3.54it/s]

[260/765]  raw='pass'  → → 1

 34%|███▍      | 261/765 [01:17<02:21,  3.55it/s]

[261/765]  raw='fail'  → → 0

 34%|███▍      | 262/765 [01:17<02:25,  3.46it/s]

[262/765]  raw='pass'  → → 1

 34%|███▍      | 263/765 [01:17<02:23,  3.49it/s]

[263/765]  raw='pass'  → → 1

 35%|███▍      | 264/765 [01:18<02:22,  3.52it/s]

[264/765]  raw='fail'  → → 0

 35%|███▍      | 265/765 [01:18<02:26,  3.41it/s]

[265/765]  raw='pass'  → → 1

 35%|███▍      | 266/765 [01:18<02:24,  3.45it/s]

[266/765]  raw='pass'  → → 1

 35%|███▍      | 267/765 [01:19<02:39,  3.13it/s]

[267/765]  raw='pass'  → → 1

 35%|███▌      | 268/765 [01:19<02:32,  3.25it/s]

[268/765]  raw='pass'  → → 1

 35%|███▌      | 269/765 [01:19<02:28,  3.35it/s]

[269/765]  raw='pass'  → → 1

 35%|███▌      | 270/765 [01:19<02:24,  3.43it/s]

[270/765]  raw='fail'  → → 0

 35%|███▌      | 271/765 [01:20<02:21,  3.49it/s]

[271/765]  raw='fail'  → → 0

 36%|███▌      | 272/765 [01:20<02:20,  3.50it/s]

[272/765]  raw='pass'  → → 1

 36%|███▌      | 273/765 [01:20<02:18,  3.55it/s]

[273/765]  raw='fail'  → → 0

 36%|███▌      | 274/765 [01:20<02:17,  3.57it/s]

[274/765]  raw='pass'  → → 1

 36%|███▌      | 275/765 [01:21<02:34,  3.17it/s]

[275/765]  raw='pass'  → → 1

 36%|███▌      | 276/765 [01:21<02:28,  3.29it/s]

[276/765]  raw='fail'  → → 0

 36%|███▌      | 277/765 [01:21<02:24,  3.38it/s]

[277/765]  raw='fail'  → → 0

 36%|███▋      | 278/765 [01:22<02:20,  3.46it/s]

[278/765]  raw='fail'  → → 0

 36%|███▋      | 279/765 [01:22<02:20,  3.45it/s]

[279/765]  raw='pass'  → → 1

 37%|███▋      | 280/765 [01:22<02:17,  3.52it/s]

[280/765]  raw='fail'  → → 0

 37%|███▋      | 281/765 [01:23<02:30,  3.22it/s]

[281/765]  raw='pass'  → → 1

 37%|███▋      | 282/765 [01:23<02:26,  3.30it/s]

[282/765]  raw='fail'  → → 0

 37%|███▋      | 283/765 [01:23<02:23,  3.36it/s]

[283/765]  raw='pass'  → → 1

 37%|███▋      | 284/765 [01:23<02:20,  3.42it/s]

[284/765]  raw='fail'  → → 0

 37%|███▋      | 285/765 [01:24<02:18,  3.48it/s]

[285/765]  raw='fail'  → → 0

 37%|███▋      | 286/765 [01:24<02:16,  3.51it/s]

[286/765]  raw='pass'  → → 1

 38%|███▊      | 287/765 [01:24<02:14,  3.55it/s]

[287/765]  raw='pass'  → → 1

 38%|███▊      | 288/765 [01:25<02:13,  3.57it/s]

[288/765]  raw='pass'  → → 1

 38%|███▊      | 289/765 [01:25<02:13,  3.56it/s]

[289/765]  raw='fail'  → → 0

 38%|███▊      | 290/765 [01:25<02:14,  3.53it/s]

[290/765]  raw='pass'  → → 1

 38%|███▊      | 291/765 [01:25<02:14,  3.52it/s]

[291/765]  raw='fail'  → → 0

 38%|███▊      | 292/765 [01:26<02:16,  3.48it/s]

[292/765]  raw='fail'  → → 0

 38%|███▊      | 293/765 [01:26<02:15,  3.49it/s]

[293/765]  raw='pass'  → → 1

 38%|███▊      | 294/765 [01:26<02:31,  3.10it/s]

[294/765]  raw='pass'  → → 1

 39%|███▊      | 295/765 [01:27<02:25,  3.23it/s]

[295/765]  raw='fail'  → → 0

 39%|███▊      | 296/765 [01:27<02:22,  3.29it/s]

[296/765]  raw='pass'  → → 1

 39%|███▉      | 297/765 [01:27<02:18,  3.37it/s]

[297/765]  raw='pass'  → → 1

 39%|███▉      | 298/765 [01:28<02:16,  3.43it/s]

[298/765]  raw='pass'  → → 1

 39%|███▉      | 299/765 [01:28<02:31,  3.08it/s]

[299/765]  raw='pass'  → → 1

 39%|███▉      | 300/765 [01:28<02:24,  3.22it/s]

[300/765]  raw='fail'  → → 0

 39%|███▉      | 301/765 [01:29<02:19,  3.32it/s]

[301/765]  raw='fail'  → → 0

 39%|███▉      | 302/765 [01:29<02:16,  3.38it/s]

[302/765]  raw='pass'  → → 1

 40%|███▉      | 303/765 [01:29<02:38,  2.92it/s]

[303/765]  raw='pass'  → → 1

 40%|███▉      | 304/765 [01:30<02:29,  3.08it/s]

[304/765]  raw='fail'  → → 0

 40%|███▉      | 305/765 [01:30<02:23,  3.21it/s]

[305/765]  raw='fail'  → → 0

 40%|████      | 306/765 [01:30<02:18,  3.31it/s]

[306/765]  raw='fail'  → → 0

 40%|████      | 307/765 [01:30<02:15,  3.39it/s]

[307/765]  raw='fail'  → → 0

 40%|████      | 308/765 [01:31<02:13,  3.43it/s]

[308/765]  raw='fail'  → → 0

 40%|████      | 309/765 [01:31<02:11,  3.47it/s]

[309/765]  raw='pass'  → → 1

 41%|████      | 310/765 [01:31<02:09,  3.52it/s]

[310/765]  raw='pass'  → → 1

 41%|████      | 311/765 [01:31<02:07,  3.56it/s]

[311/765]  raw='fail'  → → 0

 41%|████      | 312/765 [01:32<02:06,  3.59it/s]

[312/765]  raw='fail'  → → 0

 41%|████      | 313/765 [01:32<02:05,  3.61it/s]

[313/765]  raw='fail'  → → 0

 41%|████      | 314/765 [01:32<02:08,  3.51it/s]

[314/765]  raw='pass'  → → 1

 41%|████      | 315/765 [01:33<02:06,  3.57it/s]

[315/765]  raw='fail'  → → 0

 41%|████▏     | 316/765 [01:33<02:05,  3.58it/s]

[316/765]  raw='fail'  → → 0

 41%|████▏     | 317/765 [01:33<02:04,  3.60it/s]

[317/765]  raw='fail'  → → 0

 42%|████▏     | 318/765 [01:33<02:03,  3.62it/s]

[318/765]  raw='fail'  → → 0

 42%|████▏     | 319/765 [01:34<02:02,  3.64it/s]

[319/765]  raw='fail'  → → 0

 42%|████▏     | 320/765 [01:34<02:02,  3.64it/s]

[320/765]  raw='fail'  → → 0

 42%|████▏     | 321/765 [01:34<02:01,  3.67it/s]

[321/765]  raw='fail'  → → 0

 42%|████▏     | 322/765 [01:35<02:00,  3.66it/s]

[322/765]  raw='fail'  → → 0

 42%|████▏     | 323/765 [01:35<02:01,  3.65it/s]

[323/765]  raw='fail'  → → 0

 42%|████▏     | 324/765 [01:35<02:02,  3.60it/s]

[324/765]  raw='pass'  → → 1

 42%|████▏     | 325/765 [01:35<02:03,  3.57it/s]

[325/765]  raw='fail'  → → 0

 43%|████▎     | 326/765 [01:36<02:14,  3.26it/s]

[326/765]  raw='pass'  → → 1

 43%|████▎     | 327/765 [01:36<02:12,  3.31it/s]

[327/765]  raw='fail'  → → 0

 43%|████▎     | 328/765 [01:36<02:08,  3.40it/s]

[328/765]  raw='pass'  → → 1

 43%|████▎     | 329/765 [01:37<02:05,  3.49it/s]

[329/765]  raw='fail'  → → 0

 43%|████▎     | 330/765 [01:37<02:03,  3.53it/s]

[330/765]  raw='pass'  → → 1

 43%|████▎     | 331/765 [01:37<02:01,  3.56it/s]

[331/765]  raw='fail'  → → 0

 43%|████▎     | 332/765 [01:37<02:00,  3.59it/s]

[332/765]  raw='pass'  → → 1

 44%|████▎     | 333/765 [01:38<02:00,  3.57it/s]

[333/765]  raw='pass'  → → 1

 44%|████▎     | 334/765 [01:38<02:01,  3.56it/s]

[334/765]  raw='pass'  → → 1

 44%|████▍     | 335/765 [01:38<02:01,  3.55it/s]

[335/765]  raw='fail'  → → 0

 44%|████▍     | 336/765 [01:39<02:00,  3.57it/s]

[336/765]  raw='fail'  → → 0

 44%|████▍     | 337/765 [01:39<01:59,  3.58it/s]

[337/765]  raw='pass'  → → 1

 44%|████▍     | 338/765 [01:39<01:59,  3.58it/s]

[338/765]  raw='fail'  → → 0

 44%|████▍     | 339/765 [01:39<02:10,  3.27it/s]

[339/765]  raw='pass'  → → 1

 44%|████▍     | 340/765 [01:40<02:06,  3.35it/s]

[340/765]  raw='pass'  → → 1

 45%|████▍     | 341/765 [01:40<02:03,  3.43it/s]

[341/765]  raw='pass'  → → 1

 45%|████▍     | 342/765 [01:40<02:01,  3.47it/s]

[342/765]  raw='pass'  → → 1

 45%|████▍     | 343/765 [01:41<02:04,  3.40it/s]

[343/765]  raw='pass'  → → 1

 45%|████▍     | 344/765 [01:41<02:00,  3.48it/s]

[344/765]  raw='pass'  → → 1

 45%|████▌     | 345/765 [01:41<01:58,  3.54it/s]

[345/765]  raw='pass'  → → 1

 45%|████▌     | 346/765 [01:42<02:09,  3.24it/s]

[346/765]  raw='pass'  → → 1

 45%|████▌     | 347/765 [01:42<02:06,  3.31it/s]

[347/765]  raw='fail'  → → 0

 45%|████▌     | 348/765 [01:42<02:02,  3.40it/s]

[348/765]  raw='pass'  → → 1

 46%|████▌     | 349/765 [01:42<01:59,  3.48it/s]

[349/765]  raw='fail'  → → 0

 46%|████▌     | 350/765 [01:43<01:57,  3.53it/s]

[350/765]  raw='fail'  → → 0

 46%|████▌     | 351/765 [01:43<01:56,  3.54it/s]

[351/765]  raw='fail'  → → 0

 46%|████▌     | 352/765 [01:43<01:56,  3.56it/s]

[352/765]  raw='pass'  → → 1

 46%|████▌     | 353/765 [01:43<01:55,  3.57it/s]

[353/765]  raw='fail'  → → 0

 46%|████▋     | 354/765 [01:44<01:54,  3.60it/s]

[354/765]  raw='fail'  → → 0

 46%|████▋     | 355/765 [01:44<01:53,  3.60it/s]

[355/765]  raw='pass'  → → 1

 47%|████▋     | 356/765 [01:44<01:53,  3.60it/s]

[356/765]  raw='pass'  → → 1

 47%|████▋     | 357/765 [01:45<01:53,  3.60it/s]

[357/765]  raw='fail'  → → 0

 47%|████▋     | 358/765 [01:45<01:53,  3.58it/s]

[358/765]  raw='pass'  → → 1

 47%|████▋     | 359/765 [01:45<01:56,  3.49it/s]

[359/765]  raw='pass'  → → 1

 47%|████▋     | 360/765 [01:45<01:55,  3.50it/s]

[360/765]  raw='pass'  → → 1

 47%|████▋     | 361/765 [01:46<01:54,  3.53it/s]

[361/765]  raw='fail'  → → 0

 47%|████▋     | 362/765 [01:46<01:58,  3.41it/s]

[362/765]  raw='pass'  → → 1

 47%|████▋     | 363/765 [01:46<01:56,  3.44it/s]

[363/765]  raw='fail'  → → 0

 48%|████▊     | 364/765 [01:47<01:54,  3.49it/s]

[364/765]  raw='pass'  → → 1

 48%|████▊     | 365/765 [01:47<02:04,  3.22it/s]

[365/765]  raw='pass'  → → 1

 48%|████▊     | 366/765 [01:47<01:59,  3.35it/s]

[366/765]  raw='fail'  → → 0

 48%|████▊     | 367/765 [01:48<01:57,  3.39it/s]

[367/765]  raw='pass'  → → 1

 48%|████▊     | 368/765 [01:48<01:54,  3.46it/s]

[368/765]  raw='fail'  → → 0

 48%|████▊     | 369/765 [01:48<01:53,  3.50it/s]

[369/765]  raw='pass'  → → 1

 48%|████▊     | 370/765 [01:48<01:55,  3.41it/s]

[370/765]  raw='pass'  → → 1

 48%|████▊     | 371/765 [01:49<01:55,  3.42it/s]

[371/765]  raw='pass'  → → 1

 49%|████▊     | 372/765 [01:49<01:53,  3.46it/s]

[372/765]  raw='fail'  → → 0

 49%|████▉     | 373/765 [01:49<02:02,  3.21it/s]

[373/765]  raw='pass'  → → 1

 49%|████▉     | 374/765 [01:50<01:58,  3.30it/s]

[374/765]  raw='pass'  → → 1

 49%|████▉     | 375/765 [01:50<01:56,  3.34it/s]

[375/765]  raw='pass'  → → 1

 49%|████▉     | 376/765 [01:50<01:55,  3.36it/s]

[376/765]  raw='fail'  → → 0

 49%|████▉     | 377/765 [01:50<01:55,  3.36it/s]

[377/765]  raw='pass'  → → 1

 49%|████▉     | 378/765 [01:51<02:03,  3.13it/s]

[378/765]  raw='pass'  → → 1

 50%|████▉     | 379/765 [01:51<01:58,  3.26it/s]

[379/765]  raw='fail'  → → 0

 50%|████▉     | 380/765 [01:51<01:54,  3.36it/s]

[380/765]  raw='fail'  → → 0

 50%|████▉     | 381/765 [01:52<01:55,  3.31it/s]

[381/765]  raw='pass'  → → 1

 50%|████▉     | 382/765 [01:52<01:52,  3.39it/s]

[382/765]  raw='fail'  → → 0

 50%|█████     | 383/765 [01:52<01:51,  3.43it/s]

[383/765]  raw='fail'  → → 0

 50%|█████     | 384/765 [01:53<01:50,  3.45it/s]

[384/765]  raw='pass'  → → 1

 50%|█████     | 385/765 [01:53<01:49,  3.48it/s]

[385/765]  raw='fail'  → → 0

 50%|█████     | 386/765 [01:53<01:47,  3.51it/s]

[386/765]  raw='pass'  → → 1

 51%|█████     | 387/765 [01:53<01:46,  3.53it/s]

[387/765]  raw='fail'  → → 0

 51%|█████     | 388/765 [01:54<01:46,  3.54it/s]

[388/765]  raw='pass'  → → 1

 51%|█████     | 389/765 [01:54<01:46,  3.55it/s]

[389/765]  raw='pass'  → → 1

 51%|█████     | 390/765 [01:54<01:45,  3.54it/s]

[390/765]  raw='pass'  → → 1

 51%|█████     | 391/765 [01:55<01:44,  3.57it/s]

[391/765]  raw='fail'  → → 0

 51%|█████     | 392/765 [01:55<01:43,  3.59it/s]

[392/765]  raw='fail'  → → 0

 51%|█████▏    | 393/765 [01:55<01:45,  3.54it/s]

[393/765]  raw='pass'  → → 1

 52%|█████▏    | 394/765 [01:56<02:10,  2.85it/s]

[394/765]  raw='pass'  → → 1

 52%|█████▏    | 395/765 [01:56<02:01,  3.04it/s]

[395/765]  raw='pass'  → → 1

 52%|█████▏    | 396/765 [01:56<01:56,  3.17it/s]

[396/765]  raw='fail'  → → 0

 52%|█████▏    | 397/765 [01:56<01:52,  3.28it/s]

[397/765]  raw='pass'  → → 1

 52%|█████▏    | 398/765 [01:57<01:49,  3.36it/s]

[398/765]  raw='fail'  → → 0

 52%|█████▏    | 399/765 [01:57<01:47,  3.41it/s]

[399/765]  raw='fail'  → → 0

 52%|█████▏    | 400/765 [01:57<01:46,  3.41it/s]

[400/765]  raw='pass'  → → 1

 52%|█████▏    | 401/765 [01:58<01:45,  3.45it/s]

[401/765]  raw='fail'  → → 0

 53%|█████▎    | 402/765 [01:58<01:46,  3.41it/s]

[402/765]  raw='pass'  → → 1

 53%|█████▎    | 403/765 [01:58<01:43,  3.50it/s]

[403/765]  raw='fail'  → → 0

 53%|█████▎    | 404/765 [01:58<01:41,  3.56it/s]

[404/765]  raw='fail'  → → 0

 53%|█████▎    | 405/765 [01:59<01:40,  3.59it/s]

[405/765]  raw='fail'  → → 0

 53%|█████▎    | 406/765 [01:59<01:39,  3.62it/s]

[406/765]  raw='pass'  → → 1

 53%|█████▎    | 407/765 [01:59<01:49,  3.28it/s]

[407/765]  raw='pass'  → → 1

 53%|█████▎    | 408/765 [02:00<01:45,  3.39it/s]

[408/765]  raw='fail'  → → 0

 53%|█████▎    | 409/765 [02:00<01:42,  3.47it/s]

[409/765]  raw='pass'  → → 1

 54%|█████▎    | 410/765 [02:00<01:40,  3.53it/s]

[410/765]  raw='fail'  → → 0

 54%|█████▎    | 411/765 [02:00<01:39,  3.57it/s]

[411/765]  raw='fail'  → → 0

 54%|█████▍    | 412/765 [02:01<01:43,  3.42it/s]

[412/765]  raw='pass'  → → 1

 54%|█████▍    | 413/765 [02:01<01:42,  3.44it/s]

[413/765]  raw='pass'  → → 1

 54%|█████▍    | 414/765 [02:01<01:43,  3.39it/s]

[414/765]  raw='pass'  → → 1

 54%|█████▍    | 415/765 [02:02<01:42,  3.43it/s]

[415/765]  raw='fail'  → → 0

 54%|█████▍    | 416/765 [02:02<01:40,  3.47it/s]

[416/765]  raw='fail'  → → 0

 55%|█████▍    | 417/765 [02:02<01:38,  3.52it/s]

[417/765]  raw='fail'  → → 0

 55%|█████▍    | 418/765 [02:02<01:37,  3.54it/s]

[418/765]  raw='fail'  → → 0

 55%|█████▍    | 419/765 [02:03<01:37,  3.55it/s]

[419/765]  raw='fail'  → → 0

 55%|█████▍    | 420/765 [02:03<01:37,  3.55it/s]

[420/765]  raw='pass'  → → 1

 55%|█████▌    | 421/765 [02:03<01:37,  3.54it/s]

[421/765]  raw='fail'  → → 0

 55%|█████▌    | 422/765 [02:04<01:47,  3.18it/s]

[422/765]  raw='pass'  → → 1

 55%|█████▌    | 423/765 [02:04<01:46,  3.22it/s]

[423/765]  raw='pass'  → → 1

 55%|█████▌    | 424/765 [02:04<01:41,  3.35it/s]

[424/765]  raw='fail'  → → 0

 56%|█████▌    | 425/765 [02:05<01:39,  3.43it/s]

[425/765]  raw='pass'  → → 1

 56%|█████▌    | 426/765 [02:05<01:39,  3.40it/s]

[426/765]  raw='pass'  → → 1

 56%|█████▌    | 427/765 [02:05<02:01,  2.79it/s]

[427/765]  raw='pass'  → → 1

 56%|█████▌    | 428/765 [02:06<01:52,  2.99it/s]

[428/765]  raw='fail'  → → 0

 56%|█████▌    | 429/765 [02:06<01:46,  3.16it/s]

[429/765]  raw='fail'  → → 0

 56%|█████▌    | 430/765 [02:06<01:42,  3.28it/s]

[430/765]  raw='pass'  → → 1

 56%|█████▋    | 431/765 [02:06<01:38,  3.39it/s]

[431/765]  raw='pass'  → → 1

 56%|█████▋    | 432/765 [02:07<01:36,  3.45it/s]

[432/765]  raw='fail'  → → 0

 57%|█████▋    | 433/765 [02:07<01:35,  3.49it/s]

[433/765]  raw='pass'  → → 1

 57%|█████▋    | 434/765 [02:07<01:33,  3.55it/s]

[434/765]  raw='fail'  → → 0

 57%|█████▋    | 435/765 [02:08<01:32,  3.58it/s]

[435/765]  raw='fail'  → → 0

 57%|█████▋    | 436/765 [02:08<01:31,  3.59it/s]

[436/765]  raw='fail'  → → 0

 57%|█████▋    | 437/765 [02:08<01:31,  3.58it/s]

[437/765]  raw='fail'  → → 0

 57%|█████▋    | 438/765 [02:08<01:30,  3.60it/s]

[438/765]  raw='fail'  → → 0

 57%|█████▋    | 439/765 [02:09<01:30,  3.59it/s]

[439/765]  raw='fail'  → → 0

 58%|█████▊    | 440/765 [02:09<01:30,  3.60it/s]

[440/765]  raw='fail'  → → 0

 58%|█████▊    | 441/765 [02:09<01:29,  3.61it/s]

[441/765]  raw='pass'  → → 1

 58%|█████▊    | 442/765 [02:09<01:29,  3.61it/s]

[442/765]  raw='fail'  → → 0

 58%|█████▊    | 443/765 [02:10<01:28,  3.63it/s]

[443/765]  raw='fail'  → → 0

 58%|█████▊    | 444/765 [02:10<01:28,  3.64it/s]

[444/765]  raw='fail'  → → 0

 58%|█████▊    | 445/765 [02:10<01:28,  3.63it/s]

[445/765]  raw='pass'  → → 1

 58%|█████▊    | 446/765 [02:11<01:28,  3.59it/s]

[446/765]  raw='fail'  → → 0

 58%|█████▊    | 447/765 [02:11<01:29,  3.57it/s]

[447/765]  raw='pass'  → → 1

 59%|█████▊    | 448/765 [02:11<01:29,  3.56it/s]

[448/765]  raw='pass'  → → 1

 59%|█████▊    | 449/765 [02:11<01:28,  3.57it/s]

[449/765]  raw='fail'  → → 0

 59%|█████▉    | 450/765 [02:12<01:29,  3.52it/s]

[450/765]  raw='pass'  → → 1

 59%|█████▉    | 451/765 [02:12<01:29,  3.53it/s]

[451/765]  raw='fail'  → → 0

 59%|█████▉    | 452/765 [02:12<01:28,  3.55it/s]

[452/765]  raw='fail'  → → 0

 59%|█████▉    | 453/765 [02:13<01:27,  3.57it/s]

[453/765]  raw='fail'  → → 0

 59%|█████▉    | 454/765 [02:13<01:27,  3.57it/s]

[454/765]  raw='fail'  → → 0

 59%|█████▉    | 455/765 [02:13<01:27,  3.56it/s]

[455/765]  raw='pass'  → → 1

 60%|█████▉    | 456/765 [02:13<01:26,  3.55it/s]

[456/765]  raw='fail'  → → 0

 60%|█████▉    | 457/765 [02:14<01:26,  3.55it/s]

[457/765]  raw='pass'  → → 1

 60%|█████▉    | 458/765 [02:14<01:27,  3.52it/s]

[458/765]  raw='fail'  → → 0

 60%|██████    | 459/765 [02:14<01:26,  3.52it/s]

[459/765]  raw='fail'  → → 0

 60%|██████    | 460/765 [02:15<01:25,  3.56it/s]

[460/765]  raw='fail'  → → 0

 60%|██████    | 461/765 [02:15<01:25,  3.54it/s]

[461/765]  raw='pass'  → → 1

 60%|██████    | 462/765 [02:15<01:27,  3.45it/s]

[462/765]  raw='pass'  → → 1

 61%|██████    | 463/765 [02:15<01:27,  3.47it/s]

[463/765]  raw='fail'  → → 0

 61%|██████    | 464/765 [02:16<01:26,  3.47it/s]

[464/765]  raw='fail'  → → 0

 61%|██████    | 465/765 [02:16<01:26,  3.47it/s]

[465/765]  raw='pass'  → → 1

 61%|██████    | 466/765 [02:16<01:25,  3.50it/s]

[466/765]  raw='fail'  → → 0

 61%|██████    | 467/765 [02:17<01:24,  3.54it/s]

[467/765]  raw='pass'  → → 1

 61%|██████    | 468/765 [02:17<01:23,  3.57it/s]

[468/765]  raw='pass'  → → 1

 61%|██████▏   | 469/765 [02:17<01:23,  3.57it/s]

[469/765]  raw='fail'  → → 0

 61%|██████▏   | 470/765 [02:17<01:29,  3.29it/s]

[470/765]  raw='pass'  → → 1

 62%|██████▏   | 471/765 [02:18<01:26,  3.40it/s]

[471/765]  raw='fail'  → → 0

 62%|██████▏   | 472/765 [02:18<01:24,  3.47it/s]

[472/765]  raw='fail'  → → 0

 62%|██████▏   | 473/765 [02:18<01:23,  3.50it/s]

[473/765]  raw='pass'  → → 1

 62%|██████▏   | 474/765 [02:19<01:22,  3.52it/s]

[474/765]  raw='fail'  → → 0

 62%|██████▏   | 475/765 [02:19<01:22,  3.53it/s]

[475/765]  raw='pass'  → → 1

 62%|██████▏   | 476/765 [02:19<01:21,  3.54it/s]

[476/765]  raw='fail'  → → 0

 62%|██████▏   | 477/765 [02:19<01:21,  3.55it/s]

[477/765]  raw='pass'  → → 1

 62%|██████▏   | 478/765 [02:20<01:20,  3.57it/s]

[478/765]  raw='fail'  → → 0

 63%|██████▎   | 479/765 [02:20<01:20,  3.57it/s]

[479/765]  raw='fail'  → → 0

 63%|██████▎   | 480/765 [02:20<01:19,  3.58it/s]

[480/765]  raw='pass'  → → 1

 63%|██████▎   | 481/765 [02:21<01:19,  3.58it/s]

[481/765]  raw='fail'  → → 0

 63%|██████▎   | 482/765 [02:21<01:19,  3.54it/s]

[482/765]  raw='fail'  → → 0

 63%|██████▎   | 483/765 [02:21<01:19,  3.57it/s]

[483/765]  raw='fail'  → → 0

 63%|██████▎   | 484/765 [02:21<01:18,  3.56it/s]

[484/765]  raw='pass'  → → 1

 63%|██████▎   | 485/765 [02:22<01:18,  3.57it/s]

[485/765]  raw='pass'  → → 1

 64%|██████▎   | 486/765 [02:22<01:20,  3.48it/s]

[486/765]  raw='pass'  → → 1

 64%|██████▎   | 487/765 [02:22<01:19,  3.49it/s]

[487/765]  raw='fail'  → → 0

 64%|██████▍   | 488/765 [02:23<01:18,  3.52it/s]

[488/765]  raw='pass'  → → 1

 64%|██████▍   | 489/765 [02:23<01:17,  3.54it/s]

[489/765]  raw='fail'  → → 0

 64%|██████▍   | 490/765 [02:23<01:17,  3.53it/s]

[490/765]  raw='pass'  → → 1

 64%|██████▍   | 491/765 [02:23<01:17,  3.53it/s]

[491/765]  raw='pass'  → → 1

 64%|██████▍   | 492/765 [02:24<01:16,  3.55it/s]

[492/765]  raw='pass'  → → 1

 64%|██████▍   | 493/765 [02:24<01:16,  3.54it/s]

[493/765]  raw='pass'  → → 1

 65%|██████▍   | 494/765 [02:24<01:16,  3.56it/s]

[494/765]  raw='pass'  → → 1

 65%|██████▍   | 495/765 [02:24<01:15,  3.57it/s]

[495/765]  raw='fail'  → → 0

 65%|██████▍   | 496/765 [02:25<01:15,  3.57it/s]

[496/765]  raw='fail'  → → 0

 65%|██████▍   | 497/765 [02:25<01:14,  3.58it/s]

[497/765]  raw='pass'  → → 1

 65%|██████▌   | 498/765 [02:25<01:14,  3.58it/s]

[498/765]  raw='fail'  → → 0

 65%|██████▌   | 499/765 [02:26<01:14,  3.59it/s]

[499/765]  raw='pass'  → → 1

 65%|██████▌   | 500/765 [02:26<01:13,  3.60it/s]

[500/765]  raw='fail'  → → 0

 65%|██████▌   | 501/765 [02:26<01:13,  3.60it/s]

[501/765]  raw='fail'  → → 0

 66%|██████▌   | 502/765 [02:26<01:13,  3.60it/s]

[502/765]  raw='fail'  → → 0

 66%|██████▌   | 503/765 [02:27<01:13,  3.56it/s]

[503/765]  raw='pass'  → → 1

 66%|██████▌   | 504/765 [02:27<01:13,  3.55it/s]

[504/765]  raw='fail'  → → 0

 66%|██████▌   | 505/765 [02:27<01:13,  3.55it/s]

[505/765]  raw='fail'  → → 0

 66%|██████▌   | 506/765 [02:28<01:13,  3.54it/s]

[506/765]  raw='fail'  → → 0

 66%|██████▋   | 507/765 [02:28<01:13,  3.53it/s]

[507/765]  raw='fail'  → → 0

 66%|██████▋   | 508/765 [02:28<01:13,  3.51it/s]

[508/765]  raw='pass'  → → 1

 67%|██████▋   | 509/765 [02:28<01:13,  3.46it/s]

[509/765]  raw='pass'  → → 1

 67%|██████▋   | 510/765 [02:29<01:13,  3.49it/s]

[510/765]  raw='fail'  → → 0

 67%|██████▋   | 511/765 [02:29<01:18,  3.23it/s]

[511/765]  raw='pass'  → → 1

 67%|██████▋   | 512/765 [02:29<01:16,  3.32it/s]

[512/765]  raw='pass'  → → 1

 67%|██████▋   | 513/765 [02:30<01:14,  3.37it/s]

[513/765]  raw='fail'  → → 0

 67%|██████▋   | 514/765 [02:30<01:13,  3.41it/s]

[514/765]  raw='pass'  → → 1

 67%|██████▋   | 515/765 [02:30<01:12,  3.46it/s]

[515/765]  raw='pass'  → → 1

 67%|██████▋   | 516/765 [02:31<01:17,  3.19it/s]

[516/765]  raw='pass'  → → 1

 68%|██████▊   | 517/765 [02:31<01:14,  3.33it/s]

[517/765]  raw='fail'  → → 0

 68%|██████▊   | 518/765 [02:31<01:12,  3.42it/s]

[518/765]  raw='pass'  → → 1

 68%|██████▊   | 519/765 [02:31<01:10,  3.48it/s]

[519/765]  raw='fail'  → → 0

 68%|██████▊   | 520/765 [02:32<01:09,  3.53it/s]

[520/765]  raw='pass'  → → 1

 68%|██████▊   | 521/765 [02:32<01:10,  3.47it/s]

[521/765]  raw='pass'  → → 1

 68%|██████▊   | 522/765 [02:32<01:08,  3.54it/s]

[522/765]  raw='fail'  → → 0

 68%|██████▊   | 523/765 [02:33<01:07,  3.58it/s]

[523/765]  raw='pass'  → → 1

 68%|██████▊   | 524/765 [02:33<01:06,  3.60it/s]

[524/765]  raw='fail'  → → 0

 69%|██████▊   | 525/765 [02:33<01:13,  3.25it/s]

[525/765]  raw='pass'  → → 1

 69%|██████▉   | 526/765 [02:33<01:11,  3.36it/s]

[526/765]  raw='pass'  → → 1

 69%|██████▉   | 527/765 [02:34<01:09,  3.45it/s]

[527/765]  raw='fail'  → → 0

 69%|██████▉   | 528/765 [02:34<01:07,  3.51it/s]

[528/765]  raw='pass'  → → 1

 69%|██████▉   | 529/765 [02:34<01:06,  3.55it/s]

[529/765]  raw='fail'  → → 0

 69%|██████▉   | 530/765 [02:35<01:05,  3.58it/s]

[530/765]  raw='fail'  → → 0

 69%|██████▉   | 531/765 [02:35<01:05,  3.59it/s]

[531/765]  raw='fail'  → → 0

 70%|██████▉   | 532/765 [02:35<01:04,  3.60it/s]

[532/765]  raw='fail'  → → 0

 70%|██████▉   | 533/765 [02:35<01:04,  3.60it/s]

[533/765]  raw='pass'  → → 1

 70%|██████▉   | 534/765 [02:36<01:04,  3.59it/s]

[534/765]  raw='pass'  → → 1

 70%|██████▉   | 535/765 [02:36<01:03,  3.60it/s]

[535/765]  raw='pass'  → → 1

 70%|███████   | 536/765 [02:36<01:03,  3.59it/s]

[536/765]  raw='fail'  → → 0

 70%|███████   | 537/765 [02:36<01:03,  3.57it/s]

[537/765]  raw='fail'  → → 0

 70%|███████   | 538/765 [02:37<01:03,  3.57it/s]

[538/765]  raw='fail'  → → 0

 70%|███████   | 539/765 [02:37<01:04,  3.49it/s]

[539/765]  raw='fail'  → → 0

 71%|███████   | 540/765 [02:37<01:04,  3.50it/s]

[540/765]  raw='pass'  → → 1

 71%|███████   | 541/765 [02:38<01:03,  3.52it/s]

[541/765]  raw='fail'  → → 0

 71%|███████   | 542/765 [02:38<01:03,  3.53it/s]

[542/765]  raw='fail'  → → 0

 71%|███████   | 543/765 [02:38<01:04,  3.44it/s]

[543/765]  raw='pass'  → → 1

 71%|███████   | 544/765 [02:39<01:03,  3.49it/s]

[544/765]  raw='fail'  → → 0

 71%|███████   | 545/765 [02:39<01:02,  3.52it/s]

[545/765]  raw='fail'  → → 0

 71%|███████▏  | 546/765 [02:39<01:01,  3.54it/s]

[546/765]  raw='fail'  → → 0

 72%|███████▏  | 547/765 [02:39<01:01,  3.53it/s]

[547/765]  raw='fail'  → → 0

 72%|███████▏  | 548/765 [02:40<01:07,  3.21it/s]

[548/765]  raw='pass'  → → 1

 72%|███████▏  | 549/765 [02:40<01:05,  3.28it/s]

[549/765]  raw='pass'  → → 1

 72%|███████▏  | 550/765 [02:40<01:04,  3.35it/s]

[550/765]  raw='pass'  → → 1

 72%|███████▏  | 551/765 [02:41<01:03,  3.39it/s]

[551/765]  raw='fail'  → → 0

 72%|███████▏  | 552/765 [02:41<01:02,  3.42it/s]

[552/765]  raw='fail'  → → 0

 72%|███████▏  | 553/765 [02:41<01:01,  3.45it/s]

[553/765]  raw='pass'  → → 1

 72%|███████▏  | 554/765 [02:41<01:00,  3.47it/s]

[554/765]  raw='pass'  → → 1

 73%|███████▎  | 555/765 [02:42<01:00,  3.48it/s]

[555/765]  raw='fail'  → → 0

 73%|███████▎  | 556/765 [02:42<01:00,  3.45it/s]

[556/765]  raw='pass'  → → 1

 73%|███████▎  | 557/765 [02:42<00:59,  3.49it/s]

[557/765]  raw='pass'  → → 1

 73%|███████▎  | 558/765 [02:43<00:58,  3.54it/s]

[558/765]  raw='fail'  → → 0

 73%|███████▎  | 559/765 [02:43<00:58,  3.54it/s]

[559/765]  raw='pass'  → → 1

 73%|███████▎  | 560/765 [02:43<00:57,  3.55it/s]

[560/765]  raw='pass'  → → 1

 73%|███████▎  | 561/765 [02:43<00:59,  3.42it/s]

[561/765]  raw='pass'  → → 1

 73%|███████▎  | 562/765 [02:44<00:58,  3.48it/s]

[562/765]  raw='fail'  → → 0

 74%|███████▎  | 563/765 [02:44<00:58,  3.48it/s]

[563/765]  raw='fail'  → → 0

 74%|███████▎  | 564/765 [02:44<00:57,  3.51it/s]

[564/765]  raw='fail'  → → 0

 74%|███████▍  | 565/765 [02:45<00:57,  3.49it/s]

[565/765]  raw='pass'  → → 1

 74%|███████▍  | 566/765 [02:45<00:56,  3.52it/s]

[566/765]  raw='pass'  → → 1

 74%|███████▍  | 567/765 [02:45<00:55,  3.54it/s]

[567/765]  raw='pass'  → → 1

 74%|███████▍  | 568/765 [02:45<00:57,  3.42it/s]

[568/765]  raw='pass'  → → 1

 74%|███████▍  | 569/765 [02:46<00:56,  3.48it/s]

[569/765]  raw='fail'  → → 0

 75%|███████▍  | 570/765 [02:46<00:55,  3.51it/s]

[570/765]  raw='pass'  → → 1

 75%|███████▍  | 571/765 [02:46<00:55,  3.51it/s]

[571/765]  raw='fail'  → → 0

 75%|███████▍  | 572/765 [02:47<00:54,  3.55it/s]

[572/765]  raw='pass'  → → 1

 75%|███████▍  | 573/765 [02:47<00:54,  3.54it/s]

[573/765]  raw='pass'  → → 1

 75%|███████▌  | 574/765 [02:47<00:54,  3.48it/s]

[574/765]  raw='pass'  → → 1

 75%|███████▌  | 575/765 [02:47<00:54,  3.51it/s]

[575/765]  raw='pass'  → → 1

 75%|███████▌  | 576/765 [02:48<00:53,  3.54it/s]

[576/765]  raw='pass'  → → 1

 75%|███████▌  | 577/765 [02:48<00:52,  3.57it/s]

[577/765]  raw='fail'  → → 0

 76%|███████▌  | 578/765 [02:48<00:52,  3.58it/s]

[578/765]  raw='fail'  → → 0

 76%|███████▌  | 579/765 [02:49<00:51,  3.58it/s]

[579/765]  raw='fail'  → → 0

 76%|███████▌  | 580/765 [02:49<00:51,  3.59it/s]

[580/765]  raw='pass'  → → 1

 76%|███████▌  | 581/765 [02:49<00:51,  3.60it/s]

[581/765]  raw='fail'  → → 0

 76%|███████▌  | 582/765 [02:49<00:50,  3.60it/s]

[582/765]  raw='fail'  → → 0

 76%|███████▌  | 583/765 [02:50<00:50,  3.61it/s]

[583/765]  raw='fail'  → → 0

 76%|███████▋  | 584/765 [02:50<00:51,  3.52it/s]

[584/765]  raw='pass'  → → 1

 76%|███████▋  | 585/765 [02:50<00:52,  3.45it/s]

[585/765]  raw='pass'  → → 1

 77%|███████▋  | 586/765 [02:51<00:51,  3.47it/s]

[586/765]  raw='pass'  → → 1

 77%|███████▋  | 587/765 [02:51<00:50,  3.49it/s]

[587/765]  raw='fail'  → → 0

 77%|███████▋  | 588/765 [02:51<00:49,  3.55it/s]

[588/765]  raw='fail'  → → 0

 77%|███████▋  | 589/765 [02:51<00:48,  3.60it/s]

[589/765]  raw='fail'  → → 0

 77%|███████▋  | 590/765 [02:52<00:48,  3.64it/s]

[590/765]  raw='fail'  → → 0

 77%|███████▋  | 591/765 [02:52<00:47,  3.67it/s]

[591/765]  raw='fail'  → → 0

 77%|███████▋  | 592/765 [02:52<00:47,  3.65it/s]

[592/765]  raw='fail'  → → 0

 78%|███████▊  | 593/765 [02:52<00:47,  3.65it/s]

[593/765]  raw='fail'  → → 0

 78%|███████▊  | 594/765 [02:53<00:46,  3.64it/s]

[594/765]  raw='fail'  → → 0

 78%|███████▊  | 595/765 [02:53<00:46,  3.62it/s]

[595/765]  raw='pass'  → → 1

 78%|███████▊  | 596/765 [02:53<00:55,  3.02it/s]

[596/765]  raw='pass'  → → 1

 78%|███████▊  | 597/765 [02:54<00:53,  3.13it/s]

[597/765]  raw='pass'  → → 1

 78%|███████▊  | 598/765 [02:54<00:52,  3.18it/s]

[598/765]  raw='pass'  → → 1

 78%|███████▊  | 599/765 [02:54<00:50,  3.29it/s]

[599/765]  raw='pass'  → → 1

 78%|███████▊  | 600/765 [02:55<00:48,  3.38it/s]

[600/765]  raw='fail'  → → 0

 79%|███████▊  | 601/765 [02:55<00:47,  3.45it/s]

[601/765]  raw='pass'  → → 1

 79%|███████▊  | 602/765 [02:55<00:47,  3.42it/s]

[602/765]  raw='pass'  → → 1

 79%|███████▉  | 603/765 [02:55<00:47,  3.38it/s]

[603/765]  raw='pass'  → → 1

 79%|███████▉  | 604/765 [02:56<00:46,  3.45it/s]

[604/765]  raw='pass'  → → 1

 79%|███████▉  | 605/765 [02:56<00:45,  3.51it/s]

[605/765]  raw='pass'  → → 1

 79%|███████▉  | 606/765 [02:56<00:44,  3.56it/s]

[606/765]  raw='fail'  → → 0

 79%|███████▉  | 607/765 [02:57<00:44,  3.59it/s]

[607/765]  raw='fail'  → → 0

 79%|███████▉  | 608/765 [02:57<00:47,  3.29it/s]

[608/765]  raw='pass'  → → 1

 80%|███████▉  | 609/765 [02:57<00:46,  3.39it/s]

[609/765]  raw='pass'  → → 1

 80%|███████▉  | 610/765 [02:57<00:44,  3.45it/s]

[610/765]  raw='pass'  → → 1

 80%|███████▉  | 611/765 [02:58<00:44,  3.45it/s]

[611/765]  raw='pass'  → → 1

 80%|████████  | 612/765 [02:58<00:43,  3.48it/s]

[612/765]  raw='pass'  → → 1

 80%|████████  | 613/765 [02:58<00:43,  3.49it/s]

[613/765]  raw='pass'  → → 1

 80%|████████  | 614/765 [02:59<00:43,  3.46it/s]

[614/765]  raw='pass'  → → 1

 80%|████████  | 615/765 [02:59<00:43,  3.47it/s]

[615/765]  raw='fail'  → → 0

 81%|████████  | 616/765 [02:59<00:43,  3.43it/s]

[616/765]  raw='fail'  → → 0

 81%|████████  | 617/765 [03:00<00:42,  3.45it/s]

[617/765]  raw='fail'  → → 0

 81%|████████  | 618/765 [03:00<00:42,  3.48it/s]

[618/765]  raw='fail'  → → 0

 81%|████████  | 619/765 [03:00<00:41,  3.48it/s]

[619/765]  raw='fail'  → → 0

 81%|████████  | 620/765 [03:00<00:41,  3.48it/s]

[620/765]  raw='pass'  → → 1

 81%|████████  | 621/765 [03:01<00:46,  3.11it/s]

[621/765]  raw='pass'  → → 1

 81%|████████▏ | 622/765 [03:01<00:45,  3.15it/s]

[622/765]  raw='pass'  → → 1

 81%|████████▏ | 623/765 [03:01<00:43,  3.25it/s]

[623/765]  raw='pass'  → → 1

 82%|████████▏ | 624/765 [03:02<00:42,  3.32it/s]

[624/765]  raw='pass'  → → 1

 82%|████████▏ | 625/765 [03:02<00:41,  3.39it/s]

[625/765]  raw='fail'  → → 0

 82%|████████▏ | 626/765 [03:02<00:40,  3.44it/s]

[626/765]  raw='fail'  → → 0

 82%|████████▏ | 627/765 [03:03<00:40,  3.44it/s]

[627/765]  raw='pass'  → → 1

 82%|████████▏ | 628/765 [03:03<00:39,  3.44it/s]

[628/765]  raw='pass'  → → 1

 82%|████████▏ | 629/765 [03:03<00:39,  3.44it/s]

[629/765]  raw='fail'  → → 0

 82%|████████▏ | 630/765 [03:03<00:42,  3.19it/s]

[630/765]  raw='pass'  → → 1

 82%|████████▏ | 631/765 [03:04<00:52,  2.53it/s]

[631/765]  raw='pass'  → → 1

 83%|████████▎ | 632/765 [03:04<00:48,  2.76it/s]

[632/765]  raw='pass'  → → 1

 83%|████████▎ | 633/765 [03:05<00:47,  2.77it/s]

[633/765]  raw='pass'  → → 1

 83%|████████▎ | 634/765 [03:05<00:44,  2.94it/s]

[634/765]  raw='pass'  → → 1

 83%|████████▎ | 635/765 [03:05<00:42,  3.03it/s]

[635/765]  raw='pass'  → → 1

 83%|████████▎ | 636/765 [03:06<00:40,  3.16it/s]

[636/765]  raw='pass'  → → 1

 83%|████████▎ | 637/765 [03:06<00:39,  3.21it/s]

[637/765]  raw='pass'  → → 1

 83%|████████▎ | 638/765 [03:06<00:38,  3.31it/s]

[638/765]  raw='fail'  → → 0

 84%|████████▎ | 639/765 [03:06<00:36,  3.41it/s]

[639/765]  raw='fail'  → → 0

 84%|████████▎ | 640/765 [03:07<00:36,  3.44it/s]

[640/765]  raw='pass'  → → 1

 84%|████████▍ | 641/765 [03:07<00:36,  3.40it/s]

[641/765]  raw='fail'  → → 0

 84%|████████▍ | 642/765 [03:07<00:40,  3.05it/s]

[642/765]  raw='pass'  → → 1

 84%|████████▍ | 643/765 [03:08<00:38,  3.16it/s]

[643/765]  raw='pass'  → → 1

 84%|████████▍ | 644/765 [03:08<00:36,  3.28it/s]

[644/765]  raw='fail'  → → 0

 84%|████████▍ | 645/765 [03:08<00:35,  3.38it/s]

[645/765]  raw='fail'  → → 0

 84%|████████▍ | 646/765 [03:09<00:35,  3.33it/s]

[646/765]  raw='pass'  → → 1

 85%|████████▍ | 647/765 [03:09<00:38,  3.09it/s]

[647/765]  raw='pass'  → → 1

 85%|████████▍ | 648/765 [03:09<00:36,  3.21it/s]

[648/765]  raw='pass'  → → 1

 85%|████████▍ | 649/765 [03:10<00:35,  3.30it/s]

[649/765]  raw='fail'  → → 0

 85%|████████▍ | 650/765 [03:10<00:34,  3.37it/s]

[650/765]  raw='pass'  → → 1

 85%|████████▌ | 651/765 [03:10<00:33,  3.41it/s]

[651/765]  raw='fail'  → → 0

 85%|████████▌ | 652/765 [03:10<00:32,  3.43it/s]

[652/765]  raw='fail'  → → 0

 85%|████████▌ | 653/765 [03:11<00:32,  3.43it/s]

[653/765]  raw='pass'  → → 1

 85%|████████▌ | 654/765 [03:11<00:32,  3.44it/s]

[654/765]  raw='pass'  → → 1

 86%|████████▌ | 655/765 [03:11<00:31,  3.47it/s]

[655/765]  raw='fail'  → → 0

 86%|████████▌ | 656/765 [03:12<00:31,  3.48it/s]

[656/765]  raw='fail'  → → 0

 86%|████████▌ | 657/765 [03:12<00:31,  3.48it/s]

[657/765]  raw='fail'  → → 0

 86%|████████▌ | 658/765 [03:12<00:30,  3.49it/s]

[658/765]  raw='fail'  → → 0

 86%|████████▌ | 659/765 [03:12<00:30,  3.50it/s]

[659/765]  raw='fail'  → → 0

 86%|████████▋ | 660/765 [03:13<00:30,  3.46it/s]

[660/765]  raw='fail'  → → 0

 86%|████████▋ | 661/765 [03:13<00:33,  3.14it/s]

[661/765]  raw='pass'  → → 1

 87%|████████▋ | 662/765 [03:13<00:32,  3.20it/s]

[662/765]  raw='pass'  → → 1

 87%|████████▋ | 663/765 [03:14<00:31,  3.28it/s]

[663/765]  raw='fail'  → → 0

 87%|████████▋ | 664/765 [03:14<00:30,  3.33it/s]

[664/765]  raw='pass'  → → 1

 87%|████████▋ | 665/765 [03:14<00:29,  3.38it/s]

[665/765]  raw='fail'  → → 0

 87%|████████▋ | 666/765 [03:15<00:29,  3.37it/s]

[666/765]  raw='pass'  → → 1

 87%|████████▋ | 667/765 [03:15<00:28,  3.40it/s]

[667/765]  raw='fail'  → → 0

 87%|████████▋ | 668/765 [03:15<00:28,  3.43it/s]

[668/765]  raw='fail'  → → 0

 87%|████████▋ | 669/765 [03:15<00:28,  3.41it/s]

[669/765]  raw='pass'  → → 1

 88%|████████▊ | 670/765 [03:16<00:27,  3.42it/s]

[670/765]  raw='pass'  → → 1

 88%|████████▊ | 671/765 [03:16<00:30,  3.12it/s]

[671/765]  raw='pass'  → → 1

 88%|████████▊ | 672/765 [03:16<00:29,  3.16it/s]

[672/765]  raw='pass'  → → 1

 88%|████████▊ | 673/765 [03:17<00:28,  3.18it/s]

[673/765]  raw='fail'  → → 0

 88%|████████▊ | 674/765 [03:17<00:29,  3.04it/s]

[674/765]  raw='pass'  → → 1

 88%|████████▊ | 675/765 [03:17<00:28,  3.17it/s]

[675/765]  raw='fail'  → → 0

 88%|████████▊ | 676/765 [03:18<00:27,  3.25it/s]

[676/765]  raw='fail'  → → 0

 88%|████████▊ | 677/765 [03:18<00:26,  3.30it/s]

[677/765]  raw='pass'  → → 1

 89%|████████▊ | 678/765 [03:18<00:25,  3.36it/s]

[678/765]  raw='fail'  → → 0

 89%|████████▉ | 679/765 [03:18<00:25,  3.37it/s]

[679/765]  raw='pass'  → → 1

 89%|████████▉ | 680/765 [03:19<00:24,  3.40it/s]

[680/765]  raw='pass'  → → 1

 89%|████████▉ | 681/765 [03:19<00:24,  3.40it/s]

[681/765]  raw='pass'  → → 1

 89%|████████▉ | 682/765 [03:19<00:24,  3.42it/s]

[682/765]  raw='pass'  → → 1

 89%|████████▉ | 683/765 [03:20<00:23,  3.45it/s]

[683/765]  raw='pass'  → → 1

 89%|████████▉ | 684/765 [03:20<00:23,  3.47it/s]

[684/765]  raw='pass'  → → 1

 90%|████████▉ | 685/765 [03:20<00:22,  3.50it/s]

[685/765]  raw='pass'  → → 1

 90%|████████▉ | 686/765 [03:20<00:22,  3.54it/s]

[686/765]  raw='fail'  → → 0

 90%|████████▉ | 687/765 [03:21<00:21,  3.57it/s]

[687/765]  raw='pass'  → → 1

 90%|████████▉ | 688/765 [03:21<00:21,  3.58it/s]

[688/765]  raw='fail'  → → 0

 90%|█████████ | 689/765 [03:21<00:21,  3.59it/s]

[689/765]  raw='pass'  → → 1

 90%|█████████ | 690/765 [03:22<00:20,  3.60it/s]

[690/765]  raw='fail'  → → 0

 90%|█████████ | 691/765 [03:22<00:20,  3.62it/s]

[691/765]  raw='fail'  → → 0

 90%|█████████ | 692/765 [03:22<00:20,  3.62it/s]

[692/765]  raw='fail'  → → 0

 91%|█████████ | 693/765 [03:23<00:22,  3.24it/s]

[693/765]  raw='pass'  → → 1

 91%|█████████ | 694/765 [03:23<00:21,  3.35it/s]

[694/765]  raw='fail'  → → 0

 91%|█████████ | 695/765 [03:23<00:20,  3.40it/s]

[695/765]  raw='fail'  → → 0

 91%|█████████ | 696/765 [03:23<00:19,  3.47it/s]

[696/765]  raw='fail'  → → 0

 91%|█████████ | 697/765 [03:24<00:19,  3.51it/s]

[697/765]  raw='pass'  → → 1

 91%|█████████ | 698/765 [03:24<00:18,  3.56it/s]

[698/765]  raw='fail'  → → 0

 91%|█████████▏| 699/765 [03:24<00:18,  3.58it/s]

[699/765]  raw='fail'  → → 0

 92%|█████████▏| 700/765 [03:24<00:18,  3.61it/s]

[700/765]  raw='fail'  → → 0

 92%|█████████▏| 701/765 [03:25<00:17,  3.61it/s]

[701/765]  raw='fail'  → → 0

 92%|█████████▏| 702/765 [03:25<00:17,  3.62it/s]

[702/765]  raw='fail'  → → 0

 92%|█████████▏| 703/765 [03:25<00:17,  3.62it/s]

[703/765]  raw='pass'  → → 1

 92%|█████████▏| 704/765 [03:26<00:16,  3.61it/s]

[704/765]  raw='pass'  → → 1

 92%|█████████▏| 705/765 [03:26<00:16,  3.62it/s]

[705/765]  raw='fail'  → → 0

 92%|█████████▏| 706/765 [03:26<00:16,  3.63it/s]

[706/765]  raw='fail'  → → 0

 92%|█████████▏| 707/765 [03:26<00:17,  3.23it/s]

[707/765]  raw='pass'  → → 1

 93%|█████████▎| 708/765 [03:27<00:17,  3.34it/s]

[708/765]  raw='fail'  → → 0

 93%|█████████▎| 709/765 [03:27<00:16,  3.42it/s]

[709/765]  raw='fail'  → → 0

 93%|█████████▎| 710/765 [03:27<00:15,  3.46it/s]

[710/765]  raw='pass'  → → 1

 93%|█████████▎| 711/765 [03:28<00:15,  3.51it/s]

[711/765]  raw='fail'  → → 0

 93%|█████████▎| 712/765 [03:28<00:14,  3.54it/s]

[712/765]  raw='pass'  → → 1

 93%|█████████▎| 713/765 [03:28<00:14,  3.47it/s]

[713/765]  raw='pass'  → → 1

 93%|█████████▎| 714/765 [03:28<00:14,  3.51it/s]

[714/765]  raw='pass'  → → 1

 93%|█████████▎| 715/765 [03:29<00:14,  3.54it/s]

[715/765]  raw='fail'  → → 0

 94%|█████████▎| 716/765 [03:29<00:13,  3.55it/s]

[716/765]  raw='fail'  → → 0

 94%|█████████▎| 717/765 [03:29<00:13,  3.54it/s]

[717/765]  raw='pass'  → → 1

 94%|█████████▍| 718/765 [03:30<00:13,  3.55it/s]

[718/765]  raw='fail'  → → 0

 94%|█████████▍| 719/765 [03:30<00:12,  3.58it/s]

[719/765]  raw='fail'  → → 0

 94%|█████████▍| 720/765 [03:30<00:12,  3.58it/s]

[720/765]  raw='fail'  → → 0

 94%|█████████▍| 721/765 [03:30<00:12,  3.57it/s]

[721/765]  raw='pass'  → → 1

 94%|█████████▍| 722/765 [03:31<00:12,  3.54it/s]

[722/765]  raw='pass'  → → 1

 95%|█████████▍| 723/765 [03:31<00:11,  3.55it/s]

[723/765]  raw='fail'  → → 0

 95%|█████████▍| 724/765 [03:31<00:11,  3.58it/s]

[724/765]  raw='fail'  → → 0

 95%|█████████▍| 725/765 [03:32<00:11,  3.60it/s]

[725/765]  raw='fail'  → → 0

 95%|█████████▍| 726/765 [03:32<00:10,  3.58it/s]

[726/765]  raw='pass'  → → 1

 95%|█████████▌| 727/765 [03:32<00:10,  3.57it/s]

[727/765]  raw='fail'  → → 0

 95%|█████████▌| 728/765 [03:32<00:10,  3.56it/s]

[728/765]  raw='fail'  → → 0

 95%|█████████▌| 729/765 [03:33<00:10,  3.55it/s]

[729/765]  raw='pass'  → → 1

 95%|█████████▌| 730/765 [03:33<00:09,  3.57it/s]

[730/765]  raw='fail'  → → 0

 96%|█████████▌| 731/765 [03:33<00:09,  3.61it/s]

[731/765]  raw='fail'  → → 0

 96%|█████████▌| 732/765 [03:34<00:10,  3.29it/s]

[732/765]  raw='pass'  → → 1

 96%|█████████▌| 733/765 [03:34<00:09,  3.37it/s]

[733/765]  raw='fail'  → → 0

 96%|█████████▌| 734/765 [03:34<00:09,  3.43it/s]

[734/765]  raw='pass'  → → 1

 96%|█████████▌| 735/765 [03:34<00:08,  3.47it/s]

[735/765]  raw='fail'  → → 0

 96%|█████████▌| 736/765 [03:35<00:08,  3.49it/s]

[736/765]  raw='fail'  → → 0

 96%|█████████▋| 737/765 [03:35<00:08,  3.49it/s]

[737/765]  raw='fail'  → → 0

 96%|█████████▋| 738/765 [03:35<00:07,  3.53it/s]

[738/765]  raw='pass'  → → 1

 97%|█████████▋| 739/765 [03:36<00:07,  3.57it/s]

[739/765]  raw='fail'  → → 0

 97%|█████████▋| 740/765 [03:36<00:07,  3.56it/s]

[740/765]  raw='fail'  → → 0

 97%|█████████▋| 741/765 [03:36<00:06,  3.59it/s]

[741/765]  raw='fail'  → → 0

 97%|█████████▋| 742/765 [03:36<00:06,  3.60it/s]

[742/765]  raw='pass'  → → 1

 97%|█████████▋| 743/765 [03:37<00:06,  3.60it/s]

[743/765]  raw='fail'  → → 0

 97%|█████████▋| 744/765 [03:37<00:05,  3.61it/s]

[744/765]  raw='pass'  → → 1

 97%|█████████▋| 745/765 [03:37<00:05,  3.60it/s]

[745/765]  raw='fail'  → → 0

 98%|█████████▊| 746/765 [03:37<00:05,  3.61it/s]

[746/765]  raw='pass'  → → 1

 98%|█████████▊| 747/765 [03:38<00:04,  3.63it/s]

[747/765]  raw='pass'  → → 1

 98%|█████████▊| 748/765 [03:38<00:04,  3.62it/s]

[748/765]  raw='pass'  → → 1

 98%|█████████▊| 749/765 [03:38<00:04,  3.62it/s]

[749/765]  raw='fail'  → → 0

 98%|█████████▊| 750/765 [03:39<00:04,  3.62it/s]

[750/765]  raw='fail'  → → 0

 98%|█████████▊| 751/765 [03:39<00:03,  3.62it/s]

[751/765]  raw='pass'  → → 1

 98%|█████████▊| 752/765 [03:39<00:03,  3.52it/s]

[752/765]  raw='pass'  → → 1

 98%|█████████▊| 753/765 [03:39<00:03,  3.55it/s]

[753/765]  raw='fail'  → → 0

 99%|█████████▊| 754/765 [03:40<00:03,  3.54it/s]

[754/765]  raw='fail'  → → 0

 99%|█████████▊| 755/765 [03:40<00:02,  3.54it/s]

[755/765]  raw='pass'  → → 1

 99%|█████████▉| 756/765 [03:40<00:02,  3.48it/s]

[756/765]  raw='pass'  → → 1

 99%|█████████▉| 757/765 [03:41<00:02,  3.51it/s]

[757/765]  raw='pass'  → → 1

 99%|█████████▉| 758/765 [03:41<00:01,  3.52it/s]

[758/765]  raw='pass'  → → 1

 99%|█████████▉| 759/765 [03:41<00:01,  3.45it/s]

[759/765]  raw='pass'  → → 1

 99%|█████████▉| 760/765 [03:41<00:01,  3.49it/s]

[760/765]  raw='pass'  → → 1

 99%|█████████▉| 761/765 [03:42<00:01,  3.51it/s]

[761/765]  raw='pass'  → → 1

100%|█████████▉| 762/765 [03:42<00:00,  3.52it/s]

[762/765]  raw='fail'  → → 0

100%|█████████▉| 763/765 [03:42<00:00,  3.40it/s]

[763/765]  raw='pass'  → → 1

100%|█████████▉| 764/765 [03:43<00:00,  3.43it/s]

[764/765]  raw='pass'  → → 1

100%|██████████| 765/765 [03:43<00:00,  3.42it/s]

[765/765]  raw='fail'  → → 0
Parsed: 765/765
Accuracy: 0.8588
              precision    recall  f1-score   support

        Fail       0.94      0.81      0.87       442
        Pass       0.78      0.93      0.85       323

    accuracy                           0.86       765
   macro avg       0.86      0.87      0.86       765
weighted avg       0.87      0.86      0.86       765

[[357  85]
 [ 23 300]]

In [ ]:
#from downloading it from drive
# ── 1. get the adapter from Drive (Cell B pattern) ──
from google.colab import drive
import shutil, os
drive.mount("/content/drive")

LOCAL  = "./qwen2-lora-balanced-adapter"
DRIVE  = "/content/drive/MyDrive/qwen2-lora-balanced-adapter"

if not os.path.exists(LOCAL):
    shutil.copytree(DRIVE, LOCAL)
print("Files:", os.listdir(LOCAL))   # expect adapter_model.safetensors, adapter_config.json, tokenizer files

# ── 2. load base model (4-bit) + attach the trained adapter ──
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel
import torch

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16, bnb_4bit_use_double_quant=True,
)

base = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2-7B-Instruct",
    quantization_config=bnb_config,
    device_map="auto",
)

model_ft = PeftModel.from_pretrained(base, LOCAL)
model_ft.eval()
model_ft.config.use_cache = False

tokenizer = AutoTokenizer.from_pretrained(LOCAL)   # the saved tokenizer, with chat template
tokenizer.padding_side = "left"                    # inference

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Files: ['adapter_model.safetensors', 'tokenizer_config.json', 'chat_template.jinja', 'adapter_config.json', 'README.md', 'tokenizer.json']

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

In [ ]:
#3. use it — same predict function as always ──
y_pred, y_generated = predict_decoder_only(X_test_prompts, model_ft, tokenizer)

In [ ]:
from google.colab import runtime
print("Adapter safe on Drive. Releasing the A100.")
runtime.unassign()

Adapter safe on Drive. Releasing the A100.

### testing

In [ ]:
# L4 GPU 4h crashing not working T_T, 3 times!!
sft_config = SFTConfig(
    output_dir="./qwen2-lora-balanced",     # Qwen path
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    warmup_steps=50,
    learning_rate=2e-4,
    fp16=False, bf16=False,
    logging_steps=25,
    eval_strategy="steps", eval_steps=100,
    save_strategy="steps", save_steps=100,
    load_best_model_at_end=True, metric_for_best_model="eval_loss",
    report_to="none",
    max_length=2000,
    completion_only_loss=True,
    optim="paged_adamw_8bit",
)

# fp32 cast, same cell as trainer
for n, p in model.named_parameters():
    if p.requires_grad: p.data = p.data.float()

trainer = SFTTrainer(
    model=model, args=sft_config,
    train_dataset=train_hf,
    eval_dataset=val_hf.select(range(250)),
    processing_class=tokenizer,
)
trainer.train()

Adding EOS to train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/250 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

In [ ]:
# Save adapter locally
ADAPTER_PATH = "./qwen2-lora-balanced-adapter"

trainer.model.save_pretrained(ADAPTER_PATH)
tokenizer.save_pretrained(ADAPTER_PATH)
print(f"Saved locally: {ADAPTER_PATH}")
print(f"Files: {os.listdir(ADAPTER_PATH)}")

Saved locally: ./qwen2-lora-balanced-adapter
Files: ['adapter_model.safetensors', 'tokenizer_config.json', 'chat_template.jinja', 'adapter_config.json', 'README.md', 'tokenizer.json']

In [ ]:
# Backup to Drive
import shutil, os
from google.colab import drive

drive.mount("/content/drive", force_remount=True)

LOCAL_ADAPTER_PATH = "./qwen2-lora-balanced-adapter"
DRIVE_ADAPTER_PATH = "/content/drive/MyDrive/qwen2-lora-balanced-adapter"

# safety: never touch Drive unless the fresh local adapter exists
assert os.path.exists(LOCAL_ADAPTER_PATH), "No local adapter — did the save cell run?"

if os.path.exists(DRIVE_ADAPTER_PATH):
    shutil.rmtree(DRIVE_ADAPTER_PATH)
    print("Removed old version from Drive")

shutil.copytree(LOCAL_ADAPTER_PATH, DRIVE_ADAPTER_PATH)
print(f"   Backed up to Drive: {DRIVE_ADAPTER_PATH}")
print(f"   Files: {os.listdir(DRIVE_ADAPTER_PATH)}")

In [ ]:
# Kill the runtime after everything is saved
from google.colab import runtime
print("All saved. Terminating runtime good night.")
runtime.unassign()

In [ ]:
# Cell ??: Load base model and apply LoRA
gc.collect()
torch.cuda.empty_cache()

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)
model.config.pad_token_id = tokenizer.eos_token_id
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)
model = get_peft_model(model, lora_config)

# cast trainable LoRA layers to float16 (avoids bfloat16 error on T4)
for _, param in model.named_parameters():
    if param.requires_grad:
        param.data = param.data.to(torch.float16)

dtypes = set(p.dtype for p in model.parameters())
print("Dtypes in model:", dtypes)    # should NOT contain torch.bfloat16 im getting error T_T
model.print_trainable_parameters()

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Dtypes in model: {torch.uint8, torch.float32, torch.float16}
trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

In [ ]:
# Fine-tune T4 GPU
# fp16/bf16 disabled avoids  bfloat16 error on T4
# Qwen2 has 128k context but we cap at 2048 to fit T4 memory
sft_config = SFTConfig(
    output_dir="./qwen2-lora-balanced",
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,      # effective batch size = 8
    warmup_steps=50,
    learning_rate=2e-4,
    fp16=False,
    bf16=False,
    logging_steps=25,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    report_to="none",
    max_length=2048,                    # Qwen2 supports 128k but T4 caps here
    dataset_text_field="text",
    loss_type="nll",
    optim="paged_adamw_8bit",
)

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_hf,
    eval_dataset=val_hf,
    processing_class=tokenizer,
)

print("Starting fine-tuning...")
trainer.train()

Adding EOS to train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3010 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/765 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/765 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151645}.

Starting fine-tuning...

TrainOutput(global_step=1131, training_loss=51289129.7788974, metrics={'train_runtime': 18991.2316, 'train_samples_per_second': 0.475, 'train_steps_per_second': 0.06, 'total_flos': 2.2126878604331827e+17, 'train_loss': 51289129.7788974, 'epoch': 3.0})

In [ ]:
# clean up a corrupted state
# Step 1 clean up corrupted state
for var in ["model", "ft_model", "base_model", "trainer"]:
    if var in dir():
        exec(f"del {var}")
        print(f"  deleted {var}")

gc.collect()
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()
print("Free GPU (GB):", round(torch.cuda.mem_get_info()[0] / 1e9, 2))

  deleted model
  deleted trainer
Free GPU (GB): 2.63

In [ ]:
#Save adapter
trainer.model.save_pretrained(ADAPTER_PATH)
tokenizer.save_pretrained(ADAPTER_PATH)
print(f"Adapter saved to {ADAPTER_PATH}")

Adapter saved to ./qwen2-lora-balanced-adapter

In [ ]:
#Load fine-tuned model for inference
gc.collect()
torch.cuda.empty_cache()

tokenizer.padding_side = "left"     # switch to left padding for inference

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
)
ft_model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
ft_model.eval()

X_test_prompts_qwen_ft = pd.DataFrame(
    test_df.apply(generate_qwen_test_prompt, axis=1), columns=["text"]
)
print(f"Test prompts : {len(X_test_prompts_qwen_ft)}")
print("Last 50 chars:", repr(X_test_prompts_qwen_ft["text"].iloc[0][-50:]))
# should end with '<|im_start|>assistant\n'

NameError: name 'gc' is not defined

In [ ]:
# Predict
def predict_qwen_ft(test, model, tokenizer, max_input_tokens=2048):
    y_pred, y_generated = [], []
    model.eval()

    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]
        inputs = tokenizer(
            prompt, return_tensors="pt",
            truncation=True, max_length=max_input_tokens, padding=False,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=3,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
        generated  = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        result = {1: "Pass", 0: "Fail", -1: "???"}[y_pred[-1]]
        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {result}")

    return y_pred, y_generated


y_pred, y_generated = predict_qwen_ft(X_test_prompts_qwen_ft, ft_model, tokenizer)

  0%|          | 0/765 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
  0%|          | 1/765 [00:00<07:31,  1.69it/s]

[  1/765]  raw='fail'  →  Fail

  0%|          | 2/765 [00:01<07:21,  1.73it/s]

[  2/765]  raw='fail'  →  Fail

  0%|          | 3/765 [00:01<07:02,  1.80it/s]

[  3/765]  raw='fail'  →  Fail

  1%|          | 4/765 [00:02<07:51,  1.62it/s]

[  4/765]  raw='pass'  →  Pass

  1%|          | 5/765 [00:02<07:03,  1.80it/s]

[  5/765]  raw='fail'  →  Fail

  1%|          | 6/765 [00:03<06:56,  1.82it/s]

[  6/765]  raw='fail'  →  Fail

  1%|          | 7/765 [00:04<07:20,  1.72it/s]

[  7/765]  raw='pass'  →  Pass

  1%|          | 8/765 [00:04<07:10,  1.76it/s]

[  8/765]  raw='fail'  →  Fail

  1%|          | 9/765 [00:05<07:43,  1.63it/s]

[  9/765]  raw='pass'  →  Pass

  1%|▏         | 10/765 [00:05<07:03,  1.78it/s]

[ 10/765]  raw='fail'  →  Fail

  1%|▏         | 11/765 [00:06<06:58,  1.80it/s]

[ 11/765]  raw='fail'  →  Fail

  2%|▏         | 12/765 [00:06<07:32,  1.67it/s]

[ 12/765]  raw='pass'  →  Pass

  2%|▏         | 13/765 [00:07<07:19,  1.71it/s]

[ 13/765]  raw='pass'  →  Pass

  2%|▏         | 14/765 [00:08<07:19,  1.71it/s]

[ 14/765]  raw='pass'  →  Pass

  2%|▏         | 15/765 [00:08<07:08,  1.75it/s]

[ 15/765]  raw='fail'  →  Fail

  2%|▏         | 16/765 [00:09<07:14,  1.72it/s]

[ 16/765]  raw='pass'  →  Pass

  2%|▏         | 17/765 [00:09<07:05,  1.76it/s]

[ 17/765]  raw='pass'  →  Pass

  2%|▏         | 18/765 [00:10<07:25,  1.68it/s]

[ 18/765]  raw='pass'  →  Pass

  2%|▏         | 19/765 [00:10<06:59,  1.78it/s]

[ 19/765]  raw='fail'  →  Fail

  3%|▎         | 20/765 [00:11<07:51,  1.58it/s]

[ 20/765]  raw='pass'  →  Pass

  3%|▎         | 21/765 [00:12<07:16,  1.70it/s]

[ 21/765]  raw='fail'  →  Fail

  3%|▎         | 22/765 [00:12<06:51,  1.81it/s]

[ 22/765]  raw='fail'  →  Fail

  3%|▎         | 23/765 [00:13<06:33,  1.88it/s]

[ 23/765]  raw='fail'  →  Fail

  3%|▎         | 24/765 [00:13<07:24,  1.67it/s]

[ 24/765]  raw='pass'  →  Pass

  3%|▎         | 25/765 [00:14<07:26,  1.66it/s]

[ 25/765]  raw='pass'  →  Pass

  3%|▎         | 26/765 [00:15<07:10,  1.72it/s]

[ 26/765]  raw='fail'  →  Fail

  4%|▎         | 27/765 [00:15<06:48,  1.80it/s]

[ 27/765]  raw='fail'  →  Fail

  4%|▎         | 28/765 [00:16<06:45,  1.82it/s]

[ 28/765]  raw='fail'  →  Fail

  4%|▍         | 29/765 [00:16<06:50,  1.79it/s]

[ 29/765]  raw='pass'  →  Pass

  4%|▍         | 30/765 [00:17<06:43,  1.82it/s]

[ 30/765]  raw='fail'  →  Fail

  4%|▍         | 31/765 [00:17<06:49,  1.79it/s]

[ 31/765]  raw='pass'  →  Pass

  4%|▍         | 32/765 [00:18<06:42,  1.82it/s]

[ 32/765]  raw='fail'  →  Fail

  4%|▍         | 33/765 [00:19<07:27,  1.64it/s]

[ 33/765]  raw='pass'  →  Pass

  4%|▍         | 34/765 [00:19<07:08,  1.70it/s]

[ 34/765]  raw='fail'  →  Fail

  5%|▍         | 35/765 [00:20<06:56,  1.75it/s]

[ 35/765]  raw='fail'  →  Fail

  5%|▍         | 36/765 [00:20<06:50,  1.78it/s]

[ 36/765]  raw='fail'  →  Fail

  5%|▍         | 37/765 [00:21<06:54,  1.76it/s]

[ 37/765]  raw='pass'  →  Pass

  5%|▍         | 38/765 [00:21<06:50,  1.77it/s]

[ 38/765]  raw='fail'  →  Fail

  5%|▌         | 39/765 [00:22<07:03,  1.71it/s]

[ 39/765]  raw='pass'  →  Pass

  5%|▌         | 40/765 [00:23<07:30,  1.61it/s]

[ 40/765]  raw='pass'  →  Pass

  5%|▌         | 41/765 [00:23<08:19,  1.45it/s]

[ 41/765]  raw='pass'  →  Pass

  5%|▌         | 42/765 [00:24<08:00,  1.50it/s]

[ 42/765]  raw='fail'  →  Fail

  6%|▌         | 43/765 [00:25<07:21,  1.64it/s]

[ 43/765]  raw='fail'  →  Fail

  6%|▌         | 44/765 [00:25<07:07,  1.68it/s]

[ 44/765]  raw='pass'  →  Pass

  6%|▌         | 45/765 [00:26<06:42,  1.79it/s]

[ 45/765]  raw='fail'  →  Fail

  6%|▌         | 46/765 [00:26<06:40,  1.79it/s]

[ 46/765]  raw='fail'  →  Fail

  6%|▌         | 47/765 [00:27<06:34,  1.82it/s]

[ 47/765]  raw='fail'  →  Fail

  6%|▋         | 48/765 [00:27<06:40,  1.79it/s]

[ 48/765]  raw='pass'  →  Pass

  6%|▋         | 49/765 [00:28<06:35,  1.81it/s]

[ 49/765]  raw='fail'  →  Fail

  7%|▋         | 50/765 [00:28<06:55,  1.72it/s]

[ 50/765]  raw='pass'  →  Pass

  7%|▋         | 51/765 [00:29<06:43,  1.77it/s]

[ 51/765]  raw='fail'  →  Fail

  7%|▋         | 52/765 [00:29<06:26,  1.85it/s]

[ 52/765]  raw='fail'  →  Fail

  7%|▋         | 53/765 [00:30<06:33,  1.81it/s]

[ 53/765]  raw='fail'  →  Fail

  7%|▋         | 54/765 [00:31<07:46,  1.52it/s]

[ 54/765]  raw='pass'  →  Pass

  7%|▋         | 55/765 [00:31<07:19,  1.62it/s]

[ 55/765]  raw='fail'  →  Fail

  7%|▋         | 56/765 [00:32<07:00,  1.69it/s]

[ 56/765]  raw='fail'  →  Fail

  7%|▋         | 57/765 [00:33<06:45,  1.75it/s]

[ 57/765]  raw='fail'  →  Fail

  8%|▊         | 58/765 [00:33<06:46,  1.74it/s]

[ 58/765]  raw='fail'  →  Fail

  8%|▊         | 59/765 [00:34<06:53,  1.71it/s]

[ 59/765]  raw='pass'  →  Pass

  8%|▊         | 60/765 [00:34<06:33,  1.79it/s]

[ 60/765]  raw='fail'  →  Fail

  8%|▊         | 61/765 [00:35<06:49,  1.72it/s]

[ 61/765]  raw='pass'  →  Pass

  8%|▊         | 62/765 [00:35<06:50,  1.71it/s]

[ 62/765]  raw='fail'  →  Fail

  8%|▊         | 63/765 [00:36<07:12,  1.62it/s]

[ 63/765]  raw='pass'  →  Pass

  8%|▊         | 64/765 [00:37<06:44,  1.73it/s]

[ 64/765]  raw='fail'  →  Fail

  8%|▊         | 65/765 [00:37<06:15,  1.86it/s]

[ 65/765]  raw='fail'  →  Fail

  9%|▊         | 66/765 [00:38<06:30,  1.79it/s]

[ 66/765]  raw='pass'  →  Pass

  9%|▉         | 67/765 [00:38<06:57,  1.67it/s]

[ 67/765]  raw='pass'  →  Pass

  9%|▉         | 68/765 [00:39<06:43,  1.73it/s]

[ 68/765]  raw='fail'  →  Fail

  9%|▉         | 69/765 [00:39<06:32,  1.78it/s]

[ 69/765]  raw='fail'  →  Fail

  9%|▉         | 70/765 [00:40<06:13,  1.86it/s]

[ 70/765]  raw='fail'  →  Fail

  9%|▉         | 71/765 [00:40<06:10,  1.87it/s]

[ 71/765]  raw='fail'  →  Fail

  9%|▉         | 72/765 [00:41<05:59,  1.93it/s]

[ 72/765]  raw='fail'  →  Fail

 10%|▉         | 73/765 [00:41<06:01,  1.92it/s]

[ 73/765]  raw='fail'  →  Fail

 10%|▉         | 74/765 [00:42<06:06,  1.89it/s]

[ 74/765]  raw='fail'  →  Fail

 10%|▉         | 75/765 [00:42<05:56,  1.94it/s]

[ 75/765]  raw='fail'  →  Fail

 10%|▉         | 76/765 [00:43<06:19,  1.82it/s]

[ 76/765]  raw='pass'  →  Pass

 10%|█         | 77/765 [00:44<06:05,  1.88it/s]

[ 77/765]  raw='fail'  →  Fail

 10%|█         | 78/765 [00:44<06:14,  1.83it/s]

[ 78/765]  raw='pass'  →  Pass

 10%|█         | 79/765 [00:45<05:58,  1.91it/s]

[ 79/765]  raw='fail'  →  Fail

 10%|█         | 80/765 [00:45<06:41,  1.71it/s]

[ 80/765]  raw='pass'  →  Pass

 11%|█         | 81/765 [00:46<06:52,  1.66it/s]

[ 81/765]  raw='pass'  →  Pass

 11%|█         | 82/765 [00:47<06:47,  1.68it/s]

[ 82/765]  raw='fail'  →  Fail

 11%|█         | 83/765 [00:47<07:33,  1.50it/s]

[ 83/765]  raw='pass'  →  Pass

 11%|█         | 84/765 [00:48<08:00,  1.42it/s]

[ 84/765]  raw='pass'  →  Pass

 11%|█         | 85/765 [00:49<07:10,  1.58it/s]

[ 85/765]  raw='fail'  →  Fail

 11%|█         | 86/765 [00:49<07:00,  1.62it/s]

[ 86/765]  raw='fail'  →  Fail

 11%|█▏        | 87/765 [00:50<06:43,  1.68it/s]

[ 87/765]  raw='fail'  →  Fail

 12%|█▏        | 88/765 [00:50<06:27,  1.75it/s]

[ 88/765]  raw='fail'  →  Fail

 12%|█▏        | 89/765 [00:51<06:33,  1.72it/s]

[ 89/765]  raw='pass'  →  Pass

 12%|█▏        | 90/765 [00:51<06:11,  1.81it/s]

[ 90/765]  raw='fail'  →  Fail

 12%|█▏        | 91/765 [00:52<06:26,  1.74it/s]

[ 91/765]  raw='pass'  →  Pass

 12%|█▏        | 92/765 [00:53<07:10,  1.56it/s]

[ 92/765]  raw='pass'  →  Pass

 12%|█▏        | 93/765 [00:54<07:15,  1.54it/s]

[ 93/765]  raw='pass'  →  Pass

 12%|█▏        | 94/765 [00:54<06:44,  1.66it/s]

[ 94/765]  raw='fail'  →  Fail

 12%|█▏        | 95/765 [00:55<06:29,  1.72it/s]

[ 95/765]  raw='fail'  →  Fail

 13%|█▎        | 96/765 [00:55<06:06,  1.82it/s]

[ 96/765]  raw='fail'  →  Fail

 13%|█▎        | 97/765 [00:55<05:51,  1.90it/s]

[ 97/765]  raw='fail'  →  Fail

 13%|█▎        | 98/765 [00:56<05:44,  1.94it/s]

[ 98/765]  raw='fail'  →  Fail

 13%|█▎        | 99/765 [00:57<06:34,  1.69it/s]

[ 99/765]  raw='pass'  →  Pass

 13%|█▎        | 100/765 [00:57<06:08,  1.80it/s]

[100/765]  raw='fail'  →  Fail

 13%|█▎        | 101/765 [00:58<05:50,  1.89it/s]

[101/765]  raw='fail'  →  Fail

 13%|█▎        | 102/765 [00:58<05:49,  1.90it/s]

[102/765]  raw='fail'  →  Fail

 13%|█▎        | 103/765 [00:59<05:41,  1.94it/s]

[103/765]  raw='fail'  →  Fail

 14%|█▎        | 104/765 [00:59<05:43,  1.92it/s]

[104/765]  raw='fail'  →  Fail

 14%|█▎        | 105/765 [01:00<05:36,  1.96it/s]

[105/765]  raw='fail'  →  Fail

 14%|█▍        | 106/765 [01:00<06:27,  1.70it/s]

[106/765]  raw='pass'  →  Pass

 14%|█▍        | 107/765 [01:01<06:37,  1.66it/s]

[107/765]  raw='pass'  →  Pass

 14%|█▍        | 108/765 [01:02<06:14,  1.75it/s]

[108/765]  raw='fail'  →  Fail

 14%|█▍        | 109/765 [01:02<06:30,  1.68it/s]

[109/765]  raw='pass'  →  Pass

 14%|█▍        | 110/765 [01:03<06:16,  1.74it/s]

[110/765]  raw='fail'  →  Fail

 15%|█▍        | 111/765 [01:03<06:06,  1.79it/s]

[111/765]  raw='fail'  →  Fail

 15%|█▍        | 112/765 [01:04<05:47,  1.88it/s]

[112/765]  raw='fail'  →  Fail

 15%|█▍        | 113/765 [01:04<05:49,  1.86it/s]

[113/765]  raw='pass'  →  Pass

 15%|█▍        | 114/765 [01:05<05:58,  1.82it/s]

[114/765]  raw='fail'  →  Fail

 15%|█▌        | 115/765 [01:05<05:44,  1.89it/s]

[115/765]  raw='fail'  →  Fail

 15%|█▌        | 116/765 [01:06<05:43,  1.89it/s]

[116/765]  raw='fail'  →  Fail

 15%|█▌        | 117/765 [01:07<05:55,  1.82it/s]

[117/765]  raw='fail'  →  Fail

 15%|█▌        | 118/765 [01:07<06:02,  1.78it/s]

[118/765]  raw='pass'  →  Pass

 16%|█▌        | 119/765 [01:08<05:55,  1.82it/s]

[119/765]  raw='fail'  →  Fail

 16%|█▌        | 120/765 [01:08<06:10,  1.74it/s]

[120/765]  raw='pass'  →  Pass

 16%|█▌        | 121/765 [01:09<06:27,  1.66it/s]

[121/765]  raw='pass'  →  Pass

 16%|█▌        | 122/765 [01:10<06:22,  1.68it/s]

[122/765]  raw='fail'  →  Fail

 16%|█▌        | 123/765 [01:10<06:35,  1.63it/s]

[123/765]  raw='pass'  →  Pass

 16%|█▌        | 124/765 [01:11<06:42,  1.59it/s]

[124/765]  raw='fail'  →  Fail

 16%|█▋        | 125/765 [01:11<06:11,  1.72it/s]

[125/765]  raw='fail'  →  Fail

 16%|█▋        | 126/765 [01:12<06:03,  1.76it/s]

[126/765]  raw='fail'  →  Fail

 17%|█▋        | 127/765 [01:12<05:55,  1.79it/s]

[127/765]  raw='fail'  →  Fail

 17%|█▋        | 128/765 [01:13<05:50,  1.82it/s]

[128/765]  raw='fail'  →  Fail

 17%|█▋        | 129/765 [01:14<06:00,  1.76it/s]

[129/765]  raw='fail'  →  Fail

 17%|█▋        | 130/765 [01:14<06:23,  1.66it/s]

[130/765]  raw='pass'  →  Pass

 17%|█▋        | 131/765 [01:15<06:11,  1.71it/s]

[131/765]  raw='fail'  →  Fail

 17%|█▋        | 132/765 [01:15<05:59,  1.76it/s]

[132/765]  raw='fail'  →  Fail

 17%|█▋        | 133/765 [01:16<05:50,  1.80it/s]

[133/765]  raw='fail'  →  Fail

 18%|█▊        | 134/765 [01:16<05:52,  1.79it/s]

[134/765]  raw='fail'  →  Fail

 18%|█▊        | 135/765 [01:17<05:47,  1.81it/s]

[135/765]  raw='fail'  →  Fail

 18%|█▊        | 136/765 [01:17<05:52,  1.79it/s]

[136/765]  raw='fail'  →  Fail

 18%|█▊        | 137/765 [01:18<06:41,  1.56it/s]

[137/765]  raw='pass'  →  Pass

 18%|█▊        | 138/765 [01:19<06:35,  1.59it/s]

[138/765]  raw='pass'  →  Pass

 18%|█▊        | 139/765 [01:20<07:10,  1.45it/s]

[139/765]  raw='pass'  →  Pass

 18%|█▊        | 140/765 [01:20<06:29,  1.61it/s]

[140/765]  raw='fail'  →  Fail

 18%|█▊        | 141/765 [01:21<06:09,  1.69it/s]

[141/765]  raw='fail'  →  Fail

 19%|█▊        | 142/765 [01:21<06:23,  1.62it/s]

[142/765]  raw='fail'  →  Fail

 19%|█▊        | 143/765 [01:22<06:07,  1.69it/s]

[143/765]  raw='fail'  →  Fail

 19%|█▉        | 144/765 [01:23<07:08,  1.45it/s]

[144/765]  raw='pass'  →  Pass

 19%|█▉        | 145/765 [01:23<06:48,  1.52it/s]

[145/765]  raw='pass'  →  Pass

 19%|█▉        | 146/765 [01:24<06:22,  1.62it/s]

[146/765]  raw='fail'  →  Fail

 19%|█▉        | 147/765 [01:25<07:00,  1.47it/s]

[147/765]  raw='pass'  →  Pass

 19%|█▉        | 148/765 [01:25<06:54,  1.49it/s]

[148/765]  raw='pass'  →  Pass

 19%|█▉        | 149/765 [01:26<06:36,  1.55it/s]

[149/765]  raw='fail'  →  Fail

 20%|█▉        | 150/765 [01:27<06:15,  1.64it/s]

[150/765]  raw='fail'  →  Fail

 20%|█▉        | 151/765 [01:27<06:41,  1.53it/s]

[151/765]  raw='pass'  →  Pass

 20%|█▉        | 152/765 [01:28<06:35,  1.55it/s]

[152/765]  raw='pass'  →  Pass

 20%|██        | 153/765 [01:28<06:15,  1.63it/s]

[153/765]  raw='fail'  →  Fail

 20%|██        | 154/765 [01:29<06:18,  1.61it/s]

[154/765]  raw='pass'  →  Pass

 20%|██        | 155/765 [01:30<06:21,  1.60it/s]

[155/765]  raw='pass'  →  Pass

 20%|██        | 156/765 [01:30<06:35,  1.54it/s]

[156/765]  raw='pass'  →  Pass

 21%|██        | 157/765 [01:31<06:42,  1.51it/s]

[157/765]  raw='pass'  →  Pass

 21%|██        | 158/765 [01:32<06:49,  1.48it/s]

[158/765]  raw='pass'  →  Pass

 21%|██        | 159/765 [01:32<06:41,  1.51it/s]

[159/765]  raw='pass'  →  Pass

 21%|██        | 160/765 [01:33<06:49,  1.48it/s]

[160/765]  raw='pass'  →  Pass

 21%|██        | 161/765 [01:34<06:13,  1.62it/s]

[161/765]  raw='fail'  →  Fail

 21%|██        | 162/765 [01:34<05:45,  1.74it/s]

[162/765]  raw='fail'  →  Fail

 21%|██▏       | 163/765 [01:35<05:45,  1.74it/s]

[163/765]  raw='fail'  →  Fail

 21%|██▏       | 164/765 [01:35<05:44,  1.74it/s]

[164/765]  raw='pass'  →  Pass

 22%|██▏       | 165/765 [01:36<05:46,  1.73it/s]

[165/765]  raw='fail'  →  Fail

 22%|██▏       | 166/765 [01:36<05:38,  1.77it/s]

[166/765]  raw='fail'  →  Fail

 22%|██▏       | 167/765 [01:37<05:23,  1.85it/s]

[167/765]  raw='fail'  →  Fail

 22%|██▏       | 168/765 [01:37<05:23,  1.85it/s]

[168/765]  raw='fail'  →  Fail

 22%|██▏       | 169/765 [01:38<05:34,  1.78it/s]

[169/765]  raw='pass'  →  Pass

 22%|██▏       | 170/765 [01:39<05:30,  1.80it/s]

[170/765]  raw='fail'  →  Fail

 22%|██▏       | 171/765 [01:39<05:55,  1.67it/s]

[171/765]  raw='pass'  →  Pass

 22%|██▏       | 172/765 [01:40<06:05,  1.62it/s]

[172/765]  raw='pass'  →  Pass

 23%|██▎       | 173/765 [01:41<06:33,  1.50it/s]

[173/765]  raw='pass'  →  Pass

 23%|██▎       | 174/765 [01:41<06:48,  1.45it/s]

[174/765]  raw='pass'  →  Pass

 23%|██▎       | 175/765 [01:42<06:08,  1.60it/s]

[175/765]  raw='fail'  →  Fail

 23%|██▎       | 176/765 [01:42<05:50,  1.68it/s]

[176/765]  raw='fail'  →  Fail

 23%|██▎       | 177/765 [01:43<05:38,  1.74it/s]

[177/765]  raw='fail'  →  Fail

 23%|██▎       | 178/765 [01:44<05:57,  1.64it/s]

[178/765]  raw='pass'  →  Pass

 23%|██▎       | 179/765 [01:45<06:37,  1.47it/s]

[179/765]  raw='pass'  →  Pass

 24%|██▎       | 180/765 [01:45<05:55,  1.64it/s]

[180/765]  raw='fail'  →  Fail

 24%|██▎       | 181/765 [01:45<05:32,  1.75it/s]

[181/765]  raw='fail'  →  Fail

 24%|██▍       | 182/765 [01:46<05:14,  1.86it/s]

[182/765]  raw='fail'  →  Fail

 24%|██▍       | 183/765 [01:46<05:06,  1.90it/s]

[183/765]  raw='fail'  →  Fail

 24%|██▍       | 184/765 [01:47<04:57,  1.95it/s]

[184/765]  raw='fail'  →  Fail

 24%|██▍       | 185/765 [01:48<05:19,  1.82it/s]

[185/765]  raw='pass'  →  Pass

 24%|██▍       | 186/765 [01:48<05:48,  1.66it/s]

[186/765]  raw='pass'  →  Pass

 24%|██▍       | 187/765 [01:49<05:42,  1.69it/s]

[187/765]  raw='fail'  →  Fail

 25%|██▍       | 188/765 [01:49<05:21,  1.80it/s]

[188/765]  raw='fail'  →  Fail

 25%|██▍       | 189/765 [01:50<05:33,  1.73it/s]

[189/765]  raw='pass'  →  Pass

 25%|██▍       | 190/765 [01:51<05:42,  1.68it/s]

[190/765]  raw='pass'  →  Pass

 25%|██▍       | 191/765 [01:51<05:47,  1.65it/s]

[191/765]  raw='pass'  →  Pass

 25%|██▌       | 192/765 [01:52<06:19,  1.51it/s]

[192/765]  raw='pass'  →  Pass

 25%|██▌       | 193/765 [01:53<06:06,  1.56it/s]

[193/765]  raw='fail'  →  Fail

 25%|██▌       | 194/765 [01:53<05:55,  1.61it/s]

[194/765]  raw='fail'  →  Fail

 25%|██▌       | 195/765 [01:54<06:44,  1.41it/s]

[195/765]  raw='pass'  →  Pass

 26%|██▌       | 196/765 [01:55<06:05,  1.56it/s]

[196/765]  raw='fail'  →  Fail

 26%|██▌       | 197/765 [01:55<06:06,  1.55it/s]

[197/765]  raw='pass'  →  Pass

 26%|██▌       | 198/765 [01:56<05:45,  1.64it/s]

[198/765]  raw='fail'  →  Fail

 26%|██▌       | 199/765 [01:56<05:40,  1.66it/s]

[199/765]  raw='pass'  →  Pass

 26%|██▌       | 200/765 [01:57<05:22,  1.75it/s]

[200/765]  raw='fail'  →  Fail

 26%|██▋       | 201/765 [01:57<05:17,  1.77it/s]

[201/765]  raw='fail'  →  Fail

 26%|██▋       | 202/765 [01:58<05:18,  1.77it/s]

[202/765]  raw='pass'  →  Pass

 27%|██▋       | 203/765 [01:59<05:23,  1.74it/s]

[203/765]  raw='fail'  →  Fail

 27%|██▋       | 204/765 [01:59<05:16,  1.77it/s]

[204/765]  raw='fail'  →  Fail

 27%|██▋       | 205/765 [02:00<05:09,  1.81it/s]

[205/765]  raw='fail'  →  Fail

 27%|██▋       | 206/765 [02:00<05:14,  1.78it/s]

[206/765]  raw='fail'  →  Fail

 27%|██▋       | 207/765 [02:01<05:39,  1.64it/s]

[207/765]  raw='pass'  →  Pass

 27%|██▋       | 208/765 [02:02<05:42,  1.63it/s]

[208/765]  raw='pass'  →  Pass

 27%|██▋       | 209/765 [02:02<05:31,  1.68it/s]

[209/765]  raw='fail'  →  Fail

 27%|██▋       | 210/765 [02:03<05:26,  1.70it/s]

[210/765]  raw='fail'  →  Fail

 28%|██▊       | 211/765 [02:03<05:08,  1.80it/s]

[211/765]  raw='fail'  →  Fail

 28%|██▊       | 212/765 [02:04<05:03,  1.83it/s]

[212/765]  raw='fail'  →  Fail

 28%|██▊       | 213/765 [02:04<05:10,  1.78it/s]

[213/765]  raw='pass'  →  Pass

 28%|██▊       | 214/765 [02:05<04:57,  1.85it/s]

[214/765]  raw='fail'  →  Fail

 28%|██▊       | 215/765 [02:05<05:04,  1.81it/s]

[215/765]  raw='pass'  →  Pass

 28%|██▊       | 216/765 [02:06<04:59,  1.83it/s]

[216/765]  raw='fail'  →  Fail

 28%|██▊       | 217/765 [02:06<04:46,  1.91it/s]

[217/765]  raw='fail'  →  Fail

 28%|██▊       | 218/765 [02:07<05:46,  1.58it/s]

[218/765]  raw='pass'  →  Pass

 29%|██▊       | 219/765 [02:08<05:51,  1.55it/s]

[219/765]  raw='pass'  →  Pass

 29%|██▉       | 220/765 [02:08<05:24,  1.68it/s]

[220/765]  raw='fail'  →  Fail

 29%|██▉       | 221/765 [02:09<05:04,  1.79it/s]

[221/765]  raw='fail'  →  Fail

 29%|██▉       | 222/765 [02:09<05:08,  1.76it/s]

[222/765]  raw='fail'  →  Fail

 29%|██▉       | 223/765 [02:10<05:31,  1.63it/s]

[223/765]  raw='pass'  →  Pass

 29%|██▉       | 224/765 [02:11<05:39,  1.59it/s]

[224/765]  raw='pass'  →  Pass

 29%|██▉       | 225/765 [02:11<05:22,  1.67it/s]

[225/765]  raw='fail'  →  Fail

 30%|██▉       | 226/765 [02:12<05:38,  1.59it/s]

[226/765]  raw='pass'  →  Pass

 30%|██▉       | 227/765 [02:13<05:21,  1.67it/s]

[227/765]  raw='fail'  →  Fail

 30%|██▉       | 228/765 [02:13<05:01,  1.78it/s]

[228/765]  raw='fail'  →  Fail

 30%|██▉       | 229/765 [02:14<04:56,  1.81it/s]

[229/765]  raw='fail'  →  Fail

 30%|███       | 230/765 [02:14<04:53,  1.82it/s]

[230/765]  raw='fail'  →  Fail

 30%|███       | 231/765 [02:15<05:01,  1.77it/s]

[231/765]  raw='fail'  →  Fail

 30%|███       | 232/765 [02:15<05:14,  1.69it/s]

[232/765]  raw='fail'  →  Fail

 30%|███       | 233/765 [02:16<04:55,  1.80it/s]

[233/765]  raw='fail'  →  Fail

 31%|███       | 234/765 [02:16<04:59,  1.77it/s]

[234/765]  raw='fail'  →  Fail

 31%|███       | 235/765 [02:17<05:16,  1.67it/s]

[235/765]  raw='pass'  →  Pass

 31%|███       | 236/765 [02:18<05:08,  1.72it/s]

[236/765]  raw='fail'  →  Fail

 31%|███       | 237/765 [02:18<04:46,  1.85it/s]

[237/765]  raw='fail'  →  Fail

 31%|███       | 238/765 [02:19<04:43,  1.86it/s]

[238/765]  raw='fail'  →  Fail

 31%|███       | 239/765 [02:19<05:00,  1.75it/s]

[239/765]  raw='pass'  →  Pass

 31%|███▏      | 240/765 [02:20<04:53,  1.79it/s]

[240/765]  raw='pass'  →  Pass

 32%|███▏      | 241/765 [02:21<05:15,  1.66it/s]

[241/765]  raw='pass'  →  Pass

 32%|███▏      | 242/765 [02:21<04:56,  1.76it/s]

[242/765]  raw='fail'  →  Fail

 32%|███▏      | 243/765 [02:21<04:44,  1.83it/s]

[243/765]  raw='fail'  →  Fail

 32%|███▏      | 244/765 [02:22<04:31,  1.92it/s]

[244/765]  raw='fail'  →  Fail

 32%|███▏      | 245/765 [02:22<04:32,  1.91it/s]

[245/765]  raw='fail'  →  Fail

 32%|███▏      | 246/765 [02:23<05:34,  1.55it/s]

[246/765]  raw='pass'  →  Pass

 32%|███▏      | 247/765 [02:24<05:32,  1.56it/s]

[247/765]  raw='pass'  →  Pass

 32%|███▏      | 248/765 [02:25<05:04,  1.70it/s]

[248/765]  raw='fail'  →  Fail

 33%|███▎      | 249/765 [02:25<05:03,  1.70it/s]

[249/765]  raw='fail'  →  Fail

 33%|███▎      | 250/765 [02:26<04:41,  1.83it/s]

[250/765]  raw='fail'  →  Fail

 33%|███▎      | 251/765 [02:26<04:38,  1.85it/s]

[251/765]  raw='fail'  →  Fail

 33%|███▎      | 252/765 [02:27<04:42,  1.82it/s]

[252/765]  raw='fail'  →  Fail

 33%|███▎      | 253/765 [02:27<04:47,  1.78it/s]

[253/765]  raw='fail'  →  Fail

 33%|███▎      | 254/765 [02:28<04:33,  1.87it/s]

[254/765]  raw='fail'  →  Fail

 33%|███▎      | 255/765 [02:28<05:08,  1.65it/s]

[255/765]  raw='pass'  →  Pass

 33%|███▎      | 256/765 [02:29<05:02,  1.68it/s]

[256/765]  raw='fail'  →  Fail

 34%|███▎      | 257/765 [02:30<04:53,  1.73it/s]

[257/765]  raw='fail'  →  Fail

 34%|███▎      | 258/765 [02:30<04:45,  1.77it/s]

[258/765]  raw='fail'  →  Fail

 34%|███▍      | 259/765 [02:31<04:34,  1.85it/s]

[259/765]  raw='fail'  →  Fail

 34%|███▍      | 260/765 [02:31<04:48,  1.75it/s]

[260/765]  raw='pass'  →  Pass

 34%|███▍      | 261/765 [02:32<04:33,  1.84it/s]

[261/765]  raw='fail'  →  Fail

 34%|███▍      | 262/765 [02:32<04:56,  1.70it/s]

[262/765]  raw='pass'  →  Pass

 34%|███▍      | 263/765 [02:33<05:04,  1.65it/s]

[263/765]  raw='pass'  →  Pass

 35%|███▍      | 264/765 [02:34<04:46,  1.75it/s]

[264/765]  raw='fail'  →  Fail

 35%|███▍      | 265/765 [02:34<05:06,  1.63it/s]

[265/765]  raw='pass'  →  Pass

 35%|███▍      | 266/765 [02:35<05:00,  1.66it/s]

[266/765]  raw='fail'  →  Fail

 35%|███▍      | 267/765 [02:36<05:27,  1.52it/s]

[267/765]  raw='pass'  →  Pass

 35%|███▌      | 268/765 [02:36<05:17,  1.57it/s]

[268/765]  raw='fail'  →  Fail

 35%|███▌      | 269/765 [02:37<05:07,  1.61it/s]

[269/765]  raw='pass'  →  Pass

 35%|███▌      | 270/765 [02:37<04:44,  1.74it/s]

[270/765]  raw='fail'  →  Fail

 35%|███▌      | 271/765 [02:38<04:31,  1.82it/s]

[271/765]  raw='fail'  →  Fail

 36%|███▌      | 272/765 [02:38<04:45,  1.73it/s]

[272/765]  raw='pass'  →  Pass

 36%|███▌      | 273/765 [02:39<04:31,  1.81it/s]

[273/765]  raw='fail'  →  Fail

 36%|███▌      | 274/765 [02:39<04:36,  1.78it/s]

[274/765]  raw='pass'  →  Pass

 36%|███▌      | 275/765 [02:40<05:09,  1.58it/s]

[275/765]  raw='pass'  →  Pass

 36%|███▌      | 276/765 [02:41<04:46,  1.71it/s]

[276/765]  raw='fail'  →  Fail

 36%|███▌      | 277/765 [02:41<04:46,  1.70it/s]

[277/765]  raw='fail'  →  Fail

 36%|███▋      | 278/765 [02:42<04:31,  1.79it/s]

[278/765]  raw='fail'  →  Fail

 36%|███▋      | 279/765 [02:42<04:37,  1.75it/s]

[279/765]  raw='pass'  →  Pass

 37%|███▋      | 280/765 [02:43<04:23,  1.84it/s]

[280/765]  raw='fail'  →  Fail

 37%|███▋      | 281/765 [02:44<04:54,  1.64it/s]

[281/765]  raw='pass'  →  Pass

 37%|███▋      | 282/765 [02:44<04:36,  1.74it/s]

[282/765]  raw='fail'  →  Fail

 37%|███▋      | 283/765 [02:45<04:48,  1.67it/s]

[283/765]  raw='pass'  →  Pass

 37%|███▋      | 284/765 [02:45<04:44,  1.69it/s]

[284/765]  raw='fail'  →  Fail

 37%|███▋      | 285/765 [02:46<04:29,  1.78it/s]

[285/765]  raw='fail'  →  Fail

 37%|███▋      | 286/765 [02:46<04:33,  1.75it/s]

[286/765]  raw='pass'  →  Pass

 38%|███▊      | 287/765 [02:47<04:25,  1.80it/s]

[287/765]  raw='pass'  →  Pass

 38%|███▊      | 288/765 [02:48<04:22,  1.82it/s]

[288/765]  raw='fail'  →  Fail

 38%|███▊      | 289/765 [02:48<04:12,  1.89it/s]

[289/765]  raw='fail'  →  Fail

 38%|███▊      | 290/765 [02:49<04:17,  1.84it/s]

[290/765]  raw='fail'  →  Fail

 38%|███▊      | 291/765 [02:49<04:15,  1.86it/s]

[291/765]  raw='fail'  →  Fail

 38%|███▊      | 292/765 [02:50<04:08,  1.90it/s]

[292/765]  raw='fail'  →  Fail

 38%|███▊      | 293/765 [02:50<04:27,  1.77it/s]

[293/765]  raw='pass'  →  Pass

 38%|███▊      | 294/765 [02:51<05:03,  1.55it/s]

[294/765]  raw='pass'  →  Pass

 39%|███▊      | 295/765 [02:52<04:39,  1.68it/s]

[295/765]  raw='fail'  →  Fail

 39%|███▊      | 296/765 [02:52<04:43,  1.65it/s]

[296/765]  raw='pass'  →  Pass

 39%|███▉      | 297/765 [02:53<04:35,  1.70it/s]

[297/765]  raw='pass'  →  Pass

 39%|███▉      | 298/765 [02:53<04:37,  1.68it/s]

[298/765]  raw='pass'  →  Pass

 39%|███▉      | 299/765 [02:54<05:05,  1.53it/s]

[299/765]  raw='pass'  →  Pass

 39%|███▉      | 300/765 [02:55<04:41,  1.65it/s]

[300/765]  raw='fail'  →  Fail

 39%|███▉      | 301/765 [02:55<04:22,  1.77it/s]

[301/765]  raw='fail'  →  Fail

 39%|███▉      | 302/765 [02:56<04:26,  1.74it/s]

[302/765]  raw='pass'  →  Pass

 40%|███▉      | 303/765 [02:57<05:09,  1.49it/s]

[303/765]  raw='pass'  →  Pass

 40%|███▉      | 304/765 [02:57<04:49,  1.59it/s]

[304/765]  raw='fail'  →  Fail

 40%|███▉      | 305/765 [02:58<04:34,  1.67it/s]

[305/765]  raw='fail'  →  Fail

 40%|████      | 306/765 [02:58<04:16,  1.79it/s]

[306/765]  raw='fail'  →  Fail

 40%|████      | 307/765 [02:59<04:05,  1.87it/s]

[307/765]  raw='fail'  →  Fail

 40%|████      | 308/765 [02:59<03:58,  1.92it/s]

[308/765]  raw='fail'  →  Fail

 40%|████      | 309/765 [03:00<04:08,  1.84it/s]

[309/765]  raw='fail'  →  Fail

 41%|████      | 310/765 [03:00<04:13,  1.79it/s]

[310/765]  raw='fail'  →  Fail

 41%|████      | 311/765 [03:01<04:11,  1.81it/s]

[311/765]  raw='fail'  →  Fail

 41%|████      | 312/765 [03:01<04:07,  1.83it/s]

[312/765]  raw='fail'  →  Fail

 41%|████      | 313/765 [03:02<04:00,  1.88it/s]

[313/765]  raw='fail'  →  Fail

 41%|████      | 314/765 [03:03<04:21,  1.73it/s]

[314/765]  raw='pass'  →  Pass

 41%|████      | 315/765 [03:03<04:07,  1.82it/s]

[315/765]  raw='fail'  →  Fail

 41%|████▏     | 316/765 [03:04<04:06,  1.82it/s]

[316/765]  raw='fail'  →  Fail

 41%|████▏     | 317/765 [03:04<04:08,  1.80it/s]

[317/765]  raw='pass'  →  Pass

 42%|████▏     | 318/765 [03:05<04:06,  1.82it/s]

[318/765]  raw='fail'  →  Fail

 42%|████▏     | 319/765 [03:05<04:02,  1.84it/s]

[319/765]  raw='fail'  →  Fail

 42%|████▏     | 320/765 [03:06<04:08,  1.79it/s]

[320/765]  raw='pass'  →  Pass

 42%|████▏     | 321/765 [03:06<03:58,  1.86it/s]

[321/765]  raw='fail'  →  Fail

 42%|████▏     | 322/765 [03:07<03:58,  1.86it/s]

[322/765]  raw='fail'  →  Fail

 42%|████▏     | 323/765 [03:07<04:05,  1.80it/s]

[323/765]  raw='pass'  →  Pass

 42%|████▏     | 324/765 [03:08<04:01,  1.82it/s]

[324/765]  raw='fail'  →  Fail

 42%|████▏     | 325/765 [03:09<04:00,  1.83it/s]

[325/765]  raw='fail'  →  Fail

 43%|████▎     | 326/765 [03:09<04:28,  1.64it/s]

[326/765]  raw='pass'  →  Pass

 43%|████▎     | 327/765 [03:10<04:09,  1.75it/s]

[327/765]  raw='fail'  →  Fail

 43%|████▎     | 328/765 [03:10<04:13,  1.73it/s]

[328/765]  raw='fail'  →  Fail

 43%|████▎     | 329/765 [03:11<03:57,  1.84it/s]

[329/765]  raw='fail'  →  Fail

 43%|████▎     | 330/765 [03:11<04:05,  1.77it/s]

[330/765]  raw='pass'  →  Pass

 43%|████▎     | 331/765 [03:12<04:00,  1.80it/s]

[331/765]  raw='fail'  →  Fail

 43%|████▎     | 332/765 [03:12<03:57,  1.83it/s]

[332/765]  raw='fail'  →  Fail

 44%|████▎     | 333/765 [03:13<03:56,  1.83it/s]

[333/765]  raw='fail'  →  Fail

 44%|████▎     | 334/765 [03:14<04:08,  1.73it/s]

[334/765]  raw='pass'  →  Pass

 44%|████▍     | 335/765 [03:14<04:01,  1.78it/s]

[335/765]  raw='fail'  →  Fail

 44%|████▍     | 336/765 [03:15<03:49,  1.87it/s]

[336/765]  raw='fail'  →  Fail

 44%|████▍     | 337/765 [03:15<03:56,  1.81it/s]

[337/765]  raw='pass'  →  Pass

 44%|████▍     | 338/765 [03:16<04:00,  1.78it/s]

[338/765]  raw='fail'  →  Fail

 44%|████▍     | 339/765 [03:17<04:24,  1.61it/s]

[339/765]  raw='pass'  →  Pass

 44%|████▍     | 340/765 [03:17<04:22,  1.62it/s]

[340/765]  raw='pass'  →  Pass

 45%|████▍     | 341/765 [03:18<04:16,  1.66it/s]

[341/765]  raw='fail'  →  Fail

 45%|████▍     | 342/765 [03:18<04:21,  1.62it/s]

[342/765]  raw='pass'  →  Pass

 45%|████▍     | 343/765 [03:19<04:31,  1.56it/s]

[343/765]  raw='pass'  →  Pass

 45%|████▍     | 344/765 [03:20<04:22,  1.60it/s]

[344/765]  raw='pass'  →  Pass

 45%|████▌     | 345/765 [03:20<04:12,  1.67it/s]

[345/765]  raw='pass'  →  Pass

 45%|████▌     | 346/765 [03:21<04:31,  1.54it/s]

[346/765]  raw='pass'  →  Pass

 45%|████▌     | 347/765 [03:22<04:21,  1.60it/s]

[347/765]  raw='fail'  →  Fail

 45%|████▌     | 348/765 [03:22<04:16,  1.63it/s]

[348/765]  raw='pass'  →  Pass

 46%|████▌     | 349/765 [03:23<03:58,  1.74it/s]

[349/765]  raw='fail'  →  Fail

 46%|████▌     | 350/765 [03:23<03:45,  1.84it/s]

[350/765]  raw='fail'  →  Fail

 46%|████▌     | 351/765 [03:24<03:49,  1.80it/s]

[351/765]  raw='fail'  →  Fail

 46%|████▌     | 352/765 [03:24<03:52,  1.77it/s]

[352/765]  raw='pass'  →  Pass

 46%|████▌     | 353/765 [03:25<03:49,  1.79it/s]

[353/765]  raw='fail'  →  Fail

 46%|████▋     | 354/765 [03:25<03:38,  1.88it/s]

[354/765]  raw='fail'  →  Fail

 46%|████▋     | 355/765 [03:26<03:44,  1.82it/s]

[355/765]  raw='pass'  →  Pass

 47%|████▋     | 356/765 [03:27<03:54,  1.74it/s]

[356/765]  raw='pass'  →  Pass

 47%|████▋     | 357/765 [03:27<03:48,  1.78it/s]

[357/765]  raw='fail'  →  Fail

 47%|████▋     | 358/765 [03:28<03:50,  1.77it/s]

[358/765]  raw='pass'  →  Pass

 47%|████▋     | 359/765 [03:28<04:02,  1.67it/s]

[359/765]  raw='pass'  →  Pass

 47%|████▋     | 360/765 [03:29<03:53,  1.73it/s]

[360/765]  raw='fail'  →  Fail

 47%|████▋     | 361/765 [03:29<03:42,  1.82it/s]

[361/765]  raw='fail'  →  Fail

 47%|████▋     | 362/765 [03:30<04:02,  1.66it/s]

[362/765]  raw='pass'  →  Pass

 47%|████▋     | 363/765 [03:31<03:47,  1.77it/s]

[363/765]  raw='fail'  →  Fail

 48%|████▊     | 364/765 [03:31<03:51,  1.74it/s]

[364/765]  raw='pass'  →  Pass

 48%|████▊     | 365/765 [03:32<04:11,  1.59it/s]

[365/765]  raw='pass'  →  Pass

 48%|████▊     | 366/765 [03:32<03:51,  1.72it/s]

[366/765]  raw='fail'  →  Fail

 48%|████▊     | 367/765 [03:33<03:54,  1.70it/s]

[367/765]  raw='pass'  →  Pass

 48%|████▊     | 368/765 [03:33<03:41,  1.79it/s]

[368/765]  raw='fail'  →  Fail

 48%|████▊     | 369/765 [03:34<03:51,  1.71it/s]

[369/765]  raw='pass'  →  Pass

 48%|████▊     | 370/765 [03:35<04:04,  1.61it/s]

[370/765]  raw='pass'  →  Pass

 48%|████▊     | 371/765 [03:35<03:59,  1.64it/s]

[371/765]  raw='pass'  →  Pass

 49%|████▊     | 372/765 [03:36<03:44,  1.75it/s]

[372/765]  raw='fail'  →  Fail

 49%|████▉     | 373/765 [03:37<04:03,  1.61it/s]

[373/765]  raw='pass'  →  Pass

 49%|████▉     | 374/765 [03:37<03:57,  1.64it/s]

[374/765]  raw='pass'  →  Pass

 49%|████▉     | 375/765 [03:38<03:55,  1.65it/s]

[375/765]  raw='pass'  →  Pass

 49%|████▉     | 376/765 [03:38<03:54,  1.66it/s]

[376/765]  raw='fail'  →  Fail

 49%|████▉     | 377/765 [03:39<03:53,  1.66it/s]

[377/765]  raw='fail'  →  Fail

 49%|████▉     | 378/765 [03:40<04:10,  1.54it/s]

[378/765]  raw='pass'  →  Pass

 50%|████▉     | 379/765 [03:40<03:51,  1.66it/s]

[379/765]  raw='fail'  →  Fail

 50%|████▉     | 380/765 [03:41<03:38,  1.77it/s]

[380/765]  raw='fail'  →  Fail

 50%|████▉     | 381/765 [03:41<03:54,  1.64it/s]

[381/765]  raw='pass'  →  Pass

 50%|████▉     | 382/765 [03:42<03:44,  1.71it/s]

[382/765]  raw='fail'  →  Fail

 50%|█████     | 383/765 [03:42<03:30,  1.82it/s]

[383/765]  raw='fail'  →  Fail

 50%|█████     | 384/765 [03:43<03:32,  1.79it/s]

[384/765]  raw='fail'  →  Fail

 50%|█████     | 385/765 [03:43<03:23,  1.87it/s]

[385/765]  raw='fail'  →  Fail

 50%|█████     | 386/765 [03:44<03:35,  1.76it/s]

[386/765]  raw='pass'  →  Pass

 51%|█████     | 387/765 [03:45<03:25,  1.84it/s]

[387/765]  raw='fail'  →  Fail

 51%|█████     | 388/765 [03:45<03:30,  1.79it/s]

[388/765]  raw='fail'  →  Fail

 51%|█████     | 389/765 [03:46<03:36,  1.74it/s]

[389/765]  raw='pass'  →  Pass

 51%|█████     | 390/765 [03:46<03:37,  1.72it/s]

[390/765]  raw='pass'  →  Pass

 51%|█████     | 391/765 [03:47<03:27,  1.80it/s]

[391/765]  raw='fail'  →  Fail

 51%|█████     | 392/765 [03:47<03:18,  1.88it/s]

[392/765]  raw='fail'  →  Fail

 51%|█████▏    | 393/765 [03:48<03:19,  1.87it/s]

[393/765]  raw='fail'  →  Fail

 52%|█████▏    | 394/765 [03:49<04:05,  1.51it/s]

[394/765]  raw='pass'  →  Pass

 52%|█████▏    | 395/765 [03:49<03:58,  1.55it/s]

[395/765]  raw='fail'  →  Fail

 52%|█████▏    | 396/765 [03:50<03:47,  1.62it/s]

[396/765]  raw='fail'  →  Fail

 52%|█████▏    | 397/765 [03:51<03:49,  1.60it/s]

[397/765]  raw='pass'  →  Pass

 52%|█████▏    | 398/765 [03:51<03:43,  1.64it/s]

[398/765]  raw='fail'  →  Fail

 52%|█████▏    | 399/765 [03:52<03:36,  1.69it/s]

[399/765]  raw='fail'  →  Fail

 52%|█████▏    | 400/765 [03:52<03:37,  1.68it/s]

[400/765]  raw='pass'  →  Pass

 52%|█████▏    | 401/765 [03:53<03:29,  1.74it/s]

[401/765]  raw='fail'  →  Fail

 53%|█████▎    | 402/765 [03:54<03:41,  1.64it/s]

[402/765]  raw='fail'  →  Fail

 53%|█████▎    | 403/765 [03:54<03:25,  1.76it/s]

[403/765]  raw='fail'  →  Fail

 53%|█████▎    | 404/765 [03:55<03:17,  1.83it/s]

[404/765]  raw='fail'  →  Fail

 53%|█████▎    | 405/765 [03:55<03:09,  1.89it/s]

[405/765]  raw='fail'  →  Fail

 53%|█████▎    | 406/765 [03:56<03:16,  1.83it/s]

[406/765]  raw='pass'  →  Pass

 53%|█████▎    | 407/765 [03:56<03:39,  1.63it/s]

[407/765]  raw='pass'  →  Pass

 53%|█████▎    | 408/765 [03:57<03:25,  1.74it/s]

[408/765]  raw='fail'  →  Fail

 53%|█████▎    | 409/765 [03:57<03:19,  1.79it/s]

[409/765]  raw='fail'  →  Fail

 54%|█████▎    | 410/765 [03:58<03:09,  1.88it/s]

[410/765]  raw='fail'  →  Fail

 54%|█████▎    | 411/765 [03:58<03:01,  1.95it/s]

[411/765]  raw='fail'  →  Fail

 54%|█████▍    | 412/765 [03:59<03:23,  1.73it/s]

[412/765]  raw='pass'  →  Pass

 54%|█████▍    | 413/765 [04:00<03:31,  1.67it/s]

[413/765]  raw='fail'  →  Fail

 54%|█████▍    | 414/765 [04:00<03:40,  1.59it/s]

[414/765]  raw='fail'  →  Fail

 54%|█████▍    | 415/765 [04:01<03:23,  1.72it/s]

[415/765]  raw='fail'  →  Fail

 54%|█████▍    | 416/765 [04:01<03:12,  1.81it/s]

[416/765]  raw='fail'  →  Fail

 55%|█████▍    | 417/765 [04:02<03:04,  1.89it/s]

[417/765]  raw='fail'  →  Fail

 55%|█████▍    | 418/765 [04:02<03:04,  1.89it/s]

[418/765]  raw='fail'  →  Fail

 55%|█████▍    | 419/765 [04:03<03:10,  1.81it/s]

[419/765]  raw='fail'  →  Fail

 55%|█████▍    | 420/765 [04:04<03:14,  1.78it/s]

[420/765]  raw='fail'  →  Fail

 55%|█████▌    | 421/765 [04:04<03:05,  1.86it/s]

[421/765]  raw='fail'  →  Fail

 55%|█████▌    | 422/765 [04:05<03:30,  1.63it/s]

[422/765]  raw='pass'  →  Pass

 55%|█████▌    | 423/765 [04:06<03:35,  1.59it/s]

[423/765]  raw='pass'  →  Pass

 55%|█████▌    | 424/765 [04:06<03:19,  1.71it/s]

[424/765]  raw='fail'  →  Fail

 56%|█████▌    | 425/765 [04:07<03:18,  1.72it/s]

[425/765]  raw='fail'  →  Fail

 56%|█████▌    | 426/765 [04:07<03:26,  1.64it/s]

[426/765]  raw='pass'  →  Pass

 56%|█████▌    | 427/765 [04:08<04:00,  1.40it/s]

[427/765]  raw='pass'  →  Pass

 56%|█████▌    | 428/765 [04:09<03:35,  1.56it/s]

[428/765]  raw='fail'  →  Fail

 56%|█████▌    | 429/765 [04:09<03:30,  1.60it/s]

[429/765]  raw='fail'  →  Fail

 56%|█████▌    | 430/765 [04:10<03:27,  1.62it/s]

[430/765]  raw='pass'  →  Pass

 56%|█████▋    | 431/765 [04:11<03:25,  1.63it/s]

[431/765]  raw='pass'  →  Pass

 56%|█████▋    | 432/765 [04:11<03:21,  1.65it/s]

[432/765]  raw='fail'  →  Fail

 57%|█████▋    | 433/765 [04:12<03:18,  1.67it/s]

[433/765]  raw='pass'  →  Pass

 57%|█████▋    | 434/765 [04:12<03:05,  1.78it/s]

[434/765]  raw='fail'  →  Fail

 57%|█████▋    | 435/765 [04:13<02:56,  1.87it/s]

[435/765]  raw='fail'  →  Fail

 57%|█████▋    | 436/765 [04:13<02:55,  1.87it/s]

[436/765]  raw='fail'  →  Fail

 57%|█████▋    | 437/765 [04:14<02:54,  1.88it/s]

[437/765]  raw='fail'  →  Fail

 57%|█████▋    | 438/765 [04:14<02:49,  1.93it/s]

[438/765]  raw='fail'  →  Fail

 57%|█████▋    | 439/765 [04:15<02:54,  1.87it/s]

[439/765]  raw='pass'  →  Pass

 58%|█████▊    | 440/765 [04:15<02:53,  1.87it/s]

[440/765]  raw='fail'  →  Fail

 58%|█████▊    | 441/765 [04:16<02:58,  1.82it/s]

[441/765]  raw='pass'  →  Pass

 58%|█████▊    | 442/765 [04:16<02:55,  1.84it/s]

[442/765]  raw='fail'  →  Fail

 58%|█████▊    | 443/765 [04:17<02:49,  1.90it/s]

[443/765]  raw='fail'  →  Fail

 58%|█████▊    | 444/765 [04:17<02:43,  1.96it/s]

[444/765]  raw='fail'  →  Fail

 58%|█████▊    | 445/765 [04:18<02:55,  1.83it/s]

[445/765]  raw='fail'  →  Fail

 58%|█████▊    | 446/765 [04:19<02:52,  1.85it/s]

[446/765]  raw='fail'  →  Fail

 58%|█████▊    | 447/765 [04:19<02:57,  1.79it/s]

[447/765]  raw='fail'  →  Fail

 59%|█████▊    | 448/765 [04:20<02:54,  1.82it/s]

[448/765]  raw='fail'  →  Fail

 59%|█████▊    | 449/765 [04:20<02:51,  1.84it/s]

[449/765]  raw='fail'  →  Fail

 59%|█████▉    | 450/765 [04:21<02:56,  1.79it/s]

[450/765]  raw='pass'  →  Pass

 59%|█████▉    | 451/765 [04:21<02:48,  1.86it/s]

[451/765]  raw='fail'  →  Fail

 59%|█████▉    | 452/765 [04:22<02:42,  1.93it/s]

[452/765]  raw='fail'  →  Fail

 59%|█████▉    | 453/765 [04:22<02:47,  1.86it/s]

[453/765]  raw='fail'  →  Fail

 59%|█████▉    | 454/765 [04:23<02:46,  1.87it/s]

[454/765]  raw='fail'  →  Fail

 59%|█████▉    | 455/765 [04:23<02:57,  1.75it/s]

[455/765]  raw='pass'  →  Pass

 60%|█████▉    | 456/765 [04:24<02:53,  1.78it/s]

[456/765]  raw='fail'  →  Fail

 60%|█████▉    | 457/765 [04:25<02:58,  1.72it/s]

[457/765]  raw='fail'  →  Fail

 60%|█████▉    | 458/765 [04:25<02:53,  1.77it/s]

[458/765]  raw='fail'  →  Fail

 60%|██████    | 459/765 [04:26<02:49,  1.81it/s]

[459/765]  raw='fail'  →  Fail

 60%|██████    | 460/765 [04:26<02:42,  1.88it/s]

[460/765]  raw='fail'  →  Fail

 60%|██████    | 461/765 [04:27<02:52,  1.76it/s]

[461/765]  raw='pass'  →  Pass

 60%|██████    | 462/765 [04:28<03:03,  1.65it/s]

[462/765]  raw='pass'  →  Pass

 61%|██████    | 463/765 [04:28<02:51,  1.76it/s]

[463/765]  raw='fail'  →  Fail

 61%|██████    | 464/765 [04:29<02:48,  1.79it/s]

[464/765]  raw='fail'  →  Fail

 61%|██████    | 465/765 [04:29<02:51,  1.75it/s]

[465/765]  raw='pass'  →  Pass

 61%|██████    | 466/765 [04:30<02:43,  1.83it/s]

[466/765]  raw='fail'  →  Fail

 61%|██████    | 467/765 [04:30<02:46,  1.79it/s]

[467/765]  raw='pass'  →  Pass

 61%|██████    | 468/765 [04:31<02:48,  1.76it/s]

[468/765]  raw='fail'  →  Fail

 61%|██████▏   | 469/765 [04:31<02:45,  1.79it/s]

[469/765]  raw='fail'  →  Fail

 61%|██████▏   | 470/765 [04:32<02:59,  1.65it/s]

[470/765]  raw='pass'  →  Pass

 62%|██████▏   | 471/765 [04:33<02:47,  1.76it/s]

[471/765]  raw='fail'  →  Fail

 62%|██████▏   | 472/765 [04:33<02:38,  1.85it/s]

[472/765]  raw='fail'  →  Fail

 62%|██████▏   | 473/765 [04:34<02:36,  1.86it/s]

[473/765]  raw='fail'  →  Fail

 62%|██████▏   | 474/765 [04:34<02:35,  1.87it/s]

[474/765]  raw='fail'  →  Fail

 62%|██████▏   | 475/765 [04:35<02:36,  1.85it/s]

[475/765]  raw='fail'  →  Fail

 62%|██████▏   | 476/765 [04:35<02:34,  1.87it/s]

[476/765]  raw='fail'  →  Fail

 62%|██████▏   | 477/765 [04:36<02:43,  1.76it/s]

[477/765]  raw='fail'  →  Fail

 62%|██████▏   | 478/765 [04:36<02:32,  1.89it/s]

[478/765]  raw='fail'  →  Fail

 63%|██████▎   | 479/765 [04:37<02:35,  1.83it/s]

[479/765]  raw='fail'  →  Fail

 63%|██████▎   | 480/765 [04:37<02:39,  1.79it/s]

[480/765]  raw='fail'  →  Fail

 63%|██████▎   | 481/765 [04:38<02:43,  1.74it/s]

[481/765]  raw='pass'  →  Pass

 63%|██████▎   | 482/765 [04:39<02:39,  1.78it/s]

[482/765]  raw='fail'  →  Fail

 63%|██████▎   | 483/765 [04:39<02:32,  1.85it/s]

[483/765]  raw='fail'  →  Fail

 63%|██████▎   | 484/765 [04:40<02:32,  1.85it/s]

[484/765]  raw='fail'  →  Fail

 63%|██████▎   | 485/765 [04:40<02:31,  1.84it/s]

[485/765]  raw='pass'  →  Pass

 64%|██████▎   | 486/765 [04:41<02:43,  1.70it/s]

[486/765]  raw='pass'  →  Pass

 64%|██████▎   | 487/765 [04:41<02:34,  1.80it/s]

[487/765]  raw='fail'  →  Fail

 64%|██████▍   | 488/765 [04:42<02:40,  1.72it/s]

[488/765]  raw='pass'  →  Pass

 64%|██████▍   | 489/765 [04:42<02:35,  1.77it/s]

[489/765]  raw='fail'  →  Fail

 64%|██████▍   | 490/765 [04:43<02:41,  1.70it/s]

[490/765]  raw='pass'  →  Pass

 64%|██████▍   | 491/765 [04:44<02:41,  1.70it/s]

[491/765]  raw='pass'  →  Pass

 64%|██████▍   | 492/765 [04:44<02:37,  1.74it/s]

[492/765]  raw='fail'  →  Fail

 64%|██████▍   | 493/765 [04:45<02:34,  1.76it/s]

[493/765]  raw='fail'  →  Fail

 65%|██████▍   | 494/765 [04:45<02:37,  1.72it/s]

[494/765]  raw='pass'  →  Pass

 65%|██████▍   | 495/765 [04:46<02:28,  1.81it/s]

[495/765]  raw='fail'  →  Fail

 65%|██████▍   | 496/765 [04:46<02:28,  1.81it/s]

[496/765]  raw='fail'  →  Fail

 65%|██████▍   | 497/765 [04:47<02:30,  1.78it/s]

[497/765]  raw='pass'  →  Pass

 65%|██████▌   | 498/765 [04:48<02:30,  1.77it/s]

[498/765]  raw='fail'  →  Fail

 65%|██████▌   | 499/765 [04:48<02:33,  1.74it/s]

[499/765]  raw='pass'  →  Pass

 65%|██████▌   | 500/765 [04:49<02:26,  1.81it/s]

[500/765]  raw='fail'  →  Fail

 65%|██████▌   | 501/765 [04:49<02:24,  1.83it/s]

[501/765]  raw='fail'  →  Fail

 66%|██████▌   | 502/765 [04:50<02:27,  1.79it/s]

[502/765]  raw='fail'  →  Fail

 66%|██████▌   | 503/765 [04:50<02:29,  1.75it/s]

[503/765]  raw='fail'  →  Fail

 66%|██████▌   | 504/765 [04:51<02:25,  1.79it/s]

[504/765]  raw='fail'  →  Fail

 66%|██████▌   | 505/765 [04:51<02:19,  1.86it/s]

[505/765]  raw='fail'  →  Fail

 66%|██████▌   | 506/765 [04:52<02:14,  1.92it/s]

[506/765]  raw='fail'  →  Fail

 66%|██████▋   | 507/765 [04:52<02:14,  1.92it/s]

[507/765]  raw='fail'  →  Fail

 66%|██████▋   | 508/765 [04:53<02:23,  1.79it/s]

[508/765]  raw='pass'  →  Pass

 67%|██████▋   | 509/765 [04:54<02:30,  1.70it/s]

[509/765]  raw='pass'  →  Pass

 67%|██████▋   | 510/765 [04:54<02:22,  1.79it/s]

[510/765]  raw='fail'  →  Fail

 67%|██████▋   | 511/765 [04:55<02:35,  1.64it/s]

[511/765]  raw='pass'  →  Pass

 67%|██████▋   | 512/765 [04:56<02:33,  1.65it/s]

[512/765]  raw='pass'  →  Pass

 67%|██████▋   | 513/765 [04:56<02:30,  1.67it/s]

[513/765]  raw='fail'  →  Fail

 67%|██████▋   | 514/765 [04:57<02:25,  1.73it/s]

[514/765]  raw='fail'  →  Fail

 67%|██████▋   | 515/765 [04:57<02:25,  1.72it/s]

[515/765]  raw='fail'  →  Fail

 67%|██████▋   | 516/765 [04:58<02:37,  1.58it/s]

[516/765]  raw='pass'  →  Pass

 68%|██████▊   | 517/765 [04:59<02:24,  1.71it/s]

[517/765]  raw='fail'  →  Fail

 68%|██████▊   | 518/765 [04:59<02:27,  1.67it/s]

[518/765]  raw='pass'  →  Pass

 68%|██████▊   | 519/765 [05:00<02:22,  1.73it/s]

[519/765]  raw='fail'  →  Fail

 68%|██████▊   | 520/765 [05:00<02:23,  1.71it/s]

[520/765]  raw='pass'  →  Pass

 68%|██████▊   | 521/765 [05:01<02:28,  1.64it/s]

[521/765]  raw='fail'  →  Fail

 68%|██████▊   | 522/765 [05:01<02:18,  1.76it/s]

[522/765]  raw='fail'  →  Fail

 68%|██████▊   | 523/765 [05:02<02:14,  1.80it/s]

[523/765]  raw='fail'  →  Fail

 68%|██████▊   | 524/765 [05:02<02:12,  1.82it/s]

[524/765]  raw='fail'  →  Fail

 69%|██████▊   | 525/765 [05:03<02:27,  1.62it/s]

[525/765]  raw='pass'  →  Pass

 69%|██████▉   | 526/765 [05:04<02:20,  1.70it/s]

[526/765]  raw='fail'  →  Fail

 69%|██████▉   | 527/765 [05:04<02:11,  1.81it/s]

[527/765]  raw='fail'  →  Fail

 69%|██████▉   | 528/765 [05:05<02:15,  1.75it/s]

[528/765]  raw='pass'  →  Pass

 69%|██████▉   | 529/765 [05:05<02:08,  1.84it/s]

[529/765]  raw='fail'  →  Fail

 69%|██████▉   | 530/765 [05:06<02:06,  1.86it/s]

[530/765]  raw='fail'  →  Fail

 69%|██████▉   | 531/765 [05:06<02:01,  1.93it/s]

[531/765]  raw='fail'  →  Fail

 70%|██████▉   | 532/765 [05:07<01:58,  1.96it/s]

[532/765]  raw='fail'  →  Fail

 70%|██████▉   | 533/765 [05:07<02:00,  1.92it/s]

[533/765]  raw='pass'  →  Pass

 70%|██████▉   | 534/765 [05:08<02:08,  1.79it/s]

[534/765]  raw='pass'  →  Pass

 70%|██████▉   | 535/765 [05:09<02:11,  1.75it/s]

[535/765]  raw='pass'  →  Pass

 70%|███████   | 536/765 [05:09<02:11,  1.75it/s]

[536/765]  raw='fail'  →  Fail

 70%|███████   | 537/765 [05:10<02:07,  1.78it/s]

[537/765]  raw='fail'  →  Fail

 70%|███████   | 538/765 [05:10<02:02,  1.85it/s]

[538/765]  raw='fail'  →  Fail

 70%|███████   | 539/765 [05:11<02:10,  1.73it/s]

[539/765]  raw='fail'  →  Fail

 71%|███████   | 540/765 [05:11<02:11,  1.71it/s]

[540/765]  raw='pass'  →  Pass

 71%|███████   | 541/765 [05:12<02:10,  1.71it/s]

[541/765]  raw='pass'  →  Pass

 71%|███████   | 542/765 [05:13<02:13,  1.67it/s]

[542/765]  raw='fail'  →  Fail

 71%|███████   | 543/765 [05:13<02:19,  1.59it/s]

[543/765]  raw='pass'  →  Pass

 71%|███████   | 544/765 [05:14<02:16,  1.62it/s]

[544/765]  raw='fail'  →  Fail

 71%|███████   | 545/765 [05:15<02:13,  1.65it/s]

[545/765]  raw='fail'  →  Fail

 71%|███████▏  | 546/765 [05:15<02:08,  1.70it/s]

[546/765]  raw='fail'  →  Fail

 72%|███████▏  | 547/765 [05:16<02:04,  1.75it/s]

[547/765]  raw='fail'  →  Fail

 72%|███████▏  | 548/765 [05:16<02:17,  1.58it/s]

[548/765]  raw='pass'  →  Pass

 72%|███████▏  | 549/765 [05:17<02:11,  1.65it/s]

[549/765]  raw='pass'  →  Pass

 72%|███████▏  | 550/765 [05:18<02:08,  1.67it/s]

[550/765]  raw='fail'  →  Fail

 72%|███████▏  | 551/765 [05:18<02:03,  1.73it/s]

[551/765]  raw='fail'  →  Fail

 72%|███████▏  | 552/765 [05:19<01:57,  1.81it/s]

[552/765]  raw='fail'  →  Fail

 72%|███████▏  | 553/765 [05:19<01:59,  1.77it/s]

[553/765]  raw='pass'  →  Pass

 72%|███████▏  | 554/765 [05:20<02:01,  1.73it/s]

[554/765]  raw='fail'  →  Fail

 73%|███████▎  | 555/765 [05:20<02:01,  1.72it/s]

[555/765]  raw='fail'  →  Fail

 73%|███████▎  | 556/765 [05:21<02:06,  1.65it/s]

[556/765]  raw='pass'  →  Pass

 73%|███████▎  | 557/765 [05:22<02:09,  1.61it/s]

[557/765]  raw='pass'  →  Pass

 73%|███████▎  | 558/765 [05:22<02:03,  1.68it/s]

[558/765]  raw='fail'  →  Fail

 73%|███████▎  | 559/765 [05:23<02:05,  1.64it/s]

[559/765]  raw='pass'  →  Pass

 73%|███████▎  | 560/765 [05:23<02:03,  1.66it/s]

[560/765]  raw='pass'  →  Pass

 73%|███████▎  | 561/765 [05:24<02:09,  1.57it/s]

[561/765]  raw='pass'  →  Pass

 73%|███████▎  | 562/765 [05:25<02:02,  1.65it/s]

[562/765]  raw='fail'  →  Fail

 74%|███████▎  | 563/765 [05:25<02:00,  1.68it/s]

[563/765]  raw='fail'  →  Fail

 74%|███████▎  | 564/765 [05:26<01:50,  1.82it/s]

[564/765]  raw='fail'  →  Fail

 74%|███████▍  | 565/765 [05:26<01:56,  1.71it/s]

[565/765]  raw='pass'  →  Pass

 74%|███████▍  | 566/765 [05:27<01:57,  1.69it/s]

[566/765]  raw='fail'  →  Fail

 74%|███████▍  | 567/765 [05:28<01:57,  1.69it/s]

[567/765]  raw='pass'  →  Pass

 74%|███████▍  | 568/765 [05:28<02:03,  1.59it/s]

[568/765]  raw='pass'  →  Pass

 74%|███████▍  | 569/765 [05:29<01:54,  1.71it/s]

[569/765]  raw='fail'  →  Fail

 75%|███████▍  | 570/765 [05:29<01:51,  1.76it/s]

[570/765]  raw='fail'  →  Fail

 75%|███████▍  | 571/765 [05:30<01:47,  1.80it/s]

[571/765]  raw='fail'  →  Fail

 75%|███████▍  | 572/765 [05:30<01:49,  1.77it/s]

[572/765]  raw='pass'  →  Pass

 75%|███████▍  | 573/765 [05:31<01:49,  1.75it/s]

[573/765]  raw='pass'  →  Pass

 75%|███████▌  | 574/765 [05:32<01:54,  1.67it/s]

[574/765]  raw='pass'  →  Pass

 75%|███████▌  | 575/765 [05:32<01:50,  1.71it/s]

[575/765]  raw='pass'  →  Pass

 75%|███████▌  | 576/765 [05:33<01:53,  1.66it/s]

[576/765]  raw='pass'  →  Pass

 75%|███████▌  | 577/765 [05:33<01:46,  1.77it/s]

[577/765]  raw='fail'  →  Fail

 76%|███████▌  | 578/765 [05:34<01:41,  1.85it/s]

[578/765]  raw='fail'  →  Fail

 76%|███████▌  | 579/765 [05:34<01:43,  1.80it/s]

[579/765]  raw='fail'  →  Fail

 76%|███████▌  | 580/765 [05:35<01:44,  1.77it/s]

[580/765]  raw='pass'  →  Pass

 76%|███████▌  | 581/765 [05:36<01:41,  1.81it/s]

[581/765]  raw='fail'  →  Fail

 76%|███████▌  | 582/765 [05:36<01:42,  1.79it/s]

[582/765]  raw='fail'  →  Fail

 76%|███████▌  | 583/765 [05:37<01:37,  1.87it/s]

[583/765]  raw='fail'  →  Fail

 76%|███████▋  | 584/765 [05:37<01:44,  1.74it/s]

[584/765]  raw='pass'  →  Pass

 76%|███████▋  | 585/765 [05:38<01:49,  1.64it/s]

[585/765]  raw='pass'  →  Pass

 77%|███████▋  | 586/765 [05:38<01:46,  1.69it/s]

[586/765]  raw='pass'  →  Pass

 77%|███████▋  | 587/765 [05:39<01:42,  1.74it/s]

[587/765]  raw='fail'  →  Fail

 77%|███████▋  | 588/765 [05:40<01:39,  1.78it/s]

[588/765]  raw='fail'  →  Fail

 77%|███████▋  | 589/765 [05:40<01:39,  1.77it/s]

[589/765]  raw='fail'  →  Fail

 77%|███████▋  | 590/765 [05:41<01:34,  1.85it/s]

[590/765]  raw='fail'  →  Fail

 77%|███████▋  | 591/765 [05:41<01:30,  1.92it/s]

[591/765]  raw='fail'  →  Fail

 77%|███████▋  | 592/765 [05:42<01:28,  1.96it/s]

[592/765]  raw='fail'  →  Fail

 78%|███████▊  | 593/765 [05:42<01:25,  2.00it/s]

[593/765]  raw='fail'  →  Fail

 78%|███████▊  | 594/765 [05:43<01:26,  1.97it/s]

[594/765]  raw='fail'  →  Fail

 78%|███████▊  | 595/765 [05:43<01:33,  1.81it/s]

[595/765]  raw='pass'  →  Pass

 78%|███████▊  | 596/765 [05:44<01:51,  1.52it/s]

[596/765]  raw='fail'  →  Fail

 78%|███████▊  | 597/765 [05:45<01:50,  1.52it/s]

[597/765]  raw='pass'  →  Pass

 78%|███████▊  | 598/765 [05:45<01:43,  1.61it/s]

[598/765]  raw='pass'  →  Pass

 78%|███████▊  | 599/765 [05:46<01:43,  1.60it/s]

[599/765]  raw='pass'  →  Pass

 78%|███████▊  | 600/765 [05:46<01:35,  1.73it/s]

[600/765]  raw='fail'  →  Fail

 79%|███████▊  | 601/765 [05:47<01:32,  1.77it/s]

[601/765]  raw='fail'  →  Fail

 79%|███████▊  | 602/765 [05:48<01:37,  1.68it/s]

[602/765]  raw='pass'  →  Pass

 79%|███████▉  | 603/765 [05:48<01:41,  1.60it/s]

[603/765]  raw='pass'  →  Pass

 79%|███████▉  | 604/765 [05:49<01:38,  1.64it/s]

[604/765]  raw='pass'  →  Pass

 79%|███████▉  | 605/765 [05:50<01:39,  1.61it/s]

[605/765]  raw='pass'  →  Pass

 79%|███████▉  | 606/765 [05:50<01:31,  1.74it/s]

[606/765]  raw='fail'  →  Fail

 79%|███████▉  | 607/765 [05:51<01:30,  1.74it/s]

[607/765]  raw='fail'  →  Fail

 79%|███████▉  | 608/765 [05:51<01:37,  1.61it/s]

[608/765]  raw='pass'  →  Pass

 80%|███████▉  | 609/765 [05:52<01:33,  1.67it/s]

[609/765]  raw='pass'  →  Pass

 80%|███████▉  | 610/765 [05:52<01:32,  1.68it/s]

[610/765]  raw='pass'  →  Pass

 80%|███████▉  | 611/765 [05:53<01:34,  1.63it/s]

[611/765]  raw='pass'  →  Pass

 80%|████████  | 612/765 [05:54<01:31,  1.68it/s]

[612/765]  raw='fail'  →  Fail

 80%|████████  | 613/765 [05:54<01:30,  1.67it/s]

[613/765]  raw='pass'  →  Pass

 80%|████████  | 614/765 [05:55<01:27,  1.72it/s]

[614/765]  raw='fail'  →  Fail

 80%|████████  | 615/765 [05:55<01:21,  1.83it/s]

[615/765]  raw='fail'  →  Fail

 81%|████████  | 616/765 [05:56<01:21,  1.83it/s]

[616/765]  raw='fail'  →  Fail

 81%|████████  | 617/765 [05:56<01:18,  1.89it/s]

[617/765]  raw='fail'  →  Fail

 81%|████████  | 618/765 [05:57<01:17,  1.89it/s]

[618/765]  raw='pass'  →  Pass

 81%|████████  | 619/765 [05:57<01:14,  1.96it/s]

[619/765]  raw='fail'  →  Fail

 81%|████████  | 620/765 [05:58<01:17,  1.86it/s]

[620/765]  raw='pass'  →  Pass

 81%|████████  | 621/765 [05:59<01:28,  1.63it/s]

[621/765]  raw='pass'  →  Pass

 81%|████████▏ | 622/765 [05:59<01:31,  1.57it/s]

[622/765]  raw='fail'  →  Fail

 81%|████████▏ | 623/765 [06:00<01:28,  1.60it/s]

[623/765]  raw='pass'  →  Pass

 82%|████████▏ | 624/765 [06:01<01:26,  1.63it/s]

[624/765]  raw='pass'  →  Pass

 82%|████████▏ | 625/765 [06:01<01:18,  1.77it/s]

[625/765]  raw='fail'  →  Fail

 82%|████████▏ | 626/765 [06:02<01:15,  1.85it/s]

[626/765]  raw='fail'  →  Fail

 82%|████████▏ | 627/765 [06:02<01:15,  1.82it/s]

[627/765]  raw='pass'  →  Pass

 82%|████████▏ | 628/765 [06:03<01:19,  1.73it/s]

[628/765]  raw='pass'  →  Pass

 82%|████████▏ | 629/765 [06:03<01:17,  1.75it/s]

[629/765]  raw='pass'  →  Pass

 82%|████████▏ | 630/765 [06:04<01:24,  1.60it/s]

[630/765]  raw='pass'  →  Pass

 82%|████████▏ | 631/765 [06:05<01:39,  1.35it/s]

[631/765]  raw='pass'  →  Pass

 83%|████████▎ | 632/765 [06:06<01:31,  1.45it/s]

[632/765]  raw='fail'  →  Fail

 83%|████████▎ | 633/765 [06:06<01:32,  1.43it/s]

[633/765]  raw='pass'  →  Pass

 83%|████████▎ | 634/765 [06:07<01:27,  1.50it/s]

[634/765]  raw='pass'  →  Pass

 83%|████████▎ | 635/765 [06:08<01:23,  1.55it/s]

[635/765]  raw='fail'  →  Fail

 83%|████████▎ | 636/765 [06:08<01:23,  1.54it/s]

[636/765]  raw='pass'  →  Pass

 83%|████████▎ | 637/765 [06:09<01:23,  1.53it/s]

[637/765]  raw='pass'  →  Pass

 83%|████████▎ | 638/765 [06:09<01:20,  1.59it/s]

[638/765]  raw='fail'  →  Fail

 84%|████████▎ | 639/765 [06:10<01:14,  1.70it/s]

[639/765]  raw='fail'  →  Fail

 84%|████████▎ | 640/765 [06:10<01:11,  1.75it/s]

[640/765]  raw='fail'  →  Fail

 84%|████████▍ | 641/765 [06:11<01:09,  1.80it/s]

[641/765]  raw='fail'  →  Fail

 84%|████████▍ | 642/765 [06:12<01:19,  1.56it/s]

[642/765]  raw='pass'  →  Pass

 84%|████████▍ | 643/765 [06:12<01:14,  1.64it/s]

[643/765]  raw='fail'  →  Fail

 84%|████████▍ | 644/765 [06:13<01:10,  1.71it/s]

[644/765]  raw='fail'  →  Fail

 84%|████████▍ | 645/765 [06:13<01:06,  1.80it/s]

[645/765]  raw='fail'  →  Fail

 84%|████████▍ | 646/765 [06:14<01:11,  1.67it/s]

[646/765]  raw='pass'  →  Pass

 85%|████████▍ | 647/765 [06:15<01:16,  1.53it/s]

[647/765]  raw='pass'  →  Pass

 85%|████████▍ | 648/765 [06:15<01:14,  1.57it/s]

[648/765]  raw='pass'  →  Pass

 85%|████████▍ | 649/765 [06:16<01:10,  1.65it/s]

[649/765]  raw='fail'  →  Fail

 85%|████████▍ | 650/765 [06:17<01:10,  1.63it/s]

[650/765]  raw='pass'  →  Pass

 85%|████████▌ | 651/765 [06:17<01:05,  1.73it/s]

[651/765]  raw='fail'  →  Fail

 85%|████████▌ | 652/765 [06:18<01:01,  1.83it/s]

[652/765]  raw='fail'  →  Fail

 85%|████████▌ | 653/765 [06:18<01:02,  1.79it/s]

[653/765]  raw='pass'  →  Pass

 85%|████████▌ | 654/765 [06:19<01:03,  1.75it/s]

[654/765]  raw='fail'  →  Fail

 86%|████████▌ | 655/765 [06:19<01:02,  1.75it/s]

[655/765]  raw='fail'  →  Fail

 86%|████████▌ | 656/765 [06:20<00:59,  1.83it/s]

[656/765]  raw='fail'  →  Fail

 86%|████████▌ | 657/765 [06:20<00:58,  1.85it/s]

[657/765]  raw='fail'  →  Fail

 86%|████████▌ | 658/765 [06:21<00:55,  1.93it/s]

[658/765]  raw='fail'  →  Fail

 86%|████████▌ | 659/765 [06:21<00:53,  1.97it/s]

[659/765]  raw='fail'  →  Fail

 86%|████████▋ | 660/765 [06:22<00:54,  1.94it/s]

[660/765]  raw='fail'  →  Fail

 86%|████████▋ | 661/765 [06:23<01:01,  1.68it/s]

[661/765]  raw='pass'  →  Pass

 87%|████████▋ | 662/765 [06:23<01:02,  1.64it/s]

[662/765]  raw='pass'  →  Pass

 87%|████████▋ | 663/765 [06:24<00:59,  1.71it/s]

[663/765]  raw='fail'  →  Fail

 87%|████████▋ | 664/765 [06:24<00:59,  1.70it/s]

[664/765]  raw='pass'  →  Pass

 87%|████████▋ | 665/765 [06:25<00:56,  1.78it/s]

[665/765]  raw='fail'  →  Fail

 87%|████████▋ | 666/765 [06:26<00:58,  1.69it/s]

[666/765]  raw='pass'  →  Pass

 87%|████████▋ | 667/765 [06:26<00:54,  1.78it/s]

[667/765]  raw='fail'  →  Fail

 87%|████████▋ | 668/765 [06:27<00:55,  1.76it/s]

[668/765]  raw='pass'  →  Pass

 87%|████████▋ | 669/765 [06:27<00:57,  1.67it/s]

[669/765]  raw='pass'  →  Pass

 88%|████████▊ | 670/765 [06:28<00:57,  1.64it/s]

[670/765]  raw='pass'  →  Pass

 88%|████████▊ | 671/765 [06:29<01:02,  1.51it/s]

[671/765]  raw='pass'  →  Pass

 88%|████████▊ | 672/765 [06:29<01:01,  1.52it/s]

[672/765]  raw='pass'  →  Pass

 88%|████████▊ | 673/765 [06:30<00:55,  1.65it/s]

[673/765]  raw='fail'  →  Fail

 88%|████████▊ | 674/765 [06:31<00:58,  1.55it/s]

[674/765]  raw='pass'  →  Pass

 88%|████████▊ | 675/765 [06:31<00:54,  1.64it/s]

[675/765]  raw='fail'  →  Fail

 88%|████████▊ | 676/765 [06:32<00:53,  1.65it/s]

[676/765]  raw='fail'  →  Fail

 88%|████████▊ | 677/765 [06:32<00:51,  1.70it/s]

[677/765]  raw='fail'  →  Fail

 89%|████████▊ | 678/765 [06:33<00:47,  1.81it/s]

[678/765]  raw='fail'  →  Fail

 89%|████████▉ | 679/765 [06:33<00:49,  1.74it/s]

[679/765]  raw='pass'  →  Pass

 89%|████████▉ | 680/765 [06:34<00:49,  1.71it/s]

[680/765]  raw='fail'  →  Fail

 89%|████████▉ | 681/765 [06:35<00:50,  1.67it/s]

[681/765]  raw='pass'  →  Pass

 89%|████████▉ | 682/765 [06:35<00:50,  1.64it/s]

[682/765]  raw='pass'  →  Pass

 89%|████████▉ | 683/765 [06:36<00:48,  1.69it/s]

[683/765]  raw='pass'  →  Pass

 89%|████████▉ | 684/765 [06:36<00:47,  1.70it/s]

[684/765]  raw='pass'  →  Pass

 90%|████████▉ | 685/765 [06:37<00:47,  1.70it/s]

[685/765]  raw='pass'  →  Pass

 90%|████████▉ | 686/765 [06:37<00:45,  1.74it/s]

[686/765]  raw='fail'  →  Fail

 90%|████████▉ | 687/765 [06:38<00:46,  1.69it/s]

[687/765]  raw='pass'  →  Pass

 90%|████████▉ | 688/765 [06:39<00:45,  1.71it/s]

[688/765]  raw='fail'  →  Fail

 90%|█████████ | 689/765 [06:39<00:45,  1.66it/s]

[689/765]  raw='pass'  →  Pass

 90%|█████████ | 690/765 [06:40<00:43,  1.73it/s]

[690/765]  raw='fail'  →  Fail

 90%|█████████ | 691/765 [06:40<00:40,  1.81it/s]

[691/765]  raw='fail'  →  Fail

 90%|█████████ | 692/765 [06:41<00:39,  1.83it/s]

[692/765]  raw='fail'  →  Fail

 91%|█████████ | 693/765 [06:42<00:44,  1.62it/s]

[693/765]  raw='fail'  →  Fail

 91%|█████████ | 694/765 [06:42<00:41,  1.73it/s]

[694/765]  raw='fail'  →  Fail

 91%|█████████ | 695/765 [06:43<00:39,  1.76it/s]

[695/765]  raw='fail'  →  Fail

 91%|█████████ | 696/765 [06:43<00:38,  1.80it/s]

[696/765]  raw='fail'  →  Fail

 91%|█████████ | 697/765 [06:44<00:39,  1.72it/s]

[697/765]  raw='pass'  →  Pass

 91%|█████████ | 698/765 [06:44<00:36,  1.82it/s]

[698/765]  raw='fail'  →  Fail

 91%|█████████▏| 699/765 [06:45<00:35,  1.84it/s]

[699/765]  raw='fail'  →  Fail

 92%|█████████▏| 700/765 [06:45<00:34,  1.90it/s]

[700/765]  raw='fail'  →  Fail

 92%|█████████▏| 701/765 [06:46<00:33,  1.89it/s]

[701/765]  raw='fail'  →  Fail

 92%|█████████▏| 702/765 [06:46<00:32,  1.94it/s]

[702/765]  raw='fail'  →  Fail

 92%|█████████▏| 703/765 [06:47<00:32,  1.92it/s]

[703/765]  raw='pass'  →  Pass

 92%|█████████▏| 704/765 [06:47<00:31,  1.91it/s]

[704/765]  raw='fail'  →  Fail

 92%|█████████▏| 705/765 [06:48<00:31,  1.90it/s]

[705/765]  raw='fail'  →  Fail

 92%|█████████▏| 706/765 [06:48<00:30,  1.95it/s]

[706/765]  raw='fail'  →  Fail

 92%|█████████▏| 707/765 [06:49<00:34,  1.68it/s]

[707/765]  raw='pass'  →  Pass

 93%|█████████▎| 708/765 [06:50<00:32,  1.74it/s]

[708/765]  raw='fail'  →  Fail

 93%|█████████▎| 709/765 [06:50<00:31,  1.78it/s]

[709/765]  raw='fail'  →  Fail

 93%|█████████▎| 710/765 [06:51<00:31,  1.77it/s]

[710/765]  raw='pass'  →  Pass

 93%|█████████▎| 711/765 [06:51<00:29,  1.86it/s]

[711/765]  raw='fail'  →  Fail

 93%|█████████▎| 712/765 [06:52<00:29,  1.79it/s]

[712/765]  raw='pass'  →  Pass

 93%|█████████▎| 713/765 [06:53<00:30,  1.69it/s]

[713/765]  raw='pass'  →  Pass

 93%|█████████▎| 714/765 [06:53<00:29,  1.74it/s]

[714/765]  raw='fail'  →  Fail

 93%|█████████▎| 715/765 [06:54<00:27,  1.82it/s]

[715/765]  raw='fail'  →  Fail

 94%|█████████▎| 716/765 [06:54<00:25,  1.90it/s]

[716/765]  raw='fail'  →  Fail

 94%|█████████▎| 717/765 [06:55<00:26,  1.84it/s]

[717/765]  raw='pass'  →  Pass

 94%|█████████▍| 718/765 [06:55<00:25,  1.85it/s]

[718/765]  raw='fail'  →  Fail

 94%|█████████▍| 719/765 [06:56<00:24,  1.86it/s]

[719/765]  raw='fail'  →  Fail

 94%|█████████▍| 720/765 [06:56<00:23,  1.88it/s]

[720/765]  raw='fail'  →  Fail

 94%|█████████▍| 721/765 [06:57<00:24,  1.81it/s]

[721/765]  raw='pass'  →  Pass

 94%|█████████▍| 722/765 [06:57<00:24,  1.73it/s]

[722/765]  raw='fail'  →  Fail

 95%|█████████▍| 723/765 [06:58<00:22,  1.83it/s]

[723/765]  raw='fail'  →  Fail

 95%|█████████▍| 724/765 [06:58<00:21,  1.89it/s]

[724/765]  raw='fail'  →  Fail

 95%|█████████▍| 725/765 [06:59<00:20,  1.96it/s]

[725/765]  raw='fail'  →  Fail

 95%|█████████▍| 726/765 [06:59<00:20,  1.89it/s]

[726/765]  raw='pass'  →  Pass

 95%|█████████▌| 727/765 [07:00<00:20,  1.88it/s]

[727/765]  raw='fail'  →  Fail

 95%|█████████▌| 728/765 [07:01<00:19,  1.88it/s]

[728/765]  raw='fail'  →  Fail

 95%|█████████▌| 729/765 [07:01<00:19,  1.81it/s]

[729/765]  raw='pass'  →  Pass

 95%|█████████▌| 730/765 [07:02<00:18,  1.90it/s]

[730/765]  raw='fail'  →  Fail

 96%|█████████▌| 731/765 [07:02<00:17,  1.94it/s]

[731/765]  raw='fail'  →  Fail

 96%|█████████▌| 732/765 [07:03<00:19,  1.73it/s]

[732/765]  raw='pass'  →  Pass

 96%|█████████▌| 733/765 [07:03<00:17,  1.83it/s]

[733/765]  raw='fail'  →  Fail

 96%|█████████▌| 734/765 [07:04<00:17,  1.79it/s]

[734/765]  raw='pass'  →  Pass

 96%|█████████▌| 735/765 [07:04<00:15,  1.88it/s]

[735/765]  raw='fail'  →  Fail

 96%|█████████▌| 736/765 [07:05<00:15,  1.84it/s]

[736/765]  raw='fail'  →  Fail

 96%|█████████▋| 737/765 [07:06<00:15,  1.80it/s]

[737/765]  raw='fail'  →  Fail

 96%|█████████▋| 738/765 [07:06<00:14,  1.83it/s]

[738/765]  raw='pass'  →  Pass

 97%|█████████▋| 739/765 [07:07<00:13,  1.91it/s]

[739/765]  raw='fail'  →  Fail

 97%|█████████▋| 740/765 [07:07<00:12,  1.95it/s]

[740/765]  raw='fail'  →  Fail

 97%|█████████▋| 741/765 [07:08<00:12,  1.93it/s]

[741/765]  raw='fail'  →  Fail

 97%|█████████▋| 742/765 [07:08<00:12,  1.91it/s]

[742/765]  raw='pass'  →  Pass

 97%|█████████▋| 743/765 [07:09<00:11,  1.85it/s]

[743/765]  raw='fail'  →  Fail

 97%|█████████▋| 744/765 [07:09<00:11,  1.76it/s]

[744/765]  raw='pass'  →  Pass

 97%|█████████▋| 745/765 [07:10<00:10,  1.84it/s]

[745/765]  raw='fail'  →  Fail

 98%|█████████▊| 746/765 [07:10<00:10,  1.76it/s]

[746/765]  raw='pass'  →  Pass

 98%|█████████▊| 747/765 [07:11<00:10,  1.75it/s]

[747/765]  raw='pass'  →  Pass

 98%|█████████▊| 748/765 [07:12<00:09,  1.73it/s]

[748/765]  raw='fail'  →  Fail

 98%|█████████▊| 749/765 [07:12<00:09,  1.77it/s]

[749/765]  raw='fail'  →  Fail

 98%|█████████▊| 750/765 [07:13<00:08,  1.85it/s]

[750/765]  raw='fail'  →  Fail

 98%|█████████▊| 751/765 [07:13<00:07,  1.85it/s]

[751/765]  raw='fail'  →  Fail

 98%|█████████▊| 752/765 [07:14<00:07,  1.71it/s]

[752/765]  raw='pass'  →  Pass

 98%|█████████▊| 753/765 [07:14<00:06,  1.80it/s]

[753/765]  raw='fail'  →  Fail

 99%|█████████▊| 754/765 [07:15<00:06,  1.83it/s]

[754/765]  raw='fail'  →  Fail

 99%|█████████▊| 755/765 [07:15<00:05,  1.73it/s]

[755/765]  raw='pass'  →  Pass

 99%|█████████▉| 756/765 [07:16<00:05,  1.65it/s]

[756/765]  raw='pass'  →  Pass

 99%|█████████▉| 757/765 [07:17<00:04,  1.66it/s]

[757/765]  raw='pass'  →  Pass

 99%|█████████▉| 758/765 [07:17<00:04,  1.69it/s]

[758/765]  raw='pass'  →  Pass

 99%|█████████▉| 759/765 [07:18<00:03,  1.61it/s]

[759/765]  raw='pass'  →  Pass

 99%|█████████▉| 760/765 [07:19<00:03,  1.64it/s]

[760/765]  raw='pass'  →  Pass

 99%|█████████▉| 761/765 [07:19<00:02,  1.65it/s]

[761/765]  raw='pass'  →  Pass

100%|█████████▉| 762/765 [07:20<00:01,  1.72it/s]

[762/765]  raw='fail'  →  Fail

100%|█████████▉| 763/765 [07:20<00:01,  1.61it/s]

[763/765]  raw='pass'  →  Pass

100%|█████████▉| 764/765 [07:21<00:00,  1.63it/s]

[764/765]  raw='pass'  →  Pass

100%|██████████| 765/765 [07:22<00:00,  1.73it/s]

[765/765]  raw='fail'  →  Fail

In [ ]:
# Cell 10 Evaluate
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         0       0      fail         Fail         Fail
1         0       0      fail         Fail         Fail
2         0       0      fail         Fail         Fail
3         1       1      pass         Pass         Pass
4         0       0      fail         Fail         Fail
5         0       0      fail         Fail         Fail
6         1       1      pass         Pass         Pass
7         1       0      fail         Pass         Fail
8         1       1      pass         Pass         Pass
9         0       0      fail         Fail         Fail
10        0       0      fail         Fail         Fail
11        1       1      pass         Pass         Pass
12        1       1      pass         Pass         Pass
13        1       1      pass         Pass         Pass
14        1       0      fail         Pass         Fail
15        1       1      pass         Pass         Pass
16        1       1      pass         Pass         Pass
17        1       1      pass         Pass         Pass
18        0       0      fail         Fail         Fail
19        0       1      pass         Fail         Pass
20        0       0      fail         Fail         Fail
21        0       0      fail         Fail         Fail
22        0       0      fail         Fail         Fail
23        1       1      pass         Pass         Pass
24        1       1      pass         Pass         Pass
25        1       0      fail         Pass         Fail
26        0       0      fail         Fail         Fail
27        1       0      fail         Pass         Fail
28        1       1      pass         Pass         Pass
29        0       0      fail         Fail         Fail
30        1       1      pass         Pass         Pass
31        0       0      fail         Fail         Fail
32        1       1      pass         Pass         Pass
33        0       0      fail         Fail         Fail
34        0       0      fail         Fail         Fail
35        1       0      fail         Pass         Fail
36        1       1      pass         Pass         Pass
37        0       0      fail         Fail         Fail
38        1       1      pass         Pass         Pass
39        1       1      pass         Pass         Pass
40        1       1      pass         Pass         Pass
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        1       1      pass         Pass         Pass
44        0       0      fail         Fail         Fail
45        0       0      fail         Fail         Fail
46        0       0      fail         Fail         Fail
47        1       1      pass         Pass         Pass
48        0       0      fail         Fail         Fail
49        1       1      pass         Pass         Pass
50        0       0      fail         Fail         Fail
51        0       0      fail         Fail         Fail
52        1       0      fail         Pass         Fail
53        1       1      pass         Pass         Pass
54        0       0      fail         Fail         Fail
55        0       0      fail         Fail         Fail
56        0       0      fail         Fail         Fail
57        0       0      fail         Fail         Fail
58        0       1      pass         Fail         Pass
59        0       0      fail         Fail         Fail
60        1       1      pass         Pass         Pass
61        0       0      fail         Fail         Fail
62        1       1      pass         Pass         Pass
63        0       0      fail         Fail         Fail
64        0       0      fail         Fail         Fail
65        1       1      pass         Pass         Pass
66        1       1      pass         Pass         Pass
67        0       0      fail         Fail         Fail
68        1       0      fail         Pass         Fail
69        0       0      fail         Fail         Fail
70        0       0      fail         Fail         Fail
71        0       0      fail         Fail         Fail
72        0       0      fail         Fail         Fail
73        0       0      fail         Fail         Fail
74        0       0      fail         Fail         Fail
75        1       1      pass         Pass         Pass
76        0       0      fail         Fail         Fail
77        1       1      pass         Pass         Pass
78        0       0      fail         Fail         Fail
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        1       0      fail         Pass         Fail
82        1       1      pass         Pass         Pass
83        1       1      pass         Pass         Pass
84        0       0      fail         Fail         Fail
85        0       0      fail         Fail         Fail
86        0       0      fail         Fail         Fail
87        0       0      fail         Fail         Fail
88        1       1      pass         Pass         Pass
89        0       0      fail         Fail         Fail
90        1       1      pass         Pass         Pass
91        1       1      pass         Pass         Pass
92        1       1      pass         Pass         Pass
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       0      fail         Fail         Fail
96        0       0      fail         Fail         Fail
97        0       0      fail         Fail         Fail
98        0       1      pass         Fail         Pass
99        0       0      fail         Fail         Fail
100       0       0      fail         Fail         Fail
101       0       0      fail         Fail         Fail
102       0       0      fail         Fail         Fail
103       0       0      fail         Fail         Fail
104       0       0      fail         Fail         Fail
105       1       1      pass         Pass         Pass
106       1       1      pass         Pass         Pass
107       0       0      fail         Fail         Fail
108       1       1      pass         Pass         Pass
109       0       0      fail         Fail         Fail
110       0       0      fail         Fail         Fail
111       0       0      fail         Fail         Fail
112       1       1      pass         Pass         Pass
113       0       0      fail         Fail         Fail
114       0       0      fail         Fail         Fail
115       0       0      fail         Fail         Fail
116       1       0      fail         Pass         Fail
117       1       1      pass         Pass         Pass
118       0       0      fail         Fail         Fail
119       1       1      pass         Pass         Pass
120       1       1      pass         Pass         Pass
121       1       0      fail         Pass         Fail
122       1       1      pass         Pass         Pass
123       1       0      fail         Pass         Fail
124       0       0      fail         Fail         Fail
125       0       0      fail         Fail         Fail
126       0       0      fail         Fail         Fail
127       0       0      fail         Fail         Fail
128       0       0      fail         Fail         Fail
129       1       1      pass         Pass         Pass
130       0       0      fail         Fail         Fail
131       0       0      fail         Fail         Fail
132       0       0      fail         Fail         Fail
133       0       0      fail         Fail         Fail
134       0       0      fail         Fail         Fail
135       0       0      fail         Fail         Fail
136       1       1      pass         Pass         Pass
137       1       1      pass         Pass         Pass
138       1       1      pass         Pass         Pass
139       0       0      fail         Fail         Fail
140       0       0      fail         Fail         Fail
141       0       0      fail         Fail         Fail
142       1       0      fail         Pass         Fail
143       1       1      pass         Pass         Pass
144       0       1      pass         Fail         Pass
145       1       0      fail         Pass         Fail
146       1       1      pass         Pass         Pass
147       1       1      pass         Pass         Pass
148       1       0      fail         Pass         Fail
149       0       0      fail         Fail         Fail
150       1       1      pass         Pass         Pass
151       0       1      pass         Fail         Pass
152       1       0      fail         Pass         Fail
153       0       1      pass         Fail         Pass
154       0       1      pass         Fail         Pass
155       1       1      pass         Pass         Pass
156       0       1      pass         Fail         Pass
157       1       1      pass         Pass         Pass
158       1       1      pass         Pass         Pass
159       1       1      pass         Pass         Pass
160       0       0      fail         Fail         Fail
161       0       0      fail         Fail         Fail
162       0       0      fail         Fail         Fail
163       1       1      pass         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0      fail         Fail         Fail
166       0       0      fail         Fail         Fail
167       0       0      fail         Fail         Fail
168       1       1      pass         Pass         Pass
169       1       0      fail         Pass         Fail
170       1       1      pass         Pass         Pass
171       1       1      pass         Pass         Pass
172       1       1      pass         Pass         Pass
173       1       1      pass         Pass         Pass
174       0       0      fail         Fail         Fail
175       0       0      fail         Fail         Fail
176       0       0      fail         Fail         Fail
177       0       1      pass         Fail         Pass
178       1       1      pass         Pass         Pass
179       0       0      fail         Fail         Fail
180       0       0      fail         Fail         Fail
181       0       0      fail         Fail         Fail
182       0       0      fail         Fail         Fail
183       0       0      fail         Fail         Fail
184       1       1      pass         Pass         Pass
185       1       1      pass         Pass         Pass
186       0       0      fail         Fail         Fail
187       0       0      fail         Fail         Fail
188       1       1      pass         Pass         Pass
189       1       1      pass         Pass         Pass
190       0       1      pass         Fail         Pass
191       1       1      pass         Pass         Pass
192       0       0      fail         Fail         Fail
193       0       0      fail         Fail         Fail
194       1       1      pass         Pass         Pass
195       0       0      fail         Fail         Fail
196       1       1      pass         Pass         Pass
197       0       0      fail         Fail         Fail
198       1       1      pass         Pass         Pass
199       0       0      fail         Fail         Fail
200       0       0      fail         Fail         Fail
201       1       1      pass         Pass         Pass
202       0       0      fail         Fail         Fail
203       1       0      fail         Pass         Fail
204       0       0      fail         Fail         Fail
205       0       0      fail         Fail         Fail
206       1       1      pass         Pass         Pass
207       0       1      pass         Fail         Pass
208       0       0      fail         Fail         Fail
209       0       0      fail         Fail         Fail
210       0       0      fail         Fail         Fail
211       0       0      fail         Fail         Fail
212       1       1      pass         Pass         Pass
213       0       0      fail         Fail         Fail
214       0       1      pass         Fail         Pass
215       0       0      fail         Fail         Fail
216       0       0      fail         Fail         Fail
217       1       1      pass         Pass         Pass
218       1       1      pass         Pass         Pass
219       0       0      fail         Fail         Fail
220       0       0      fail         Fail         Fail
221       0       0      fail         Fail         Fail
222       1       1      pass         Pass         Pass
223       1       1      pass         Pass         Pass
224       0       0      fail         Fail         Fail
225       1       1      pass         Pass         Pass
226       0       0      fail         Fail         Fail
227       0       0      fail         Fail         Fail
228       0       0      fail         Fail         Fail
229       0       0      fail         Fail         Fail
230       1       0      fail         Pass         Fail
231       1       0      fail         Pass         Fail
232       0       0      fail         Fail         Fail
233       0       0      fail         Fail         Fail
234       1       1      pass         Pass         Pass
235       0       0      fail         Fail         Fail
236       0       0      fail         Fail         Fail
237       0       0      fail         Fail         Fail
238       1       1      pass         Pass         Pass
239       0       1      pass         Fail         Pass
240       0       1      pass         Fail         Pass
241       0       0      fail         Fail         Fail
242       0       0      fail         Fail         Fail
243       0       0      fail         Fail         Fail
244       0       0      fail         Fail         Fail
245       1       1      pass         Pass         Pass
246       1       1      pass         Pass         Pass
247       0       0      fail         Fail         Fail
248       1       0      fail         Pass         Fail
249       0       0      fail         Fail         Fail
250       0       0      fail         Fail         Fail
251       1       0      fail         Pass         Fail
252       1       0      fail         Pass         Fail
253       0       0      fail         Fail         Fail
254       1       1      pass         Pass         Pass
255       0       0      fail         Fail         Fail
256       1       0      fail         Pass         Fail
257       0       0      fail         Fail         Fail
258       0       0      fail         Fail         Fail
259       1       1      pass         Pass         Pass
260       0       0      fail         Fail         Fail
261       1       1      pass         Pass         Pass
262       1       1      pass         Pass         Pass
263       0       0      fail         Fail         Fail
264       1       1      pass         Pass         Pass
265       1       0      fail         Pass         Fail
266       1       1      pass         Pass         Pass
267       1       0      fail         Pass         Fail
268       1       1      pass         Pass         Pass
269       0       0      fail         Fail         Fail
270       0       0      fail         Fail         Fail
271       1       1      pass         Pass         Pass
272       0       0      fail         Fail         Fail
273       1       1      pass         Pass         Pass
274       1       1      pass         Pass         Pass
275       0       0      fail         Fail         Fail
276       0       0      fail         Fail         Fail
277       0       0      fail         Fail         Fail
278       1       1      pass         Pass         Pass
279       0       0      fail         Fail         Fail
280       1       1      pass         Pass         Pass
281       0       0      fail         Fail         Fail
282       1       1      pass         Pass         Pass
283       0       0      fail         Fail         Fail
284       0       0      fail         Fail         Fail
285       1       1      pass         Pass         Pass
286       0       1      pass         Fail         Pass
287       1       0      fail         Pass         Fail
288       0       0      fail         Fail         Fail
289       0       0      fail         Fail         Fail
290       0       0      fail         Fail         Fail
291       0       0      fail         Fail         Fail
292       1       1      pass         Pass         Pass
293       1       1      pass         Pass         Pass
294       0       0      fail         Fail         Fail
295       1       1      pass         Pass         Pass
296       1       1      pass         Pass         Pass
297       1       1      pass         Pass         Pass
298       1       1      pass         Pass         Pass
299       0       0      fail         Fail         Fail
300       0       0      fail         Fail         Fail
301       0       1      pass         Fail         Pass
302       1       1      pass         Pass         Pass
303       0       0      fail         Fail         Fail
304       0       0      fail         Fail         Fail
305       0       0      fail         Fail         Fail
306       0       0      fail         Fail         Fail
307       0       0      fail         Fail         Fail
308       1       0      fail         Pass         Fail
309       0       0      fail         Fail         Fail
310       0       0      fail         Fail         Fail
311       0       0      fail         Fail         Fail
312       1       0      fail         Pass         Fail
313       1       1      pass         Pass         Pass
314       0       0      fail         Fail         Fail
315       0       0      fail         Fail         Fail
316       0       1      pass         Fail         Pass
317       0       0      fail         Fail         Fail
318       1       0      fail         Pass         Fail
319       0       1      pass         Fail         Pass
320       0       0      fail         Fail         Fail
321       0       0      fail         Fail         Fail
322       0       1      pass         Fail         Pass
323       0       0      fail         Fail         Fail
324       1       0      fail         Pass         Fail
325       1       1      pass         Pass         Pass
326       0       0      fail         Fail         Fail
327       1       0      fail         Pass         Fail
328       0       0      fail         Fail         Fail
329       1       1      pass         Pass         Pass
330       0       0      fail         Fail         Fail
331       0       0      fail         Fail         Fail
332       0       0      fail         Fail         Fail
333       0       1      pass         Fail         Pass
334       0       0      fail         Fail         Fail
335       0       0      fail         Fail         Fail
336       1       1      pass         Pass         Pass
337       0       0      fail         Fail         Fail
338       1       1      pass         Pass         Pass
339       1       1      pass         Pass         Pass
340       1       0      fail         Pass         Fail
341       1       1      pass         Pass         Pass
342       1       1      pass         Pass         Pass
343       1       1      pass         Pass         Pass
344       1       1      pass         Pass         Pass
345       1       1      pass         Pass         Pass
346       0       0      fail         Fail         Fail
347       1       1      pass         Pass         Pass
348       0       0      fail         Fail         Fail
349       0       0      fail         Fail         Fail
350       0       0      fail         Fail         Fail
351       1       1      pass         Pass         Pass
352       0       0      fail         Fail         Fail
353       0       0      fail         Fail         Fail
354       1       1      pass         Pass         Pass
355       0       1      pass         Fail         Pass

0.85 O_O

In [ ]:
# save
from google.colab import drive
import shutil
drive.mount("/content/drive")
shutil.copytree(ADAPTER_PATH, f"/content/drive/MyDrive/{ADAPTER_PATH}")
print("Backed up to Drive")

ValueError: Mountpoint must not already contain files

In [ ]:
#
from google.colab import drive
import shutil
drive.mount("/content/drive")
shutil.copytree(ADAPTER_PATH, f"/content/drive/MyDrive/{ADAPTER_PATH}")
print("Backed up to Drive")

MessageError: Error: credential propagation was unsuccessful

##### downloading and testing adapter

In [ ]:

from google.colab import drive
import shutil
import os

drive.mount("/content/drive")

local_path = "./qwen2-lora-balanced"                          # where trainer saved checkpoints
drive_path = "/content/drive/MyDrive/qwen2-lora-balanced-adapter"

# find the best checkpoint folder saved by trainer
checkpoints = [f for f in os.listdir(local_path) if f.startswith("checkpoint")]
print("Checkpoints found:", checkpoints)

Mounted at /content/drive

FileNotFoundError: [Errno 2] No such file or directory: './qwen2-lora-balanced'

In [ ]:
#prediction

In [ ]:
def predict(test, model, tokenizer):
    """Zero-shot binary prediction. Returns (y_pred, y_generated).
    Returns -1 for unparseable outputs.
    """
    y_pred = []
    y_generated = []
    pipe = pipeline(
        task="text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=5,
        do_sample=False,
    )
    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]
        result = pipe(prompt)
        generated = result[0]["generated_text"][len(prompt):].strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)          # unparseable

    return y_pred, y_generated

In [ ]:
def predict(test, model, tokenizer):
    y_pred = []
    y_generated = []

    pipe = pipeline(
        task="text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=5,
        temperature=0.1,
        do_sample=True,
    )

    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]
        result = pipe(prompt)

        # grab only the newly generated text after the prompt
        generated = result[0]["generated_text"][len(prompt):].strip()
        y_generated.append(generated)

        # parse Pass / Fail (case-insensitive)
        lower = generated.lower()
        if "pass" in lower:
            y_pred.append(1)
        elif "fail" in lower:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        # print each response as it comes in
        label = {1: "Pass", 0: "Fail", -1: "???"}[y_pred[-1]]
        print(f"[{i+1:>3}/{len(test)}] Generated: {repr(generated):<20}  →  {label}")

    return y_pred, y_generated

In [ ]:
def predict(test, model, tokenizer):
    y_pred = []
    y_generated = []

    # get the single token id for "Pass" and "Fail"
    pass_id = tokenizer.encode("Pass", add_special_tokens=False)[0]
    fail_id = tokenizer.encode("Fail", add_special_tokens=False)[0]
    print(f"Token ids  —  Pass: {pass_id}, Fail: {fail_id}")

    model.eval()
    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model(**inputs)

        # logits for the very next token the model would generate
        next_token_logits = outputs.logits[0, -1, :]

        pass_logit = next_token_logits[pass_id].item()
        fail_logit = next_token_logits[fail_id].item()

        label = "Pass" if pass_logit > fail_logit else "Fail"
        y_pred.append(1 if label == "Pass" else 0)
        y_generated.append(f"Pass={pass_logit:.2f} Fail={fail_logit:.2f}")

        print(f"[{i+1:>3}/{len(test)}]  Pass logit: {pass_logit:6.2f}  "
              f"Fail logit: {fail_logit:6.2f}  →  {label}")

    return y_pred, y_generated

In [ ]:
### save the models

In [ ]:
import os

adapter_local = "./phi2-lora-balanced-adapter"
if os.path.exists(adapter_local):
    files = os.listdir(adapter_local)
    print(f"Found adapter at {adapter_local}")
    print(f"Files: {files}")
else:
    print("Adapter NOT found on local disk — may have been lost if runtime restarted")

Found adapter at ./phi2-lora-balanced-adapter
Files: ['tokenizer_config.json', 'README.md', 'tokenizer.json', 'adapter_config.json', 'adapter_model.safetensors']

In [ ]:
# Step 3: copy to Google Drive
import shutil

drive_path = "/content/drive/MyDrive/phi2-lora-balanced-adapter"

shutil.copytree(adapter_local, drive_path)
print(f"Adapter saved to Google Drive at:\n  {drive_path}")

Adapter saved to Google Drive at:
  /content/drive/MyDrive/phi2-lora-balanced-adapter

# Ollama

In [ ]:
!nvidia-smi

In [ ]:
!apt-get install -y zstd

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 53 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 0s (17.0 MB/s)
Selecting previously unselected package zstd.
(Reading database ... 122403 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [ ]:
#we need to start the serve

In [ ]:
import subprocess, time
subprocess.Popen(["ollama", "serve"])
time.sleep(5)

In [ ]:
!ollama ps

NAME               ID              SIZE      PROCESSOR    CONTEXT    UNTIL
llama3.2:latest    a80c4f17acd5    2.6 GB    100% GPU     4096       31 seconds from now

In [ ]:
!ollama pull llama3.2

In [ ]:
!ollama run llama3.2 "hi"

Hello! It's nice to meet you. Is there something I can help you with or wou
would you like to chat?

Local host
  * is where the ollama seerver is listening for request. localhost 11434
    * end this request to the Ollama server running right here on this same Colab machine, knocking on door 11434.

In [ ]:
import requests
r = requests.post("http://localhost:11434/api/generate", json={
    "model": "llama3.2:latest",
    "prompt": "Say hello in one sentence",
    "stream": False
})
print(r.json()["response"])

Hello!

## Llama3.2:latest

In [ ]:
def generate_llama_prompt(row):
    return (
        f"You are a fair essay grader. Read the essay below carefully.\n"
        f"Prompt name: {row['prompt_name']}\n"
        f"Task type: {row['task']}\n\n"
        f"Classify the essay as Pass or Fail.\n"
        f"Pass = the essay meets an acceptable standard (proficient or above).\n"
        f"Fail = the essay does not meet the standard (developing or below).\n"
        f"Respond with one word only: Pass or Fail.\n\n"
        f"Essay: {row['full_text']}"
    )

X_test_prompts_llama = pd.DataFrame(
    test_df.apply(generate_llama_prompt, axis=1), columns=["text"]
)

In [ ]:
import requests
from tqdm import tqdm

def predict_ollama(test, model_name="llama3.2:latest"):
    y_pred, y_generated = [], []

    for i in tqdm(range(len(test))):
        prompt = test.iloc[i]["text"]

        resp = requests.post("http://localhost:11434/api/chat", json={
            "model": model_name,
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
            "options": {
                "temperature": 0,      # greedy / deterministic, like do_sample=False
                "num_predict": 5,      # cap new tokens, like max_new_tokens=5
                "num_ctx": 4096,       # context window
            },
            "keep_alive": -1,          # keep model pinned on GPU between calls
        })

        generated = resp.json()["message"]["content"].strip().lower()
        y_generated.append(generated)

        if "pass" in generated:
            y_pred.append(1)
        elif "fail" in generated:
            y_pred.append(0)
        else:
            y_pred.append(-1)

        result = {1: "Pass", 0: "Fail", -1: "???"}[y_pred[-1]]
        print(f"[{i+1:>3}/{len(test)}]  raw='{generated}'  →  {result}")

    return y_pred, y_generated


y_pred, y_generated = predict_ollama(X_test_prompts_llama)

  0%|          | 1/765 [00:03<41:46,  3.28s/it]

[  1/765]  raw='fail'  →  Fail

  0%|          | 2/765 [00:03<20:37,  1.62s/it]

[  2/765]  raw='fail'  →  Fail

  0%|          | 3/765 [00:04<13:51,  1.09s/it]

[  3/765]  raw='fail'  →  Fail

  1%|          | 4/765 [00:04<11:00,  1.15it/s]

[  4/765]  raw='pass'  →  Pass

  1%|          | 5/765 [00:05<09:17,  1.36it/s]

[  5/765]  raw='fail'  →  Fail

  1%|          | 6/765 [00:05<07:58,  1.59it/s]

[  6/765]  raw='fail'  →  Fail

  1%|          | 7/765 [00:06<07:25,  1.70it/s]

[  7/765]  raw='pass.'  →  Pass

  1%|          | 8/765 [00:06<07:00,  1.80it/s]

[  8/765]  raw='fail'  →  Fail

  1%|          | 9/765 [00:07<06:52,  1.83it/s]

[  9/765]  raw='pass.'  →  Pass

  1%|▏         | 10/765 [00:07<06:28,  1.94it/s]

[ 10/765]  raw='fail'  →  Fail

  1%|▏         | 11/765 [00:08<06:08,  2.05it/s]

[ 11/765]  raw='fail'  →  Fail

  2%|▏         | 12/765 [00:08<06:12,  2.02it/s]

[ 12/765]  raw='pass'  →  Pass

  2%|▏         | 13/765 [00:09<06:07,  2.04it/s]

[ 13/765]  raw='fail'  →  Fail

  2%|▏         | 14/765 [00:09<06:03,  2.07it/s]

[ 14/765]  raw='pass'  →  Pass

  2%|▏         | 15/765 [00:09<05:58,  2.09it/s]

[ 15/765]  raw='fail'  →  Fail

  2%|▏         | 16/765 [00:10<05:57,  2.09it/s]

[ 16/765]  raw='pass'  →  Pass

  2%|▏         | 17/765 [00:10<05:55,  2.10it/s]

[ 17/765]  raw='fail'  →  Fail

  2%|▏         | 18/765 [00:11<06:00,  2.07it/s]

[ 18/765]  raw='pass.'  →  Pass

  2%|▏         | 19/765 [00:11<05:56,  2.10it/s]

[ 19/765]  raw='fail.'  →  Fail

  3%|▎         | 20/765 [00:12<06:02,  2.06it/s]

[ 20/765]  raw='pass'  →  Pass

  3%|▎         | 21/765 [00:12<05:56,  2.09it/s]

[ 21/765]  raw='fail'  →  Fail

  3%|▎         | 22/765 [00:13<05:41,  2.18it/s]

[ 22/765]  raw='fail'  →  Fail

  3%|▎         | 23/765 [00:13<05:31,  2.24it/s]

[ 23/765]  raw='fail'  →  Fail

  3%|▎         | 24/765 [00:14<05:44,  2.15it/s]

[ 24/765]  raw='pass'  →  Pass

  3%|▎         | 25/765 [00:14<05:58,  2.07it/s]

[ 25/765]  raw='pass.'  →  Pass

  3%|▎         | 26/765 [00:15<05:50,  2.11it/s]

[ 26/765]  raw='fail'  →  Fail

  4%|▎         | 27/765 [00:15<05:38,  2.18it/s]

[ 27/765]  raw='fail'  →  Fail

  4%|▎         | 28/765 [00:16<05:35,  2.19it/s]

[ 28/765]  raw='fail.'  →  Fail

  4%|▍         | 29/765 [00:16<05:33,  2.21it/s]

[ 29/765]  raw='fail'  →  Fail

  4%|▍         | 30/765 [00:16<05:34,  2.20it/s]

[ 30/765]  raw='fail'  →  Fail

  4%|▍         | 31/765 [00:17<05:40,  2.15it/s]

[ 31/765]  raw='pass.'  →  Pass

  4%|▍         | 32/765 [00:17<05:37,  2.17it/s]

[ 32/765]  raw='fail.'  →  Fail

  4%|▍         | 33/765 [00:18<05:49,  2.09it/s]

[ 33/765]  raw='fail.'  →  Fail

  4%|▍         | 34/765 [00:18<05:52,  2.07it/s]

[ 34/765]  raw='fail.'  →  Fail

  5%|▍         | 35/765 [00:19<05:42,  2.13it/s]

[ 35/765]  raw='fail.'  →  Fail

  5%|▍         | 36/765 [00:19<05:36,  2.17it/s]

[ 36/765]  raw='fail'  →  Fail

  5%|▍         | 37/765 [00:20<05:42,  2.13it/s]

[ 37/765]  raw='pass.'  →  Pass

  5%|▍         | 38/765 [00:20<05:44,  2.11it/s]

[ 38/765]  raw='pass.'  →  Pass

  5%|▌         | 39/765 [00:21<05:46,  2.10it/s]

[ 39/765]  raw='fail'  →  Fail

  5%|▌         | 40/765 [00:21<05:58,  2.02it/s]

[ 40/765]  raw='pass.'  →  Pass

  5%|▌         | 41/765 [00:22<06:22,  1.89it/s]

[ 41/765]  raw='pass.'  →  Pass

  5%|▌         | 42/765 [00:22<06:27,  1.87it/s]

[ 42/765]  raw='fail'  →  Fail

  6%|▌         | 43/765 [00:23<06:10,  1.95it/s]

[ 43/765]  raw='fail'  →  Fail

  6%|▌         | 44/765 [00:23<05:57,  2.02it/s]

[ 44/765]  raw='pass.'  →  Pass

  6%|▌         | 45/765 [00:24<05:41,  2.11it/s]

[ 45/765]  raw='fail'  →  Fail

  6%|▌         | 46/765 [00:24<05:36,  2.13it/s]

[ 46/765]  raw='fail.'  →  Fail

  6%|▌         | 47/765 [00:25<05:37,  2.13it/s]

[ 47/765]  raw='pass.'  →  Pass

  6%|▋         | 48/765 [00:25<05:37,  2.12it/s]

[ 48/765]  raw='fail'  →  Fail

  6%|▋         | 49/765 [00:26<05:32,  2.15it/s]

[ 49/765]  raw='fail'  →  Fail

  7%|▋         | 50/765 [00:26<05:36,  2.13it/s]

[ 50/765]  raw='fail'  →  Fail

  7%|▋         | 51/765 [00:27<05:33,  2.14it/s]

[ 51/765]  raw='fail'  →  Fail

  7%|▋         | 52/765 [00:27<05:31,  2.15it/s]

[ 52/765]  raw='fail.'  →  Fail

  7%|▋         | 53/765 [00:27<05:31,  2.15it/s]

[ 53/765]  raw='fail.'  →  Fail

  7%|▋         | 54/765 [00:28<05:58,  1.98it/s]

[ 54/765]  raw='pass.'  →  Pass

  7%|▋         | 55/765 [00:29<06:00,  1.97it/s]

[ 55/765]  raw='fail'  →  Fail

  7%|▋         | 56/765 [00:29<05:44,  2.06it/s]

[ 56/765]  raw='fail'  →  Fail

  7%|▋         | 57/765 [00:29<05:35,  2.11it/s]

[ 57/765]  raw='fail'  →  Fail

  8%|▊         | 58/765 [00:30<05:32,  2.13it/s]

[ 58/765]  raw='fail'  →  Fail

  8%|▊         | 59/765 [00:30<05:35,  2.11it/s]

[ 59/765]  raw='fail'  →  Fail

  8%|▊         | 60/765 [00:31<05:25,  2.16it/s]

[ 60/765]  raw='fail'  →  Fail

  8%|▊         | 61/765 [00:31<05:24,  2.17it/s]

[ 61/765]  raw='pass'  →  Pass

  8%|▊         | 62/765 [00:32<05:29,  2.13it/s]

[ 62/765]  raw='fail'  →  Fail

  8%|▊         | 63/765 [00:32<05:39,  2.07it/s]

[ 63/765]  raw='pass.'  →  Pass

  8%|▊         | 64/765 [00:33<05:31,  2.11it/s]

[ 64/765]  raw='fail'  →  Fail

  8%|▊         | 65/765 [00:33<05:25,  2.15it/s]

[ 65/765]  raw='fail.'  →  Fail

  9%|▊         | 66/765 [00:34<05:25,  2.15it/s]

[ 66/765]  raw='fail'  →  Fail

  9%|▉         | 67/765 [00:34<05:37,  2.07it/s]

[ 67/765]  raw='pass'  →  Pass

  9%|▉         | 68/765 [00:35<05:33,  2.09it/s]

[ 68/765]  raw='fail'  →  Fail

  9%|▉         | 69/765 [00:35<05:33,  2.09it/s]

[ 69/765]  raw='fail.'  →  Fail

  9%|▉         | 70/765 [00:36<05:27,  2.12it/s]

[ 70/765]  raw='fail.'  →  Fail

  9%|▉         | 71/765 [00:36<05:21,  2.16it/s]

[ 71/765]  raw='pass.'  →  Pass

  9%|▉         | 72/765 [00:36<05:16,  2.19it/s]

[ 72/765]  raw='fail'  →  Fail

 10%|▉         | 73/765 [00:37<05:08,  2.24it/s]

[ 73/765]  raw='fail.'  →  Fail

 10%|▉         | 74/765 [00:37<05:03,  2.28it/s]

[ 74/765]  raw='fail'  →  Fail

 10%|▉         | 75/765 [00:38<05:01,  2.29it/s]

[ 75/765]  raw='fail'  →  Fail

 10%|▉         | 76/765 [00:38<05:09,  2.22it/s]

[ 76/765]  raw='fail'  →  Fail

 10%|█         | 77/765 [00:39<05:07,  2.24it/s]

[ 77/765]  raw='fail'  →  Fail

 10%|█         | 78/765 [00:39<05:09,  2.22it/s]

[ 78/765]  raw='pass.'  →  Pass

 10%|█         | 79/765 [00:40<05:06,  2.24it/s]

[ 79/765]  raw='fail.'  →  Fail

 10%|█         | 80/765 [00:40<05:17,  2.16it/s]

[ 80/765]  raw='pass'  →  Pass

 11%|█         | 81/765 [00:41<05:29,  2.08it/s]

[ 81/765]  raw='pass'  →  Pass

 11%|█         | 82/765 [00:41<05:35,  2.04it/s]

[ 82/765]  raw='pass.'  →  Pass

 11%|█         | 83/765 [00:42<05:42,  1.99it/s]

[ 83/765]  raw='pass'  →  Pass

 11%|█         | 84/765 [00:42<05:57,  1.91it/s]

[ 84/765]  raw='pass'  →  Pass

 11%|█         | 85/765 [00:43<05:47,  1.96it/s]

[ 85/765]  raw='fail'  →  Fail

 11%|█         | 86/765 [00:43<05:34,  2.03it/s]

[ 86/765]  raw='fail.'  →  Fail

 11%|█▏        | 87/765 [00:44<05:27,  2.07it/s]

[ 87/765]  raw='pass.'  →  Pass

 12%|█▏        | 88/765 [00:44<05:19,  2.12it/s]

[ 88/765]  raw='fail'  →  Fail

 12%|█▏        | 89/765 [00:45<05:23,  2.09it/s]

[ 89/765]  raw='pass.'  →  Pass

 12%|█▏        | 90/765 [00:45<05:14,  2.14it/s]

[ 90/765]  raw='fail'  →  Fail

 12%|█▏        | 91/765 [00:45<05:17,  2.13it/s]

[ 91/765]  raw='pass.'  →  Pass

 12%|█▏        | 92/765 [00:46<05:30,  2.04it/s]

[ 92/765]  raw='fail'  →  Fail

 12%|█▏        | 93/765 [00:47<05:42,  1.96it/s]

[ 93/765]  raw='pass.'  →  Pass

 12%|█▏        | 94/765 [00:47<05:28,  2.04it/s]

[ 94/765]  raw='fail'  →  Fail

 12%|█▏        | 95/765 [00:47<05:26,  2.05it/s]

[ 95/765]  raw='fail'  →  Fail

 13%|█▎        | 96/765 [00:48<05:17,  2.11it/s]

[ 96/765]  raw='fail'  →  Fail

 13%|█▎        | 97/765 [00:48<05:12,  2.14it/s]

[ 97/765]  raw='fail'  →  Fail

 13%|█▎        | 98/765 [00:49<05:18,  2.10it/s]

[ 98/765]  raw='fail.'  →  Fail

 13%|█▎        | 99/765 [00:49<05:34,  1.99it/s]

[ 99/765]  raw='fail'  →  Fail

 13%|█▎        | 100/765 [00:50<05:35,  1.98it/s]

[100/765]  raw='fail.'  →  Fail

 13%|█▎        | 101/765 [00:50<05:20,  2.07it/s]

[101/765]  raw='pass.'  →  Pass

 13%|█▎        | 102/765 [00:51<05:11,  2.13it/s]

[102/765]  raw='pass.'  →  Pass

 13%|█▎        | 103/765 [00:51<05:29,  2.01it/s]

[103/765]  raw='fail'  →  Fail

 14%|█▎        | 104/765 [00:52<05:48,  1.90it/s]

[104/765]  raw='fail'  →  Fail

 14%|█▎        | 105/765 [00:52<05:33,  1.98it/s]

[105/765]  raw='fail'  →  Fail

 14%|█▍        | 106/765 [00:53<05:42,  1.92it/s]

[106/765]  raw='pass'  →  Pass

 14%|█▍        | 107/765 [00:54<05:49,  1.88it/s]

[107/765]  raw='pass'  →  Pass

 14%|█▍        | 108/765 [00:54<05:44,  1.91it/s]

[108/765]  raw='fail.'  →  Fail

 14%|█▍        | 109/765 [00:55<05:40,  1.93it/s]

[109/765]  raw='pass.'  →  Pass

 14%|█▍        | 110/765 [00:55<05:30,  1.98it/s]

[110/765]  raw='pass.'  →  Pass

 15%|█▍        | 111/765 [00:55<05:19,  2.05it/s]

[111/765]  raw='fail.'  →  Fail

 15%|█▍        | 112/765 [00:56<05:07,  2.13it/s]

[112/765]  raw='fail'  →  Fail

 15%|█▍        | 113/765 [00:56<05:04,  2.14it/s]

[113/765]  raw='pass.'  →  Pass

 15%|█▍        | 114/765 [00:57<05:08,  2.11it/s]

[114/765]  raw='fail.'  →  Fail

 15%|█▌        | 115/765 [00:57<05:03,  2.14it/s]

[115/765]  raw='fail'  →  Fail

 15%|█▌        | 116/765 [00:58<04:56,  2.19it/s]

[116/765]  raw='fail'  →  Fail

 15%|█▌        | 117/765 [00:58<04:56,  2.19it/s]

[117/765]  raw='fail'  →  Fail

 15%|█▌        | 118/765 [00:59<05:02,  2.14it/s]

[118/765]  raw='pass.'  →  Pass

 16%|█▌        | 119/765 [00:59<05:02,  2.13it/s]

[119/765]  raw='pass.'  →  Pass

 16%|█▌        | 120/765 [01:00<05:03,  2.12it/s]

[120/765]  raw='fail'  →  Fail

 16%|█▌        | 121/765 [01:00<05:10,  2.08it/s]

[121/765]  raw='fail'  →  Fail

 16%|█▌        | 122/765 [01:01<05:10,  2.07it/s]

[122/765]  raw='fail'  →  Fail

 16%|█▌        | 123/765 [01:01<05:16,  2.03it/s]

[123/765]  raw='pass.'  →  Pass

 16%|█▌        | 124/765 [01:02<05:28,  1.95it/s]

[124/765]  raw='fail'  →  Fail

 16%|█▋        | 125/765 [01:02<05:25,  1.97it/s]

[125/765]  raw='fail.'  →  Fail

 16%|█▋        | 126/765 [01:03<05:08,  2.07it/s]

[126/765]  raw='fail'  →  Fail

 17%|█▋        | 127/765 [01:03<04:59,  2.13it/s]

[127/765]  raw='fail'  →  Fail

 17%|█▋        | 128/765 [01:04<05:01,  2.12it/s]

[128/765]  raw='fail.'  →  Fail

 17%|█▋        | 129/765 [01:04<05:02,  2.10it/s]

[129/765]  raw='fail'  →  Fail

 17%|█▋        | 130/765 [01:05<05:15,  2.01it/s]

[130/765]  raw='pass.'  →  Pass

 17%|█▋        | 131/765 [01:05<05:11,  2.04it/s]

[131/765]  raw='fail'  →  Fail

 17%|█▋        | 132/765 [01:06<05:05,  2.07it/s]

[132/765]  raw='fail.'  →  Fail

 17%|█▋        | 133/765 [01:06<04:57,  2.12it/s]

[133/765]  raw='fail'  →  Fail

 18%|█▊        | 134/765 [01:06<04:55,  2.14it/s]

[134/765]  raw='fail'  →  Fail

 18%|█▊        | 135/765 [01:07<04:51,  2.16it/s]

[135/765]  raw='pass.'  →  Pass

 18%|█▊        | 136/765 [01:07<04:53,  2.15it/s]

[136/765]  raw='fail.'  →  Fail

 18%|█▊        | 137/765 [01:17<34:48,  3.33s/it]

[137/765]  raw='pass.'  →  Pass

 18%|█▊        | 138/765 [01:18<26:00,  2.49s/it]

[138/765]  raw='fail.'  →  Fail

 18%|█▊        | 139/765 [01:18<19:57,  1.91s/it]

[139/765]  raw='pass'  →  Pass

 18%|█▊        | 140/765 [01:19<15:33,  1.49s/it]

[140/765]  raw='fail.'  →  Fail

 18%|█▊        | 141/765 [01:19<12:13,  1.18s/it]

[141/765]  raw='fail.'  →  Fail

 19%|█▊        | 142/765 [01:20<10:05,  1.03it/s]

[142/765]  raw='fail'  →  Fail

 19%|█▊        | 143/765 [01:20<08:33,  1.21it/s]

[143/765]  raw='pass.'  →  Pass

 19%|█▉        | 144/765 [01:21<07:47,  1.33it/s]

[144/765]  raw='pass.'  →  Pass

 19%|█▉        | 145/765 [01:22<07:08,  1.45it/s]

[145/765]  raw='fail.'  →  Fail

 19%|█▉        | 146/765 [01:22<06:25,  1.61it/s]

[146/765]  raw='fail'  →  Fail

 19%|█▉        | 147/765 [01:23<06:10,  1.67it/s]

[147/765]  raw='fail'  →  Fail

 19%|█▉        | 148/765 [01:23<06:02,  1.70it/s]

[148/765]  raw='pass.'  →  Pass

 19%|█▉        | 149/765 [01:24<05:43,  1.79it/s]

[149/765]  raw='fail'  →  Fail

 20%|█▉        | 150/765 [01:24<05:27,  1.88it/s]

[150/765]  raw='fail.'  →  Fail

 20%|█▉        | 151/765 [01:25<05:22,  1.90it/s]

[151/765]  raw='pass'  →  Pass

 20%|█▉        | 152/765 [01:25<05:23,  1.89it/s]

[152/765]  raw='fail'  →  Fail

 20%|██        | 153/765 [01:26<05:14,  1.95it/s]

[153/765]  raw='fail.'  →  Fail

 20%|██        | 154/765 [01:26<05:08,  1.98it/s]

[154/765]  raw='fail'  →  Fail

 20%|██        | 155/765 [01:27<05:08,  1.98it/s]

[155/765]  raw='fail'  →  Fail

 20%|██        | 156/765 [01:27<05:12,  1.95it/s]

[156/765]  raw='pass'  →  Pass

 21%|██        | 157/765 [01:28<05:19,  1.90it/s]

[157/765]  raw='fail.'  →  Fail

 21%|██        | 158/765 [01:28<05:22,  1.88it/s]

[158/765]  raw='pass.'  →  Pass

 21%|██        | 159/765 [01:29<05:17,  1.91it/s]

[159/765]  raw='fail'  →  Fail

 21%|██        | 160/765 [01:29<05:16,  1.91it/s]

[160/765]  raw='fail'  →  Fail

 21%|██        | 161/765 [01:30<05:07,  1.97it/s]

[161/765]  raw='fail'  →  Fail

 21%|██        | 162/765 [01:30<04:47,  2.09it/s]

[162/765]  raw='fail'  →  Fail

 21%|██▏       | 163/765 [01:31<04:51,  2.07it/s]

[163/765]  raw='fail.'  →  Fail

 21%|██▏       | 164/765 [01:31<04:51,  2.06it/s]

[164/765]  raw='pass.'  →  Pass

 22%|██▏       | 165/765 [01:32<04:55,  2.03it/s]

[165/765]  raw='fail'  →  Fail

 22%|██▏       | 166/765 [01:32<04:52,  2.05it/s]

[166/765]  raw='fail.'  →  Fail

 22%|██▏       | 167/765 [01:33<04:45,  2.09it/s]

[167/765]  raw='fail'  →  Fail

 22%|██▏       | 168/765 [01:33<04:46,  2.08it/s]

[168/765]  raw='fail.'  →  Fail

 22%|██▏       | 169/765 [01:34<04:47,  2.07it/s]

[169/765]  raw='pass'  →  Pass

 22%|██▏       | 170/765 [01:34<04:47,  2.07it/s]

[170/765]  raw='pass.'  →  Pass

 22%|██▏       | 171/765 [01:35<04:55,  2.01it/s]

[171/765]  raw='pass'  →  Pass

 22%|██▏       | 172/765 [01:35<05:01,  1.97it/s]

[172/765]  raw='fail'  →  Fail

 23%|██▎       | 173/765 [01:36<05:13,  1.89it/s]

[173/765]  raw='pass'  →  Pass

 23%|██▎       | 174/765 [01:36<05:19,  1.85it/s]

[174/765]  raw='pass'  →  Pass

 23%|██▎       | 175/765 [01:37<05:05,  1.93it/s]

[175/765]  raw='fail'  →  Fail

 23%|██▎       | 176/765 [01:37<04:50,  2.03it/s]

[176/765]  raw='fail.'  →  Fail

 23%|██▎       | 177/765 [01:38<04:42,  2.08it/s]

[177/765]  raw='fail.'  →  Fail

 23%|██▎       | 178/765 [01:38<04:47,  2.04it/s]

[178/765]  raw='fail.'  →  Fail

 23%|██▎       | 179/765 [01:39<05:08,  1.90it/s]

[179/765]  raw='pass.'  →  Pass

 24%|██▎       | 180/765 [01:39<05:00,  1.95it/s]

[180/765]  raw='fail'  →  Fail

 24%|██▎       | 181/765 [01:40<04:45,  2.04it/s]

[181/765]  raw='fail'  →  Fail

 24%|██▍       | 182/765 [01:40<04:34,  2.12it/s]

[182/765]  raw='fail'  →  Fail

 24%|██▍       | 183/765 [01:40<04:26,  2.19it/s]

[183/765]  raw='fail'  →  Fail

 24%|██▍       | 184/765 [01:41<04:20,  2.23it/s]

[184/765]  raw='fail'  →  Fail

 24%|██▍       | 185/765 [01:41<04:24,  2.19it/s]

[185/765]  raw='fail'  →  Fail

 24%|██▍       | 186/765 [01:42<04:50,  1.99it/s]

[186/765]  raw='fail'  →  Fail

 24%|██▍       | 187/765 [01:42<04:55,  1.95it/s]

[187/765]  raw='fail.'  →  Fail

 25%|██▍       | 188/765 [01:43<04:49,  2.00it/s]

[188/765]  raw='fail'  →  Fail

 25%|██▍       | 189/765 [01:43<04:46,  2.01it/s]

[189/765]  raw='pass.'  →  Pass

 25%|██▍       | 190/765 [01:44<05:02,  1.90it/s]

[190/765]  raw='pass.'  →  Pass

 25%|██▍       | 191/765 [01:45<05:00,  1.91it/s]

[191/765]  raw='fail'  →  Fail

 25%|██▌       | 192/765 [01:45<05:15,  1.82it/s]

[192/765]  raw='pass'  →  Pass

 25%|██▌       | 193/765 [01:46<05:22,  1.77it/s]

[193/765]  raw='fail.'  →  Fail

 25%|██▌       | 194/765 [01:46<05:11,  1.83it/s]

[194/765]  raw='fail.'  →  Fail

 25%|██▌       | 195/765 [01:47<05:22,  1.77it/s]

[195/765]  raw='pass.'  →  Pass

 26%|██▌       | 196/765 [01:47<05:12,  1.82it/s]

[196/765]  raw='fail'  →  Fail

 26%|██▌       | 197/765 [01:48<05:11,  1.83it/s]

[197/765]  raw='pass.'  →  Pass

 26%|██▌       | 198/765 [01:48<05:03,  1.87it/s]

[198/765]  raw='fail'  →  Fail

 26%|██▌       | 199/765 [01:49<04:55,  1.92it/s]

[199/765]  raw='fail'  →  Fail

 26%|██▌       | 200/765 [01:49<04:41,  2.01it/s]

[200/765]  raw='fail'  →  Fail

 26%|██▋       | 201/765 [01:50<04:31,  2.08it/s]

[201/765]  raw='fail'  →  Fail

 26%|██▋       | 202/765 [01:50<04:34,  2.05it/s]

[202/765]  raw='pass.'  →  Pass

 27%|██▋       | 203/765 [01:51<04:36,  2.03it/s]

[203/765]  raw='fail.'  →  Fail

 27%|██▋       | 204/765 [01:51<04:32,  2.06it/s]

[204/765]  raw='fail.'  →  Fail

 27%|██▋       | 205/765 [01:52<04:29,  2.07it/s]

[205/765]  raw='fail.'  →  Fail

 27%|██▋       | 206/765 [01:52<04:25,  2.11it/s]

[206/765]  raw='fail'  →  Fail

 27%|██▋       | 207/765 [01:53<04:35,  2.02it/s]

[207/765]  raw='fail'  →  Fail

 27%|██▋       | 208/765 [01:53<05:08,  1.81it/s]

[208/765]  raw='pass.'  →  Pass

 27%|██▋       | 209/765 [01:54<05:06,  1.81it/s]

[209/765]  raw='fail'  →  Fail

 27%|██▋       | 210/765 [01:54<04:55,  1.88it/s]

[210/765]  raw='fail'  →  Fail

 28%|██▊       | 211/765 [01:55<04:43,  1.95it/s]

[211/765]  raw='fail'  →  Fail

 28%|██▊       | 212/765 [01:55<04:29,  2.05it/s]

[212/765]  raw='fail'  →  Fail

 28%|██▊       | 213/765 [01:56<04:28,  2.05it/s]

[213/765]  raw='pass.'  →  Pass

 28%|██▊       | 214/765 [01:56<04:23,  2.09it/s]

[214/765]  raw='fail.'  →  Fail

 28%|██▊       | 215/765 [01:57<04:23,  2.08it/s]

[215/765]  raw='fail'  →  Fail

 28%|██▊       | 216/765 [01:57<04:18,  2.13it/s]

[216/765]  raw='fail'  →  Fail

 28%|██▊       | 217/765 [01:58<04:10,  2.19it/s]

[217/765]  raw='fail'  →  Fail

 28%|██▊       | 218/765 [01:58<04:33,  2.00it/s]

[218/765]  raw='pass.'  →  Pass

 29%|██▊       | 219/765 [01:59<04:44,  1.92it/s]

[219/765]  raw='pass.'  →  Pass

 29%|██▉       | 220/765 [01:59<04:35,  1.98it/s]

[220/765]  raw='fail.'  →  Fail

 29%|██▉       | 221/765 [02:00<04:25,  2.05it/s]

[221/765]  raw='fail'  →  Fail

 29%|██▉       | 222/765 [02:00<04:21,  2.07it/s]

[222/765]  raw='fail'  →  Fail

 29%|██▉       | 223/765 [02:01<04:29,  2.01it/s]

[223/765]  raw='pass.'  →  Pass

 29%|██▉       | 224/765 [02:01<04:40,  1.93it/s]

[224/765]  raw='fail'  →  Fail

 29%|██▉       | 225/765 [02:02<04:41,  1.92it/s]

[225/765]  raw='fail'  →  Fail

 30%|██▉       | 226/765 [02:02<04:38,  1.94it/s]

[226/765]  raw='pass'  →  Pass

 30%|██▉       | 227/765 [02:03<04:32,  1.97it/s]

[227/765]  raw='fail'  →  Fail

 30%|██▉       | 228/765 [02:03<04:21,  2.06it/s]

[228/765]  raw='fail.'  →  Fail

 30%|██▉       | 229/765 [02:04<04:12,  2.12it/s]

[229/765]  raw='fail.'  →  Fail

 30%|███       | 230/765 [02:04<04:07,  2.16it/s]

[230/765]  raw='fail.'  →  Fail

 30%|███       | 231/765 [02:05<04:09,  2.14it/s]

[231/765]  raw='fail'  →  Fail

 30%|███       | 232/765 [02:05<04:17,  2.07it/s]

[232/765]  raw='pass'  →  Pass

 30%|███       | 233/765 [02:06<04:11,  2.12it/s]

[233/765]  raw='fail'  →  Fail

 31%|███       | 234/765 [02:06<04:06,  2.15it/s]

[234/765]  raw='fail'  →  Fail

 31%|███       | 235/765 [02:07<04:15,  2.07it/s]

[235/765]  raw='pass.'  →  Pass

 31%|███       | 236/765 [02:07<04:18,  2.04it/s]

[236/765]  raw='fail.'  →  Fail

 31%|███       | 237/765 [02:08<04:08,  2.13it/s]

[237/765]  raw='fail'  →  Fail

 31%|███       | 238/765 [02:08<03:59,  2.20it/s]

[238/765]  raw='fail'  →  Fail

 31%|███       | 239/765 [02:08<04:07,  2.13it/s]

[239/765]  raw='pass.'  →  Pass

 31%|███▏      | 240/765 [02:09<04:08,  2.11it/s]

[240/765]  raw='pass.'  →  Pass

 32%|███▏      | 241/765 [02:09<04:11,  2.08it/s]

[241/765]  raw='fail'  →  Fail

 32%|███▏      | 242/765 [02:10<04:11,  2.08it/s]

[242/765]  raw='pass.'  →  Pass

 32%|███▏      | 243/765 [02:10<04:05,  2.13it/s]

[243/765]  raw='fail.'  →  Fail

 32%|███▏      | 244/765 [02:11<03:57,  2.19it/s]

[244/765]  raw='fail'  →  Fail

 32%|███▏      | 245/765 [02:11<03:57,  2.19it/s]

[245/765]  raw='fail.'  →  Fail

 32%|███▏      | 246/765 [02:12<04:17,  2.01it/s]

[246/765]  raw='fail.'  →  Fail

 32%|███▏      | 247/765 [02:12<04:32,  1.90it/s]

[247/765]  raw='fail'  →  Fail

 32%|███▏      | 248/765 [02:13<04:25,  1.95it/s]

[248/765]  raw='fail'  →  Fail

 33%|███▎      | 249/765 [02:13<04:17,  2.00it/s]

[249/765]  raw='fail'  →  Fail

 33%|███▎      | 250/765 [02:14<04:12,  2.04it/s]

[250/765]  raw='fail'  →  Fail

 33%|███▎      | 251/765 [02:14<04:00,  2.14it/s]

[251/765]  raw='fail'  →  Fail

 33%|███▎      | 252/765 [02:15<03:57,  2.16it/s]

[252/765]  raw='fail'  →  Fail

 33%|███▎      | 253/765 [02:15<04:02,  2.11it/s]

[253/765]  raw='fail.'  →  Fail

 33%|███▎      | 254/765 [02:16<03:55,  2.17it/s]

[254/765]  raw='fail'  →  Fail

 33%|███▎      | 255/765 [02:16<04:05,  2.07it/s]

[255/765]  raw='fail'  →  Fail

 33%|███▎      | 256/765 [02:17<04:08,  2.05it/s]

[256/765]  raw='fail.'  →  Fail

 34%|███▎      | 257/765 [02:17<04:02,  2.09it/s]

[257/765]  raw='fail'  →  Fail

 34%|███▎      | 258/765 [02:18<03:59,  2.12it/s]

[258/765]  raw='fail.'  →  Fail

 34%|███▍      | 259/765 [02:18<03:50,  2.19it/s]

[259/765]  raw='fail'  →  Fail

 34%|███▍      | 260/765 [02:18<03:54,  2.15it/s]

[260/765]  raw='fail'  →  Fail

 34%|███▍      | 261/765 [02:19<03:52,  2.17it/s]

[261/765]  raw='fail'  →  Fail

 34%|███▍      | 262/765 [02:19<03:58,  2.11it/s]

[262/765]  raw='pass.'  →  Pass

 34%|███▍      | 263/765 [02:20<04:05,  2.05it/s]

[263/765]  raw='pass'  →  Pass

 35%|███▍      | 264/765 [02:20<04:00,  2.08it/s]

[264/765]  raw='fail.'  →  Fail

 35%|███▍      | 265/765 [02:21<04:02,  2.07it/s]

[265/765]  raw='pass'  →  Pass

 35%|███▍      | 266/765 [02:21<04:04,  2.04it/s]

[266/765]  raw='fail'  →  Fail

 35%|███▍      | 267/765 [02:22<04:10,  1.99it/s]

[267/765]  raw='pass'  →  Pass

 35%|███▌      | 268/765 [02:23<04:15,  1.95it/s]

[268/765]  raw='fail.'  →  Fail

 35%|███▌      | 269/765 [02:23<04:12,  1.97it/s]

[269/765]  raw='pass.'  →  Pass

 35%|███▌      | 270/765 [02:23<04:00,  2.06it/s]

[270/765]  raw='fail'  →  Fail

 35%|███▌      | 271/765 [02:24<03:49,  2.16it/s]

[271/765]  raw='fail'  →  Fail

 36%|███▌      | 272/765 [02:24<03:52,  2.12it/s]

[272/765]  raw='pass.'  →  Pass

 36%|███▌      | 273/765 [02:25<03:47,  2.16it/s]

[273/765]  raw='fail'  →  Fail

 36%|███▌      | 274/765 [02:25<03:48,  2.15it/s]

[274/765]  raw='pass.'  →  Pass

 36%|███▌      | 275/765 [02:26<04:00,  2.04it/s]

[275/765]  raw='pass'  →  Pass

 36%|███▌      | 276/765 [02:26<03:59,  2.04it/s]

[276/765]  raw='fail.'  →  Fail

 36%|███▌      | 277/765 [02:27<03:54,  2.08it/s]

[277/765]  raw='fail'  →  Fail

 36%|███▋      | 278/765 [02:27<03:52,  2.10it/s]

[278/765]  raw='fail'  →  Fail

 36%|███▋      | 279/765 [02:28<03:57,  2.05it/s]

[279/765]  raw='pass.'  →  Pass

 37%|███▋      | 280/765 [02:28<03:53,  2.08it/s]

[280/765]  raw='fail'  →  Fail

 37%|███▋      | 281/765 [02:29<04:00,  2.02it/s]

[281/765]  raw='pass'  →  Pass

 37%|███▋      | 282/765 [02:29<04:02,  1.99it/s]

[282/765]  raw='fail.'  →  Fail

 37%|███▋      | 283/765 [02:30<04:06,  1.96it/s]

[283/765]  raw='fail'  →  Fail

 37%|███▋      | 284/765 [02:30<04:02,  1.99it/s]

[284/765]  raw='fail'  →  Fail

 37%|███▋      | 285/765 [02:31<03:56,  2.03it/s]

[285/765]  raw='fail.'  →  Fail

 37%|███▋      | 286/765 [02:31<03:50,  2.08it/s]

[286/765]  raw='fail.'  →  Fail

 38%|███▊      | 287/765 [02:32<03:48,  2.09it/s]

[287/765]  raw='pass.'  →  Pass

 38%|███▊      | 288/765 [02:32<03:46,  2.11it/s]

[288/765]  raw='fail.'  →  Fail

 38%|███▊      | 289/765 [02:33<03:39,  2.17it/s]

[289/765]  raw='fail'  →  Fail

 38%|███▊      | 290/765 [02:33<03:37,  2.18it/s]

[290/765]  raw='fail.'  →  Fail

 38%|███▊      | 291/765 [02:33<03:35,  2.20it/s]

[291/765]  raw='fail'  →  Fail

 38%|███▊      | 292/765 [02:34<03:33,  2.22it/s]

[292/765]  raw='fail.'  →  Fail

 38%|███▊      | 293/765 [02:34<03:41,  2.13it/s]

[293/765]  raw='fail.'  →  Fail

 38%|███▊      | 294/765 [02:35<03:53,  2.01it/s]

[294/765]  raw='pass'  →  Pass

 39%|███▊      | 295/765 [02:35<03:53,  2.02it/s]

[295/765]  raw='fail.'  →  Fail

 39%|███▊      | 296/765 [02:36<03:50,  2.03it/s]

[296/765]  raw='pass.'  →  Pass

 39%|███▉      | 297/765 [02:36<03:49,  2.04it/s]

[297/765]  raw='pass.'  →  Pass

 39%|███▉      | 298/765 [02:37<03:51,  2.02it/s]

[298/765]  raw='pass.'  →  Pass

 39%|███▉      | 299/765 [02:37<03:58,  1.96it/s]

[299/765]  raw='pass'  →  Pass

 39%|███▉      | 300/765 [02:38<03:52,  2.00it/s]

[300/765]  raw='fail'  →  Fail

 39%|███▉      | 301/765 [02:38<03:41,  2.10it/s]

[301/765]  raw='fail'  →  Fail

 39%|███▉      | 302/765 [02:39<03:39,  2.11it/s]

[302/765]  raw='fail'  →  Fail

 40%|███▉      | 303/765 [02:39<03:52,  1.99it/s]

[303/765]  raw='pass'  →  Pass

 40%|███▉      | 304/765 [02:40<03:54,  1.97it/s]

[304/765]  raw='fail.'  →  Fail

 40%|███▉      | 305/765 [02:40<03:43,  2.06it/s]

[305/765]  raw='fail'  →  Fail

 40%|████      | 306/765 [02:41<03:34,  2.14it/s]

[306/765]  raw='fail'  →  Fail

 40%|████      | 307/765 [02:41<03:29,  2.19it/s]

[307/765]  raw='fail'  →  Fail

 40%|████      | 308/765 [02:42<03:24,  2.23it/s]

[308/765]  raw='fail'  →  Fail

 40%|████      | 309/765 [02:42<03:32,  2.15it/s]

[309/765]  raw='fail.'  →  Fail

 41%|████      | 310/765 [02:43<03:36,  2.10it/s]

[310/765]  raw='fail'  →  Fail

 41%|████      | 311/765 [02:43<03:35,  2.10it/s]

[311/765]  raw='fail.'  →  Fail

 41%|████      | 312/765 [02:44<03:37,  2.09it/s]

[312/765]  raw='fail.'  →  Fail

 41%|████      | 313/765 [02:44<03:33,  2.12it/s]

[313/765]  raw='fail.'  →  Fail

 41%|████      | 314/765 [02:45<03:40,  2.05it/s]

[314/765]  raw='pass.'  →  Pass

 41%|████      | 315/765 [02:45<03:38,  2.06it/s]

[315/765]  raw='fail'  →  Fail

 41%|████▏     | 316/765 [02:45<03:28,  2.16it/s]

[316/765]  raw='fail'  →  Fail

 41%|████▏     | 317/765 [02:46<03:28,  2.15it/s]

[317/765]  raw='pass.'  →  Pass

 42%|████▏     | 318/765 [02:46<03:28,  2.14it/s]

[318/765]  raw='fail'  →  Fail

 42%|████▏     | 319/765 [02:47<03:28,  2.14it/s]

[319/765]  raw='fail.'  →  Fail

 42%|████▏     | 320/765 [02:47<03:28,  2.13it/s]

[320/765]  raw='fail.'  →  Fail

 42%|████▏     | 321/765 [02:48<03:27,  2.14it/s]

[321/765]  raw='fail.'  →  Fail

 42%|████▏     | 322/765 [02:48<03:22,  2.19it/s]

[322/765]  raw='pass.'  →  Pass

 42%|████▏     | 323/765 [02:49<03:26,  2.14it/s]

[323/765]  raw='fail.'  →  Fail

 42%|████▏     | 324/765 [02:49<03:25,  2.14it/s]

[324/765]  raw='pass.'  →  Pass

 42%|████▏     | 325/765 [02:50<03:21,  2.18it/s]

[325/765]  raw='fail'  →  Fail

 43%|████▎     | 326/765 [02:50<03:31,  2.08it/s]

[326/765]  raw='pass'  →  Pass

 43%|████▎     | 327/765 [02:51<03:29,  2.09it/s]

[327/765]  raw='fail'  →  Fail

 43%|████▎     | 328/765 [02:51<03:26,  2.11it/s]

[328/765]  raw='fail.'  →  Fail

 43%|████▎     | 329/765 [02:52<03:23,  2.15it/s]

[329/765]  raw='fail'  →  Fail

 43%|████▎     | 330/765 [02:52<03:22,  2.15it/s]

[330/765]  raw='fail.'  →  Fail

 43%|████▎     | 331/765 [02:52<03:19,  2.17it/s]

[331/765]  raw='fail'  →  Fail

 43%|████▎     | 332/765 [02:53<03:17,  2.19it/s]

[332/765]  raw='fail'  →  Fail

 44%|████▎     | 333/765 [02:53<03:19,  2.17it/s]

[333/765]  raw='pass.'  →  Pass

 44%|████▎     | 334/765 [02:54<03:22,  2.13it/s]

[334/765]  raw='fail'  →  Fail

 44%|████▍     | 335/765 [02:54<03:20,  2.15it/s]

[335/765]  raw='fail'  →  Fail

 44%|████▍     | 336/765 [02:55<03:14,  2.20it/s]

[336/765]  raw='fail'  →  Fail

 44%|████▍     | 337/765 [02:55<03:16,  2.18it/s]

[337/765]  raw='pass.'  →  Pass

 44%|████▍     | 338/765 [02:56<03:22,  2.10it/s]

[338/765]  raw='fail'  →  Fail

 44%|████▍     | 339/765 [02:56<03:30,  2.02it/s]

[339/765]  raw='pass'  →  Pass

 44%|████▍     | 340/765 [02:57<03:33,  2.00it/s]

[340/765]  raw='fail'  →  Fail

 45%|████▍     | 341/765 [02:57<03:30,  2.02it/s]

[341/765]  raw='fail'  →  Fail

 45%|████▍     | 342/765 [02:58<03:31,  2.00it/s]

[342/765]  raw='pass'  →  Pass

 45%|████▍     | 343/765 [02:58<03:43,  1.89it/s]

[343/765]  raw='pass.'  →  Pass

 45%|████▍     | 344/765 [02:59<03:41,  1.90it/s]

[344/765]  raw='fail'  →  Fail

 45%|████▌     | 345/765 [02:59<03:39,  1.91it/s]

[345/765]  raw='pass.'  →  Pass

 45%|████▌     | 346/765 [03:00<03:39,  1.91it/s]

[346/765]  raw='fail'  →  Fail

 45%|████▌     | 347/765 [03:00<03:38,  1.92it/s]

[347/765]  raw='fail.'  →  Fail

 45%|████▌     | 348/765 [03:01<03:33,  1.96it/s]

[348/765]  raw='fail.'  →  Fail

 46%|████▌     | 349/765 [03:01<03:22,  2.05it/s]

[349/765]  raw='fail'  →  Fail

 46%|████▌     | 350/765 [03:02<03:13,  2.14it/s]

[350/765]  raw='fail'  →  Fail

 46%|████▌     | 351/765 [03:02<03:12,  2.15it/s]

[351/765]  raw='fail.'  →  Fail

 46%|████▌     | 352/765 [03:03<03:16,  2.11it/s]

[352/765]  raw='pass.'  →  Pass

 46%|████▌     | 353/765 [03:03<03:14,  2.12it/s]

[353/765]  raw='fail'  →  Fail

 46%|████▋     | 354/765 [03:04<03:09,  2.17it/s]

[354/765]  raw='fail'  →  Fail

 46%|████▋     | 355/765 [03:04<03:08,  2.17it/s]

[355/765]  raw='pass'  →  Pass

 47%|████▋     | 356/765 [03:05<03:12,  2.12it/s]

[356/765]  raw='fail'  →  Fail

 47%|████▋     | 357/765 [03:05<03:11,  2.13it/s]

[357/765]  raw='fail'  →  Fail

 47%|████▋     | 358/765 [03:06<03:10,  2.14it/s]

[358/765]  raw='fail'  →  Fail

 47%|████▋     | 359/765 [03:06<03:15,  2.07it/s]

[359/765]  raw='fail.'  →  Fail

 47%|████▋     | 360/765 [03:07<03:15,  2.07it/s]

[360/765]  raw='fail.'  →  Fail

 47%|████▋     | 361/765 [03:07<03:11,  2.11it/s]

[361/765]  raw='fail.'  →  Fail

 47%|████▋     | 362/765 [03:08<03:15,  2.07it/s]

[362/765]  raw='pass'  →  Pass

 47%|████▋     | 363/765 [03:08<03:13,  2.08it/s]

[363/765]  raw='fail'  →  Fail

 48%|████▊     | 364/765 [03:09<03:14,  2.06it/s]

[364/765]  raw='fail.'  →  Fail

 48%|████▊     | 365/765 [03:09<03:20,  2.00it/s]

[365/765]  raw='fail'  →  Fail

 48%|████▊     | 366/765 [03:10<03:18,  2.01it/s]

[366/765]  raw='fail.'  →  Fail

 48%|████▊     | 367/765 [03:10<03:15,  2.04it/s]

[367/765]  raw='fail.'  →  Fail

 48%|████▊     | 368/765 [03:10<03:10,  2.09it/s]

[368/765]  raw='fail'  →  Fail

 48%|████▊     | 369/765 [03:11<03:09,  2.09it/s]

[369/765]  raw='pass.'  →  Pass

 48%|████▊     | 370/765 [03:11<03:18,  1.99it/s]

[370/765]  raw='pass'  →  Pass

 48%|████▊     | 371/765 [03:12<03:20,  1.97it/s]

[371/765]  raw='fail.'  →  Fail

 49%|████▊     | 372/765 [03:12<03:11,  2.05it/s]

[372/765]  raw='fail'  →  Fail

 49%|████▉     | 373/765 [03:13<03:13,  2.03it/s]

[373/765]  raw='pass'  →  Pass

 49%|████▉     | 374/765 [03:14<03:20,  1.95it/s]

[374/765]  raw='pass.'  →  Pass

 49%|████▉     | 375/765 [03:14<03:22,  1.92it/s]

[375/765]  raw='pass'  →  Pass

 49%|████▉     | 376/765 [03:15<03:19,  1.95it/s]

[376/765]  raw='fail.'  →  Fail

 49%|████▉     | 377/765 [03:15<03:16,  1.98it/s]

[377/765]  raw='fail'  →  Fail

 49%|████▉     | 378/765 [03:16<03:18,  1.95it/s]

[378/765]  raw='pass'  →  Pass

 50%|████▉     | 379/765 [03:16<03:12,  2.01it/s]

[379/765]  raw='fail'  →  Fail

 50%|████▉     | 380/765 [03:16<03:01,  2.13it/s]

[380/765]  raw='fail'  →  Fail

 50%|████▉     | 381/765 [03:17<03:03,  2.09it/s]

[381/765]  raw='pass.'  →  Pass

 50%|████▉     | 382/765 [03:17<03:02,  2.10it/s]

[382/765]  raw='fail'  →  Fail

 50%|█████     | 383/765 [03:18<02:56,  2.17it/s]

[383/765]  raw='fail'  →  Fail

 50%|█████     | 384/765 [03:18<02:55,  2.17it/s]

[384/765]  raw='fail'  →  Fail

 50%|█████     | 385/765 [03:19<02:51,  2.22it/s]

[385/765]  raw='fail'  →  Fail

 50%|█████     | 386/765 [03:19<02:51,  2.21it/s]

[386/765]  raw='fail'  →  Fail

 51%|█████     | 387/765 [03:20<02:53,  2.18it/s]

[387/765]  raw='fail.'  →  Fail

 51%|█████     | 388/765 [03:20<02:53,  2.18it/s]

[388/765]  raw='fail'  →  Fail

 51%|█████     | 389/765 [03:21<02:58,  2.11it/s]

[389/765]  raw='fail.'  →  Fail

 51%|█████     | 390/765 [03:21<02:59,  2.08it/s]

[390/765]  raw='pass'  →  Pass

 51%|█████     | 391/765 [03:22<02:57,  2.11it/s]

[391/765]  raw='fail'  →  Fail

 51%|█████     | 392/765 [03:22<02:50,  2.19it/s]

[392/765]  raw='fail'  →  Fail

 51%|█████▏    | 393/765 [03:22<02:50,  2.18it/s]

[393/765]  raw='pass.'  →  Pass

 52%|█████▏    | 394/765 [03:23<03:05,  2.00it/s]

[394/765]  raw='pass'  →  Pass

 52%|█████▏    | 395/765 [03:24<03:12,  1.93it/s]

[395/765]  raw='fail.'  →  Fail

 52%|█████▏    | 396/765 [03:24<03:05,  1.99it/s]

[396/765]  raw='fail'  →  Fail

 52%|█████▏    | 397/765 [03:25<03:05,  1.98it/s]

[397/765]  raw='fail'  →  Fail

 52%|█████▏    | 398/765 [03:25<03:03,  2.00it/s]

[398/765]  raw='fail'  →  Fail

 52%|█████▏    | 399/765 [03:26<03:01,  2.02it/s]

[399/765]  raw='fail'  →  Fail

 52%|█████▏    | 400/765 [03:26<03:02,  2.01it/s]

[400/765]  raw='pass.'  →  Pass

 52%|█████▏    | 401/765 [03:27<03:00,  2.01it/s]

[401/765]  raw='fail.'  →  Fail

 53%|█████▎    | 402/765 [03:27<03:03,  1.98it/s]

[402/765]  raw='fail'  →  Fail

 53%|█████▎    | 403/765 [03:28<02:59,  2.02it/s]

[403/765]  raw='fail.'  →  Fail

 53%|█████▎    | 404/765 [03:28<02:51,  2.11it/s]

[404/765]  raw='pass'  →  Pass

 53%|█████▎    | 405/765 [03:28<02:47,  2.14it/s]

[405/765]  raw='fail.'  →  Fail

 53%|█████▎    | 406/765 [03:29<02:49,  2.12it/s]

[406/765]  raw='fail'  →  Fail

 53%|█████▎    | 407/765 [03:29<02:56,  2.03it/s]

[407/765]  raw='pass'  →  Pass

 53%|█████▎    | 408/765 [03:30<02:55,  2.04it/s]

[408/765]  raw='fail.'  →  Fail

 53%|█████▎    | 409/765 [03:30<02:50,  2.09it/s]

[409/765]  raw='pass.'  →  Pass

 54%|█████▎    | 410/765 [03:31<02:45,  2.14it/s]

[410/765]  raw='fail'  →  Fail

 54%|█████▎    | 411/765 [03:31<02:38,  2.23it/s]

[411/765]  raw='fail'  →  Fail

 54%|█████▍    | 412/765 [03:32<02:42,  2.18it/s]

[412/765]  raw='pass'  →  Pass

 54%|█████▍    | 413/765 [03:32<02:50,  2.07it/s]

[413/765]  raw='fail.'  →  Fail

 54%|█████▍    | 414/765 [03:33<02:53,  2.02it/s]

[414/765]  raw='fail'  →  Fail

 54%|█████▍    | 415/765 [03:33<02:49,  2.06it/s]

[415/765]  raw='fail'  →  Fail

 54%|█████▍    | 416/765 [03:34<02:42,  2.15it/s]

[416/765]  raw='fail'  →  Fail

 55%|█████▍    | 417/765 [03:34<02:37,  2.21it/s]

[417/765]  raw='fail'  →  Fail

 55%|█████▍    | 418/765 [03:35<02:34,  2.25it/s]

[418/765]  raw='fail'  →  Fail

 55%|█████▍    | 419/765 [03:35<02:37,  2.20it/s]

[419/765]  raw='fail.'  →  Fail

 55%|█████▍    | 420/765 [03:35<02:41,  2.14it/s]

[420/765]  raw='fail.'  →  Fail

 55%|█████▌    | 421/765 [03:36<02:38,  2.17it/s]

[421/765]  raw='fail'  →  Fail

 55%|█████▌    | 422/765 [03:36<02:43,  2.09it/s]

[422/765]  raw='pass'  →  Pass

 55%|█████▌    | 423/765 [03:37<02:50,  2.01it/s]

[423/765]  raw='pass'  →  Pass

 55%|█████▌    | 424/765 [03:37<02:43,  2.09it/s]

[424/765]  raw='fail'  →  Fail

 56%|█████▌    | 425/765 [03:38<02:38,  2.15it/s]

[425/765]  raw='fail'  →  Fail

 56%|█████▌    | 426/765 [03:38<02:42,  2.08it/s]

[426/765]  raw='fail'  →  Fail

 56%|█████▌    | 427/765 [03:39<02:56,  1.91it/s]

[427/765]  raw='pass.'  →  Pass

 56%|█████▌    | 428/765 [03:40<02:55,  1.92it/s]

[428/765]  raw='fail'  →  Fail

 56%|█████▌    | 429/765 [03:40<02:48,  1.99it/s]

[429/765]  raw='fail'  →  Fail

 56%|█████▌    | 430/765 [03:41<02:53,  1.93it/s]

[430/765]  raw='fail'  →  Fail

 56%|█████▋    | 431/765 [03:41<02:50,  1.96it/s]

[431/765]  raw='pass'  →  Pass

 56%|█████▋    | 432/765 [03:42<02:49,  1.97it/s]

[432/765]  raw='fail'  →  Fail

 57%|█████▋    | 433/765 [03:42<02:52,  1.93it/s]

[433/765]  raw='fail.'  →  Fail

 57%|█████▋    | 434/765 [03:43<02:45,  2.01it/s]

[434/765]  raw='fail'  →  Fail

 57%|█████▋    | 435/765 [03:43<02:41,  2.05it/s]

[435/765]  raw='pass.'  →  Pass

 57%|█████▋    | 436/765 [03:43<02:36,  2.11it/s]

[436/765]  raw='fail'  →  Fail

 57%|█████▋    | 437/765 [03:44<02:35,  2.11it/s]

[437/765]  raw='fail.'  →  Fail

 57%|█████▋    | 438/765 [03:44<02:28,  2.20it/s]

[438/765]  raw='fail'  →  Fail

 57%|█████▋    | 439/765 [03:45<02:27,  2.20it/s]

[439/765]  raw='pass.'  →  Pass

 58%|█████▊    | 440/765 [03:45<02:28,  2.19it/s]

[440/765]  raw='pass.'  →  Pass

 58%|█████▊    | 441/765 [03:46<02:29,  2.17it/s]

[441/765]  raw='pass'  →  Pass

 58%|█████▊    | 442/765 [03:46<02:30,  2.15it/s]

[442/765]  raw='fail.'  →  Fail

 58%|█████▊    | 443/765 [03:47<02:25,  2.21it/s]

[443/765]  raw='fail'  →  Fail

 58%|█████▊    | 444/765 [03:47<02:21,  2.27it/s]

[444/765]  raw='fail'  →  Fail

 58%|█████▊    | 445/765 [03:47<02:23,  2.23it/s]

[445/765]  raw='fail'  →  Fail

 58%|█████▊    | 446/765 [03:48<02:25,  2.19it/s]

[446/765]  raw='fail.'  →  Fail

 58%|█████▊    | 447/765 [03:48<02:28,  2.14it/s]

[447/765]  raw='fail'  →  Fail

 59%|█████▊    | 448/765 [03:49<02:28,  2.14it/s]

[448/765]  raw='pass.'  →  Pass

 59%|█████▊    | 449/765 [03:49<02:24,  2.19it/s]

[449/765]  raw='fail'  →  Fail

 59%|█████▉    | 450/765 [03:50<02:25,  2.16it/s]

[450/765]  raw='fail'  →  Fail

 59%|█████▉    | 451/765 [03:50<02:21,  2.21it/s]

[451/765]  raw='fail'  →  Fail

 59%|█████▉    | 452/765 [03:51<02:18,  2.26it/s]

[452/765]  raw='fail'  →  Fail

 59%|█████▉    | 453/765 [03:51<02:19,  2.23it/s]

[453/765]  raw='fail.'  →  Fail

 59%|█████▉    | 454/765 [03:52<02:21,  2.19it/s]

[454/765]  raw='fail.'  →  Fail

 59%|█████▉    | 455/765 [03:52<02:24,  2.14it/s]

[455/765]  raw='fail'  →  Fail

 60%|█████▉    | 456/765 [03:53<02:25,  2.12it/s]

[456/765]  raw='fail'  →  Fail

 60%|█████▉    | 457/765 [03:53<02:26,  2.10it/s]

[457/765]  raw='fail'  →  Fail

 60%|█████▉    | 458/765 [03:54<02:26,  2.10it/s]

[458/765]  raw='fail.'  →  Fail

 60%|██████    | 459/765 [03:54<02:26,  2.09it/s]

[459/765]  raw='fail.'  →  Fail

 60%|██████    | 460/765 [03:54<02:19,  2.18it/s]

[460/765]  raw='fail'  →  Fail

 60%|██████    | 461/765 [03:55<02:20,  2.17it/s]

[461/765]  raw='fail'  →  Fail

 60%|██████    | 462/765 [03:55<02:27,  2.06it/s]

[462/765]  raw='fail.'  →  Fail

 61%|██████    | 463/765 [03:56<02:24,  2.08it/s]

[463/765]  raw='fail'  →  Fail

 61%|██████    | 464/765 [03:56<02:19,  2.16it/s]

[464/765]  raw='fail'  →  Fail

 61%|██████    | 465/765 [03:57<02:20,  2.13it/s]

[465/765]  raw='fail'  →  Fail

 61%|██████    | 466/765 [03:57<02:20,  2.12it/s]

[466/765]  raw='fail.'  →  Fail

 61%|██████    | 467/765 [03:58<02:22,  2.10it/s]

[467/765]  raw='fail.'  →  Fail

 61%|██████    | 468/765 [03:58<02:21,  2.10it/s]

[468/765]  raw='fail'  →  Fail

 61%|██████▏   | 469/765 [03:59<02:19,  2.12it/s]

[469/765]  raw='fail.'  →  Fail

 61%|██████▏   | 470/765 [03:59<02:21,  2.08it/s]

[470/765]  raw='fail'  →  Fail

 62%|██████▏   | 471/765 [04:00<02:20,  2.09it/s]

[471/765]  raw='fail'  →  Fail

 62%|██████▏   | 472/765 [04:00<02:14,  2.17it/s]

[472/765]  raw='fail'  →  Fail

 62%|██████▏   | 473/765 [04:01<02:12,  2.21it/s]

[473/765]  raw='fail'  →  Fail

 62%|██████▏   | 474/765 [04:01<02:12,  2.20it/s]

[474/765]  raw='fail.'  →  Fail

 62%|██████▏   | 475/765 [04:01<02:12,  2.19it/s]

[475/765]  raw='fail'  →  Fail

 62%|██████▏   | 476/765 [04:02<02:11,  2.20it/s]

[476/765]  raw='fail'  →  Fail

 62%|██████▏   | 477/765 [04:02<02:11,  2.19it/s]

[477/765]  raw='fail'  →  Fail

 62%|██████▏   | 478/765 [04:03<02:08,  2.23it/s]

[478/765]  raw='fail'  →  Fail

 63%|██████▎   | 479/765 [04:03<02:09,  2.21it/s]

[479/765]  raw='fail.'  →  Fail

 63%|██████▎   | 480/765 [04:04<02:10,  2.18it/s]

[480/765]  raw='fail'  →  Fail

 63%|██████▎   | 481/765 [04:04<02:12,  2.14it/s]

[481/765]  raw='fail'  →  Fail

 63%|██████▎   | 482/765 [04:05<02:11,  2.15it/s]

[482/765]  raw='fail'  →  Fail

 63%|██████▎   | 483/765 [04:05<02:08,  2.20it/s]

[483/765]  raw='fail'  →  Fail

 63%|██████▎   | 484/765 [04:06<02:06,  2.23it/s]

[484/765]  raw='fail'  →  Fail

 63%|██████▎   | 485/765 [04:06<02:07,  2.20it/s]

[485/765]  raw='fail.'  →  Fail

 64%|██████▎   | 486/765 [04:07<02:11,  2.12it/s]

[486/765]  raw='pass'  →  Pass

 64%|██████▎   | 487/765 [04:07<02:09,  2.15it/s]

[487/765]  raw='fail'  →  Fail

 64%|██████▍   | 488/765 [04:07<02:08,  2.15it/s]

[488/765]  raw='pass'  →  Pass

 64%|██████▍   | 489/765 [04:08<02:10,  2.11it/s]

[489/765]  raw='fail.'  →  Fail

 64%|██████▍   | 490/765 [04:08<02:10,  2.10it/s]

[490/765]  raw='pass'  →  Pass

 64%|██████▍   | 491/765 [04:09<02:12,  2.07it/s]

[491/765]  raw='fail'  →  Fail

 64%|██████▍   | 492/765 [04:09<02:10,  2.09it/s]

[492/765]  raw='fail'  →  Fail

 64%|██████▍   | 493/765 [04:10<02:10,  2.08it/s]

[493/765]  raw='fail'  →  Fail

 65%|██████▍   | 494/765 [04:10<02:10,  2.07it/s]

[494/765]  raw='fail'  →  Fail

 65%|██████▍   | 495/765 [04:11<02:09,  2.09it/s]

[495/765]  raw='fail.'  →  Fail

 65%|██████▍   | 496/765 [04:11<02:07,  2.11it/s]

[496/765]  raw='fail'  →  Fail

 65%|██████▍   | 497/765 [04:12<02:09,  2.07it/s]

[497/765]  raw='pass.'  →  Pass

 65%|██████▌   | 498/765 [04:12<02:11,  2.04it/s]

[498/765]  raw='fail'  →  Fail

 65%|██████▌   | 499/765 [04:13<02:09,  2.05it/s]

[499/765]  raw='fail.'  →  Fail

 65%|██████▌   | 500/765 [04:13<02:05,  2.11it/s]

[500/765]  raw='fail'  →  Fail

 65%|██████▌   | 501/765 [04:14<02:01,  2.17it/s]

[501/765]  raw='fail'  →  Fail

 66%|██████▌   | 502/765 [04:14<02:02,  2.14it/s]

[502/765]  raw='fail.'  →  Fail

 66%|██████▌   | 503/765 [04:15<02:04,  2.10it/s]

[503/765]  raw='fail'  →  Fail

 66%|██████▌   | 504/765 [04:15<02:02,  2.13it/s]

[504/765]  raw='fail'  →  Fail

 66%|██████▌   | 505/765 [04:16<01:59,  2.18it/s]

[505/765]  raw='fail'  →  Fail

 66%|██████▌   | 506/765 [04:16<01:54,  2.26it/s]

[506/765]  raw='fail'  →  Fail

 66%|██████▋   | 507/765 [04:16<01:53,  2.28it/s]

[507/765]  raw='fail.'  →  Fail

 66%|██████▋   | 508/765 [04:17<01:58,  2.17it/s]

[508/765]  raw='pass.'  →  Pass

 67%|██████▋   | 509/765 [04:17<02:01,  2.10it/s]

[509/765]  raw='pass'  →  Pass

 67%|██████▋   | 510/765 [04:18<02:00,  2.11it/s]

[510/765]  raw='fail'  →  Fail

 67%|██████▋   | 511/765 [04:18<02:02,  2.07it/s]

[511/765]  raw='fail'  →  Fail

 67%|██████▋   | 512/765 [04:19<02:05,  2.01it/s]

[512/765]  raw='pass.'  →  Pass

 67%|██████▋   | 513/765 [04:19<02:05,  2.01it/s]

[513/765]  raw='fail.'  →  Fail

 67%|██████▋   | 514/765 [04:20<02:00,  2.08it/s]

[514/765]  raw='pass'  →  Pass

 67%|██████▋   | 515/765 [04:20<02:00,  2.08it/s]

[515/765]  raw='fail.'  →  Fail

 67%|██████▋   | 516/765 [04:21<02:03,  2.02it/s]

[516/765]  raw='pass'  →  Pass

 68%|██████▊   | 517/765 [04:21<02:02,  2.03it/s]

[517/765]  raw='fail.'  →  Fail

 68%|██████▊   | 518/765 [04:22<01:59,  2.06it/s]

[518/765]  raw='fail'  →  Fail

 68%|██████▊   | 519/765 [04:22<01:58,  2.08it/s]

[519/765]  raw='fail'  →  Fail

 68%|██████▊   | 520/765 [04:23<01:59,  2.05it/s]

[520/765]  raw='fail'  →  Fail

 68%|██████▊   | 521/765 [04:23<02:01,  2.01it/s]

[521/765]  raw='fail'  →  Fail

 68%|██████▊   | 522/765 [04:24<01:58,  2.06it/s]

[522/765]  raw='fail'  →  Fail

 68%|██████▊   | 523/765 [04:24<01:54,  2.11it/s]

[523/765]  raw='fail'  →  Fail

 68%|██████▊   | 524/765 [04:25<01:54,  2.11it/s]

[524/765]  raw='fail'  →  Fail

 69%|██████▊   | 525/765 [04:25<02:01,  1.97it/s]

[525/765]  raw='pass.'  →  Pass

 69%|██████▉   | 526/765 [04:26<02:00,  1.98it/s]

[526/765]  raw='fail'  →  Fail

 69%|██████▉   | 527/765 [04:26<01:55,  2.06it/s]

[527/765]  raw='fail'  →  Fail

 69%|██████▉   | 528/765 [04:27<01:53,  2.08it/s]

[528/765]  raw='fail'  →  Fail

 69%|██████▉   | 529/765 [04:27<01:54,  2.07it/s]

[529/765]  raw='fail.'  →  Fail

 69%|██████▉   | 530/765 [04:28<01:49,  2.15it/s]

[530/765]  raw='fail'  →  Fail

 69%|██████▉   | 531/765 [04:28<01:45,  2.21it/s]

[531/765]  raw='fail'  →  Fail

 70%|██████▉   | 532/765 [04:28<01:44,  2.23it/s]

[532/765]  raw='fail.'  →  Fail

 70%|██████▉   | 533/765 [04:29<01:44,  2.23it/s]

[533/765]  raw='pass.'  →  Pass

 70%|██████▉   | 534/765 [04:29<01:47,  2.15it/s]

[534/765]  raw='pass.'  →  Pass

 70%|██████▉   | 535/765 [04:30<01:50,  2.09it/s]

[535/765]  raw='pass.'  →  Pass

 70%|███████   | 536/765 [04:30<01:51,  2.06it/s]

[536/765]  raw='fail'  →  Fail

 70%|███████   | 537/765 [04:31<01:49,  2.08it/s]

[537/765]  raw='fail.'  →  Fail

 70%|███████   | 538/765 [04:31<01:46,  2.12it/s]

[538/765]  raw='fail.'  →  Fail

 70%|███████   | 539/765 [04:32<01:45,  2.13it/s]

[539/765]  raw='fail.'  →  Fail

 71%|███████   | 540/765 [04:32<01:47,  2.08it/s]

[540/765]  raw='fail.'  →  Fail

 71%|███████   | 541/765 [04:33<01:47,  2.09it/s]

[541/765]  raw='fail'  →  Fail

 71%|███████   | 542/765 [04:33<01:47,  2.07it/s]

[542/765]  raw='fail'  →  Fail

 71%|███████   | 543/765 [04:34<01:49,  2.02it/s]

[543/765]  raw='fail'  →  Fail

 71%|███████   | 544/765 [04:34<01:49,  2.02it/s]

[544/765]  raw='fail'  →  Fail

 71%|███████   | 545/765 [04:35<01:48,  2.02it/s]

[545/765]  raw='fail.'  →  Fail

 71%|███████▏  | 546/765 [04:35<01:46,  2.05it/s]

[546/765]  raw='fail.'  →  Fail

 72%|███████▏  | 547/765 [04:36<01:43,  2.11it/s]

[547/765]  raw='fail.'  →  Fail

 72%|███████▏  | 548/765 [04:36<01:46,  2.04it/s]

[548/765]  raw='pass'  →  Pass

 72%|███████▏  | 549/765 [04:37<01:46,  2.02it/s]

[549/765]  raw='fail'  →  Fail

 72%|███████▏  | 550/765 [04:37<01:46,  2.02it/s]

[550/765]  raw='fail'  →  Fail

 72%|███████▏  | 551/765 [04:38<01:44,  2.04it/s]

[551/765]  raw='fail.'  →  Fail

 72%|███████▏  | 552/765 [04:38<01:39,  2.13it/s]

[552/765]  raw='fail'  →  Fail

 72%|███████▏  | 553/765 [04:39<01:40,  2.10it/s]

[553/765]  raw='fail'  →  Fail

 72%|███████▏  | 554/765 [04:39<01:42,  2.07it/s]

[554/765]  raw='fail.'  →  Fail

 73%|███████▎  | 555/765 [04:40<01:42,  2.04it/s]

[555/765]  raw='fail.'  →  Fail

 73%|███████▎  | 556/765 [04:40<01:43,  2.02it/s]

[556/765]  raw='fail'  →  Fail

 73%|███████▎  | 557/765 [04:41<01:45,  1.97it/s]

[557/765]  raw='fail'  →  Fail

 73%|███████▎  | 558/765 [04:41<01:45,  1.97it/s]

[558/765]  raw='fail'  →  Fail

 73%|███████▎  | 559/765 [04:42<01:42,  2.00it/s]

[559/765]  raw='fail'  →  Fail

 73%|███████▎  | 560/765 [04:42<01:41,  2.01it/s]

[560/765]  raw='fail'  →  Fail

 73%|███████▎  | 561/765 [04:43<01:42,  1.99it/s]

[561/765]  raw='pass'  →  Pass

 73%|███████▎  | 562/765 [04:43<01:41,  2.00it/s]

[562/765]  raw='fail.'  →  Fail

 74%|███████▎  | 563/765 [04:44<01:37,  2.07it/s]

[563/765]  raw='fail'  →  Fail

 74%|███████▎  | 564/765 [04:44<01:33,  2.15it/s]

[564/765]  raw='fail'  →  Fail

 74%|███████▍  | 565/765 [04:44<01:33,  2.14it/s]

[565/765]  raw='pass'  →  Pass

 74%|███████▍  | 566/765 [04:45<01:36,  2.07it/s]

[566/765]  raw='fail.'  →  Fail

 74%|███████▍  | 567/765 [04:46<01:36,  2.04it/s]

[567/765]  raw='pass.'  →  Pass

 74%|███████▍  | 568/765 [04:46<01:38,  2.00it/s]

[568/765]  raw='fail'  →  Fail

 74%|███████▍  | 569/765 [04:46<01:35,  2.06it/s]

[569/765]  raw='fail'  →  Fail

 75%|███████▍  | 570/765 [04:47<01:30,  2.15it/s]

[570/765]  raw='fail'  →  Fail

 75%|███████▍  | 571/765 [04:47<01:29,  2.17it/s]

[571/765]  raw='fail'  →  Fail

 75%|███████▍  | 572/765 [04:48<01:30,  2.13it/s]

[572/765]  raw='pass.'  →  Pass

 75%|███████▍  | 573/765 [04:48<01:29,  2.14it/s]

[573/765]  raw='fail'  →  Fail

 75%|███████▌  | 574/765 [04:49<01:30,  2.10it/s]

[574/765]  raw='pass'  →  Pass

 75%|███████▌  | 575/765 [04:49<01:30,  2.10it/s]

[575/765]  raw='pass'  →  Pass

 75%|███████▌  | 576/765 [04:50<01:30,  2.09it/s]

[576/765]  raw='pass'  →  Pass

 75%|███████▌  | 577/765 [04:50<01:28,  2.13it/s]

[577/765]  raw='fail'  →  Fail

 76%|███████▌  | 578/765 [04:51<01:25,  2.18it/s]

[578/765]  raw='fail.'  →  Fail

 76%|███████▌  | 579/765 [04:51<01:25,  2.18it/s]

[579/765]  raw='fail'  →  Fail

 76%|███████▌  | 580/765 [04:52<01:27,  2.12it/s]

[580/765]  raw='pass.'  →  Pass

 76%|███████▌  | 581/765 [04:52<01:27,  2.11it/s]

[581/765]  raw='fail.'  →  Fail

 76%|███████▌  | 582/765 [04:53<01:26,  2.12it/s]

[582/765]  raw='fail'  →  Fail

 76%|███████▌  | 583/765 [04:53<01:23,  2.17it/s]

[583/765]  raw='fail'  →  Fail

 76%|███████▋  | 584/765 [04:54<01:26,  2.09it/s]

[584/765]  raw='pass.'  →  Pass

 76%|███████▋  | 585/765 [04:54<01:30,  1.99it/s]

[585/765]  raw='fail.'  →  Fail

 77%|███████▋  | 586/765 [04:55<01:30,  1.97it/s]

[586/765]  raw='fail'  →  Fail

 77%|███████▋  | 587/765 [04:55<01:27,  2.03it/s]

[587/765]  raw='fail'  →  Fail

 77%|███████▋  | 588/765 [04:55<01:24,  2.08it/s]

[588/765]  raw='fail'  →  Fail

 77%|███████▋  | 589/765 [04:56<01:25,  2.06it/s]

[589/765]  raw='fail'  →  Fail

 77%|███████▋  | 590/765 [04:56<01:24,  2.08it/s]

[590/765]  raw='pass.'  →  Pass

 77%|███████▋  | 591/765 [04:57<01:20,  2.15it/s]

[591/765]  raw='pass.'  →  Pass

 77%|███████▋  | 592/765 [04:57<01:18,  2.19it/s]

[592/765]  raw='fail'  →  Fail

 78%|███████▊  | 593/765 [04:58<01:17,  2.23it/s]

[593/765]  raw='pass.'  →  Pass

 78%|███████▊  | 594/765 [04:58<01:15,  2.25it/s]

[594/765]  raw='fail'  →  Fail

 78%|███████▊  | 595/765 [04:59<01:17,  2.19it/s]

[595/765]  raw='pass'  →  Pass

 78%|███████▊  | 596/765 [04:59<01:23,  2.01it/s]

[596/765]  raw='fail'  →  Fail

 78%|███████▊  | 597/765 [05:00<01:27,  1.92it/s]

[597/765]  raw='pass'  →  Pass

 78%|███████▊  | 598/765 [05:00<01:24,  1.98it/s]

[598/765]  raw='fail'  →  Fail

 78%|███████▊  | 599/765 [05:01<01:23,  2.00it/s]

[599/765]  raw='pass'  →  Pass

 78%|███████▊  | 600/765 [05:01<01:20,  2.04it/s]

[600/765]  raw='fail.'  →  Fail

 79%|███████▊  | 601/765 [05:02<01:18,  2.10it/s]

[601/765]  raw='fail'  →  Fail

 79%|███████▊  | 602/765 [05:02<01:18,  2.07it/s]

[602/765]  raw='pass'  →  Pass

 79%|███████▉  | 603/765 [05:03<01:20,  2.02it/s]

[603/765]  raw='fail'  →  Fail

 79%|███████▉  | 604/765 [05:03<01:19,  2.02it/s]

[604/765]  raw='fail'  →  Fail

 79%|███████▉  | 605/765 [05:04<01:19,  2.02it/s]

[605/765]  raw='pass'  →  Pass

 79%|███████▉  | 606/765 [05:04<01:16,  2.08it/s]

[606/765]  raw='fail'  →  Fail

 79%|███████▉  | 607/765 [05:05<01:15,  2.09it/s]

[607/765]  raw='fail.'  →  Fail

 79%|███████▉  | 608/765 [05:05<01:17,  2.04it/s]

[608/765]  raw='pass'  →  Pass

 80%|███████▉  | 609/765 [05:06<01:16,  2.03it/s]

[609/765]  raw='pass.'  →  Pass

 80%|███████▉  | 610/765 [05:06<01:16,  2.02it/s]

[610/765]  raw='pass.'  →  Pass

 80%|███████▉  | 611/765 [05:07<01:16,  2.02it/s]

[611/765]  raw='pass'  →  Pass

 80%|████████  | 612/765 [05:07<01:16,  2.01it/s]

[612/765]  raw='fail'  →  Fail

 80%|████████  | 613/765 [05:08<01:16,  2.00it/s]

[613/765]  raw='pass.'  →  Pass

 80%|████████  | 614/765 [05:08<01:15,  2.00it/s]

[614/765]  raw='fail'  →  Fail

 80%|████████  | 615/765 [05:09<01:12,  2.07it/s]

[615/765]  raw='fail'  →  Fail

 81%|████████  | 616/765 [05:09<01:10,  2.11it/s]

[616/765]  raw='fail.'  →  Fail

 81%|████████  | 617/765 [05:10<01:08,  2.15it/s]

[617/765]  raw='fail'  →  Fail

 81%|████████  | 618/765 [05:10<01:07,  2.17it/s]

[618/765]  raw='pass.'  →  Pass

 81%|████████  | 619/765 [05:10<01:06,  2.21it/s]

[619/765]  raw='fail.'  →  Fail

 81%|████████  | 620/765 [05:11<01:06,  2.18it/s]

[620/765]  raw='fail.'  →  Fail

 81%|████████  | 621/765 [05:11<01:09,  2.06it/s]

[621/765]  raw='pass'  →  Pass

 81%|████████▏ | 622/765 [05:12<01:12,  1.98it/s]

[622/765]  raw='fail'  →  Fail

 81%|████████▏ | 623/765 [05:12<01:11,  1.97it/s]

[623/765]  raw='pass.'  →  Pass

 82%|████████▏ | 624/765 [05:13<01:11,  1.96it/s]

[624/765]  raw='pass.'  →  Pass

 82%|████████▏ | 625/765 [05:13<01:08,  2.05it/s]

[625/765]  raw='fail.'  →  Fail

 82%|████████▏ | 626/765 [05:14<01:03,  2.18it/s]

[626/765]  raw='fail'  →  Fail

 82%|████████▏ | 627/765 [05:14<01:01,  2.23it/s]

[627/765]  raw='pass'  →  Pass

 82%|████████▏ | 628/765 [05:15<01:02,  2.18it/s]

[628/765]  raw='pass'  →  Pass

 82%|████████▏ | 629/765 [05:15<01:03,  2.15it/s]

[629/765]  raw='fail.'  →  Fail

 82%|████████▏ | 630/765 [05:16<01:04,  2.08it/s]

[630/765]  raw='pass'  →  Pass

 82%|████████▏ | 631/765 [05:16<01:10,  1.90it/s]

[631/765]  raw='fail'  →  Fail

 83%|████████▎ | 632/765 [05:17<01:11,  1.87it/s]

[632/765]  raw='pass.'  →  Pass

 83%|████████▎ | 633/765 [05:17<01:09,  1.89it/s]

[633/765]  raw='pass'  →  Pass

 83%|████████▎ | 634/765 [05:18<01:08,  1.91it/s]

[634/765]  raw='fail'  →  Fail

 83%|████████▎ | 635/765 [05:18<01:05,  1.97it/s]

[635/765]  raw='fail'  →  Fail

 83%|████████▎ | 636/765 [05:19<01:05,  1.98it/s]

[636/765]  raw='pass'  →  Pass

 83%|████████▎ | 637/765 [05:19<01:05,  1.96it/s]

[637/765]  raw='fail'  →  Fail

 83%|████████▎ | 638/765 [05:20<01:04,  1.97it/s]

[638/765]  raw='fail.'  →  Fail

 84%|████████▎ | 639/765 [05:20<01:02,  2.03it/s]

[639/765]  raw='fail.'  →  Fail

 84%|████████▎ | 640/765 [05:21<00:59,  2.08it/s]

[640/765]  raw='fail'  →  Fail

 84%|████████▍ | 641/765 [05:21<00:59,  2.10it/s]

[641/765]  raw='fail'  →  Fail

 84%|████████▍ | 642/765 [05:22<01:00,  2.02it/s]

[642/765]  raw='fail'  →  Fail

 84%|████████▍ | 643/765 [05:22<01:00,  2.03it/s]

[643/765]  raw='pass'  →  Pass

 84%|████████▍ | 644/765 [05:23<00:57,  2.10it/s]

[644/765]  raw='fail.'  →  Fail

 84%|████████▍ | 645/765 [05:23<00:55,  2.15it/s]

[645/765]  raw='fail'  →  Fail

 84%|████████▍ | 646/765 [05:24<00:55,  2.13it/s]

[646/765]  raw='pass'  →  Pass

 85%|████████▍ | 647/765 [05:24<01:00,  1.95it/s]

[647/765]  raw='pass'  →  Pass

 85%|████████▍ | 648/765 [05:25<01:00,  1.92it/s]

[648/765]  raw='fail.'  →  Fail

 85%|████████▍ | 649/765 [05:25<00:58,  1.98it/s]

[649/765]  raw='fail.'  →  Fail

 85%|████████▍ | 650/765 [05:26<00:57,  2.02it/s]

[650/765]  raw='fail'  →  Fail

 85%|████████▌ | 651/765 [05:26<00:55,  2.04it/s]

[651/765]  raw='fail.'  →  Fail

 85%|████████▌ | 652/765 [05:27<00:53,  2.12it/s]

[652/765]  raw='fail'  →  Fail

 85%|████████▌ | 653/765 [05:27<00:51,  2.16it/s]

[653/765]  raw='fail'  →  Fail

 85%|████████▌ | 654/765 [05:28<00:52,  2.13it/s]

[654/765]  raw='fail'  →  Fail

 86%|████████▌ | 655/765 [05:28<00:51,  2.13it/s]

[655/765]  raw='fail'  →  Fail

 86%|████████▌ | 656/765 [05:29<00:50,  2.17it/s]

[656/765]  raw='fail'  →  Fail

 86%|████████▌ | 657/765 [05:29<00:49,  2.18it/s]

[657/765]  raw='fail.'  →  Fail

 86%|████████▌ | 658/765 [05:29<00:48,  2.20it/s]

[658/765]  raw='fail.'  →  Fail

 86%|████████▌ | 659/765 [05:30<00:46,  2.27it/s]

[659/765]  raw='fail'  →  Fail

 86%|████████▋ | 660/765 [05:30<00:45,  2.30it/s]

[660/765]  raw='fail'  →  Fail

 86%|████████▋ | 661/765 [05:31<00:47,  2.18it/s]

[661/765]  raw='pass'  →  Pass

 87%|████████▋ | 662/765 [05:31<00:50,  2.06it/s]

[662/765]  raw='pass.'  →  Pass

 87%|████████▋ | 663/765 [05:32<00:48,  2.09it/s]

[663/765]  raw='fail'  →  Fail

 87%|████████▋ | 664/765 [05:32<00:47,  2.12it/s]

[664/765]  raw='fail'  →  Fail

 87%|████████▋ | 665/765 [05:33<00:46,  2.13it/s]

[665/765]  raw='fail'  →  Fail

 87%|████████▋ | 666/765 [05:33<00:47,  2.10it/s]

[666/765]  raw='pass.'  →  Pass

 87%|████████▋ | 667/765 [05:34<00:45,  2.13it/s]

[667/765]  raw='fail'  →  Fail

 87%|████████▋ | 668/765 [05:34<00:45,  2.15it/s]

[668/765]  raw='fail'  →  Fail

 87%|████████▋ | 669/765 [05:35<00:46,  2.07it/s]

[669/765]  raw='pass.'  →  Pass

 88%|████████▊ | 670/765 [05:35<00:47,  1.99it/s]

[670/765]  raw='fail'  →  Fail

 88%|████████▊ | 671/765 [05:36<00:48,  1.94it/s]

[671/765]  raw='pass'  →  Pass

 88%|████████▊ | 672/765 [05:36<00:48,  1.92it/s]

[672/765]  raw='pass'  →  Pass

 88%|████████▊ | 673/765 [05:37<00:46,  1.97it/s]

[673/765]  raw='fail'  →  Fail

 88%|████████▊ | 674/765 [05:37<00:46,  1.98it/s]

[674/765]  raw='fail'  →  Fail

 88%|████████▊ | 675/765 [05:38<00:46,  1.94it/s]

[675/765]  raw='pass.'  →  Pass

 88%|████████▊ | 676/765 [05:38<00:44,  1.98it/s]

[676/765]  raw='fail'  →  Fail

 88%|████████▊ | 677/765 [05:39<00:43,  2.01it/s]

[677/765]  raw='fail'  →  Fail

 89%|████████▊ | 678/765 [05:39<00:42,  2.07it/s]

[678/765]  raw='fail'  →  Fail

 89%|████████▉ | 679/765 [05:40<00:41,  2.09it/s]

[679/765]  raw='pass.'  →  Pass

 89%|████████▉ | 680/765 [05:40<00:41,  2.06it/s]

[680/765]  raw='fail'  →  Fail

 89%|████████▉ | 681/765 [05:41<00:41,  2.03it/s]

[681/765]  raw='pass.'  →  Pass

 89%|████████▉ | 682/765 [05:41<00:40,  2.05it/s]

[682/765]  raw='fail'  →  Fail

 89%|████████▉ | 683/765 [05:42<00:40,  2.04it/s]

[683/765]  raw='pass.'  →  Pass

 89%|████████▉ | 684/765 [05:42<00:39,  2.07it/s]

[684/765]  raw='pass.'  →  Pass

 90%|████████▉ | 685/765 [05:43<00:38,  2.07it/s]

[685/765]  raw='fail'  →  Fail

 90%|████████▉ | 686/765 [05:43<00:37,  2.08it/s]

[686/765]  raw='fail'  →  Fail

 90%|████████▉ | 687/765 [05:44<00:37,  2.08it/s]

[687/765]  raw='fail'  →  Fail

 90%|████████▉ | 688/765 [05:44<00:37,  2.06it/s]

[688/765]  raw='fail.'  →  Fail

 90%|█████████ | 689/765 [05:45<00:37,  2.04it/s]

[689/765]  raw='fail'  →  Fail

 90%|█████████ | 690/765 [05:45<00:36,  2.05it/s]

[690/765]  raw='pass.'  →  Pass

 90%|█████████ | 691/765 [05:45<00:35,  2.08it/s]

[691/765]  raw='fail.'  →  Fail

 90%|█████████ | 692/765 [05:46<00:34,  2.13it/s]

[692/765]  raw='fail.'  →  Fail

 91%|█████████ | 693/765 [05:46<00:35,  2.05it/s]

[693/765]  raw='pass'  →  Pass

 91%|█████████ | 694/765 [05:47<00:34,  2.05it/s]

[694/765]  raw='pass.'  →  Pass

 91%|█████████ | 695/765 [05:47<00:33,  2.10it/s]

[695/765]  raw='fail.'  →  Fail

 91%|█████████ | 696/765 [05:48<00:32,  2.14it/s]

[696/765]  raw='fail.'  →  Fail

 91%|█████████ | 697/765 [05:48<00:32,  2.10it/s]

[697/765]  raw='pass.'  →  Pass

 91%|█████████ | 698/765 [05:49<00:31,  2.11it/s]

[698/765]  raw='fail'  →  Fail

 91%|█████████▏| 699/765 [05:49<00:30,  2.15it/s]

[699/765]  raw='fail.'  →  Fail

 92%|█████████▏| 700/765 [05:50<00:29,  2.21it/s]

[700/765]  raw='fail'  →  Fail

 92%|█████████▏| 701/765 [05:50<00:28,  2.23it/s]

[701/765]  raw='fail'  →  Fail

 92%|█████████▏| 702/765 [05:51<00:27,  2.29it/s]

[702/765]  raw='fail'  →  Fail

 92%|█████████▏| 703/765 [05:51<00:27,  2.25it/s]

[703/765]  raw='pass.'  →  Pass

 92%|█████████▏| 704/765 [05:51<00:27,  2.21it/s]

[704/765]  raw='pass.'  →  Pass

 92%|█████████▏| 705/765 [05:52<00:27,  2.22it/s]

[705/765]  raw='fail.'  →  Fail

 92%|█████████▏| 706/765 [05:52<00:26,  2.26it/s]

[706/765]  raw='fail'  →  Fail

 92%|█████████▏| 707/765 [05:53<00:26,  2.17it/s]

[707/765]  raw='pass'  →  Pass

 93%|█████████▎| 708/765 [05:53<00:27,  2.11it/s]

[708/765]  raw='fail'  →  Fail

 93%|█████████▎| 709/765 [05:54<00:26,  2.13it/s]

[709/765]  raw='fail.'  →  Fail

 93%|█████████▎| 710/765 [05:54<00:25,  2.12it/s]

[710/765]  raw='pass.'  →  Pass

 93%|█████████▎| 711/765 [05:55<00:24,  2.16it/s]

[711/765]  raw='fail'  →  Fail

 93%|█████████▎| 712/765 [05:55<00:24,  2.15it/s]

[712/765]  raw='fail'  →  Fail

 93%|█████████▎| 713/765 [05:56<00:25,  2.07it/s]

[713/765]  raw='fail.'  →  Fail

 93%|█████████▎| 714/765 [05:56<00:24,  2.07it/s]

[714/765]  raw='pass.'  →  Pass

 93%|█████████▎| 715/765 [05:57<00:23,  2.16it/s]

[715/765]  raw='fail'  →  Fail

 94%|█████████▎| 716/765 [05:57<00:21,  2.25it/s]

[716/765]  raw='fail'  →  Fail

 94%|█████████▎| 717/765 [05:57<00:21,  2.21it/s]

[717/765]  raw='pass.'  →  Pass

 94%|█████████▍| 718/765 [05:58<00:21,  2.19it/s]

[718/765]  raw='fail'  →  Fail

 94%|█████████▍| 719/765 [05:58<00:21,  2.19it/s]

[719/765]  raw='fail.'  →  Fail

 94%|█████████▍| 720/765 [05:59<00:20,  2.18it/s]

[720/765]  raw='fail.'  →  Fail

 94%|█████████▍| 721/765 [05:59<00:20,  2.14it/s]

[721/765]  raw='fail.'  →  Fail

 94%|█████████▍| 722/765 [06:00<00:20,  2.10it/s]

[722/765]  raw='fail'  →  Fail

 95%|█████████▍| 723/765 [06:00<00:19,  2.14it/s]

[723/765]  raw='fail'  →  Fail

 95%|█████████▍| 724/765 [06:01<00:18,  2.24it/s]

[724/765]  raw='fail'  →  Fail

 95%|█████████▍| 725/765 [06:01<00:17,  2.27it/s]

[725/765]  raw='fail.'  →  Fail

 95%|█████████▍| 726/765 [06:02<00:17,  2.27it/s]

[726/765]  raw='pass'  →  Pass

 95%|█████████▌| 727/765 [06:02<00:17,  2.23it/s]

[727/765]  raw='fail'  →  Fail

 95%|█████████▌| 728/765 [06:02<00:16,  2.24it/s]

[728/765]  raw='fail.'  →  Fail

 95%|█████████▌| 729/765 [06:03<00:16,  2.18it/s]

[729/765]  raw='pass.'  →  Pass

 95%|█████████▌| 730/765 [06:03<00:16,  2.18it/s]

[730/765]  raw='fail.'  →  Fail

 96%|█████████▌| 731/765 [06:04<00:15,  2.23it/s]

[731/765]  raw='fail'  →  Fail

 96%|█████████▌| 732/765 [06:04<00:15,  2.13it/s]

[732/765]  raw='pass'  →  Pass

 96%|█████████▌| 733/765 [06:05<00:15,  2.12it/s]

[733/765]  raw='fail'  →  Fail

 96%|█████████▌| 734/765 [06:05<00:14,  2.08it/s]

[734/765]  raw='fail'  →  Fail

 96%|█████████▌| 735/765 [06:06<00:14,  2.14it/s]

[735/765]  raw='fail'  →  Fail

 96%|█████████▌| 736/765 [06:06<00:13,  2.16it/s]

[736/765]  raw='fail'  →  Fail

 96%|█████████▋| 737/765 [06:07<00:13,  2.09it/s]

[737/765]  raw='fail.'  →  Fail

 96%|█████████▋| 738/765 [06:07<00:13,  2.07it/s]

[738/765]  raw='pass.'  →  Pass

 97%|█████████▋| 739/765 [06:08<00:12,  2.10it/s]

[739/765]  raw='fail'  →  Fail

 97%|█████████▋| 740/765 [06:08<00:11,  2.15it/s]

[740/765]  raw='fail.'  →  Fail

 97%|█████████▋| 741/765 [06:09<00:11,  2.17it/s]

[741/765]  raw='fail'  →  Fail

 97%|█████████▋| 742/765 [06:09<00:10,  2.16it/s]

[742/765]  raw='pass.'  →  Pass

 97%|█████████▋| 743/765 [06:10<00:10,  2.15it/s]

[743/765]  raw='fail'  →  Fail

 97%|█████████▋| 744/765 [06:10<00:09,  2.11it/s]

[744/765]  raw='pass.'  →  Pass

 97%|█████████▋| 745/765 [06:10<00:09,  2.14it/s]

[745/765]  raw='fail'  →  Fail

 98%|█████████▊| 746/765 [06:11<00:08,  2.12it/s]

[746/765]  raw='pass.'  →  Pass

 98%|█████████▊| 747/765 [06:11<00:08,  2.08it/s]

[747/765]  raw='fail.'  →  Fail

 98%|█████████▊| 748/765 [06:12<00:08,  2.07it/s]

[748/765]  raw='fail'  →  Fail

 98%|█████████▊| 749/765 [06:12<00:07,  2.10it/s]

[749/765]  raw='fail.'  →  Fail

 98%|█████████▊| 750/765 [06:13<00:06,  2.17it/s]

[750/765]  raw='fail'  →  Fail

 98%|█████████▊| 751/765 [06:13<00:06,  2.21it/s]

[751/765]  raw='fail'  →  Fail

 98%|█████████▊| 752/765 [06:14<00:06,  2.16it/s]

[752/765]  raw='pass'  →  Pass

 98%|█████████▊| 753/765 [06:14<00:05,  2.18it/s]

[753/765]  raw='fail'  →  Fail

 99%|█████████▊| 754/765 [06:15<00:04,  2.20it/s]

[754/765]  raw='fail.'  →  Fail

 99%|█████████▊| 755/765 [06:15<00:04,  2.17it/s]

[755/765]  raw='pass'  →  Pass

 99%|█████████▉| 756/765 [06:16<00:04,  2.06it/s]

[756/765]  raw='pass.'  →  Pass

 99%|█████████▉| 757/765 [06:16<00:03,  2.05it/s]

[757/765]  raw='fail'  →  Fail

 99%|█████████▉| 758/765 [06:17<00:03,  2.06it/s]

[758/765]  raw='pass.'  →  Pass

 99%|█████████▉| 759/765 [06:17<00:02,  2.03it/s]

[759/765]  raw='fail.'  →  Fail

 99%|█████████▉| 760/765 [06:18<00:02,  2.01it/s]

[760/765]  raw='fail'  →  Fail

 99%|█████████▉| 761/765 [06:18<00:02,  1.99it/s]

[761/765]  raw='fail.'  →  Fail

100%|█████████▉| 762/765 [06:19<00:01,  1.99it/s]

[762/765]  raw='fail'  →  Fail

100%|█████████▉| 763/765 [06:19<00:01,  1.98it/s]

[763/765]  raw='fail'  →  Fail

100%|█████████▉| 764/765 [06:20<00:00,  1.92it/s]

[764/765]  raw='pass.'  →  Pass

100%|██████████| 765/765 [06:20<00:00,  2.01it/s]

[765/765]  raw='fail'  →  Fail

In [ ]:
# Evaluate
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         0       0      fail         Fail         Fail
1         0       0      fail         Fail         Fail
2         0       0      fail         Fail         Fail
3         1       1      pass         Pass         Pass
4         0       0      fail         Fail         Fail
5         0       0      fail         Fail         Fail
6         1       1     pass.         Pass         Pass
7         1       0      fail         Pass         Fail
8         1       1     pass.         Pass         Pass
9         0       0      fail         Fail         Fail
10        0       0      fail         Fail         Fail
11        1       1      pass         Pass         Pass
12        1       0      fail         Pass         Fail
13        1       1      pass         Pass         Pass
14        1       0      fail         Pass         Fail
15        1       1      pass         Pass         Pass
16        1       0      fail         Pass         Fail
17        1       1     pass.         Pass         Pass
18        0       0     fail.         Fail         Fail
19        0       1      pass         Fail         Pass
20        0       0      fail         Fail         Fail
21        0       0      fail         Fail         Fail
22        0       0      fail         Fail         Fail
23        1       1      pass         Pass         Pass
24        1       1     pass.         Pass         Pass
25        1       0      fail         Pass         Fail
26        0       0      fail         Fail         Fail
27        1       0     fail.         Pass         Fail
28        1       0      fail         Pass         Fail
29        0       0      fail         Fail         Fail
30        1       1     pass.         Pass         Pass
31        0       0     fail.         Fail         Fail
32        1       0     fail.         Pass         Fail
33        0       0     fail.         Fail         Fail
34        0       0     fail.         Fail         Fail
35        1       0      fail         Pass         Fail
36        1       1     pass.         Pass         Pass
37        0       1     pass.         Fail         Pass
38        1       0      fail         Pass         Fail
39        1       1     pass.         Pass         Pass
40        1       1     pass.         Pass         Pass
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        1       1     pass.         Pass         Pass
44        0       0      fail         Fail         Fail
45        0       0     fail.         Fail         Fail
46        0       1     pass.         Fail         Pass
47        1       0      fail         Pass         Fail
48        0       0      fail         Fail         Fail
49        1       0      fail         Pass         Fail
50        0       0      fail         Fail         Fail
51        0       0     fail.         Fail         Fail
52        1       0     fail.         Pass         Fail
53        1       1     pass.         Pass         Pass
54        0       0      fail         Fail         Fail
55        0       0      fail         Fail         Fail
56        0       0      fail         Fail         Fail
57        0       0      fail         Fail         Fail
58        0       0      fail         Fail         Fail
59        0       0      fail         Fail         Fail
60        1       1      pass         Pass         Pass
61        0       0      fail         Fail         Fail
62        1       1     pass.         Pass         Pass
63        0       0      fail         Fail         Fail
64        0       0     fail.         Fail         Fail
65        1       0      fail         Pass         Fail
66        1       1      pass         Pass         Pass
67        0       0      fail         Fail         Fail
68        1       0     fail.         Pass         Fail
69        0       0     fail.         Fail         Fail
70        0       1     pass.         Fail         Pass
71        0       0      fail         Fail         Fail
72        0       0     fail.         Fail         Fail
73        0       0      fail         Fail         Fail
74        0       0      fail         Fail         Fail
75        1       0      fail         Pass         Fail
76        0       0      fail         Fail         Fail
77        1       1     pass.         Pass         Pass
78        0       0     fail.         Fail         Fail
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        1       1     pass.         Pass         Pass
82        1       1      pass         Pass         Pass
83        1       1      pass         Pass         Pass
84        0       0      fail         Fail         Fail
85        0       0     fail.         Fail         Fail
86        0       1     pass.         Fail         Pass
87        0       0      fail         Fail         Fail
88        1       1     pass.         Pass         Pass
89        0       0      fail         Fail         Fail
90        1       1     pass.         Pass         Pass
91        1       0      fail         Pass         Fail
92        1       1     pass.         Pass         Pass
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       0      fail         Fail         Fail
96        0       0      fail         Fail         Fail
97        0       0     fail.         Fail         Fail
98        0       0      fail         Fail         Fail
99        0       0     fail.         Fail         Fail
100       0       1     pass.         Fail         Pass
101       0       1     pass.         Fail         Pass
102       0       0      fail         Fail         Fail
103       0       0      fail         Fail         Fail
104       0       0      fail         Fail         Fail
105       1       1      pass         Pass         Pass
106       1       1      pass         Pass         Pass
107       0       0     fail.         Fail         Fail
108       1       1     pass.         Pass         Pass
109       0       1     pass.         Fail         Pass
110       0       0     fail.         Fail         Fail
111       0       0      fail         Fail         Fail
112       1       1     pass.         Pass         Pass
113       0       0     fail.         Fail         Fail
114       0       0      fail         Fail         Fail
115       0       0      fail         Fail         Fail
116       1       0      fail         Pass         Fail
117       1       1     pass.         Pass         Pass
118       0       1     pass.         Fail         Pass
119       1       0      fail         Pass         Fail
120       1       0      fail         Pass         Fail
121       1       0      fail         Pass         Fail
122       1       1     pass.         Pass         Pass
123       1       0      fail         Pass         Fail
124       0       0     fail.         Fail         Fail
125       0       0      fail         Fail         Fail
126       0       0      fail         Fail         Fail
127       0       0     fail.         Fail         Fail
128       0       0      fail         Fail         Fail
129       1       1     pass.         Pass         Pass
130       0       0      fail         Fail         Fail
131       0       0     fail.         Fail         Fail
132       0       0      fail         Fail         Fail
133       0       0      fail         Fail         Fail
134       0       1     pass.         Fail         Pass
135       0       0     fail.         Fail         Fail
136       1       1     pass.         Pass         Pass
137       1       0     fail.         Pass         Fail
138       1       1      pass         Pass         Pass
139       0       0     fail.         Fail         Fail
140       0       0     fail.         Fail         Fail
141       0       0      fail         Fail         Fail
142       1       1     pass.         Pass         Pass
143       1       1     pass.         Pass         Pass
144       0       0     fail.         Fail         Fail
145       1       0      fail         Pass         Fail
146       1       0      fail         Pass         Fail
147       1       1     pass.         Pass         Pass
148       1       0      fail         Pass         Fail
149       0       0     fail.         Fail         Fail
150       1       1      pass         Pass         Pass
151       0       0      fail         Fail         Fail
152       1       0     fail.         Pass         Fail
153       0       0      fail         Fail         Fail
154       0       0      fail         Fail         Fail
155       1       1      pass         Pass         Pass
156       0       0     fail.         Fail         Fail
157       1       1     pass.         Pass         Pass
158       1       0      fail         Pass         Fail
159       1       0      fail         Pass         Fail
160       0       0      fail         Fail         Fail
161       0       0      fail         Fail         Fail
162       0       0     fail.         Fail         Fail
163       1       1     pass.         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0     fail.         Fail         Fail
166       0       0      fail         Fail         Fail
167       0       0     fail.         Fail         Fail
168       1       1      pass         Pass         Pass
169       1       1     pass.         Pass         Pass
170       1       1      pass         Pass         Pass
171       1       0      fail         Pass         Fail
172       1       1      pass         Pass         Pass
173       1       1      pass         Pass         Pass
174       0       0      fail         Fail         Fail
175       0       0     fail.         Fail         Fail
176       0       0     fail.         Fail         Fail
177       0       0     fail.         Fail         Fail
178       1       1     pass.         Pass         Pass
179       0       0      fail         Fail         Fail
180       0       0      fail         Fail         Fail
181       0       0      fail         Fail         Fail
182       0       0      fail         Fail         Fail
183       0       0      fail         Fail         Fail
184       1       0      fail         Pass         Fail
185       1       0      fail         Pass         Fail
186       0       0     fail.         Fail         Fail
187       0       0      fail         Fail         Fail
188       1       1     pass.         Pass         Pass
189       1       1     pass.         Pass         Pass
190       0       0      fail         Fail         Fail
191       1       1      pass         Pass         Pass
192       0       0     fail.         Fail         Fail
193       0       0     fail.         Fail         Fail
194       1       1     pass.         Pass         Pass
195       0       0      fail         Fail         Fail
196       1       1     pass.         Pass         Pass
197       0       0      fail         Fail         Fail
198       1       0      fail         Pass         Fail
199       0       0      fail         Fail         Fail
200       0       0      fail         Fail         Fail
201       1       1     pass.         Pass         Pass
202       0       0     fail.         Fail         Fail
203       1       0     fail.         Pass         Fail
204       0       0     fail.         Fail         Fail
205       0       0      fail         Fail         Fail
206       1       0      fail         Pass         Fail
207       0       1     pass.         Fail         Pass
208       0       0      fail         Fail         Fail
209       0       0      fail         Fail         Fail
210       0       0      fail         Fail         Fail
211       0       0      fail         Fail         Fail
212       1       1     pass.         Pass         Pass
213       0       0     fail.         Fail         Fail
214       0       0      fail         Fail         Fail
215       0       0      fail         Fail         Fail
216       0       0      fail         Fail         Fail
217       1       1     pass.         Pass         Pass
218       1       1     pass.         Pass         Pass
219       0       0     fail.         Fail         Fail
220       0       0      fail         Fail         Fail
221       0       0      fail         Fail         Fail
222       1       1     pass.         Pass         Pass
223       1       0      fail         Pass         Fail
224       0       0      fail         Fail         Fail
225       1       1      pass         Pass         Pass
226       0       0      fail         Fail         Fail
227       0       0     fail.         Fail         Fail
228       0       0     fail.         Fail         Fail
229       0       0     fail.         Fail         Fail
230       1       0      fail         Pass         Fail
231       1       1      pass         Pass         Pass
232       0       0      fail         Fail         Fail
233       0       0      fail         Fail         Fail
234       1       1     pass.         Pass         Pass
235       0       0     fail.         Fail         Fail
236       0       0      fail         Fail         Fail
237       0       0      fail         Fail         Fail
238       1       1     pass.         Pass         Pass
239       0       1     pass.         Fail         Pass
240       0       0      fail         Fail         Fail
241       0       1     pass.         Fail         Pass
242       0       0     fail.         Fail         Fail
243       0       0      fail         Fail         Fail
244       0       0     fail.         Fail         Fail
245       1       0     fail.         Pass         Fail
246       1       0      fail         Pass         Fail
247       0       0      fail         Fail         Fail
248       1       0      fail         Pass         Fail
249       0       0      fail         Fail         Fail
250       0       0      fail         Fail         Fail
251       1       0      fail         Pass         Fail
252       1       0     fail.         Pass         Fail
253       0       0      fail         Fail         Fail
254       1       0      fail         Pass         Fail
255       0       0     fail.         Fail         Fail
256       1       0      fail         Pass         Fail
257       0       0     fail.         Fail         Fail
258       0       0      fail         Fail         Fail
259       1       0      fail         Pass         Fail
260       0       0      fail         Fail         Fail
261       1       1     pass.         Pass         Pass
262       1       1      pass         Pass         Pass
263       0       0     fail.         Fail         Fail
264       1       1      pass         Pass         Pass
265       1       0      fail         Pass         Fail
266       1       1      pass         Pass         Pass
267       1       0     fail.         Pass         Fail
268       1       1     pass.         Pass         Pass
269       0       0      fail         Fail         Fail
270       0       0      fail         Fail         Fail
271       1       1     pass.         Pass         Pass
272       0       0      fail         Fail         Fail
273       1       1     pass.         Pass         Pass
274       1       1      pass         Pass         Pass
275       0       0     fail.         Fail         Fail
276       0       0      fail         Fail         Fail
277       0       0      fail         Fail         Fail
278       1       1     pass.         Pass         Pass
279       0       0      fail         Fail         Fail
280       1       1      pass         Pass         Pass
281       0       0     fail.         Fail         Fail
282       1       0      fail         Pass         Fail
283       0       0      fail         Fail         Fail
284       0       0     fail.         Fail         Fail
285       1       0     fail.         Pass         Fail
286       0       1     pass.         Fail         Pass
287       1       0     fail.         Pass         Fail
288       0       0      fail         Fail         Fail
289       0       0     fail.         Fail         Fail
290       0       0      fail         Fail         Fail
291       0       0     fail.         Fail         Fail
292       1       0     fail.         Pass         Fail
293       1       1      pass         Pass         Pass
294       0       0     fail.         Fail         Fail
295       1       1     pass.         Pass         Pass
296       1       1     pass.         Pass         Pass
297       1       1     pass.         Pass         Pass
298       1       1      pass         Pass         Pass
299       0       0      fail         Fail         Fail
300       0       0      fail         Fail         Fail
301       0       0      fail         Fail         Fail
302       1       1      pass         Pass         Pass
303       0       0     fail.         Fail         Fail
304       0       0      fail         Fail         Fail
305       0       0      fail         Fail         Fail
306       0       0      fail         Fail         Fail
307       0       0      fail         Fail         Fail
308       1       0     fail.         Pass         Fail
309       0       0      fail         Fail         Fail
310       0       0     fail.         Fail         Fail
311       0       0     fail.         Fail         Fail
312       1       0     fail.         Pass         Fail
313       1       1     pass.         Pass         Pass
314       0       0      fail         Fail         Fail
315       0       0      fail         Fail         Fail
316       0       1     pass.         Fail         Pass
317       0       0      fail         Fail         Fail
318       1       0     fail.         Pass         Fail
319       0       0     fail.         Fail         Fail
320       0       0     fail.         Fail         Fail
321       0       1     pass.         Fail         Pass
322       0       0     fail.         Fail         Fail
323       0       1     pass.         Fail         Pass
324       1       0      fail         Pass         Fail
325       1       1      pass         Pass         Pass
326       0       0      fail         Fail         Fail
327       1       0     fail.         Pass         Fail
328       0       0      fail         Fail         Fail
329       1       0     fail.         Pass         Fail
330       0       0      fail         Fail         Fail
331       0       0      fail         Fail         Fail
332       0       1     pass.         Fail         Pass
333       0       0      fail         Fail         Fail
334       0       0      fail         Fail         Fail
335       0       0      fail         Fail         Fail
336       1       1     pass.         Pass         Pass
337       0       0      fail         Fail         Fail
338       1       1      pass         Pass         Pass
339       1       0      fail         Pass         Fail
340       1       0      fail         Pass         Fail
341       1       1      pass         Pass         Pass
342       1       1     pass.         Pass         Pass
343       1       0      fail         Pass         Fail
344       1       1     pass.         Pass         Pass
345       1       0      fail         Pass         Fail
346       0       0     fail.         Fail         Fail
347       1       0     fail.         Pass         Fail
348       0       0      fail         Fail         Fail
349       0       0      fail         Fail         Fail
350       0       0     fail.         Fail         Fail
351       1       1     pass.         Pass         Pass
352       0       0      fail         Fail         Fail
353       0       0      fail         Fail         Fail
354       1       1      pass         Pass         Pass
355       0       0      fail         Fail         Fail

0.76 from ollama models very good, expect no less from ollama

## Qwen

In [ ]:
## Qwen2.5:7b

In [ ]:
!ollama pull qwen2.5:7b

In [ ]:
y_pred, y_generated = predict_ollama(X_test_prompts_llama, model_name="qwen2.5:7b")

  0%|          | 1/765 [00:28<6:08:02, 28.90s/it]

[  1/765]  raw='pass'  →  Pass

  0%|          | 2/765 [00:29<2:35:00, 12.19s/it]

[  2/765]  raw='pass'  →  Pass

  0%|          | 3/765 [00:29<1:26:41,  6.83s/it]

[  3/765]  raw='pass'  →  Pass

  1%|          | 4/765 [00:30<55:14,  4.36s/it]

[  4/765]  raw='pass'  →  Pass

  1%|          | 5/765 [00:30<37:14,  2.94s/it]

[  5/765]  raw='pass'  →  Pass

  1%|          | 6/765 [00:31<26:25,  2.09s/it]

[  6/765]  raw='pass'  →  Pass

  1%|          | 7/765 [00:31<20:00,  1.58s/it]

[  7/765]  raw='pass'  →  Pass

  1%|          | 8/765 [00:32<15:39,  1.24s/it]

[  8/765]  raw='pass'  →  Pass

  1%|          | 9/765 [00:32<13:06,  1.04s/it]

[  9/765]  raw='pass'  →  Pass

  1%|▏         | 10/765 [00:33<10:39,  1.18it/s]

[ 10/765]  raw='pass'  →  Pass

  1%|▏         | 11/765 [00:33<09:24,  1.34it/s]

[ 11/765]  raw='fail'  →  Fail

  2%|▏         | 12/765 [00:34<08:50,  1.42it/s]

[ 12/765]  raw='pass'  →  Pass

  2%|▏         | 13/765 [00:34<08:09,  1.54it/s]

[ 13/765]  raw='pass'  →  Pass

  2%|▏         | 14/765 [00:35<07:46,  1.61it/s]

[ 14/765]  raw='pass'  →  Pass

  2%|▏         | 15/765 [00:36<07:14,  1.73it/s]

[ 15/765]  raw='pass'  →  Pass

  2%|▏         | 16/765 [00:36<06:59,  1.79it/s]

[ 16/765]  raw='pass'  →  Pass

  2%|▏         | 17/765 [00:37<06:43,  1.85it/s]

[ 17/765]  raw='pass'  →  Pass

  2%|▏         | 18/765 [00:37<06:47,  1.83it/s]

[ 18/765]  raw='pass'  →  Pass

  2%|▏         | 19/765 [00:38<06:23,  1.94it/s]

[ 19/765]  raw='pass'  →  Pass

  3%|▎         | 20/765 [00:38<06:46,  1.83it/s]

[ 20/765]  raw='pass'  →  Pass

  3%|▎         | 21/765 [00:39<06:26,  1.93it/s]

[ 21/765]  raw='fail'  →  Fail

  3%|▎         | 22/765 [00:39<06:03,  2.04it/s]

[ 22/765]  raw='fail'  →  Fail

  3%|▎         | 23/765 [00:39<05:42,  2.17it/s]

[ 23/765]  raw='pass'  →  Pass

  3%|▎         | 24/765 [00:40<06:08,  2.01it/s]

[ 24/765]  raw='pass'  →  Pass

  3%|▎         | 25/765 [00:41<06:13,  1.98it/s]

[ 25/765]  raw='pass'  →  Pass

  3%|▎         | 26/765 [00:41<05:57,  2.06it/s]

[ 26/765]  raw='pass'  →  Pass

  4%|▎         | 27/765 [00:41<05:38,  2.18it/s]

[ 27/765]  raw='pass'  →  Pass

  4%|▎         | 28/765 [00:42<05:31,  2.22it/s]

[ 28/765]  raw='pass'  →  Pass

  4%|▍         | 29/765 [00:42<05:34,  2.20it/s]

[ 29/765]  raw='pass'  →  Pass

  4%|▍         | 30/765 [00:43<05:35,  2.19it/s]

[ 30/765]  raw='fail'  →  Fail

  4%|▍         | 31/765 [00:43<05:43,  2.14it/s]

[ 31/765]  raw='pass'  →  Pass

  4%|▍         | 32/765 [00:44<05:35,  2.19it/s]

[ 32/765]  raw='pass'  →  Pass

  4%|▍         | 33/765 [00:44<06:01,  2.03it/s]

[ 33/765]  raw='pass'  →  Pass

  4%|▍         | 34/765 [00:45<05:50,  2.09it/s]

[ 34/765]  raw='pass'  →  Pass

  5%|▍         | 35/765 [00:45<05:39,  2.15it/s]

[ 35/765]  raw='fail'  →  Fail

  5%|▍         | 36/765 [00:46<05:35,  2.17it/s]

[ 36/765]  raw='pass'  →  Pass

  5%|▍         | 37/765 [00:46<05:43,  2.12it/s]

[ 37/765]  raw='pass'  →  Pass

  5%|▍         | 38/765 [00:47<05:45,  2.10it/s]

[ 38/765]  raw='pass'  →  Pass

  5%|▌         | 39/765 [00:47<05:51,  2.07it/s]

[ 39/765]  raw='pass'  →  Pass

  5%|▌         | 40/765 [00:48<06:12,  1.95it/s]

[ 40/765]  raw='pass'  →  Pass

  5%|▌         | 41/765 [00:48<06:49,  1.77it/s]

[ 41/765]  raw='pass'  →  Pass

  5%|▌         | 42/765 [00:49<06:43,  1.79it/s]

[ 42/765]  raw='fail'  →  Fail

  6%|▌         | 43/765 [00:49<06:08,  1.96it/s]

[ 43/765]  raw='fail'  →  Fail

  6%|▌         | 44/765 [00:50<05:53,  2.04it/s]

[ 44/765]  raw='pass'  →  Pass

  6%|▌         | 45/765 [00:50<05:29,  2.19it/s]

[ 45/765]  raw='pass'  →  Pass

  6%|▌         | 46/765 [00:51<05:27,  2.20it/s]

[ 46/765]  raw='fail'  →  Fail

  6%|▌         | 47/765 [00:51<05:27,  2.20it/s]

[ 47/765]  raw='fail'  →  Fail

  6%|▋         | 48/765 [00:51<05:33,  2.15it/s]

[ 48/765]  raw='pass'  →  Pass

  6%|▋         | 49/765 [00:52<05:31,  2.16it/s]

[ 49/765]  raw='fail'  →  Fail

  7%|▋         | 50/765 [00:52<05:45,  2.07it/s]

[ 50/765]  raw='pass'  →  Pass

  7%|▋         | 51/765 [00:53<05:41,  2.09it/s]

[ 51/765]  raw='pass'  →  Pass

  7%|▋         | 52/765 [00:53<05:24,  2.20it/s]

[ 52/765]  raw='pass'  →  Pass

  7%|▋         | 53/765 [00:54<05:29,  2.16it/s]

[ 53/765]  raw='pass'  →  Pass

  7%|▋         | 54/765 [00:54<06:17,  1.88it/s]

[ 54/765]  raw='pass'  →  Pass

  7%|▋         | 55/765 [00:55<06:06,  1.94it/s]

[ 55/765]  raw='pass'  →  Pass

  7%|▋         | 56/765 [00:55<05:51,  2.02it/s]

[ 56/765]  raw='pass'  →  Pass

  7%|▋         | 57/765 [00:56<05:37,  2.10it/s]

[ 57/765]  raw='pass'  →  Pass

  8%|▊         | 58/765 [00:56<05:37,  2.09it/s]

[ 58/765]  raw='pass'  →  Pass

  8%|▊         | 59/765 [00:57<05:43,  2.06it/s]

[ 59/765]  raw='pass'  →  Pass

  8%|▊         | 60/765 [00:57<05:24,  2.17it/s]

[ 60/765]  raw='fail'  →  Fail

  8%|▊         | 61/765 [00:58<05:34,  2.10it/s]

[ 61/765]  raw='pass'  →  Pass

  8%|▊         | 62/765 [00:58<05:39,  2.07it/s]

[ 62/765]  raw='pass'  →  Pass

  8%|▊         | 63/765 [00:59<05:53,  1.99it/s]

[ 63/765]  raw='pass'  →  Pass

  8%|▊         | 64/765 [00:59<05:34,  2.09it/s]

[ 64/765]  raw='fail'  →  Fail

  8%|▊         | 65/765 [01:00<05:16,  2.21it/s]

[ 65/765]  raw='fail'  →  Fail

  9%|▊         | 66/765 [01:00<05:22,  2.17it/s]

[ 66/765]  raw='pass'  →  Pass

  9%|▉         | 67/765 [01:01<05:49,  2.00it/s]

[ 67/765]  raw='pass'  →  Pass

  9%|▉         | 68/765 [01:01<05:37,  2.06it/s]

[ 68/765]  raw='fail'  →  Fail

  9%|▉         | 69/765 [01:02<05:32,  2.09it/s]

[ 69/765]  raw='pass'  →  Pass

  9%|▉         | 70/765 [01:02<05:16,  2.20it/s]

[ 70/765]  raw='pass'  →  Pass

  9%|▉         | 71/765 [01:02<05:06,  2.26it/s]

[ 71/765]  raw='pass'  →  Pass

  9%|▉         | 72/765 [01:03<04:58,  2.32it/s]

[ 72/765]  raw='fail'  →  Fail

 10%|▉         | 73/765 [01:03<04:50,  2.38it/s]

[ 73/765]  raw='pass'  →  Pass

 10%|▉         | 74/765 [01:04<04:50,  2.38it/s]

[ 74/765]  raw='fail'  →  Fail

 10%|▉         | 75/765 [01:04<04:50,  2.38it/s]

[ 75/765]  raw='fail'  →  Fail

 10%|▉         | 76/765 [01:05<05:07,  2.24it/s]

[ 76/765]  raw='pass'  →  Pass

 10%|█         | 77/765 [01:05<04:53,  2.34it/s]

[ 77/765]  raw='pass'  →  Pass

 10%|█         | 78/765 [01:05<04:58,  2.30it/s]

[ 78/765]  raw='pass'  →  Pass

 10%|█         | 79/765 [01:06<04:53,  2.34it/s]

[ 79/765]  raw='pass'  →  Pass

 10%|█         | 80/765 [01:06<05:22,  2.13it/s]

[ 80/765]  raw='pass'  →  Pass

 11%|█         | 81/765 [01:07<05:32,  2.05it/s]

[ 81/765]  raw='pass'  →  Pass

 11%|█         | 82/765 [01:07<05:33,  2.05it/s]

[ 82/765]  raw='pass'  →  Pass

 11%|█         | 83/765 [01:08<06:00,  1.89it/s]

[ 83/765]  raw='pass'  →  Pass

 11%|█         | 84/765 [01:09<06:24,  1.77it/s]

[ 84/765]  raw='pass'  →  Pass

 11%|█         | 85/765 [01:09<05:51,  1.93it/s]

[ 85/765]  raw='fail'  →  Fail

 11%|█         | 86/765 [01:10<05:36,  2.02it/s]

[ 86/765]  raw='pass'  →  Pass

 11%|█▏        | 87/765 [01:10<05:26,  2.07it/s]

[ 87/765]  raw='pass'  →  Pass

 12%|█▏        | 88/765 [01:10<05:18,  2.13it/s]

[ 88/765]  raw='pass'  →  Pass

 12%|█▏        | 89/765 [01:11<05:23,  2.09it/s]

[ 89/765]  raw='pass'  →  Pass

 12%|█▏        | 90/765 [01:11<05:05,  2.21it/s]

[ 90/765]  raw='pass'  →  Pass

 12%|█▏        | 91/765 [01:12<05:13,  2.15it/s]

[ 91/765]  raw='pass'  →  Pass

 12%|█▏        | 92/765 [01:12<05:46,  1.94it/s]

[ 92/765]  raw='pass'  →  Pass

 12%|█▏        | 93/765 [01:13<05:49,  1.92it/s]

[ 93/765]  raw='fail'  →  Fail

 12%|█▏        | 94/765 [01:13<05:31,  2.03it/s]

[ 94/765]  raw='fail'  →  Fail

 12%|█▏        | 95/765 [01:14<05:21,  2.09it/s]

[ 95/765]  raw='fail'  →  Fail

 13%|█▎        | 96/765 [01:14<05:07,  2.17it/s]

[ 96/765]  raw='pass'  →  Pass

 13%|█▎        | 97/765 [01:15<05:00,  2.22it/s]

[ 97/765]  raw='fail'  →  Fail

 13%|█▎        | 98/765 [01:15<04:52,  2.28it/s]

[ 98/765]  raw='fail'  →  Fail

 13%|█▎        | 99/765 [01:16<05:29,  2.02it/s]

[ 99/765]  raw='fail'  →  Fail

 13%|█▎        | 100/765 [01:16<05:15,  2.11it/s]

[100/765]  raw='fail'  →  Fail

 13%|█▎        | 101/765 [01:17<05:01,  2.20it/s]

[101/765]  raw='pass'  →  Pass

 13%|█▎        | 102/765 [01:17<04:57,  2.23it/s]

[102/765]  raw='pass'  →  Pass

 13%|█▎        | 103/765 [01:17<04:49,  2.29it/s]

[103/765]  raw='pass'  →  Pass

 14%|█▎        | 104/765 [01:18<04:47,  2.30it/s]

[104/765]  raw='pass'  →  Pass

 14%|█▎        | 105/765 [01:18<04:38,  2.37it/s]

[105/765]  raw='pass'  →  Pass

 14%|█▍        | 106/765 [01:19<05:13,  2.10it/s]

[106/765]  raw='pass'  →  Pass

 14%|█▍        | 107/765 [01:19<05:22,  2.04it/s]

[107/765]  raw='pass'  →  Pass

 14%|█▍        | 108/765 [01:20<05:09,  2.12it/s]

[108/765]  raw='fail'  →  Fail

 14%|█▍        | 109/765 [01:20<05:18,  2.06it/s]

[109/765]  raw='pass'  →  Pass

 14%|█▍        | 110/765 [01:21<05:08,  2.12it/s]

[110/765]  raw='pass'  →  Pass

 15%|█▍        | 111/765 [01:21<04:56,  2.20it/s]

[111/765]  raw='pass'  →  Pass

 15%|█▍        | 112/765 [01:22<04:46,  2.28it/s]

[112/765]  raw='pass'  →  Pass

 15%|█▍        | 113/765 [01:22<04:47,  2.27it/s]

[113/765]  raw='pass'  →  Pass

 15%|█▍        | 114/765 [01:22<04:57,  2.19it/s]

[114/765]  raw='pass'  →  Pass

 15%|█▌        | 115/765 [01:23<04:49,  2.25it/s]

[115/765]  raw='pass'  →  Pass

 15%|█▌        | 116/765 [01:23<04:47,  2.26it/s]

[116/765]  raw='pass'  →  Pass

 15%|█▌        | 117/765 [01:24<04:54,  2.20it/s]

[117/765]  raw='pass'  →  Pass

 15%|█▌        | 118/765 [01:24<05:01,  2.15it/s]

[118/765]  raw='pass'  →  Pass

 16%|█▌        | 119/765 [01:25<04:57,  2.17it/s]

[119/765]  raw='pass'  →  Pass

 16%|█▌        | 120/765 [01:25<05:05,  2.11it/s]

[120/765]  raw='fail'  →  Fail

 16%|█▌        | 121/765 [01:26<05:21,  2.01it/s]

[121/765]  raw='pass'  →  Pass

 16%|█▌        | 122/765 [01:26<05:20,  2.01it/s]

[122/765]  raw='pass'  →  Pass

 16%|█▌        | 123/765 [01:27<05:27,  1.96it/s]

[123/765]  raw='pass'  →  Pass

 16%|█▌        | 124/765 [01:27<05:34,  1.92it/s]

[124/765]  raw='pass'  →  Pass

 16%|█▋        | 125/765 [01:28<05:16,  2.02it/s]

[125/765]  raw='pass'  →  Pass

 16%|█▋        | 126/765 [01:28<05:00,  2.13it/s]

[126/765]  raw='pass'  →  Pass

 17%|█▋        | 127/765 [01:29<05:00,  2.12it/s]

[127/765]  raw='pass'  →  Pass

 17%|█▋        | 128/765 [01:29<04:49,  2.20it/s]

[128/765]  raw='pass'  →  Pass

 17%|█▋        | 129/765 [01:30<04:59,  2.12it/s]

[129/765]  raw='fail'  →  Fail

 17%|█▋        | 130/765 [01:30<05:16,  2.01it/s]

[130/765]  raw='pass'  →  Pass

 17%|█▋        | 131/765 [01:31<05:11,  2.04it/s]

[131/765]  raw='pass'  →  Pass

 17%|█▋        | 132/765 [01:31<04:58,  2.12it/s]

[132/765]  raw='pass'  →  Pass

 17%|█▋        | 133/765 [01:32<04:52,  2.16it/s]

[133/765]  raw='pass'  →  Pass

 18%|█▊        | 134/765 [01:32<04:52,  2.16it/s]

[134/765]  raw='fail'  →  Fail

 18%|█▊        | 135/765 [01:32<04:47,  2.19it/s]

[135/765]  raw='pass'  →  Pass

 18%|█▊        | 136/765 [01:33<04:52,  2.15it/s]

[136/765]  raw='pass'  →  Pass

 18%|█▊        | 137/765 [01:43<34:24,  3.29s/it]

[137/765]  raw='pass'  →  Pass

 18%|█▊        | 138/765 [01:43<25:46,  2.47s/it]

[138/765]  raw='fail'  →  Fail

 18%|█▊        | 139/765 [01:44<20:02,  1.92s/it]

[139/765]  raw='pass'  →  Pass

 18%|█▊        | 140/765 [01:44<15:27,  1.48s/it]

[140/765]  raw='fail'  →  Fail

 18%|█▊        | 141/765 [01:45<12:10,  1.17s/it]

[141/765]  raw='fail'  →  Fail

 19%|█▊        | 142/765 [01:45<10:12,  1.02it/s]

[142/765]  raw='fail'  →  Fail

 19%|█▊        | 143/765 [01:46<08:33,  1.21it/s]

[143/765]  raw='fail'  →  Fail

 19%|█▉        | 144/765 [01:47<08:10,  1.26it/s]

[144/765]  raw='pass'  →  Pass

 19%|█▉        | 145/765 [01:47<07:16,  1.42it/s]

[145/765]  raw='pass'  →  Pass

 19%|█▉        | 146/765 [01:48<06:28,  1.59it/s]

[146/765]  raw='fail'  →  Fail

 19%|█▉        | 147/765 [01:48<06:30,  1.58it/s]

[147/765]  raw='pass'  →  Pass

 19%|█▉        | 148/765 [01:49<06:15,  1.64it/s]

[148/765]  raw='pass'  →  Pass

 19%|█▉        | 149/765 [01:49<05:55,  1.73it/s]

[149/765]  raw='pass'  →  Pass

 20%|█▉        | 150/765 [01:50<05:28,  1.87it/s]

[150/765]  raw='fail'  →  Fail

 20%|█▉        | 151/765 [01:50<05:38,  1.82it/s]

[151/765]  raw='pass'  →  Pass

 20%|█▉        | 152/765 [01:51<05:31,  1.85it/s]

[152/765]  raw='pass'  →  Pass

 20%|██        | 153/765 [01:51<05:15,  1.94it/s]

[153/765]  raw='pass'  →  Pass

 20%|██        | 154/765 [01:52<05:14,  1.94it/s]

[154/765]  raw='pass'  →  Pass

 20%|██        | 155/765 [01:52<05:17,  1.92it/s]

[155/765]  raw='pass'  →  Pass

 20%|██        | 156/765 [01:53<05:28,  1.85it/s]

[156/765]  raw='pass'  →  Pass

 21%|██        | 157/765 [01:53<05:34,  1.82it/s]

[157/765]  raw='fail'  →  Fail

 21%|██        | 158/765 [01:54<05:39,  1.79it/s]

[158/765]  raw='pass'  →  Pass

 21%|██        | 159/765 [01:55<05:30,  1.84it/s]

[159/765]  raw='pass'  →  Pass

 21%|██        | 160/765 [01:55<05:37,  1.79it/s]

[160/765]  raw='pass'  →  Pass

 21%|██        | 161/765 [01:56<05:21,  1.88it/s]

[161/765]  raw='pass'  →  Pass

 21%|██        | 162/765 [01:56<04:56,  2.03it/s]

[162/765]  raw='pass'  →  Pass

 21%|██▏       | 163/765 [01:57<04:54,  2.04it/s]

[163/765]  raw='pass'  →  Pass

 21%|██▏       | 164/765 [01:57<04:50,  2.07it/s]

[164/765]  raw='pass'  →  Pass

 22%|██▏       | 165/765 [01:57<04:53,  2.05it/s]

[165/765]  raw='fail'  →  Fail

 22%|██▏       | 166/765 [01:58<04:51,  2.06it/s]

[166/765]  raw='fail'  →  Fail

 22%|██▏       | 167/765 [01:58<04:42,  2.11it/s]

[167/765]  raw='fail'  →  Fail

 22%|██▏       | 168/765 [01:59<04:40,  2.13it/s]

[168/765]  raw='fail'  →  Fail

 22%|██▏       | 169/765 [01:59<04:46,  2.08it/s]

[169/765]  raw='pass'  →  Pass

 22%|██▏       | 170/765 [02:00<04:42,  2.10it/s]

[170/765]  raw='pass'  →  Pass

 22%|██▏       | 171/765 [02:00<04:58,  1.99it/s]

[171/765]  raw='pass'  →  Pass

 22%|██▏       | 172/765 [02:01<05:06,  1.94it/s]

[172/765]  raw='pass'  →  Pass

 23%|██▎       | 173/765 [02:02<05:25,  1.82it/s]

[173/765]  raw='pass'  →  Pass

 23%|██▎       | 174/765 [02:02<05:36,  1.76it/s]

[174/765]  raw='pass'  →  Pass

 23%|██▎       | 175/765 [02:03<05:10,  1.90it/s]

[175/765]  raw='pass'  →  Pass

 23%|██▎       | 176/765 [02:03<04:50,  2.03it/s]

[176/765]  raw='pass'  →  Pass

 23%|██▎       | 177/765 [02:03<04:41,  2.09it/s]

[177/765]  raw='fail'  →  Fail

 23%|██▎       | 178/765 [02:04<04:53,  2.00it/s]

[178/765]  raw='fail'  →  Fail

 23%|██▎       | 179/765 [02:05<05:23,  1.81it/s]

[179/765]  raw='pass'  →  Pass

 24%|██▎       | 180/765 [02:05<04:57,  1.97it/s]

[180/765]  raw='pass'  →  Pass

 24%|██▎       | 181/765 [02:05<04:32,  2.14it/s]

[181/765]  raw='pass'  →  Pass

 24%|██▍       | 182/765 [02:06<04:20,  2.24it/s]

[182/765]  raw='fail'  →  Fail

 24%|██▍       | 183/765 [02:06<04:14,  2.29it/s]

[183/765]  raw='pass'  →  Pass

 24%|██▍       | 184/765 [02:07<04:01,  2.40it/s]

[184/765]  raw='fail'  →  Fail

 24%|██▍       | 185/765 [02:07<04:19,  2.23it/s]

[185/765]  raw='pass'  →  Pass

 24%|██▍       | 186/765 [02:08<04:47,  2.02it/s]

[186/765]  raw='pass'  →  Pass

 24%|██▍       | 187/765 [02:08<04:49,  1.99it/s]

[187/765]  raw='fail'  →  Fail

 25%|██▍       | 188/765 [02:09<04:32,  2.12it/s]

[188/765]  raw='fail'  →  Fail

 25%|██▍       | 189/765 [02:09<04:39,  2.06it/s]

[189/765]  raw='pass'  →  Pass

 25%|██▍       | 190/765 [02:10<04:46,  2.00it/s]

[190/765]  raw='pass'  →  Pass

 25%|██▍       | 191/765 [02:10<04:52,  1.96it/s]

[191/765]  raw='fail'  →  Fail

 25%|██▌       | 192/765 [02:11<05:13,  1.83it/s]

[192/765]  raw='pass'  →  Pass

 25%|██▌       | 193/765 [02:11<05:11,  1.84it/s]

[193/765]  raw='pass'  →  Pass

 25%|██▌       | 194/765 [02:12<05:02,  1.89it/s]

[194/765]  raw='fail'  →  Fail

 25%|██▌       | 195/765 [02:13<05:35,  1.70it/s]

[195/765]  raw='pass'  →  Pass

 26%|██▌       | 196/765 [02:13<05:13,  1.82it/s]

[196/765]  raw='pass'  →  Pass

 26%|██▌       | 197/765 [02:14<05:07,  1.84it/s]

[197/765]  raw='pass'  →  Pass

 26%|██▌       | 198/765 [02:14<04:54,  1.93it/s]

[198/765]  raw='pass'  →  Pass

 26%|██▌       | 199/765 [02:15<04:44,  1.99it/s]

[199/765]  raw='pass'  →  Pass

 26%|██▌       | 200/765 [02:15<04:31,  2.08it/s]

[200/765]  raw='fail'  →  Fail

 26%|██▋       | 201/765 [02:15<04:23,  2.14it/s]

[201/765]  raw='pass'  →  Pass

 26%|██▋       | 202/765 [02:16<04:21,  2.15it/s]

[202/765]  raw='pass'  →  Pass

 27%|██▋       | 203/765 [02:16<04:26,  2.11it/s]

[203/765]  raw='fail'  →  Fail

 27%|██▋       | 204/765 [02:17<04:20,  2.15it/s]

[204/765]  raw='pass'  →  Pass

 27%|██▋       | 205/765 [02:17<04:10,  2.24it/s]

[205/765]  raw='fail'  →  Fail

 27%|██▋       | 206/765 [02:18<04:15,  2.18it/s]

[206/765]  raw='pass'  →  Pass

 27%|██▋       | 207/765 [02:18<04:34,  2.03it/s]

[207/765]  raw='pass'  →  Pass

 27%|██▋       | 208/765 [02:19<04:41,  1.98it/s]

[208/765]  raw='pass'  →  Pass

 27%|██▋       | 209/765 [02:19<04:34,  2.03it/s]

[209/765]  raw='fail'  →  Fail

 27%|██▋       | 210/765 [02:20<04:28,  2.06it/s]

[210/765]  raw='pass'  →  Pass

 28%|██▊       | 211/765 [02:20<04:16,  2.16it/s]

[211/765]  raw='fail'  →  Fail

 28%|██▊       | 212/765 [02:21<04:06,  2.24it/s]

[212/765]  raw='pass'  →  Pass

 28%|██▊       | 213/765 [02:21<04:13,  2.18it/s]

[213/765]  raw='pass'  →  Pass

 28%|██▊       | 214/765 [02:22<04:06,  2.23it/s]

[214/765]  raw='pass'  →  Pass

 28%|██▊       | 215/765 [02:22<04:11,  2.19it/s]

[215/765]  raw='pass'  →  Pass

 28%|██▊       | 216/765 [02:22<04:04,  2.25it/s]

[216/765]  raw='fail'  →  Fail

 28%|██▊       | 217/765 [02:23<03:56,  2.31it/s]

[217/765]  raw='fail'  →  Fail

 28%|██▊       | 218/765 [02:23<04:34,  1.99it/s]

[218/765]  raw='pass'  →  Pass

 29%|██▊       | 219/765 [02:24<04:48,  1.89it/s]

[219/765]  raw='pass'  →  Pass

 29%|██▉       | 220/765 [02:25<04:32,  2.00it/s]

[220/765]  raw='pass'  →  Pass

 29%|██▉       | 221/765 [02:25<04:15,  2.13it/s]

[221/765]  raw='pass'  →  Pass

 29%|██▉       | 222/765 [02:25<04:17,  2.11it/s]

[222/765]  raw='fail'  →  Fail

 29%|██▉       | 223/765 [02:26<04:31,  2.00it/s]

[223/765]  raw='fail'  →  Fail

 29%|██▉       | 224/765 [02:27<04:42,  1.91it/s]

[224/765]  raw='pass'  →  Pass

 29%|██▉       | 225/765 [02:27<04:34,  1.97it/s]

[225/765]  raw='fail'  →  Fail

 30%|██▉       | 226/765 [02:28<04:42,  1.91it/s]

[226/765]  raw='pass'  →  Pass

 30%|██▉       | 227/765 [02:28<04:29,  2.00it/s]

[227/765]  raw='pass'  →  Pass

 30%|██▉       | 228/765 [02:28<04:10,  2.15it/s]

[228/765]  raw='pass'  →  Pass

 30%|██▉       | 229/765 [02:29<04:03,  2.21it/s]

[229/765]  raw='fail'  →  Fail

 30%|███       | 230/765 [02:29<03:59,  2.23it/s]

[230/765]  raw='pass'  →  Pass

 30%|███       | 231/765 [02:30<04:08,  2.15it/s]

[231/765]  raw='pass'  →  Pass

 30%|███       | 232/765 [02:30<04:17,  2.07it/s]

[232/765]  raw='fail'  →  Fail

 30%|███       | 233/765 [02:31<04:07,  2.15it/s]

[233/765]  raw='fail'  →  Fail

 31%|███       | 234/765 [02:31<04:09,  2.13it/s]

[234/765]  raw='pass'  →  Pass

 31%|███       | 235/765 [02:32<04:21,  2.03it/s]

[235/765]  raw='pass'  →  Pass

 31%|███       | 236/765 [02:32<04:17,  2.06it/s]

[236/765]  raw='fail'  →  Fail

 31%|███       | 237/765 [02:33<03:58,  2.21it/s]

[237/765]  raw='pass'  →  Pass

 31%|███       | 238/765 [02:33<03:54,  2.25it/s]

[238/765]  raw='pass'  →  Pass

 31%|███       | 239/765 [02:34<04:07,  2.13it/s]

[239/765]  raw='pass'  →  Pass

 31%|███▏      | 240/765 [02:34<04:06,  2.13it/s]

[240/765]  raw='pass'  →  Pass

 32%|███▏      | 241/765 [02:35<04:20,  2.01it/s]

[241/765]  raw='pass'  →  Pass

 32%|███▏      | 242/765 [02:35<04:09,  2.10it/s]

[242/765]  raw='pass'  →  Pass

 32%|███▏      | 243/765 [02:35<03:58,  2.19it/s]

[243/765]  raw='pass'  →  Pass

 32%|███▏      | 244/765 [02:36<03:48,  2.28it/s]

[244/765]  raw='pass'  →  Pass

 32%|███▏      | 245/765 [02:36<03:46,  2.29it/s]

[245/765]  raw='pass'  →  Pass

 32%|███▏      | 246/765 [02:37<04:30,  1.92it/s]

[246/765]  raw='pass'  →  Pass

 32%|███▏      | 247/765 [02:38<04:37,  1.87it/s]

[247/765]  raw='pass'  →  Pass

 32%|███▏      | 248/765 [02:38<04:19,  1.99it/s]

[248/765]  raw='fail'  →  Fail

 33%|███▎      | 249/765 [02:38<04:18,  2.00it/s]

[249/765]  raw='fail'  →  Fail

 33%|███▎      | 250/765 [02:39<04:00,  2.14it/s]

[250/765]  raw='pass'  →  Pass

 33%|███▎      | 251/765 [02:39<03:51,  2.22it/s]

[251/765]  raw='fail'  →  Fail

 33%|███▎      | 252/765 [02:40<03:51,  2.22it/s]

[252/765]  raw='pass'  →  Pass

 33%|███▎      | 253/765 [02:40<04:01,  2.12it/s]

[253/765]  raw='fail'  →  Fail

 33%|███▎      | 254/765 [02:41<03:52,  2.20it/s]

[254/765]  raw='fail'  →  Fail

 33%|███▎      | 255/765 [02:41<04:14,  2.00it/s]

[255/765]  raw='pass'  →  Pass

 33%|███▎      | 256/765 [02:42<04:11,  2.02it/s]

[256/765]  raw='pass'  →  Pass

 34%|███▎      | 257/765 [02:42<04:06,  2.06it/s]

[257/765]  raw='pass'  →  Pass

 34%|███▎      | 258/765 [02:43<03:56,  2.14it/s]

[258/765]  raw='fail'  →  Fail

 34%|███▍      | 259/765 [02:43<03:48,  2.21it/s]

[259/765]  raw='pass'  →  Pass

 34%|███▍      | 260/765 [02:44<03:58,  2.12it/s]

[260/765]  raw='pass'  →  Pass

 34%|███▍      | 261/765 [02:44<03:49,  2.19it/s]

[261/765]  raw='pass'  →  Pass

 34%|███▍      | 262/765 [02:45<04:04,  2.06it/s]

[262/765]  raw='pass'  →  Pass

 34%|███▍      | 263/765 [02:45<04:13,  1.98it/s]

[263/765]  raw='pass'  →  Pass

 35%|███▍      | 264/765 [02:45<03:56,  2.12it/s]

[264/765]  raw='fail'  →  Fail

 35%|███▍      | 265/765 [02:46<04:08,  2.01it/s]

[265/765]  raw='pass'  →  Pass

 35%|███▍      | 266/765 [02:47<04:06,  2.03it/s]

[266/765]  raw='pass'  →  Pass

 35%|███▍      | 267/765 [02:47<04:26,  1.87it/s]

[267/765]  raw='pass'  →  Pass

 35%|███▌      | 268/765 [02:48<04:24,  1.88it/s]

[268/765]  raw='pass'  →  Pass

 35%|███▌      | 269/765 [02:48<04:17,  1.93it/s]

[269/765]  raw='pass'  →  Pass

 35%|███▌      | 270/765 [02:49<03:57,  2.09it/s]

[270/765]  raw='pass'  →  Pass

 35%|███▌      | 271/765 [02:49<03:46,  2.18it/s]

[271/765]  raw='pass'  →  Pass

 36%|███▌      | 272/765 [02:49<03:54,  2.10it/s]

[272/765]  raw='pass'  →  Pass

 36%|███▌      | 273/765 [02:50<03:41,  2.22it/s]

[273/765]  raw='pass'  →  Pass

 36%|███▌      | 274/765 [02:50<03:44,  2.19it/s]

[274/765]  raw='pass'  →  Pass

 36%|███▌      | 275/765 [02:51<04:09,  1.97it/s]

[275/765]  raw='pass'  →  Pass

 36%|███▌      | 276/765 [02:51<03:57,  2.06it/s]

[276/765]  raw='fail'  →  Fail

 36%|███▌      | 277/765 [02:52<03:56,  2.06it/s]

[277/765]  raw='fail'  →  Fail

 36%|███▋      | 278/765 [02:52<03:44,  2.16it/s]

[278/765]  raw='fail'  →  Fail

 36%|███▋      | 279/765 [02:53<03:47,  2.13it/s]

[279/765]  raw='pass'  →  Pass

 37%|███▋      | 280/765 [02:53<03:41,  2.19it/s]

[280/765]  raw='fail'  →  Fail

 37%|███▋      | 281/765 [02:54<04:01,  2.00it/s]

[281/765]  raw='pass'  →  Pass

 37%|███▋      | 282/765 [02:54<03:52,  2.08it/s]

[282/765]  raw='fail'  →  Fail

 37%|███▋      | 283/765 [02:55<04:00,  2.00it/s]

[283/765]  raw='pass'  →  Pass

 37%|███▋      | 284/765 [02:55<04:01,  1.99it/s]

[284/765]  raw='pass'  →  Pass

 37%|███▋      | 285/765 [02:56<03:50,  2.08it/s]

[285/765]  raw='fail'  →  Fail

 37%|███▋      | 286/765 [02:56<03:47,  2.11it/s]

[286/765]  raw='fail'  →  Fail

 38%|███▊      | 287/765 [02:57<03:43,  2.14it/s]

[287/765]  raw='pass'  →  Pass

 38%|███▊      | 288/765 [02:57<03:41,  2.16it/s]

[288/765]  raw='pass'  →  Pass

 38%|███▊      | 289/765 [02:57<03:35,  2.21it/s]

[289/765]  raw='pass'  →  Pass

 38%|███▊      | 290/765 [02:58<03:33,  2.23it/s]

[290/765]  raw='fail'  →  Fail

 38%|███▊      | 291/765 [02:58<03:32,  2.23it/s]

[291/765]  raw='pass'  →  Pass

 38%|███▊      | 292/765 [02:59<03:26,  2.29it/s]

[292/765]  raw='fail'  →  Fail

 38%|███▊      | 293/765 [02:59<03:39,  2.15it/s]

[293/765]  raw='pass'  →  Pass

 38%|███▊      | 294/765 [03:00<04:03,  1.93it/s]

[294/765]  raw='pass'  →  Pass

 39%|███▊      | 295/765 [03:00<03:52,  2.03it/s]

[295/765]  raw='fail'  →  Fail

 39%|███▊      | 296/765 [03:01<03:53,  2.01it/s]

[296/765]  raw='pass'  →  Pass

 39%|███▉      | 297/765 [03:01<03:47,  2.06it/s]

[297/765]  raw='pass'  →  Pass

 39%|███▉      | 298/765 [03:02<03:49,  2.03it/s]

[298/765]  raw='pass'  →  Pass

 39%|███▉      | 299/765 [03:03<04:09,  1.87it/s]

[299/765]  raw='pass'  →  Pass

 39%|███▉      | 300/765 [03:03<03:54,  1.98it/s]

[300/765]  raw='pass'  →  Pass

 39%|███▉      | 301/765 [03:03<03:39,  2.11it/s]

[301/765]  raw='pass'  →  Pass

 39%|███▉      | 302/765 [03:04<03:40,  2.10it/s]

[302/765]  raw='fail'  →  Fail

 40%|███▉      | 303/765 [03:05<04:09,  1.85it/s]

[303/765]  raw='pass'  →  Pass

 40%|███▉      | 304/765 [03:05<03:59,  1.92it/s]

[304/765]  raw='pass'  →  Pass

 40%|███▉      | 305/765 [03:05<03:45,  2.04it/s]

[305/765]  raw='pass'  →  Pass

 40%|████      | 306/765 [03:06<03:34,  2.14it/s]

[306/765]  raw='fail'  →  Fail

 40%|████      | 307/765 [03:06<03:28,  2.19it/s]

[307/765]  raw='pass'  →  Pass

 40%|████      | 308/765 [03:07<03:23,  2.25it/s]

[308/765]  raw='pass'  →  Pass

 40%|████      | 309/765 [03:07<03:30,  2.17it/s]

[309/765]  raw='fail'  →  Fail

 41%|████      | 310/765 [03:08<03:35,  2.11it/s]

[310/765]  raw='pass'  →  Pass

 41%|████      | 311/765 [03:08<03:34,  2.12it/s]

[311/765]  raw='pass'  →  Pass

 41%|████      | 312/765 [03:09<03:29,  2.16it/s]

[312/765]  raw='pass'  →  Pass

 41%|████      | 313/765 [03:09<03:24,  2.21it/s]

[313/765]  raw='pass'  →  Pass

 41%|████      | 314/765 [03:10<03:40,  2.05it/s]

[314/765]  raw='pass'  →  Pass

 41%|████      | 315/765 [03:10<03:26,  2.18it/s]

[315/765]  raw='pass'  →  Pass

 41%|████▏     | 316/765 [03:10<03:25,  2.19it/s]

[316/765]  raw='pass'  →  Pass

 41%|████▏     | 317/765 [03:11<03:25,  2.18it/s]

[317/765]  raw='pass'  →  Pass

 42%|████▏     | 318/765 [03:11<03:23,  2.19it/s]

[318/765]  raw='fail'  →  Fail

 42%|████▏     | 319/765 [03:12<03:21,  2.22it/s]

[319/765]  raw='pass'  →  Pass

 42%|████▏     | 320/765 [03:12<03:25,  2.17it/s]

[320/765]  raw='fail'  →  Fail

 42%|████▏     | 321/765 [03:13<03:19,  2.22it/s]

[321/765]  raw='pass'  →  Pass

 42%|████▏     | 322/765 [03:13<03:18,  2.23it/s]

[322/765]  raw='pass'  →  Pass

 42%|████▏     | 323/765 [03:14<03:25,  2.15it/s]

[323/765]  raw='fail'  →  Fail

 42%|████▏     | 324/765 [03:14<03:20,  2.20it/s]

[324/765]  raw='pass'  →  Pass

 42%|████▏     | 325/765 [03:15<03:19,  2.21it/s]

[325/765]  raw='pass'  →  Pass

 43%|████▎     | 326/765 [03:15<03:39,  2.00it/s]

[326/765]  raw='pass'  →  Pass

 43%|████▎     | 327/765 [03:16<03:30,  2.08it/s]

[327/765]  raw='pass'  →  Pass

 43%|████▎     | 328/765 [03:16<03:31,  2.07it/s]

[328/765]  raw='pass'  →  Pass

 43%|████▎     | 329/765 [03:16<03:24,  2.14it/s]

[329/765]  raw='pass'  →  Pass

 43%|████▎     | 330/765 [03:17<03:26,  2.11it/s]

[330/765]  raw='pass'  →  Pass

 43%|████▎     | 331/765 [03:17<03:19,  2.17it/s]

[331/765]  raw='fail'  →  Fail

 43%|████▎     | 332/765 [03:18<03:18,  2.19it/s]

[332/765]  raw='pass'  →  Pass

 44%|████▎     | 333/765 [03:18<03:17,  2.19it/s]

[333/765]  raw='pass'  →  Pass

 44%|████▎     | 334/765 [03:19<03:23,  2.12it/s]

[334/765]  raw='pass'  →  Pass

 44%|████▍     | 335/765 [03:19<03:17,  2.18it/s]

[335/765]  raw='pass'  →  Pass

 44%|████▍     | 336/765 [03:20<03:10,  2.25it/s]

[336/765]  raw='fail'  →  Fail

 44%|████▍     | 337/765 [03:20<03:16,  2.18it/s]

[337/765]  raw='pass'  →  Pass

 44%|████▍     | 338/765 [03:21<03:23,  2.10it/s]

[338/765]  raw='pass'  →  Pass

 44%|████▍     | 339/765 [03:21<03:38,  1.95it/s]

[339/765]  raw='pass'  →  Pass

 44%|████▍     | 340/765 [03:22<03:42,  1.91it/s]

[340/765]  raw='pass'  →  Pass

 45%|████▍     | 341/765 [03:22<03:35,  1.97it/s]

[341/765]  raw='pass'  →  Pass

 45%|████▍     | 342/765 [03:23<03:37,  1.94it/s]

[342/765]  raw='pass'  →  Pass

 45%|████▍     | 343/765 [03:23<03:48,  1.85it/s]

[343/765]  raw='pass'  →  Pass

 45%|████▍     | 344/765 [03:24<03:47,  1.85it/s]

[344/765]  raw='pass'  →  Pass

 45%|████▌     | 345/765 [03:24<03:37,  1.93it/s]

[345/765]  raw='pass'  →  Pass

 45%|████▌     | 346/765 [03:25<03:48,  1.83it/s]

[346/765]  raw='pass'  →  Pass

 45%|████▌     | 347/765 [03:26<03:43,  1.87it/s]

[347/765]  raw='pass'  →  Pass

 45%|████▌     | 348/765 [03:26<03:38,  1.90it/s]

[348/765]  raw='fail'  →  Fail

 46%|████▌     | 349/765 [03:26<03:24,  2.03it/s]

[349/765]  raw='fail'  →  Fail

 46%|████▌     | 350/765 [03:27<03:12,  2.16it/s]

[350/765]  raw='fail'  →  Fail

 46%|████▌     | 351/765 [03:27<03:10,  2.17it/s]

[351/765]  raw='pass'  →  Pass

 46%|████▌     | 352/765 [03:28<03:14,  2.12it/s]

[352/765]  raw='pass'  →  Pass

 46%|████▌     | 353/765 [03:28<03:12,  2.14it/s]

[353/765]  raw='pass'  →  Pass

 46%|████▋     | 354/765 [03:29<03:06,  2.21it/s]

[354/765]  raw='pass'  →  Pass

 46%|████▋     | 355/765 [03:29<03:08,  2.17it/s]

[355/765]  raw='pass'  →  Pass

 47%|████▋     | 356/765 [03:30<03:16,  2.08it/s]

[356/765]  raw='pass'  →  Pass

 47%|████▋     | 357/765 [03:30<03:13,  2.11it/s]

[357/765]  raw='pass'  →  Pass

 47%|████▋     | 358/765 [03:31<03:15,  2.08it/s]

[358/765]  raw='fail'  →  Fail

 47%|████▋     | 359/765 [03:31<03:23,  1.99it/s]

[359/765]  raw='pass'  →  Pass

 47%|████▋     | 360/765 [03:32<03:16,  2.06it/s]

[360/765]  raw='fail'  →  Fail

 47%|████▋     | 361/765 [03:32<03:08,  2.15it/s]

[361/765]  raw='pass'  →  Pass

 47%|████▋     | 362/765 [03:33<03:22,  1.99it/s]

[362/765]  raw='pass'  →  Pass

 47%|████▋     | 363/765 [03:33<03:13,  2.07it/s]

[363/765]  raw='pass'  →  Pass

 48%|████▊     | 364/765 [03:34<03:13,  2.08it/s]

[364/765]  raw='pass'  →  Pass

 48%|████▊     | 365/765 [03:34<03:26,  1.93it/s]

[365/765]  raw='pass'  →  Pass

 48%|████▊     | 366/765 [03:35<03:15,  2.04it/s]

[366/765]  raw='fail'  →  Fail

 48%|████▊     | 367/765 [03:35<03:13,  2.05it/s]

[367/765]  raw='pass'  →  Pass

 48%|████▊     | 368/765 [03:35<03:02,  2.17it/s]

[368/765]  raw='pass'  →  Pass

 48%|████▊     | 369/765 [03:36<03:10,  2.08it/s]

[369/765]  raw='pass'  →  Pass

 48%|████▊     | 370/765 [03:37<03:21,  1.96it/s]

[370/765]  raw='pass'  →  Pass

 48%|████▊     | 371/765 [03:37<03:21,  1.96it/s]

[371/765]  raw='pass'  →  Pass

 49%|████▊     | 372/765 [03:37<03:06,  2.11it/s]

[372/765]  raw='fail'  →  Fail

 49%|████▉     | 373/765 [03:38<03:18,  1.98it/s]

[373/765]  raw='pass'  →  Pass

 49%|████▉     | 374/765 [03:39<03:22,  1.93it/s]

[374/765]  raw='pass'  →  Pass

 49%|████▉     | 375/765 [03:39<03:18,  1.96it/s]

[375/765]  raw='pass'  →  Pass

 49%|████▉     | 376/765 [03:40<03:18,  1.96it/s]

[376/765]  raw='pass'  →  Pass

 49%|████▉     | 377/765 [03:40<03:14,  1.99it/s]

[377/765]  raw='fail'  →  Fail

 49%|████▉     | 378/765 [03:41<03:28,  1.86it/s]

[378/765]  raw='pass'  →  Pass

 50%|████▉     | 379/765 [03:41<03:14,  1.99it/s]

[379/765]  raw='pass'  →  Pass

 50%|████▉     | 380/765 [03:42<02:59,  2.14it/s]

[380/765]  raw='fail'  →  Fail

 50%|████▉     | 381/765 [03:42<03:10,  2.01it/s]

[381/765]  raw='pass'  →  Pass

 50%|████▉     | 382/765 [03:43<03:05,  2.07it/s]

[382/765]  raw='fail'  →  Fail

 50%|█████     | 383/765 [03:43<02:53,  2.20it/s]

[383/765]  raw='pass'  →  Pass

 50%|█████     | 384/765 [03:43<02:51,  2.22it/s]

[384/765]  raw='pass'  →  Pass

 50%|█████     | 385/765 [03:44<02:43,  2.33it/s]

[385/765]  raw='fail'  →  Fail

 50%|█████     | 386/765 [03:44<02:53,  2.19it/s]

[386/765]  raw='pass'  →  Pass

 51%|█████     | 387/765 [03:45<02:49,  2.23it/s]

[387/765]  raw='pass'  →  Pass

 51%|█████     | 388/765 [03:45<02:52,  2.18it/s]

[388/765]  raw='fail'  →  Fail

 51%|█████     | 389/765 [03:46<02:57,  2.12it/s]

[389/765]  raw='pass'  →  Pass

 51%|█████     | 390/765 [03:46<03:00,  2.07it/s]

[390/765]  raw='pass'  →  Pass

 51%|█████     | 391/765 [03:47<02:54,  2.15it/s]

[391/765]  raw='pass'  →  Pass

 51%|█████     | 392/765 [03:47<02:46,  2.24it/s]

[392/765]  raw='fail'  →  Fail

 51%|█████▏    | 393/765 [03:47<02:46,  2.23it/s]

[393/765]  raw='pass'  →  Pass

 52%|█████▏    | 394/765 [03:48<03:18,  1.87it/s]

[394/765]  raw='pass'  →  Pass

 52%|█████▏    | 395/765 [03:49<03:20,  1.84it/s]

[395/765]  raw='fail'  →  Fail

 52%|█████▏    | 396/765 [03:49<03:12,  1.91it/s]

[396/765]  raw='pass'  →  Pass

 52%|█████▏    | 397/765 [03:50<03:15,  1.88it/s]

[397/765]  raw='fail'  →  Fail

 52%|█████▏    | 398/765 [03:50<03:10,  1.93it/s]

[398/765]  raw='pass'  →  Pass

 52%|█████▏    | 399/765 [03:51<03:07,  1.95it/s]

[399/765]  raw='fail'  →  Fail

 52%|█████▏    | 400/765 [03:51<03:06,  1.95it/s]

[400/765]  raw='pass'  →  Pass

 52%|█████▏    | 401/765 [03:52<03:02,  2.00it/s]

[401/765]  raw='pass'  →  Pass

 53%|█████▎    | 402/765 [03:52<03:09,  1.92it/s]

[402/765]  raw='fail'  →  Fail

 53%|█████▎    | 403/765 [03:53<02:57,  2.04it/s]

[403/765]  raw='fail'  →  Fail

 53%|█████▎    | 404/765 [03:53<02:47,  2.15it/s]

[404/765]  raw='pass'  →  Pass

 53%|█████▎    | 405/765 [03:54<02:41,  2.23it/s]

[405/765]  raw='fail'  →  Fail

 53%|█████▎    | 406/765 [03:54<02:45,  2.17it/s]

[406/765]  raw='fail'  →  Fail

 53%|█████▎    | 407/765 [03:55<03:00,  1.98it/s]

[407/765]  raw='pass'  →  Pass

 53%|█████▎    | 408/765 [03:55<02:54,  2.04it/s]

[408/765]  raw='pass'  →  Pass

 53%|█████▎    | 409/765 [03:56<02:49,  2.10it/s]

[409/765]  raw='pass'  →  Pass

 54%|█████▎    | 410/765 [03:56<02:43,  2.17it/s]

[410/765]  raw='pass'  →  Pass

 54%|█████▎    | 411/765 [03:56<02:32,  2.33it/s]

[411/765]  raw='fail'  →  Fail

 54%|█████▍    | 412/765 [03:57<02:47,  2.11it/s]

[412/765]  raw='pass'  →  Pass

 54%|█████▍    | 413/765 [03:57<02:55,  2.01it/s]

[413/765]  raw='fail'  →  Fail

 54%|█████▍    | 414/765 [03:58<03:02,  1.93it/s]

[414/765]  raw='pass'  →  Pass

 54%|█████▍    | 415/765 [03:58<02:49,  2.07it/s]

[415/765]  raw='pass'  →  Pass

 54%|█████▍    | 416/765 [03:59<02:40,  2.17it/s]

[416/765]  raw='pass'  →  Pass

 55%|█████▍    | 417/765 [03:59<02:30,  2.31it/s]

[417/765]  raw='pass'  →  Pass

 55%|█████▍    | 418/765 [04:00<02:29,  2.32it/s]

[418/765]  raw='pass'  →  Pass

 55%|█████▍    | 419/765 [04:00<02:35,  2.23it/s]

[419/765]  raw='fail'  →  Fail

 55%|█████▍    | 420/765 [04:01<02:39,  2.16it/s]

[420/765]  raw='fail'  →  Fail

 55%|█████▌    | 421/765 [04:01<02:34,  2.23it/s]

[421/765]  raw='pass'  →  Pass

 55%|█████▌    | 422/765 [04:02<02:49,  2.02it/s]

[422/765]  raw='pass'  →  Pass

 55%|█████▌    | 423/765 [04:02<02:57,  1.92it/s]

[423/765]  raw='pass'  →  Pass

 55%|█████▌    | 424/765 [04:03<02:44,  2.08it/s]

[424/765]  raw='pass'  →  Pass

 56%|█████▌    | 425/765 [04:03<02:41,  2.11it/s]

[425/765]  raw='fail'  →  Fail

 56%|█████▌    | 426/765 [04:04<02:48,  2.01it/s]

[426/765]  raw='pass'  →  Pass

 56%|█████▌    | 427/765 [04:04<03:16,  1.72it/s]

[427/765]  raw='pass'  →  Pass

 56%|█████▌    | 428/765 [04:05<03:02,  1.84it/s]

[428/765]  raw='fail'  →  Fail

 56%|█████▌    | 429/765 [04:05<02:56,  1.90it/s]

[429/765]  raw='fail'  →  Fail

 56%|█████▌    | 430/765 [04:06<02:57,  1.89it/s]

[430/765]  raw='pass'  →  Pass

 56%|█████▋    | 431/765 [04:06<02:55,  1.90it/s]

[431/765]  raw='pass'  →  Pass

 56%|█████▋    | 432/765 [04:07<02:50,  1.95it/s]

[432/765]  raw='pass'  →  Pass

 57%|█████▋    | 433/765 [04:07<02:47,  1.98it/s]

[433/765]  raw='pass'  →  Pass

 57%|█████▋    | 434/765 [04:08<02:38,  2.09it/s]

[434/765]  raw='pass'  →  Pass

 57%|█████▋    | 435/765 [04:08<02:31,  2.18it/s]

[435/765]  raw='pass'  →  Pass

 57%|█████▋    | 436/765 [04:09<02:28,  2.21it/s]

[436/765]  raw='pass'  →  Pass

 57%|█████▋    | 437/765 [04:09<02:24,  2.28it/s]

[437/765]  raw='fail'  →  Fail

 57%|█████▋    | 438/765 [04:09<02:18,  2.37it/s]

[438/765]  raw='pass'  →  Pass

 57%|█████▋    | 439/765 [04:10<02:22,  2.29it/s]

[439/765]  raw='pass'  →  Pass

 58%|█████▊    | 440/765 [04:10<02:23,  2.27it/s]

[440/765]  raw='pass'  →  Pass

 58%|█████▊    | 441/765 [04:11<02:25,  2.22it/s]

[441/765]  raw='pass'  →  Pass

 58%|█████▊    | 442/765 [04:11<02:23,  2.25it/s]

[442/765]  raw='pass'  →  Pass

 58%|█████▊    | 443/765 [04:12<02:17,  2.35it/s]

[443/765]  raw='fail'  →  Fail

 58%|█████▊    | 444/765 [04:12<02:14,  2.39it/s]

[444/765]  raw='fail'  →  Fail

 58%|█████▊    | 445/765 [04:13<02:22,  2.25it/s]

[445/765]  raw='pass'  →  Pass

 58%|█████▊    | 446/765 [04:13<02:20,  2.27it/s]

[446/765]  raw='pass'  →  Pass

 58%|█████▊    | 447/765 [04:13<02:25,  2.18it/s]

[447/765]  raw='pass'  →  Pass

 59%|█████▊    | 448/765 [04:14<02:24,  2.19it/s]

[448/765]  raw='pass'  →  Pass

 59%|█████▊    | 449/765 [04:14<02:23,  2.20it/s]

[449/765]  raw='pass'  →  Pass

 59%|█████▉    | 450/765 [04:15<02:27,  2.13it/s]

[450/765]  raw='fail'  →  Fail

 59%|█████▉    | 451/765 [04:15<02:21,  2.21it/s]

[451/765]  raw='pass'  →  Pass

 59%|█████▉    | 452/765 [04:16<02:15,  2.30it/s]

[452/765]  raw='pass'  →  Pass

 59%|█████▉    | 453/765 [04:16<02:17,  2.27it/s]

[453/765]  raw='fail'  →  Fail

 59%|█████▉    | 454/765 [04:17<02:17,  2.25it/s]

[454/765]  raw='fail'  →  Fail

 59%|█████▉    | 455/765 [04:17<02:25,  2.13it/s]

[455/765]  raw='pass'  →  Pass

 60%|█████▉    | 456/765 [04:18<02:25,  2.12it/s]

[456/765]  raw='pass'  →  Pass

 60%|█████▉    | 457/765 [04:18<02:28,  2.08it/s]

[457/765]  raw='fail'  →  Fail

 60%|█████▉    | 458/765 [04:19<02:26,  2.10it/s]

[458/765]  raw='fail'  →  Fail

 60%|██████    | 459/765 [04:19<02:22,  2.15it/s]

[459/765]  raw='pass'  →  Pass

 60%|██████    | 460/765 [04:19<02:13,  2.28it/s]

[460/765]  raw='pass'  →  Pass

 60%|██████    | 461/765 [04:20<02:22,  2.13it/s]

[461/765]  raw='fail'  →  Fail

 60%|██████    | 462/765 [04:20<02:30,  2.02it/s]

[462/765]  raw='fail'  →  Fail

 61%|██████    | 463/765 [04:21<02:20,  2.14it/s]

[463/765]  raw='pass'  →  Pass

 61%|██████    | 464/765 [04:21<02:17,  2.19it/s]

[464/765]  raw='fail'  →  Fail

 61%|██████    | 465/765 [04:22<02:21,  2.12it/s]

[465/765]  raw='fail'  →  Fail

 61%|██████    | 466/765 [04:22<02:16,  2.19it/s]

[466/765]  raw='pass'  →  Pass

 61%|██████    | 467/765 [04:23<02:15,  2.19it/s]

[467/765]  raw='pass'  →  Pass

 61%|██████    | 468/765 [04:23<02:16,  2.18it/s]

[468/765]  raw='pass'  →  Pass

 61%|██████▏   | 469/765 [04:24<02:14,  2.19it/s]

[469/765]  raw='pass'  →  Pass

 61%|██████▏   | 470/765 [04:24<02:24,  2.05it/s]

[470/765]  raw='pass'  →  Pass

 62%|██████▏   | 471/765 [04:25<02:18,  2.12it/s]

[471/765]  raw='pass'  →  Pass

 62%|██████▏   | 472/765 [04:25<02:12,  2.21it/s]

[472/765]  raw='fail'  →  Fail

 62%|██████▏   | 473/765 [04:25<02:09,  2.25it/s]

[473/765]  raw='pass'  →  Pass

 62%|██████▏   | 474/765 [04:26<02:10,  2.24it/s]

[474/765]  raw='fail'  →  Fail

 62%|██████▏   | 475/765 [04:26<02:10,  2.23it/s]

[475/765]  raw='pass'  →  Pass

 62%|██████▏   | 476/765 [04:27<02:09,  2.23it/s]

[476/765]  raw='pass'  →  Pass

 62%|██████▏   | 477/765 [04:27<02:14,  2.14it/s]

[477/765]  raw='pass'  →  Pass

 62%|██████▏   | 478/765 [04:28<02:07,  2.24it/s]

[478/765]  raw='pass'  →  Pass

 63%|██████▎   | 479/765 [04:28<02:10,  2.20it/s]

[479/765]  raw='pass'  →  Pass

 63%|██████▎   | 480/765 [04:29<02:11,  2.16it/s]

[480/765]  raw='pass'  →  Pass

 63%|██████▎   | 481/765 [04:29<02:15,  2.10it/s]

[481/765]  raw='pass'  →  Pass

 63%|██████▎   | 482/765 [04:30<02:11,  2.16it/s]

[482/765]  raw='pass'  →  Pass

 63%|██████▎   | 483/765 [04:30<02:06,  2.23it/s]

[483/765]  raw='fail'  →  Fail

 63%|██████▎   | 484/765 [04:30<02:05,  2.23it/s]

[484/765]  raw='fail'  →  Fail

 63%|██████▎   | 485/765 [04:31<02:05,  2.22it/s]

[485/765]  raw='pass'  →  Pass

 64%|██████▎   | 486/765 [04:31<02:15,  2.07it/s]

[486/765]  raw='pass'  →  Pass

 64%|██████▎   | 487/765 [04:32<02:07,  2.18it/s]

[487/765]  raw='fail'  →  Fail

 64%|██████▍   | 488/765 [04:32<02:12,  2.10it/s]

[488/765]  raw='pass'  →  Pass

 64%|██████▍   | 489/765 [04:33<02:12,  2.09it/s]

[489/765]  raw='pass'  →  Pass

 64%|██████▍   | 490/765 [04:33<02:18,  1.99it/s]

[490/765]  raw='pass'  →  Pass

 64%|██████▍   | 491/765 [04:34<02:17,  1.99it/s]

[491/765]  raw='pass'  →  Pass

 64%|██████▍   | 492/765 [04:34<02:16,  2.00it/s]

[492/765]  raw='pass'  →  Pass

 64%|██████▍   | 493/765 [04:35<02:14,  2.02it/s]

[493/765]  raw='pass'  →  Pass

 65%|██████▍   | 494/765 [04:35<02:15,  2.00it/s]

[494/765]  raw='pass'  →  Pass

 65%|██████▍   | 495/765 [04:36<02:09,  2.08it/s]

[495/765]  raw='pass'  →  Pass

 65%|██████▍   | 496/765 [04:36<02:07,  2.12it/s]

[496/765]  raw='pass'  →  Pass

 65%|██████▍   | 497/765 [04:37<02:07,  2.10it/s]

[497/765]  raw='fail'  →  Fail

 65%|██████▌   | 498/765 [04:37<02:07,  2.09it/s]

[498/765]  raw='pass'  →  Pass

 65%|██████▌   | 499/765 [04:38<02:09,  2.06it/s]

[499/765]  raw='pass'  →  Pass

 65%|██████▌   | 500/765 [04:38<02:04,  2.13it/s]

[500/765]  raw='pass'  →  Pass

 65%|██████▌   | 501/765 [04:39<02:00,  2.19it/s]

[501/765]  raw='fail'  →  Fail

 66%|██████▌   | 502/765 [04:39<01:59,  2.19it/s]

[502/765]  raw='fail'  →  Fail

 66%|██████▌   | 503/765 [04:40<02:03,  2.13it/s]

[503/765]  raw='pass'  →  Pass

 66%|██████▌   | 504/765 [04:40<02:01,  2.16it/s]

[504/765]  raw='fail'  →  Fail

 66%|██████▌   | 505/765 [04:40<01:54,  2.28it/s]

[505/765]  raw='pass'  →  Pass

 66%|██████▌   | 506/765 [04:41<01:50,  2.35it/s]

[506/765]  raw='fail'  →  Fail

 66%|██████▋   | 507/765 [04:41<01:50,  2.33it/s]

[507/765]  raw='fail'  →  Fail

 66%|██████▋   | 508/765 [04:42<01:58,  2.18it/s]

[508/765]  raw='pass'  →  Pass

 67%|██████▋   | 509/765 [04:42<02:04,  2.06it/s]

[509/765]  raw='pass'  →  Pass

 67%|██████▋   | 510/765 [04:43<01:59,  2.13it/s]

[510/765]  raw='pass'  →  Pass

 67%|██████▋   | 511/765 [04:43<02:07,  1.99it/s]

[511/765]  raw='pass'  →  Pass

 67%|██████▋   | 512/765 [04:44<02:09,  1.96it/s]

[512/765]  raw='pass'  →  Pass

 67%|██████▋   | 513/765 [04:44<02:08,  1.96it/s]

[513/765]  raw='fail'  →  Fail

 67%|██████▋   | 514/765 [04:45<02:03,  2.03it/s]

[514/765]  raw='pass'  →  Pass

 67%|██████▋   | 515/765 [04:45<02:03,  2.03it/s]

[515/765]  raw='pass'  →  Pass

 67%|██████▋   | 516/765 [04:46<02:12,  1.89it/s]

[516/765]  raw='pass'  →  Pass

 68%|██████▊   | 517/765 [04:46<02:04,  1.99it/s]

[517/765]  raw='fail'  →  Fail

 68%|██████▊   | 518/765 [04:47<02:04,  1.98it/s]

[518/765]  raw='pass'  →  Pass

 68%|██████▊   | 519/765 [04:47<02:01,  2.02it/s]

[519/765]  raw='fail'  →  Fail

 68%|██████▊   | 520/765 [04:48<02:02,  2.00it/s]

[520/765]  raw='pass'  →  Pass

 68%|██████▊   | 521/765 [04:48<02:06,  1.93it/s]

[521/765]  raw='pass'  →  Pass

 68%|██████▊   | 522/765 [04:49<01:58,  2.05it/s]

[522/765]  raw='pass'  →  Pass

 68%|██████▊   | 523/765 [04:49<01:53,  2.14it/s]

[523/765]  raw='pass'  →  Pass

 68%|██████▊   | 524/765 [04:50<01:51,  2.17it/s]

[524/765]  raw='pass'  →  Pass

 69%|██████▊   | 525/765 [04:50<02:04,  1.93it/s]

[525/765]  raw='pass'  →  Pass

 69%|██████▉   | 526/765 [04:51<02:00,  1.98it/s]

[526/765]  raw='pass'  →  Pass

 69%|██████▉   | 527/765 [04:51<01:52,  2.12it/s]

[527/765]  raw='fail'  →  Fail

 69%|██████▉   | 528/765 [04:52<01:53,  2.08it/s]

[528/765]  raw='pass'  →  Pass

 69%|██████▉   | 529/765 [04:52<01:48,  2.17it/s]

[529/765]  raw='fail'  →  Fail

 69%|██████▉   | 530/765 [04:53<01:44,  2.24it/s]

[530/765]  raw='fail'  →  Fail

 69%|██████▉   | 531/765 [04:53<01:41,  2.32it/s]

[531/765]  raw='pass'  →  Pass

 70%|██████▉   | 532/765 [04:53<01:38,  2.36it/s]

[532/765]  raw='pass'  →  Pass

 70%|██████▉   | 533/765 [04:54<01:40,  2.31it/s]

[533/765]  raw='pass'  →  Pass

 70%|██████▉   | 534/765 [04:54<01:47,  2.15it/s]

[534/765]  raw='fail'  →  Fail

 70%|██████▉   | 535/765 [04:55<01:50,  2.09it/s]

[535/765]  raw='pass'  →  Pass

 70%|███████   | 536/765 [04:55<01:50,  2.07it/s]

[536/765]  raw='pass'  →  Pass

 70%|███████   | 537/765 [04:56<01:47,  2.12it/s]

[537/765]  raw='pass'  →  Pass

 70%|███████   | 538/765 [04:56<01:40,  2.25it/s]

[538/765]  raw='fail'  →  Fail

 70%|███████   | 539/765 [04:57<01:46,  2.12it/s]

[539/765]  raw='pass'  →  Pass

 71%|███████   | 540/765 [04:57<01:48,  2.07it/s]

[540/765]  raw='pass'  →  Pass

 71%|███████   | 541/765 [04:58<01:47,  2.09it/s]

[541/765]  raw='pass'  →  Pass

 71%|███████   | 542/765 [04:58<01:50,  2.02it/s]

[542/765]  raw='pass'  →  Pass

 71%|███████   | 543/765 [04:59<01:55,  1.92it/s]

[543/765]  raw='pass'  →  Pass

 71%|███████   | 544/765 [04:59<01:54,  1.93it/s]

[544/765]  raw='pass'  →  Pass

 71%|███████   | 545/765 [05:00<01:52,  1.96it/s]

[545/765]  raw='pass'  →  Pass

 71%|███████▏  | 546/765 [05:00<01:49,  2.01it/s]

[546/765]  raw='fail'  →  Fail

 72%|███████▏  | 547/765 [05:01<01:42,  2.12it/s]

[547/765]  raw='fail'  →  Fail

 72%|███████▏  | 548/765 [05:01<01:52,  1.93it/s]

[548/765]  raw='pass'  →  Pass

 72%|███████▏  | 549/765 [05:02<01:49,  1.98it/s]

[549/765]  raw='fail'  →  Fail

 72%|███████▏  | 550/765 [05:02<01:48,  1.99it/s]

[550/765]  raw='pass'  →  Pass

 72%|███████▏  | 551/765 [05:03<01:44,  2.05it/s]

[551/765]  raw='pass'  →  Pass

 72%|███████▏  | 552/765 [05:03<01:40,  2.13it/s]

[552/765]  raw='pass'  →  Pass

 72%|███████▏  | 553/765 [05:04<01:40,  2.11it/s]

[553/765]  raw='fail'  →  Fail

 72%|███████▏  | 554/765 [05:04<01:43,  2.03it/s]

[554/765]  raw='fail'  →  Fail

 73%|███████▎  | 555/765 [05:05<01:44,  2.01it/s]

[555/765]  raw='pass'  →  Pass

 73%|███████▎  | 556/765 [05:05<01:48,  1.93it/s]

[556/765]  raw='fail'  →  Fail

 73%|███████▎  | 557/765 [05:06<01:49,  1.90it/s]

[557/765]  raw='pass'  →  Pass

 73%|███████▎  | 558/765 [05:06<01:43,  2.00it/s]

[558/765]  raw='pass'  →  Pass

 73%|███████▎  | 559/765 [05:07<01:43,  1.99it/s]

[559/765]  raw='pass'  →  Pass

 73%|███████▎  | 560/765 [05:07<01:43,  1.99it/s]

[560/765]  raw='pass'  →  Pass

 73%|███████▎  | 561/765 [05:08<01:47,  1.89it/s]

[561/765]  raw='pass'  →  Pass

 73%|███████▎  | 562/765 [05:08<01:44,  1.95it/s]

[562/765]  raw='pass'  →  Pass

 74%|███████▎  | 563/765 [05:09<01:40,  2.01it/s]

[563/765]  raw='fail'  →  Fail

 74%|███████▎  | 564/765 [05:09<01:33,  2.15it/s]

[564/765]  raw='pass'  →  Pass

 74%|███████▍  | 565/765 [05:10<01:36,  2.07it/s]

[565/765]  raw='pass'  →  Pass

 74%|███████▍  | 566/765 [05:10<01:38,  2.03it/s]

[566/765]  raw='fail'  →  Fail

 74%|███████▍  | 567/765 [05:11<01:38,  2.01it/s]

[567/765]  raw='pass'  →  Pass

 74%|███████▍  | 568/765 [05:11<01:42,  1.91it/s]

[568/765]  raw='pass'  →  Pass

 74%|███████▍  | 569/765 [05:12<01:35,  2.06it/s]

[569/765]  raw='fail'  →  Fail

 75%|███████▍  | 570/765 [05:12<01:30,  2.15it/s]

[570/765]  raw='pass'  →  Pass

 75%|███████▍  | 571/765 [05:13<01:29,  2.17it/s]

[571/765]  raw='fail'  →  Fail

 75%|███████▍  | 572/765 [05:13<01:30,  2.13it/s]

[572/765]  raw='pass'  →  Pass

 75%|███████▍  | 573/765 [05:14<01:29,  2.14it/s]

[573/765]  raw='pass'  →  Pass

 75%|███████▌  | 574/765 [05:14<01:32,  2.06it/s]

[574/765]  raw='pass'  →  Pass

 75%|███████▌  | 575/765 [05:15<01:31,  2.07it/s]

[575/765]  raw='pass'  →  Pass

 75%|███████▌  | 576/765 [05:15<01:33,  2.02it/s]

[576/765]  raw='pass'  →  Pass

 75%|███████▌  | 577/765 [05:16<01:30,  2.07it/s]

[577/765]  raw='pass'  →  Pass

 76%|███████▌  | 578/765 [05:16<01:25,  2.20it/s]

[578/765]  raw='fail'  →  Fail

 76%|███████▌  | 579/765 [05:16<01:26,  2.16it/s]

[579/765]  raw='pass'  →  Pass

 76%|███████▌  | 580/765 [05:17<01:28,  2.10it/s]

[580/765]  raw='pass'  →  Pass

 76%|███████▌  | 581/765 [05:17<01:25,  2.15it/s]

[581/765]  raw='pass'  →  Pass

 76%|███████▌  | 582/765 [05:18<01:26,  2.11it/s]

[582/765]  raw='fail'  →  Fail

 76%|███████▌  | 583/765 [05:18<01:23,  2.17it/s]

[583/765]  raw='fail'  →  Fail

 76%|███████▋  | 584/765 [05:19<01:28,  2.05it/s]

[584/765]  raw='pass'  →  Pass

 76%|███████▋  | 585/765 [05:19<01:33,  1.93it/s]

[585/765]  raw='pass'  →  Pass

 77%|███████▋  | 586/765 [05:20<01:30,  1.98it/s]

[586/765]  raw='pass'  →  Pass

 77%|███████▋  | 587/765 [05:20<01:25,  2.07it/s]

[587/765]  raw='fail'  →  Fail

 77%|███████▋  | 588/765 [05:21<01:22,  2.15it/s]

[588/765]  raw='pass'  →  Pass

 77%|███████▋  | 589/765 [05:21<01:22,  2.12it/s]

[589/765]  raw='pass'  →  Pass

 77%|███████▋  | 590/765 [05:22<01:18,  2.24it/s]

[590/765]  raw='pass'  →  Pass

 77%|███████▋  | 591/765 [05:22<01:15,  2.30it/s]

[591/765]  raw='pass'  →  Pass

 77%|███████▋  | 592/765 [05:22<01:13,  2.35it/s]

[592/765]  raw='pass'  →  Pass

 78%|███████▊  | 593/765 [05:23<01:10,  2.44it/s]

[593/765]  raw='pass'  →  Pass

 78%|███████▊  | 594/765 [05:23<01:11,  2.40it/s]

[594/765]  raw='fail'  →  Fail

 78%|███████▊  | 595/765 [05:24<01:17,  2.20it/s]

[595/765]  raw='pass'  →  Pass

 78%|███████▊  | 596/765 [05:24<01:29,  1.89it/s]

[596/765]  raw='pass'  →  Pass

 78%|███████▊  | 597/765 [05:25<01:31,  1.84it/s]

[597/765]  raw='pass'  →  Pass

 78%|███████▊  | 598/765 [05:26<01:27,  1.90it/s]

[598/765]  raw='pass'  →  Pass

 78%|███████▊  | 599/765 [05:26<01:26,  1.92it/s]

[599/765]  raw='pass'  →  Pass

 78%|███████▊  | 600/765 [05:26<01:19,  2.07it/s]

[600/765]  raw='pass'  →  Pass

 79%|███████▊  | 601/765 [05:27<01:16,  2.15it/s]

[601/765]  raw='fail'  →  Fail

 79%|███████▊  | 602/765 [05:27<01:19,  2.05it/s]

[602/765]  raw='pass'  →  Pass

 79%|███████▉  | 603/765 [05:28<01:23,  1.94it/s]

[603/765]  raw='pass'  →  Pass

 79%|███████▉  | 604/765 [05:28<01:21,  1.98it/s]

[604/765]  raw='pass'  →  Pass

 79%|███████▉  | 605/765 [05:29<01:22,  1.95it/s]

[605/765]  raw='pass'  →  Pass

 79%|███████▉  | 606/765 [05:29<01:17,  2.06it/s]

[606/765]  raw='fail'  →  Fail

 79%|███████▉  | 607/765 [05:30<01:16,  2.07it/s]

[607/765]  raw='pass'  →  Pass

 79%|███████▉  | 608/765 [05:31<01:21,  1.93it/s]

[608/765]  raw='pass'  →  Pass

 80%|███████▉  | 609/765 [05:31<01:19,  1.97it/s]

[609/765]  raw='pass'  →  Pass

 80%|███████▉  | 610/765 [05:32<01:19,  1.95it/s]

[610/765]  raw='pass'  →  Pass

 80%|███████▉  | 611/765 [05:32<01:20,  1.91it/s]

[611/765]  raw='pass'  →  Pass

 80%|████████  | 612/765 [05:33<01:18,  1.96it/s]

[612/765]  raw='fail'  →  Fail

 80%|████████  | 613/765 [05:33<01:18,  1.94it/s]

[613/765]  raw='fail'  →  Fail

 80%|████████  | 614/765 [05:34<01:15,  1.99it/s]

[614/765]  raw='pass'  →  Pass

 80%|████████  | 615/765 [05:34<01:11,  2.10it/s]

[615/765]  raw='fail'  →  Fail

 81%|████████  | 616/765 [05:34<01:09,  2.14it/s]

[616/765]  raw='fail'  →  Fail

 81%|████████  | 617/765 [05:35<01:05,  2.25it/s]

[617/765]  raw='pass'  →  Pass

 81%|████████  | 618/765 [05:35<01:04,  2.28it/s]

[618/765]  raw='pass'  →  Pass

 81%|████████  | 619/765 [05:36<01:01,  2.36it/s]

[619/765]  raw='pass'  →  Pass

 81%|████████  | 620/765 [05:36<01:04,  2.24it/s]

[620/765]  raw='pass'  →  Pass

 81%|████████  | 621/765 [05:37<01:12,  1.99it/s]

[621/765]  raw='pass'  →  Pass

 81%|████████▏ | 622/765 [05:37<01:15,  1.90it/s]

[622/765]  raw='pass'  →  Pass

 81%|████████▏ | 623/765 [05:38<01:13,  1.94it/s]

[623/765]  raw='pass'  →  Pass

 82%|████████▏ | 624/765 [05:38<01:11,  1.96it/s]

[624/765]  raw='pass'  →  Pass

 82%|████████▏ | 625/765 [05:39<01:05,  2.15it/s]

[625/765]  raw='pass'  →  Pass

 82%|████████▏ | 626/765 [05:39<01:00,  2.29it/s]

[626/765]  raw='fail'  →  Fail

 82%|████████▏ | 627/765 [05:40<01:00,  2.26it/s]

[627/765]  raw='pass'  →  Pass

 82%|████████▏ | 628/765 [05:40<01:03,  2.15it/s]

[628/765]  raw='pass'  →  Pass

 82%|████████▏ | 629/765 [05:40<01:02,  2.17it/s]

[629/765]  raw='pass'  →  Pass

 82%|████████▏ | 630/765 [05:41<01:07,  2.01it/s]

[630/765]  raw='pass'  →  Pass

 82%|████████▏ | 631/765 [05:42<01:17,  1.72it/s]

[631/765]  raw='fail'  →  Fail

 83%|████████▎ | 632/765 [05:42<01:13,  1.80it/s]

[632/765]  raw='pass'  →  Pass

 83%|████████▎ | 633/765 [05:43<01:15,  1.76it/s]

[633/765]  raw='pass'  →  Pass

 83%|████████▎ | 634/765 [05:43<01:12,  1.82it/s]

[634/765]  raw='pass'  →  Pass

 83%|████████▎ | 635/765 [05:44<01:08,  1.89it/s]

[635/765]  raw='pass'  →  Pass

 83%|████████▎ | 636/765 [05:44<01:09,  1.87it/s]

[636/765]  raw='pass'  →  Pass

 83%|████████▎ | 637/765 [05:45<01:09,  1.84it/s]

[637/765]  raw='pass'  →  Pass

 83%|████████▎ | 638/765 [05:46<01:07,  1.88it/s]

[638/765]  raw='pass'  →  Pass

 84%|████████▎ | 639/765 [05:46<01:03,  1.98it/s]

[639/765]  raw='fail'  →  Fail

 84%|████████▎ | 640/765 [05:46<01:01,  2.03it/s]

[640/765]  raw='pass'  →  Pass

 84%|████████▍ | 641/765 [05:47<00:59,  2.08it/s]

[641/765]  raw='fail'  →  Fail

 84%|████████▍ | 642/765 [05:48<01:05,  1.87it/s]

[642/765]  raw='pass'  →  Pass

 84%|████████▍ | 643/765 [05:48<01:03,  1.93it/s]

[643/765]  raw='pass'  →  Pass

 84%|████████▍ | 644/765 [05:48<00:59,  2.04it/s]

[644/765]  raw='fail'  →  Fail

 84%|████████▍ | 645/765 [05:49<00:54,  2.20it/s]

[645/765]  raw='fail'  →  Fail

 84%|████████▍ | 646/765 [05:49<00:57,  2.07it/s]

[646/765]  raw='pass'  →  Pass

 85%|████████▍ | 647/765 [05:50<01:02,  1.89it/s]

[647/765]  raw='pass'  →  Pass

 85%|████████▍ | 648/765 [05:51<01:02,  1.88it/s]

[648/765]  raw='pass'  →  Pass

 85%|████████▍ | 649/765 [05:51<00:58,  1.98it/s]

[649/765]  raw='pass'  →  Pass

 85%|████████▍ | 650/765 [05:52<00:58,  1.96it/s]

[650/765]  raw='fail'  →  Fail

 85%|████████▌ | 651/765 [05:52<00:55,  2.06it/s]

[651/765]  raw='pass'  →  Pass

 85%|████████▌ | 652/765 [05:52<00:52,  2.17it/s]

[652/765]  raw='fail'  →  Fail

 85%|████████▌ | 653/765 [05:53<00:51,  2.19it/s]

[653/765]  raw='pass'  →  Pass

 85%|████████▌ | 654/765 [05:53<00:51,  2.15it/s]

[654/765]  raw='pass'  →  Pass

 86%|████████▌ | 655/765 [05:54<00:52,  2.09it/s]

[655/765]  raw='fail'  →  Fail

 86%|████████▌ | 656/765 [05:54<00:49,  2.19it/s]

[656/765]  raw='fail'  →  Fail

 86%|████████▌ | 657/765 [05:55<00:49,  2.19it/s]

[657/765]  raw='fail'  →  Fail

 86%|████████▌ | 658/765 [05:55<00:47,  2.26it/s]

[658/765]  raw='fail'  →  Fail

 86%|████████▌ | 659/765 [05:55<00:45,  2.35it/s]

[659/765]  raw='fail'  →  Fail

 86%|████████▋ | 660/765 [05:56<00:44,  2.37it/s]

[660/765]  raw='fail'  →  Fail

 86%|████████▋ | 661/765 [05:56<00:48,  2.13it/s]

[661/765]  raw='pass'  →  Pass

 87%|████████▋ | 662/765 [05:57<00:51,  2.01it/s]

[662/765]  raw='pass'  →  Pass

 87%|████████▋ | 663/765 [05:57<00:49,  2.07it/s]

[663/765]  raw='pass'  →  Pass

 87%|████████▋ | 664/765 [05:58<00:48,  2.06it/s]

[664/765]  raw='pass'  →  Pass

 87%|████████▋ | 665/765 [05:58<00:47,  2.12it/s]

[665/765]  raw='fail'  →  Fail

 87%|████████▋ | 666/765 [05:59<00:48,  2.02it/s]

[666/765]  raw='pass'  →  Pass

 87%|████████▋ | 667/765 [05:59<00:46,  2.12it/s]

[667/765]  raw='pass'  →  Pass

 87%|████████▋ | 668/765 [06:00<00:46,  2.09it/s]

[668/765]  raw='pass'  →  Pass

 87%|████████▋ | 669/765 [06:00<00:47,  2.01it/s]

[669/765]  raw='pass'  →  Pass

 88%|████████▊ | 670/765 [06:01<00:48,  1.95it/s]

[670/765]  raw='pass'  →  Pass

 88%|████████▊ | 671/765 [06:02<00:51,  1.81it/s]

[671/765]  raw='fail'  →  Fail

 88%|████████▊ | 672/765 [06:02<00:51,  1.80it/s]

[672/765]  raw='pass'  →  Pass

 88%|████████▊ | 673/765 [06:03<00:48,  1.91it/s]

[673/765]  raw='fail'  →  Fail

 88%|████████▊ | 674/765 [06:03<00:49,  1.85it/s]

[674/765]  raw='pass'  →  Pass

 88%|████████▊ | 675/765 [06:04<00:46,  1.94it/s]

[675/765]  raw='fail'  →  Fail

 88%|████████▊ | 676/765 [06:04<00:45,  1.97it/s]

[676/765]  raw='fail'  →  Fail

 88%|████████▊ | 677/765 [06:05<00:43,  2.04it/s]

[677/765]  raw='fail'  →  Fail

 89%|████████▊ | 678/765 [06:05<00:40,  2.13it/s]

[678/765]  raw='pass'  →  Pass

 89%|████████▉ | 679/765 [06:06<00:41,  2.08it/s]

[679/765]  raw='pass'  →  Pass

 89%|████████▉ | 680/765 [06:06<00:41,  2.04it/s]

[680/765]  raw='pass'  →  Pass

 89%|████████▉ | 681/765 [06:07<00:41,  2.01it/s]

[681/765]  raw='pass'  →  Pass

 89%|████████▉ | 682/765 [06:07<00:41,  1.99it/s]

[682/765]  raw='fail'  →  Fail

 89%|████████▉ | 683/765 [06:08<00:40,  2.03it/s]

[683/765]  raw='pass'  →  Pass

 89%|████████▉ | 684/765 [06:08<00:40,  2.01it/s]

[684/765]  raw='pass'  →  Pass

 90%|████████▉ | 685/765 [06:09<00:40,  2.00it/s]

[685/765]  raw='pass'  →  Pass

 90%|████████▉ | 686/765 [06:09<00:38,  2.08it/s]

[686/765]  raw='pass'  →  Pass

 90%|████████▉ | 687/765 [06:09<00:38,  2.03it/s]

[687/765]  raw='pass'  →  Pass

 90%|████████▉ | 688/765 [06:10<00:37,  2.07it/s]

[688/765]  raw='fail'  →  Fail

 90%|█████████ | 689/765 [06:10<00:37,  2.02it/s]

[689/765]  raw='pass'  →  Pass

 90%|█████████ | 690/765 [06:11<00:36,  2.05it/s]

[690/765]  raw='pass'  →  Pass

 90%|█████████ | 691/765 [06:11<00:34,  2.13it/s]

[691/765]  raw='pass'  →  Pass

 90%|█████████ | 692/765 [06:12<00:32,  2.21it/s]

[692/765]  raw='pass'  →  Pass

 91%|█████████ | 693/765 [06:12<00:35,  2.00it/s]

[693/765]  raw='pass'  →  Pass

 91%|█████████ | 694/765 [06:13<00:34,  2.06it/s]

[694/765]  raw='pass'  →  Pass

 91%|█████████ | 695/765 [06:13<00:33,  2.10it/s]

[695/765]  raw='fail'  →  Fail

 91%|█████████ | 696/765 [06:14<00:32,  2.14it/s]

[696/765]  raw='pass'  →  Pass

 91%|█████████ | 697/765 [06:14<00:33,  2.06it/s]

[697/765]  raw='pass'  →  Pass

 91%|█████████ | 698/765 [06:15<00:31,  2.13it/s]

[698/765]  raw='pass'  →  Pass

 91%|█████████▏| 699/765 [06:15<00:30,  2.18it/s]

[699/765]  raw='fail'  →  Fail

 92%|█████████▏| 700/765 [06:16<00:29,  2.23it/s]

[700/765]  raw='fail'  →  Fail

 92%|█████████▏| 701/765 [06:16<00:28,  2.25it/s]

[701/765]  raw='pass'  →  Pass

 92%|█████████▏| 702/765 [06:16<00:27,  2.31it/s]

[702/765]  raw='fail'  →  Fail

 92%|█████████▏| 703/765 [06:17<00:27,  2.29it/s]

[703/765]  raw='pass'  →  Pass

 92%|█████████▏| 704/765 [06:17<00:26,  2.30it/s]

[704/765]  raw='pass'  →  Pass

 92%|█████████▏| 705/765 [06:18<00:25,  2.32it/s]

[705/765]  raw='pass'  →  Pass

 92%|█████████▏| 706/765 [06:18<00:24,  2.37it/s]

[706/765]  raw='fail'  →  Fail

 92%|█████████▏| 707/765 [06:19<00:27,  2.11it/s]

[707/765]  raw='pass'  →  Pass

 93%|█████████▎| 708/765 [06:19<00:26,  2.11it/s]

[708/765]  raw='fail'  →  Fail

 93%|█████████▎| 709/765 [06:20<00:25,  2.17it/s]

[709/765]  raw='pass'  →  Pass

 93%|█████████▎| 710/765 [06:20<00:25,  2.12it/s]

[710/765]  raw='pass'  →  Pass

 93%|█████████▎| 711/765 [06:21<00:24,  2.18it/s]

[711/765]  raw='pass'  →  Pass

 93%|█████████▎| 712/765 [06:21<00:24,  2.13it/s]

[712/765]  raw='pass'  →  Pass

 93%|█████████▎| 713/765 [06:22<00:25,  2.02it/s]

[713/765]  raw='pass'  →  Pass

 93%|█████████▎| 714/765 [06:22<00:24,  2.09it/s]

[714/765]  raw='pass'  →  Pass

 93%|█████████▎| 715/765 [06:22<00:22,  2.20it/s]

[715/765]  raw='fail'  →  Fail

 94%|█████████▎| 716/765 [06:23<00:21,  2.29it/s]

[716/765]  raw='pass'  →  Pass

 94%|█████████▎| 717/765 [06:23<00:21,  2.22it/s]

[717/765]  raw='pass'  →  Pass

 94%|█████████▍| 718/765 [06:24<00:21,  2.24it/s]

[718/765]  raw='pass'  →  Pass

 94%|█████████▍| 719/765 [06:24<00:20,  2.23it/s]

[719/765]  raw='pass'  →  Pass

 94%|█████████▍| 720/765 [06:25<00:20,  2.24it/s]

[720/765]  raw='fail'  →  Fail

 94%|█████████▍| 721/765 [06:25<00:20,  2.16it/s]

[721/765]  raw='pass'  →  Pass

 94%|█████████▍| 722/765 [06:26<00:20,  2.09it/s]

[722/765]  raw='fail'  →  Fail

 95%|█████████▍| 723/765 [06:26<00:18,  2.22it/s]

[723/765]  raw='fail'  →  Fail

 95%|█████████▍| 724/765 [06:26<00:17,  2.30it/s]

[724/765]  raw='pass'  →  Pass

 95%|█████████▍| 725/765 [06:27<00:16,  2.37it/s]

[725/765]  raw='fail'  →  Fail

 95%|█████████▍| 726/765 [06:27<00:17,  2.27it/s]

[726/765]  raw='fail'  →  Fail

 95%|█████████▌| 727/765 [06:28<00:17,  2.22it/s]

[727/765]  raw='pass'  →  Pass

 95%|█████████▌| 728/765 [06:28<00:16,  2.25it/s]

[728/765]  raw='pass'  →  Pass

 95%|█████████▌| 729/765 [06:29<00:16,  2.15it/s]

[729/765]  raw='pass'  →  Pass

 95%|█████████▌| 730/765 [06:29<00:15,  2.22it/s]

[730/765]  raw='pass'  →  Pass

 96%|█████████▌| 731/765 [06:30<00:15,  2.26it/s]

[731/765]  raw='fail'  →  Fail

 96%|█████████▌| 732/765 [06:30<00:16,  2.05it/s]

[732/765]  raw='pass'  →  Pass

 96%|█████████▌| 733/765 [06:31<00:15,  2.09it/s]

[733/765]  raw='pass'  →  Pass

 96%|█████████▌| 734/765 [06:31<00:15,  2.07it/s]

[734/765]  raw='pass'  →  Pass

 96%|█████████▌| 735/765 [06:32<00:14,  2.11it/s]

[735/765]  raw='pass'  →  Pass

 96%|█████████▌| 736/765 [06:32<00:13,  2.15it/s]

[736/765]  raw='fail'  →  Fail

 96%|█████████▋| 737/765 [06:32<00:13,  2.12it/s]

[737/765]  raw='pass'  →  Pass

 96%|█████████▋| 738/765 [06:33<00:12,  2.13it/s]

[738/765]  raw='pass'  →  Pass

 97%|█████████▋| 739/765 [06:33<00:11,  2.25it/s]

[739/765]  raw='fail'  →  Fail

 97%|█████████▋| 740/765 [06:34<00:10,  2.33it/s]

[740/765]  raw='pass'  →  Pass

 97%|█████████▋| 741/765 [06:34<00:10,  2.31it/s]

[741/765]  raw='pass'  →  Pass

 97%|█████████▋| 742/765 [06:35<00:10,  2.28it/s]

[742/765]  raw='pass'  →  Pass

 97%|█████████▋| 743/765 [06:35<00:09,  2.24it/s]

[743/765]  raw='fail'  →  Fail

 97%|█████████▋| 744/765 [06:36<00:09,  2.13it/s]

[744/765]  raw='pass'  →  Pass

 97%|█████████▋| 745/765 [06:36<00:08,  2.25it/s]

[745/765]  raw='pass'  →  Pass

 98%|█████████▊| 746/765 [06:37<00:08,  2.12it/s]

[746/765]  raw='pass'  →  Pass

 98%|█████████▊| 747/765 [06:37<00:08,  2.08it/s]

[747/765]  raw='fail'  →  Fail

 98%|█████████▊| 748/765 [06:38<00:08,  2.06it/s]

[748/765]  raw='fail'  →  Fail

 98%|█████████▊| 749/765 [06:38<00:07,  2.14it/s]

[749/765]  raw='fail'  →  Fail

 98%|█████████▊| 750/765 [06:38<00:06,  2.21it/s]

[750/765]  raw='fail'  →  Fail

 98%|█████████▊| 751/765 [06:39<00:06,  2.26it/s]

[751/765]  raw='pass'  →  Pass

 98%|█████████▊| 752/765 [06:39<00:06,  2.08it/s]

[752/765]  raw='pass'  →  Pass

 98%|█████████▊| 753/765 [06:40<00:05,  2.19it/s]

[753/765]  raw='pass'  →  Pass

 99%|█████████▊| 754/765 [06:40<00:04,  2.20it/s]

[754/765]  raw='fail'  →  Fail

 99%|█████████▊| 755/765 [06:41<00:04,  2.11it/s]

[755/765]  raw='pass'  →  Pass

 99%|█████████▉| 756/765 [06:41<00:04,  2.01it/s]

[756/765]  raw='pass'  →  Pass

 99%|█████████▉| 757/765 [06:42<00:04,  1.99it/s]

[757/765]  raw='fail'  →  Fail

 99%|█████████▉| 758/765 [06:42<00:03,  2.04it/s]

[758/765]  raw='pass'  →  Pass

 99%|█████████▉| 759/765 [06:43<00:03,  1.95it/s]

[759/765]  raw='pass'  →  Pass

 99%|█████████▉| 760/765 [06:43<00:02,  1.96it/s]

[760/765]  raw='pass'  →  Pass

 99%|█████████▉| 761/765 [06:44<00:02,  1.96it/s]

[761/765]  raw='fail'  →  Fail

100%|█████████▉| 762/765 [06:44<00:01,  2.00it/s]

[762/765]  raw='fail'  →  Fail

100%|█████████▉| 763/765 [06:45<00:01,  1.89it/s]

[763/765]  raw='pass'  →  Pass

100%|█████████▉| 764/765 [06:45<00:00,  1.90it/s]

[764/765]  raw='pass'  →  Pass

100%|██████████| 765/765 [06:46<00:00,  1.88it/s]

[765/765]  raw='pass'  →  Pass

In [ ]:
results_df = pd.DataFrame({
    "y_true"    : y_true,
    "y_pred"    : y_pred,
    "generated" : y_generated,
})
results_df["y_true_label"] = results_df["y_true"].map({1: "Pass", 0: "Fail"})
results_df["y_pred_label"] = results_df["y_pred"].map({1: "Pass", 0: "Fail", -1: "???"})
print(results_df.to_string())

valid_mask   = [i for i, p in enumerate(y_pred) if p != -1]
y_true_valid = y_true[valid_mask]
y_pred_valid = [y_pred[i] for i in valid_mask]

print(f"\nParsed      : {len(valid_mask)}/{len(y_pred)}")
print(f"Unparseable : {len(y_pred) - len(valid_mask)}")

if y_pred_valid:
    print(f"\nAccuracy : {accuracy_score(y_true_valid, y_pred_valid):.4f}")
    print(classification_report(
        y_true_valid, y_pred_valid,
        labels=[0, 1], target_names=["Fail", "Pass"], zero_division=0
    ))
    cm = confusion_matrix(y_true_valid, y_pred_valid, labels=[0, 1])
    print("Confusion Matrix (rows=true, cols=pred):")
    print("           Fail  Pass")
    for label, row in zip(["Fail", "Pass"], cm):
        print(f"True {label:<5}: {row}")

     y_true  y_pred generated y_true_label y_pred_label
0         0       1      pass         Fail         Pass
1         0       1      pass         Fail         Pass
2         0       1      pass         Fail         Pass
3         1       1      pass         Pass         Pass
4         0       1      pass         Fail         Pass
5         0       1      pass         Fail         Pass
6         1       1      pass         Pass         Pass
7         1       1      pass         Pass         Pass
8         1       1      pass         Pass         Pass
9         0       1      pass         Fail         Pass
10        0       0      fail         Fail         Fail
11        1       1      pass         Pass         Pass
12        1       1      pass         Pass         Pass
13        1       1      pass         Pass         Pass
14        1       1      pass         Pass         Pass
15        1       1      pass         Pass         Pass
16        1       1      pass         Pass         Pass
17        1       1      pass         Pass         Pass
18        0       1      pass         Fail         Pass
19        0       1      pass         Fail         Pass
20        0       0      fail         Fail         Fail
21        0       0      fail         Fail         Fail
22        0       1      pass         Fail         Pass
23        1       1      pass         Pass         Pass
24        1       1      pass         Pass         Pass
25        1       1      pass         Pass         Pass
26        0       1      pass         Fail         Pass
27        1       1      pass         Pass         Pass
28        1       1      pass         Pass         Pass
29        0       0      fail         Fail         Fail
30        1       1      pass         Pass         Pass
31        0       1      pass         Fail         Pass
32        1       1      pass         Pass         Pass
33        0       1      pass         Fail         Pass
34        0       0      fail         Fail         Fail
35        1       1      pass         Pass         Pass
36        1       1      pass         Pass         Pass
37        0       1      pass         Fail         Pass
38        1       1      pass         Pass         Pass
39        1       1      pass         Pass         Pass
40        1       1      pass         Pass         Pass
41        0       0      fail         Fail         Fail
42        0       0      fail         Fail         Fail
43        1       1      pass         Pass         Pass
44        0       1      pass         Fail         Pass
45        0       0      fail         Fail         Fail
46        0       0      fail         Fail         Fail
47        1       1      pass         Pass         Pass
48        0       0      fail         Fail         Fail
49        1       1      pass         Pass         Pass
50        0       1      pass         Fail         Pass
51        0       1      pass         Fail         Pass
52        1       1      pass         Pass         Pass
53        1       1      pass         Pass         Pass
54        0       1      pass         Fail         Pass
55        0       1      pass         Fail         Pass
56        0       1      pass         Fail         Pass
57        0       1      pass         Fail         Pass
58        0       1      pass         Fail         Pass
59        0       0      fail         Fail         Fail
60        1       1      pass         Pass         Pass
61        0       1      pass         Fail         Pass
62        1       1      pass         Pass         Pass
63        0       0      fail         Fail         Fail
64        0       0      fail         Fail         Fail
65        1       1      pass         Pass         Pass
66        1       1      pass         Pass         Pass
67        0       0      fail         Fail         Fail
68        1       1      pass         Pass         Pass
69        0       1      pass         Fail         Pass
70        0       1      pass         Fail         Pass
71        0       0      fail         Fail         Fail
72        0       1      pass         Fail         Pass
73        0       0      fail         Fail         Fail
74        0       0      fail         Fail         Fail
75        1       1      pass         Pass         Pass
76        0       1      pass         Fail         Pass
77        1       1      pass         Pass         Pass
78        0       1      pass         Fail         Pass
79        1       1      pass         Pass         Pass
80        1       1      pass         Pass         Pass
81        1       1      pass         Pass         Pass
82        1       1      pass         Pass         Pass
83        1       1      pass         Pass         Pass
84        0       0      fail         Fail         Fail
85        0       1      pass         Fail         Pass
86        0       1      pass         Fail         Pass
87        0       1      pass         Fail         Pass
88        1       1      pass         Pass         Pass
89        0       1      pass         Fail         Pass
90        1       1      pass         Pass         Pass
91        1       1      pass         Pass         Pass
92        1       0      fail         Pass         Fail
93        0       0      fail         Fail         Fail
94        0       0      fail         Fail         Fail
95        0       1      pass         Fail         Pass
96        0       0      fail         Fail         Fail
97        0       0      fail         Fail         Fail
98        0       0      fail         Fail         Fail
99        0       0      fail         Fail         Fail
100       0       1      pass         Fail         Pass
101       0       1      pass         Fail         Pass
102       0       1      pass         Fail         Pass
103       0       1      pass         Fail         Pass
104       0       1      pass         Fail         Pass
105       1       1      pass         Pass         Pass
106       1       1      pass         Pass         Pass
107       0       0      fail         Fail         Fail
108       1       1      pass         Pass         Pass
109       0       1      pass         Fail         Pass
110       0       1      pass         Fail         Pass
111       0       1      pass         Fail         Pass
112       1       1      pass         Pass         Pass
113       0       1      pass         Fail         Pass
114       0       1      pass         Fail         Pass
115       0       1      pass         Fail         Pass
116       1       1      pass         Pass         Pass
117       1       1      pass         Pass         Pass
118       0       1      pass         Fail         Pass
119       1       0      fail         Pass         Fail
120       1       1      pass         Pass         Pass
121       1       1      pass         Pass         Pass
122       1       1      pass         Pass         Pass
123       1       1      pass         Pass         Pass
124       0       1      pass         Fail         Pass
125       0       1      pass         Fail         Pass
126       0       1      pass         Fail         Pass
127       0       1      pass         Fail         Pass
128       0       0      fail         Fail         Fail
129       1       1      pass         Pass         Pass
130       0       1      pass         Fail         Pass
131       0       1      pass         Fail         Pass
132       0       1      pass         Fail         Pass
133       0       0      fail         Fail         Fail
134       0       1      pass         Fail         Pass
135       0       1      pass         Fail         Pass
136       1       1      pass         Pass         Pass
137       1       0      fail         Pass         Fail
138       1       1      pass         Pass         Pass
139       0       0      fail         Fail         Fail
140       0       0      fail         Fail         Fail
141       0       0      fail         Fail         Fail
142       1       0      fail         Pass         Fail
143       1       1      pass         Pass         Pass
144       0       1      pass         Fail         Pass
145       1       0      fail         Pass         Fail
146       1       1      pass         Pass         Pass
147       1       1      pass         Pass         Pass
148       1       1      pass         Pass         Pass
149       0       0      fail         Fail         Fail
150       1       1      pass         Pass         Pass
151       0       1      pass         Fail         Pass
152       1       1      pass         Pass         Pass
153       0       1      pass         Fail         Pass
154       0       1      pass         Fail         Pass
155       1       1      pass         Pass         Pass
156       0       0      fail         Fail         Fail
157       1       1      pass         Pass         Pass
158       1       1      pass         Pass         Pass
159       1       1      pass         Pass         Pass
160       0       1      pass         Fail         Pass
161       0       1      pass         Fail         Pass
162       0       1      pass         Fail         Pass
163       1       1      pass         Pass         Pass
164       0       0      fail         Fail         Fail
165       0       0      fail         Fail         Fail
166       0       0      fail         Fail         Fail
167       0       0      fail         Fail         Fail
168       1       1      pass         Pass         Pass
169       1       1      pass         Pass         Pass
170       1       1      pass         Pass         Pass
171       1       1      pass         Pass         Pass
172       1       1      pass         Pass         Pass
173       1       1      pass         Pass         Pass
174       0       1      pass         Fail         Pass
175       0       1      pass         Fail         Pass
176       0       0      fail         Fail         Fail
177       0       0      fail         Fail         Fail
178       1       1      pass         Pass         Pass
179       0       1      pass         Fail         Pass
180       0       1      pass         Fail         Pass
181       0       0      fail         Fail         Fail
182       0       1      pass         Fail         Pass
183       0       0      fail         Fail         Fail
184       1       1      pass         Pass         Pass
185       1       1      pass         Pass         Pass
186       0       0      fail         Fail         Fail
187       0       0      fail         Fail         Fail
188       1       1      pass         Pass         Pass
189       1       1      pass         Pass         Pass
190       0       0      fail         Fail         Fail
191       1       1      pass         Pass         Pass
192       0       1      pass         Fail         Pass
193       0       0      fail         Fail         Fail
194       1       1      pass         Pass         Pass
195       0       1      pass         Fail         Pass
196       1       1      pass         Pass         Pass
197       0       1      pass         Fail         Pass
198       1       1      pass         Pass         Pass
199       0       0      fail         Fail         Fail
200       0       1      pass         Fail         Pass
201       1       1      pass         Pass         Pass
202       0       0      fail         Fail         Fail
203       1       1      pass         Pass         Pass
204       0       0      fail         Fail         Fail
205       0       1      pass         Fail         Pass
206       1       1      pass         Pass         Pass
207       0       1      pass         Fail         Pass
208       0       0      fail         Fail         Fail
209       0       1      pass         Fail         Pass
210       0       0      fail         Fail         Fail
211       0       1      pass         Fail         Pass
212       1       1      pass         Pass         Pass
213       0       1      pass         Fail         Pass
214       0       1      pass         Fail         Pass
215       0       0      fail         Fail         Fail
216       0       0      fail         Fail         Fail
217       1       1      pass         Pass         Pass
218       1       1      pass         Pass         Pass
219       0       1      pass         Fail         Pass
220       0       1      pass         Fail         Pass
221       0       0      fail         Fail         Fail
222       1       0      fail         Pass         Fail
223       1       1      pass         Pass         Pass
224       0       0      fail         Fail         Fail
225       1       1      pass         Pass         Pass
226       0       1      pass         Fail         Pass
227       0       1      pass         Fail         Pass
228       0       0      fail         Fail         Fail
229       0       1      pass         Fail         Pass
230       1       1      pass         Pass         Pass
231       1       0      fail         Pass         Fail
232       0       0      fail         Fail         Fail
233       0       1      pass         Fail         Pass
234       1       1      pass         Pass         Pass
235       0       0      fail         Fail         Fail
236       0       1      pass         Fail         Pass
237       0       1      pass         Fail         Pass
238       1       1      pass         Pass         Pass
239       0       1      pass         Fail         Pass
240       0       1      pass         Fail         Pass
241       0       1      pass         Fail         Pass
242       0       1      pass         Fail         Pass
243       0       1      pass         Fail         Pass
244       0       1      pass         Fail         Pass
245       1       1      pass         Pass         Pass
246       1       1      pass         Pass         Pass
247       0       0      fail         Fail         Fail
248       1       0      fail         Pass         Fail
249       0       1      pass         Fail         Pass
250       0       0      fail         Fail         Fail
251       1       1      pass         Pass         Pass
252       1       0      fail         Pass         Fail
253       0       0      fail         Fail         Fail
254       1       1      pass         Pass         Pass
255       0       1      pass         Fail         Pass
256       1       1      pass         Pass         Pass
257       0       0      fail         Fail         Fail
258       0       1      pass         Fail         Pass
259       1       1      pass         Pass         Pass
260       0       1      pass         Fail         Pass
261       1       1      pass         Pass         Pass
262       1       1      pass         Pass         Pass
263       0       0      fail         Fail         Fail
264       1       1      pass         Pass         Pass
265       1       1      pass         Pass         Pass
266       1       1      pass         Pass         Pass
267       1       1      pass         Pass         Pass
268       1       1      pass         Pass         Pass
269       0       1      pass         Fail         Pass
270       0       1      pass         Fail         Pass
271       1       1      pass         Pass         Pass
272       0       1      pass         Fail         Pass
273       1       1      pass         Pass         Pass
274       1       1      pass         Pass         Pass
275       0       0      fail         Fail         Fail
276       0       0      fail         Fail         Fail
277       0       0      fail         Fail         Fail
278       1       1      pass         Pass         Pass
279       0       0      fail         Fail         Fail
280       1       1      pass         Pass         Pass
281       0       0      fail         Fail         Fail
282       1       1      pass         Pass         Pass
283       0       1      pass         Fail         Pass
284       0       0      fail         Fail         Fail
285       1       0      fail         Pass         Fail
286       0       1      pass         Fail         Pass
287       1       1      pass         Pass         Pass
288       0       1      pass         Fail         Pass
289       0       0      fail         Fail         Fail
290       0       1      pass         Fail         Pass
291       0       0      fail         Fail         Fail
292       1       1      pass         Pass         Pass
293       1       1      pass         Pass         Pass
294       0       0      fail         Fail         Fail
295       1       1      pass         Pass         Pass
296       1       1      pass         Pass         Pass
297       1       1      pass         Pass         Pass
298       1       1      pass         Pass         Pass
299       0       1      pass         Fail         Pass
300       0       1      pass         Fail         Pass
301       0       0      fail         Fail         Fail
302       1       1      pass         Pass         Pass
303       0       1      pass         Fail         Pass
304       0       1      pass         Fail         Pass
305       0       0      fail         Fail         Fail
306       0       1      pass         Fail         Pass
307       0       1      pass         Fail         Pass
308       1       0      fail         Pass         Fail
309       0       1      pass         Fail         Pass
310       0       1      pass         Fail         Pass
311       0       1      pass         Fail         Pass
312       1       1      pass         Pass         Pass
313       1       1      pass         Pass         Pass
314       0       1      pass         Fail         Pass
315       0       1      pass         Fail         Pass
316       0       1      pass         Fail         Pass
317       0       0      fail         Fail         Fail
318       1       1      pass         Pass         Pass
319       0       0      fail         Fail         Fail
320       0       1      pass         Fail         Pass
321       0       1      pass         Fail         Pass
322       0       0      fail         Fail         Fail
323       0       1      pass         Fail         Pass
324       1       1      pass         Pass         Pass
325       1       1      pass         Pass         Pass
326       0       1      pass         Fail         Pass
327       1       1      pass         Pass         Pass
328       0       1      pass         Fail         Pass
329       1       1      pass         Pass         Pass
330       0       0      fail         Fail         Fail
331       0       1      pass         Fail         Pass
332       0       1      pass         Fail         Pass
333       0       1      pass         Fail         Pass
334       0       1      pass         Fail         Pass
335       0       0      fail         Fail         Fail
336       1       1      pass         Pass         Pass
337       0       1      pass         Fail         Pass
338       1       1      pass         Pass         Pass
339       1       1      pass         Pass         Pass
340       1       1      pass         Pass         Pass
341       1       1      pass         Pass         Pass
342       1       1      pass         Pass         Pass
343       1       1      pass         Pass         Pass
344       1       1      pass         Pass         Pass
345       1       1      pass         Pass         Pass
346       0       1      pass         Fail         Pass
347       1       0      fail         Pass         Fail
348       0       0      fail         Fail         Fail
349       0       0      fail         Fail         Fail
350       0       1      pass         Fail         Pass
351       1       1      pass         Pass         Pass
352       0       1      pass         Fail         Pass
353       0       1      pass         Fail         Pass
354       1       1      pass         Pass         Pass
355       0       1      pass         Fail         Pass

In [ ]:
!ollama list

NAME               ID              SIZE      MODIFIED
qwen2.5:7b         845dbda0ea48    4.7 GB    About an hour ago
llama3.2:latest    a80c4f17acd5    2.0 GB    About an hour ago